dotnet/project-system

build.cmd
=> Fix spelling mistake in build.cmd

src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.pkgdef, src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj
This is just a temporary workaround to get F5 working until we completely auto-generate this as part of: https://github.com/dotnet/roslyn/issues/10253
=> Replace macros with real values in pkgdef

netci.groovy
Support for this was added in https://github.com/dotnet/dotnet-ci/pull/277
=> Use Utilities.SetMachineAffinity instead of setting label

src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj, src/ProjectSystemSetup/ProjectSystemSetup.csproj, src/ProjectSystemSetup/source.extension.vsixmanifest
This was preventing F5 from picking up the new changes to it.
=> Include pkgdef's in VSIX

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/CSharpProjectSystemPackage.cs, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.csproj, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/VSPackage.resx, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.csproj, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/VSPackage.resx, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/VisualBasicProjectSystemPackage.cs, src/ProjectSystemSetup/ProjectSystemSetup.csproj, src/ProjectSystemSetup/source.extension.vsixmanifest
We need to start to refer to localized strings in the project factory registeration which requires a package.
=> Added C# and Visual Basic project system packages

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/CSharpProjectSystemPackage.cs, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/GlobalSuppressions.cs, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.csproj, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/CSharpProjectCapabilityProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/VSPackage.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PreferedProjectFactoryRegistrationAttribute.cs, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/GlobalSuppressions.cs, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.csproj, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/VisualBasicProjectCapabilityProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/VSPackage.resx, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/VisualBasicProjectSystemPackage.cs
We now handle non-flavored csproj/vbproj by default. We'll add some smarts soon to only opt into projects that we actually support.
=> Opts the new project system into csproj/vbproj

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/GlobalSuppressions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/LanguageServiceErrorListProvider.cs
=> Fix code analysis warnings

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Shell/HierarchyIdTests.cs
=> Add unit tests for HierarchyId

src/ProjectSystem.sln, src/Targets/Microsoft.CSharp.Designer.targets, src/Targets/Microsoft.VisualBasic.Designer.targets
These targets will end up containing all things related to designer scenarios, include properties that drive Solution Explorer and VS behavior, project rules (properties, items, etc).
=> Added new "designer targets"

build/Nuget/Microsoft.VisualStudio.ProjectSystem.VSInsertion.nuspec, src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj, src/ProjectSystemSetup/ProjectSystemSetup.csproj
Add the missing pkgdef and vsixmanifest files to the nuget package
=> Include pkgdef and vsixmanifest as part of Nuget

CONTRIBUTING.md, docs/repo/Debugging Tips.md, docs/repo/Getting Started.md
Added a page on diagnosing design-time builds.
=> Add info about design-time builds

docs/well-known-project-properties.md
=> Fixed RunPostBuildEvent description

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectThreadingServiceFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IOptionsSettingsFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/SVsServiceProviderFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/OptionsSettingsTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/OptionsSettings.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/RoslynServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UserNotificationServices.cs
=> Adding a check to make sure certain API's are being called from UI thread.

.gitignore
=>  Ignored C++ IntelliSense cache file

docs/design-time-builds.md, docs/well-known-project-properties.md
Wrote a document talking about design-time builds both for the existing and new project system.
=> Documented design-time builds

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IRoslynServicesFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IUserNotificationServicesFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/RenamerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Renamer.cs
=> Rename file should rename matching all symbols in the file.

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerView.vb, src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerWindowPane.vb, src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/PropertyPageInfo.vb, src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/SpecialFileCustomView.vb, src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/SpecialFileCustomViewProvider.vb, src/Microsoft.VisualStudio.AppDesigner/Common/DTEUtils.vb, src/Microsoft.VisualStudio.AppDesigner/Common/ShellUtil.vb, src/Microsoft.VisualStudio.AppDesigner/Common/Utils.vb, src/Microsoft.VisualStudio.AppDesigner/DesignerFramework/DesignUtil.vb, src/Microsoft.VisualStudio.AppDesigner/DesignerFramework/DesignerMessageBox.vb, src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/ConfigurationState.vb, src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerView.vb, src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerWindowPane.vb, src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropertyPageSerializationService_Store.vb, src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPage.vb, src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPageHostDialog.vb, src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPageUserControlBase.vb, src/Microsoft.VisualStudio.AppDesigner/PropPages/PropertyControlData.vb, src/Microsoft.VisualStudio.AppDesigner/PropPages/PropertyListener.vb, src/Microsoft.VisualStudio.Editors/Common/Utils.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsDesignerView.vb
See https://github.com/dotnet/roslyn-project-system/pull/274 for more context.
=> Log exceptions as telemetry for AppDesigner

netci.groovy
Tagging @tannergooding @dotnet/project-system for review
=> Prefer CI machines with VS 15 Preview 3 from Preview 2

src/Targets/Microsoft.CSharp.DesignTime.targets, src/Targets/Microsoft.VisualBasic.DesignTime.targets
Update design time targets to look in the current folder for XAML files by default
=> Update design time targets

docs/design-time-builds.md
tag @dotnet/project-system 
FYI @hughbe
=> Add perf and error info to design-time build doc

src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/Packaging/VisualBasicProjectSystemPackage.cs, src/ProjectSystemDogfoodSetup/Dogfood.pkgdef
This is likely to cause a few as-yet undiscovered issues.
@davkean @dotnet/project-system
=> Changed the VB project id to be different from the CSharp project id

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/InterceptedProjectProperties/LocalDebuggerCommandArgumentsProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/LocalDebuggerCommandArgumentsValueProvider.cs
@dotnet/project-system @333fred
=> Quote the name of the exectuable passed to F5 

src/VisualStudioEditorsSetup/source.extension.vsixmanifest
The ShortcuPath will be the probing path for the binaries to be looked into for Ngen-ing
@brettfo @dotnet/project-system for review
=> Add the Probing path as ShortcutPath for Ngening Editors

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
=> Add temporary workaround to prevent data sources failure dialog

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/VSPackage.resx
=> Add resources for Netstandard Class library templates

src/ProjectSystemDogfoodSetup/Dogfood.pkgdef
The keys changed, fix them so that we opt into csproj for F5.
=> Fix dogfood VSIX to opt into project system

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/IJsonSection.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchSettingsSerializationProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
I had defined the serialization providers incorrectly. Verified this new definition works correctly.
=> Fix serialization Providers

build/Targets/References.targets, src/Dependencies/VisualStudio/project.json, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProvider.cs
@dotnet/project-system @abpiskunov
=> Add filtering of the dependencies node based on a capbility

src/Dependencies/CPS/project.json, src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/TargetFrameworkProjectConfigurationDimensionProvider.cs
TODO: Add unit tests (we need to merge this PR ASAP to unblock further work)
=> Add target framework dimension provider

src/Targets/Microsoft.Managed.DesignTime.targets
Adds PackageReferences capability to the managed projects
For review @dotnet/project-system @srivatsn
=> Add PackageReferences capability

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProvider.cs
=> Simplify Tasks.Task -> Task and remove TplExtensions.CompletedTask usage

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependencyNodeIdTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyNodeId.cs
FYI Minor bug fix @dotnet/project-system
=> Fix bug in DependencyNodeId, make GetHashCode to be case insensitive

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
=> Properties full path check

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs
This workaround will removed and tracked by #514
=> Unblock guid parse error for dogfooding

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/ProcessRunner.cs
Tagging @dotnet/project-system @srivatsn for review.
=> Fixed process wrapper to call the right async method.

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectInstancePropertiesProviderFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/ImplicitProjectPropertiesProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/DebugTests/StartupProjectRegistrarTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/DelegatedProjectPropertiesProviderBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/ImplicitProjectPropertiesProvider.cs
=> Handle IProjectInstancePropertiesProvider overrides to access implicit properties properly

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UserNotificationServices.cs
This is to solve #408 
@adrianvmsft
=> Condition added not to show dialogue window in case of UIAutomation.

build/Targets/References.targets, src/Microsoft.VisualStudio.AppDesigner/Common/ShellUtil.vb, src/Microsoft.VisualStudio.Editors/Common/ShellUtil.vb
=> Remove unneeded VSDesigner.WCF dependency

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependenciesSubTreeProviderBaseTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/NuGetDependenciesSubTreeProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesSubTreeProviderBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyNode.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyNodeId.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/NuGetDependenciesSubTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/ProjectDependenciesSubTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/ProjectDependencyNode.cs
In progress: 
- still adding unit tests for changes
@dotnet/project-system 
Fixes #663 and #412
=> Fix issue 663 project nodes always yellow and 412 dependencies nodes visibly slow to show

src/VsixV3/ProjectSystemPackage/Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.swixproj, src/VsixV3/ProjectSystemPackage/Microsoft.VisualStudio.ProjectSystem.Managed.swixproj
Remove hard-coded version for Editors V3
@srivatsn @dotnet/project-system for review
=> Update the version of the v3 vsixes

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectLockFileWatcher.cs
Notify Project Lock File changes across configured projects for each TFM matching the current active configuration.
Fixes #672, #682 
Related: #692 
/cc @dotnet/project-system @lifengl
=> Notify Project Lock File changes across configured projects for each TFM

src/VsixV3/EditorsPackage/Microsoft.VisualStudio.Editors.swixproj, src/VsixV3/EditorsPackage/Microsoft.VisualStudio.Editors.swr, src/VsixV3/EditorsPackage/Microsoft.VisualStudio.Editors.vsmanproj
@srivatsn @natidea @dotnet/project-system for review
=> Move UseVisualStudioVersion property to affect the BuildVersion

src/Targets/Microsoft.CSharp.DesignTime.targets, src/Targets/Microsoft.VisualBasic.DesignTime.targets
This fixes #606. @dotnet/project-system @basoundr for review.
=> Use the shared project AddItemTemplatesGuid for shared projects.

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/SimpleRenameStrategy.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx
fixes #599 
New message looks like
=> Extracting the code element name from the filepath

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
fixes #389 
new 
old 
Properties are now same as old csproj , but i see that the old but the Heading looks different. 
It's Misc in old and General in new.
=> Hide properties from Project browse object

build/Targets/VSL.Imports.targets, src/Microsoft.VisualStudio.Editors/PropPages/TargetFrameworkMoniker.vb, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/TargetFrameworkMonikerValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/project.json
Filed #795 to get rid of hardcoded list below
=> Display target framework in application property page

build.cmd
- Update build.cmd to reflect VS 2017 changes
- Write build fail and success in color
- Update build.cmd help to reflect changes
=> Update Build.cmd to reflect new VS and options

src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/AdditionalFiles.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/AdditionalFiles.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ProjectItemsSchema.xaml, src/Targets/Microsoft.Managed.DesignTime.targets, src/VsixV3/ProjectSystemPackage/Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.swr
=> Add support for "AdditionalFiles" build action item type

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
fixes #416 and #417
@davkean @srivatsn @dotnet/project-system
=> Enabling CheckForOverflowUnderflow and removing configuration label

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
Simple change to import ISourceCodeControlIntegration with ImportMany
@srivatsn @333fred
=> Fix for https://github.com/dotnet/roslyn-project-system/issues/748

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Utilities/TaskDelaySchedulerTests.cs
The test assumed the inner task would not ever be run. But of course, task scheduling is not deterministic so tweaked the code to handle both cases
@srivatsn @333fred
=> https://github.com/dotnet/roslyn-project-system/issues/699

src/Microsoft.VisualStudio.Editors/PropPages/WPF/ApplicationPropPageVBWPF.vb, src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeParser/ProjectTreeParser.MutableProjectTree.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PropertyPages/TestPropertyProviders.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectDebuggerProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyNode.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyNodeId.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/NuGetDependenciesSubTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/FocusAttacher.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
- Use C# 7.0 pattern matching
- Remove unneeded type
=> Use C# 7.0 pattern matching

src/VisualStudioEditorsSetup/VisualStudioEditorsSetup.csproj
Following the recommended from VSSDK documentation.
@tannergooding @srivatsn @dotnet/project-system for review
=> Remove the NgenApplication property

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Editor/MsBuildModelWatcherTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Editor/MsBuildModelWatcher.cs
Merging my change from dev15-rc2 into master. Tagging @dotnet/project-system. Tagging @MattGertz for ask mode approval.
=> Merge dev15 rc2

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectCapabilitiesScopeFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/References/ReferenceContextProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/AddFileContextProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/AssemblyReferenceContextProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/BaseReferenceContextProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/ComReferencesProviderContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/ProjectReferencesProviderContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/SharedProjectReferencesProviderContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/WinRTReferencesProviderContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs, src/Targets/Microsoft.Managed.DesignTime.targets
This allows consumers of the project system to opt out for #399 and #400
=> Expose extensibility points for opting out of tabs in the reference manager

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchProfileDataTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchProfileTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Collections/DictionaryEqualityComparer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfile.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/DictionaryEqualityComparer.cs
Move DictionaryEqualityComparer to our coding style
Move DictionaryEqualityComparer -> collections namespace
Internalize DictionaryEqualityComparer
tag @dotnet/project-system
=> Move DictionaryEqualityComparer and internalize

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/VSPackage.resx
=> Adding resource string for class library (.net core)

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
=> Reroute property for LangVersion

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependenciesGraphProjectContextProviderFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependencyNodeFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IGraphContextFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectCatalogSnapshotFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectChangeDescriptionFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectChangeDiffFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectRuleSnapshotFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectSubscriptionUpdateFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PropertyPages/DebugPageViewModelTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesSubTreeProviderBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SubTreeRootDependencyNode.cs
Dogfooding the analyzer/fix all.
=> Use null-coalescing operator

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Reload/ProjectReloadManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs
tag @dotnet/project-system @BillHiebert
=> Use CPS constant for the HandlesOwnReload capability

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProvider.cs
Fixes 
- https://github.com/dotnet/roslyn-project-system/issues/810
- https://github.com/dotnet/roslyn-project-system/issues/837
=> Fix Scope To This issue for Dependencies tree nodes and flacky test

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/EnvironmentGridTemplateColumn.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/WatermarkTextBox.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/AddFileContextProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/AssemblyReferenceContextProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/BaseReferenceContextProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/ComReferencesProviderContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/ProjectReferencesProviderContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/SharedProjectReferencesProviderContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/WinRTReferencesProviderContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/Converters.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/ObservableList.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/DataFlowExtensions/DataFlowExtensionMethodCaller.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/DataFlowExtensions/DataFlowExtensionMethodWrapper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/DataFlowExtensions/IDataFlowExtensionWrapper.cs
if the types need not be public
@srivatsn @dotnet/project-system for review
=> Modify public types to internal types

src/Microsoft.VisualStudio.Editors/XmlIntellisense/XmlIntellisense.vb, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectDebuggerProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectDebuggerProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Reload/ProjectReloadManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/UnconfiguredProjectContextProvider.cs
This reverts commit 48f9d5451e36cf481ab257d58dc7c6e7c5289071, reversing
changes made to f685806746bda2a33df15c7d845e0e055032c7c3.
It's a breaking change, so we're going to take it at a better time.
=> Revert "Merge pull request #993 from davkean/Async"

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IPhysicalProjectTreeStorageFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PhysicalProjectTreeStorageTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PhysicalProjectTreeTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IPhysicalProjectTree.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PhysicalProjectTree.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PhysicalProjectTreeStorage.cs
=> Added IPhysicalProjectTreeStorage to IPhysicalProjectTree

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/EditAndContinue/EditAndContinueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/AggregateWorkspaceProjectContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ILanguageServiceHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs, src/Targets/Microsoft.Managed.DesignTime.targets
This EditAndContinueProvider is just a proxy which redirects the call for EnC to the language service.
@srivatsn @tmat @dotnet/project-system for review
=> Add Edit and Continue support

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ActiveConfiguredProjectFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PhysicalProjectTreeStorageTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UnconfiguredProjectCommonServicesTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/DebugTests/StartupProjectRegistrarTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PropertyPages/BuildMacroInfoTests.cs
To match the name of the thing it's mocking.
This makes it easier to find.
=> Rename mock IActiveConfiguredProjectFactory

src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/FuncWithOut.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/Moq/ReturnsExtensions.cs
- Fix mocking method with out parameter returned no result
- Add ability to mock methods with two out params
=> Fix mocking method with out parameter returned no result

src/Dependencies/Roslyn/project.json, src/DeployTestDependencies/project.json, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IWorkspaceProjectContextFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/SourceItemHandlerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/SourceItemHandler.cs
=> Ensure that we use rooted paths for adding/removing source files.

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ProjectContextCodeModelProvider.cs
Fixes: #924.
When calling the legacy project system on a background thread, COM marshalling used to marshal it back to the UI thread - because CPS is free-threaded, we have to explictly do this ourselves.
Roslyn and the CreateAggregatedObject wrapper that they are using are not free-threaded.
=> Always retrieve code model from UI thread

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerView.vb
To avoid confusing with fields.
=> Use "camelCasing" for parameters

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/AdditionalFiles.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/CSharp.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Content.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/EmbeddedResource.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/None.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/VisualBasic.xaml
@dsplaisted @srivatsn @dotnet/project-system for review
Fixes #1043
=> Add Link as Attribute rather than metadata

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/EditProjectFileCommandTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Input/CommandGroup.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Input/VisualStudioStandard2kCommandId.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Menus.vsct, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/EditProjectFileCommand.cs
This addresses #761. Tagging @dotnet/project-system @davkean for review.
=> Moved the edit project file command to use the existing command

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ProjectHostProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/UnconfiguredProjectHostObject.cs
- Use IUnconfiguredProjectVsServices instead of HostObject
- Also inlined initialization and removed an unneeded Requires (it would null ref before it was called).
=> Use IUnconfiguredProjectVsServices instead of HostObject

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/VSPackage.resx
part to fix https://github.com/dotnet/sdk/issues/556
corresponding template change https://github.com/dotnet/sdk/pull/584
=> Adding Description for .Net Core Class Library

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Xproj/MigrateXprojProjectFactoryTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/AbstractAddClassProjectCommandTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/EditProjectFileCommandTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependencyNodeTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/ProjectDependenciesSubTreeProviderTests.cs
Tagging @nguerrera @dotnet/project-system for review.
=> Fixed loc bugs in tests. Fixes #1085

src/Targets/Microsoft.Managed.DesignTime.targets
@dotnet/project-system @davkean @BillHiebert @jviau
=> Add capability to show actual file type icons for nested items instead of generic one

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.cs.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.de.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.es.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.fr.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.it.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.ja.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.ko.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.pl.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.pt-BR.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.ru.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.tr.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.zh-Hans.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.zh-Hant.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.zh-Hant.xlf
@srivatsn @dotnet/project-system
=> Update xlf (and conversion back to resx) following 4979164bd

build/Targets/VSL.Imports.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj
@srivatsn @dotnet/project-system
=> Localize VSCT content

.github/PULL_REQUEST_TEMPLATE.md
I've added the pr request template Roslyn uses so we don't have to keep looking up the template every time we submit a pr. Tagging @dotnet/project-system @srivatsn for review.
=> Added pull request template for convencience

src/Dependencies/MSBuild/project.json, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Reload/ReloadableProject.cs, src/NuGet.config
Consumes the new msbuild feature: [https://github.com/Microsoft/msbuild/pull/1507](https://github.com/Microsoft/msbuild/pull/1507)
=> Remove Reload workaround and use official API (target Dev15-RC3)

src/Microsoft.VisualStudio.AppDesigner/Common/Utils.vb, src/Microsoft.VisualStudio.Editors/Common/Utils.vb
Fixes: https://github.com/dotnet/roslyn-project-system/issues/360.
This is not called through out the product.
=> Remove dead code

src/Microsoft.VisualStudio.Editors/PropPages/xlf/ApplicationPropPage.es.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ApplicationPropPage.fr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ApplicationPropPage.pl.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ApplicationPropPage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.it.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.ko.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.pl.xlf
bugfix for r#1331 (368875,368010,368022,368870,368872, 368881)
=> LOC CHECKIN | dotnet/roslyn-project-system | 20170125 | bugfix

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs
Adding a new profile, (or removing an existing one) doesn't work correctly., The profile is added but is not reflected in the dropdown so if you switch to another profile, say to copy some common option, there is no way to switch back.  
https://github.com/dotnet/roslyn-project-system/issues/1263
Save the settings and then close and re-open the property pages
**Risk**
Very low risk. The SourceItems on the dropdown control needs to be bound to an obvservable collection rather than a list. The change to support this is very small.
None. No extra code is run.
From RC.2. The change to make the property pages extensible broke this scenario.
**Root cause …
=> Adding a new launch profile doesn't work correctly.

docs/repo/Debugging Tips.md
=> Add Capabilities section

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralConfiguredBrowseObject.xaml
@srivatsn @jinujoseph. I'll fill out the template when we're satisfied.
=> Set browse object properties to be visible=false to fix caching issues.

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/cs/GeneralBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/cs/GeneralConfiguredBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/de/GeneralBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/de/GeneralConfiguredBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/es/GeneralBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/es/GeneralConfiguredBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/fr/GeneralBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/fr/GeneralConfiguredBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/it/GeneralBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/it/GeneralConfiguredBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ja/GeneralBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ja/GeneralConfiguredBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ko/GeneralBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ko/GeneralConfiguredBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pl/GeneralBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pl/GeneralConfiguredBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pt-BR/GeneralBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pt-BR/GeneralConfiguredBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ru/GeneralBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ru/GeneralConfiguredBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ru/ResolvedSdkReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/tr/GeneralBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/tr/GeneralConfiguredBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hans/GeneralBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hans/GeneralConfiguredBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hant/GeneralBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hant/GeneralConfiguredBrowseObject.xaml
See #1472, the changes did not apply to languages other then English so all of those issues would remain for non-English VS users
Same as #1472, but for all non-English languages.
None
**Risk**
Low
None
No
The loc process for these files currently requires a manual step due to lack of resources and late onboarding of new loc process with no pre-baked tooling we could use. We are planning to automate everything for next cycle in partnership with central engineering team. Sri and I had been doing a good job pointing out when the tool had to be re-run but missed it on this PR.
I saw a CHS only bug report …
=> Update loc xaml

src/Microsoft.VisualStudio.Editors/PropPages/AssemblyInfoPropPage.cs.resx, src/Microsoft.VisualStudio.Editors/PropPages/AssemblyInfoPropPage.tr.resx
This is the required step after approved loc team xlf change #1475 
@srivatsn
=> Run xlf converter following loc handback

netci.groovy
1. explicitly setting the 'refspec' in order to locate the PR content. re:line-208
2. moving the Rosyln-Internal commit-pointer forward. re:line-236
3. *trivial* modifying comments and formatting.
Testing:
https://ci.dot.net/job/dotnet_roslyn-project-system/job/master/job/vsi_prtest/6/
=> Modifying Roslyn-Project-System Jenkin's groovy file:

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractSpecialFileProvider.cs
=> Remove unused using

netci.groovy
Modifying Roslyn-Project-System Jenkin's groovy file: 
1. explicitly setting the 'refspec' in order to locate the PR content. line#208+
2. moving the Rosyln-Internal commit-pointer forward. line#236
3. *trivial* modifying comments and formatting
=> Jenkins groovyfile

build/build.proj
This makes it more obvious that they were run.
=> Log when tests passed

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Input/VisualStudioStandard2kCommandId.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs
Ran across these as I was investigating something.
=> Small clean up of the Edit Project File

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/References/DesignTimeAssemblyResolutionTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/SimpleRenamerTests.cs
These tests were duplicated and xUnit was complaining about them.
=> Remove duplicate tests

THIRD-PARTY-NOTICES
- Due to https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/MigrationError.cs#L9
=> Add 3pn entry for dotnet/cli

build/Targets/References.targets, build/Targets/VSL.Versions.targets
This was being used by vsmanproj.
=> Add back MicroBuildVersion

build/build.proj
Master equivalent of https://github.com/dotnet/roslyn-project-system/pull/1685.
Unfortunately, I merged 15.0.1's version based on the wrong tip - so these need to be new commits.
=> Remove unneeded global properties [master]

README.md, docs/repo/Getting Started.md
Master equivalent of https://github.com/dotnet/roslyn-project-system/pull/1688
=> Update docs to reflect VS2017 release [master]

README.md, docs/repo/Getting Started.md
dev15.1.x equivalent of https://github.com/dotnet/roslyn-project-system/pull/1688.
=> Update docs to reflect VS2017 release [dev15.1.x] 

README.md, docs/repo/Getting Started.md
Updated docs to reflect VS2017 release and new branch structure
=> Update docs to reflect VS2017 release [dev15.0.x]

netci.groovy
This is a PR-infrastructure only change. I'll manually merge dev15.0.x into dev15.1.x, and then dev15.1.x into master after this is merged. Tagging @tannergooding for review. @natidea @johnbeisner FYI.
=> Moved the ci and integration tests to the final vs image.

netci.groovy
PR-Infra-only change. Not going to get fooled again, I'll hold off merging until https://github.com/dotnet/roslyn/pull/17628 is merged. Tagging @tannergooding, FYI @natidea.
=> Update dev15 image to match label change.

netci.groovy
=> Merge dev15.0.x into dev15.1.x

netci.groovy
=> Merge Dev15.1.x into master

src/Microsoft.VisualStudio.Editors/MyApplication/MyApplicationProperties.vb, src/Microsoft.VisualStudio.Editors/PropPages/WPF/ApplicationPropPageVBWPF.vb, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/OutputTypeEnumProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/OutputTypeExValueProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/OutputTypeExValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/OutputTypeEnumProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
Fix for #1299 - Change all instances of case insensitive code for OutputType to be case sensitive since checks in the targets are case sensitive.
=> Case sensitive output type

.gitignore
=> Ignore vscode settings from git changes

src/Microsoft.VisualStudio.Editor.UnitTests/Microsoft.VisualStudio.Editors.UnitTests.csproj, src/Microsoft.VisualStudio.Editors.SettingsDesigner.UnitTests/SettingsDesignerUnitTests.vbproj
Cleanup the new tests projects and make my build output clean again.
=> Cleanup test projects

CONTRIBUTING.md
=> Fix links to sub pages in CONTRIBUTING.md

build.cmd, build/Scripts/copyOutput.cmd, build/Targets/VSL.Imports.targets
Also removing microbuild specific properties and introduce switches for the functionalities performed in Official build
@davkean @dotnet/project-system for review
=> Update build cmd to copy artifacts

build.cmd, build/build.proj
- Run tests after tree has built
- Run targets as individuals so that we get a pretty log/order
Before:
```
Restoring packages for ProjectSystem (this may take some time)
Building ProjectSystem [Debug]
Microsoft.VisualStudio.AppDesigner -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.AppDesigner.dll
Microsoft.VisualStudio.ProjectSystem.Managed.TestServices -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.dll
Microsoft.VisualStudio.ProjectSystem.Managed -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.ProjectSystem.Managed.dll
Microsoft.VisualStudio.ProjectSystem.CSharp -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.ProjectSystem.CSharp.dll
Microsoft.VisualStudio.ProjectSystem.VisualBasic -> …
```
=> Run tests after tree has built

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/VSPackage.resx
Fixes #1785 
Also use the correct casing and name of xUnit.
Make note this is a string change, to save everyone updating the strings every time they change them, I'm using https://github.com/dotnet/roslyn-project-system/issues/1794 to track running it once before the localization cut-off.
=> Update xUnit template description

build/Targets/VSL.Versions.targets
=> Nuget Patch Version should start with Numeral

build.cmd, build/Scripts/copyOutput.cmd
- Pass bin directory to CopyOutput.cmd instead of it pulling it from the current environment
- Turn off echo and turn on set local in CopyOutput.cmd to avoid dirtying output, and environment
- Log MSBuild logs to bin\[Config]\Logs
- Stop listing all the log files on success - it's too verbose and really only needed for failure cases. We just log the directory.
Before:
```
Restoring packages for ProjectSystem (this may take some time)
Building ProjectSystem [Debug]
Microsoft.VisualStudio.AppDesigner -> E:\project-system2\bin\Debug\Microsoft.VisualStudio.AppDesigner.dll
Microsoft.VisualStudio.ProjectSystem.Managed.TestServices -> E:\project-system2\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.dll
Microsoft.VisualStudio.ProjectSystem.Managed -> …
```
=> Log MSBuild logs to bin\[Config]\Logs

build.cmd, build/Scripts/copyOutput.cmd
As per feedback: https://github.com/dotnet/roslyn-project-system/pull/1811.
=> Enable turning on echo for scripts

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
Tagging @natidea @abpiskunov @srivatsn for review
Fixes [#1373 (comment)](https://github.com/dotnet/roslyn-project-system/issues/1373#issuecomment-285260349) and TFS bug 393230.
Instead of unsubscribing for provider events in Dispose , do it in ProjectUnloading event and don't process event if current object is Disposing.
Porting this fix from Dev 15.1 to 15.0
Port of https://github.com/dotnet/roslyn-project-system/pull/1732
**Scenario**
During some scenarios (load after migration, initial restore .. other(?)) project is reloaded programmatically and that causes CPS objects do be disposed while they are in progress or doing some stuff. In our case we use a collection of MEF imports that are being disposed and attempt to unsubscribe from their events. When we try to use the collection we …
=> Fix ObjectDisposed exception for dependencies tree

docs/compatibility.md
A work-in-progress that lets us keep track of compatibility/behavioral differences between legacy project system and the new one.
=> Added a compatibility doc

src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/SimpleFileWatcher.cs
Move SimpleFIleWatcher to the IO namespace and format it.
=> Move SimpleFileWatcher to the IO namespace

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VsProject.cs
We can just export this from the object itself.
=> Remove unneeded property

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/FileRenameTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/Renamer.cs
To match the rest of the rename types.
=> Move FileRenameTracker to Rename namespace

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Threading/Tasks/SequencialTaskExecutorTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Threading/Tasks/TaskDelaySchedulerTests.cs
These tests were testing types from another namepace.
=> Move tests to correct namespace

src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPage.resx, src/Microsoft.VisualStudio.Editors/PropPages/DebugPropPage.resx
Resolves VSO Bug 391341 and 391539
=> Fixing a couple of accessibility bugs in the property pages.

src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvancedServicesDialog.cs.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvancedServicesDialog.es.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ServicesPropPage.de.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ServicesPropPage.es.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ServicesPropPage.pl.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ServicesPropPage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ServicesPropPage.ru.xlf
New PR to dev15.3.x as requested
BUGS:
https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=410792
https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=410793
https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=410795
https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=410801https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=410802
https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=410804
=> LOC CHECKIN | project-system | 20170421 | bugfix

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml
This resolves DevDiv VSO Bug 391556.
=> Updating the Debug prop page to set accessibility names.

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/MSBuildXmlAccessor.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/SupportedTargetFrameworksEnumProvider.cs
This fixes a build break introduced in the previous PR (warnings).
=> Fix warnings in previous PR

docs/compatibility.md, docs/configurations.md
=> Add documentation about configurations

src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerWindowPane.vb
This replaces #2061 and resolves VSO Bug 409664.
=> Updating PropPageDesignerWindowPane.PreProcessMessage to not handle Alt+Down

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectConfigurationFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ActiveConfiguredProjectsProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredObjects.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredProjectsProvider.cs
(Preparing to make IActiveConfiguredProjectsProvider public for the VSTest guys)
CPS doesn't expose ImmutableArray in their API. Move to IReadOnlyList<T> to be consistent with them.
=> Use IReadOnlyList instead of ImmutableArray

src/Templates/Microsoft.NetCore.VB.ProjectTemplates.Test/MSTest.vstemplate, src/Templates/Microsoft.NetCore.VB.ProjectTemplates.Test/XUnitTest.vstemplate, src/Templates/Microsoft.NetCore.VB.ProjectTemplates/ClassLibrary.vstemplate, src/Templates/Microsoft.NetStandard.VB.ProjectTemplates/ClassLibrary.vstemplate
Vb class library templates appear with C# icon
**[Bug 429537](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/429537)**
None
**Risk**
None
ad hoc testing
=> updating vb template icon

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractLanguageServiceRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs
- Virtual -> Abstract method
- Fixed comment
=> [LanguageService] Misc changes

docs/repo/working-project-properties.md
Tagging @dotnet/project-system for review
=> Add doc to explain the working of the Project properties

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ActiveConfiguredProjectsProviderTests.cs
Remove duplicate test that xUnit was complaining about.
=> Remove duplicate test

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Logging/ProjectOutputWindowProjectLogger.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Logging/FormatArray.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Logging/IProjectLogger.cs
This is the same as this https://github.com/dotnet/project-system/pull/2142, just merging into a branch before we merge into 15.3.x with other logging PRs.
=> [Logging] Reduce allocations in logger

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectSystemOptionsFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectThreadingServiceMock.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectOutputWindowPaneProviderFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsOutputWindowPaneFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Logging/ProjectOutputWindowProjectLoggerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Logging/ProjectOutputWindowProjectLogger.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Logging/FormatArray.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Logging/IProjectLogger.cs
Note, only the last two commits should be reviewed - as this includes: https://github.com/dotnet/project-system/pull/2263.
=> [Logging] Add logging tests

build/Targets/References.targets
Adding hint paths to unblock signed build
=> Unblock signed builds

build/Targets/References.targets
same as https://github.com/dotnet/project-system/pull/2306 but against master instead of 15.3
=> adding additional hint paths

build/Targets/VSL.Imports.targets
This is a port of https://github.com/dotnet/roslyn/pull/19881
=> Fix the `LinkVSSDKEmbeddableAssemblies` target.

src/Microsoft.VisualStudio.Editors/PropPages/CSharpLanguageVersion.vb, src/Microsoft.VisualStudio.Editors/PropPages/CSharpLanguageVersionUtilities.vb
Preparing 15.6 branch for language features for C# 7.2.
Relates to compiler change https://github.com/dotnet/roslyn/pull/19846
FYI @OmarTawfik
=> Add option for LangVersion 7.2

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/VsOptionalServiceTests.cs
=> Make sure tests are testing right class

netci.groovy
Fixes https://github.com/dotnet/project-system/pull/2441#issuecomment-308590271
=> Updating the groovy script for the non-integration jobs to use the new install location.

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
After installing one of the 15.3 Previews customers will start experiencing more "random" UI delays in normal VS operations including:
- Expanding nodes in Solution Explorer
- Add new and removing items to and from the tree
- Opening C# source files
- Opening XML files
- Typing
- Opening and closing the solution
None
**Risk**
Low. This simply replaces an _async -> synchronous -> async_ call with _async -> async_.
This will reduce UI delays and reduce the number of active threads.
Yes, the dependency …
=> Remove JoinableTaskFactory.Run usage

src/ProjectSystem.sln
Updated the solution description to match repro changes.
=> Update description of solution

build/Targets/References.targets, build/Targets/Settings.targets, build/Targets/VSL.Versions.targets
Infrastructure only change to fix https://github.com/dotnet/project-system/issues/2315
=> Updating our Roslyn dependencies to 2.3.0-beta3-61808-05

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/BuildUpToDateCheck.cs
A user tries to build while a NuGet restore (or some other critical build task) is running in the background. The up to date check currently will block on the UI thread, waiting for the background critical task to complete before returning whether the project is up to date. Since most critical tasks will cause the up to date check to fail, we should instead *not* wait for critical tasks to complete (meaning no UI delays) and just fail the up to date check if such tasks are running.
Fixes #2385 
Go get a cup of coffee.
**Risk**
Low, the major risk would be that we would fail the up to date check when we shouldn't, which would just mean MSBuild will be called when it could be skipped.
Improves …
=> Don't drain critial tasks when doing up to date check

build/Targets/VSL.Versions.targets, src/Common/Integration/App.config, src/DeployIntegrationDependencies/DeployIntegrationDependencies.csproj, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/CSharp/CSharpErrorListTests.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/CSharp/CSharpSquigglesTests.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/VisualBasic/VisualBasicErrorListTests.cs
=> disabling flaky tests

docs/repo/architecture.md
Use different pictures for architecture documentation
=> use different arch pics

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/VsTelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/BuildUpToDateCheck.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/ITelemetryService.cs
This helps us understand how the up to date check is performing in the real world.
#2381 
None
**Risk**
Low, just adding standard telemetry
Low, just adding standard telemetry
No.
=> Up to date check telemetry

src/Microsoft.VisualStudio.AppDesigner/Resources/xlf/Designer.ru.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ApplicationPropPage.ru.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.ru.xlf, src/Microsoft.VisualStudio.Editors/Resources/xlf/Designer.ru.xlf
https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=456084
https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=456087
=> LOC CHECKIN | project-system-master | 20170628 | bugfix

src/Microsoft.VisualStudio.Editors/ResourceEditor/Resource.vb
In a project targeting netstandard2.0 our multi-targeting support would quite correctly tell the ResX designer that System.String came from netstandard.dll. The designer would then try to load netstandard.dll, fail, and crash VS because netstandard.dll isn't part of the desktop 4.6.2 framework used by VS.
To work around this we redirected all types from netstandard.dll to mscorlib.dll. This turned out to be both overly broad and insufficient. Overly broad because System.String is the only type used by the designer that the multi-targeting service is going to redirect. And insufficient because in projects targeting netcoreapp2.0 System.String lives in System.Runtime version 4.0.2.0--and the desktop framework doesn't have that version of System.Runtime. So editing ResX files in these …
=> Always use the loaded System.String in the ResX designer

build/Targets/VSL.Versions.targets
@srivatsn could you please approve
FYI @dotnet/project-system
=> Change versions from 15.6 to 15.5 to reflect the actual product version being targeted in master

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectSystemOptions.cs
This allocates 1.3 MB (0.1%) of data opening ProjectSystem.sln.
=> Cache reading IsProjectOutputPaneEnabled

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ActiveConfiguredProjectsProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Telemetry/VsTelemetryServiceTests.cs
This groups them in Test Explorer.
=> Make tests with a trait

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/MetadataReferenceItemHandler.cs
MetadataReferenceItemHandler wasn't looking at the aliases of the
references to see if they actually were unique before presuming another
add could be ignored. This corrects that oversight.
Fixes dotnet/project-system#2550.
=> Reimplement MetadataReferenceItemHandler to merge aliases

src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/CSharp/CSharpErrorListTests.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/CSharp/CSharpProjectFileEditTest.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/CSharp/CSharpSquigglesTests.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/Utilities/AbstractIntegrationTest.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/VisualBasic/VisualBasicErrorListTests.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/VisualBasic/VisualBasicSquigglesTest.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/WorkspaceTests.cs
=> Blindly port the ProjectFileEdit_NetCore.xml test.

docs/design-time-builds.md
Fixed a typo in ResolveAssemblyReferences
=> Fix ResolveAssemblyReferences typo.

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/DependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/CommonConstants.cs
This was about 0.1% of data allocated opening ProjectSystem.sln.
=> Remove char[] allocations

netci.groovy
FYI. @jmarolf, @Srivatsn, @dotnet/project-system
=> Updating the jenkins machines to 15.3.P7

build/SignToolData.json, build/Versions.props, setup/Directory.Build.targets, setup/Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles/Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.csproj
Willow setup packages were not built and signed properly.
=> Fix Willow setup package builds

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/ProjectRuleSnapshotExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
Simplify the bool check in the up-to-date check.
=> Simplify bool check

build/Versions.props
Fixes MicroBuild package reference, resolves a signing issue.
=> Update to RepoToolset v39

build/Versions.props, src/HostAgnostic.props
Adding analyzers for usage of CPS apis
=> adding project system analyzers

build/Versions.props, src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS/Packaging/FSharpProjectSystemPackage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs
FYI. @dotnet/project-system, @brettfo, @KevinRansom
=>  Updating the FSharpProjectSystemPackage to register the 'SortByDisplayOrder` project capability.

build/Test.ruleset, build/Versions.props, src/HostAgnostic.props, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Xproj/MigrateXprojProjectFactoryTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/AssertEx.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Build/BuildUtilitiesTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ActiveConfiguredProjectsProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Build/TargetFrameworkGlobalBuildPropertyProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/ConfigurationProjectConfigurationDimensionProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/PlatformProjectConfigurationDimensionProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/TargetFrameworkProjectConfigurationDimensionProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchProfileDataTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/MetadataReferenceItemHandlerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/SourceItemHandlerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptedProjectProperties/AssemblyOriginatorKeyFileValueProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/SupportedTargetFrameworksEnumProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/NuGet/ProjectRestoreInfoBuilderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/DependencyModelTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/PackageAnalyzerAssemblyDependencyModelTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/PackageAssemblyDependencyModelTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/PackageDependencyModelTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/PackageUnknownDependencyModelTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependencyExtensionsTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs
This both adds xunit analyzers to the project and fixes the warning they produce.
=> adding xunit analyzers

Directory.Build.props, build/Versions.props, src/Common/Integration/App.config, src/Common/Test/App.config, src/DeployIntegrationDependencies/DeployIntegrationDependencies.csproj, src/DeployTestDependencies/DeployTestDependencies.csproj, src/HostAgnostic.props, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/Microsoft.VisualStudio.ProjectSystem.IntegrationTests.csproj, src/VisualStudio.props, src/VisualStudioDesigner.props
This resolves https://github.com/dotnet/project-system/issues/2307.
This additionally ensures we are referencing the latest versions of our dependencies (or the current version used by VS) to ensure we are consuming the latest APIs, bug fixes, etc.
=> Updating our dependencies.

build/Versions.props
=> Bump NuGet moniker to -beta2

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Order/TreeItemOrderPropertyProviderSource.cs
Fix accidental revert in #2930
=> Fix accidental revert in #2930

src/Templates/Microsoft.NetCore.CSharp.ProjectTemplates.Test/MSTest.vstemplate, src/Templates/Microsoft.NetCore.CSharp.ProjectTemplates.Test/XUnitTest.vstemplate, src/Templates/Microsoft.NetCore.CSharp.ProjectTemplates/ClassLibrary.vstemplate, src/Templates/Microsoft.NetCore.CSharp.ProjectTemplates/ConsoleApplication.vstemplate, src/Templates/Microsoft.NetCore.FSharp.ProjectTemplates.Test/MSTest.vstemplate, src/Templates/Microsoft.NetCore.FSharp.ProjectTemplates.Test/XUnitTest.vstemplate, src/Templates/Microsoft.NetCore.FSharp.ProjectTemplates/ClassLibrary.vstemplate, src/Templates/Microsoft.NetCore.FSharp.ProjectTemplates/ConsoleApplication.vstemplate, src/Templates/Microsoft.NetCore.VB.ProjectTemplates.Test/MSTest.vstemplate, src/Templates/Microsoft.NetCore.VB.ProjectTemplates.Test/XUnitTest.vstemplate, src/Templates/Microsoft.NetCore.VB.ProjectTemplates/ClassLibrary.vstemplate, src/Templates/Microsoft.NetCore.VB.ProjectTemplates/ConsoleApplication.vstemplate, src/Templates/Microsoft.NetStandard.CSharp.ProjectTemplates/ClassLibrary.vstemplate, src/Templates/Microsoft.NetStandard.FSharp.ProjectTemplates/ClassLibrary.vstemplate, src/Templates/Microsoft.NetStandard.VB.ProjectTemplates/ClassLibrary.vstemplate
=> remove RequiredFrameworkVersion

build/Internal/Toolset.csproj
=> Clear RestoreSources in internal toolset proj

build/Versions.props
I hope to start enabling rules and/or fixing violations in subsequent PRs. FYI @jinujoseph
=> Move to latest analyzers package

build/Default.ruleset, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TestDependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/TargetFramework.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Dependency.cs
fixes https://github.com/dotnet/project-system/issues/2979
=> Implement comparison operators

build/Default.ruleset, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Build/MsBuildProjectFile.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/AbstractGenerateNuGetPackageCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/TargetedProjectContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/SimpleFileWatcher.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/DebugTokenReplacer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/DisposableBag.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/SequencialTaskExecutor.cs
fixes https://github.com/dotnet/project-system/issues/2981
=> Implement idisposable correctly

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/TargetFrameworkProvider.cs
- Remove unneeded AppliesTo
- Change TargetFrameworkProvider to follow guidelines
=> Change TargetFrameworkProvider to follow guidelines

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/CodeMarkerTimerId.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/NuGetRestorer.cs
Naming guidelines was complaining about this one.
=> Put constant into own class

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/AssemblyInfoPropertiesProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ContextHandlerProvider.Handlers.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ContextHandlerProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IContextHandlerProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHandlerManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/AssemblyAttributeProperties/AssemblyInfoProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Reload/ProjectReloadInterceptor.cs, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/Automation/VisualBasicVSImports.cs
- Simplify delegate invocation
- Change tuple names -> lower case
This changes it to match as per dotnet/roslyn#23716 (comment).
=> More suggestion cleanup

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Xproj/MigrateXprojProjectFactoryTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/AbstractBuildEventValueProvider.AbstractBuildEventHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/VsTelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/AssemblyAttributeProperties/AssemblyInfoProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/SupportedTargetFrameworksEnumProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Reload/ProjectReloadInterceptor.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
Clean up all the tuple desconstruction messages.
=> Tuple deconstruction

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/ConfigurationProjectConfigurationDimensionProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/PlatformProjectConfigurationDimensionProvider.cs
Note: There's currently a regression on this path unrelated to this: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/540631.
=> Remove unneeded async state machines

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs
=> Don't crash if CommandName is null

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ConfiguredProjectImplicitActivationTrackingTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/EventHandlerExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ConfiguredProjectImplicitActivationTracking.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IConfiguredProjectImplicitActivationTracking.cs
Add ImplicitlyActivated/ImplicitlyDeactivated events to IConfiguredProjectImplicitActivationTracking that let configured-project services react to be activated and deactivated.
=> Activation deactivation

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
When the user builds a .NET Core/.NET Standard project, it is always considered up-to-date and is never rebuilt.
#3050
User has to manually rebuild every time the project changes.
**Risk**
The main risk would be that we somehow have missed an output group registration and the up to date check is still broken in places. However, since we're using the same groups we used before, this seems unlikely.
None, watching the same output groups as before.
Yes. CPS changed how they deal with output groups and it broke the up to date check.
We have a workitem to add integration tests for up to date check. …
=> Watch output groups for up to date check

Directory.Build.props, build/Toolset.proj, build/Versions.props, build/build.ps1
=> Update RepoToolset to 1.0.0-beta-62413-01

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/NuGetRestorer.NuGetRestorerInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/NuGetRestorer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/PackageRestoreInitiator.PackageRestoreInitiatorInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/PackageRestoreInitiator.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AbstractProjectDynamicLoadComponent.AbstractProjectDynamicLoadInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AbstractProjectDynamicLoadComponent.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs
This includes prior open PRs, only review 3484e22.
Review feedback from: https://github.com/dotnet/project-system/pull/3093.
=> Remove async

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IAsyncServiceProviderMoq.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/NuGet/ProjectAssetFileWatcherTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectAssetFileWatcher.cs
Fixes #2708.
<details>**Customer scenario**
**Risk**
(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")
**Is this a regression from a previous …
=> Connect to the tree provider asynchronously.

src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeParser/ProjectTreeParser.MutableProjectItemTree.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeParser/ProjectTreeParser.MutableProjectPropertiesContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeParser/ProjectTreeParser.MutableProjectTree.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeParser/ProjectTreeParser.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/AbstractMoveCommandTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/MoveDownCommandTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/MoveUpCommandTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/OrderingHelperTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Menus.vsct, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/AbstractMoveCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/MoveDownCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/MoveUpCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/OrderingHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.zh-Hant.xlf
This adds move up and move down gestures for F# projects.
Original issue here: https://github.com/dotnet/project-system/issues/2887
=> Added MoveUp/MoveDown commands

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
This addresses the issue described in DEVDIV [553720](https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=553720)
Basically, when first reading the launch settings files in response to dataflow, the AspNetCoreWeb is not present which breaks the launch settings provider which imports custom serializers. This is similar to the other race conditions that been reported recently with capabilities not being present when responding to dataflow. The fix is to include the capabilities dataflow in the project subscription in a manner similar to this [PR](https://github.com/dotnet/project-system/pull/3167).
In addition to the above, I was concerned about capabilities changing even when nothing in the project subscription has changed.  The project rule dataflow …
=> Include capabilities in project subscription dataflow

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf
Port localization translations for 15.6 to 15.5
=> Add net21 detection to15.5

src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/AssertEx.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PropertyPages/PropertyPageTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AbstractMoveCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/Renamer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/Web/DefaultHttpClient.cs
=> Use var instead of explicit type

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectAccessorFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectItemProviderFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Logging/ProjectLoggingExtensionsTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/SupportedTargetFrameworksEnumProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Interop/IVsAppId.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/SupportedTargetFrameworksEnumProvider.cs
Master equivalent of https://github.com/dotnet/project-system/pull/3278.
=> Apply formatting rules across the tree  (master)

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectChangeDiffFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectLogger.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/UnconfiguredProjectFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandlerTests.ConcreteAbstractEvaluationCommandLineHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandlerTests.EvaluationCommandLineHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandlerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandler.cs
About to make changes to this class to fix a hang, and it has no tests. Add some to cover some scenarios.
=> Add tests for AbstractEvaluationCommandHandler

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsShellUtilitiesHelperFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UI/IVsShellUtilitiesHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UI/VsShellUtilitiesHelper.cs
These methods are left over when the project edit code lived in this repo.
=> Remove unused methods

src/Microsoft.VisualStudio.Editors/PropPages/AssemblyInfoPropPage.Designer.vb
Fixes #3128 
The combobox can now display a list of suggestions for the language based on the user input
=> Changed NeutralLanguageCombobox.AutoCompleteMode from Append to SuggestAppend

src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/CSharp/CSharpErrorListTests.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/CSharp/CSharpProjectFileEditTest.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/CSharp/CSharpSquigglesTests.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/VisualBasic/VisualBasicErrorListTests.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/VisualBasic/VisualBasicSquigglesTest.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/WorkspaceTests.cs
Dev15.7.x version of https://github.com/dotnet/project-system/pull/3287.
=> Disable integration tests (dev15.7.x)

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/Automation/VisualBasicNamespaceImportsList.cs
This was caught by the component verification unit tests that I'm porting from CPS.
=> Make sure all exports of a part apply to the same capability

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/Mocks/IVsUpgradeLoggerFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/DebugFrameworksMenuTextUpdater.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/DynamicMenuCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AbstractMoveCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/WatermarkTextBox.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/ImplicitTopLevelDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UserNotificationServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/Converters.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfileData.cs
Pattern matching rule/fixer has been updated to handle negative checks, apply across the tree.
=> Apply pattern matching

docs/repo/getting-started.md
I'm assuming shipping documentation changes to master is okay. You can use the GitHub user interface to retarget this PR to the appropriate branch if need be.
=> docs: corrected environment variable declaration

Launch.cmd, docs/repo/getting-started.md
Some minor improvements to the experience of new and existing contributors.
=> docs: added shortcut to launch vs with recently built bits

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Generators/SingleFileGeneratorFactoryAggregatorTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PropertyPages/BuildMacroInfoTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/References/DesignTimeAssemblyResolutionTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/GlobalSuppressions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Generators/SingleFileGeneratorFactoryAggregator.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/BuildMacroInfo.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/DesignTimeAssemblyResolution.cs
Equivalent of https://github.com/dotnet/project-system/pull/3534 for the rest of the COM aggregation services.
=> Reduce leaks when an extension holds onto IVsHierarchy (rest)

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/DotNetCoreProjectCompatibilityDetector.cs
=> Only check compat for projects that support package references

src/Templates/Microsoft.NetCore.CSharp.ProjectTemplates.Test/Microsoft.NetCore.CSharp.ProjectTemplates.Test.csproj, src/Templates/Microsoft.NetCore.FSharp.ProjectTemplates.Test/Microsoft.NetCore.FSharp.ProjectTemplates.Test.csproj, src/Templates/Microsoft.NetCore.VB.ProjectTemplates.Test/Microsoft.NetCore.VB.ProjectTemplates.Test.csproj
fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/522736
=> Move test templates to be under "Test" instead of ".NET Core"

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/DebugProfileEnumValuesGeneratorTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/DebugProfileEnumValuesGenerator.cs
=> Escape mnemonics  for debug launch profiles

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/AbstractExtenderCATIDProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AbstractAddItemCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AbstractMoveCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddExistingItemBelowCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddExistingItemCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Collections/ImmutableStringDictionary.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/BaseProjectConfigurationDimensionProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/DebugTokenReplacer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/UnconfiguredProjectContextProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UnconfiguredProjectTasksService.cs
Applies https://github.com/dotnet/project-system/pull/3583 across the tree.
=> Apply formatting rules across the tree

src/Directory.Build.props, src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeParser/ProjectTreeParser.MutableProjectTree.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectAccessorFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/ExportFactoryFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IJsonModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectTreeCustomizablePropertyContextFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/MockIDependenciesTreeServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TestDependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Order/TreeItemOrderPropertyProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/LanguageServiceErrorListProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectAssetFileWatcher.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/VsItemList.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/AbstractBuildEventValueProvider.AbstractBuildEventHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GroupedByTargetTreeViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/IDependenciesTreeServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/IDependenciesTreeViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/IDependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/TreeViewProviderBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/Interop/VsHierarchyExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectAccessor.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ILanguageServiceHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ProjectTreeServiceExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectAccessor.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractSpecialFileProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AppDesignerFolderSpecialFileProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/SemaphoreSlimExtensions.cs
A version of https://github.com/dotnet/project-system/pull/3591 that got rebased but couldn't open the original.
=> Opt into new language features

Directory.Build.props, Launch.cmd, build.cmd, docs/repo/getting-started.md
This includes https://github.com/dotnet/project-system/pull/3599, so review https://github.com/dotnet/project-system/commit/6e229f220572ddcb960dff0a46824808a15a2472 onwards.
=> Add ability to launch under different hive

ProjectSystem.sln
Solution wants to move these config sections because ProjectSystemSetup was moved.
Let it.
=> Move configs position in solution

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/SourceItemHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHandlerManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/SemaphoreSlimExtensions.cs
For @jasonmalinowski - I've done zero validation whatsoever, but it builds on my machine.
<details>**Customer scenario**
**Risk**
(with a brief justification for that assessment (e.g. "Low perf impact because no extra …
=> Try to be free threaded

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/AbstractHostObject.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ConfiguredProjectHostObject.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ProjectHostProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/UnconfiguredProjectHostObject.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IConfiguredProjectHostObject.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IProjectHostProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/UnconfiguredProjectContextProvider.cs
Fixes: https://github.com/dotnet/project-system/issues/3327.
=> Reduce confusion between DisplayName & handshake between language service and project system

src/Microsoft.VisualStudio.AppDesigner/Common/Utils.vb, src/Microsoft.VisualStudio.Editors/Common/ListViewComparer.vb, src/Microsoft.VisualStudio.Editors/Common/Utils.vb, src/Microsoft.VisualStudio.Editors/DesignerFramework/ToolStripImageComboBox.vb, src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPage.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/PublicSettingsSingleFileGenerator.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsSingleFileGeneratorBase.vb
Convert old doc comment syntax to actual doc comment syntax.
=> Convert to docs to actual XML docs syntax

src/Microsoft.VisualStudio.AppDesigner/Common/Utils.vb, src/Microsoft.VisualStudio.Editors/Common/ListViewComparer.vb, src/Microsoft.VisualStudio.Editors/Common/Utils.vb, src/Microsoft.VisualStudio.Editors/DesignerFramework/ToolStripImageComboBox.vb, src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/BuildEventCommandLineDialog.vb, src/Microsoft.VisualStudio.Editors/PropPages/ComponentWrapper.vb, src/Microsoft.VisualStudio.Editors/PropPages/ReferenceComponent.vb, src/Microsoft.VisualStudio.Editors/PropPages/ReferencePropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/ServiceReferenceComponent.vb, src/Microsoft.VisualStudio.Editors/PropPages/UnusedReferencePropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/VBDescriptionAttribute.vb, src/Microsoft.VisualStudio.Editors/PropPages/VBDisplayNameAttribute.vb, src/Microsoft.VisualStudio.Editors/PropPages/WebReferenceComponent.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceListView.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceStringTable.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/PublicSettingsSingleFileGenerator.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsSingleFileGeneratorBase.vb
This includes https://github.com/dotnet/project-system/pull/3656, so only review https://github.com/dotnet/project-system/commit/0a06b0ace1f31b11a7535a9eb186f9fb253858ae.
=> Lower case <summary> tag usage

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/Packaging/CSharpProjectSystemPackage.cs, src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS/Packaging/FSharpProjectSystemPackage.cs, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/Packaging/VisualBasicProjectSystemPackage.cs
To make it a bit easier to read.
=> Format project type registration

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Resources/ManagedImagesMonikers.cs
Simplify this class into simple read-only fields.
=> Turn properties into fields

src/ProjectSystemSetup/Properties/launchSettings.json
These were very long on the toolbar.
=> Reduce launch profile text

build/Versions.props
Keep this change in 15.8 branch only.
=> Version padding for 15.8

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/CommandLineHandlerTestBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractWorkspaceContextHandler.cs
Per https://github.com/dotnet/project-system/pull/3738#discussion_r203071929.
=> [LanguageService] Initialize should throw on null context

src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPageVBWinForms.vb
Fixes #3666
- Sort splash screen drop-down items.
=> Sort splash screen drop-down items

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
=> Hide "Auto-Generate Binding Redirects"

.vsts-ci.yml
Allows our signed build to be configured based on per-branch yaml files
=> adding yaml build

build/Versions.props
This speeds up test invocation by about 35%.
=> Move xunit/Moq to latest versions

src/Directory.Build.props
- Turn on strict mode (https://github.com/dotnet/roslyn/search?q=FeatureStrictEnabled&unscoped_q=FeatureStrictEnabled)
- Opt into VB 15.3
=> Turn on strict mode and opt into VB 15.3

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectChangeDiffFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/MetadataFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandlerTests.EvaluationCommandLineHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandlerTests.cs
Added a couple of tests that we're passing through metadata though AbstractEvaluationCommandLineHandler.
=> Add a couple of metadata tests

build/Versions.props, src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/Moq/AbstractMock.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IActiveConfiguredProjectsProviderFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectPropertiesFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/UnconfiguredProjectFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IActiveDebugFrameworkServicesFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IActiveDebugFrameworkServicesMock.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IOutputGroupsFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/DebugFrameworksDynamicMenuCommandTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/DebugFrameworksMenuTextUpdaterTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PropertyPages/PropertyPageControlTests.cs
This is just a cherry-pick of https://github.com/dotnet/project-system/pull/3820 into LanguageServices.
=> Cherry pick #3820 into langauge services

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ExportFactoryFactory.cs
Add method to ExportFactoryFactory and move it down to Managed
=> (Test only) Export factory

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ConfiguredProjectFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ExportFactoryFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ICommandLineHandlerFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ICommandLineParserServiceFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IEvaluationHandlerFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectChangeDescriptionFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectRuleSnapshotFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectSubscriptionUpdateFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectVersionedValueFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectVersionedValueFactory`1.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IWorkspaceContextHandlerFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IWorkspaceProjectContextFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IWorkspaceProjectContextMock.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/OrderPrecedenceImportCollectionExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContextTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IApplyChangesToWorkspaceContext.cs
Add a service that is responsible for taking project snapshot data and sending it IEvaluationHandler/ICommandLineHandler.
This will be consumed by WorkspaceContextHost in a later PR, and is being PR'd to make it easier to review.
=> [Language Service] Add ApplyChangesToWorkspaceContext

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/PackageRestoreInitiator.PackageRestoreInitiatorInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetSubscriptionHostBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DataFlowUtilities.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/Automation/VisualBasicNamespaceImportsList.cs
Add new overloads to LinkToAsyncAction/LinkToAction that simplifies signing up to dataflow blocks.
=> Simplify dataflow usage

src/Microsoft.VisualStudio.Editors/PropPages/AdvBuildSettingsPropPage.ComboItem.vb, src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPage.vb
These are showing up in the error list.
=> Add accessibility modifiers

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactoryTests.cs
The former has been removed in master.
=> Replace IProjectThreadingServiceMock withIProjectThreadingServiceFactory

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/GlobalSuppressions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/ITelemetryTestChannelFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Telemetry/TelemetryTestContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Telemetry/VsTelemetryServiceTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyTreeTelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/DesignTimeTelemetryLogger.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/VsTelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/ITelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryEventName.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryPropertyName.cs
Add additional VsTelemetryService tests.
This includes https://github.com/dotnet/project-system/pull/3895, so only review https://github.com/dotnet/project-system/commit/0b73bed5a75161ab7b7b489a74c970fd3006e964.
=> Telemetry tests

src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/LazyExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ITelemetryServiceFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IWorkspaceProjectContextFactoryFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IWorkspaceProjectContextProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextProvider.ForegroundWorkspaceProjectContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextProvider.ProjectContextInitData.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryEventName.cs
Responsible for creating/disposing a IWorkspaceProjectContext.
=> Add WorkspaceContextProvider

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/VSPackage.resx, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.zh-Hant.xlf, src/Templates/Microsoft.NetCore.CSharp.ProjectTemplates.Test/Microsoft.NetCore.CSharp.ProjectTemplates.Test.csproj, src/Templates/Microsoft.NetCore.CSharp.ProjectTemplates.Test/NUnitTest.vstemplate, src/Templates/Microsoft.NetCore.CSharp.ProjectTemplates.Test/source.extension.vsixmanifest, src/Templates/Microsoft.NetCore.FSharp.ProjectTemplates.Test/Microsoft.NetCore.FSharp.ProjectTemplates.Test.csproj, src/Templates/Microsoft.NetCore.FSharp.ProjectTemplates.Test/NUnitTest.vstemplate, src/Templates/Microsoft.NetCore.FSharp.ProjectTemplates.Test/source.extension.vsixmanifest, src/Templates/Microsoft.NetCore.VB.ProjectTemplates.Test/Microsoft.NetCore.VB.ProjectTemplates.Test.csproj, src/Templates/Microsoft.NetCore.VB.ProjectTemplates.Test/NUnitTest.vstemplate, src/Templates/Microsoft.NetCore.VB.ProjectTemplates.Test/source.extension.vsixmanifest
adding templates for NUnit test framework
fixes https://github.com/Microsoft/vstest/issues/1570
=> adding NUnit templates

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContextProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetRuleSubscriberBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetSubscriptionHostBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/ICrossTargetRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/ICrossTargetSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependenciesRuleHandlerBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/DisposableBag.cs
This includes https://github.com/dotnet/project-system/pull/3920, so only review https://github.com/dotnet/project-system/commit/27553a800af9e07f307db70d943752218e37c434 and https://github.com/dotnet/project-system/commit/b064bdf84eb18c4be8cb58cbfc9f9c8d8fcefd84.
=>  Use DisposableBag in CrossTargetRuleSubscriberBase

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
Best reviewed commit by commit. Commit messages explain my intentions for each change. The combined diff is a bit much in one go.
I'm happy for this to be split up into smaller PRs, but there are dependencies between the commits. Given the time zone differences between us I'd be interested in feedback on the lot.
=> Various BuildUpToDateCheck optimisations

docs/repo/dependencies-node-roadmap.md, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/Actions/CheckChildrenGraphActionHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/Actions/GetChildrenGraphActionHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/Actions/IDependenciesGraphActionHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/Actions/SearchGraphActionHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/IDependenciesGraphBuilder.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/ViewProviders/IDependenciesGraphViewProvider.cs
Add documentation on the role of graph nodes in the Dependencies node implementation.
=> Add graph nodes documentation

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPage.cs
We had a roundabout way of getting an UnconfiguredProject from IVsHierarchy, just use extension.
=> Use GetUnconfiguredProject extension

src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/TaskExtensions.cs
Found this while doing other ConfigureAwait work. Uses the pattern from [here](https://github.com/dotnet/corefx/blob/851a53bee21639cd65e109b72fd5f9ef90cc0f39/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs) except adds in disposal of the cts. No idea why System.Threading only does that in one of the methods.
Only "breaking" change here is the observation of the task so that we don't swallow exceptions. Currently the only place this method is used, outside of tests, is here:
https://github.com/dotnet/project-system/blob/dfe534a3e7803efb763ba9dcd35c5ce60c9104a5/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs#L807
No chance of throwing with that since its not a real task that does any work, just a completion source. See: …
=> Cancel delay tasks, dispose of token source, and observe the task.

netci.groovy
Commit 3e7d8b4 took a dependency on 15.8 which broke integration tests. Move to 15.8 image.
=> Move to 15.8 image to fix integration tests

src/Directory.Build.props, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/OpenProjectEditorOnDefaultActionCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs
Open project file for editing on double click. Fixes #1224
See that issue for a gif of the feature.
=> Open the project file for editing on double click or ENTER

docs/repo/debugging-tips.md, docs/repo/debugging/async-test-hangs.md
Ran into a hang in https://github.com/dotnet/project-system/pull/3980 - thought I would write up based on an internal doc that @jaredpar wrote how I figured out test that caused it.
=> Add doc around debugging async test hangs

src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj, src/Microsoft.VisualStudio.Editors/MyExtensibility/MyExtensibilityPropPage.resx, src/Microsoft.VisualStudio.Editors/MyExtensibility/MyExtensibilityPropPage.vb, src/Microsoft.VisualStudio.Editors/MyExtensibility/MyExtensionDataGridView.vb, src/Microsoft.VisualStudio.Editors/MyExtensibility/xlf/MyExtensibilityPropPage.cs.xlf, src/Microsoft.VisualStudio.Editors/MyExtensibility/xlf/MyExtensibilityPropPage.de.xlf, src/Microsoft.VisualStudio.Editors/MyExtensibility/xlf/MyExtensibilityPropPage.es.xlf, src/Microsoft.VisualStudio.Editors/MyExtensibility/xlf/MyExtensibilityPropPage.fr.xlf, src/Microsoft.VisualStudio.Editors/MyExtensibility/xlf/MyExtensibilityPropPage.it.xlf, src/Microsoft.VisualStudio.Editors/MyExtensibility/xlf/MyExtensibilityPropPage.ja.xlf, src/Microsoft.VisualStudio.Editors/MyExtensibility/xlf/MyExtensibilityPropPage.ko.xlf, src/Microsoft.VisualStudio.Editors/MyExtensibility/xlf/MyExtensibilityPropPage.pl.xlf, src/Microsoft.VisualStudio.Editors/MyExtensibility/xlf/MyExtensibilityPropPage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/MyExtensibility/xlf/MyExtensibilityPropPage.ru.xlf, src/Microsoft.VisualStudio.Editors/MyExtensibility/xlf/MyExtensibilityPropPage.tr.xlf, src/Microsoft.VisualStudio.Editors/MyExtensibility/xlf/MyExtensibilityPropPage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/MyExtensibility/xlf/MyExtensibilityPropPage.zh-Hant.xlf
A refactoring of the My Extensions property page for correct narrator behavior to fix [391558](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/391558/)
=> My Extensions property page ListView refactoring to DataGridView

build/Versions.props
Fixes failure to submit coverage reports.
=> Update to codecov.exe that supports gzip

src/Microsoft.VisualStudio.Editors/XmlToSchema/InputXmlForm.vb
Fixes #3997 
I'm not intimate with this code, but this looks like a plausible fix.
=> Fix method return

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextProvider.ProjectContextInitData.cs
We don't need to reimplement on partial class for the nested type - it's on the main partial.
=> Do not implement interface on partial class

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ActiveWorkspaceProjectContextTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceContextHost.cs
Missing an import, export & importing wrong type.
=> Fix minor MEF issues

build/Default.ruleset
Cherry pick the rule turn off so that I can stop ConfigureAwait'ing in this branch.
=> Cherry pick ConfigureAwait rule turn off

docs/up-to-date-check.md, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
Adds `docs/up-to-date-check.md` that describes the process used by `BuildUpToDateCheck`.
Also some minor refactoring and code documentation.
=> BuildUpToDateCheck documentation and refactor

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/AbstractMultiLifetimeComponentTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AbstractMultiLifetimeComponent.cs
Returns a task that completes when when the component is Loaded.
=> Add AbstractMultiLifetimeComponent.Loaded

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/EditAndContinue/EditAndContinueProvider.cs
As per: https://github.com/dotnet/project-system/pull/4033/files#r218715300.
=> Correctly assign ref argument

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/PackageRuleHandler.cs
~~Replace O(N) with O(1).~~
`Enumerable.Count` on `string[]` is O(1) but still looks weird.
=> Replace Linq Count() with Any/Length

.vsts-ci.yml, build/build.ps1
Upload our integration tests so other teams can run them.
=> upload integration tests

.vsts-ci.yml, .vsts-dnceng.yml, build/build.ps1, src/Directory.Build.props
Adding Azure Devops to the Dev15.9 branch
=> Port ado to dev15.9

build/Default.ruleset, build/Versions.props, netci.groovy, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ConfiguredProjectFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectCommonServicesFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectServiceFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectPropertiesFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectServicesFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/UnconfiguredProjectFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PropertyPages/BuildMacroInfoTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
testing infra fix for https://github.com/dotnet/project-system/pull/4085
=> Breaking changes

.vsts-dnceng.yml
adds spainish test run
fixes https://github.com/dotnet/project-system/issues/3441
=> removing host configuration

.vsts-dnceng.yml, build/CIBuild.cmd
Don't test sign in the spanish build. We only care that build and test pass for this configuration
=> Spanish builds fix

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/AbstractBuildEventValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectAccessor.cs
This was added by CPS to fix known dead lock issues
=> use delegate-based API instead of using-based API

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/DependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/DiagnosticDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/PackageAnalyzerAssemblyDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/PackageAssemblyDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/PackageDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/PackageUnknownDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/AnalyzerRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/AssemblyRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/ComRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependenciesChanges.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependenciesRuleHandlerBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/PackageRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/ProjectRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/SdkRuleHandler.cs
A grab bag of stuff I saw while working on dependency node bugs today.
Easiest to review commits separately. Descriptions in commit messages.
=> Miscellaneous changes to dependencies code

src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/ITaskDelayScheduler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/TaskDelayScheduler.cs
This will be easier to review commit by commit.
Fixes #4115.
=> Fix TaskDelayScheduler race/NRE and minor cleanup

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/DuplicatedDependenciesSnapshotFilter.cs
=> Add missing comparison type

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/AbstractMultiLifetimeComponentFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/DebugTokenReplacerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsSolutionBuildManager2Factory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/NuGet/ProjectAssetFileWatcherTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PropertyPages/PropertyPageTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/PackageRestoreInitiator.PackageRestoreInitiatorInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/PackageRestoreInitiator.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectSystemOptions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/WpfBasedPropertyPage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/SVsSettingsPersistenceManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContextProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetSubscriptionHostBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyIconSet.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/DependenciesViewModelFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/ImplicitTopLevelDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySubscriptionsHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Order/TreeItemOrderPropertyProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UI/DialogServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/Web/DefaultHttpClient.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/ImplicitlyActiveDimensionProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/DebugTokenReplacer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
New build of VS has more analysis, clean up the error list to remove unused fields/methods, and apply var settings.
=> Remove unused fields & other stuff

src/Microsoft.VisualStudio.Editors/SettingsDesigner/AppConfigSerializer.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/ConnectionStringUITypeEditor.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsValueSerializer.vb
These were missed in https://github.com/dotnet/project-system/pull/4152.
=> Mark methods as shared

build/build.ps1
Avoid man in the middle attacks.
=> Pull vswhere from https

build/build.ps1
Also avoid PublishArtifacts from failing during a failed build.
=> Write out binlog for toolset restore

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GroupedByTargetTreeViewProvider.cs
See commit comments for description.
=> Refactor tree node update/creation

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IProjectTreeExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GroupedByTargetTreeViewProvider.cs
- Remove unused methods `AddElementsToTree`, `RemoveElementsFromTree`, and `FindImmediateChildByPath`
- Rename `FindNodeByCaption` -> `GetChildWithCaption` (it only checks children)
- Inline method to simplify and improve perf
=> Refactor IProjectTreeExtensions

src/HostAgnostic.props, src/Microsoft.VisualStudio.AppDesigner/PropPages/SKUMatrix.vb, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.csproj, src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS/Microsoft.VisualStudio.ProjectSystem.FSharp.VS.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.csproj, src/VisualStudio.props, src/VisualStudioDesigner.props
This includes https://github.com/dotnet/project-system/pull/4191, so review https://github.com/dotnet/project-system/commit/e2c6d06fcec844bf5bdda26b7c79cb0b84104c76 onwards. It's expected to fail in release until #4191 is merged.
=> Move common references into common locations

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ConfiguredProjectServicesFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectPropertiesFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
Created this for some tests that I'm not ready to commit yet, and probably will end up abandoning, but this will be useful in future anyway
=> Create mock factory for ConfiguredProjectServices

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs
Merging parallel PRs resulted in a compile error, fixed here.
=> Fix compile error

src/Directory.Build.props, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/MetadataExtensions.cs
There's a good chance this won't work on our CI machines. This is just a test.
=> Use C# 7.3

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Xproj/GlobalJsonRemoverTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/DebugProfileEnumValuesGeneratorTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependencyTests.cs
- Reinstate commented test
- Use assertions that provide more details when they fail
=> Test tidying

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs
One PR added a test using an API that another PR changed.
=> Fix compile error after parallel PR merges

src/Microsoft.VisualStudio.Editors/PropPages/PackagePropPage.resx, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.cs.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.de.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.es.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.fr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.it.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.ja.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.ko.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.pl.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.ru.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.tr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.zh-Hant.xlf
Adds the Narrator fix for the Assembly Version as in [4054](https://github.com/dotnet/project-system/pull/4054)
=> Package Property Page Accessible Name Change

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/LanguageServices/CSharpLanguageFeaturesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.FSharp/ProjectSystem/LanguageServices/FSharpCommandLineParserService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Build/BuildUtilitiesTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/GetProfileNameDialog.xaml.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/UnconfiguredProjectExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Build/BuildUtilities.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/BaseProjectConfigurationDimensionProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/TargetFrameworkProjectConfigurationDimensionProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/PackagePropertyPage/BaseVersionValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Text/LazyStringSplit.cs
Various reductions to memory, mainly avoiding temporary strings and arrays. I searched the project for `Trim` and `Split`.
=> Memory reduction

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/PackageRuleHandler.PackageDependencyMetadata.cs
This error was introduced in 3744d8f6cbb1d03da506e7b30bae4d8acffcac7d
Fixes #4313.
=> Fix merge error

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/ProjectRuleHandler.cs
Seems there's no need to store the results of one loop for use in another. It's possible to just raise events directly in the first loop.
Fixes #4311
=> Avoid list allocations

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectChangeDescriptionFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectRuleSnapshotFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectSubscriptionUpdateFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IAggregateDependenciesSnapshotProviderFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependenciesSnapshotFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependenciesSnapshotProviderFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependencyFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependencyModelFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IMockDependenciesViewModelFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectCatalogSnapshotFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectDependenciesSubTreeProviderFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/ITargetFrameworkFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/ITargetFrameworkProviderFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/ITargetedDependenciesSnapshotFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsHiearchyItemFactory.cs
Makes it easier to see what policy is applied via intellisense.
=> Specify default on parameter directly

docs/repo/debugging/tracing.md
This was very useful, but thought it could benefit from the final step
=> Completed the example for accessing CPS trace buffer

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Fixes [#746371](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/746371)
=> Fix non english rules

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs
Some cleanup before I start modifying this class.
=> Replace properties with fields

src/Directory.Build.props, src/Directory.Build.targets
Thanks @tmat for the inspiration.
=> Import props/targets from NuGet in WPF tmpproj builds

docs/repo/loading-components-with-projects.md
Hopefully a true and correct representation of https://github.com/dotnet/project-system/pull/4395#issuecomment-447532685
=> Documenting the Mind of Kean

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
I _think_ this is the correct way to remove the use of `IProjectLockService` but would love some reviewer to correct me.
=> remove use of IProjectLockService

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/MigrateXprojProjectFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS.UnitTests/ProjectSystem/VS/FSharpProjectSelectorTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/Workspaces/WorkspaceFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ProjectRootImageProjectTreeModifierTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UnconfiguredProjectTasksServiceTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsSettingsStoreTester.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/OutputTypeExValueProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/OutputTypeValueProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/References/DesignTimeAssemblyResolutionTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/UnconfiguredProjectVsServicesTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Telemetry/SDKVersionTelemetryTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/AbstractAddClassProjectCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/HACK_AddItemHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/SpecialFilesProviders/VsProjectSpecialFilesManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/ManagedPathHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/ServiceProviderToOleServiceProviderAdapter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/UnconfiguredProjectContextProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/AssemblyAttributeProperties/AssemblyInfoProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractSpecialFileProvider.cs
Just removing some noise from the Error List.
=> Fix violations of IDE0059

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceContextHost.WorkspaceContextHostInstance.cs
We weren't waiting for changes to be applied before we closed the batch. This path is currently synchronous so it's just by chance that this currently works.
=>  Make sure to apply changes under batch

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Xproj/MigrateXprojProjectFactoryTests.cs, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/MigrateXprojProjectFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.FSharp/GlobalSuppressions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeParser/Tokenizer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/AssemblyInfoPropertiesProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/CreateFileFromTemplateServiceTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageElementHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/Renamer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHandlerManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractSpecialFileProvider.cs
Some more compiler noise since updating roslyn packages.
I've gone through the test changes and they seem to be fine to me, but some of them do seem a little light on substance now, so I could be mistaken.
=> Fix ide0060 warnings

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs
This commit was missed in the features/LanguageService merge to master: https://github.com/dotnet/project-system/pull/4418.
=> Log design-time build success changes

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphChangeTracker.cs
Add documentation to the `WeakCollection<T>` type as discussed in https://github.com/dotnet/project-system/pull/4434#discussion_r245808709.
Also use the generic form of `WeakReference<T>`.
=> Document weak collection

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Now that the CPS changes have been merged we can opt in.
Fixes #113
=> Opt-in to AvailableItemName support in CPS

.github/ISSUE_TEMPLATE.md
Adding support for an issue template. This should help us guide people to file issues with the information that we need to triage them.
=> Adding a template for filing new issues.

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SDKVersionTelemetryServiceComponent.SDKVersionTelemetryServiceInstance.cs
=> fixes #4512

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphChangeTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/AggregateDependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/IDependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/IDependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/RuleHandlers/ProjectRuleHandler.cs
Small commits pulled from larger work for separate review.
=> Little bits

.vsts-ci.yml
@davkean 	noticed that we weren't publishing these for some reason, fixing...
=> upload test result artifacts

src/Microsoft.VisualStudio.Editors/PropPages/AdvBuildSettingsPropPage.resx, src/Microsoft.VisualStudio.Editors/PropPages/CSharpLanguageVersion.vb, src/Microsoft.VisualStudio.Editors/PropPages/CSharpLanguageVersionUtilities.vb, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.cs.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.de.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.es.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.fr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.it.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.ja.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.ko.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.pl.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.ru.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.tr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.zh-Hant.xlf
This change reflects the changes in the Roslyn PR https://github.com/dotnet/roslyn/pull/33089
=> Add new C# language versions

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IWorkspaceProjectContextMockFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/DynamicItemHandlerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/DynamicItemHandler.cs
This isn't needed til 16.1 but figured it was an easy one to do between sessions :)
Fixes #4468
=> Add .razor files as dynamic items for Razor Components support

build/Versions.props
=> Update versions to match release

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/VsUIServiceTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsUIService`1.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsUIService`2.cs
Move IVsUIService<T> to global scope
Equivalent of https://github.com/dotnet/project-system/pull/4589, but for IVsUIService.
=> Move IVsUIService to global scope

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/StartupProjectHelper.cs
Moved StartupProjectHelper to IVsUIService usage
Removed null checks for services because if these two services do not exist, we shouldn't be running.
This is blocked on https://github.com/dotnet/project-system/pull/4592 merging.
=> Moved StartupProjectHelper to IVsUIService usage

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/VSPackage.resx, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/xlf/VSPackage.zh-Hant.xlf
This was leftover from when the project file editor factory lived in this code base.
=> Remove unused resource

docs/design-time-builds.md, docs/well-known-project-properties.md
=> Update GitHub URL

src/Microsoft.VisualStudio.Editors/PropPages/PackagePropPage.Designer.vb, src/Microsoft.VisualStudio.Editors/PropPages/PackagePropPage.vb
Was working on creating a PR to add my License fix to the dev16.0.x branch and accidentally pushed to the branch.
I apologize - I updated my remotes and this won't happen again.
=> Revert change

src/Microsoft.VisualStudio.Editors/PropPages/PackagePropPage.resx
Simple fix for: https://github.com/dotnet/project-system/issues/4632
=> Package property sizing fixes

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/NuGet/ProjectRestoreInfoBuilderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectRestoreInfoBuilder.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/Snapshots/ImmutablePropertyCollection.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/Snapshots/ProjectProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/Snapshots/ProjectProperty.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/Snapshots/ProjectRestoreInfo.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/Snapshots/ReferenceItem.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/Snapshots/ReferenceItems.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/Snapshots/ReferenceProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/Snapshots/ReferenceProperty.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/Snapshots/RestoreBuilder.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/Snapshots/TargetFrameworkInfo.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/Snapshots/TargetFrameworks.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ProjectReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/StringComparers.cs
Pulled out self-contained changes that I've made in the rewrite of the NuGet restore code to make review purposes easier.
=> Random cleanup in NuGet restore code

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/DotNetCoreProjectCompatibilityDetector.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectFaultServiceExtensions.cs
=> Do not RunAndForget in a global context

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/DotNetCoreProjectCompatibilityDetector.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectFaultServiceExtensions.cs
follow up to https://github.com/dotnet/project-system/pull/4680
=> Do not pass CancelOnUnload if a null project is given

src/HostAgnostic.props, src/VisualStudio.props
Depends on https://github.com/dotnet/project-system/pull/4689
These dependencies already come from HostAgnostic so they are not needed here
=> [Minor] remove duplicate dependencies

src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj
These Editor dependencies are already imported
=> remove duplicate dependencies

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/VersionCompatibility/VersionCompatibilityTests.cs
Adding a test for `VersionCompatibilityData` type to lay the ground work for fixing [819411](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/819411)
=> add test for deserializing version compatibility

src/Microsoft.VisualStudio.Editors/PropPages/AdvBuildSettingsPropPage.vb
Don’t allow selection of preview C# versions in the dropdown unless the project is also a preview .NET project.
=> Update language dropdown

build/Packages.targets, src/VisualStudio.props
=> remove reference to Microsoft.VisualStudio.Utilities

build/Default.ruleset, build/Packages.targets, src/VisualStudio.props
Updating package versions to latest - Primarily to update Microsoft.VisualStudio.Utilities so we can switch from DpiHelper to DpiAwareness
- **Disabled:** VSTHRD003 for **all projects**
- **Re-added** Microsoft.VisualStudio.Utilities with updated version
- **Updated** all the dependencies of Microsoft.VisualStudio.Utilities
=> Update package versions

src/Directory.Build.props, src/Microsoft.VisualStudio.Editors/PropPages/WPF/ApplicationPropPageVBWPF.vb
alternative to https://github.com/dotnet/project-system/pull/4754
=> implement GetHashCode instead of throwing

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/TempPE/TempPEBuildManagerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/TempPEBuildManager.cs
Part of #4163
Tests for the TempPEBuildManager
=> Added tests for TempPEBuildManager

src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj
Additional ones that were missed.
=> Remove unneeded DependentUpon & empty updates

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreUnconfiguredDataSource.cs
Fixes: #4801
Tests are coming to test this - didn't want to block fix/insertion on them as still trying to figure out how to test data sources.
=> Tool reference in multi-targeting project causes fault

CONTRIBUTING.md
Now that IntelliCode is in-box we should try it out, and I guess it won't hurt for others to know about it too.
=> Add note about custom intellicode model

docs/well-known-project-properties.md, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.CSharp.DesignTime.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.VisualBasic.DesignTime.targets
=> Return values for DesignerHiddenCodeGeneration

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
Fixes the symptom of #4860, if not the cause. Unfortunately I was not able to reproduce the exception, so the underlying problem is unclear. This will, at least, prevent the exception.
=> Prevent KeyNotFoundException

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IUnconfiguredProjectVsServicesFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/CSharp/RenamerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/RenamerTestsBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/VisualBasic/RenamerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/Renamer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/CompileItemHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IApplyChangesToWorkspaceContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IFileRenameHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IProjectUpdatedHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs
initial rough attempt at synchronizing workspace and project system during a rename
=> Sync workspace events

.editorconfig, build/Default.ruleset, build/Packages.targets, build/Versions.props, src/Microsoft.VisualStudio.Editors/MyExtensibility/MyExtensibilityPropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/ReferencePropPage.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb
Bumps the analyzer package versions.
Applies some .editorconfig values to VB files as well.
=> Analyzer updates

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/AdditionalFiles.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/ApplicationDefinition.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Compile.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Content.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/EditorConfigFiles.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/EmbeddedResource.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/None.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Page.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Resource.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/XamlAppDef.BrowseObject.xaml
Fix the enum value for user controls.
=> Change Control subtype to UserControl

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/RenamerTestsBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Refactor/VisualStudioRefactorNotifyService.Instance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Refactor/VisualStudioRefactorNotifyService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/Renamer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Refactor/IRefactorNotifyService.cs
dependent upon https://github.com/dotnet/project-system/pull/4983
=> Add refactor notify

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/Renamer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf
Adding resource strings and some small cleanup
=> small cleanup of rename

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IPackageRestoreUnconfiguredDataSourceFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PackageRestore/PackageRestoreInitiatorInstanceTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/IPackageRestoreConfiguredDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/IPackageRestoreUnconfiguredDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreConfiguredDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreInitiator.PackageRestoreInitiatorInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreUnconfiguredDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/Snapshots/ConfiguredProjectRestoreUpdate.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/Snapshots/UnconfiguredProjectRestoreUpdate.cs
This is a minor set of package restore changes needed for operation progress, pulled them out to make reviews a little easiers.
=> Minor package restore changes

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/RenamerTestsBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/Renamer.UndoTransaction.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/Renamer.cs
fixes https://github.com/dotnet/project-system/issues/4538
fixes https://github.com/dotnet/project-system/issues/3527
fixes https://github.com/dotnet/project-system/issues/2663
=> Add undo for rename type to match file

build/Packages.targets, src/HostAgnostic.props, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AnalyzerConfigItemHandler.cs
=> Remove reflection usage

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectDependenciesSubTreeProviderFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/IProjectDependenciesSubTreeProviderInternal.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/Filters/ImplicitTopLevelDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/AnalyzerRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/AssemblyRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/ComRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/DependenciesRuleHandlerBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/FrameworkRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/ProjectRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/SdkRuleHandler.cs
=> Tidy dependency node rule handlers

build/Packages.targets
=> Turn package updates into a table

build/Packages.targets, build/Versions.props
=> Inline package version

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/Actions/InputNodeGraphActionHandlerBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphChangeTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/BaseProjectConfigurationDimensionProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ActiveDebugFrameworkServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/SDKVersionTelemetryServiceComponent.SDKVersionTelemetryServiceInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/AggregateDependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/DependenciesRuleHandlerBase.cs
Latest compiler version introduced new warnings, clear up the warnings.
=> Nullable annotations

src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.pkgdef, src/Microsoft.VisualStudio.Editors/VSPackage.resx, src/Microsoft.VisualStudio.Editors/package/VBPackage.vb, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.cs.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.de.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.es.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.fr.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.it.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.ja.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.ko.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.pl.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.ru.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.tr.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.zh-Hant.xlf
Fix for https://github.com/dotnet/project-system/issues/4606
=> Add option page keywords

src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPageInternalBase.vb
Was doing some TFM testing and ran into this
=> Fix Null Reference in Property Pages

build/Packages.targets
Reacting to the impactful change email.
=> Move from vside.myget.org to pkgs.dev.azure.com

.vsts-ci.yml, build.cmd, build/azure-pipelines.yml
For consistency and let's us explicitly specify and hence doc the command-lines in the pipelines.
=> Add no- versions of all switches

Directory.Build.targets, build/Scripts/UnitTests.targets, build/Scripts/Workarounds.targets
Move double-write target so that all projects inherit it.
=> Fix double-write again

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/UnconfiguredProjectFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/TempPECompilerManagerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/TempPECompilerManager.cs
=> Move compiler manager to UnconfiguredProject scope

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.State.cs
=> Fix analyzer error

build/Scripts/IntegrationTests.targets
This includes https://github.com/dotnet/project-system/pull/5161, so just review https://github.com/dotnet/project-system/commit/7a381d1c1ef652a47f015744848320f27f68f7c8.
=> Cleanup test results files we don't use

src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/Environment/AssemblyLifetime.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/Environment/TestEnvironment.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/ProjectSystemHostConfiguration.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/TestBase.cs
Pull this logic our into separate classes.
=> Refactor hive/environment setting

build.cmd, build/Bootstrap/SetVSEnvironment.cmd, build/Versions.props, build/build.ps1
Always launch build under dev prompt
To simplify finding VS tools and setting our environment, etc we always launch build under a VS command prompt.
=> Always launch build under dev prompt

Directory.Build.props
=> Remove workaround as the bug has been fixed.

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/DteEnvironmentOptions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IPhysicalProjectTreeExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IRoslynServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IVsService`1.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NewProjectInitializationProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UI/DontShowAgainMessageBox.xaml.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/NameValuePair.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/ObservableList.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/ObservableListExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VersionCompatibility/DotNetCoreProjectCompatibilityDetector.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/Interop/VsHierarchyExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/ServiceProviderToOleServiceProviderAdapter.cs
Bits pulled out from another pass of null annotations (which I'll submit later).
Easiest to review commit by commit.
=> Misc tidying

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcherTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/TempPECompilerManagerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcher.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/TempPECompilerManager.cs
Attempt Number 4.
Unfortunately the flakiness best manifests itself on a fresh PR build, sorry about the spam :)
=> Fix flaky tests

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TargetFrameworkProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/OnceInitializedOnceDisposedUnderLockAsync.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/IDependencyViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/AggregateDependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/IDependencyExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/AnalyzerRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/AssemblyRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/ComRuleHandler.cs
Small changes pulled out of larger work on the dependencies node.
=> Dependency node cleanup

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Refactor/VisualStudioRefactorNotifyService.Instance.cs
=> catch COM exceptions

build/import/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectConfigurationFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VisualBasic/VisualBasicVSImports.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectDebuggerProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/PasteOrdering.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageControl.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/BaseReferenceContextProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettings.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractSpecialFileProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
Removes a bunch of null forgiveness operators.
=> Up annotated vs-validation library

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Refactor/VisualStudioRefactorNotifyService.Instance.cs
pulls in #5322 from @drewnoakes only review 67d26a0af
=> addressing feedback for #5319

Directory.Build.targets, build/import/Coverage.targets, build/import/Packages.targets, build/import/Versions.props, build/proj/CodeCov.proj, src/Directory.Build.targets
These are some minor changes that don't actually make it run yet but want to get them in to make review easier as I update this.
=> Minor changes in CodeCov

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/Renamer.cs
=> defer getting the document from the workspace for as long as possible

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsDataSource.cs
Fixes #5341
This isn't the same file as that bug, but the file in that bug will be deleted when the feature branch is merged anyway.
=> Don't fault the block if our rules aren't loaded

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractSpecialFileProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AppDesignerFolderSpecialFileProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/IAppDesignerFolderSpecialFileProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IAppDesignerFolderSpecialFileProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviders/AppDesignerFolderSpecialFileProviderTests.cs
This will become the root base class for special file providers, and moved AppDesignerFolderSpecialFileProvider over to it. Other providers forthcoming.
=> Introduce new AbstractSpecialFileProvider base

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/IDependencyCrossTargetSubscriber.cs
Part of an initiative to consolidate duplicated code across the dependencies node.
=> Use DisposableBag for subscriptions

ProjectSystem.sln, docs/Documentation.csproj, docs/docs.projitems, docs/docs.shproj
We want to dogfood shared projects, so add a VB shared project as a replacement for documentation.csproj.
=> Replace Documentation.csproj with docs shared project

src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.cs.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.de.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.es.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.fr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.it.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.ja.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.ko.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.pl.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.ru.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.tr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.zh-Hant.xlf
fix for bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/976541
Fixes [AB#976541](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/976541)
=> LOC CHECKIN | dotnet/project-system dev16.3.x  | 20190904

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesTreeViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.ContextTracker.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextHostInstanceTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/OnceInitializedOnceDisposedUnderLockAsyncTests.cs
New warnings appeared latest master, annotate types correctly.
=> Annotation new warnings

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IPhysicalProjectTreeStorage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PhysicalProjectTreeStorage.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/Moq/ReturnsExtensions.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IFolderManagerFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PhysicalProjectTreeStorageTests.cs
These are needed by the special file providers, I've pulled them out into their own review.
=> Add "IPhysicalProjectTreeStorage.AddFileAsync/AddFolderAsync"

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AdditionalDesignTimeBuildInputDataSource.cs
This reverts commit e652168a2d3d5364cc8e83d2dd199314948eb59f, reversing
changes made to 49144adfd7dd20f7a9ef03794ea0e5fd58d5b839.
=> Revert "Merge pull request #5437 from davkean/RemoveExport"

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VsProject.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VsProject_VsLangProjectProperties.cs
Pulls duplicate code out into helper methods.
=> VsLangProj property refactor

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractAppXamlSpecialFileProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/CSharp/CSharpAppXamlSpecialFileProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/VisualBasic/VisualBasicAppXamlSpecialFileProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviders/AbstractAppXamlSpecialFileProviderTestBase.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviders/AbstractFindByNameSpecialFileProviderTestBase.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviders/AppConfigSpecialFileProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviders/CSharp/CSharpAppXamlSpecialFileProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviders/VisualBasic/VisualBasicAppXamlSpecialFileProviderTests.cs
Fixes: https://github.com/dotnet/project-system/issues/116
This cannot currently be hit in the project but will be in once https://github.com/dotnet/project-system/issues/4249 has been fixed. This is lieu of https://github.com/dotnet/project-system/pull/3767.
=> Add "Application Definition" special file handler

build/ci/unit-tests.yml
=> Update yml to include dev16.4.x branch

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VsBuildManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsBuildManagerBridge.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsChangeTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsCompiler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcher.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/IDesignTimeInputsBuildManagerBridge.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsBuildManagerBridgeTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsChangeTrackerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsCompilerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsDataSourceTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcherTests.cs
Because of the change in using statement separation rule, might be easier to review by commit.
=> Various cleanup following the TempPE branch merge

src/Common/BannedSymbols.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProjectTypeCapabilities.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProjectTypeRegistration.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VisualBasic/VisualBasicNamespaceImportsList.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredProjectsLoader.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ConfiguredProjectImplicitActivationTracking.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHostInitiator.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UnconfiguredProjectTasksService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/ComponentVerificationTests.cs
Have added a new test that verifies correct usage now, of which there is a single violation: https://github.com/dotnet/project-system/issues/5519.
Based on this: https://github.com/dotnet/project-system/pull/5501#discussion_r324947156.
=> Unban ProjectAutoLoad/ConfiguredProjectAutoLoad

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreConfiguredInputDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageControl.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Waiting/VisualStudioWaitIndicator.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Build/BuildUtilities.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Interop/Win32Interop.cs
Found an interesting analyzer, installed it to take a look, it found a few minor fixes.
=> Fix a few minor details found by analyzers

docs/opening-with-new-project-system.md
Fixes #5243.
Updates the documentation to reflect the new project system detection
logic for VS 2019 16.4.
=> Update documentation on project system detection

build/ci/unit-tests.yml
The test checks wouldn't run on docs or Readme file but this would easily
=> Trigger unit tests to run on all commits

src/Microsoft.VisualStudio.Editors/ResourceEditor/SerializableEncodingConverter.vb
Replace an `ArrayList` and a couple of `SortedList`s with the equivalent `List(Of String)` and `SortedList(Of String, String)`.
This is the last one of these changes for a while.
=> Replace ArrayList and SortedList

src/Microsoft.VisualStudio.Editors/DesignerFramework/BaseRootDesigner.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/Category.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/CategoryCollection.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/FileWatcher.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/FindReplace.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/Resource.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceComparerForFind.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView_EditorState.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceListView.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceSerializationService_Store.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceStringTable.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ThumbnailCache.vb, src/Microsoft.VisualStudio.Editors/StringComparers.vb
This is basically the same as #5577 but with the bugs worked out--there are no more exceptions when using the RESX Designer.
=> Try again to clean up the RESX Designer

build.cmd, build/script/SetVSEnvironment.cmd
Running into this locally due to what I have installed.
=> Move LIB workaround to build.cmd

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs
Fixes: #5589 
Replacement for https://github.com/dotnet/project-system/pull/5594.
=> Respect IntegratedConsoleDebugging capability

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcher.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/Actions/SearchGraphActionHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphChangeTracker.WeakCollection.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphChangeTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphProvider.IconCache.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphSchema.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/GraphNodeIdExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/IDependenciesGraphChangeTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UI/AddItemDialogService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/IDependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/ProjectRuleHandler.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/TestDependencyModel.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/AnalyzerDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/AssemblyDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/ComDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/DiagnosticDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/PackageAnalyzerAssemblyDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/PackageAssemblyDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/PackageDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/PackageFrameworkAssembliesViewModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/PackageUnknownDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/ProjectDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/SdkDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/SharedProjectDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependencyTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TestDependency.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TestDependencyExtensions.cs
Small clean ups pulled out while looking into graph nodes in the dependencies node.
=> Dependency node bits

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AbstractAddItemCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/DebugTokenReplacer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/ProjectRuleSnapshotExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.State.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/DebugTokenReplacerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PropertyPages/DebugPageViewModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/VersionCompatibility/TestDotNetCoreProjectCompatibilityDetector.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/VersionCompatibility/VersionCompatibilityTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/VisualBasic/VisualBasicProjectCompatibilityProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/VisualBasic/VisualBasicProjectTypeGuidProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/VsSafeProjectGuidServiceTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/WindowsForms/WindowsFormsEditorProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Shell/HierarchyIdTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Telemetry/VsTelemetryServiceTests.cs
Cuts the number of remaining `#nullable disable` directives in the repo from 29 to 15.
=> Annotations

.editorconfig
=> Add rule for usings outside of namespace

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs
Fixes: https://github.com/dotnet/project-system/issues/5545
=> Populate DebugLaunchSettings.Project

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/OutputTypeExValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/OutputTypeValueProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/OutputTypeExValueProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/OutputTypeValueProviderTests.cs
=> Pass comparer to immutible dictionary

build/import/Packages.targets
This gives us access to the new TargetFile image.
=> Update version of ImageCatalog

build/import/Versions.props
We keep forgetting to do this :P
=> Bump version number

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ErrorProfileDebugTargetsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectDebuggerProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/DebugTokenReplacer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchSettingsUIProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/IPersistOption.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfileData.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/WritableLaunchProfile.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/WritableLaunchSettings.cs
Some clean up of the debug namespace.
I've been looking at what it'll take to add remote debugging support.
This namespace has also so far evaded null annotations, mostly due to its complexity and my lack of familiarity. I would like to get it annotated sometime soon.
=> Debug clean up

.editorconfig
This was causing lightbulb to show up.
=> Disable ConfigureAwait analysis

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.LaunchType.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/ProfileCommandNames.cs
Make DebugPageViewModel follow same standards as rest of tree.
=> Move fields/properties/events/nested types

src/Common/ManagedCodeMarkers.vb, src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerRootDesigner.vb, src/Microsoft.VisualStudio.AppDesigner/DesignerFramework/DesignerWindowPaneProviderBase.vb, src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerRootDesigner.vb, src/Microsoft.VisualStudio.AppDesigner/interop/NativeMethods.vb, src/Microsoft.VisualStudio.Editors/DesignerFramework/BaseDesignerLoader.vb, src/Microsoft.VisualStudio.Editors/DesignerFramework/DesignerWindowPaneProviderBase.vb, src/Microsoft.VisualStudio.Editors/PropPages/AdvBuildSettingsPropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/AdvCompilerSettingsPropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/BuildEventCommandLineDialog.vb, src/Microsoft.VisualStudio.Editors/PropPages/BuildEventCommandLineDialogService.vb, src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/CSharpApplicationPropPage.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsDesignerEditorFactory.vb, src/Microsoft.VisualStudio.Editors/SettingsGlobalObject/SettingsGlobalObjectProvider.vb, src/Microsoft.VisualStudio.Editors/interop/NativeMethods.vb, src/Microsoft.VisualStudio.Editors/package/Constants.vb
Also removes redundant numeric suffixes.
=> VB comment cleanup

src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPage.vb, src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPageUserControlBase.vb, src/Microsoft.VisualStudio.Editors/PropPages/AdvBuildSettingsPropPage.vb
Inline methods that implement interface members and only delegate to other methods of the same signature.
=> Simplify interface method implementations

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerWindowPane.vb, src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/CmdTargetHelper.vb, src/Microsoft.VisualStudio.AppDesigner/DesignerFramework/DesignerMessageBox.vb, src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPageUserControlBase.vb, src/Microsoft.VisualStudio.AppDesigner/PropPages/PropertyControlData.vb, src/Microsoft.VisualStudio.Editors/DesignerFramework/DesignerMessageBox.vb, src/Microsoft.VisualStudio.Editors/DesignerFramework/DesignerToolbarPanel.vb, src/Microsoft.VisualStudio.Editors/DesignerFramework/GenericComponentSerializationStore.vb, src/Microsoft.VisualStudio.Editors/HelpKeywords.vb, src/Microsoft.VisualStudio.Editors/Menus.vsct, src/Microsoft.VisualStudio.Editors/PropPages/CompilePropPage2.vb, src/Microsoft.VisualStudio.Editors/PropPages/WPF/ApplicationPropPageVBWPF.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceStringTable.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceTypeEditor.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceTypeEditorTextFile.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourcesFolderService.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourcesFolderService_ResourceEditor.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/AppConfigSerializer.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/ConnectionStringUITypeEditor.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/ProjectUtils.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsDesignerLoader.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsDesignerView.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsSerializer.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsSingleFileGeneratorBase.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/TypeEditorHostControl.vb, src/Microsoft.VisualStudio.Editors/SettingsGlobalObject/SettingsGlobalObjectProvider.vb
- Remove assumptions of gender where it is unknown or irrelevant.
- Recognises non-binary gender.
=> Remove references to gender

tests/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/ProjectFileEditorTests.cs
Been meaning to do this for a while. It was surprisingly painless.
=> Add project file editing integration tests

build/import/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/AbstractExtenderCATIDProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreUnconfiguredInputDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/ProjectDesignerPageMetadata.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/SpecialFilesProviders/VsProjectSpecialFilesManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UI/AddItemDialogService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/LinqExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AbstractItemFileWatchDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/PublishItemsOutputGroupProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/ProjectRuleHandler.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectConfigurationFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/ComponentComposition.cs
Includes temporary suppression of some warnings due to incorrect CPS annotations. CPS PR to fix those is here: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/221897
This also upgrades the VS threading analyzer, which required code changes.
=> Upgrade CPS

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/ProjectImports/ImportTreeCommandGroupHandler.cs
We will never be called with zero selected items.
=> Remove unneed items count check

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.zh-Hant.xlf, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
Moved to the right position in the alphabetical order.
Removed display name since this doesn't display anywhere.
=> Clean up OutDir property

src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.pkgdef
In preparation for #68 this PR cleans up redundant parts of the pkgdef to make diffing easier.
=> PkgDef Cleanup

src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.pkgdef
Last step to make diffing easier for #68
=> Change from Assembly regsitration to Codebase

.github/workflows/issues-to-teams.yml, .github/workflows/post-to-teams.yml, .github/workflows/prs-to-teams.yml
This PR does some cool stuff to set up notifications for PRs but unfortunately the only way to test it is to keep creating new PRs.
=> Setup up notifications for new PRs

.github/workflows/issues-to-teams.yml
Minor tweak of the issue template
=> Get issue number from issue object

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreService.PackageRestoreServiceInstance.cs
NominateProjectAsync will return false in two circumstances:
1) The cancellation token has been cancelled
2) An unhandled error occurred during nomination
Either way, respect this flag so that operation progress doesn't remain pending waiting for the assets file to be generated.
=> Respect NominateProjectAsync failure

src/Microsoft.VisualStudio.Editors/PropPages/AssemblyInfoUtils.vb
Fixes: https://github.com/dotnet/project-system/issues/1419
=> Filter out invariant culture from languages combo

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Imaging/AppDesignerFolderProjectImageProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Imaging/ProjectImageKey.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/AbstractSpecialFolderProjectTreePropertiesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/AppDesignerFolderProjectTreePropertiesProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/AppDesignerFolderProjectTreePropertiesProviderTests.cs
https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/226418 provides a better approach for this.
=> Remove missing folder state for AppDesigner

src/Microsoft.VisualStudio.Editors/PropPages/AdvBuildSettingsPropPage.resx, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.cs.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.de.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.es.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.fr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.it.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.ja.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.ko.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.pl.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.ru.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.tr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/AdvBuildSettingsPropPage.zh-Hant.xlf
Fixes: https://github.com/dotnet/project-system/issues/3792.
I'll wait for 16.6 before I merge this in.
=> Remove "underflow" from /checked description

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
Add DisableCentralPackageVersions for NuGet CPVM scenarios.
=> Add_DisableCentralPackageVersions

build/import/HostAgnostic.props, build/import/VisualStudio.props, build/import/Workarounds.targets
This includes https://github.com/dotnet/project-system/pull/5981, so just review https://github.com/dotnet/project-system/commit/58ce9f95630555f5c928164a9c9e243b3ad887fc
=> Combine EmbedInteropTypes workarounds

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Commands/DependenciesContextMenuProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependencyTreeFlags.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/TargetDependencyViewModel.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/DependenciesViewModelFactoryTests.cs
=> Restore flag name used on target group nodes

build/import/HostAgnostic.props, build/import/Packages.targets, src/Microsoft.VisualStudio.AppDesigner/PublicAPI.Shipped.txt, src/Microsoft.VisualStudio.Editors/PublicAPI.Shipped.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/PublicAPI.Shipped.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Shipped.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Unshipped.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Shipped.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Unshipped.txt
This required upgrading analyzers, which also picked up some bugs resulting in "new" API.
=> Persist nullability into PublicAPI.XXX.txt

Directory.Build.props
Remove a bunch of workarounds that are no longer needed.
=> Remove workarounds

tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectValueDataSource.cs
The receiving type has since been updated to allow nullable options.
=> Remove outdated nullable warning suppression

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AppManifestSpecialFileProvider.cs
Fixes #6009
This regressed in #5475
=> Reference the app.manifest template from the app.manifest special file provider

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/OperationProgress/DataProgressTrackerServiceExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/OperationProgress/ProgressTrackerOutputDataSource.cs
=> Add owner field to make dump investigation easier

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectCapabilitiesMissingVetoProjectLoad.ProjectType.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectCapabilitiesMissingVetoProjectLoad.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.Designer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/ProjectCapabilitiesMissingVetoProjectLoadTests.cs
This veto loads a project with missing capabilities to catch situations such as https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1083914/.
=> Veto loading a project with missing capabilities

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IVsUIService`1.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IVsUIService`2.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/TargetFrameworkMonikersValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Refactor/VisualStudioRefactorNotifyService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredObjects.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredProjectsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/StringFormat.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Utilities/DeconstructionExtensions.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Logging/ProjectOutputWindowProjectLoggerTests.cs
A collection of small things from the last few weeks.
=> Small bits

build/import/Packages.targets
To workaround https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1091660.
=> Move to latest build tools

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectLaunchTargetsProviderTests.cs
Just review:
https://github.com/dotnet/project-system/commit/49bc68dd3493502e2c260baf2376e155636457c4
https://github.com/dotnet/project-system/commit/14aff544fcd4f7791af7db7a8c1218a82a537ad9
=> Refactor ConsoleDebugTargetsProvider

src/Microsoft.VisualStudio.Editors/OptionPages/GeneralOptionPageControl.xaml, src/Microsoft.VisualStudio.Editors/OptionPages/GeneralOptionPageResources.Designer.vb, src/Microsoft.VisualStudio.Editors/OptionPages/GeneralOptionPageResources.resx, src/Microsoft.VisualStudio.Editors/OptionPages/SDKStyleProjectOptionsData.vb, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.cs.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.de.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.es.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.fr.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.it.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.ja.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.ko.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.pl.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.ru.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.tr.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.zh-Hant.xlf, src/Microsoft.VisualStudio.Editors/PublicAPI.Unshipped.txt
This option will be consumed by the file nesting API in CPS and is documented at https://docs.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer
Fixes #6017
=> Add file nesting option to SDK-Style Projects page

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
=> Add ConfigurableFileNesting capability to the managed design time targets

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Commands/ReferenceManagerCommandHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Fixes: https://github.com/dotnet/project-system/issues/6016
CPS PR to respect '0': https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/241815?_a=overview.
=> Turn off Assembly pane in Reference Manager for .NET Core/.NET Standard projects

docs/repo/coding-conventions.md
Presumably the project system concept of "flavoring" has made its way in @davkean's subconsciousness 😄
=> Replace usages of "flavor" with "favor"

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreUnconfiguredInputDataSource.cs
Fixes: https://github.com/dotnet/project-system/issues/5904
We are merging data from configurations into a single value. This can cause data source versions to go back in time when switching from Debug -> Release -> Make some changes -> Debug.
We want to prevent that, so introduce a forward only block that will only publish new versions of a value when it has the same or higher version than the previous value. The expectation is that another value with a more recent data source version will appear shortly afterwards.
=> Prevent restore versions going back in time

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/FSharp/FSharpProjectDesignerPage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/FSharp/FSharpProjectDesignerPageProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/FSharp/FSharpProjectDesignerPageProviderTests.cs
=> Add missing Signing page for F sharp

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/PackageReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.zh-Hant.xlf
Fixes https://github.com/dotnet/project-system/issues/6011. 
Feature design at: https://github.com/NuGet/Home/blob/dev/designs/PackageReference-Extern-Alias.md
=> Add aliases in nomination

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf
This string was changed in master and Dev16.6.
=> Fix build break

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsChangeTracker.cs
Fixes https://github.com/dotnet/project-system/issues/6124
How common is this NFW @davkean ? Do we need this in 16.6?
=> Protect against values missing from dictionaries in TempPE compilation

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreUnconfiguredInputDataSource.cs
Fixes: https://github.com/dotnet/project-system/issues/5904 for 16.6.
We are merging data from configurations into a single value. This can cause data source versions to go back in time when switching from Debug -> Release -> Make some changes -> Debug.
We want to prevent that, so introduce a forward only block that will only publish new versions of a value when it has the same or higher version than the previous value. The expectation is that another value with a more recent data source version will appear shortly.
=> [16.6] Prevent restore versions going back in time

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ActiveWorkspaceProjectContextHost.cs
Workaround for: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/649032/.
If the active config changes after ActiveWorkspaceProjectContextHost calls into the active configuration's host, we can get into a situation where it will start waiting on a configuration that will never complete its work.
This is a temporary workaround, until I can make significant changes to IActiveWorkspaceProjectContextHost to behave and work exactly like IActiveConfigurationSubscriptionService which automatically handles configuration changes by listening to active configuration data flow.
=> Attempt to reduce hang in WorkspaceProjectContextHost

tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/ComponentComposition.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/ComponentVerificationTests.AllExportsTestData.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/ComponentVerificationTests.cs
It probably won't help me falling into this trap, but it will give me something to feel shameful about when I finally track down the issue and realise I could have just run the tests to tell me the problem.
=> Quick test to validate the an export can actually be constructed

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/FrameworkReferenceAssemblyAttachedCollectionSourceProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/TargetFrameworkContentCache.cs
Addresses post-merge feedback on #6136.
=> Target Framework Assemblies follow up

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf
=> Change resource string

build/ci/unit-tests-template.yml
- To be consistent
- To be correct
=> Update descriptions of artifacts

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/DependenciesTreeConfiguredProjectSearchContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/DependenciesTreeSearchProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/FrameworkReferenceItem.cs
=> Remove unused code

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/LaunchTargetPropertyPageValueProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/LaunchTargetPropertyPageValueProviderTests.cs
Fix the LaunchTargetPropertyPageValueProvider to take into account the changes
made in commit 888cb89.
=> Fix LaunchTargetPropertyPageValueProvider

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesProjectTreeProvider.cs
=> DependenciesProjectTreeProvider tidy

src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/TaskSchedulerPriority.cs
=> Remove unused enum TaskSchedulerPriority

build/import/Packages.targets
=> Bump analyzer package versions

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/LanguageServiceErrorListProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/NodeHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/GeneratePackageOnBuildPropertyProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesProjectTreeProvider.cs
=> Use langword for null in XML docs

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/AbstractGenerateNuGetPackageCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageElementHost.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Build/LanguageServiceErrorListProviderTests.cs
Searched with RegEx `/\*\s*\w+\s*\*/` and found these.
=> Use named arguments

src/Microsoft.VisualStudio.ProjectSystem.Managed/PooledObjects/InternPool.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.cs
=> Move InternPool to PooledObjects namespace

build/import/Packages.targets, build/import/Workarounds.targets
=> Remove workaround for Microsoft.VSSDK.BuildTools

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/RelatableItemBase.cs
=> Add documentation cref

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/IDependencyExtensions.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DependencyExtensionsTests.cs
=> Remove unused IDependencyExtensions.HasSameTarget

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependencyTreeFlags.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/SdkAndPackagesDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/IDependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/DependenciesRuleHandlerBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Utilities/SetDiff.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/TestDependencyModel.cs
This PR contains several small fixes which I've pulled out of a subsequent PR in order to make that PR easier to review.
=> Small fixes pulled out of larger work

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/AnalyzerDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/AssemblyDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/ComDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/DependencyGroupModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/DependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/FrameworkDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/PackageDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/ProjectDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/SdkDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/SharedProjectDependencyModel.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/DependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DependencyTests.cs
=> Review changes

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
This reverts commit 68dae79c2acb689747dc516edfca3ce4e35f50ee.
=> Revert "Enable Additional Dependent to detect files added or removed"

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ProjectContextCodeModelProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs
F# doesn't implement symbol model #3664
=> Changed to only be turned on for C# and VB

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/RenamerProjectTreeActionHandler.cs
=> Fix code analysis messages

build/ci/official.yml, build/ci/unit-tests.yml
=> Speed up first use of dotnet.exe

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProjectTypeCapabilities.cs
=> Add comments to ProjectTypeCapabilities

build/import/Versions.props
=> Increase Version

tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs
This test would have flagged the bug fixed in #6323.
=> Add unit test for differences in dependency ID/provider type capitalisation

Launch.cmd, setup/ProjectSystemSetup/Properties/launchSettings.json
- Turn on tree verification and RDT validation
- Turns on item ids in caption for display nodes under DEBUG
- Turns on capabilities tree under DEBUG
- Removed unneeded variables for client debugging as our bits aren't present
=> Turn on CPS diagnostics for debugging

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerLoader.vb, src/Microsoft.VisualStudio.AppDesigner/DesignerFramework/DesignerMenuCommand.vb, src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerLoader.vb, src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerView.vb, src/Microsoft.VisualStudio.AppDesigner/PropPages/SKUMatrix.vb, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ExecutableDebugPropertyPage.xaml.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ParentDebugPropertyPage.xaml.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ProjectDebugPropertyPage.xaml.cs
These showed up after updating builds.
=> Remove more unused suppressions

Directory.Build.targets
=> Remove extra directory separator

src/Microsoft.VisualStudio.AppDesigner/GlobalSuppressions.vb, src/Microsoft.VisualStudio.Editors/GlobalSuppressions.vb, src/Microsoft.VisualStudio.Editors/PropPages/AdvancedServicesDialog.vb, src/Microsoft.VisualStudio.Editors/PropPages/ServicesAuthenticationForm.vb, src/Microsoft.VisualStudio.Editors/PropPages/ServicesPropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/ServicesPropPageConfigHelper.vb, src/Microsoft.VisualStudio.Editors/XmlToSchema/InputXmlForm.vb, src/Microsoft.VisualStudio.Editors/XmlToSchema/PasteXmlDialog.vb, src/Microsoft.VisualStudio.Editors/XmlToSchema/Utilities.vb, src/Microsoft.VisualStudio.Editors/XmlToSchema/WebUrlDialog.vb, src/Microsoft.VisualStudio.Editors/XmlToSchema/Wizard.vb, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/GlobalSuppressions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/GlobalSuppressions.cs
Tracked by: https://github.com/dotnet/roslyn/issues/46075
=> Suppress noise in generated code

build/import/Packages.targets
This upgrades to the latest version on NuGet.
=> Upgrade compiler to latest version

.github/workflows/teams-notifications.yml, build/import/Workarounds.targets
Fix dev16.7.x so it posts PRs into Teams
=> Cherrypick webhook on Teams Workflow

src/Microsoft.VisualStudio.AppDesigner/GlobalSuppressions.vb, src/Microsoft.VisualStudio.Editors/GlobalSuppressions.vb, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/GlobalSuppressions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/GlobalSuppressions.cs
This bug has been fixed in the latest build of master.
=> Remove unneeded suppressions

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsChangeTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcher.cs
=> Simplify publishing values

tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProviderTests.cs
=> Remove unused field

build/import/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ErrorProfileDebugTargetsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/OutputTypeValueProviderBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TargetFrameworkProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsChangeTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsCompiler.CompilationQueue.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Collections/DictionaryEqualityComparer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ImmutableCollectionLinqExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/PooledObjects/PooledDictionary.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ActiveDebugFrameworkServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchSettings.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfileExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettings.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/AssemblyAttributeProperties/AssemblyInfoProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/ActiveLaunchProfileExtensionValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/InterceptedProjectProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/DisposableBag.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Shipped.txt, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchProfileDataTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchProfileTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs
Need to update to new package to fix https://github.com/dotnet/project-system/issues/6470, but this has resulted in a bunch of nullable warnings due to new version of Immutable.
This PR is just about addressing them. The bug above will be fixed in a future PR.
=> Update to new package of LanguageServices/deal with warnings

build.cmd
Automatically open the build log when throwing the /diagnostic switch and we're not running CI.
=> Automatically open build log on /diagnostic

Directory.Build.props
Continuation to #6469. Adding the props file
=> Workaround WPF temp project bug - not detecting correct csc

tests/DeployIntegrationDependencies/DeployIntegrationDependencies.csproj, tests/DeployTestDependencies/DeployTestDependencies.csproj, tests/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/Microsoft.VisualStudio.ProjectSystem.IntegrationTests.csproj, tests/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests.csproj, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.csproj, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client.UnitTests.csproj, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj
These explicit references are not needed.
=> Remove unneeded references

build/import/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/RelationBase.cs, tests/.editorconfig
=> Update analyzer package versions

src/Microsoft.VisualStudio.AppDesigner/PropPages/PropertyControlData.vb, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPage.cs
These were resulting in warnings.
=> Remove unused suppressions

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/RenamerProjectTreeActionHandler.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsThreadedWaitDialogFactoryFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Waiting/VisualStudioWaitContextTests.cs
Simplifying boolean comparisons using Roslynator.
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1049.md
=> RCS1049: Simplify boolean comparison

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/ServiceProviderToOleServiceProviderAdapter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/AssemblyAttributeProperties/AssemblyInfoProperties.cs
Refactor using Roslynator to change if statements with returns to return statements.
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1073.md
=> RCS1073: Convert 'if' to 'return' statement

tests/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/ProjectLayoutTestBase.cs
Small optimisation using AppendLine() instead of Append().AppendLine().
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1197.md
=> RCS1197: Optimize StringBuilder.Append/AppendLine call

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ConnectionPoint/ConnectionPoint.cs
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1089.md
=> RCS1089: Use --/++ operator instead of assignment
