dotnet/project-system

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceContextHost.WorkspaceContextHostInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextProvider.WorkspaceProjectContextAccessor.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextProvider.cs
- Release context on UI-thread
- I was lead to believe that Dispose was free-threaded, but it enforces UI thread and I missed it because of Watson handling.
- Avoid UI-thread check through accessor
- Missed a call through the accessor which hit error reporter, which I missed because it faulted the block.
=> Fix thread affinity of IWorkspaceProjectContext

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/AnalyzerDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/AssemblyDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/ComDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/DependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/DiagnosticDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/PackageAnalyzerAssemblyDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/PackageAssemblyDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/PackageDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/PackageUnknownDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/ProjectDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/SdkDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/SharedProjectDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/IDependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/AnalyzerRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/AssemblyRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/ComRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependenciesRuleHandlerBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/PackageRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/ProjectRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/SdkRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/MetadataExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/DesignTimeTelemetryLoggerProvider.cs
Pushing these small changes ahead of a larger PR based off this, to make the next PR easier to review.
---
Out of curiousity I loaded `Roslyn.sln`, performed a search in the solution, and counted the number of each kind of `DependencyModel` subclass created. Results:
| Type | Count |
|----|----:|
| `AssemblyDependencyModel` | 17,315 |
| `PackageDependencyModel` | 14,819 |
| `PackageDependencyModel` | 7,764 |
| `ProjectDependencyModel` | 3,756 |
| `AnalyzerDependencyModel` | 2,238 |
| `SdkDependencyModel` | 1,218 |
| `PackageAnalyzerDependencyModel` | 1,119 |
| `SharedProjectDependencyModel` | 10 |
| `SubTreeRootDependencyModel` | 5 |
Note this includes the change in 31813b78708fb9f498c58a2e5f8c31e6099a1b50 where root nodes are reused (hence the 5). That number would probably be just under …
=> Reduce work and allocations in dependency node

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependencyIconSetCacheTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyIconSetCache.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphProvider.cs
Optimisations to interlocked operations on immutable collections (while waiting for a clone from TFS).
I didn't change usages in the language service.
The `GetOrAdd` method is a candidate for [ImmutableInterlocked in corefx](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableInterlocked.cs).
=> Immutable interlocked optimisations

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphProvider.cs
VS `GraphNode`s specify their icons as `string`. This string is created from an `ImageMoniker`'s Guid and integer ID.
There are many more graph nodes than distinct icons, hence creating a new string for each node results in a large number of duplicate string objects on the heap. This change results in strings being reused.
Loading `Roslyn.sln` and performing a search in the solution explorer produced the following counts:
|Icon String|Count|Wasted Bytes|
|----|----:|-----------:|
|`ae27a6b0-e345-4288-96df-5eaf394ee369;3644`|12,210|1,172,064|
|`259567c1-aa6b-46bf-811c-c145dd9f3b48;3`|11,491|1,057,080|
|`259567c1-aa6b-46bf-811c-c145dd9f3b48;11`|5,617|516,672|
|`259567c1-aa6b-46bf-811c-c145dd9f3b48;9`|1,423|130,824|
|`259567c1-aa6b-46bf-811c-c145dd9f3b48;1`|1,368|125,764| …
=> Cache ImageMoniker strings, reducing GC heap by 0.5%

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs
Fixes an error I introduced in 77ca8fac8d423fbbfb1a43f5b1d71e0af3cb80f1 that caused many dependency tree nodes to appear with warning icons.
A unit test has been added to ensure this doesn't return.
The misconception in that earlier commit was that the `Add` method replaces items that already present. There is no method on `ImmutableHashSet<>.Builder` that achieves this, so we need the remove/add combo.
=> Fix dependencies node regression

src/Microsoft.VisualStudio.ProjectSystem.FSharp/Microsoft.VisualStudio.ProjectSystem.FSharp.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/CommandLineNotificationHandler.cs
Add a command-line handler that notifies FSharpCommandLineParserService.HandleCommandLineNotifications of the new command-line arguments.
This is the replacement for this logic in the now-defunct class: https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHandlerManager.cs#L213.
=> Add command-line handler for F#

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/IDependenciesChanges.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependenciesChanges.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Shipped.txt
Some fixes that restore the correct presentation of the dependencies node.
As mentioned in #4269, the change in e8d5becd53e75ac5382772124341912ae1eaac14 should not be necessary. As far as I can tell it only changes the order of items in the dictionary, which shouldn't have a bearing on anything of consequence. I'll follow up on that tomorrow.
Also added `Equals`/`GetHashCode` to the custom struct recently introduced in place of the `ValueTuple`. It's used in a set, and the default `ValueType` implementations are slow and likely to cause collisions (it's my understanding they'd only compute the hash code on the first field, `ProviderType` which is commonly duplicated). This
=> Fix dependencies node showing unresolved icons

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
While looking into #4261, a few improvements to the log output were identified.
---
When _no_ outputs are specified, the log gave a misleading message of form:
> FastUpToDate: Earliest write timestamp on output is 31/12/9999 23:59:59 on ''.
Now we print out:
> No build outputs defined.
This would have sped up the diagnosis of the problem.
---
Copied output files (as opposed to built ones) were logged as:
> Checking build output file '{sourcePath}':
This is better explained as:
> Checking copied output (UpToDateCheckBuilt with Original property) file '{sourcePath}':
---
@davkean noticed this message is backwards:
> Build output destination is newer than source, not up to date.
It should read:
> Source is newer than build output destination, not up to date.
---
Finally a non-logging change. …
=> BuildUpToDateCheck improvements

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependencyModelFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IMockDependenciesViewModelFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/ITargetedDependenciesSnapshotFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependencyTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DuplicatedDependenciesSnapshotFilterTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/TreeView/GroupedByTargetTreeViewProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs
This PR contains preliminary work ahead of a change I'd like to follow up with.
The change that's coming is to `ITargetedDependenciesSnapshot` and how its `TopLevelDependencies` and `DependenciesWorld` collections are constructed, primarily to simplify the API such that components are unable to produce invalid state _by design_. This will simplify testing and will also reduce allocations.
That work is based on the following rules:
- `TopLevelDependencies` is the subset of `DependenciesWorld` where `TopLevel == true`
- All `DependenciesWorld` dictionary entries have keys that match their (dependency) value's `Id`
In 29cbdf95741f348588a0734c7ffe904f2ad0ea33 these rules are codified as assertions.
This PR:
- Fixes unit tests that violated the above rules by correcting test data
- Makes a …
=> Dependency snapshot testing

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/AbstractProjectConfigurationProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralConfiguredBrowseObject.xaml
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/680205
This at least solves the 99% case of this property always being hit for SDK projects and correctly handles returning false for the empty string default value. In testing even when RunCodeAnalysis is specifically set to true, none of the other CodeAnalysis* properties are hit.
=> Implement RunCodeAnalysis property to prevent watsons

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TestDependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/OrderingHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/IDependency.cs
For the `Dependency` class:
- Remove the chained constructors to avoid duplicate work when cloning via `SetProperties`
- Make all properties get-only
- Remove unused operator overloads
- Avoid creating an immutable array builder when we know it would end up empty
=> Dependency class optimisations

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/DependencyViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/IDependencyModelExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/PackageFrameworkAssembliesViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/TargetDependencyViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/IDependencyExtensions.cs
Implementations of `IDependencyViewModel` properties generally have fixed values or can delegate to a source object. They're faster to construct and take less memory.
A consequence of this is that `DependencyViewModel` now has a reference to `IDependencyModel`. However these view model objects are very short-lived, being constructed to pass directly to `IDependenciesTreeViewProvider` and `IDependenciesGraphBuilder` which query them on the stack, but don't retain references.
=> Reduce size of dependency view models

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependencyFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependencyModelFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DuplicatedDependenciesSnapshotFilterTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/ImplicitTopLevelDependenciesSnapshotFilterTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/SdkAndPackagesDependenciesSnapshotFilterTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TestDependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/UnresolvedDependenciesSnapshotFilterTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/UnsupportedProjectsSnapshotFilterTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/DependenciesSnapshotFilterBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/DuplicatedDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/IDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/ImplicitTopLevelDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/SdkAndPackagesDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/UnresolvedDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/UnsupportedProjectsSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs
`IDependenciesSnapshotFilter` implementations are the source of a lot of presentation logic for the dependencies node. Keeping this code correct, tested and having good performance is important to the stability and scale of the feature.
`IDependenciesSnapshotFilter` has a moderately complex and implicit contract that's not enforced by the design, though I believe it could be. This PR is a first step towards a design where implementations may not violate the contract.
The 'top-level' dependencies collection is the subset of 'world' dependencies where `TopLevel` is `true`.
Rather than require all filter implementations to correctly manage the top-level collection separately as a `HashSet<IDependency>`, it's possible to just compute that subset when needed directly from the world …
=> Remove topLevelBuilder from IDependenciesSnapshotFilter

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyIconSetCache.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/ImmutableInterlockedEx.cs
This would occur after an optimistic update failed. The loop needs to update the value of `prior` before continuing, otherwise it's an endless loop.
I observed this as a hang when unloading projects in d16.0stg. Let's get this in for the next insertion.
=> Fix endless loop if optimistic set update fails

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerEditorFactory.vb, src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.pkgdef
Our app designer wasn't using the Designer logical view properly which means that when find results were being opened, if the app designer was open, the shell thought it was a valid window to show instead of opening a window with the text view. This fixes that.
~This goes with a CPS pull request (https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/152382) to open the designer with the write logical view. If these changes are inserted without the CPS changes then the app designer will not open from the Properties context menu. It will still open from the Debug -> Properties menu item, but still worth holding off on merging this PR until CPS is ready.~
Turns out the CPS change wasn't necessary, I was just incorrectly not handling the Primary logical view. Fixing that means …
=> Don't handle TextView so opening results from find works

build/Versions.props
removes noise on the commandline build.
=> Do not warn about using a pre-release sdk to build

src/Microsoft.VisualStudio.AppDesigner/Microsoft.VisualStudio.AppDesigner.vbproj, src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
This will no longer fail the commandline build with newer versions of the .NET SDK
=> Do not warn about licensing url being deprecated in future versions

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Utilities/MetadataExtensionsTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Utilities/StringExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/MetadataExtensions.cs
In the debugging for #4323 I was surprised by the output of one of these helper methods. Digging further uncovered a bug masked within a ternary where one value was `default`. The `default` was resolved as a non-nullable type, meaning the intended `null` value was never produced.
Tests added for all these extensions.
=> Test and fix MetadataExtensions

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
This addresses the following customer feedback item https://developercommunity.visualstudio.com/content/problem/255121/launchsettingsjson-modified-on-ide-load-and-branch.html
The only code change was in UpdateAndSaveSettingsInternalAsync which was calling to check out the file even when dontPersist is set to true.
Rest of the change was updating unit tests to verify the correct behavior
=> Fix launchSettings.json modified on IDE load and branch switch

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
Fixes #3744 
//cc: @AndyGerlicher @rainersigwald
=> UpToDateCheck uses first (newest) MSBuildAllProjects only

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySubscriptionsHost.cs
Following discussion in Teams, there doesn't seem to be a reason to switch onto the UI thread to add a subscription.
I've tested this change and it runs without blowing up.
@abpiskunov can you see any issue here?
=> Don't switch to UI thread to subscribe

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/AbstractMultiLifetimeComponentFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/AbstractMultiLifetimeComponentTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceContextHostTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IActiveWorkspaceProjectContextHostFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/PackageRestoreInitiator.PackageRestoreInitiatorInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/PackageRestoreInitiator.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SDKVersionTelemetryServiceComponent.SDKVersionTelemetryServiceInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SDKVersionTelemetryServiceComponent.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AbstractMultiLifetimeComponent.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IMultiLifetimeInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IWorkspaceProjectContextHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceContextHost.cs
This fixes a deadlock when the UI thread is blocked on Loaded, such as during PrioritizedProjectLoad. This occurred because MultiLifetimeComponent.Loaded was backed by a TaskCompletionSource that did not have a JoinableTask relationship to the code that completed it (MultiLifetimeComponent.LoadAsync).
I sat down with Andrew Arnott came up with a design that creates the relationship. I've used the name Publish (mimicking ITreeService, etc) as this method is basically the precursor to #3425.
=>  IWorkspaceProjectContextHost.Loaded -> PublishAsync

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/IProjectDependenciesSubTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/IDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySubscriptionsHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ImmutableCollectionLinqExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/SemaphoreSlimExtensions.cs
While working through #3548 I found a few places we could tighten things up, which I've pulled out into this PR.
- 91560a37e15fa7d797002e124ef1dc72465aa3f8 remove locks made redundant by previous changes
- 21abe962d98829591d296a1213a7960dd3b5970e 144ac2a9d697378454bd6fcc5a8856fde1035bb0 7310b4052000f3a308bcf9632708559dc221cf68 d9c83c6aeacf6cb539326447904e78bff1d5d994 f92789ddb7175bf51d74ecdfc3a811e2815a99f9 reduce allocations
- 2cd92e1e95e03b7d088ebdb1a2a5aa2aa060c064 documentation
=> Locking, allocations, documentation and cleanup

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Properties/CSharpProjectDesignerPageProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/MigrateXprojProjectFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS/ProjectSystem/VS/Properties/FSharpProjectDesignerPageProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectDebuggerProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/OrderingHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/StartupProjectHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/TargetFrameworkMonikersValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContextProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/DesignTimeTelemetryLogger.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Build/BuildUtilities.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/PooledObjects/ObjectPool.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/PooledObjects/PooledArray.DebuggerProxy.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/PooledObjects/PooledArray.Enumerator.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/PooledObjects/PooledArray.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/PooledObjects/PooledDictionary.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/PooledObjects/PooledHashSet.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/PooledObjects/PooledStringBuilder.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredProjectsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/BaseProjectConfigurationDimensionProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/ImplicitlyActiveDimensionProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ContextHandlerProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/UnconfiguredProjectContextProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/AssemblyAttributeProperties/AssemblyInfoProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Text/StringBuilderExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/Properties/VisualBasicProjectDesignerPageProvider.cs
Roslyn has an internal implementation of object pools that they ship as a [source based nuget package](https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis.PooledObjects/2.11.0-beta3-63519-01).  Unfortunately we cannot consume this package directly without changing our build infrastructure.  
I've added them here as a generalized machanism for re-using common builder objects.
=> Use object pool

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerView.vb, src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/DesignerTabButton.vb, src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/DesignerTabControl.vb, src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerView.vb
This is a fix for: [646608](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/646608/) and [646587](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/646587/)
In the WinForm property pages, tabbing at the last item in a page will take you to the page's title tab item. For example, tabbing at the "Advanced..." button on the Build property page (the last control on the page) would take you to the "Build" tab. But, If you tabbed again, it would not take you back into the property page as expected, but go down to the next title tab item. There was no way to tab back into the property page, and tabbing kept you in the property page named tabs.
The base for this PR is https://github.com/dotnet/project-system/pull/2666. It is contained in the first commit.
To make the previous comments …
=> Fixing Tab and Shift-Tab behavior on Property Pages

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IUnconfiguredProjectVsServicesMock.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactoryTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactory.cs
In the new language-service integration, we pass the real hierarchy to Roslyn. Make sure Razor gets the same hiearchy.
=> Use "real" hierarchy for Razor

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/TargetFrameworkProvider.cs
Fixes #2714, which identified `TargetFrameworkProvider.GetTargetFramework` as a source of high contention, albeit under the influence of a since-fixed evaluation loop bug.
`GetTargetFramework` looks up `ITargetFramework` instances by name. It did this via O(N) scanning of a mutable list within a lock (where N is usually a very small number, but still required the protection of a lock).
This change introduces lock-free caching of these instances using O(1) lookup in an immutable dictionary keyed by the input string. Cache misses should be very rare. Hits are now the fast path and have zero contention.
=> Remove lock from TargetFrameworkProvider

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TestDependencyExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/DuplicatedDependenciesSnapshotFilter.cs
CPU profiling shows about 50% of `DependenciesSnapshot.FromChanges` time was spent in `DuplicatedDependenciesSnapshotFilter.BeforeAddOrUpdate`, mostly enumerating immutable dictionaries.
On loading `Roslyn.sln` <sup>1</sup> we spent 4% CPU time producing dependencies snapshots, half of which was in this method:
The normal case here is that no duplicate caption is found. This change halves the number of iterations required.
I'm looking at separating handling of top-level and non-top-level nodes across the dependencies node, at which point the number of items being iterated will drop considerably, along with that CPU percentage. In the meantime, this is an easy win.
<sup>1</sup> Based on a 30 second PerfView capture started when the "Preparing projects" dialog disappears.
=> Merge consecutive iteration loops

src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/SemaphoreSlimExtensions.cs
These unused forms do not use `JoinableTaskCollection` and are prone to deadlocks in certain cases.
Relates indirectly to #2117, which covers a hang on the use of these now-removed methods.
=> Remove unused SemaphoreSlimExtensions methods

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySubscriptionsHost.cs
This host class will always create a snapshot, and there's no reason it can't be created in the constructor.
=> Remove property laziness

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
Relates to #2707, which identifies this as an expensive operation.
=> Only call GetActiveConfiguredProjectExports when needed

src/Microsoft.VisualStudio.Editors/PropPages/AssemblyInfoPropPage.vb
Fixes: [646590](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/646590/)
On the Assembly Information property page, if the Neutral Language ComboBox is dropped down the escape key will close both the ComboBox and the property page. This will preview the key pressed and not close the property page if escape was used to close the ComboBox.
=> Fix both NeutralLanguageComboBox and AssemblyInfoPropPage closing on Escape

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Extensibility/IProjectExportProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Extensibility/ProjectExportProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/AggregateDependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySubscriptionsHost.cs
To keep the size of a future PR down a bit, here's a grab bag of small tidy ups.
The only functional change here is in e89b1f955024d2860a7c2b24c96554a8054c6aaf which fixes a memory leak in `AggregateDependenciesSnapshotProvider` in cases where the project path changes, as it will not be removed from its collection.
=> Small bits pulled from larger work

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Following @davkean's comments in #4376, this PR adds the `DynamicDependentFile` capability via `Microsoft.Managed.DesignTime.targets`.
=> Add project capability DynamicDependentFile via targets

build/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IActiveDebugFrameworkServicesFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IEnvironmentHelperFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/ITokenReplacerFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsDebugger10Factory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs, src/VisualStudio.props
Fixes: https://github.com/dotnet/project-system/issues/3667 for new project system.
The integrated console experience causes F5 to leave the console open similar to CTRL+F5, but unlike CTRL+F5 it will reuse the window on future F5s. When turned on (by default), it affects both F5 and CTRL+F5. It has added advantage of being able to snap the console window next to VS, and continually F5 over and over again without it changing position.
It can be dismissed by pressing a key while it is open, or can be turned off by checking _Tools_ -> _Options_ -> _Automatically close the console when debugging stops,_ after which the old behavior is reinstated.
**CTRL+F5:**
**F5:**
This required to me move more code than I'd like due to the order in which things were calculated.
=> Opt into the new integrated console experience

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ActiveWorkspaceProjectContextHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IWorkspaceProjectContextHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceContextHost.WorkspaceContextHostInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceContextHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHostInitiator.cs
- Add an implemention IActiveWorkspaceProjectContext for the new language service integration
- This lets non-multi-targeting aware consumers to use the "active" configuration's version of the workspace host
- Ensure that we've initialized the language service before project load has completed
This is the last of the changes needed to make the language-service rewrite work.
=>  Add an implemention of IActiveWorkspaceProjectContext for new language service

build/Default.ruleset
dotnet/roslyn-analyzers#1861 has since been fixed, so the comment can be removed. Rules in this group are meta-analyzers that apply to the source code of analyzers themselves.
We do not have any analyzers in this repository so it's fine to disable these diagnostics.
RS1014 (DoNotIgnoreReturnValueOnImmutableObjectMethodInvocation) is kept as it's of general use.
=> Update meta analyzers in ruleset

ProjectSystem.sln, docs/Documentation.csproj
This brings the documentation files into the solution so that they are easier to edit and appear in search results.
This probably shouldn't be a `csproj` file. If there's a better project format that allows globbing and is in-box, let me know.
I looked at shared projects but concluded they didn't support globbing (IIRC&mdash;I authored this a while back).
=> Add minimal project for documentation

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Fixes #4397
I've tested this and it works for C# and VB projects, but for some reason doesn't for F# projects. Hopefully someone knows why, or its just my local environment being weird. I can't see F# opting out of `DefineCommonManagedCapabilities` or anything, but I don't really know where to look either.
=> Add AppServicePublish capability to all SDK projects that output to exe

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContextProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySubscriptionsHost.cs
> I have a [branch](https://github.com/drewnoakes/project-system/tree/dep-node-review) with 65 small and focussed commits that improve the approachability of the dependencies node code by moving things around, remove duplicate code, document APIs, as well as reducing allocations and locking. These commits complete my end-to-end review of the dependencies node, and my ongoing work targetting specific bugs continues from the tip of that branch.
This PR is the first few commits and should be reviewable on its own. I'll feed the rest in as they're reviewed.
- Move code to local functions
- Reduce logic in AggregateCrossTargetProjectContext
- Merge consecutive locks into a single lock
=> Dependencies subscription host part 1

build/Default.ruleset, build/Versions.props, src/Microsoft.VisualStudio.Editors/SettingsGlobalObject/SettingsGlobalObjectProvider.vb
Relates to #4377
~These changes fix the errors, but looking at these I wonder whether the types wouldn't failed serialisation anyway, and if it wouldn't be better to just make them non-serialisable.~
=> Enable CA2235 (non serializable fields on serializable types)

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/TreeView/DependenciesTreeViewProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesTreeViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/Actions/SearchGraphActionHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/Actions/TrackChangesGraphActionHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphChangeTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/IDependenciesGraphChangeTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/ViewProviders/GraphViewProviderBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/ViewProviders/IDependenciesGraphViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/ViewProviders/PackageGraphViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/ViewProviders/ProjectGraphViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/PackageFrameworkAssembliesViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/AggregateDependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/IDependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySubscriptionsHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/RuleHandlers/DependenciesRuleHandlerBase.cs
Following #4429, more changes to the dependencies node's tree and graph logic.
In particular:
- 97f66bb6c18c2c1a9c6cf25867e1470b64c1e381 Rename `GroupedByTargetTreeViewProvider` to `DependenciesTreeViewProvider`
- 6cdde4b36082aa654bfac3e6b1f957586d840222 Extract tracking of changes to graph contexts from `DependenciesGraphProvider` to new `DependenciesGraphChangeTracker` class
- 81b81c0a1268f305f7ff71c2e6a1725e3bdfcc63 More API documentation
- da983990ed8294a6644753d95df2b2ab0089eb90 Remove duplication of project path from `IDependenciesSnapshotProvider` and its snapshot&mdash;allow the snapshot to be the source of truth over time, as mentioned in https://github.com/dotnet/project-system/pull/4386#discussion_r241693587
- 141f7453c1f4984d69aca64164c411d28c6c8b13 Remove `JTF.RunAsync` from …
=> Dependencies tree and graph changes

src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests/ProjectSystem/VS/Properties/VisualBasicProjectDesignerPageProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/Properties/VisualBasicProjectDesignerPage.cs, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/Properties/VisualBasicProjectDesignerPageProvider.cs
Needed this to do some testing for TempPE.
We don't show the Signing property page for Visual Basic projects. Seems to work fine once added though, which can't be said of F# so will leave #3660 open.
=> Show the signing page in the App Designer for VB

build/Versions.props
Includes fix for compile warning in dotnet/roslyn-analyzers#1985.
=> Bump Roslyn analyzers

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/ICrossTargetSubscriptionsHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs
Relates to #2707 which reports high CPU time in JTF overhead due to lock via `ExecuteWithinLockAsync`.
`AggregateCrossTargetProjectContext` is (now) immutable. Only updates to `_currentAggregateProjectContext` need be serialised via locking. For reads, any race that exists after removing this read lock existed before.
=>  Remove redundant locking in DependenciesSnapshotProvider 

src/Microsoft.VisualStudio.Editors/SettingsGlobalObject/SettingsGlobalObjectProvider.vb
Provides an alternative fix to that in #4402 where we enabled an analyzer that detects serializable types with non-serializable fields.
The VS shell needs this type to be serializable even though it must not be doing any serialization (or was swallowing exceptions).
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/765098
=> Make ConcreteApplicationSettings Serializable Again

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/ImplicitTopLevelDependenciesSnapshotFilterTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/ImplicitTopLevelDependenciesSnapshotFilter.cs
Fixes: https://github.com/dotnet/project-system/issues/2688
Added a check for SharedProjectDependency flag in ImplicitTopLevelDependenciesSnapshotFilter. Before the check it would be marked as implicit, and there would be no 'remove' option in the context menu.
The reason, to the best of my knowledge, that this was needed is that a shared dependency is _not_ a project reference and therefore not added to the catalog as a project reference. So, in [`DependenciesSnapshotProvider`][DependenciesSnapshotProvider], the shared project is not added to the projectItemsSpecs so the check in ImplicitTopLevelDependenciesSnapshotFilter will mark it implicit.
[DependenciesSnapshotProvider]:           /src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/De …
=> Fixed Shared Projects not being able to be removed from the context menu

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs
Reduces the amount of enumeration.
Following suggestion by @jmarolf in https://github.com/dotnet/project-system/pull/4440#pullrequestreview-190241568.
=> Optimise linq a bit

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectInstancePropertiesProviderFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptedProjectProperties/AssemblyOriginatorKeyFileValueProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptedProjectProperties/InterceptedProjectPropertiesProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptedProjectProperties/TargetFrameworkValueProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/InterceptedProjectPropertiesProviderBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ProjectFileInterceptedViaSnapshotProjectPropertiesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
CPS supports tagging properties providers that can get property values from a ProjectInstance, which is more efficient, so this PR creates a new provider that opts into it (via the `HasEquivalentProjectInstancePropertiesProvider` metadata), and then moves any of our intercepted properties that are compatible with it, to that provider.
Compatibility was determined by simply testing within Visual Studio - TargetFrameworkMonikers fails here, as it needs access to all configured projects, which is not available sometimes with this model - and by querying each property via DTE - PreBuildEvent and PostBuildEvent fail here because of a NotSupportedException in the PageProperty class.
The two tests in `InterceptedProjectPropertiesProviderTests.cs` have been cribbed from the now-reverted …
=> Support getting compatible property values via GetCommonProperties

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PackageReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ProjectReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.zh-Hant.xlf
AS part of https://github.com/NuGet/NuGet.Client/pull/2271 We added a new feature to generate msbuild property to nuget package path if someone set `GeneratePathProperty` on a `PackageReference`. But Project system wasn't updated to pass this new metadata to NuGet as part of nomination.
This PR is to pass that and pass this new metadata to NuGet.
=> Passing GeneratePathProperty metadata as part of nomination

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsService`1.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsUIService`1.cs
Turn class fields into capture class fields which will get collected when the delegate falls out of scope (when the AsyncLazy/Lazy value is created).
=> Reduce the number of fields in VsService/VSUIService

build/CIBuild.cmd
testing to see if installing the dotnet sdk is what is causing our builds to be cancelled
=> do not install the dotnet-sdk on build machines

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
While the ProjectSubscriptionService will look in Project, File *and* ProjectSubscriptionService for rules to use for its data (see ProjectSubscriptionService.NamesOfCatalogsToTry in CPS), this data isn't need for the project tree so move it to ProjectSubcriptionService only.
=> Move LanguageService rule to ProjectSubscriptionService

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AppDesignerFolderProjectTreePropertiesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectRootImageProjectTreePropertiesProvider.cs
Test icon provider and ourselves were both marked with zero priority, resulting in us being defined in whatever order MEF returned. Make it explicit.
Test provider from the Unit Testing team will update to be higher than us.
=> Apply consistent order for tree providers

docs/repo/dependencies-node-roadmap.md
Adds some documentation on the various identifiers used through the dependencies node, following #4513.
Also adds some brief information on the extensibility model for the dependencies node.
=> Document IDs in the dependencies node

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/None.xaml
These properties were accidentally removed as part of the rule cleanup, add them back as they are required to make basic functionality work.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/752977
Fixes: https://github.com/dotnet/project-system/issues/4507
~This is still a WIP as even with these properties, https://devdiv.visualstudio.com/DevDiv/_workitems/edit/752977 isn't resolved.~ All fixed.
=> Add back needed properties to None.xaml

src/Microsoft.VisualStudio.Editors/Common/Utils.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/CSVEncoder.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/Resource.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb
When a project has a RESX with a linked resource file, and that file is missing on disk, Visual Studio crashes when you attempt to drag drop the resource to another application.
Also avoided NFW in these situations - these exceptions are expected to occur.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/785726.
=> Avoid crash via resource drag drop

src/Directory.Build.props
About to ban additional APIs such as Task.Run which is used extensively throughout it. There's no need to enforce this in test projects.
=> Turn off banned APIs for the test projects

src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPageUserControlBase.vb
This was regressed here: https://github.com/dotnet/project-system/commit/0f703e739aade8e590b8f881583b736122a04e21#diff-81707917a7981f2eb7606e2abfd61343R286
DISPID_UNKNOWN became set to itself, ie `0`, when it should have been `-1`.
I've restored it and added a comment.
Fixes #4549
=> Fix regression in app designer picking up project file changes

src/Directory.Build.props, src/Directory.Build.targets, src/HostAgnostic.props, src/VisualStudioDesigner.props
Adding additional APIs to the BannedSymbols in the future that are very specific to the project system such as IServiceProvider, just opt out to avoid us having to suppress all usage.
=> Opt out of banned symbols in AppDesigner/Editors

src/BannedSymbols.txt, src/Directory.Build.props, src/Directory.Build.targets, src/HostAgnostic.props, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/GlobalJsonRemover.cs, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/MigrateXprojProjectFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS/Packaging/FSharpProjectSystemPackage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IServiceProviderExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/HACK_AddItemHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/NodeHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/StartupProjectHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsService`1.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsService`2.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsUIService`1.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsUIService`2.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/ServiceProviderToOleServiceProviderAdapter.cs, src/VisualStudioDesigner.props
This includes https://github.com/dotnet/project-system/pull/4555 so only review https://github.com/dotnet/project-system/pull/4556/commits/9e5672dafca8f8518be1e044571ce8f3da43ea01.
Ban IServiceProvider/IAsyncServiceProvider usage
IVsUIService/IVsService should be used instead. Existing usages are baselined and being tracked by #4375.
=> Ban IServiceProvider/IAsyncServiceProvider usage

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/IDependencyCrossTargetSubscriber.cs
The dependencies node currently receives both evaluation and design time data updates via DataFlow from CPS, each from its own block.
A single block is guaranteed to not overlap async data callbacks, but because we have two we require synchronisation between them.
**NOTE** This is not urgent and can wait to be merged, or changed to target a different branch.
=> Serialise dependencies node data updates

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IActiveEditorContextTrackerFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextHostInstanceTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/ActiveEditorContextTrackerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ActiveEditorContextTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IActiveEditorContextTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/782754.
Avoid blocking on initialization of the active workspace context just to get the default workspace context id for a multi-targeting projects it hasn't been set. Instead, just return the first one that is registered. This returns the behavior to what it was previously before the new language-service integration was checked in. 
This means that there is a chance that it may return no longer the "active configuration" context but instead the first one to register itself - but practically won't occur because we block on the active config registration in WorkspaceProjectContextHostInitiator.
Due to a flaw in the new integration, there's timing bug where IActiveWorkspaceProjectContext.OpenContextForWrite can hang (or never …
=> Fix hang in GetWorkspaceContextIdFromActiveContext

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/DependenciesViewModelFactoryTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesTreeViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/DependenciesViewModelFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Composition/OrderPrecedenceImportCollectionExtensions.cs
- Fix NRE for unknown provider type by returning and handling `null`. Fixes #3653.
- Pass correct comparer for use when looking up providers by type. Was previously using `Ordinal` (via `EqualityComparer<string>.Default`) rather than the required `OrdinalIgnoreCase`.
=> Dependency node ProviderType fixes

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
This log message was backwards and potentially misleading.
=> Fix incorrect UpToDateCheck log message

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/GetProfileNameDialog.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.Designer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Unshipped.txt
Fixes for [785764](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/785764/) and [786001](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/786001/)
Adds AutomationProperties.HelpText to 5 items in the debug property page and the new profile dialog. These strings are read by screen readers to give a better description of what will actually happen when the buttons are used - especially when the result is a UI only change. The strings were just first intuitive strings I thought of - I would appreciate any input @cartermp @AbhitejJohn 
New Button (Debug Property Page) - Open the new profile dialog
Delete Button (Debug Property Page) - Delete the current profile and change to the next available profile
Launch Browser Checkbox (Debug Property Page)  - Checking enables a textbox to …
=> Add accessible help text to the debug property page

src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Shipped.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/CancellationSeries.cs
This type was not intended for consumption outside this repo and should have been internal.
This type will exist in 16.0, but the the likelihood of someone taking a dependency on it is very small, and if someone found it useful they could always copy the source from this repo directly. It's a small type.
=> Make CancellationSeries internal

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs
These tests are used to determine whether a parent dependency tree node should be displayed as unresolved. If an invisible child makes the parent unresolved, it's confusing to the user.
For example, the NuGet node may be unresolved and the unresolved package supplies an SDK, and is hidden from the tree. In such a case, the SDK node will be marked as unresolved, and annotating the NuGet node is just confusing and misleading.
Fixes #4577.
=> Unresolved child test excludes non-visible children

src/Microsoft.VisualStudio.Editors/PropPages/PackagePropPage.vb
Fix for: [795312](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/795312)
Switching the radio button choice from Package License Expression to Package License File does not properly set the value of PackageLicenseExpression to empty in the project file. It needs to be explicitly set to dirty so that it will pick up the change.
=> Ensure PackageLicenseExpression property is set

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/ActiveEditorContextTrackerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ActiveEditorContextTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IActiveEditorContextTracker.cs
#4563 caused ActiveEditorContextTracker to be scoped across the solution instead of per project, resulting in the "default" context for a project to be the first one registered across the solution, instead for the project. This broke Razer for solutions with more than one project.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/795781.
tag @jjmew for approval.
=>  Scope ActiveEditorContextTracker per project

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectDebuggerProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/DotNetCoreProjectCompatibilityDetector.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/AbstractGenerateNuGetPackageCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactory.cs
Fields don't need to restate the service type - it's only needed for the import.
=> Simplify IVsService<T>/IVsUIService<T>

src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Xproj/MigrateXprojProjectFactoryTests.cs, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/Packaging/CSharpProjectSystemPackage.cs, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/CSharpProjectCompatibilityProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/CSharpProjectTypeGuidProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/MigrateXprojProjectFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS.UnitTests/ProjectSystem/VS/FSharpProjectSelectorTests.cs, src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS/Packaging/FSharpProjectSystemPackage.cs, src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS/ProjectSystem/VS/FSharpProjectSelector.cs, src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS/ProjectSystem/VS/FSharpProjectTypeGuidProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/ProjectType.cs, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/Packaging/VisualBasicProjectSystemPackage.cs, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/VisualBasicProjectCompatibilityProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/VisualBasicProjectTypeGuidProvider.cs
In preparation for merging of the language-specific dlls & packages, centralize ProjectType GUID definitions into a single type.
=> Centralize ProjectType usage

CONTRIBUTING.md, Directory.Build.props, README.md, docs/repo/debugging/tracing.md, docs/repo/roadmap.md, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Build/LanguageServiceErrorListProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectDebuggerProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfileData.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/AppDesignerFolderProjectTreePropertiesProvider.cs
https://github.com/drewnoakes/roslyn-project-system is the old name of this repo and currently redirects to this repo.
=> Update GitHub URL

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
Previously it was possible for an update to occur during the up to date computation. Its collections are not thread safe so could report incorrect values or even raise exceptions.
This commit makes the following changes:
- Derive from `OnceInitializedOnceDisposedUnderLockAsync`
- Export `IProjectDynamicLoadComponent` to respond to project capabilites
- Perform update and query within `ExecuteUnderLockAsync` for isolation
=> Synchronise up-to-date check query and project updates

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProjectTypeRegistration.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSPackage.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.csproj, src/ProjectSystemSetup/ProjectSystemSetup.csproj, src/ProjectSystemSetup/source.extension.vsixmanifest
Fixes part of https://github.com/dotnet/project-system/issues/3817.
This package was never used and was solely present to find two strings. Delete package and move registration to Managed.VS.
=> Remove VisualBasicProjectSystemPackage

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/CSharp/CSharpSyntaxFactsServiceTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/VisualBasic/VisualBasicSyntaxFactsServiceTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/CSharp/CSharpProjectTypeGuidProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/CSharp/CSharpSimpleRenamerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/VisualBasic/VisualBasicSimpleRenameTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/VisualBasic/VisualBasicProjectTypeGuidProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/CSharp/CSharpProjectTypeGuidProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/FSharp/FSharpProjectTypeGuidProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VisualBasic/VisualBasicProjectTypeGuidProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/CSharp/CSharpSyntaxFactsService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/VisualBasic/VisualBasicSyntaxFactsService.cs
These components use no project state, or store state on a per project basis, push to them out to the global scope so that they can be shared across all C#/VB/F# projects. In a 1000 project-solution, this reduces the number of these components from 1000 to 1.
=> Move components out of UnconfiguredProject-scope

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
Fix for: https://github.com/dotnet/project-system/issues/4622
Even if the logic in HandleLaunchSettingsFileChangedAsync was regressed and a different change is needed, we should probably still have this check.
=> Make HandleLaunchSettingsFileChangedAsync return Task.CompletedTask

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/CSharp/CSharpCodeDomProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/VisualBasic/VisualBasicCodeDomProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/CSharp/CSharpCodeDomProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/VisualBasic/VisualBasicCodeDomProvider.cs
This mimics legacy behavior. Consumers of IVSMDCodeDomCreator.CreateCodeDomProvider always get a new version of the CodeDomProvider, in CPS we were sharing this per project.
CodeDomProviders indirectly have mutable state via the underlying generators that keeps track of statement depth and options.
There is no current bug that this fixes, but as we start addressing UI delays, async editors we might start using these provides off UI thread, and want to avoid having designers overlap their usage, which would only be a problem in CPS.
=> Always return a new CodeDomProvider

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/RuleHandlers/DependenciesRuleHandlerBase.cs
This could be triggered by changing the TFM from netcoreapp2.2 to net4.5. In that case:
- A DTB fires off a change
- `removedItem` is "Microsoft.NETCore.App"
- The removed rule is "ResolvedSdkReference"
- The "OriginalItemSpec" item property is an empty string
- `GetStringProperty` therefore returns `null` which is assigned to `dependencyId`
- `shouldProceed` is a delegate referencing `IReadOnlyDictionary<,>.ContainsKey`, and throws ANE for the null key
Although this exception would be thrown back into the Dataflow block, changing the TFM causes new Dataflow subscriptions to be created, so the UI stabilises eventually, with or without this exception.
Using `removedItem` in place of the OriginalItemSpec allows the removal to continue correctly.
=> Prevent ANE when removing item with empty OriginalItemSpec

.editorconfig, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/.editorconfig
Two space indent makes sense for the rules, but I think four spaces is easier to work with - especially for WPF.
=> Only Apply Two Space Indent on Rules

src/Microsoft.VisualStudio.Editors/PropPages/PackagePropPage.vb
Fix for https://github.com/dotnet/project-system/issues/4633
When a user selects a License item, it will first try to find an existing item with the same Include attribute as the selected relative path. In a case where there was no existing license item chosen and an item had an empty Include and either a Remove or Update attribute there would be a System.InvalidOperationException because it would try to add the Include but items can only have one of Include, Update or Remove. 
This will ensure that we don't even try to look for the item if the previous include value is empty. We should only be modifying an item that has exactly the same Include.
=> Add check for empty Include attribute when adding License item 

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.Designer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Unshipped.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchSettingsUIProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Unshipped.txt
Fix for https://github.com/dotnet/project-system/issues/1125
Assuming I am reading the issue correctly, this only changes "nativeDebugging" in launchSettings.json for the currently selected profile 
Adds the check box to the bottom:
Like non-Core projects:
=> Add Native Code Debugging CheckBox to the Debug prop page

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/NuGet/ProjectRestoreInfoBuilderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/PackageRestoreInitiator.PackageRestoreInitiatorInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectRestoreInfoBuilder.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ProjectReference.xaml
We were calculating full path ourselves, when we can just pull it from the built-in metadata.
=> Use FullPath metadata instead of calculating ourselves

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Added basic WPF and WindowsForms capabilities, as well as one for XBAP for property pages, just in case. Legacy WPF flavors detect XBAP just by checking the `HostInBrowser` property so I've just mimicked that.
We might need more differentiation later in these, for different target frameworks, but I figure that can come later.
Fixes #4248
=> Add WinForms, WPF and XBAP capabilities

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/DotNetCoreProjectCompatibilityDetector.cs
Fixes internal bugs
- [819419](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/819419)
- [739377](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/739377)
Now that our package is initialized in the background there is no gurnatee that we will be initalized as soon as the solution is opened.  We may be initialized at any point after the solution is opened.
This change makes sure that as soon as we are initialized, if the solution has finished opening, we check version compatibilty.
=> smallest possible change to fix race in DotNetVersionCompatibility

build/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IDataProgressTrackerServiceFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IDataProgressTrackerServiceRegistration.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextHostInstanceTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextHostTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/DependenciesViewModelFactoryTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/OperationProgress/DataProgressTrackerServiceExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/OperationProgress/OperationProgressStageId.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/OperationProgress/ProgressTrackerOutputDataSource.cs
**Background**
In the old day of the legacy project system, after solution load had completed - the project was guaranteed to have finished running a IntelliSense & references design-time build. Also modifications to the projects also were guaranteed to have finished running design-time builds by the time the API that modified the project had returned. 
This was a simple life and meant designers could open and query the project for stuff that required a design-time (such as CodeModel or references) without worrying if the data was present. Either it was present and the design-time build completed, or it wasn't and the design-time build failed. There was no querying an in-between "in progress" state.
In turns out design-time builds are slow, this resulted in large solution load times and …
=> Opt into operation progress

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
The CPS bug that blocked this has been resolved so no point not merging this.
Fixes #4479
=> Support Data Source Window for .NET Framework and .NET Core 3.0

src/HostAgnostic.props
=> remove unneeded test dependencies

build.cmd, build/build.ps1
- Always produce NuGet packages during build (this was inadvertently turned off during last infrastructure move). An internal team is building our bits/consuming them and wasn't obvious how to turn this on
- Stop tying GenerateDependentAssemblyVersionFile to "pack" - it's tried to VS insertion assets which we always produce
- Fix GenerateDependentAssemblyVersionFile so that it handles incremental, it was failing if the direction already existed and appending to the file if existed
=> Always produce NuGet packages

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/BuildOptionsFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/AnalyzerConfigItemHandlerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/BuildOptions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/FSharp/FSharpBuildOptions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AnalyzerConfigItemHandler.cs
Basic support for harvesting .editorconfig files from the command line and passing it to the language service via `IWorkspaceProjectContext`.
This breaks out some of the changes in #4619.
=> Pass .editorconfig files to LS

.gitignore
Update the gitignore file to not list some of the CIBuild.cmd artifacts that are created for integration tests
=> Ignore integration test artifacts

build/Packages.targets, build/Toolset.proj, build/Versions.props, build/build.ps1
Add a media-recorder-logger to integration tests run with CIBuild.cmd so its easier to diagnose failures
=> save a video video on integration test runs

build/build.ps1
Ensure that integration tests run using build.cmd fail the build appropriately
=> fail build on failed test run

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/DotNetCoreProjectCompatibilityDetector.cs
small fix that ensures we queue a download of the setting file if one does not exist on startup
=> ensure that the cache file is downloaded

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/AdditionalFiles.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/AdditionalFiles.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/ApplicationDefinition.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/ApplicationDefinition.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Compile.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Compile.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Content.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Content.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/EmbeddedResource.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/EmbeddedResource.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/None.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/None.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Page.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Page.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Resource.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Resource.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/XamlAppDef.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/XamlAppDef.xaml
Needed for #4163 but also parity with legacy.
=> Add missing DesignTimeSharedInput property from File and BrowseObject Rules

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Threading/Tasks/TaskDelaySchedulerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/ITaskDelayScheduler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/TaskDelayScheduler.cs
Part of #4163
This adds a mechanism to TaskDelayScheduler to run a task without delay, cancelling any pending tasks that hadn't run yet.
=> Allow running a task on a TaskDelayScheduler immediately

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Automation/VsLangProjectPropertiesTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VsBuildManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VsProject.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs
Part of #4163
Initially this implementation just matches the [CPS implementation](https://devdiv.visualstudio.com/DevDiv/_git/CPS?path=%2Fsrc%2FMicrosoft.VisualStudio.ProjectSystem.VS.Implementation%2FPackage%2FAutomation%2FVSProject%2FOAVSBuildManager.cs&version=GBmaster). The two TempPE related methods will be filled out in a future PR.
=> Provide an implementation of VSLangProj.BuildManager

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
An internal customer reported seeing this message when building twice in a row. This extension to the log message would help identify why this seemingly incorrect behaviour occurs.
=> Extend up to date check log message

build/Packages.targets, build/Versions.props, src/Directory.Build.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PotentialEditorConfigDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PotentialEditorConfigFiles.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PotentialEditorConfigFiles.xaml
Add an `IFileWatchProviderDataSource` for potential .editorconfig files.
Note that this is dependent on the changes in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/171765 so you may want to review that first.
=> Add an IFileWatchProviderDataSource

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/NuGet/ProjectAssetFileWatcherInstanceTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectAssetFileWatcher.ProjectAssetFileWatcherInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectAssetFileWatcher.cs
This marks ProjectAssetsFileWatcher with "PackageReferences". Given that PackageReferences is a dynamic capability this involved moving over to IProjectDynamicLoadComponent as per https://github.com/dotnet/project-system/blob/master/docs/repo/loading-components-with-projects.md.
The diff is much easier if you skip the first one, which is just a boilerplate move to that pattern, and just read the commits onwards which are changes to the existing code.
This opens ProjectAssetsFileWatcher for other uses as called out in https://github.com/dotnet/project-system/issues/2491.
=> Mark ProjectAssetsFileWatcher with "PackageReferences"

src/BannedSymbols.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ConnectionPoint/ConnectionPoint.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/AbstractAddClassProjectCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/AbstractGenerateNuGetPackageCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectAssetFileWatcher.ProjectAssetFileWatcherInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/BuildMacroInfo.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageControl.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/DesignTimeAssemblyResolution.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VersionCompatibility/DotNetCoreProjectCompatibilityDetector.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsUIService`1.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Xproj/GlobalJsonRemover.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Xproj/MigrateXprojProjectFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/Interop/VsHierarchyExtensions.cs
Consistently use HResult vs VSConstants across the tree.
=> Use HResult over VSConstants

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VersionCompatibility/DotNetCoreProjectCompatibilityDetector.cs
turns out `is`/`as` patterns don't work on COM objects ¯\_(ツ)_/¯
=> correct fix for com exception

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/AdditionalFiles.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/AdditionalFiles.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/ApplicationDefinition.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/ApplicationDefinition.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Compile.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Compile.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Content.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Content.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/EmbeddedResource.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/EmbeddedResource.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/None.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/None.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Page.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Page.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Resource.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Resource.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/XamlAppDef.BrowseObject.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/XamlAppDef.xaml
Roslyn.sln has started to get a bunch of modifications with SubType being filled in, even though ProjectSystem.sln doesn't. Maybe something to do with Arcade? Either way this was always coming, now it just came quicker.
This means as the compiler pushes SubType information to CPS, it gets stored in the <project>.user file instead of the project file itself.
Fixes #182 
cc @jasonmalinowski
=> Persist SubType to the .user file instead of the project file

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectSubscriptionUpdateFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/NuGet/Snapshots/RestoreBuilderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/Snapshots/RestoreBuilder.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/ProjectRuleSnapshotExtensions.EmptyProjectRuleSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/ProjectRuleSnapshotExtensions.cs
Other teams have copied our rules to enable package reference support. These rules will become out-of-date with our built-in rules so handle missing rules. Also makes unit testing easier.
=>  Handle missing/out of date rules 

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs
Fixes: #4742
There was a race where we'd occasionally get called back on dataflow before the registration occured and we'd null reference.
=> Hook up operation progress before dataflow

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Fix for: https://github.com/dotnet/project-system/issues/4355 along with https://github.com/dotnet/sdk/pull/2994
https://github.com/dotnet/sdk/pull/2994 stops the SDK targets from removing the ``ReferenceManagerCOM`` ``ProjectCapability`` for all NET Core projects 
This PR only enables ``ReferenceManagerCOM`` if NETCoreApp >=3.0
=> Enable the COM tab in the Reference Manager for NETCoreApp >=3.0

src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerView.vb, src/Microsoft.VisualStudio.Editors/Common/SplitButton.vb, src/Microsoft.VisualStudio.Editors/DesignerFramework/DesignerDataGridView.vb, src/Microsoft.VisualStudio.Editors/PropPages/AdvBuildSettingsPropPage.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceListView.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceStringTable.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsDesignerView.vb
Splitting https://github.com/dotnet/project-system/pull/4766 into separate parts. This PR will update the LogicalToDeviceUnits calls with the corresponding DpiAwareness method, except those regarding images.
=> Update LogicalToDeviceUnits calls with DpiAwareness 

src/Microsoft.VisualStudio.AppDesigner/Microsoft.VisualStudio.AppDesigner.vbproj, src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
`<SubType>` is now stored in the user file, `<DependentUpon>` is now implicitly determined.
=> Remove unneeded <SubType> and <DependentUpon>

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/CompileItemHandler_CommandLineTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/CompileItemHandler_EvaluationTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/CompileItemHandler.cs
To match the naming of the other handlers that are named after their equivalent item.
=> Rename "SouceItemHandler" -> "CompileItemHandler"

src/Microsoft.VisualStudio.Editors/PropPages/PackagePropPage.Designer.vb, src/Microsoft.VisualStudio.Editors/PropPages/PackagePropPage.vb
Fix for https://github.com/dotnet/project-system/issues/4634
This makes the previously readonly text box for License File editable. The user can either browse for a file or enter a relative or absolute path to a file. The text box will convert any absolute path to a relative path. The text box will also correctly respond to changes in the project file.
More context for the initial feature: https://github.com/dotnet/project-system/pull/4223
=> Make the license file text box editable

src/Microsoft.VisualStudio.AppDesigner/Microsoft.VisualStudio.AppDesigner.vbproj, src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
RESX generation has a dependency on DependentUpon to determine the name of the resource embedded in the dll. 
Fixed: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/888081.
I'll do this in 16.2 another way and we need to think about this given that project system doesn't require it anymore. This just fixes the regression.
=> Revert DependentUpon/SubType changes

docs/well-known-project-properties.md, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.CSharp.DesignTime.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.VisualBasic.DesignTime.targets
~First pass at fixing #4478. My goal is to learn more about properties.~
Fixes #4478.
Sets value of two known properties used by designer code generation that determine the visibility and naming style of generated fields.
Can be merged once https://dev.azure.com/devdiv/DevDiv/_git/CPS/pullrequest/180589 completes.
=> Return values for VSHPROPID_DesignerFunctionVisibility and VSHPROPID_DesignerVariableNaming

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerView.vb
Fix for https://github.com/dotnet/project-system/issues/4745
Currently, this seems to be *always* failing when opening the property pages. 
At least one of the reasons `GetNestedHierarchy` is failing here is because the `ItemID` is `VSConstants.VSITEMID_ROOT` and it will always fail if that is the case.
I don't believe this is valuable to have, especially if we hit it every time with no issues with the `Hierarchy`
=> Remove the Debug.Fail for already having the hierarchy

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerPanel.vb, src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerView.vb
More useless asserts that are always hit on the property pages. Seemingly they are hit because of some race condition because when debugging the panels always have a non-zero size.
=> Remove property page control size asserts

src/Microsoft.VisualStudio.AppDesigner/PropPages/PropertyListener.vb
Fixes: https://github.com/dotnet/project-system/issues/4746 
As Dave said, our configuration properties do not implement `ConnectionPointContainer` like `DynamicTypeBrowseObject` does, for example. This will always be hit for configured property pages and should be removed.
=> Connection point debug assert removed

build/azure-pipelines-integration.yml
dnceng has said they are turning these VMs off so I am moving us to another queue that hopefully won't get shutdown
=> update queues used in the integration tests

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/IDependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs
When the tree provider is initialized later, it can register an event handler after the event is fired.  This can lead into an empty tree.  It happens when it is hosted outside of VS.
=> Fix a timing issue inside dependencies tree code:

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PackageRestore/Snapshots/RestoreBuilderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/Snapshots/RestoreBuilder.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
Fixes: https://github.com/dotnet/project-system/issues/4854.
Note: This has localization impact that I believe is okay; if we do not ship localized values - then the user will continue to get the old string.
=> Use NuGetTargetMoniker instead of TFM if its exists

src/Microsoft.VisualStudio.AppDesigner/DesignerFramework/BaseDialog.vb, src/Microsoft.VisualStudio.Editors/AddImportsDialogs/AddImportsDialogService.vb, src/Microsoft.VisualStudio.Editors/DesignerFramework/BaseDialog.vb, src/Microsoft.VisualStudio.Editors/PropPages/BuildEventCommandLineDialog.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/ConnectionStringUITypeEditor.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsDesignerView.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/TypeEditorHostControl.vb, src/Microsoft.VisualStudio.Editors/XmlToSchema/InputXmlForm.vb, src/Microsoft.VisualStudio.Editors/XmlToSchema/Wizard.vb
Fixes https://github.com/dotnet/project-system/issues/4769
This wraps all of the WinForms ShowDialog calls with `DpiAwareness.EnterDpiScope(DpiAwarenessContext.SystemAware)` . It was a little tedious and some of the Using's scopes were purposely trying to maintain the format of large functions/blocks of code. Also, the guidance was to wrap everything from the instantiation of the dialog to the `ShowDialog`, not just the call.
=> Wrap dialog creation in SystemAware DpiScope

src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceFile.vb, src/Microsoft.VisualStudio.Editors/StringComparers.vb
Fixes: #3575
ResX's files are persisted as "alphabetized" if they were determined to be "alphabetized" when opened. However, the persistence and determination use different comparisons, resulting in a file that was persisted as "alphabetized" to be opened as "non-alphabetized". Make them the same ("ordinal ignore case") .
The determination check was changed to match the persistence format to reduce the churn when editing the ResX in a new version of VS.
=> Always persist ResX files in ordinal order

.vsts-ci.yml
Reverts dotnet/project-system#4878
Our sign target bakes in the 15.0 path to MSBuild so we cannot use 2019 machines for official builds
```xml
<Import Project="BuildStep.props" />
<Target Name="Sign">
<Exec Command='"$(MSBuildProjectDirectory)\vswhere.exe" -latest -prerelease -property installationPath -requires Microsoft.Component.MSBuild'
Condition="'$(RealSign)' == 'true'"
ConsoleToMsBuild="true"
StandardErrorImportance="high">
<Output TaskParameter="ConsoleOutput" PropertyName="_VsInstallDir" />
</Exec>
<ItemGroup>
<SignToolArgs Include='-outputconfig "$(OutputConfigFile)"' Condition="'$(OutputConfigFile)' != ''" />      
<SignToolArgs Include='-nugetPackagesPath "$(NuGetPackageRoot)\"' />
<SignToolArgs Include='-intermediateOutputPath "$(ArtifactsObjDir)\"' />
<SignToolArgs …
```
=> Revert "use VS2019 on the official build"

src/BannedSymbols.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/DebugFrameworksDynamicMenuCommandTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/DebugFrameworksDynamicMenuCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/DebugFrameworksMenuTextUpdater.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectSystemOptions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/UIThreadHelper.cs
ThreadHelper is only initialized inside Visual Studio, move over to JoinableTaskContext which is its replacement for MEF components and is unit testable.
=> Use JoinableTaskContext instead of ThreadHelper

src/Microsoft.VisualStudio.Editors/Common/Utils.vb, src/Microsoft.VisualStudio.Editors/PropPages/AdvBuildSettingsPropPage.vb
Fire a telemetry every time the C# Advanced Build Settings dialog is opened. We want to get some idea of how many people actually use this dialog.
=> Add telemetry for advanced build settings dialog

docs/design-time-builds.md
Visual Studio 2017 version 15.9 is the only currently supported version of VS 2017 that the tools run on, so we can remove the old instructions for earlier point releases.
=> Remove old design-time build logging info

ProjectSystem.sln, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependenciesSnapshotFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependencyFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/ITargetFrameworkFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/ITargetedDependenciesSnapshotFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/MockIDependenciesTreeServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/TestDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependenciesSnapshotTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependencyTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/SdkAndPackagesDependenciesSnapshotFilterTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TestDependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/TreeView/DependenciesTreeViewProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesTreeViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/IDependenciesChanges.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/IDependenciesTreeServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/IDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/DependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/Filters/IAddDependencyContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/Filters/IRemoveDependencyContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/IDependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependenciesChangesBuilder.cs
Small bits while working on `FrameworkReference` support.
Of note:
- 1c04eb30c0db798afde6e8b9c34df86fbde90f3a fixes a bug where a change to the project's path (e.g. via rename) wouldn't be propagated to the snapshot.
- 93787d340d063af979f3872ed58944c9989904cb fixes an exception that could occur in rare circumstances.
- b6a1b30f4fd36f765c65540fb0bdc51d217f4a72 helps reduce string allocations.
=> Small dependency node fixes

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/IDependenciesTreeViewProvider.cs
`DependenciesProjectTreeProvider` imports multiple of these but only uses the highest priority one.
=> Fix ProjectSystemContract cardinality

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependenciesSnapshotFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependenciesSnapshotTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/TreeView/DependenciesTreeViewProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/Actions/GetChildrenGraphActionHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/Actions/SearchGraphActionHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphChangeTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesTreeViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/DependenciesViewModelFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/AggregateDependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/IDependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/IDependenciesSnapshotExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/IDependencyCrossTargetSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/ProjectRuleHandler.cs
Fixes #4937.
This PR is basically all in 89b57bbcec0831652773484a8827c40ff79ac500.
Previously any target framework not containing a dependency was removed from the snapshot. This was presumably to clean up when a target framework was removed from the project.
This change passes an explicit list of target frameworks through for the snapshot update, so that the tree can always show all target frameworks in multi-targeting projects.
Without this change, it's possible to have a misleading presentation in the UI (see #4937). With SDK 3.0.100, the MSBuild SDK no longer appears as a dependency, so it's much more likely we'd have target frameworks with no dependencies at all.
This also adds validation that the active target framework is present in related collections.
=> Don't hide/remove empty TFMs from the Dependencies node

src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests/ProjectSystem/ProjectTreeParserTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeParser/ProjectTreeParser.MutableProjectItemTree.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeParser/ProjectTreeParser.MutableProjectPropertiesContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeParser/ProjectTreeParser.MutableProjectTree.SubTypeRule.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeParser/ProjectTreeParser.MutableProjectTree.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeParser/ProjectTreeParser.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeWriter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeWriterOptions.cs
Add SubType/ItemType support to project tree parser, and a few other changes.
Need this to test the WindowsFormsEditorProvider.
=> Add SubType/ItemType support to project tree parser

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
Fixes https://github.com/dotnet/project-system/issues/4951
Original ask [here](https://github.com/NuGet/Home/issues/7351).
Spec at https://github.com/NuGet/Client.Engineering/blob/master/Specs/RuntimeJsonFromProject.md. 
The SDK will provide the RuntimeIdentifierGraphPath, that NuGet will treat that as the project provided runtime identifier graph.
This will effectively replace the platforms package.
cc @davkean @jjmew
=> Pass RuntimeIdentifierGraphPath during nomination

build/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/OrderPrecedenceImportCollectionExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IPhysicalProjectTreeFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectSystemOptionsFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectTreeServiceFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectSpecificEditorProviderFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/WindowsForms/WindowsFormsEditorProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectSystemOptions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WindowsForms/WindowsFormsEditorProvider.EditorInfo.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WindowsForms/WindowsFormsEditorProvider.SubTypeDescriptor.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WindowsForms/WindowsFormsEditorProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectSystemOptions.cs
Enable WinForms designer to open
Fixes: #3823, #4804
This ports WinFormEditorProvider from CPS, and changes behavior from it and legacy:
- Users can now control (using Open With... -> Set As Default) whether the designer opens by default for Forms, User Controls and Components separately from each other. Legacy/CPS have a single setting that controls this. This is helpful because the Component designer is less useful than the Form designer, so you might want the latter to open but not the former.
- This new setting roams and is shared across all languages. Legacy/CPS is per language per VS install.
- Component Designer is turned off by default. Users can open it via the View Designer command, or use above Open With to set it to open by default.
- The name of the designer editor has …
=> Enable WinForms designer to open

src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPageUserControlBase.vb, src/Microsoft.VisualStudio.AppDesigner/PublicAPI.Shipped.txt, src/Microsoft.VisualStudio.Editors/My Project/AssemblyInfo.vb, src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/CompilePropPage2.vb, src/Microsoft.VisualStudio.Editors/PropPages/DebugPropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/ReferencePropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/UnusedReferencePropPage.vb, src/Microsoft.VisualStudio.Editors/PublicAPI.Shipped.txt
Fix naming violations in parameters, which theoretically can break usage, but is doubtful.
=> Fix naming violations

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsThreadedWaitDialogFactoryFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/CSharp/RenamerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/RenamerTestsBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/VisualBasic/RenamerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Waiting/VisualStudioWaitContextTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Waiting/VisualStudioWaitIndicatorInstanceTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Waiting/VisualStudioWaitIndicatorTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IRoslynServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/Renamer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/RoslynServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Waiting/VisualStudioWaitContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Waiting/VisualStudioWaitIndicator.Instance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Waiting/VisualStudioWaitIndicator.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Waiting/IWaitContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Waiting/IWaitIndicator.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Waiting/WaitIndicatorResult.cs
allows the user to cancel a long running rename operation
=> Add waiter service

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependenciesSnapshotFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/ITargetedDependenciesSnapshotFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependenciesSnapshotTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependencyExtensionsTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesTreeViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/TargetDependencyViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/Filters/UnsupportedProjectsSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/IDependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/ITargetedDependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs
Allowing non-visible items to turn this flag 'true' can produce a "Dependencies" node with a warning icon, but no children with a corresponding warning to drill into.
Relates to #4362.
=> Snapshot tracks only visible unresolved items

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
The stub immediately below this declares it depends upon `ResolveFrameworkReferences` yet that target may not exist.
=> Add a stub for target ResolveFrameworkReferences

src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceStringTable.vb
Reverts this commit: https://github.com/dotnet/project-system/pull/3786/commits/c30f4626d9a1e176492d1b279b3d45aa42fd5ae6
Fixes [AB#936285](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/936285)
When rows are set to autosize the DataGridView ignores any manual change of Height, which means rows can expand to larger than the visible area on the screen. This makes the editing a very poor experience when using very long resource strings.
This also fixes a perf regression mentioned in the bug, and in the code here:
https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceStringTable.vb#L606-L608
=> Revert change to make rows autosize

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependenciesSnapshotTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Utilities/SetDiff.cs
New validation on `DependenciesSnapshot.ActiveTargetFramework` could be hit before this change when changing a project's target framework(s).
This change replaces the previous logic to:
- prevent `ActiveTargetFramework` from not being present as one of the targets in the snapshot
- eagerly populate the snapshot with any additional frameworks as soon as they're discovered rather than letting it happen lazily
=> Fix snapshot's active target framework bug

.gitattributes
Several unit tests include string literals for expected values. Without this setting, a repo checked out with alternative line ending settings will have failing tests. This can occur, for example, if you clone the repo using WSL.
=> Force .cs and .vb to use crlf

build/azure-pipelines.yml, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ConfiguredProjectFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ConfiguredProjectServicesFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectSubscriptionServiceFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectServicesFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectValueDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsDataSourceTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputs.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/IDesignTimeInputsDataSource.cs
This is the first little piece of the latest rewrite of TempPE, this time using data flow. I wouldn't be surprised if this changes (in particular the shape of `DesignTimeInputs`) but I'm putting it up early because it's my first ever use of data flow.
Also, excitingly, it's the first set of tests I've been able to write that isn't tied horribly to the internal implementation details of the class under test! Well except all of those mocks that are used by it and its base classes, and the specific parts of the project changes that I specified in JSON, but it's close to good at least! 😛
Also note this is going into a feature branch.
=> DesignTimeInputs data source and tests

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/XamlRuleTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/AnalyzerReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/CollectedFrameworkReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/CollectedPackageDownload.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/CompilerCommandLineArgs.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PackageReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedAnalyzerReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedAssemblyReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedCOMReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedCompilationReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedFrameworkReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedPackageReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedProjectReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedSdkReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/SdkReference.xaml
Validates:
1. When `SourceType` is `TargetResults` that `MSBuildTarget` is present
1. That `MSBuildTarget` is only present when `SourceType` is `TargetResults`
1. When `SourceType` is `Item` that `ItemType` is present
1. That `ItemType` is only present when `SourceType` is `Item`
This resulted in removing a bunch of redundant `ItemType` attributes from rule data sources.
=> Validate top level rule DataSource properties

.gitignore
In 16.2, deployments & coverage files are no longer deployed to TestResults - ignore their new locations.
=> Ignore test deployment & coverage files

build/Default.ruleset, build/Packages.targets, src/HostAgnostic.props
These analyzers are deprecated as per https://github.com/dotnet/roslyn-analyzers/issues/2664#issuecomment-509884741.
=> Remove deprecated analyzers

build/Packages.targets
Moq 4.11 contains some breaking changes and wanted to test to make sure we're not affected by it. We're not, so just upgrade so others don't need to do same testing.
=> Upgrade Moq to 4.12.0

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/XamlRuleTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/AnalyzerReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/CollectedFrameworkReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/CollectedPackageDownload.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/CompilerCommandLineArgs.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PackageReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedAnalyzerReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedAssemblyReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedCOMReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedCompilationReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedFrameworkReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedPackageReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedProjectReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedSdkReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/SdkReference.xaml
Reverts part of #5000.
Fixes #5007 and broken property pages.
=> ItemType is allowed when SourceType != "Item"

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PotentialEditorConfigDataSource.cs
Fixes a NRE due to a dataflow race condition in `PotentialEditorConfigDataSource`. 
It was possible for `ProcessProjectChanged` to be called before `_broadcastBlock` was assigned, leading to a NRE when it was dereferenced.
This exception has been fixed indirectly in `master` via 2894df437536832d27c2c9e125180fcebc2f7a8b so does not need to be integrated forward. This PR prevents it happening in 16.3 preview 1.
@tmeschter @jmarolf @jjmew
=> Fix NRE due to dataflow race

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/LanguageService.xaml
If a developer attempts to use a language feature not supported by the
version of C# currently in use by a project, the Language Service can
offer a fix to upgrade the user to a newer version. In order to do this
correctly in all scenarios, the Language Service needs to know the
maximum supported language version available to the project.
Here we obtain the value from MSBuild and pass it unchanged to the
Language Service. Typically the value will be a version like "7.3" or
"8.0", but the LS will also need to handle (in some manner) the empty
string, values that _may_ make sense to the compiler but are
questionable for LS purposes (e.g., "current", "preview"), and outright
garbage values.
=> Pass MaxSupportedLangVersion to the Language Service

.editorconfig, ProjectSystem.sln, build/Default.ruleset, build/Packages.targets, build/Test.ruleset, build/azure-pipelines.yml, src/Directory.Build.props, src/HostAgnostic.props
Reverts dotnet/project-system#4929
We need 2019 for this feature to work, and our signed build can't use 2019 for reasons I don't really understand. So the .editorconfig support broke the signed build. In order to unblock everyone else I'm backing out the change.
=> Revert "Turn on discovery of .editorconfig files"

.vsconfig
16.3 includes 3.0 by default which we automatically work against, but there's no 'Or' concept in .vsconfig so we cannot represent that.
=> Remove the need for .NET Core 2.1 to be installed

src/Microsoft.VisualStudio.Editors/MyApplication/MyApplicationProperties.vb, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
For the VB MyApplication model we need to support the `MyType` property from our browse object. This is currently retrieved by the property pages via the `VBProjectProperties3` interface, which CPS doesn't implement, so this PR adds a fallback to use `ICustomTypeDescriptor`.
Legacy only uses `VBProjectProperties3` for the `MyType` and `MyApplication` properties, and I couldn't find any other consumers, so actually doing the work to allow CPS to implement various project properties interfaces is overkill at the moment (The `MyApplication` property support was already added for #4708 and just needs to be turned on for CPS projects when ready).
Fixes #5046
=> Add MyType property

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ConfiguredProjectServicesFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsAsyncFileChangeExMock.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcherTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/TestHelpers/TestIVsAsyncFileChangeEx.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcher.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/IDesignTimeInputsFileWatcher.cs
A dataflow block that listens for design time inputs and shared inputs, and watches those files, and then sends output whenever a file is changed.
=> Design time inputs file watcher

build/Packages.targets, src/HostAgnostic.props
Fixes: https://github.com/dotnet/project-system/issues/4933
These are deprecated.
Microsoft.CodeQuality.Analyzers.Exp were already removed.
=> Remove Text.Analyzers

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
LaunchSettingsProvider has a mismatch of properties/fields, demote properties -> fields to when they aren't used outside of the class. Some of this involved removing a test that checked we null'd out fields, which doesn't belong in a unit test.
=> Domote properties to fields

src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.Designer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf
This is more in keeping with its siblings, such as "Assemblies", "Projects", "Frameworks" and so on.
This change will likely effect localisation, as previously "NuGet" was unmodified in translation files.
(It's possible "SDK" should become "SDKs" as well.)
Relates to #4362.
=> Rename the "NuGet" dependencies node to "Packages"

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/WpfBasedPropertyPage.cs
I observed this when closing the property page.
It may have followed a previous bug, as IIRC I double-clicked the project node in Solution Explorer, expecting an editor to appear, and the property page appeared instead.
The assertion failure dialog read:
```text
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Dispose
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.VisualStudio.ProjectSystem.VS.PropertyPages.WpfBasedPropertyPage.Dispose(Boolean disposing)
at Microsoft.VisualStudio.ProjectSystem.VS.PropertyPages.PropertyPage.Deactivate()
at Microsoft.VisualStudio.Editors.ApplicationDesigner.PropertyPageInfo.Dispose(Boolean disposing)
--- End of stack trace from …
```
=> Prevent NRE in WpfBasedPropertyPage.Dispose

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.State.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
Introduces the immutable `BuildUpToDateCheck.State` class to hold state relating to the fast up-to-date check.
This is preparatory work for #4736, which I have a local fix for that builds upon this work. Unlike this PR, that fix will change the unit tests for the up to date check.
=> Up-to-date check uses immutable snapshot

src/Microsoft.VisualStudio.Editors/Menus.vsct, src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.pkgdef, src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj, src/Microsoft.VisualStudio.Editors/VSPackage.resx, src/Microsoft.VisualStudio.Editors/xlf/Menus.vsct.cs.xlf, src/Microsoft.VisualStudio.Editors/xlf/Menus.vsct.de.xlf, src/Microsoft.VisualStudio.Editors/xlf/Menus.vsct.es.xlf, src/Microsoft.VisualStudio.Editors/xlf/Menus.vsct.fr.xlf, src/Microsoft.VisualStudio.Editors/xlf/Menus.vsct.it.xlf, src/Microsoft.VisualStudio.Editors/xlf/Menus.vsct.ja.xlf, src/Microsoft.VisualStudio.Editors/xlf/Menus.vsct.ko.xlf, src/Microsoft.VisualStudio.Editors/xlf/Menus.vsct.pl.xlf, src/Microsoft.VisualStudio.Editors/xlf/Menus.vsct.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/xlf/Menus.vsct.ru.xlf, src/Microsoft.VisualStudio.Editors/xlf/Menus.vsct.tr.xlf, src/Microsoft.VisualStudio.Editors/xlf/Menus.vsct.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/xlf/Menus.vsct.zh-Hant.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.cs.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.de.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.es.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.fr.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.it.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.ja.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.ko.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.pl.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.ru.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.tr.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.zh-Hant.xlf
Fixes this repo's side of https://github.com/dotnet/project-system/issues/4561.
This ports all the strings and vstc from the VS repo and prevents that dll from loading. I've confirmed that EditorsUI no longer loads with these changes (it did previously) and the menus & strings are picked up.
Note, I did not port the toolbar bitmap as it is no being used and has since been replaced. There a few strings that I've yet to find a reference to and will delete them in a followup when I've 100% confirmed they are no longer being used.
=> Remove Microsoft.VisualStudio.EditorsUI.dll

src/Microsoft.VisualStudio.Editors/VSPackage.resx, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.cs.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.de.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.es.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.fr.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.it.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.ja.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.ko.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.pl.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.ru.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.tr.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/xlf/VSPackage.zh-Hant.xlf
This resource was a used by a now defunt options page that was used for simplified "options".
The registration is being removed here: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/192167.
Also removed other resources that I've now confirmed are being used nowhere.
=> Remove resources

build/Packages.targets
VSSDK.DTE/VSSDK.TemplateWizardInterface are non-official Microsoft packages that NuGet.VisualStudio has taken a dependency on. These packages contain the same dlls as other packages. I've asked them to remove the dependency but in the meantime avoid using assets from those packages.
Fixes: https://github.com/dotnet/project-system/issues/4802.
=> Remove double-writes in the build

src/BannedSymbols.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/TempPEBuildManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DataflowOption.cs
We have wrappers that simplify the boilerplate and make dataflow links easier to read.
=> Ban StandardRuleDataflowLinkOptions/DataflowLinkOptions

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsAsyncFileChangeExMock.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcherTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcher.cs
The compiler (which you haven't seen yet) makes a lot more sense when the file watcher just watches.
=> Don't fire a change when a new file is being watched.

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.State.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
Fixes #4736 without breaking #3245.
Rather than setting a flag `itemsChangedSinceLastCheck` dirty when items change and clearing it in `IsUpToDateAsync`, we now keep track of the last time an input item changed and compare that with output timestamps to determine if we need to rebuild.
Most of the work here went into updating the tests.
=> Fix up-to-date check false negatives

Directory.Build.targets, build/Scripts/UnitTests.targets
This brings back inline test failures that we used to have before we adopted RoslynTools.RepoToolset:
=> Enable inline test failures during build

build.cmd, build/CIBuild.cmd, build/azure-pipelines.yml
This removes the `CIBuild.cmd` script. This may not be safe to do if other branches use `master`'s version of these build scripts. If that turns out to be the case, we'll revert this commit.
The easiest way for us to test this is to get this change into `master` then submit a PR to a branch such as `dev16.0.x` and see if that PR builds.
=> Azure pipelines calls build.cmd directly

build/Packages.targets, build/Versions.props
These properties/references are not used, remove them. The using of these are being tracked by: https://github.com/dotnet/project-system/issues/5092.
=> Remove unused props/references

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/DependencyModelTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/IDependencyModelEqualityComparerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/IDependencyModelEqualityComparer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/DependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependenciesChangesBuilder.cs
`IDependencyModel` is an extensibility point and we should not be requiring implementors to add correct `Equals`/`GetHashCode` methods. There's no good way to express this on the interface, but we don't want the implementation to vary based on provider anyway.
=> Use dedicated comparer for IDependencyModel

build/Packages.targets, build/Toolset.proj
These package references are never used, and/or given a version which breaks restore.
This caused one of the failures in https://github.com/dotnet/project-system/pull/5111.
=> Fix restore failure

Test.cmd
I'm removing this under the assumption no one is using it.
@dotnet/project-system Please tell me if you are using this script to run unit tests, and if so, I'll update it to call through the updated build.cmd.
=> Remove test.cmd

build/Packages.targets, build/Scripts/IntegrationTests.targets, src/VisualStudioIntegration.props
This includes https://github.com/dotnet/project-system/pull/5127, so just review https://github.com/dotnet/project-system/commit/9bf9c5d250049df68679db47505f97ce098a897b.
Turn on vstest.console.exe warnings so that they appear in the build. We were ignoring these warnings, turn them back on but avoid the original reason they were turned off.
=> Turn on warnings

src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/TestBase.cs
We don't want to force first launch and this was causing Apex to attempt to copy over a bunch of dlls into the VS directory failing the test run.
=> Turn off first launch

.vsts-ci.yml, build/azure-pipelines.yml, build/build.ps1
It was confusing that ci implies other switches, explicitly set /diagnostic on unit tests & signed builds.
=> /ci no longer implies /diagnostic

.vsts-ci.yml, build.cmd, build/azure-pipelines.yml, build/build.ps1, src/Directory.Build.props
f341eab removed the `-optimize` argument for signed builds, resulting in two changes:
1. Output binaries were not being optimised
2. IBC data was not being applied (when available)
The "optimize" parameter of `Build.ps1` was serving double duty.
This PR:
- adds a new `ibc` parameter
- sets `ibc` on signed builds only
- removes overriding the MSBuild `Optimize` property so that optimisation occurs for Release builds even if we don't want IBC
=> Fix optimization for signed builds

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectCommonServicesFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IUnconfiguredProjectServicesFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IActiveConfiguredProjectSubscriptionServiceFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsDataSourceTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcherTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcher.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/IDesignTimeInputsDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/IDesignTimeInputsFileWatcher.cs
This moves the TempPE stuff to the unconfigured project scope so there is only one instance per project.
Note: This is untested, as that is blocked on getting the compiler manager merged and I don't want to cloud that PR, however this is to a feature branch so it doesn't matter :)
=> Move to UnconfiguredProject scope

src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/ProjectSystemHostConfiguration.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/TestBase.cs
This reduces the MEF composition errors in the build log, there's a few remaining that require changes to Apex itself.
=> Reduce MEF composition errors in build log

src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/ProjectSystemHostConfiguration.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/ProjectSystemOperationsConfiguration.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/TestBase.cs
Control the assemblies that end up in the MEF composition to remove all MEF discovery errors in test logs.
This required a single call to a non-public API on TestContextLogger - attempting to replace is impossible without reimplementing the entire MSTest infrastructure.
This replaced:
```
Populating Assembly Catalog: ApexAssemblyCatalog (attributed with [ProvidesOperationsExtensionAttribute])
Failed to load assembly Microsoft.VisualStudio.TestTools.UnitTesting.AssertInconclusiveException while looking for exports. Exception: System.TypeLoadException: Cannot find type System.Exception in module System.Runtime.dll.
at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String …
```
=> Remove all MEF discovery errors

build/Scripts/IntegrationTests.targets, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/ProjectSystemOperationsConfiguration.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/WarningIgnorerLogger.cs
Certain errors occur because the process is not elevated, we cannot turn off these lifetime actions, so to avoid logging out errors that just confuse investigations - ignore them.
This also lets us start to pick up standard error as only "real" errors are now logged through it.
=> Avoid logging errors we can do nothing about

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ConfiguredProjectServicesFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/GlobalSuppressions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IActiveWorkspaceProjectContextHostFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsAsyncFileChangeExMock.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcherTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/TempPECompilerManagerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcher.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/TempPECompilerManager.cs
Contains #5081 so skip the first two commits (or don't they're really small).
This PR contains a class that manages the compilation of TempPE DLLs. It has two dataflow subscriptions:
* One for the design time inputs, and project information, which give it the state that it will be working with
* One for file changes, so it knows when to recompile
The basic idea is that as a design time input is changed or added, the manager collects them in a queue, and then after a short delay it starts running through the whole queue on a background thread. As needed, when more files change, that work is stopped and a new processing task is scheduled. Additionally there is a facility for "I need this now!" which will cause a compile (presumably on the UI thread) if required, without interrupting the …
=> Create a TempPE Compiler Manager

src/VisualStudioIntegration.props
We already setup the correct paths in IntegrationTests.targets to load the adapter directly from the package.
=> Make media recording actually work

src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/ProjectSystemHostConfiguration.cs
OmniLogging was removed from the MEF container , turning off the OmniLogging and screenshots. Turn it back on.
=> Turn on screenshots/omnilogging

build/Scripts/IntegrationTests.targets
Handle when TRX is missing because vstest.console.exe failed to produce one, due to it missing on disk - or for other reasons.
=> Handle when TRX is missing

build/build.ps1
We were outputting these always, only output them when someone throws the /diagnostic switch.
=> Only output VS/MSBuild version under /diagnostic

build/azure-pipelines-integration.yml
Once we stabilise the tests, we'll turn them back on.
=> Disable integration tests build triggers

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/TempPECompilerManagerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/TempPECompilerManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryEventName.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryPropertyName.cs
Telemetry to track things like queue size, how often cancellations are, how often things are actually compiled, etc.
May be refined in future.
=> Add telemetry to track compilation queue info

src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/LifetimeActions/MakeOmniLogTestSpecificLifetimeAction.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/TestBase.cs
Actually start using the features that Apex provides rather than using inheritance/overrides.
=> Move omni reset into a lifetime action

src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/Environment/AssemblyLifetime.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/Environment/TestEnvironment.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/LifetimeActions/ShutdownVisualStudioAfterLastTestLifetimeAction.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/ProjectSystemHostConfiguration.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/TestBase.cs
This includes https://github.com/dotnet/project-system/pull/5169, so just review https://github.com/dotnet/project-system/commit/c162c209f351e1a7602c4cb505aeb4d427ccf168.
Previously we were shutting down VS after each test - this increases test time significantly. Apex already shuts down VS if a test fails (to avoid dirtying future tests), but it does not shutdown VS after the last test. Introduce a lifetime action that does this.
=> Shutdown VS only after last test has finished

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcherTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcher.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/TempPECompilerManager.cs
I plan to revisit paths across the board later, once all of the bits are in and working. For now this gets bits working.
=> File watcher needs to watch full paths, not relative ones.

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcherTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/TempPECompilerManagerTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcher.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/TempPECompilerManager.cs
Fixes an issue where a compilation being cancelled would leave a 0 byte file on disk, and adds a couple of other test cases that didn't have coverage.
Also include #5158 so only review https://github.com/dotnet/project-system/commit/4b4b9d7b4634f725c9d8a7ca2ad4487282ba581e
=> More TempPECompilerManager Tests

build/Packages.targets
This should fix a hang we're seeing on the CI box.
=> Update VSSDK Build Tools version

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreUnconfiguredInputDataSource.cs
Telemetry shows that we're hitting configurations without "PackageReference" defined, filter them out from NuGet restore to prevent us throwing from GetExportedValue.
=> Avoid faulting block when PackageReference is missing

build.cmd
This will be useful now while investigating test failures where we don't want anything to build. It might be removed later, but is pretty harmless to leave in.
=> Add /no-build option

build/RepoToolset/RepoLayout.props, build/Scripts/GenerateDependentAssemblyVersionFile.targets, build/build.ps1
This moves GenerateDependentAssemblyVersionFile to msbuild.
While this is significantly more code than what we had before, the benefits will be clear when build.ps1 is replaced with an msbuild proj and you can use MSBuild Structured Build Logger to investigate the build.
=> Move GenerateDependentAssemblyVersionFile to msbuild

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedFrameworkReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedFrameworkReference.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedFrameworkReference.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedFrameworkReference.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedFrameworkReference.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedFrameworkReference.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedFrameworkReference.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedFrameworkReference.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedFrameworkReference.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedFrameworkReference.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedFrameworkReference.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedFrameworkReference.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedFrameworkReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedFrameworkReference.xaml.zh-Hant.xlf
Relates to #5070 and #4762.
With SDK 3.0.100-preview8, we now receive `ResolvedFrameworkReference` items with the required properties. This PR removes the workaround that was required until now to framework references correctly.
- The `Path` property is populated.
- The item's description is now "Framework Properties" rather than "Framework Reference Properties". This matches "Package Properties" for `<PackageReference />`.
- The version has been added. Although the version is available in the path itself, it's usually off screen.
=> Framework reference browse object

build/Codecov.proj, build/Scripts/GenerateDependentAssemblyVersionFile.targets, build/build.ps1
Preparing to replace build.ps1 with msbuild file, and CodeCov is harder than it needs to be, simplify it.
Note: This still doesn't get it to run - the GitHub properties are all wrong.
=> Simplify CodeCov usage

build/Scripts/GenerateDependentAssemblyVersionFile.targets, src/Common/ProvideCodeBaseBindingRedirection.cs, src/setup/ProjectSystemSetup/AssemblyRedirects.cs, src/setup/ProjectSystemSetup/ProjectSystemSetup.csproj, src/setup/VisualStudioEditorsSetup/AssemblyRedirects.cs, src/setup/VisualStudioEditorsSetup/VisualStudioEditorsSetup.csproj
- Rename binding redirect attribute and add some comments
- Add AppDesigner to the list of assembly versions that get updated on insertion, it was missing, see: https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2FProductData%2FAssemblyVersions.tt&version=GBmaster&line=50&lineStyle=plain&lineEnd=51&lineStartColumn=1&lineEndColumn=1.
=> Binding redirection

build/Packages.targets, build/Toolset.proj, build/build.ps1
The toolset already has access to the required properties it needs (from Directory.Build.props/targets), and does not need the properties passed to it.
Also skipped passing ExcludeRestorePackageImports, we can avoid picking up imports for PackageReferences by excluding them.
b95ec25
=> Simplify toolset restore

build/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VsBuildManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/NameValuePair.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/ObservableList.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/AggregateDependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs
The older package was explicitly turning it off. Since that was a pre-release package that doesn't represent what we are shipping, just upgrade. The version chosen here matches the current internal dogfood build.
=> Update Microsoft.Net.Compilers to one that enables .editorconfig discovery

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/CollectedFrameworkReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/FrameworkReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/ResolvedFrameworkReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/FrameworkReference.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/FrameworkReference.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/FrameworkReference.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/FrameworkReference.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/FrameworkReference.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/FrameworkReference.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/FrameworkReference.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/FrameworkReference.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/FrameworkReference.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/FrameworkReference.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/FrameworkReference.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/FrameworkReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/FrameworkReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedFrameworkReference.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedFrameworkReference.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedFrameworkReference.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedFrameworkReference.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedFrameworkReference.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedFrameworkReference.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedFrameworkReference.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedFrameworkReference.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedFrameworkReference.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedFrameworkReference.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedFrameworkReference.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedFrameworkReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedFrameworkReference.xaml.zh-Hant.xlf
Following discussion in #5070, removes the `PrivateAssets` property for framework references.
Fixes #4762.
Fixes #5070.
=> Remove FrameworkReference PrivateAssets properties

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
This partially reverts a change made in 97b3d5755562dedd304404d9946990077fd227c9 that resolved #3245. More recently PR #5089 was merged that addresses the same issue and others, making this addition to the inputs obsolete (and potentially harmful by triggering unnecessary builds). As @rainersigwald explained, the cache file is an implementation detail of MSBuild that we should not depend upon.
I've tested this in various scenarios, including those in #3245 and #4736.
=> Exclude MSBuild items cache file from up to date check inputs

docs/repo/up-to-date-check-implementation.md, docs/up-to-date-check.md
Previous documentation on the up-to-date check was technical and focused on project contributors (hence being in the `docs/repo` folder).
This PR adds a more general document explaining what the up-to-date check is, how to configure it and how to debug it.
=> Add user-facing up-to-date check documentation

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
The underlying Roslyn bug has been fixed.
=> Remove redundant #pragma warning disables

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs
Fix for: https://github.com/dotnet/project-system/issues/5180
This ensures that when tabbing onto the WPF Debug property page, the first item is consistently selected. The issue was that not all of the properties had been initialized - HasProfiles was returning false and the Profile ComboBox was disabled when the page placed the tab selection on the first enabled control. This fix just assumes that if the property has not been initialized, enable the ComboBox. If, after initialization, the property is still false, the tab selection will go to the correct control and the ComboBox will be disabled. 
Note: I am not sure why the page is not showing the selection around the ComboBox until you tab off and back onto it, but I confirmed via the Narrator that it is selected and will respond to key …
=> Fix Starting Tab Selection on Debug Property Page

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/Snapshots/ImmutablePropertyCollection.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/LinqExtensions.cs
It's perfectly valid to have a multi-TFM project where two of the <TargetFrameworks> values map to the same underlying TFM. An example of this is the Microsoft.Toolkit.Uwp.Notifications project in the https://github.com/windows-toolkit/WindowsCommunityToolkit.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/957711/
=> Avoid assuming target framework is unique across configurations

src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/Construction/GlobalJson.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/Construction/Project.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/Construction/Solution.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/DependencyNodeIntegrationTests.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/IntegrationTestBase.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/LifetimeActions/ShutdownVisualStudioAfterLastTestLifetimeAction.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/Microsoft.VisualStudio.ProjectSystem.IntegrationTests.csproj, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/OpenProjectTests.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/ProjectLayoutTestBase.cs, src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/Utilities/AssertExtensions.cs
First cut of integration tests for the dependencies node. Relates to #1607.
This revitalises PR #4658 which was automatically closed when we deleted the `feature/integration-tests` branch.
These tests build up a solution/project(s)/global.json on disk, load the solution, then inspect the dependencies nodes.
See `DependencyNodeIntegrationTests` for how such tests are authored.
=> Dependency node integration tests

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/Snapshots/ImmutablePropertyCollection.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/Snapshots/ProjectProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/Snapshots/ReferenceItems.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/Snapshots/ReferenceProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/Snapshots/TargetFrameworks.cs
- Previous implementation would enumerate input items twice. Most callers of this constructor would lazily construct objects, meaning twice the allocation. This implementation enumerates once.
- Previous implementation would allocate a `HashSet<string>` to track unique keys, then produce an immutable dictionary as the backing store for this object. This implementation uses the backing store collection directly while it is being built, avoiding the need for the temporary set.
- Previous implementation would store data using immutable list and dictionary, both of which use many GC tracked node objects to store items. This implementation maintains immutability through the API, but uses mutable collections internally as they have lower memory consumption, and less fragmentation leading to …
=> Reduce allocations in ImmutablePropertyCollection<T>

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/CrossTarget/IDependenciesRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/CrossTarget/RuleSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/AggregateDependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/IDependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/DependenciesRuleHandlerBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.cs
Steps towards larger refactoring of how the dependency node gets data from MSBuild.
Easiest to review commit by commit. Of note are:
- 7a04e2d5cf7175477fc3b8e32dca731bdf9d73dd which replaces the last usages of a .NET event with the Dataflow block @lifengl added a while back.
- 5394ef890ee6d172c71722bab874d03e41fda792 which removes redundant operations as joint rule name sets contain evaluated rule names
- 5b325d2c0d98a69550d2cb2cf6b6ec2a95534d46 which pulls duplicated code into a method and calls it twice
- 48b0d370e9ba314fb97f78650146f75e3ccd904c which avoids slicing the set of rules before calling handlers, as handlers only query items they're interested in anyway, which saves some allocation
=> Improve dependency node MSBuild rule data handling

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependencyTreeTelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/IDependencyTreeTelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs
A series of small tidy ups in the dependency node telemetry code.
=> Reduce locking and allocation in dependency node telemetry

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreUnconfiguredInputDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/DisposableBag.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs
- The cancellation support was unused so I removed it. It makes the type much smaller and simpler.
- The 'observable disposable' concept was unused, so has been removed.
- `AddDisposable` was renamed to `Add`, and object initializer support enabled. `RemoveDisposable` was also shortened. This looks better to me in usages.
- Removed `lock (this)` (which is a bad idea anyway as `this` is public which allows deadlocks if others locked on the instance too) from the implementation. Replaced with lock-free operations to guarantee safety and correctness.
Further questions:
- Should this be a stack, rather than a set, so that disposal is LIFO? I'm not sure it matters with our current usages, but in general it might be more correct. The current implementation gives no guarantee about disposal …
=> Reduce allocation in DisposableBag and remove locking

build/proj/CoreBuild.proj, build/proj/Sign.proj
This allows signing on VS 2019, instead of limiting to VS 2017.
Originally we were going to consume this by upgrading to the latest version of RoslynTools.RepoToolset. I spent 2 days on that port and gave up; it's a significant work item due to a large number of breaking changes. I timeboxed and ran out of time.
Instead, I've gone down the approach of copying the Sign.proj from the toolset, and slightly changing it. Both are in two separate commits.
=>  Allow signing on VS 2019

build/ci/official.yml
This will enable us to use some of the new VS 2019 features, such as .editorconfig support.
=> Move official build to VS 2019

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/DependencyRuleTests.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/PackageReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.zh-Hant.xlf
- 0b0a0bfbbc9828c808d5eacccd123dc3431ac9b5 Unresolved dependency rules should not have `OriginalItemSpec` properties. Added unit test to this effect and removed from `PackageReference.xaml`.
- a73dacdd8ddace4ec59c4d05d260c3ad670165e4 Removed additional `PackageReference` properties. To the best of my knowledge, and according to my testing, these properties will not be present on evaluated `PackageReference` items.
Relates to #4105 and #5078.
=> Remove some PackageReference XAML properties

build/script/SetVSEnvironment.cmd
We are moving across to consuming VS 2019-only features such as compiler .editorconfig suppport.
=> Force VS 2019 for building repository

build/ci/official.yml
This is no longer used, see: https://github.com/dotnet/project-system/pull/5102#issuecomment-513453333.
=> Stop publishing integration tests results

src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.pkgdef
Tested all editors with a delayed design time build, and both Settings and Resource editors rely on build results, and the App Designer includes the Resource Editor.
Fixes [AB#952010](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/952010)
=> Defer editor creation for Partial Load Mode

build/ci/unit-tests-template.yml, build/ci/unit-tests.yml
This splits common logic from unit-test into a parameter-driven template file.
This unifies the build logic between Spanish and Windows runs, by changing the following:
1) NuGet Cache is cleared in Windows runs, it was only running on Spanish previously which was an oversight. This caches when our sources don't contain a package that we've referred to.
2) Spanish runs also test sign, similar to Windows.
=> Split unit-tests.yml into template

ProjectSystem.sln, build/build.projitems, build/build.shproj
This avoids having to keep the list of solution items up to date.
Having these items in the solution means their contents will be searched by find-in-files.
=> Use shared project for build files

build/ci/integration-tests.yml, build/ci/official.yml, build/ci/unit-tests-template.yml
This includes https://github.com/dotnet/project-system/pull/5312 so just review https://github.com/dotnet/project-system/commit/25dac9a10c473f35767a16c1ae11c6781bc07c6e.
his moves official build from BatchScript -> CmdLine ("script"). The docs are not clear on the differences and cannot find the source code for BatchScript, but this consistently brings it inline with unit-tests and integration-tests.
=> Consistently call build.cmd 

src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IActiveConfiguredProjectProviderFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/UnconfiguredProjectFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IServiceProviderFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsTaskFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Input/AbstractProjectCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContext.cs
The only behaviour change is in 6d45d37e2348daf1b31517764795882d1965dd2d, where a null value will now throw earlier.
=> Annotations

build/proj/Build.proj, build/proj/CoreBuild.proj
This removes the ability inside CoreBuild.proj to turn off pack/restore. Build.proj (which calls CoreBuild) always passed true for these. 
- Restore always occurs, there's no way to turn it off. If folks decide they want this ability, we can always add it back.
- Pack always occurs when you `/build` or `/rebuild`.
This lets https://github.com/dotnet/project-system/pull/4768 do a restore only build via:
```
build /no-build /no-test /no-deploy
```
=> Remove "pack" and "restore" concepts from CoreBuild.proj

Directory.Build.props
The build already forces VS 2019, make sure the same applies if you open the solution in VS 2017 or below. This causes projects to be not be loaded and results in:
=> Force VS 2019 for solution

build/ci/official.yml
Previously this was located in another repository and kept being out of sync with our build, moving it to the official build.
=> Take ownership of http://index indexing

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IPhysicalProjectTreeStorage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PhysicalProjectTreeStorage.ConfiguredImports.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PhysicalProjectTreeStorage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractFindByNameSpecialFileProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IFileSystemFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectItemProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectTreeServiceFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectTreeServiceStateFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PhysicalProjectTreeStorageTests.cs
This is breakout from a larger PR where I'm adding licenses special file provider support, this adds a new method called `IPhysicalProjectTreeStorage.AddFileAsync` which creates a zero'd file on disk and publishes it to Solution Explorer before it has returned.
=> Add IPhysicalProjectTreeStorage.AddFileAsync

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesProjectTreeProvider.cs
Now that this flows from Dataflow rather than events, we can actually await the tree update operations, preventing races between updates. (`SubmitTreeUpdateAsync` internally queues the update, but there's still a small window where a race can occur.)
=> Await tree update

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/Filters/DuplicatedDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/IDependency.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependencyTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DuplicatedDependenciesSnapshotFilterTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TestDependency.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TestDependencyExtensions.cs
This computed property does not need to be on `IDependency`.
Part of work to consolidate code across the dependency node (in this case `IDependencyModel` and `IDependency`).
=> Compute alias when needed

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.State.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
Fixes #5386.
A data point used by the fast up-to-date check in VS is the last time the set of inputs changed. This is used to address issues described in #4736 and #3245.
After #5089 that time stamp was updated when the project loaded. This meant that loading a project which is up-to-date (from MSBuild's perspective) would always have `LastItemsChangedAtUtc` after the last output time, but building would not update the outputs and the project would be considered out of date until it was actually rebuilt (either due to clean/rebuild/input change).
This change only updates `LastItemsChangedAtUtc` when we already have a set of items. This means the property maintains its default value (`DateTime.MinValue`) after project load and is only updated when the set of items actually changes.
(This …
=> Fix up-to-date false negative on project load

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/PackageReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.zh-Hant.xlf
Unresolved `PackageReference` items will not have a path property. This exists on `ResolvedPackageReference`.
=> Remove unused PackageReference.Path XAML property

src/Microsoft.VisualStudio.Editors/OptionPages/GeneralOptionPageControl.xaml, src/Microsoft.VisualStudio.Editors/OptionPages/LoggingLevelToInt32Converter.vb
- Adds some vertical space between options
- Removes left margin from the "Logging Level" text so the left column is flush aligned
- Moves the combo box to the same horizontal offset as is used in other property pages (e.g. _VB Defaults_)
- Makes the group box align to top, as in other property pages (e.g. _Performance_)
- Reduces the height of the combo box to match other property pages
Before:
After:
=> Options layout

src/Microsoft.VisualStudio.Editors/OptionPages/GeneralOptionPageControl.xaml.vb, src/Microsoft.VisualStudio.Editors/OptionPages/GeneralOptionPageResources.Designer.vb, src/Microsoft.VisualStudio.Editors/OptionPages/GeneralOptionPageResources.resx, src/Microsoft.VisualStudio.Editors/OptionPages/GeneralOptions.vb, src/Microsoft.VisualStudio.Editors/OptionPages/LogLevel.vb, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.cs.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.de.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.es.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.fr.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.it.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.ja.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.ko.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.pl.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.ru.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.tr.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.zh-Hant.xlf, src/Microsoft.VisualStudio.Editors/PublicAPI.Shipped.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Menus.vsct, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LogLevel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheckLogger.cs
Fixes #5353.
This PR adds an additional log level option for the up-to-date check:
The _Minimal_ level will cause the up to date check to log a single line for any project not considered up to date.
For example:
```
1>FastUpToDate: Input 'C:\Repo\Library\Class1.cs' is newer (30/08/2019 5:18:37 PM) than earliest output 'C:\Repo\Library\bin\Debug\netstandard2.0\Library.dll' (30/08/2019 4:54:01 PM), not up to date. (Library)
1>------ Build started: Project: Library, Configuration: Debug Any CPU ------
1>Library -> C:\Repo\Library\bin\Debug\netstandard2.0\Library.dll
2>FastUpToDate: Input 'C:\Repo\Library\bin\Debug\netstandard2.0\Library.dll' is newer (30/08/2019 5:18:43 PM) than earliest output 'C:\Repo\ConsoleApp\bin\Debug\netcoreapp2.2\ConsoleApp.dll' (30/08/2019 4:54:02 PM), not up to …
```
=> Add 'minimal' log level for up-to-date check

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/Filters/DeduplicateCaptionsSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/Filters/DuplicatedDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/Filters/ImplicitTopLevelDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/Filters/UnresolvedDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/Filters/UnresolvedProjectReferenceSnapshotFilter.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DeduplicateCaptionsSnapshotFilterTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/UnresolvedProjectReferenceSnapshotFilterTests.cs
Looking over the filters used in processing dependency updates, they had misleading names and documentation.
b8f2576c995b01d86bc14a921b61caca6eb31eb3 makes a perf improvement too.
=> Dependency filter review

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/AbstractGenerateNuGetPackageCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/GeneratePackageOnBuildPropertyProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsSolutionBuildManager2Factory.cs
Previously for the Pack command we would set GeneratePackageOnBuild to true, and then do a build. This causes a problem as we would see the project as up to date even if the package output didn't exist.
This fixes the problem by setting GeneratePackageOnBuild to false, and then calling the Pack target, which will create build outputs and/or package outputs as necessary. Just calling Pack isn't enough, as it has a condition that it doesn't do a build if GeneratePackageOnBuild is true, which according to the Nuget team is by design.
Fixes #1339
Fixes [AB#935258](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/935258)
=> Force generate package on build to false when packing

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerView.vb, src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPageUserControlBase.vb, src/Microsoft.VisualStudio.Editors/Common/DTEUtils.vb, src/Microsoft.VisualStudio.Editors/Common/Utils.vb, src/Microsoft.VisualStudio.Editors/PropPages/AdvBuildSettingsPropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/AdvCompilerSettingsPropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPageInternalBase.vb, src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPageBase.vb, src/Microsoft.VisualStudio.Editors/PropPages/ReferencePathsPropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/ReferencePropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/TargetFrameworkMoniker.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/FileWatcher.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/Resource.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceFile.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceStringTable.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceTypeEditorImageBase.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/AppConfigSerializer.vb, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VisualBasic/VisualBasicNamespaceImportsList.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VisualBasic/VisualBasicVSImports.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/NameValuePair.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Build/BuildUtilities.cs
The former is clearer in code, and is faster in execution.
```
BenchmarkDotNet=v0.11.1, OS=Windows 10.0.18362
Intel Xeon Silver 4110 CPU 2.10GHz, 2 CPU, 32 logical and 16 physical cores
[Host] : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.8.3815.0
Clr    : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.8.3815.0
Job=Clr  Runtime=Clr
```
|        Method | SameLength |      Mean |     Error |    StdDev |    Median |
|-------------- |----------- |----------:|----------:|----------:|----------:|
|      Comparer |      False |  3.520 ns | 0.1193 ns | 0.3441 ns |  3.421 ns |
|  StaticEquals |      False |  2.661 ns | 0.1319 ns | 0.3890 ns |  2.447 ns |
|  MemberEquals |      False |  2.805 ns | 0.0251 ns | 0.0222 ns |  2.800 ns |
| StaticCompare |      False | 24.074 …
=> Use string.Equals over string.Compare

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/CrossTarget/IDependenciesRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/ProjectItemMetadata.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/DependenciesRuleHandlerBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.PackageDependencyMetadata.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Utilities/InternPool.cs
Part of #5044. For that issue we'll need to update how evaluation and design-time build data flows through the first stages of the dependency node pipeline.
Previously the code that handled this was implemented in `DependenciesRuleHandlerBase` for most types of dependencies, however `PackageRuleHandler` overrode this with largely copy/paste logic.
This PR allows the logic in the base class to be reused by `PackageRuleHandler` without duplication.
It also starts to unpick complexity in `PackageRuleHandler`, making a clearer division between the handling of evaluation data and design-time data.
=> Flatten package rule handler logic

build/import/Versions.props
I'm guessing the intention when changing version numbers to 16.3.0 was to keep them in line with VS, so...
=> Keep version number in line with Visual Studio

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/Renamer.cs
MEF lets you import something by type that is different to the type of the parameter.
=> Remove test-only constructor

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/CrossTarget/IDependenciesRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencyRulesSubscriberBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/DependenciesRuleHandlerBase.cs
The dependencies node defines interface `IDependencyCrossTargetSubscriber`, implementations of which subscribe to project Dataflow sources and emit events when data changes.
There are currently two implementations of this interface, `DependencyRulesSubscriber` and `DependencySharedProjectsSubscriber`. Both of these shared a considerable amount of code yet differed in various ways.
For example:
- They used different base classes (`OnceInitializedOnceDisposedUnderLockAsync` vs. `OnceInitializedOnceDisposed` respectively).
- The former protected against project unload and capabilities changes while processing updates, while the latter did not.
- The former suppressed version-only updates while the latter did not.
This PR extracts a new common base class `DependencyRulesSubscriberBase<T>` to …
=> Extract base class for rules subscribers

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/CrossTarget/IDependenciesRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencyRulesSubscriberBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/IDependencyCrossTargetSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/DependenciesRuleHandlerBase.cs
Includes #5420 so just review 43b9ab419ad1f942bc0d311d636590a3cfb7e009.
Previously the rules subscriber would subscribe to the active project during its initialization phase, then shortly after subscribe to all inner projects. This meant that the active project was subscribed to twice, leading to redundant work being done when updates fired.
=> Fix double subscribe to project data sources

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/CSharp/CSharpAssemblyInfoSpecialFileProvider.cs
This creates a special file provider for C#. This currently points to AssemblyInfoInternal, which I've verified works, though produces a file that doesn't compile in most SDK-style projects, because of duplicate attributes.
That will be fixed in #5347
=> Create a special file provider for C#, for the AssemblyInfo file

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesTreeViewProvider.cs
This was added in 8f558fe5d4f6891164601017b48d15a7bdb83ea6 in an attempt to suppress NRT warnings. The filePath variable may be null for non-project items, and so this was triggering errors in VS, such as that reported in #5454.
Removing this line does not seem to introduce any new warnings, and fixes the error.
=> Removes invalid Assumes.NotNull

build/import/Packages.targets
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/980771. This SDK has a fix to avoid NGEN'ing resource dlls for Editors and AppDesigner.
=> Avoid NGEN'ing resource dlls

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
For #5347
This allows the AssemblyInfo wizard to know which type of file to create.
=> Add GenerateAssemblyInfo property

src/Microsoft.VisualStudio.Editors/PropPages/PackagePropPage.vb
Probable fix for [972272](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/972272/)
This makes it impossible to set a license file path with invalid path characters
=> Check for invalid path characters in license file path

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ProjectItemsSchema.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractFindByNameSpecialFileProvider2.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractFindByNameUnderAppDesignerSpecialFileProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/LicensesSpecialFileProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IPhysicalProjectTreeStorageFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviders/AbstractFindByNameUnderAppDesignerSpecialFileProviderTestBase.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviders/LicensesSpecialFileProviderTests.cs
Fixes: https://github.com/dotnet/project-system/issues/4938.
This adds a new implementation of AbstractFindByNameSpecialFileProvider called AbstractFindByNameSpecialFileProvider2 that derives from the new AbstractSpecialFileProvider. The original will be removed & replaced in a later PR
=> Add licenses.licx special file provider

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VsBuildManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputFileChange.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsBuildManagerBridge.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsChangeTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsCompiler.QueueItem.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsCompiler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcher.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/IDesignTimeInputsBuildManagerBridge.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/IDesignTimeInputsCompiler.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsBuildManagerBridgeTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsCompilerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsDataSourceTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcherTests.cs
On balance most of the bits of the TempPE infrastructure either needs full paths, or doesn't care. Given that using full paths means we get de-duping of inputs for free, it makes sense to use them throughout.
I left the public API bits using relative paths for backwards compatibility reasons.
For #4163
=> Use full paths for design time inputs

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractFindByNameUnderAppDesignerSpecialFileProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AppManifestSpecialFileProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AppSettingsSpecialFileProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AssemblyResourcesSpecialFileProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/CSharp/CSharpAssemblyInfoSpecialFileProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/VisualBasic/VisualBasicAssemblyInfoSpecialFileProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ISpecialFilesManagerFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviders/AbstractFindByNameUnderAppDesignerSpecialFileProviderTestBase.cs
After we moved the template-based special file providers over to AbstractFindByNameUnderAppDesignerSpecialFileProvider, we stopped ensuring that the AppDesigner existed before we added the template, this caused template creation to fail.
=> Make sure AppDesigner exists before adding template

src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb
We were sending non-fatal watsons when opening resource files that were not language-specific.
=> Do not non-fatal watson on main path

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WindowsForms/WindowsFormsAddItemFilter.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/WindowsForms/WindowsFormsAddItemFilterTests.cs
Fixes #5398 
We filter Windows Forms templates by capabilities but there are two that don't support that, so this hides them too.
=> Hide broken windows forms templates

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesNodeCommandGroupHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SuppressObjectBrowserForPackageReferenceCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Input/GetCommandStatusResult.cs
Fixes part of #1256.
There's nothing obviously correct to show for NuGet packages themselves in the Object Browser.
Instead we should in future allow the Object Browser to be launched from child nodes representing assemblies within the packages themselves (the other part of #1256).
Legacy doesn't offer Open in Object Browser for packages either, though if using `packages.config` then package assemblies are added directly as references and do work with the Object Browser.
=> Suppress "Open in Object Browser" for NuGet packages

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependencyTreeFlags.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/SubTreeRootDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/AnalyzerRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/AssemblyRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/ComRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/FrameworkRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/ProjectRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/SdkRuleHandler.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/SubTreeRootDependencyModelTests.cs
We were using IDM_VS_CTXT_REFERENCE context menu for the Packages/Projects/References node because CPS throught they were "References". We've stopped marking them as as Reference and instead ReferenceFolder, which causes CPS to use the IDM_VS_CTXT_REFERENCEROOT context menu.
Also simplified the number of flags we were using for the nodes - they aren't being used anywhere and we can them back if we need them.
Before:
After:
=> Use References folder context menu

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs
Fixes #5531. 
The initialisation code had a pathway that would attempt to trigger initialisation again. The base class `OnceInitializedOnceDisposedAsync` does not support this re-entrancy.
=> Fix re-entrant initialisation

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesTreeViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/TargetDependencyViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/Filters/UnresolvedProjectReferenceSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/IDependencyExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/DependenciesSnapshotFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependenciesSnapshotTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependencyExtensionsTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs
Fixes #5539.
Previous logic would display a dependency as unresolved if it had a descendant that was unresolved yet not actually displayed in the tree due to an intermediary node being hidden.
This change determines this status of dependencies by walking the graph from visible top-level nodes.
With this change I believe it's no longer possible to show a dependency or dependency group as unresolved which does not have an unresolved child (or is unresolved itself). I'm really pleased to have gotten rid of this confusing UI state.
Because we now walk the tree, it's no longer necessary to lazily compute and store a bunch of additional information about the snapshot. This means several collections have been removed, along with locks to protect them. There's no locking as state no longer …
=> Consider reachability of unresolved children in dependencies node

src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPage.vb, src/Microsoft.VisualStudio.Editors/Resources/Microsoft.VisualStudio.Editors.Designer.Designer.vb, src/Microsoft.VisualStudio.Editors/Resources/Microsoft.VisualStudio.Editors.Designer.resx, src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.cs.xlf, src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.de.xlf, src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.es.xlf, src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.fr.xlf, src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.it.xlf, src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.ja.xlf, src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.ko.xlf, src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.pl.xlf, src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.ru.xlf, src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.tr.xlf, src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.zh-Hant.xlf
Adds a check for invalid characters in the name of the resource file on the Application property page. It fails validation instead of a warning because the file cannot exist.
=> Check for invalid characters in resource file 

src/Microsoft.VisualStudio.Editors/PropPages/CodeAnalysisPropPage.vb
1. Bump up the latest stable version to 2.9.5
2. Add a temporary workaround for https://github.com/NuGet/Home/issues/8616, which seems to avoid the underlying issue.
=> Minor updates to Code Analysis property page

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WindowsForms/WindowsFormsAddItemFilter.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/WindowsForms/WindowsFormsAddItemFilterTests.cs
Follow up to #5501 but for the VB templates, which are named slightly differently.
This fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/975632 but I'm not using the fancy AB# notation because I don't what this to close that. Strictly speaking https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/206040?_a=overview is the solution to that work item, this just responds to the change.
=> Hide broken templates for VB WinForms projects too

src/Microsoft.VisualStudio.Editors/PropPages/AdvBuildSettingsPropPage.vb
This ensures that the tab stop on the link is respected. Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/981334
=> Set the length of the language version link text

src/Microsoft.VisualStudio.Editors/ResourceEditor/FindReplace.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/Resource.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView_EditorState.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceFile.vb
As I'm looking into splitting the Resource Designer UI from the underlying logic I'm getting tired of looking at all the old-school `Hashtable`s and `ArrayList`s. They also make it harder to understand the code.
This PR replaces a number of these "untyped" collections with the equivalent generic versions.
=> Clean up untyped collections in the Resource Designer

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ProjectItemsSchema.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ProjectItemsSchema.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ProjectItemsSchema.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ProjectItemsSchema.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ProjectItemsSchema.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ProjectItemsSchema.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ProjectItemsSchema.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ProjectItemsSchema.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ProjectItemsSchema.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ProjectItemsSchema.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ProjectItemsSchema.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ProjectItemsSchema.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ProjectItemsSchema.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ProjectItemsSchema.xaml.zh-Hant.xlf
Fixes #5526
This adds file extensions, and corresponding content types, for the files that the legacy project system has in its allow list ([here](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fvsproject%2Flangproj%2FCLangHierarchy.cpp&version=GBmaster&line=1666&lineEnd=1666&lineStartColumn=30&lineEndColumn=52&lineStyle=plain)) for not having a number on the end of its generated filename.
This goes with https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/207117?_a=overview, which adds support for the SuppressNumericSuffix metadata, though no harm will come if this is merged before that.
=> Suppress numeric suffixes

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcher.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcherTests.cs
Fixes [AB#994099](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/994099)
Switch to asynchronous disposal of the file watcher, so project unload isn't blocked. If the file watcher never actually got to process any of its input, then disposal could require a switch to the UI thread in order to get the file watcher service.
=> Switch to asynchronous disposal so we don't block project unload

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/Renamer.cs
Somewhere along the way the check go reversed so we never actually attempt to do a rename.
=> Correctly check if the user wants to rename the symbol

src/Microsoft.VisualStudio.Editors/DesignerFramework/BaseRootDesigner.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/Category.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/CategoryCollection.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/FileWatcher.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/FindReplace.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/Resource.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceComparer.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceComparerForFind.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView_EditorState.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceListView.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceSerializationService_Store.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceStringTable.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ThumbnailCache.vb, src/Microsoft.VisualStudio.Editors/StringComparers.vb
This gets rid of almost all the remaining Hashtables in the Resource Editor, as well as most of the ArrayLists. I'll get the rest of the ArrayLists in another PR.
=> More non-generic collection clean-up in Resource Editor

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.ContextTracker.cs
While investigating [AB#719762](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/719762), which uses non-standard "CPS Barebone" project templates, it became clear we do not handle empty target frameworks correctly in some cases.
=> Better handle empty target frameworks

src/Microsoft.VisualStudio.Editors/DesignerFramework/BaseRootDesigner.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/Category.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/CategoryCollection.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/FileWatcher.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/FindReplace.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/Resource.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceComparer.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceComparerForFind.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView_EditorState.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceListView.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceSerializationService_Store.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceStringTable.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ThumbnailCache.vb, src/Microsoft.VisualStudio.Editors/StringComparers.vb
This introduced a bunch of bugs due to behavior differences between hashtables and dictionaries, including the ability to pass null as the key and indexer lookup when the key doesn't exist. I started fixing it but had no confidence that I caught all the changes.
=> Revert https://github.com/dotnet/project-system/pull/5577

src/Microsoft.VisualStudio.Editors/ResourceEditor/FindReplace.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceFile.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceListView.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceStringTable.vb
Fix a number of exceptions that could occur as the result of replacing `Hashtable` with `Dictionary(Of T, U)`.
1. In ResourceFile.vb, replace indexing into `_resources` with calls to `TryGetValue`. The `Hashtable` indexer would return `null` when the key was not found, but `Dictionary(Of T, U)` throws an exception.
2. Remove `ResourceFile.GetEnumerator`. This used to just return `_resources.GetEnumerator`, and when `resources` was a `Hashtable` the enumerator would output instances of `DictionaryEntry`. The `Dictionary(Of T, U)` enumerator instead outputs `KeyValuePair(Of T, U)`, resulting in type cast exceptions everywhere we tried to enumerate the `ResourceFile`. Rather than update `ResourceFile` to properly support `IEnumerable(Of Resource)` the `GetEnumerator` method has been removed, …
=> Fix exceptions in the RESX designer

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Menus.vsct, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs
This makes sure that the Debug profile and framework switchers are known to be checkable, which helps screen readers tell users that. After this change, Before this change, Windows Narrater says "menu item", after this change it says "menu item, unchecked" for unchecked items.
Fixes our part of: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/642995
=> Make sure screen readers are aware of checkable menu item

build/import/IntegrationTests.targets
Test Explorer has started respecting this property - avoid clashing with it to avoid it failing to find this auto-generated file.
=> Rename RunSettingsFilePath to avoid clashing with Test Explorer

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/Interop/VsHierarchyExtensions.cs
This suppresses:  A member returning a [MaybeNull] value introduces a null value when 'T' is a non-nullable reference type, which is unavoidable without compiler work to track state more accurately. This is being tracked by:
https://github.com/dotnet/roslyn/issues/38638
=> Suppress nullable warnings

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/AnalyzerDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/AssemblyDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/ComDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/DiagnosticDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/FrameworkDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/GraphNodePriority.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/PackageAnalyzerAssemblyDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/PackageAssemblyDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/PackageDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/PackageFrameworkAssembliesViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/PackageUnknownDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/ProjectDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/SdkDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/SharedProjectDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/TargetDependencyViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/Dependency.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/AnalyzerDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/AssemblyDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/ComDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/DiagnosticDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/PackageAnalyzerAssemblyDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/PackageAssemblyDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/PackageDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/PackageFrameworkAssembliesViewModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/PackageUnknownDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/ProjectDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/SdkDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/SharedProjectDependencyModelTests.cs
These only apply to graph nodes. This makes their purpose clearer.
Back when `Dependency` implemented `IDependencyModel`, having them on `Dependency` may have made more sense.
=> Move dependency priority fields to own type

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/SolutionService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsSolutionEventListener.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ISolutionService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/ProjectRuleHandler.cs
Fixes #2640.
Currently when a project is closed, the dependencies node notifies any projects that depend upon it to update their dependency tree as that project is no longer resolved.
This is useful when, for example, a subset of projects are unloaded.
However when a solution is being closed there's no need for a project referrer to update its tree in response to unloading projects. Doing so creates a lot of redundant tree updates at a time when we should just be tearing everything down.
This PR avoids doing that redundant work.
After this change, looking in PerfView at an ETL trace, I see almost no activity within the dependencies node during solution close, whereas beforehand there was a moderate amount.
=> Avoid P2P reference notification on solution close

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.Designer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.zh-Hant.xlf
Adds a colon to the "Executable" label for consistency:
Uses consistent apostrophes in the French translation.
//cc: @tmeschter
=> Debug page punctuation

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/SolutionService.cs
Fixes: https://github.com/dotnet/project-system/issues/5650
OncenInitializedOnceAsync pushes onto a background thread by default, change the approach to just derive from OnceInitializedOnceDisposedAsync and explicitly switch to UI thread.
=> Fix exception on shutdown

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/AbstractExtenderCATIDProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/DebugProfileDebugTargetGenerator.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/SolutionService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/Actions/GraphActionHandlerBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/ViewProviders/ProjectGraphViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Extensibility/ProjectExportProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Frameworks/TargetFramework.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/InterceptingPropertyValueProviderBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/CancellationSeries.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/TaskDelayScheduler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesTreeViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependencyTreeTelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/AggregateDependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs
VS will automatically show documentation from interface and base declarations.
=> Remove unneeded inheritdoc

src/Microsoft.VisualStudio.Editors/OptionPages/GeneralOptionPage.vb
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1019631/.
Currently, our Tools | Options page is not loading. We used to use the `UIElementPage(bool isServerAware)` constructor to specify that the settings handled by our Tools | Options page should be stored back to the server in cloud environments. However, this constructor has been removed in favor of other methods of controlling the storage. At runtime, the page fails to load with a MissingMethodException or something similar.
Here we just remove the call to the now non-existent constructor which should be all we need to get things loading again. A future change will update how we store the settings to the cloud environment, but at the moment we are blocked by https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1023320 …
=> Stop calling non-existent base constructor

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/GetProfileNameDialog.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UI/DontShowAgainMessageBox.xaml
Fixes: https://github.com/dotnet/project-system/issues/4827
This opts into UseLayoutRounding  and TextOptions.TextFormattingMode="Display" to improve text rendering of these pages/dialogs.
Before:
After:
=> Improve text rendering for WPF pages/dialogs

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProjectTypeRegistration.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProvideDiffSupportedContentTypeAttribute.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProvideEditorFactoryMappingAttribute.cs
Part of fixing #4215, this adds the registry keys necessary to tell the diff window what to do with our project files. This is responding to the removal of the temporary registry keys in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/214544. Since the keys deal with specific .NET project file extensions they belong in this repo.
=> Add necessary registrations for project file editing

src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.vb
Bug was introduced in https://github.com/dotnet/project-system/commit/cb72e7b0
Fixes https://developercommunity.visualstudio.com/content/problem/812018/vs2019-preview-4-broke-conditional-compilation-sym.html
=> Fix incorrect symbol removal logic

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/FSharp/FSharpProjectSelector.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/OrderAddItemHintReceiver.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/SolutionService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VersionCompatibility/DotNetCoreProjectCompatibilityDetectorInitializer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Xproj/XprojProjectFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredProjectsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AdditionalFilesItemHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AnalyzerItemHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/MetadataReferenceItemHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/ProjectPropertiesItemHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/AdditionalFilesItemHandlerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/AnalyzerItemHandlerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/MetadataReferenceItemHandlerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/ProjectPropertiesItemHandlerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/FSharp/FSharpProjectSelectorTests.cs
The decision was made to stop checking for null in https://github.com/dotnet/project-system/pull/3284, remove more of these that have sneaked in.
=> Do not check for null in MEF constructors

tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/Ordering/AbstractMoveCommandTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/Ordering/MoveDownCommandTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/Ordering/MoveUpCommandTests.cs
https://github.com/dotnet/project-system/pull/5662 enforced modifier order, but I missed that there were files that violated it.
=> Order modifiers

.vsconfig
4.7.2 SDK is no longer installed by default, update to 4.8 to avoid VS wanting to install additonal features.
=> Depend on .NET Framework 4.8 SDK

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/Interop/IVsShellUtilitiesHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/Interop/VsShellUtilitiesHelper.cs
For a brief moment in time I was looking to extend this interface and its implementation to provide the VS installation directory. But it didn't quite do what I wanted.
Pulled these cleanup commits out to their own branch.
=> IVsShellUtilitiesHelper cleanup

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreProgressTracker.PackageRestoreProgressTrackerInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsChangeTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PackageRestore/PackageRestoreProgressTrackerInstanceTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsChangeTrackerTests.cs
A while back I extended CPS to allow using `ValueTuple` as well as `Tuple` for sync-link'd data. This utilises that change on our side.
=> Avoid Tuple allocation for Dataflow sync link

.editorconfig
The default was always to have a body, which forced Code Cleanup to fix them up.
=> Favor expression local functions when single line

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProjectTypeCapabilities.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddExistingItemAboveCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddExistingItemBelowCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddExistingItemCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddNewItemAboveCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddNewItemBelowCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddNewItemCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/MoveDownCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/MoveUpCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/OrderAddItemHintReceiver.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/PasteOrdering.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Order/TreeItemOrderPropertyProviderSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs
Fixes #5711. 
Relates to #5754.
Relates to #5702.
Previously, import tree items would always be displayed in alphabetical order. With this change, their tree order reflects the actual order they are evaluated in. This is helpful when tracing the value of a given property, for example.
For CPS to respect the `IProjectTree2.DisplayOrder` property, the `SortByDisplayOrder` capability must be present. This was only used in F# projects before where it controlled both the display and manipulation of item order. Consequently a new `EditableDisplayOrder` capability has been added which covers the manipulation component, and has been added to F#-specific commands/exports.
Alphabetical:
In evaluation order:
=> Display import tree items in correct order

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs
Improves the workaround for #5711 added in #5736.
Longer term we'll want to enable display order within the tree so that items with duplicate captions appear correctly. Without that, the tree is misleading. For example, an ASP.NET Core project has four sibling `Sdk.props` files:
=> Consider existing child captions when preventing duplicates

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerPanel.vb, src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerDocData.vb, src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerEditorFactory.vb, src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerLoader.vb, src/Microsoft.VisualStudio.AppDesigner/PublicAPI.Shipped.txt, src/Microsoft.VisualStudio.Editors/PublicAPI.Shipped.txt
Fixes #5723
A change was made to the shell to fix https://devdiv.visualstudio.com/DevDiv/_workitems/edit/684877 which means that while reopening document windows, all of the doc data are kept in the running document table (see code [here](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fenv%2Fmsenv%2Fcore%2Fvsshlsvc.cpp&version=GC6ff311afae3a6bfbd18cd01097c84fa8aa03f8e5&line=4107&lineEnd=4108&lineStartColumn=1&lineEndColumn=1&lineStyle=plain)). This broke the property pages because they always created a new doc data for each property page tab as its being created, but if the doc data was already in the RDT, that new one never got in there so not only was the new one orphaned (never initialized), worse the doc data that is in the RDT continued to be used by other components in …
=> Don't dispose PropPageDesignerDocData when designer is closing

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.State.cs
Fixes #4737.
outputRelativeOrFullPath was using the legacy property OutPath.
OutDir is used instead to fix the fast up-to-date check.
=> Adding OutDir property for msbuild.

src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPage.Designer.vb
The ManifestExplanationLabel is the two-line text below the Icon and manifest radio button. Currently, it's a text box with the label appearance. This affects the accessibility of the UI: there is a tab stop in it (when it shouldn't since it's not interactable) and a screen reader might confuse it as a text input.
**Before:**
**After:**
By changing the text box to a label, it does not focus nor look intereractive. Also, the position and size remain the same.
Work item tracked in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1049278
=> Display ManifestExplanationLabel as a label

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/ExecutableLaunchSettingsUIProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/ProjectLaunchSettingsUIProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageControl.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/NameValuePair.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchSettingsUIProvider.cs
Part 1 of 2 ahead of remote-debugging support for the property pages. Part 2 is annotations, and is more involved as `DebugPageViewModel` was difficult to annotate.
=> Property page tidying

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs
Fixes #5711.
Fixes #5754.
This PR shows imports in the correct order, and allows duplicate imports to appear side-by-side in the tree.
Since https://dev.azure.com/devdiv/DevDiv/_git/CPS/pullrequest/220752, CPS allows root graft tree providers (like the import tree) to opt-in to `IProjectTree2.DisplayOrder` support.
---
~This PR is blocked until the following PRs are merged:~
~This PR is blocked until we have an insertion of CPS with the above fixes.~
=> Import tree display order

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProjectTypeCapabilities.cs
We were not registering "Shared Projects" with IVsSharedMSBuildFilesManagerHierarchy, which is hidden behind the "SharedImports" capability (not to be confused with "SharedProjectReferences"), this led to:
- Context switcher was broken
- Reference Manager didn't think that any Shared Projects were referenced
This fixes:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/508624
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/792775
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/972385
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/979565
https://developercommunity.visualstudio.com/content/problem/606555/the-code-editor-project-selector-switches-back-to.html
https://developercommunity.visualstudio.com/content/problem/130875/console-net-core-2-app-still-not-showing- …
=> Register referenced "Shared Projects"

ProjectSystem.sln
CPS recently changed to register shared projects differently. That seems to have resulted in VS adding these lines to the sln file.
=> Update sln changes to shared projects

src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/IFileSystem.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/Win32FileSystem.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IFileSystemMock.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs
We shouldn't be using local time to determine file write times, as clocks can change while VS is open.
=> Remove LastFileWriteTime

THIRD-PARTY-NOTICES.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed/Annotations.cs
These definitions are taken from dotnet/runtime (originally from dotnet/corefx) which uses the MIT license.
=> Use MIT license for nullable annotations

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Certain projects in http://github.com/dotnet/runtime "turn off" package restore via <RestoreProjectStyle>Unknown</RestoreProjectStyle>: https://github.com/dotnet/runtime/blob/86bfd8d46b3817e2a027b23d829cd0d035cd8ad6/eng/restore/repoRestore.targets#L4.
This causes us to nominate to NuGet, only for it to fail to produce an assets file. This causes us to never complete operation progress resulting in https://developercommunity.visualstudio.com/content/problem/884350/intellisense-waiting-forever-dialog-in-dotnetrunti.html.
Turn off PackageReferences support if is not PackageReference based.
This works quite well, and can be changed dynamically and does the right thing.
=> Respect "RestoreProjectStyle"

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/AnalyzerRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/DependenciesRuleHandlerBase.cs
Fixes #5418.
The dependency node receives both evaluation (unresolved) data and design-time build (resolved) data. Both sources provide data about the same items and must be correlated and combined.
A while ago the dependency node changed to disallow adding items to the tree that appear _only_ in design-time build results. This broke the Analyzers node as analyzers are not available during evaluation (see #4782).
This change allows specific rules to opt out of the restriction, doing so only for analyzer items.
=> Don't require analyzers to be in evaluation data

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Imaging/AppDesignerFolderProjectImageProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Imaging/ProjectImageKey.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/AbstractSpecialFolderProjectTreePropertiesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/AppDesignerFolderProjectTreePropertiesProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/AppDesignerFolderProjectTreePropertiesProviderTests.cs
Fixes: https://github.com/dotnet/project-system/issues/216
When the properties folder is explicitly included in the project when globs are turned off and source files are included from under it, or when explicitly included in the project via `<Folder Include="Properties" />` and its missing from disk, use the missing folder icon to make it obvious as to why Add/Open Folder in File Explorer don't work.
Also made it easier for https://github.com/dotnet/project-system/issues/5803 to be implemented by plumbing out the expanded folder case.
Adding a specific missing folder icon for the App Designer is being tracked by: https://github.com/dotnet/project-system/issues/5803.
=> Use missing folder icon when Properties is missing from disk

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Fixes: https://github.com/dotnet/project-system/issues/5847
CPS monitors and reevaluates when items added to `<AdditionalDesignTimeBuildInput>` are added, removed or deleted. Start monitoring global.json files starting from the solution directory and higher so that we can react to changes to it that affect MSBuild SDK resolution.
Note, this over-eagerly finds global.json files that may not influence the project, ie Given a solution structure like so:
```
C:\
C:\Folder\
C:\Folder\Solution\
C:\Folder\Solution\global.json
```
This will monitor for changes in `C:\`, `C:\Folder` and `C:\Folder\Solution` despite only `C:\Folder\Solution\global.json` ever infuencing SDK resolution. This is a limitation in MSBuild; there's no way to batch or filter the items inside evaluation and outside of a …
=> Reevaluate when global.json changes

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/AbstractProjectConfigurationProperties.cs
Return a value for DebugInfo to unblock unit test profiling.
Full support for the rest of these is #3622
=> Implement the DebugInfo property

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs
Project imports were being marked with FileOnDisk, but not FileSystemEntity which is the base between FileOnDisk and Folder. This enables the "Copy Full Path" command but there is additional work needed to make the command actually execute which is being tracked by https://github.com/dotnet/project-system/issues/102.
=> Mark ProjectImport's with FileSystemEntity

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml
Found another text box without a help text, follows #5802.
Note: no localization needed.
Before:
After:
=> Add help text to Executable path watermark.

tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/MiscellaneousRuleTests.cs
Found this bug while reviewing the file with @drewnoakes 😄.
=> Compare visible attribute ignoring the case of the strings.

src/Microsoft.VisualStudio.Editors/package/VBPackage.vb
Fixes #5858
This is a short term solution to fix the regression for 16.5 where the Debug -> [Project] Properties menu item shows a blank screen. The real fix for this will be #5317.
Whats happening is that the Application tab initializes and then switches to the Debug page, but when the OutputType property is read to initialize the Application table it sets some data flowing through the system including a version-only update of ProjectRuleSource, which gets to the WorkspaceContext, and that triggers operation progress. It happens just in time for the Debug editor factory to be asked to initialize, which sees that operation progress has started, so gets the PLM window frame, which it can't deal with, and bombs out.
The change itself should be safe enough because the only thing that …
=> Opt the PropPageDesignerEditorFactory out of PLM

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.State.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectSnapshot2Factory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PackageRestore/PackageRestoreProgressTrackerInstanceTests.cs
Fixes #5846.
Builds on top of #5849.
This change teaches the fast up-to-date check to also consider `IProjectSnapshot.AdditionalDependentFileTimes`. This required a new subscription to `ProjectSource`, and plumbing the values through the state object.
Also, this introduces a class of input that is "not required". Specifically, potential paths to files which are probed for are not required, as those paths are speculative catch-alls. Previously a missing input would cause the project to be considered out-of-date. That behaviour is preserved for all except these new `AdditionalDependentFileTimes` items.
=> Up-to-date check considers AdditionalDependentFileTime items

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/ProjectImports/ImportTreeCommandGroupHandler.cs
All project systems use primary editor as the default editor for "Open". This has no observable change, but is just done for correctness.
=> Open import files using primary editor

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IVsOnlineServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/Renamer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsOnlineServices.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsOnlineServicesFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/CSharp/RenamerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/RenamerTestsBase.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/VisualBasic/RenamerTests.cs
We've gotten reports that renaming a file in Solution Explorer in VS Online scenarios causes VS to crash. I haven't been able to reproduce the issue, but it is conceivable that the server is trying to show the rename dialog and things are going sideways at that point. Until we can make this work properly we should block off the scenario and not even try to rename the file.
Fixes [AB#1063020](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1063020).
=> Block rename in online scenarios

src/Common/BannedSymbols.txt
To avoid double-initializing, you are meant to call EnsureInitialized/InitializedAsync.
Note, until https://github.com/dotnet/roslyn-analyzers/issues/3295 is fixed, this doesn't cover much - but will do if we pick up a new version of the analyzers with that bug fixed.
I ran into this when fixing https://github.com/dotnet/project-system/pull/5890.
=> Ban initialize methods in OnceInitializedOnceDisposedXXX

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencyRulesSubscriberBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/IDependencyCrossTargetSubscriber.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/AssertEx.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Automation/VisualBasic/VisualBasicNamespaceImportsListTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependenciesSnapshotTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs
Fixes #5836 and impacts #4474.
The first few commits are some clean-up. The main change is in 5778c199ad907fe9217b8d79dd00892a4efdde1e:
> A project subscription (evaluation or design-time build) can update in such a way that produces no change to the dependencies tree.
> 
> Previously, when no tree changes were observed we would not trigger an update. This, however, meant that we held a transitive reference to the project instance (via the catalog collection).
> 
> This change ensures we always accept updates to other fields (not just catalogs) regardless of whether `IDependencyModel` changes were made or not.
=> Fix project instance leak

src/Microsoft.VisualStudio.ProjectSystem.Managed/LinqExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.ImplicitProjectCheck.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs
=> Import tree treats NuGet props/targets as read only

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/Snapshots/RestoreHasher.cs
Fixes: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1075169
We weren't nominating ProjectReferences because they weren't factored in the hash.
=> Nominate for restore when project references change

build/import/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Commands/DependenciesContextMenuProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Commands/HideAddReferenceCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Commands/ReferenceManagerCommandHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Commands/SuppressAddReferenceCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Commands/SuppressObjectBrowserForPackageReferenceCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Order/TreeItemOrderPropertyProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/ProjectImports/ImportTreeCommandGroupHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Input/AbstractSingleNodeProjectCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Input/GetCommandStatusResult.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependencyTreeFlags.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/SubTreeRootDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/AnalyzerRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/AssemblyRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/ComRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/FrameworkRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/ProjectRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/SdkRuleHandler.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/SubTreeRootDependencyModelTests.cs
Fixes #5922.
- Opts in new menus for dependencies tree items
- Suppresses the old "Add Reference" command 
- Wires up behaviour for new "Add * Reference" commands to launch Reference Manager at the correct page
Note that the NuGet team will be modifying package-related items here too.
- 'Analyzers', 'Frameworks' and 'Packages' nodes have empty context menus, though they may be added to in future if needed. NuGet will almost certainly be adding the the 'Packages' context menu.
- Target framework nodes (for multi-targeting projects) currently display the same as the 'Dependencies' node itself. We may wish to suppress commands from these menus as they currently apply to all target frameworks. This will require coordination with the NuGet team.
- Requires …
=> Enable new dependencies tree context menus

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
#5906 caused the "COM" reference manager page to appear for .NET Core projects before 3.0, which is not supported.
=> Remove COMReferences capability for .NET Core < 3.0

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/TargetDependencyViewModel.cs
Prevents creating new `String`/`ImmutableHashSet<string>` instances to back `ProjectTreeFlags` instances on every project update.
=> Cache flags applied to configuration nodes in dependencies tree

build/import/HostAgnostic.props, build/import/Workarounds.targets
Fixes: https://github.com/dotnet/project-system/issues/5969.
Up-To-Date check didn't know we were remove these copy to output directory items, move their removal to evaluation time.
=> Fix up-to-date in project system

setup/ProjectSystemSetup/Properties/launchSettings.json
Add launch profiles to make it a little easier to debug VS Online scenarios.
The server profile requires that you fill in a path to a folder or solution for the server to open when it launches, and the the client profile requires that you fill in the "workspace ID" of the server to connect to.
Note that the order of parameters is important. The solution/folder to open, if any, must always be the first argument to devenv.exe (both in local and online scenarios). "/rootsuffix" needs to be the first switch if you wish to debug an experimental instance. The VS Online-specific switches come after those.
Also note that the /server and /client switches seem to be incompatible with /log, or at least I could never find an order that allowed both to work properly.
=> Add launch profiles for VS Online

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectDebuggerProvider.cs
`TryGetProjectItemPathFromDeployedPath` can output `null` when returning `true`.
=> Fix annotation warning

src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.vb
This is an automated codefix for IDE0075 _Visual Basic Conditional expression can be simplified_.
This started appearing in the output window during build.
=> Fix compile warning

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/DependenciesAttachedCollectionSourceProvider.Providers.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/DependenciesAttachedCollectionSourceProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/IDependenciesTreeAttachedCollectionSourceProvider.cs
Adds the `IDependenciesTreeAttachedCollectionSourceProvider` interface as an extension point for third parties to attach descendants to top-level dependencies tree items using the new mechanisms.
This is the first version of the API. It will likely be extended to support search. Once finalised, it will be made public.
=> Introduce extension point for third parties

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
This fixes https://github.com/dotnet/project-system/issues/5918
App.config was not taking into consideration in FUTD. The issue is that App.config was using the intermediate filename as a source.
This fix enables FUTD to check App.config.
The item AppConfigWithTargetPath now gets the application configuration filename from the property  AppConfig.
=> Fix fast up-to-date check to detect app.config

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
Fixes #4117 
This fixes the case when adding item Analyzer as a relative paths in in csproj
=> Fast up-to-date convert relative path to absolute for item Analyzer in NetCore

src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Unshipped.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesTreeViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependencyTreeFlags.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/PackageDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/ProjectDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/SdkDependencyModel.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/PackageDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/ProjectDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/SdkDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/TreeView/DependenciesTreeViewProviderTests.cs
Will address #6012 once this feature branch is merged into master.
---
Previously, changed nodes were removed from the tree and re-added, resulting in different hierarchy IDs for the replacements and meaning that any expansion state was not restored.
This logic existed to work around a limitation of the graph node implementation.
We no longer use graph nodes in the dependencies tree so can now fix this.
=> Don't collapse dependencies tree items on updates

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.State.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
Fixes #6006
Fixes [AB#1083953](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1083953)
The bug is that Fast up-to-date cannot detect when project.assets.json is deleted from the filesystem.
In case project.assets.json is missing FUTD will consider the project out of date.
This implementation take the output from Evaluation and keep a list (LastAdditionalDependentFileTimes) of the files in ApplicationDependentFileTimes that are present in the filesystem. In case projec.assets.json is deleted, then it compares the LastAdditionalDependentFileTimes with the current existing files.
In case FUTD is enabled, then it will check AdditionalDependentFilesAddedOrRemoved  to decide if the project is out of date or not.
=> Add Fast up-to-date the capability to detect project.assets.json

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsCompiler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/Web/RemoteCacheFile.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/IFileSystem.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/Win32FileSystem.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.TimestampCache.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/IO/Win32FileSystemTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IFileSystemMock.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs
We had races between checking that a file exists and reading its last write time, meaning that we could end up with DateTime.FromFileTime(0) in caches and fields.
Add two methods for the common usage in the tree, and treat situations where file cannot be accessed the same as the file not existing.
=> Add new file system methods for getting file write times

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/SolutionService.cs
This type should be disposed when the solution is unloaded, but did not declare `IDisposable` in its interface list, so its `Dispose` method was never called.
=> Fix disposal of SolutionService

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TargetFrameworkProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Frameworks/ITargetFramework.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Frameworks/ITargetFrameworkProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Frameworks/TargetFramework.cs
Contributes towards #4886.
- Removes `ITargetFrameworkProvider.GetNearestFramework`
- Removes `ITargetFramework.FrameworkName`
=> Remove unused ITargetFramework code

src/Microsoft.VisualStudio.Editors/AddImportsDialogs/AddImportsDialogService.vb, src/Microsoft.VisualStudio.Editors/AttributeEditor/PermissionSetService.vb, src/Microsoft.VisualStudio.Editors/PropPages/BuildEventCommandLineDialogService.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorFactory.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorRefactorNotify.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsDesignerEditorFactory.vb, src/Microsoft.VisualStudio.Editors/VBRefChangedSvc/VBReferenceChangedService.vb, src/Microsoft.VisualStudio.Editors/XmlIntellisense/XmlIntellisense.vb, src/Microsoft.VisualStudio.Editors/package/VBPackage.vb
Fixes #6035
When porting things from pkgdef to attributes I missed that the editor extension rank for the settings designer was specified in hex. I've fixed this and made it more clear for the resource editor too.
In fixing that, I noticed a few other things that were wrong, so fixed them too. Basically I forgot to compare key values last time, just existence of keys.
=> Fix some differences from the old Microsoft.VisualStudio.Editors.pkgdef

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreDataSource.cs
If the assets file was not written after restore, treat the restore as a failure.
This is one of the causes of https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1052518, which is fixed by NuGet/NuGet.Client#3320, but doing this as a defense in deep in case we hit future issues like this.
=> Treat missing assets file as failure

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/CompileItemHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IApplyChangesToWorkspaceContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IProjectUpdatedHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs
This makes three changes:
- Remove unused isActiveContext parameter 
- Avoid duplicate EndBatch calls (cause of this https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1087604 and hiding the underlying exception which will be captured in https://github.com/dotnet/project-system/pull/6051)
- Mark operation progress as finished _before_ we've done the rename prompts, not after.
=> Fix reliability of language service integration

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreUnconfiguredInputDataSource.cs
We were missing stacks/targetsite because we were reporting an unthrown exception.
=> Improve user fault telemetry

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/ResolvedPackageReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.zh-Hant.xlf
Adds `GeneratePathProperty` which is present on the (unresolved) `PackageReference` rule, and
should be available for resolved packages too.
Removes unused `ResolvedPackageReference` properties.
=> Update ResolvedPackageReference rule

build/import/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IUnconfiguredProjectVsServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/AssetsFileAttachedCollectionSourceBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/AttachedCollectionItemBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/DependenciesAttachedCollectionSourceProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/DependenciesSearchContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/DependenciesSearchProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/DiagnosticItem.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/IContainedByAttachedItems.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/PackageAssemblyGroupItem.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/PackageAssemblyItem.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/PackageReferenceItem.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/ProjectReferenceItem.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/MefExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectTreeExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/ResolvedPackageReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Assets/Models/AssetsFileDependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Assets/Models/AssetsFileLogMessage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Assets/Models/AssetsFileTarget.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Assets/Models/AssetsFileTargetLibrary.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/DependenciesTreeViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Models/PackageDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/PackageDependencyModelTests.cs
This PR introduces a functional version of dependencies tree search. Next week I will be working to consolidate the dual tree construction approaches (top-down during user expansion, vs. bottom-up during search) as part of the extensibility API design.
---
Solution Explorer search occurs via the `ISearchProvider` interface. When a search is requested, we pass back tree items that match the search expression for the tree to display. At that point we are unlikely to have materialised items ready to return, so we create just those nodes that match. The tree then uses the "contained by" relationship to populate ancestor nodes, with the expectation that an ancestor will eventually exist in the current tree. For search, these are the `IVsHierarchyItem` objects that back top-level dependencies. …
=> Implement dependencies tree search

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProjectTypeRegistration.cs
We were missing some values that the legacy project system registers. We're still missing some after this, but `PossibleProjectExtensions` unblocks #6053
=> Add some missing values from our project type registration

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs
⚠ This PR is the 16.6.x equivalent of #6091 and should not be merged without QB approval.
---
This bug has existed in the dependencies node for some time. It started surfacing for users in 16.5.4 when faulting dataflow blocks were reported (PR #6073). The bug is tracked in #6090.
The result of `Except` is lazily computed, so attempting to remove from the builder while enumerating that result causes a "Collection was modified" exception. The fix is to materialise the result prior to enumerating the data that backs it.
=> [16.6] Don't modify collection while enumerating

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs
Fixes #6090.
This bug has existed in the dependencies node for some time. It started surfacing for users in 16.5.4 when faulting dataflow blocks were reported (PR #6073).
The result of `Except` is lazily computed, so attempting to remove from the builder while enumerating that result causes a "Collection was modified" exception. The fix is to materialise the result prior to enumerating the data that backs it.
=> Don't modify collection while enumerating

tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Setup/SwrTests.cs
When adding a new .xaml file I always forget to update CommonFiles.swr to include it. Happily, we have a unit test that catches this problem. However, it doesn't currently tell you which file you need to update to correct the problem--and that's another thing I never remember.
This commit updates the test to be explicit about needing to update CommonFiles.swr.
=> Show file name in unit test output

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs
⚠ This PR is the 16.5.x equivalent of #6091 and should not be merged unless we have approval to ship this in servicing.
---
This bug has existed in the dependencies node for some time. It started surfacing for users in 16.5.4 when faulting dataflow blocks were reported (PR #6073). The bug is tracked in #6090.
The result of `Except` is lazily computed, so attempting to remove from the builder while enumerating that result causes a "Collection was modified" exception. The fix is to materialise the result prior to enumerating the data that backs it.
=> [16.5] Don't modify collection while enumerating

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs
This reverts commit a1620a645421e7659bdb957d63d3899770a414db.
This change did not meet the bar for 16.5.x servicing. This PR removes the change from the branch.
=> Revert "Don't modify collection while enumerating"

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
In Core the necessary ConfigurationManager dependency is always present for WinForms and WPF projects.
https://github.com/dotnet/winforms-designer/issues/356 is the WinForms designer issue for this.
I've manually tested this and everything seems fine, with or without a preexisting app.config.
=> Enable AppSettings project capability for WPF/WinForms

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IUnconfiguredProjectTasksServiceFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/DebugTests/StartupProjectRegistrarTests.cs
Make sure the project stays open until we've finished registering. Seeing a fault where we're being called during shutdown, and IVsStartupProjectsListService has gone away.
=> Make sure project stays open

build/import/HostAgnostic.props, build/import/Packages.targets
[AB#986703](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/986703) seems to have been fixed and the build no longer complains about this so it can be removed.
=> Remove unnecessary package ref

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VisualBasic/VisualBasicNamespaceImportsList.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VisualBasic/VisualBasicVSImports.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ContractNames.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/VisualBasicNamespaceImportsListFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Automation/VisualBasic/VisualBasicNamespaceImportsListTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Automation/VisualBasic/VsImportsTests.cs
Fixes https://github.com/dotnet/project-system/issues/3101
This updates VisualBasicNamespaceImports to use ProjectHostBridge to guarantee consistency of the collection when on the UI thread. It also moves DTE events to be triggered after the list of imports is actually updated which fixes a UI bug in the app designer, where clicking an import adds it to the project file but doesn't make the list item appear checked.
~This _doesn't_ fix the (possible?) bug that after calling `VSProject.Imports.Add` the new import is not visible in the collection upon that method returning, however since that is already a bug we have now, and the ideal solution for that involves a change to CPS's public API, and nobody answered me when I asked about it on Teams (😛), it's not worth blocking this change on.~ …
=> Update VisualBasicImports to use ProjectHostBridge and fire events

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/PackageReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/ResolvedPackageReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedPackageReference.xaml.zh-Hant.xlf
- Description that is copied from the one on AssemblyReferences
- Applied to the resolved package reference so that it gets persisted correctly
=> Clean up of the Aliases property

src/Microsoft.VisualStudio.Editors/PropPages/FixedWidthTextBox.vb, src/Microsoft.VisualStudio.Editors/PropPages/PackagePropPage.Designer.vb, src/Microsoft.VisualStudio.Editors/PropPages/PackagePropPage.resx, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.cs.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.de.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.es.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.fr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.it.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.ja.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.ko.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.pl.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.ru.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.tr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.zh-Hant.xlf
Fixes #4904. 
The warning message was long and couldn't fit in the row space. Changed the text to be consistent to the other warning message.
Here's what it would look like if PackageLicenseUrl and PackageIconUrl were found in the project file:
=> Change warning message to fit and be consistent.

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/NuGet/Relations/ProjectToDiagnosticRelation.cs
Fixes #2436.
Adds the relation required to show NuGet diagnostics as children of project reference nodes.
In future I'd like to distinguish between warnings and errors on the ancestors too.
=> Show diagnostics on project reference nodes

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/BrowseObjectDescriptionAttribute.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/BrowseObjectDisplayNameAttribute.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/FrameworkReferenceAssemblyAttachedCollectionSourceProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/FrameworkReferenceAssemblyItem.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/FrameworkReferenceIdentity.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/FrameworkReferenceItem.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/FrameworkToFrameworkAssemblyRelation.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/ITargetFrameworkContentCache.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/TargetFrameworkContentCache.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/IDependencyExtensions.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DependencyExtensionsTests.cs
Fixes #4444.
This allows a Target Framework reference to be expanded to show its constituent assemblies beneath.
Note you cannot yet search these nodes. #6139 is tracking that.
=> Show assemblies within target frameworks

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.CSharp.DesignTime.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.FSharp.DesignTime.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.VisualBasic.DesignTime.targets
This hides the Add Shared Project reference node, and Shared Projects category in Reference Manager for F# projects.
=> Only define SharedProjectReferences for C#/VB projects

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/IDependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.SnapshotUpdater.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/DependenciesTreeViewProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshotTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DependencyTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TestDependency.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TestDependencyExtensions.cs
Fixes #4474.
With changes on this feature branch we no longer use:
- `DependenciesSnapshot.ProjectPath`
- `TargetedDependenciesSnapshot.ProjectPath`
- `IDependency.FullPath`
This PR removes them all.
=> Remove paths

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/AggregateContainedByRelationCollection.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/AggregateContainsRelationCollection.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/AggregateRelationCollectionSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/IAggregateRelationCollection.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Unshipped.txt
This fixes:
1. the tree shows a lingering triangle after the last child is removed, and
2. the tree not adding a triangle/children when an item has its first child added post-initialization.
=> Signal changes to IAttachedCollectionSource.HasItems

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Commands/ReferenceManagerCommandHandler.cs
Fixes: https://github.com/dotnet/project-system/issues/6158.
Add Reference used to have two commands; AddReference and AddReferenceProjectOnly. The former is bound to the Project menu and is always available regardless of what node is selected, and the latter is bound to the right-click Project/Folder Add menu and is only available when just the project node is selected.
Rather than duplicating the same commands to achieve the same thing, we just hide the commands on the context menu when a non-project node is selected.
The PR to add & respect the flag is in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/246630.
=> Hide Add XXX Reference commands on folders

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs
This reverts commit f73f31699960f0488b8fba53d5217cf21436758b.
This fix was reverted on the `dev16.5.x` branch after it didn't make the QB bar. That reversion was then automatically forward integrated into `master`.
=> Revert "Revert "Don't modify collection while enumerating""

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs
This reverts commit f73f31699960f0488b8fba53d5217cf21436758b.
This fix was reverted on the 16.5.x branch after it didn't make the QB bar. That
reversion was then automatically forward integrated into master.
=> [16.6.x] Revert "Revert "Don't modify collection while enumerating""

src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs
This reverts commit f73f31699960f0488b8fba53d5217cf21436758b.
This fix was reverted on the 16.5.x branch after it didn't make the QB bar. That
reversion was then automatically forward integrated into master.
=> [16.7.x] Revert "Revert "Don't modify collection while enumerating""

build/import/HostAgnostic.props, build/import/Packages.targets
These packages are the reason we have to move a bunch of code from here to NuGet. They contain assemblies for which there are no binding redirects.
=> Remove NuGet package references

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreProgressTracker.PackageRestoreProgressTrackerInstance.cs
This makes sure the project gets unsubscribed from contributing to operation progress if it faults.
This is a targeted version of https://github.com/dotnet/project-system/pull/6172 because making all usages as required needs a little more thought.
=> Mark PackageRestore faults as "LimitedFunctionaity"

build/ci/unit-tests.yml
A job is automatically being injected into the build to validate that the builds produced signed binaries. It currently does not validate, but produces an output. Opt completely our CI builds completely out of this as they don't produce signed binaries.
=> Opt out of code sign valiation

src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Unshipped.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources/ManagedImageMonikers.cs
These images are the unadorned versions of icons we ship for top-level dependencies. Scenarios exist where transitive dependency providers will want to create tree items that use the same icon as top-level dependencies. Making this public enables this scenario. For example, the NuGet provider shows nested project references.
These names match those above (with "private" and "warning" suffixes).
=> Make some images public

build/import/Packages.targets, setup/ProjectSystemSetup/source.extension.vsixmanifest, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/Menus.vsct
This marks the 'Edit project file' command as client compliant.
Testing is **blocked**, not merging this to master yet.
=> Mark command as client compliant

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Commands/ReferenceManagerCommandHandler.cs
Fixed:  https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1121993/
We were overaggressive in hiding these, when we only want them hidden for Folders.
=> Fix Add XXX Reference items missing

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/BrowseObjectBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Unshipped.txt
This type was added to support extenders such as NuGet.
The type itself exists because the shell's `LocalizableProperties` did not define `GetComponentName` as `virtual`. PR https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/248337 changes that, and once that updates trickles through we'll be able to remove this type completely. For now it should be removed from our public API surface.
I will copy it into NuGet for now, and remove it from there too once the updated shell assembly is available.
=> Make BrowseObjectBase internal

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/IVsHierarchyItemExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/PackageDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/ProjectDependencyModel.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/PackageDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/ProjectDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/IVsHierarchyItemExtensionsTests.cs
This data is now obtained from an item's browse object.
=> Remove id and version data from project tree flags

src/Microsoft.VisualStudio.AppDesigner/Resources/Designer.Designer.vb
Fixes [AB#1126853](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1126853) introduced in #6180 
Bug #1058 is tracking work to stop this happening again in future.
Note that #3741 discusses an alternative workaround to #1058 in which we would rename the file to include the prefix, so that it is not removed again in future.
=> Fix resx resource generation

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Frameworks/TargetFramework.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshotTests.cs
Fixes #6204
Fixes [AB#1126588](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1126588)
We are seeing some customer NFEs around this check. The validation is theoretically correct, but the consequences of continuing in such a scenario are minor-to-non-existant. Therefore I'm leaving it as an assert to assist during development of this code.
This code would likely disappear as part of #6183.
=> Don't throw if unknown active framework is "Unsupported"

.editorconfig, src/Common/BannedSymbols.txt
Ban the use of `System.Diagnostics.Debugger.Launch()`. We've seen other teams accidentally commit code that used this method, leading to a completely unexpected dialog appearing in the middle of a scenario.
It's fine to use this in local development; in that case you can suppress the error with  #pragmas. Just please remember to remove them. 😊
=> Ban Debugger.Launch

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VersionCompatibility/DotNetCoreProjectCompatibilityDetector.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.State.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
fixes #6181 
**Problem**:
Fast up-to-date detects a project is out of date with message:
_The set of AdditionalDependentFileTimes was changed more recently...._
Update() erroneously  change the timestamp of `lastAdditionalDependentFileTimesChangedAtUtc `when the project is loaded.
**What this change does:**
When the project is first loaded we have zero additional dependent files in `AdditionalDependentFileTimes`.
In this change we do not change the timestamp when lastExistingAdditionalDependentFiles.Count is zero.
The refactor extract method was applied to create `getLastTimeAdditionalDependentFilesAddedOrRemoved`()
=> Ignore the first output from design-time build

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/PackageDependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/ProjectDependencyModel.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/PackageDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/ProjectDependencyModelTests.cs
The intention was to have consumers source this data from the browse object, but that's non-trivial from an IProjectTree in a sync context.
I will revisit this in preview 3. Right now this will unblock NuGet from merging, hopefully in time for P2.
=> Reinstate package/project ID in flags

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/AbstractBuildEventValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/OutputTypeValueProviderBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/TargetFrameworkMonikerValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/TargetFrameworkMonikersValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationManifestValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/ActiveLaunchProfileNameValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/ActiveLaunchProfileValueProviderBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ExportInterceptingPropertyValueProviderAttribute.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/IInterceptingPropertyValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/IInterceptingPropertyValueProviderMetadata.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/InterceptedProjectProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/InterceptingPropertyValueProviderBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/PackagePropertyPage/BaseVersionValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/SigningPropertyPage/AssemblyOriginatorKeyFileValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/TargetFrameworkValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Shipped.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Unshipped.txt, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IInterceptingPropertyValueProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IInterceptingPropertyValueProviderMetadataFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/AssemblyInfoPropertiesProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptedProjectProperties/ActiveLaunchProfileValueProvidersTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationManifestValueProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/OutputTypeExValueProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/OutputTypeValueProviderTests.cs
Related to #6210.
The `IInterceptingPropertyValueProvider` interface allows an implementor to easily "intercept" get or set operations for a particular property and modify or redirect the value as it sees fit. For example, reading an writing the "ApplicationManifest" property through a property page actually involves two MSBuild properties: ApplicationManifest, and NoWin32Manifest. The `ApplicationManifestValueProvider` handles reading and writing the two in concert to produce the final value exposed through the property page. Similarly the `ExecutablePathValueProvider` redirects reads and writes of the path to the .exe to debug to the launchSettings.json file, instead of reading and writing that value from the project file.
The name of the intercepted property is declared via the …
=> Allow IInterceptingPropertyValueProvider to handle multiple properties

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/PackageReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/PackageReference.xaml.zh-Hant.xlf
This fixes a bug in the NuGet provisioning of transitive dependencies when the item it is being asked to attach to is an unresolved package. Without this change, the a blank name would be used and no library found in the assets file, so all children would be removed and never populated. This change gives parity between both the unresolved and resolved package reference items, so children appear correctly regardless of the resolved state at the time children are attached.
=> Add PackageReference.Name property

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/AnalyzerRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/AssemblyRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/ComRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/FrameworkRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/ProjectRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/SdkRuleHandler.cs
These strings identify the type of a dependency (eg. Package, Assembly, ...).
Currently they're included in composite key strings for all top-level dependencies of a project. They are not displayed anywhere visible, and are not persisted beyond the lifetime of the host process (eg. devenv).
Making them shorter can save a little memory.
=> Shorten dependency provider type strings

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProjectTypeRegistration.cs
Fixes #6217.
The build will fail for a day until the CPS packaging changes get ingested.
=> Opt-in for VS Codespaces

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesProjectTreeProvider.cs
The base implementation does the same thing.
=> Remove redundant CanCopy override in DependenciesProjectTreeProvider

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Commands/ReferenceManagerCommandHandler.cs
#6228 updated the version of `Microsoft.VisualStudio.Shell.15.0` which brings in these new command IDs as constants. Replace our copies of those values.
=> Use updated VSConstants values

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Commands/DependenciesContextMenuProvider.cs
`ContainsAny` is available now, but it requires allocating the composite `ProjectTreeFlags` somewhere in order to use it, either as a temporary or on the stack. The change is not justifiable.
=> Remove TODO

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Commands/ReferenceManagerCommandHandler.cs
We now consume CPS packages that include `CommandStatus.InvisibleOnContextMenu`.
=> Use CommandStatus member workaround

tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Resources/ResourceTests.cs
Resx code generation does not respect `<LogicalName>` metadata on `<EmbeddedResource />`. This can result in an incorrect base name being used in generated code, and is being tracked by #1058.
To prevent this from happening unwittingly (eg. #6180) this commit adds a test that ensures the expected name is used. This will catch cases when code gen produces invalid code before merging/insertion.
=> Add test to ensure correct generated resource base name

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
Disable AdditionalDependentFileTimes support until we've figured it out
https://github.com/dotnet/project-system/issues/6227
=> Disable support for Additional Dependent Files

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/FrameworkReferenceAssemblyItem.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/RelatableItemBase.DefaultContextMenuController.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/RelatableItemBase.cs
Relates to #5935.
https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/250942 adds new
context menus for various kinds of transitive dependencies.
This commit opts into the use of two of them:
1. `IDM_VS_CTXT_DEPENDENCY_TRANSITIVE_ITEM` for generic items
2. `IDM_VS_CTXT_TRANSITIVE_ASSEMBLY_REFERENCE` for framework reference assemblies
This unblocks further development of Fakes support for assemblies.
=> Use new context menus for transitive dependency tree items

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/ActiveLaunchProfileCommonValueProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptedProjectProperties/ActiveLaunchProfileValueProvidersTests.cs
Add support for getting and setting the `ILaunchProfile.LaunchBrowser` and `ILaunchProfile.LaunchUrl` properties. We don't use these on our own property pages, but ASP.NET does.
=> Support Launch Browser and Launch URL properties

src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPage.resx, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ApplicationPropPage.cs.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ApplicationPropPage.de.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ApplicationPropPage.es.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ApplicationPropPage.fr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ApplicationPropPage.it.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ApplicationPropPage.ja.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ApplicationPropPage.ko.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ApplicationPropPage.pl.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ApplicationPropPage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ApplicationPropPage.ru.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ApplicationPropPage.tr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ApplicationPropPage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ApplicationPropPage.zh-Hant.xlf
In the Application page, this item's name couldn't be found by the Accessibility Insights tool.
After:
[Link ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1132995)to the original AzDO ticket.
=> Make 'Resouce file' textbox accessible.

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
Enabling only the part that checks when Additional Dependent files are added or removed.
This doesn't make a conflict with the issue #6227 which is still pending.
=> Enable Additional Dependent to detect files added or removed

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/ResolvedPackageReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/ResolvedProjectReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/DependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/ProjectItemMetadata.cs
Fixes #6275.
Requires dotnet/sdk#12069.
Introduces a `DiagnosticLevel` metadata item for resolved references. Use it to show a warning icon on top-level dependencies which contain warning or error diagnostics.
In future this logic will likely change to support showing different icons based on the severity of the diagnostic.
=> Allow resolved references to have diagnostics

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandler.cs
Fixes: https://github.com/dotnet/project-system/issues/6121
We can be pushed the same value of ConfiguredProjectVersion when other input data source versions change. Don't fail in this case. We should be tracking those versions, but I'll leave that for https://github.com/dotnet/project-system/issues/3425.
=> Avoid failing when pushed the same version

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ExecutableDebugPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ProjectDebugPropertyPage.xaml
Fixes #6225.
CPS assumes each "debugger" Rule (with `PageTemplate="debugger"`) should be shown in the launch target drop down in the toolbar, and expects that each provides the GUID and ID of the related VS debugger command in their metadata. Rules which do not are associated with default GUIDs and IDs.
Our debugger rules don't provide the GUID and IDs because they provide a debug target (e.g., Executable, Project, IIS, IISExpress, etc.) instead. For the purposes of the debugger they aren't directly "startable" on their own--they need to be associated with a launch profile that provides all the relevant settings. So we don't want them to appear on this menu.
I can't simply update CPS to filter out "debugger" pages that lack the GUID and ID, because in theory other pages are usable by the …
=> Update page templates

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/LaunchTargetPropertyPageValueProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/LaunchTargetPropertyPageValueProviderTests.cs
PR #6297 updated our debugger property pages to use the "commandNameBasedDebugger" page template instead of the "debugger" template (see the PR for more details). However, I forgot to update the `LaunchTargetPropertyPageValueProvider` which is responsible for determining the set of valid launch targets to show in the property page UI. It does this by looking for "debugger" pages with "CommandName" metadata. Once I changed the pages to use a different template, the value provider no longer found them, and they no longer appeared as options in the UI.
The fix here is to look for pages using the "CommandNameBasedDebugger" template.
=> Look for the correct page template

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/SolutionExplorer/ProjectNodeCommandHandler.cs
This is the first step to ensure that when we call GetProxyAsync for CodeSpaces, we handle the case we get a null value. I'll create an issue to track how we want to handle when openDocumentService returns null.
=> Only call OpenDocumentAsync when openDocumentService is not null.

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Frameworks/ITargetFramework.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Frameworks/TargetFramework.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesTreeViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/TargetDependencyViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs
This change was motivated by two factors:
1. For .NET 5, the target node showed ".NETCoreApp 5.0", but ".NETCoreApp" is not a concept in .NET 5.
2. We would one day like to support arbitrary user-defined names for TargetFrameworks (NuGet/Home#5154)
=> Use short name for target nodes in dependencies tree

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Frameworks/ITargetFramework.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Frameworks/TargetFramework.cs
- Remove `IEquatable<string>`
- Use statement bodies
- Annotate operator parameters correctly
A subsequent PR will remove `ITargetFramework` entirely as the abstraction adds no value.
=> Tidying for target frameworks

build/ci/official.yml, build/variables/_vsts.ps1
Previously we used to publish our symbols to \\cpvsbuild\drops\Roslyn but the share got full after 3TB so moving the more modern way of uploading symbols through the Artifacts container. Now in each build under artifacts you should be able to see a folder titled "symbols"
Fixes #5265 
Partially completes some of #5905
=> Use Artifacts container instead of \\cpvsbuild\drops\Roslyn share on build pipeline

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/DependencyId.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/IDependencyModelExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/AddDependencyContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/DeduplicateCaptionsSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/RemoveDependencyContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/SdkAndPackagesDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/UnresolvedDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/IDependencyExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DeduplicateCaptionsSnapshotFilterTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshotFilterTestsBase.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/ImplicitDependenciesSnapshotFilterTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/SdkAndPackagesDependenciesSnapshotFilterTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TestDependency.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/UnresolvedDependenciesSnapshotFilterTests.cs
#6282 changed how dependencies were identified to avoid using a composite string. However, that string was forced to lower-case, which meant that comparisons on dependencies' IDs (item specs) was case insensitive.
Since that change the following project would result in two package references being shown in the tree:
```xml
<Project Sdk="Microsoft.NET.Sdk">
<TargetFramework>net5</TargetFramework>
<ItemGroup>
<PackageReference Include="Newtonsoft.JSON" Version="11.0.10" />
</ItemGroup>
</Project>
```
This PR introduces a new `DependencyId` struct that provides proper hashing and equality.
=> Restore case insensitive dependency ID comparison

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesTreeViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/DependenciesViewModelFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/DependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/IDependenciesViewModelFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/IDependencyModelExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/TargetDependencyViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/IDependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IMockDependenciesViewModelFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/DependenciesViewModelFactoryTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshotTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TestDependency.cs
The concept of 'diagnostic level' was introduced in #6288. Previously, warnings were only shown on dependencies when they were marked as unresolved. Now we can have multiple levels.
This commit tracks the maximum visible diagnostic level in a snapshot at the snapshot level (both targeted and cross-target), and passes that value to code that's responsible for placing an icon in the tree. This value replaces the "has visible unresolved dependency", and opens up the possibility of showing different severities in tree icons in future.
This fixes an issue where a child could have a warning icon visible, but the parent would not (seen in https://github.com/dotnet/project-system/issues/6275#issuecomment-653365600).
=> Track dependency diagnostic level at snapshot level

build/import/HostAgnostic.props
After upgrading to 16.6.3 and with a `global.json` pinning to 3.1.4xx (which requires MSBuild 16.7), opening this repo caused all projects to fail to load.
The problem is that when `IsTestProject` is undefined, we see the error:
> Specified condition "$(IsTestProject)" evaluates to "" instead of a boolean
=> Fix potentially invalid expression in props file

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/SdkAndPackagesDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/IDependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/IDependencyExtensions.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/SdkAndPackagesDependenciesSnapshotFilterTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TestDependency.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TestDependencyExtensions.cs
In `netstandard2.0`, the framework is shown as an SDK reference. This is delivered via a package which is not shown in the tree. The project system has a filter which applies the resolved state of the package to the SDK item.
#6330 made a change where the diagnostic level determined whether a reference's icon showed a warning or not, rather than the resolved state. That PR did not update this SDK/package filter to correctly clear/apply the diagnostic level on the SDK node. This meant that a resolved SDK would appear with a warning icon.
=> Fix lingering warning icon on SDK references

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreProgressTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IImplicitlyActiveService.cs
Fixes part of https://github.com/dotnet/project-system/issues/6327.
We were activating the PackageRestoreProgressTracker on configurations as they were loaded, instead of just active ones.
Export/implement IImplicitlyActiveService which handles this for us automatically.
=> Avoid starting restore dataflow on inactive configurations

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/ActiveLaunchProfileCommonValueProvider.cs
Actually intercept the "LaunchBrowser" and "LaunchUrl" properties and redirect them to the `ILaunchSettingsProvider`. The code itself properly handles these properties (and we have unit tests verifying the behavior), but since we weren't exporting their names the code in question was never being called.
=> Actually intercept launch properties

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/DependencyId.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/IDependencyModelExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/AddDependencyContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/DeduplicateCaptionsSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/RemoveDependencyContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/SdkAndPackagesDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/UnresolvedDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/IDependencyExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DeduplicateCaptionsSnapshotFilterTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshotFilterTestsBase.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/ImplicitDependenciesSnapshotFilterTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/SdkAndPackagesDependenciesSnapshotFilterTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TestDependency.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/UnresolvedDependenciesSnapshotFilterTests.cs
(This is a cherry-pick of #6323 to the 16.7.x branch to get the fix in, but needs QB approval.)
---
#6282 changed how dependencies were identified to avoid using a composite string. However, that string was forced to lower-case, which meant that comparisons on dependencies' IDs (item specs) was case insensitive.
Since that change the following project would result in two package references being shown in the tree:
```xml
<Project Sdk="Microsoft.NET.Sdk">
<TargetFramework>net5</TargetFramework>
<ItemGroup>
<PackageReference Include="Newtonsoft.JSON" Version="11.0.10" />
</ItemGroup>
</Project>
```
This PR introduces a new `DependencyId` struct that provides proper hashing and equality.
=> [16.7.x] Restore case insensitive dependency ID comparison

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesTreeViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/DependenciesViewModelFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/DependencyModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/IDependenciesViewModelFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/IDependencyModelExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/TargetDependencyViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/SdkAndPackagesDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/IDependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/IDependencyExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IMockDependenciesViewModelFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/DependenciesViewModelFactoryTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshotTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/SdkAndPackagesDependenciesSnapshotFilterTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TestDependency.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TestDependencyExtensions.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/DependenciesSnapshotFactory.cs
This is a cherry-pick of #6330 and #6338 to the `dev16.7.x` branch, and needs QB approval.
Builds upon #6325, which also targets the `dev16.7.x` branch.
---
The concept of 'diagnostic level' was introduced in #6288. Previously, warnings were only shown on dependencies when they were marked as unresolved. Now we can have multiple levels.
This commit tracks the maximum visible diagnostic level in a snapshot at the snapshot level (both targeted and cross-target), and passes that value to code that's responsible for placing an icon in the tree. This value replaces the "has visible unresolved dependency", and opens up the possibility of showing different severities in tree icons in future.
This fixes an issue where a child could have a warning icon visible, but the parent would not (seen in …
=> [16.7] Track dependency diagnostic level at snapshot level

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Note: That this and Page item types when chosen in a File -> New -> Console App cause the item to be hidden in the tree, which is unrelated to below. I'm still investigating this.
=> Delete reference to unused/unshipped browse object

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
The `LaunchSettingsProvider` type aggregates two separate sources of information:
1. Launch profile and global debugger settings from the launchSettings.json file.
2. The name of the _active_ profile from the `ProjectDebugger` rule (which ultimately reads it from the .user file).
It also allows updating all of this information and writes the changes back to the appropriate data source. As part of an update it almost always checks that the active profile specified in the current `ILaunchSettings` snapshot matches the value in the `ProjectDebugger` rule, and updates the latter if it does not. It turns out this is unnecessary and can be removed.
First, consider the only three public methods on `LaunchSettingsProvider` that could conceivably change the active profile:
1. …
=> Simplify LaunchSettingsProvider

src/Common/BannedSymbols.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VisualBasic/VisualBasicVSImports.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VsProject.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/PasteOrdering.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/BuildMacroInfo.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AbstractActiveConfiguredValue.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredValue.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredValues.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IActiveConfiguredValue.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IActiveConfiguredValues.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ActiveWorkspaceProjectContextHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PhysicalProjectTreeStorage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UnconfiguredProjectCommonServices.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IActiveConfiguredProjectFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IActiveConfiguredValuesFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PhysicalProjectTreeStorageTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UnconfiguredProjectCommonServicesTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/VisualBasicNamespaceImportsListFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Automation/VisualBasic/VsImportsTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Automation/VsLangProjectPropertiesTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/DebugTests/StartupProjectRegistrarTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PropertyPages/BuildMacroInfoTests.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1042733
ActiveConfiguredProject.Value throws a MEF exception when accessing a service that is not applicable to the capabilities of the ConfiguredProject. Rather than push MEF exceptions onto all callers of this, this replaces ActiveConfiguredProject usage with two new APIs that work similar to IVsService<T>, where it returns null when the configuration does not provide the service. The majority of usages of this API ask for a service that always exists so do not need this API.
This also simplifies another pattern; pulling a collection of values from the active ConfiguredProject, previously this needed an inner class to wrap the values.
Usage:
``` C#
public FooService(IActiveConfiguredValue<IService> service);
... …
```
=> Replace ActiveConfiguredProject usage with new APIs

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/IStartupProjectProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Unshipped.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectThreadingServiceFactory.ProjectThreadingService.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDebugLaunchProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectLaunchTargetsProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/DebugTests/StartupProjectRegistrarTests.cs
This pr fixes #1308 
The Startup project was showing NetCore Libraries which overwhelm users when using VS with large projects. This bug was not about whether Libraries should be in Startup or not, but to decide which projects are non-debuggable and only display debuggables.
- Added the project capability `DisableBuiltInDebuggerServices` to disable CPS debuggers services for managed projects.
- Implemented the missing functionality in `CanLaunch()` to decide which projects should appear in the Startup list.
The logic to decide if a project is non-debuggable is in `LaunchProfilesDebugLaunchProvider`
-  Fixed unit tests
=> Fix Startup Project to show only debuggable projects.

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.Designer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.zh-Hant.xlf
As noted in #5797, Debug page was missing the key accelerators, or mnemonics.
Visual Studio has already defined some menu mnemonics:
To avoid overlaps, I eliminated the letters _B, D, E, F, H, N, P, S, T, V, W, X_ from the set. I was able to assign a key accelerator to the majority of the properties, as shown below.
**Before:**
**After:**
You'll notice that buttons have no key accelerator assigned: I was left with 4 unique letters _(J, K, M, O)_ for the 6 different buttons. Any suggestion?
=> Add mnemonics to debug page.

.github/workflows/teams-notifications.yml
We used this if statement in order to avoid getting updates in our Teams only when PRs were created in the main repo (we didn't want them coming from forks).
Since we moved to using a different URI and it's now stored as a secret, secrets don't get copied to forks so we won't see this problem anymore.
=> Move URI to secret and remove if statement

Launch.cmd, docs/repo/debugging/logging.md, setup/ProjectSystemSetup/Properties/launchSettings.json, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectSystemOptions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectSystemOptions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ServiceCapability.cs
This replaces PROJECTSYSTEM_PROJECTOUTPUTPANEENABLED in lieu of checking for the diagnostic runtime which is turned on by CPS_DiagnosticRuntime environment variable. This is turned on by default on F5 for CPS and this repository.
=> Use CPS_DiagnosticRuntime instead of PROJECTSYSTEM_PROJECTOUTPUTPANEENABLED

build/import/Workarounds.targets
Works around: https://github.com/NuGet/Home/issues/9431, which resulted in:
```
C:\Users\vsagent\.nuget\packages\roslyntools.repotoolset\1.0.0-beta-62705-01\tools\SourceLink.targets(31,5): error : SourceRoot.SourceLinkUrl is empty: 'C:\Users\vsagent\.nuget\packages\' [F:\workspace\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client\Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client.csproj]
```
I've fired off an email to figure out if we're unique in this due to our custom usage of SourceLink.
=> Workaround SourceRoot without urls

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VisualBasic/VisualBasicNamespaceImportsList.cs
We don't need to auto-initialize this service, just do this the first time someone calls us. This initialize was causing thread-pool exchaustion because we were synchronously initializing an async method that required the UI thread.
Fixes: Part of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1146682.
=> Do not auto-initialize VisualBasicNamespaceImportsList

.github/workflows/teams-notifications.yml
Currently our workflow is only posting new issues in our teams channel. Since we moved to a secret we believe this is giving us problems with PRs.
This PR is a placeholder for now and it's also helping us test the changes (hence the closing and reopening of it)
Current status: Reached out to Github support for help
Fixes #6367
=> Posting to Teams workflow should also update PRs

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/FrameworkReferenceAssemblyAttachedCollectionSourceProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/FrameworkReferenceIdentity.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1151765
Applying this fix to `dev16.7.x`. It must merge forward to `master` (automation should do this).
---
We have received Watson data showing the value of `TargetingPackPath` or `OriginalItemSpec` can be empty, based on stack traces where these value are validated during the construction of `FrameworkReferenceIdentity`. This change prevents items from being attached in such a case.
=> [16.7] Protect against exception due to empty string

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/DependenciesTreeSearchContext.cs
[AB#1155051](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1155051)
Applying this fix to `dev16.7.x`. It must merge forward to `master` (automation should do this).
---
`Interlocked.Increment` does not have an overload that accepts `uint`, therefore `_submittedResultCount` was tracked as a (signed) `int`. The maximum number of results is specified as an `uint`, and the original code made a `checked` conversion from `uint` to `int`. During testing this worked fine, however there are scenarios where `uint.MaxValue` is provided here, which triggers an `OverflowException`. That exception would fault the search operation and surfaced during previews via NFE reporting.
The fix is to widen the type of `_submittedResultCount` to `long`, the domain of which …
=> [16.7] Fix integer overflow exception

build/import/Packages.targets, build/import/VisualStudio.props, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProvider.cs
[AB#1155427](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1155427)
Porting changes from https://github.com/dotnet/project-system/pull/6358 to target 16.7.x.
This updates the debug launch to use the LaunchDebugTargetsAsync.
This provides a better guarantee that the debug targets have been launched/attached to
when the completion routine is invoked and thus OnAfterLaunchAsync is only called once
debugging has started.
@davkean @andrewcrawley
=> [16.7] Async debug launch

build/import/HostAgnostic.props, build/import/Packages.targets
This references the root packages and stops reference individual packages. Also works around the bad reference to BannedApiAnalyzers which has since been fixed.
=> Unify analyzer packages

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/AggregateRelationCollectionSource.cs
Works around a limitation of Solution Explorer's tree view where the `IPrioritizedComparable` pattern is not used uniformly, and children can appear out of order.
---
Given:
```c#
/// <summary>
/// Specifies the order of attached items in the dependencies tree.
/// </summary>
/// <remarks>
/// Used in conjunction with <see cref="IPrioritizedComparable"/>.
/// </remarks>
internal static class AttachedItemPriority
{
// Not all of these can be siblings.
public const int Diagnostic               = 100;
public const int Package                  = 200;
public const int Project                  = 300;
public const int CompileTimeAssemblyGroup = 400;
public const int FrameworkAssemblyGroup   = 500;
public const int ContentFilesGroup        = 600;
}
```
Diagnostics should appear before any other …
=> Fix priority ordering of attached tree children

build/import/Workarounds.targets
(ported to 16.7.x)
Works around: https://github.com/NuGet/Home/issues/9431, which resulted in:
```
C:\Users\vsagent\.nuget\packages\roslyntools.repotoolset\1.0.0-beta-62705-01\tools\SourceLink.targets(31,5): error : SourceRoot.SourceLinkUrl is empty: 'C:\Users\vsagent\.nuget\packages\' [F:\workspace\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client\Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client.csproj]
```
=> [16.7.x] Workaround SourceRoot without urls

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/DebugProfileEnumValuesGenerator.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ErrorProfileDebugTargetsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/IVsContainedLanguageComponentsFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Shipped.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed/Collections/DictionaryEqualityComparer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/DebugTokenReplacer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchProfile.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/IWritableLaunchProfile.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfile.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfileData.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/WritableLaunchProfile.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/AssemblyAttributeProperties/AbstractProjectFileOrAssemblyInfoPropertiesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/DelegatedProjectPropertiesBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationManifestValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/InterceptedProjectProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Shipped.txt, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/TestProjectTree.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/DebugTokenReplacerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/AssemblyInfoPropertiesProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptedProjectProperties/ActiveLaunchProfileValueProvidersTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/LaunchTargetPropertyPageValueProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/DependenciesTreeViewProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectLaunchTargetsProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactoryTests.cs
Reduces the number of un-annotated files from 14 to 5.
Includes annotations for `LaunchSettingsProvider`, which would have prevented bug [AB#1042733](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1042733) (fixed in #6389).
=> Annotate code

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerEditorFactory.vb, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/Packaging/ManagedProjectSystemClientPackage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/ProjectProperties/ProjectPropertiesEditorFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/Utilities/WaitCursor.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/VSPackage.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.zh-Hant.xlf
Creates an editor factory that shows a placeholder UI when created.
This editor factory uses the well-known GUID for the project properties editor. The 'legacy' editor is given a new GUID. The intention is to introduce a feature flag or other mechanism to conditionally delegate to the legacy implementation.
=> Register project properties editor with placeholder UI

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProvider.cs
Some scenarios do the launch entirely through the Before and After launch hooks, but have no actual debug targets to launch.
This updates the async launch implementation to manually invoke the after launch completion handler if there were no actual debug targets to launch.
=> Fire launch completion when there are no debug targets

.editorconfig
In previous versions of VS certain analyzers (like new API or missing file headers) would error but not block the build because only the IDE produced the error. Now editorconfig is plumbed through the build to the compiler, it now stops the compiler from producing outputs and hence blocks F5. This can be annoying.
This downgrades the majority of the analyzers to warnings. They continue to get promoted to errors during CI/official builds and hence will block merge until they are fixed.
=> Downgrade analyzers during dev builds to warnings

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/AggregateRelationCollectionSource.cs
Fixes #6432.
Reverts #6385 (16.8) in which we attempted to work around a bug in Solution Explorer where `IPrioritizedComparable` does not behave consistently across siblings, meaning that attached tree items do not appear in the correct order.
Unfortunately that workaround introduced an exception here: http://index/?rightProject=Microsoft.VisualStudio.Shell.TreeNavigation.HierarchyProvider&file=Items%5CHierarchyItem.cs&line=2489
The Solution Explorer bug is tracked in [AB#1158136](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1158136)
=> Fix crash in VS while searching in Solution Explorer

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Usage of this rule was removed in https://github.com/dotnet/project-system/pull/6126.
This would make a good unit test catch, however, I've removed references to rules in the design-time targets in another branch (moving them to exports) and written a different set tests to catch this sort of thing.
=> Remove reference to non-existent rule

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs
Fixes #6420.
Root graft project tree providers should only return a value for `GetPath` for tree nodes that they own. Previously the assumption was that this method was only passed its own descendants, but this is not the case.
This fixes a problem where, when the Dependencies tree was not enabled, the "Copy Full Path" command on import tree items would result in the pseudo-path (">123") being copied rather than the actual file path.
---
In a nanoFramework project:
Note item appears expanded (by arrow direction) but no child is visible.
"Copy Full Path" produces: `D:\repos\NFApp1\NFApp1\>34`, where `>34` is the item ID
"Copy Full Path" produces: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview-master\MSBuild\nanoFramework\v1.0\NFProjectSystem.Default.props`
=> Fix root graft tree provider GetPath logic

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
DotNetCliToolReference do not show up in the project item, and hence does not need a browse object.
These will be caught by the new unit test rules that require BrowseObjects to be localized, which this rule is not.
=> Remove DotNetCliToolReference from BrowseObject context

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsBuildManagerBridge.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsChangeTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsDelta.cs
Fixes AzDO 1085702
DesignTimeOutputMonikers calls initializes DesignTimeInputsBuildManagerBridge
that waits (hangs) for AppliedValue to be generated/created.
AppliedValue was not generated when bad input data block arrives and
in here we are producing an empty value that will get assigned
to AppliedValue.
=> Fix hang in GetDesignTimeMoniker

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
These data sources are unneeded:
1) We don't use this rule for writing, so we don't need HasConfigurationCondition
2) We use this via snapshot model (and not live ProjectProperties) so don't need to set ProjectFileWithInterceptionViaSnapshot for the TargetFrameworkMoniker, as the data is already snapshot.
=> Remove unneeded data sources from properties

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/IDebugProfileLaunchTargetsProvider3.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/IStartupProjectProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Unshipped.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDebugLaunchProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectLaunchTargetsProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/DebugTests/StartupProjectRegistrarTests.cs
This pr fixes #1308
The Startup project was showing NetCore Libraries which overwhelm users when using VS with large projects. This bug was not about whether Libraries should be in Startup or not, but to decide which projects are non-debuggable and only display debuggables.
Added the project capability `DisableBuiltInDebuggerServices `to disable CPS debuggers services for managed projects.
Implemented the missing functionality in `CanLaunch`() to decide which projects should appear in the Startup list.
The logic to decide if a project is non-debuggable is in `LaunchProfilesDebugLaunchProvider`
Fixed unit tests
By default, classes that do not implement `IDebugProfileLaunchTargetsProvider3 `will appear in the Startup drop down list.
=> Fix startup show only debuggable projects

src/Directory.Build.props
VS installs 5.0 SDK by default, which includes https://github.com/dotnet/sdk/pull/10998/files . This has broken WPF builds that did not import WinFx targets.
=> Force import WinFX targets

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VisualBasic/VisualBasicNamespaceImportsList.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsBuildManagerBridge.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsBuildManagerBridgeTests.cs
We were firing events during initialization, which resulted in listeners to call back into us and deadlock on Initialize because we're in the middle of initializing.
Fix both ImportsList and DesignTimeInputs to both avoid firing events the first time they set a value. This also makes sense; you don't fire "changed" events if the original state never changed.
=> Avoid deadlocks when firing events during initialization

Directory.Build.props, build/import/OverrideRepoToolsetVersions.props, build/import/Versions.props
This avoids overflowing the build number for the next 10 years.
=> Avoid overflowing build number

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Waiting/VisualStudioWaitIndicator.cs
I believe this was introduced when updating the analyzers in #6374 
This also removes the suppression for warning CS8653 as it appears to no longer be necessary
=> Suppress build warnings

build/import/Workarounds.targets
This fixes the reason these warnings were seen at command-line build time: https://github.com/dotnet/project-system/pull/6464.
=> Workaround WPF temp project bug

build/import/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ErrorProfileDebugTargetsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/OutputTypeValueProviderBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TargetFrameworkProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsChangeTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsCompiler.CompilationQueue.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Collections/DictionaryEqualityComparer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ImmutableCollectionLinqExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/PooledObjects/PooledDictionary.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ActiveDebugFrameworkServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchSettings.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfileExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettings.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/AssemblyAttributeProperties/AssemblyInfoProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/ActiveLaunchProfileExtensionValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/InterceptedProjectProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/DisposableBag.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Shipped.txt, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchProfileDataTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchProfileTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs
Includes https://github.com/dotnet/project-system/pull/6471, just review https://github.com/dotnet/project-system/commit/6c43cb59ffe24ac62f1cb5df77b4fc8beecd62c3.
Fixes: #6470
This avoids putting a large string on the LOH when we're dealing with large command-lines.
=> Call new SetOptions API

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/AppDesignerFolderProjectTreePropertiesProvider.cs
This dictionary is shared between all properties providers and this avoids a clash.
=> Prepend rule schema name to property value

build/import/HostAgnostic.props, build/import/Packages.targets, build/import/VisualStudio.props, src/Microsoft.VisualStudio.Editors/DesignerFramework/DesignerTypeDiscoveryService.vb, src/Microsoft.VisualStudio.Editors/GlobalSuppressions.vb, src/Microsoft.VisualStudio.Editors/MyExtensibility/MyExtensionTemplate.vb, src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPageBase.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/ProjectUtils.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsDesigner.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/TypePickerDialog.vb, src/Microsoft.VisualStudio.Editors/package/VBPackage.vb, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/StartupObjectsEnumProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/BaseProjectConfigurationDimensionProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/IProjectConfigurationDimensionsProvider5.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationManifestValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/SigningPropertyPage/AssemblyOriginatorKeyFileValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Reload/ProjectReloadInterceptor.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Compile.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Content.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/EditorConfigFiles.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/EmbeddedResource.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/None.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/PackageContentProjectTreePropertiesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.ImplicitProjectCheck.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/StringExtensions.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsAsyncFileChangeExMock.cs
This updates all our package versions to latest available in master, and reacts to associated fallout:
- Needed to move interop embed down to HostAgnostic layer as there are dependencies on interop assemblies at that level.
- Needed to add a reference to Microsoft.IO.Redist which CPS runtime now has a dependency.
- Need to fix nullable warnings due to update references
- Need to fix VB's reference to namespace "IO" as it conflicts with "Microsoft.IO"
=> Upgrade to the latest version of VS SDK packages

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Compile.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Content.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/EditorConfigFiles.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/EmbeddedResource.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/None.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/PackageContentProjectTreePropertiesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.ImplicitProjectCheck.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/StringExtensions.cs
Fixes: https://github.com/dotnet/project-system/issues/2141
This marks package content items as user read-only, which causes them to be opened read-only in the editor.
This depends on https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/266425.
=> Mark package content items as "user read-only"

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreDataSource.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectChangeHintSubmissionServiceFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PackageRestore/PackageRestoreDataSourceTests.cs
Fixes: https://github.com/dotnet/project-system/issues/6479
CPS can miss file changed events when there are lots of file changes (such as a branch switch via the command-line). Fire a hint specifically to tell it to that the file "might" changed, CPS itself will determine if it has.
=> Fire hint to CPS to reevaluate on assets file changed

Directory.Build.props, build/import/Packages.targets
There is no later version than 16.0 for Visual Basic.
=> Opt into C# 9.0 and VB 16.0

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/ActiveLaunchProfileCommonValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/ActiveLaunchProfileEnvironmentVariableValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/ActiveLaunchProfileExtensionValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/LaunchSettingsValueProviderBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Shipped.txt, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptedProjectProperties/ActiveLaunchProfileValueProvidersTests.cs
Fixes #6430.
`LaunchSettingsValueProviderBase.OnSetPropertyValueAsync` will often be called in a context where certain project locks have already been acquired. This was problematic because it often called `ILaunchSettingsProvider.UpdateAndSaveSettingsAsync` which tried (and failed) to acquire the locks again. To work around this `OnSetPropertyValueAsync` used `RunAndForget` to do its work in a context that held no locks; it would then simply block until it could acquire the needed locks.
This solved one problem but created another: when setting multiple properties `RunAndForget` would cause them to run in parallel rather than sequentially. This could lead to races and data loss. For example, operation "A" might retrieve the current launch settings. Then operation "B" retrieves them, …
=> Remove call to RunAndForget

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/ImplicitlyActiveConfiguredProjectReadyToBuild.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ConfiguredProjectImplicitActivationTracking.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UnconfiguredProjectTasksService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/TaskCompletionSource.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PropertyPages/DebugPageViewModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsChangeTrackerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsCompilerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcherTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Utilities/TestUtil.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/VsSafeProjectGuidServiceTests.cs
We were almost entirely using TaskCompletionSource<TResult> without actually using the result. Replace with TaskCompletionSource that hides away the result.
=> Add TaskCompletionSource

Directory.Build.props, build/import/Workarounds.props, build/import/Workarounds.targets
This is a complete workaround for the WPF temp projects not picking up NuGet packages.
=> Complete workaround for WPF temp projects

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
See https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md#lighting-up-on-later-os-versions
I believe this is all that's needed to have the project system thread this value through? I think this covers everything we need, now. /cc @nkolev92
=> adding TargetPlatformMinVersion to configuration

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsSolutionEventListener.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ILoadedInHostListener.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ISolutionService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IUnconfiguredProjectTasksService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UnconfiguredProjectTasksService.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ISolutionServiceFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UnconfiguredProjectTasksServiceTests.cs
In #6443, StartupProjectRegistrar started initializing LaunchProfilesDebugLaunchProvider much earlier than previous, causing it to overlap with solution load. This delays initialiation until after solution load.
=> Delay StartupProjectRegistrar until after solution load 

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
In 16.8 P2, .NET 5.0 SDK P8 NuGet will be reading the TargetPlatform* from the inner build. 
In 16.8 P2, NuGet is reading TargetPlatformIdentifier/TargetPlatformVersion. 
In 16.8 P3, as we discussed in a previous e-mail, NuGet will rely on TargetPlatformMoniker instead. 
Adding TPI & TPV so that P2 works consistently across commandline and VS. 
@davkean Is this the right branch for P2?
I will create a revert issue for P3 once/if we merge this.
=> Pass TPI & TPV

build/import/VisualStudio.XamlRules.targets
This embeds translated rules into satellite assemblies, ready for CPS to automatically load them from our assembly.
This doesn't change how we load these rules, that will becoming in the next PR.
=> Embed translated rules into satellite assemblies

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/RuleExporter.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/ExportedRuleTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/RuleServices.cs
- Apply [Order]
- Split into separate classes per component (this makes it easier to validate AppliesTo)
- Add a bunch of new tests
=> Organize rule exporter + tests

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/PackagePropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ParentDebugPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/SigningPropertyPage.xaml
Clean up the property pages used for Codespaces.
1. Hide the ConfigurationGeneral page. We don't want this page to be turned into a user-visible property page, so we need to tag it with `PropertyPagesHidden="True"`.
2. Explicitly set the order for our pages. None of our pages make use of the `Order` attribute so we're getting some arbitrary order that is probably just a result of the implementation details rather than a conscious choice. Here we explicitly state the ordering based on the order of the original property pages. The `Order` values are all multiple of 100 to allow for the possibility of inserting new pages later without needing to re-number everything. Also, some gaps have been left for pages that we have not yet implemented.
=> Minor property page cleanup

build/import/Packages.targets
We were running into this: https://github.com/dotnet/roslyn-analyzers/issues/4044.
=> Unify code style analyzer versions

build/import/HostAgnostic.props, tests/.editorconfig
This fixes the situation called out here: https://github.com/dotnet/roslyn/issues/43371#issuecomment-676948659.
=> Opt out test projects for Roslyn-based analyzers

build/import/HostAgnostic.props, tests/.editorconfig, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/ComponentComposition.ScopeComponents.cs
This includes https://github.com/dotnet/project-system/pull/6506, so just review: https://github.com/dotnet/project-system/commit/f50ab95aba6a6948c442b492487d0b369b7cbdd4.
This removes an analyzer workaround for a bug that has since been fixed.
=> Remove workaround

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/ServiceProviderToOleServiceProviderAdapter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Build/BuildUtilities.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Collections/DictionaryEqualityComparer.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Automation/VsLangProjectPropertiesTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/AbstractAddItemCommandHandlerTests.cs
Converts strings to `nameof` operator. I used Roslynator.
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1015.md
=> RCS1015: Use nameof operator

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs
Removed `== true` where it wasn't required using Roslynator.
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1033.md
=> RCS1033: Remove redundant boolean literal

tests/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeParser/Tokenizer.cs
Removed unnecessary interpolated string using Roslynator.
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1214.md
=> RCS1214: Unnecessary interpolated string

build/ci/official.yml
Signing can take anywhere from 30 minutes to over 1 hour depending on load, increase the timeout to 90 minutes to reduce number of aborts.
Examples tonight:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3995747&view=results
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3995577&view=results
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3995428&view=results
=> Increase official builds timeout

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/ProjectImports/ImportTreeCommandGroupHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/BaseProjectConfigurationDimensionProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsBuildManagerBridgeTests.cs
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1246.md
=> RCS1246: Use element access instead of Linq First()

src/Microsoft.VisualStudio.Editors/PropPages/CodeAnalysisPropPage.Designer.vb, src/Microsoft.VisualStudio.Editors/PropPages/CodeAnalysisPropPage.resx, src/Microsoft.VisualStudio.Editors/PropPages/CodeAnalysisPropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.cs.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.de.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.es.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.fr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.it.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.ja.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.ko.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.pl.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.ru.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.tr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
fixes https://github.com/dotnet/project-system/issues/6528
This is what the code analysis page looks like with this change:
=> Add support for AnalysisLevel and EnableNETAnalyzers properties

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/ProjectDependencyModel.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/ProjectDependencyModelTests.cs
Fixes #3685.
Previously, if a referenced project changes its assembly name, that assembly name would be used in the caption for that top-level dependency in Solution Explorer.
With this change, the project's name is used.
Given `ClassLibrary1.csproj`:
```xml
<TargetFramework>netstandard2.1</TargetFramework>
<AssemblyName>Renamed</AssemblyName>
```
=> Always use project name in caption

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/ResolvedProjectReference.xaml
Fixes #2928.
Project resolution has historically been determined by the presence of an item in the `ReferencePath` group, for which the source was a `ProjectReference`.
When a `ProjectReference` specifies `ReferenceOutputAssembly="false"`, it is explicitly stating that the referenced project's output assembly should not be included in `ReferencePath`. However, for the purposes of populating the Dependencies tree, we still wish to know that this item was present. Its absence from the `ResolvedProjectReference` item group results in a yellow triangle appearing on the reference in the tree.
To fix this, we override the target used by the `ResolvedProjectReference` rule to also return `ProjectReference` items having `ReferenceOutputAssembly="false"`.
=> Track project references having ReferenceOutputAssembly="false"

build/ci/official.yml
We were using tasks in our official build pipeline which had been deprecated which resulted in warnings showing up at the end of each build. The changes in this PR use the most up-to-date tasks and reduce the noise from the warnings.
This PR now uses the correct tasks.
Fixes #5905
=> Remove warnings of deprecated tasks on official build

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredProjectsProvider.cs
Fixes: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1155124
Fixes: https://github.com/dotnet/project-system/issues/6122
Fixes: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1155302
Active config can be set to values that aren't one of the known configs, this can happen when the project is opened without configurations and we have an active config based on the default.
=> Fix assert when active config doesn't match known configs

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/FSharp/FSharpProjectSelector.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/PackageCommandRegistrationService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/RenamerProjectTreeActionHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsUIService`1.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Waiting/VisualStudioWaitIndicator.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Xproj/XprojProjectFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Threading/JoinableTaskContextExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Waiting/IWaitIndicator.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Waiting/WaitIndicatorResult.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Waiting/VisualStudioWaitIndicatorTests.cs
IWaitIndicator had a significant amount of code handling situations that were never hit, just simplify into a single method that returns a result.
=> Simplify IWaitIndicator 

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.VisualBasic.DesignTime.targets
Separated the conditionality for .NET Framework and .NET Core, and for the latter added the case for an empty TargetFrameworkVersion string.
Fix for bug introduced in #6486.
=> Fix exception for empty TargetFrameworkVersion string

build/ci/official.yml
Our packages now go into something like `20200826.5/artifacts/Release/packages/`  instead of `20200826.5/packages` which is what the insertion tool looks for [here](https://github.com/dotnet/roslyn-tools/blob/master/src/RoslynInsertionTool/RoslynInsertionTool/LegacyInsertionArtifacts.cs#L42)
=> Publish only files within artifacts directory

build/ci/official.yml
We're getting errors that the symbols aren't correctly getting published. I've contacted the team in charge of artifactDropTask in order to understand it better since the logs seem to be doing the right thing.
This unblocks insertions.
Reopens #5905
=> Reverting task to deprecated as artifactDropTask  didn't seem to work

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/ProjectAssetsProjectEvaluationDependencyProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets, tests/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/Build/ProjectInstanceFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/Moq/ReturnsExtensions.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IFileSystemFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PackageRestore/ProjectAssetsProjectEvaluationDependencyProviderTests.cs
This replaces the MSBuild item with a MEF service, that has the added advantage of being tied to a project capability and allowing it to be loaded in project types that have not imported our Managed.DesignTime.targets.
This is a part of #2491 and enables C++ and other project types to moniter the project assets file and trigger evaluation/design-time builds when it is changed.
=>  Replace MSBuild item with MEF service 

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Menus.vsct
All the navigate commands, "Go To Test", "Go To Definition" are all bound to F12. Do the same here, but make sure its only in Solution Explorer which does not use this shortcut.
=> Bind F12 to "Navigate to Project"

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/AnalyzerReference.xaml, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/MiscellaneousRuleTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/XamlRuleTestBase.cs
This was firing an assert because we had the wrong item data source, and it was confusing Analyzers with References.
=> Fix assert in ProjectSubscriptionService

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DataflowOption.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ActiveMode.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AdditionalFilesItemHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AnalyzerConfigItemHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AnalyzerItemHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/CommandLineNotificationHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/CompileItemHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/DynamicItemHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/MetadataReferenceItemHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/ProjectFilePathAndDisplayNameEvaluationHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/ProjectPropertiesItemHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IApplyChangesToWorkspaceContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ICommandLineHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IProjectEvaluationHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IActiveConfiguredProjectProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IApplyChangesToWorkspaceContextFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ICommandLineHandlerFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IEvaluationHandlerFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContextTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/CommandLineHandlerTestBase.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/CompileItemHandler_CommandLineTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/EvaluationHandlerTestBase.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/MetadataReferenceItemHandlerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextHostInstanceTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextHostTests.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/961596
Roslyn is responsible for applying SubType to Forms, Components and other types. In multi-targeted projects, the same file can have conflicting "sub types":
```
#if NET45
class MyComponent : Form
#else
class MyComponent : Component
#endif
```
This results Roslyn pushing "Form" when it encounters scans the first definition and "Component" when it encounters the second definition.
There is no guaranteed order to which one of these get scanned first, so this can result in the same source file having a different sub type every time Roslyn does analysis. Sub Type affects the designer and icon that a type gets, so this results in tree flickering between two different icons.
This was worse before …
=> Avoid SubType fighting in multi-target projects

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Dependencies/BrowseToDependencyInExplorerCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Dependencies/ExploreDependencyFolderInWindowsCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/CopyPaste/DependencyTextPackager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependencyServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependencyTreeFlags.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/DependencyModel.DependencyFlagCache.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/TargetDependencyViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Dependency.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/ImplicitDependenciesSnapshotFilter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/IDependencyExtensions.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/TestDependencyModel.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/DependenciesTreeViewProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/AnalyzerDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/AssemblyDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/ComDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/PackageDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/ProjectDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/SdkDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/SharedProjectDependencyModelTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DependencyTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/ImplicitDependenciesSnapshotFilterTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/SdkAndPackagesDependenciesSnapshotFilterTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs
Tidies up a bunch of the tree flags used by the dependencies tree.
Fixes: https://github.com/dotnet/project-system/issues/402
Review commit by commit.
=> Review use of ProjectTreeFlags in the dependencies tree

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/VsTelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesProjectTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependencyTreeTelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/IDependencyTreeTelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.SnapshotUpdater.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/ComplexPropertyValue.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryEventName.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryPropertyName.cs
Fixes #6575.
On project unload, publish a telemetry event with data about a project's dependencies.
A sample event:
| Field | Value |
|---|---|
| vs.projectsystem.managed.projectunload.dependencies.dependencybreakdown | `{"netcoreapp3.1":{"Framework":{"TotalCount":1,"UnresolvedCount":0},"Package":{"TotalCount":1,"UnresolvedCount":0}},"net48":{"Assembly":{"TotalCount":9,"UnresolvedCount":0},"Package":{"TotalCount":1,"UnresolvedCount":0}}}` |
| vs.projectsystem.managed.projectunload.dependencies.project | 0c63db02-c6b6-465e-a104-4af7bd775739 |
| vs.projectsystem.managed.projectunload.dependencies.projectagemillis | 35636 |
| vs.projectsystem.managed.projectunload.dependencies.targetframeworkcount | 2 |
| vs.projectsystem.managed.projectunload.dependencies.totaldependencycount | 12 |
| …
=> Produce telemetry on yellow triangles in the dependency tree

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs
Fixes #5836.
Removes a guard that attempts to return early from processing on data changes. The condition here only considered one kind of change, which may result it downstream code retaining objects from earlier updates, such as a `ProjectInstance` via `IProjectCatalogSnapshot`.
Downstream code will handle the no-op case correctly anyway, so removing this guard here does not introduce considerably more work for the tree.
=> Fix potential ProjectInstance leak

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/DependenciesAttachedCollectionSourceProviderBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/FrameworkReferenceAssemblyAttachedCollectionSourceProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/RelationAttachedCollectionSourceProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/RelationAttachedCollectionSourceProviderBase.cs
Fixes #6617
Previously the import of `IAttachedCollectionSourceProvider` parts did not filter exports based on metadata. This meant that all exports were loaded, which resulted in DLLs being loaded even when the dependencies tree was unused.
This filtering is now supported by Solution Explorer, and this commit adds the relevant condition to ensure DLLs are not loaded unnecessarily.
=> Add metadata to filter MEF exports until needed

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependencyTreeTelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryPropertyName.cs
- Change the format to be easier to query
- Include totals at the TFM level
- Include a version number so we can exclude earlier representations
=> Version two of project unload dependency telemetry

src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPageInternalBase.vb, src/Microsoft.VisualStudio.Editors/PropPages/TargetFrameworkMoniker.vb, src/Microsoft.VisualStudio.Editors/PropPages/TargetFrameworks/FrameworkMultiTargetProvider.vb, src/Microsoft.VisualStudio.Editors/PropPages/TargetFrameworks/ISupportedTargetFrameworksProvider.vb, src/Microsoft.VisualStudio.Editors/PropPages/TargetFrameworks/TypeConverterTargetProvider.vb, src/Microsoft.VisualStudio.Editors/PropPages/TargetFrameworks/WebFrameworkMultiTargetProvider.vb, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/SupportedTargetFrameworksEnumProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/SupportedTargetFrameworksEnumProviderTests.cs
This refactors the logic to read supported frameworks, and removes the CPS implementation from parsing/understanding the "moniker" being based through from SupportedTargetFramworksEnumProvider.
This is a precursor to enabling us to bind to the "TargetFramework" property in https://github.com/dotnet/project-system/pull/6607.
Before this change;
1) The moniker returned from SupportedTargetFrameworksEnumProvider was being parsed and filtered. This breaks when we change this moniker to a "friendly identifier" in #6607 such as "net5.0-windows".
2) Web/Legacy/CPS filtering was all intertwined. This separates the logic into separate types.
3) This fixes a slight bug where the display name for .NET Framework-only targets in SDK-based projects would show as ".NETFramework,v4.5" if the TFM wasn't …
=> Refactor logic to read supported frameworks

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/LanguageService.xaml
Roslyn team needs to get the path of project.assets.json for specific 
projects. This is part of the new feature Remove Unused Reference.
This change pushes to Roslyn the msbuild evaluation ProjectAssetsFile
containing the absolute path for project.assets.json so they can get
this info on their side.
=> Enable property ProjectAssetFile for Roslyn.

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
The up-to-date check must return false for the first time it is executed against a project. This ensures that changes made to the project since it was last loaded (such as items being deleted) are not missed.
Previously these failures were accompanied by a message resembling:
> Input 'MyFile' (2/10/2020 12:34:56) has been modified since the last up-to-date check (01/01/0001 00:00:00), not up to date.
The "zero" date is DateTime.MinValue, and it's not clear that this indicates the up-to-date check has not yet run.
With the change in this commit, this scenario now logs a more explicit message:
> The up-to-date check has not yet run for this project. Not up-to-date.
=> Improve first up-to-date failure log message

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/DteEnvironmentOptions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IEnvironmentOptions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IUserNotificationServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/RenamerProjectTreeActionHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UserNotificationServices.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/CSharp/RenamerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/RenamerTestsBase.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/VisualBasic/RenamerTests.cs
This fixes [AB#1144262](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1144262)
It seems that this option is misleading since we are enabling the feature unconditionally. People might get confused when trying to disable the prompt and still seeing changes in your code.
This change replaces the dialog box to allow the option "Don't Ask Again" so users can disable the prompt message from here.
CheckUserConfirmation() now returns false and that means the feature is disabled by default unless there is a prompt and the user selects Yes.
This change will allow the user to disable this feature when the message prompt is disabled.
Perhaps a future enhancement is to add another checkbox in Tools |Options | Project and Solutions | General | "Always apply symbol …
=> Allow the user to disable the feature symbolic renaming on File-rename

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducer.cs
This prevents a `MissingDataException` when querying this property.
=> Provide empty SearchTerms to avoid exception on client

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/AuthenticationModeEnumProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/LaunchTargetPropertyPageEnumProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/NeutralLanguageEnumProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/SupportedTargetFrameworksEnumProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/NeutralLanguageEnumProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/SupportedTargetFrameworksEnumProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/AuthenticationModeEnumProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/LaunchTargetPropertyPageEnumProviderTests.cs
A null return value is equivalent to throwing NotImplementedException but is less disruptive during debugging.
=> Return null rather than throw

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/ProjectType.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/ProjectTypeCapabilitiesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/ProjectTypeGuidsDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/VsAggregatableProject.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DataFlowUtilities.cs
This maps from flavor project type GUIDs -> capabilities, so that we can tie specific components that light up ASP.NET full framework support behind a capability. Also adds an incomplete implementation of IVsAggregatableProject for components that sniff support based on the GUIDs it returns.
This currently maps:
Web Application Projects (not a complete list of them) -> "AspNet"
Test Projects (Legacy) -> "TestContainer"
=> Map from flavors -> capabilities

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml.cs
The Debug page was not being responsive to high contrast changes. This resulted in an accessibility bug reported here [AzDO#1172163](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1172163).
The Debug page is a special case in the Properties pages: it's a WPF control inside the WinForms window. The approach taken was to use the `SetResourceReference` to set the `BackgroundProperty` to `SystemColors.ControlBrushKey` value. In that way, we pass down the [ControlBrushKey](https://docs.microsoft.com/en-us/dotnet/api/system.windows.systemcolors.controlbrushkey?view=netcore-3.1#System_Windows_SystemColors_ControlBrushKey) dynamically.
**Before:**
**After:**
There are rough edges when toggling back and forth the high contrast setting, but I think this is a good start.
=> Enable high contrast for Debug page (to 16.8)

build/ci/richnav.yml
I pulled the pool for the new rich nav pipeline from /build/ci/official.yml (not /build/ci/unit-tests.yml) and it looks like the agent isn't available for the public CI (or else I don't have permission to authorize it). 
Link to failing build: https://dnceng.visualstudio.com/public/_build/results?buildId=853138&view=results
=> Use appropriate pool in rich nav pipeline

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyEditorDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/UIPropertyEditorDataProducerTests.cs
Properties may specify `ValueEditor`s to control how they are edited in the UI. However for `StringProperty` it's more common to specify the `Subtype` property with a value such as `"file"` to indicate that the property expects a file path.
We don't currently plumb `Subtype` through the Project Query API project model. This value only applies to `StringProperty` and we want the shape to be identical across property types.
The solution is to maps common `StringProperty.Subtype` values to `ValueEditor` values.
- Subtype `file` becomes editor `FileBrowse`
- Subtype `path` becomes editor `PathBrowse`
This causes, for example, the icon path property to show a "browse" button:
=> Set editor for StringProperty with subtype "file" or "path"

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/BasePropertyExtensions.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/BasePropertyExtensionTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducerTests.cs
Update our Project Query API implementation to return search terms from .xaml `Rule` files.
The new property page UI will support searching across the properties, and we expect that the terms searched for will generally appear in the name, description, or other displayable text associated with the property. However, there may be times we want to associate a search term with a property even when it does _not_ appear in the displayable text. To support this, the `IUIProperty` type in the Project Query API includes a `SearchTerms` member that returns a list of strings.
This change populates the `SeachTerms` by examining the property's metadata for an item named "SearchTerms". If found the value is split on semi-colons into individual terms and returned.
Note that this is something of a …
=> Add search terms support

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/GlobalSuppressions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/Tree/SpecialCodeFolderDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/Tree/SpecialWebFolderFlag.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/Tree/SpecialWebFolderPropertiesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/Tree/SpecialWebFolderPropertiesProviderDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Annotations.cs
- Marks ASP.NET folders with a specific flag based on its name.
- Gives them an icon to visiblity distinguish from normal folders. Note we need to request icons for folders as they are missing.
- Code folders support isn't completely hooked as we're missing the right hooks in CPS to determine where in the tree we are in a property provider.
=> Support special ASP.NET folders

build/import/Packages.targets, src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerEditorFactory.vb, src/Microsoft.VisualStudio.AppDesigner/Microsoft.VisualStudio.AppDesigner.vbproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyEditorFromUIPropertyDataProducer.cs
CPS [PR 281509](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/281509) registers a new Project Properties editor.
When the user opts in to feature `CPS.UpdatedProjectPropertiesDesigner.Local` we redirect requests for the legacy project editor to the new project editor.
There is currently a bug where the editor only appears on the second launch.
Codespaces support is currently blocked on [AB#1178677](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1178677).
=> Delegate to new project properties editor via feature flag

build/import/Packages.targets
The VSLangProj2 package includes VSLangProj2.dll. The version of the
package we currently reference has an unsigned copy of the assembly,
leading to build failures on systems that have not had signing
verification turned off. Here we update to a version of the package that
has a properly signed assembly, and update related packages for the
sake of consistency and to avoid NuGet warnings about version
mismatches.
=> Update VS extensibility Packages

build/import/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VisualBasic/VisualBasicNamespaceImportsList.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsBuildManagerBridge.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/PropertiesAvailableStatusFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/VisualBasicNamespaceImportsListFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/CategoryDataProducerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/ConfigurationDimensionDataProducerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/PropertyPageDataProducerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/SupportedValueDataProducerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/UIEditorMetadataProducerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/UIPropertyValueDataProducerTests.cs
Add support for the `DependsOn` and `VisibilityCondition` properties. `DependsOn` returns a list of other property names that the current property depends on for its value; the UI can use this to determine if it needs to requery the value or metadata of one property when another one changes. `VisibilityCondition`, meanwhile, represents an expression that the UI will evaluate to determine if the related UI elements should be shown or not. This would allow us to show or hide properties in response to other property values changing without requiring a round trip to the server.
Note that the type of `DependsOn` (and the existing property, `SearchTerms`) will switch from `ImmutableList<string>` to just `string` in a future update from CPS. However, I want to get the basic functionality …
=> Implement DependsOn and VisibilityCondition

build/import/HostAgnostic.props, build/import/Packages.targets, build/import/VisualStudio.props, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducer.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducerTests.cs
A recent change in the Project Query API ([PR 281922](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/281922) in CPS) changed the `SearchTerms` and `DependsOn` properties of `UIProperty` to return `string` instead of `ImmutableList<string>`. Here we adopt the latest version of the APR, and adapt the implementation to the updated return types. In practice these means that we just read these values from metadata in the .xaml file and pass it through unchanged, rather than splitting it up into a list. If the UI needs to do so, it will handle the splitting.
One odd aspect of this change is the need to move the references to PresentationCore, PresentationFramework, and WindowsBase from VisualStudio.props to HostAgnostic.props. The Microsoft.VisualStudio.ProjectSystem.Managed …
=> Adapt to Project Query API changes

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/Tree/SpecialCodeFolderDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/Tree/SpecialWebFolderPropertiesProvider.cs
App_Code and other code folders are passed specifically by IVsWebProjectSupport2.CodeFolderAdded, no need to specially look for them.
=> Handle code folders correctly

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/ConfigurationDimensionDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/ConfigurationDimensionFromPropertyDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/IPropertyPageQueryCache.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageQueryCache.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyValueDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/BasePropertyExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ParentDebugPropertyPage.xaml, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IPropertyFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IPropertyPageQueryCacheFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/ConfigurationDimensionDataProducerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/ProjectActionProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/UIPropertyValueDataProducerTests.cs
Currently when retrieving the values for a property we get them across all configurations, even for properties that are configuration-independent. At best this is inefficient as we will retrieve and transmit many duplicate values that the UI will not use. At worse it breaks the query when a particular property implementation expects to only be asked about its value (or supported values) in the currently active configuration (I'm looking at you, `TargetFrameworkMoniker`).
Here we update the `UIPropertyValueDataProducer` to only return a single value for these properties. The `IPropertyPageQueryCache` has been updated to return the "suggested" `ProjectConfiguration`, and this is the one we use to retrieve the property value as it is likely to have already been loaded.
=> Properly support configuration-independent properties

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/PackagePropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/SigningPropertyPage.xaml
Fixes #6541.
Properties declared in .xaml `Rule` files may include a `HelpUrl` field providing the web address of documentation for that property. Here we update the existing `HelpUrl`s to go through our redirection service (FWLink). This will allow us to update the URLs in the future without needing to service the product; we can just update the entry in the FWLink redirection service instead.
=> Use FWLinks for HelpUrls

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerEditorFactory.vb, src/Microsoft.VisualStudio.AppDesigner/GlobalSuppressions.vb, src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerEditorFactory.vb
Previously the delegation looped back through OpenSpecificEditor which caused a few bugs:
- The editor would not appear on the first request, but would on the second
- The document title would show the full path in some circumstances
- An open property editor would stop project file editing from working
This change performs delegation by obtaining an instance of the new editor factory directly and invoking it. This means that the new editor factory is directly handling requests made of the old editor factory.
---
(Includes #6731 so just review cd3befad1d005f95d8cc4dd5e2175cd6984a4cd6).
=> Fix delegation to new project properties editor

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WindowsForms/WindowsFormsEditorProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectTreeExtensions.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/WindowsForms/WindowsFormsEditorProviderTests.cs
Fixes: #6726
Under high project lock contention, such as during a branch switch or a change to a props/targets shared by an entire solution, we can hit UI delays selecting items in Solution Explorer trying to figure out if we can "preview" files.
Use snapshot data if available in WindowsFormsEditorProvider to prevent that.
=> Use snapshot data in WindowsFormsEditorProvider

build/import/Packages.targets
This release has a substantial perf improvement for the VSTHRD010 analyzer.
=> Bump vs-threading to 16.8.55

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/ProjectFilePathAndDisplayNameEvaluationHandler.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/ProjectFilePathAndDisplayNameEvaluationHandlerTests.cs
The map Properties may not contain the key value.
The current logic checks for existing key is present in ChangedProperties, but it gets the value from Properties causing to throw an exception.
This change only adds logic to check if Properties contains the key before getting the value.
=> Code cleanup - handle key not found

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml
Increases the chance of finding properties using related words or alternate spellings.
It seems SearchTerms metadata is not localised. This defeats their purpose in other cultures. @tmeschter do you have a sense of what's involved here? Should I file an issue for this?
I'd like some examples of this feature in the data for testing/demo purposes. I hit this organically typing "optimise" and getting different results to "optimize".
=> Add some property page search terms

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/AbstractSpecialFolderProjectTreePropertiesProvider.cs
This falls back to the new missing default folder icon when the folder is missing. This is counter change to https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/287315?_a=files.
=> Use new missing folder icon for properties

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/CategoryFromPropertyPageDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/ConfigurationDimensionFromPropertyDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageProviderState.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyProviderState.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyValueProviderState.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/SupportedValueFromPropertyDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyEditorFromUIPropertyDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyFromPropertyPageDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyValueDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyValueFromUIPropertyDataProducer.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/PropertyPageDataProducerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducerTests.cs
Currently, when we create a Project Query API entity (representing a property page, property, etc.) we communicate the important state to the producers of the child entities using a tuple. As we add more producers and further refactor this code it has become clear that the use of a tuple here will lead to errors as different producers may accidentally come to expect different tuple shapes. Remembering the correct shape often means going back to the point where the tuple is created, if you can find it.
This commit replaces the tuples with simple named types.
=> Replace tuples with named types

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/CategoryByIdDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageByIdDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/QueryDataByIdProducerBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyByIdProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyEditorByIdDataProducer.cs
When asked to retrieve an `IEntityValue` (for a property, page, etc.) given an `EntityIdentity` we always do the same two basic operations: first, we expand the `EntityIdentity` into the relevant pieces. If that works, we then pass those pieces along to another method to actually create the `IEntityValue`. Here we extract out the duplicated code into a base class for the four producers that can handle retrieving a value by key.
=> Extract boilerplate

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ApplicationManifestKindValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ResourceSpecificationKindValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/GenerateDocumentationFileValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/PackagePropertyPage/PackageLicenseKindValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/ProjectPropertiesExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/PackagePropertyPage.xaml
Temporarily save certain property values when:
- toggling between icons/manifests and resource files
- toggling documentation file generation
- toggling between package license files and package license expressions
The idea here is that these operations should be non-destructive. That is, if you toggle documentation file generation off, and then back on, we should also restore the provided doc file path (if any). Similarly, if you switch from a package license expression to a file and then back, we should restore the license expression.
We accomplish this by saving the values of the properties to `ITemporaryPropertyStorage` before deleting them, and restore them if/when they later become applicable again.
=> Temporarily save property values

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Frameworks/SupportedTargetFrameworksProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ProjectContextCodeModelProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/AuthenticationModeEnumProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/VisualBasic/MapDynamicEnumValuesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/NoOpInterceptingPropertyValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/LaunchTargetPropertyPageEnumProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/NeutralLanguageEnumProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractFindByNameSpecialFileProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/TaskResult.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectItemProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/OnceInitializedOnceDisposedUnderLockAsyncTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Threading/Tasks/TaskResultTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Waiting/VisualStudioWaitIndicatorTests.cs
Tasks with null or empty string values can be reused, avoiding allocations at run time.
=> Cache more cases of Task.FromResult

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ResourceSpecificationKindValueProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ITemporaryPropertyStorageFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ResourceSpecificationKindValueProviderTests.cs
In the new project property pages we allow the user to specify if they want to supply separate icon and manifest files for their application, or if they want to supply a resource file containing the information. This selection is done via a drop down. Depending on which option the user chooses, we show or hide the controls for the relevant properties.
This "resource specification kind" is a "synthetic" property that has no representation of its own in the project file (or any other storage). Instead, we assume that if the "Win32Resource" property has a value, the user has opted to use a resource file; otherwise, they have opted to use an icon and manifest.
This currently leads to problems when trying to switch between the two. If the project does not specify the "Win32Resource" property …
=> Preserve values of a synthetic property

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Log.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.TimestampCache.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryPropertyName.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ITelemetryServiceFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
Fixes #6776.
Extends the existing telemetry events for pass/fail to include two new properties each:
1. The duration of the check, in milliseconds
2. The number of file system timestamp queries
Event `vs/projectsystem/managed/uptodatecheck/fail`:
| property | value |
|----|---|
|vs.projectsystem.managed.uptodatecheck.durationmillis|22.5333|
|vs.projectsystem.managed.uptodatecheck.fail.reason|Outputs|
|vs.projectsystem.managed.uptodatecheck.filecount|6|
Event `vs/projectsystem/managed/uptodatecheck/success`:
| property | value |
|----|---|
|vs.projectsystem.managed.uptodatecheck.durationmillis|16.1586|
|vs.projectsystem.managed.uptodatecheck.filecount|157|
=> Extend up-to-date check telemetry

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/ProjectSetUIPropertyValueActionCore.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IRuleFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/ProjectActionProviderTests.cs
Currently, when setting a property value through the Project Query API we first find all the applicable `ConfiguredProject`s, then bind the requested rule in each, and finally retrieve and set the property in each bound rule.
This makes sense for configuration-dependent properties, where we may want to set the values in some configurations but not others. However, most of our properties are configuration-independent and it doesn't matter which `ConfiguredProject` we go through or how many: ultimately, we'll end up with just one definition in the project file, with no configuration conditions. To avoid unnecessary work we should only set the value of a configuration-independent property once.
This commit adds the necessary checks before we start retrieving the `ConfiguredProject`s.
=> Only set config-independent properties once

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/CategoryDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/CategoryFromPropertyPageDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/DebugUtilities.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/ProjectSetUIPropertyValueActionCore.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageProviderState.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyFromPropertyPageDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ParentDebugPropertyPage.xaml, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectThreadingServiceFactory.ProjectThreadingService.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/CategoryDataProducerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/PropertyPageDataProducerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducerTests.cs
This PR includes all the changes needed to get properties for debug pages to show up in the new project property pages. For background, we already define the ParentDebugPropertyPage.xaml which includes properties for the active launch profile, and the active launch profile's launch target. These will always be shown. In addition to that, we have individual .xaml Rule files for each launch target, specifying all the properties relevant to that target. We also have code that can read and write the values of the active launch profile to the launchSettings.json file.
Our goal in this change is to take the parent Rule and all the child Rules and combine them into a single property page, as exposed through the Project Query API. In practice what this means is re-writing the names of properties …
=> Simple Debug page support

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/RenamerProjectTreeActionHandler.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/CSharp/RenamerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/VisualBasic/RenamerTests.cs
[AB#1163112](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1163112) Fixes file rename crashing when a file changes its extension.
`RenameAsync()` was trying to apply symbols rename and Roslyn was failing to find the original filename.
* This change checks for changes in file extensions, and avoid calling Roslyn symbol rename.
* Apart from this, there are other few minor changes as part of the cleanup.
* Added one unit-test to test `RenamerProjectTreeActionHandler.FileChangedExtension`
=> Bug1163112

tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Resources/XliffTests.cs
NOTE This PR will fail to build until #6788 is merged. That failure is exactly what this unit test is trying to catch in future.
---
The ampersand character in UI control labels generally causes the subsequent character to be treated as a keyboard accelerator.
It is irregular for a UI element to have more than one such accelerator key.
We saw such a situation in a resource file, which was addressed in #6788.
This test ensures the scenario doesn't occur again in future.
Note that not all resource strings are used as UI labels, so it's possible this test may need tweaking in future. WPF uses underscore for accelerators, but this causes too many false positives in our resource files, so has been excluded here.
=> Ensure XLF strings do not contain multiple accelerator mnemonics

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerEditorFactory.vb
Fixes #6794.
This prevents opening the properties pages in csproj projects, which fails.
=> Only use the new properties pages for CPS projects

src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.resx, src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/CodeAnalysisPropPage.vb, src/Microsoft.VisualStudio.Editors/PropPages/Strings.Designer.vb, src/Microsoft.VisualStudio.Editors/PropPages/Strings.resx, src/Microsoft.VisualStudio.Editors/PropPages/xlf/Strings.cs.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/Strings.de.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/Strings.es.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/Strings.fr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/Strings.it.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/Strings.ja.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/Strings.ko.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/Strings.pl.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/Strings.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/Strings.ru.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/Strings.tr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/Strings.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/Strings.zh-Hant.xlf
Today if you open a .NET Core project and set **Analysis Level** to be `preview`
The build property page will fail to load:
=> update build property page to include all available warning levels

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/AnalyzerReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/ResolvedFrameworkReference.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/SdkReference.xaml, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/DependencyRuleTests.cs
Fixes #6803. Fixes #6804.
The dependencies tree consumes both unresolved and resolved versions of project dependency items.
Unresolved items are obtained quickly via evaluation in order to build the tree rapidly when a project is opened, and to quickly reflect changes to the tree as items are added, removed and updated over time.
Resolved items are obtained via design-time builds. They contain much richer information about dependencies than evaluation items, and the tree is updated with that information as it becomes available.
It's important that unresolved items are only sourced from evaluation. If their rule files request they come from design-time builds, then they the dependencies tree cannot be built until a design-time build completes.
Before this change, both SDK and Analyzer …
=> Source all unresolved references from evaluation

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.cs
Fixes #6813.
PR #6781 added a condition to `TryCreatePackageDependencyModel` that required the evaluation snapshot to contain the item before continuing. This logic does not make sense in the case of removal, as that dependency will not be in the snapshot by definition.
When removing, we do not need to create the `PackageDependencyModel`. We only need the (original) item spec.
In addition to fixing the bug, this change also cuts down on the amount of code that runs and memory that's allocated during package reference removal.
=> Fix package reference removal

src/Microsoft.VisualStudio.Editors/PropPages/PackagePropPage.resx, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.cs.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.de.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.es.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.fr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.it.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.ja.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.ko.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.pl.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.ru.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.tr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.zh-Hant.xlf
This fixes two accessibility bugs reported in AzDO: [1245123](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1245123), [1245125](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1245125).
=> Fix a11y issue: Name must not include LocalizedControlType.

src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.resx, src/Microsoft.VisualStudio.Editors/PropPages/CodeAnalysisPropPage.resx
Minor fixes for user to navigate all the interactive elements in the properties pages in a predictable order (in this case, top to bottom).
**Before:**
**After:**
**Before:**
**After:**
=> Fix tab stops to follow top to bottom order.

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshotTests.cs
Fixes #6656.
The validation in is sound in theory, however is causing quite a few NFEs. For example https://github.com/dotnet/project-system/issues/6656.
This commit disables it for now. The consequence of this test failing is that dependencies added to the tree are not exposed via extensibility APIs such as DTE/VSLangProj.
At some point we should revisit how the dependencies tree models its target frameworks, likely as part of https://github.com/dotnet/project-system/issues/6183.
=> Suppress validation of active target framework

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/DebugTests/StartupProjectRegistrarTests.cs
Fixes [AB#1229073](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1229073).
Follows #6722.
This NRE is currently the number 4 NFE for CPS-based projects. Those reports show that there may be no `IVsStartupProjectsListService` service registered, in which case the return value will be `null`.
The fix is to return early when the service does not exist.
=> Prevent NullReferenceException in StartupProjectRegistrar

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContextProvider.cs
Recently I've been working to make the dependencies tree populate faster on project load.
During testing, I found call to `GetConfigurationGeneralPropertiesAsync` seemed to be a source of some delay in the dependencies node code.
The result of that method is only used if `shortOrFullName` is null or empty, which rarely happens. I couldn't trigger this code path in my testing, so it might actually never happen.
This change avoids sourcing the `ProjectProperties` export and calling `GetConfigurationGeneralPropertiesAsync` on it unless it is absolutely necessary to do so.
=> Avoid calling expensive method in common case

.editorconfig
It was disabled due to a crash. The crash is supposed to be fixed.
=> Re-enable IDE0100

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Subscription.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
Fixes #6327.
The `BuildUpToDateCheck` component is constructed and initialised (via `IProjectDynamicLoadComponent`) for both active and inactive project configurations. Previously, this initialisation would trigger dataflow subscriptions for each project configuration, triggering CPS to construct a chain of dataflow blocks to service that subscription. For inactive configurations those chains linger in memory without actually being used.
This commit avoids this problem by deferring construction of the dataflow subscription until the first call to `IsUpToDateAsync`. This method is only called when the configuration is actually being used. In this way, the overhead associated with instances of `BuildUpToDateCheck` in inactive project configurations is minimised.
An …
=> BuildUpToDateCheck subscribes for updates lazily

src/Common/BannedSymbols.txt
As described in #6369 and #6370, `IVsFrameworkParser` uses the `FrameworkName` type which does not support the platform information added to target frameworks in .NET 5.
We have already done the work to remove usages of this interface. This change prevents us from attempting to use the type again in future.
=> Ban IVsFrameworkParser

build.cmd, build/script/SetVSEnvironment.cmd
Related: https://github.com/dotnet/project-system/issues/6744
- Removed temporary workaround that has been fixed
- Updated RequiredVSVersion to pull the version number from Versions.props which sets the ProjectSystemVersion
- The current version in that file is `16.8.1`.
- Added arguments for calling `powershell` to reduce potential failures and removed progress bar for downloading VSWhere
- Progress bars (traditionally) have overhead in Windows PowerShell.
- We are using Windows PowerShell since we call `powershell`. PowerShell Core uses `pwsh`.
- Updated version of VSWhere used to latest release
=> Updated build.cmd to use version minimum from Version.props

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs
We should only change the debugger settings when the command is set to 'Project' or 'Executable' since WebView2 debugging is only supported for those.
=> Adding command checks for WebView2 debugging

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/RenamerProjectTreeActionHandler.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/CSharp/RenamerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/VisualBasic/RenamerTests.cs
fixes [AB#1237959](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1237959)
In a fresh VS installation or repair, Dotnet ProjectSystem cannot get the value in the checkbox Tools | Options | Project and Solutions | Enable Symbol Rename. At this point VS has no knowledge of this value and that is how the system works. The user has to turn the checkbox off and then on to make it work and have a persisted value for future usages.
This small change sets the default value of EnableSymbolRename to true to match the value on a fresh VS Installation.
This change will enable Symbols Rename by default on a fresh installation.
=> Change the default value for Symbols Rename in a fresh VS installation.

build/ci/richnav.yml, build/ci/unit-tests.yml
Part of #6857
pipelines no longer need to know about `master` branch
=> Remove triggers referencing master

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerView.vb, src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerWindowPane.vb, src/Microsoft.VisualStudio.AppDesigner/Common/Utils.vb, src/Microsoft.VisualStudio.AppDesigner/PublicAPI.Unshipped.txt
The goal is to be able to measure the success of opening the properties pages. For that, we already track when they are closed and asked to be opened; but we missed an event to track when they are already opened (focused or not focused).
The general flow is as follows:
The diagram can be read like this:
- The user first right clicks the project. This is the context menu.
- The user then selects the "Properties" command.
- The ProjectFileDocumentManager calls the method `OpenWithSpecific`, which calls to the ApplicationDesignerWindowPane's `ActivateLogicalWindow`, `PopulateView`, which calls to create the AppDesignerView with the `InitView` method. This is where we get our first event out: we call `LogAppDesignerDefaultPageOpened` which sends vs/projectsystem/appdesigner/page-opened.
- We …
=> Add telemetry to track when properties pages are already opened.

src/Common/BannedSymbols.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/TargetFrameworkMonikerValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TargetFrameworkProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Frameworks/ITargetFrameworkProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Frameworks/TargetFramework.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesTreeViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependencyTreeTelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/TargetDependencyViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.ContextTracker.cs, tests/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/DependencyNodeIntegrationTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IMockDependenciesViewModelFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/DependenciesViewModelFactoryTests.cs
This PR reverts #6859 in order to restore #6712 with an additional fix.
The DependenciesSnapshotProvider keeps track of an AggregateCrossTargetProjectContextProvider (in its ContextTracker) to enable it to detect changes to a project's target framework. More specifically, it calls the context.TryUpdateCurrentAggregateProjectContextAsync expecting a non-null AggregateCrossTargetProjectContext if and only if the existing AggregateCrossTargetProjectContext is for a target framework that does not match the one in its current project context. This is the case:
1. Before any AggregateCrossTargetProjectContext has been created.
2. When the TargetFramework in the project file is changed.
When a new AggregateCrossTargetProjectContext needs to be created for the first time, …
=> Replace invalid use of the TargetFrameworkMoniker with target framework alias

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
A `TaskCompletionSource` is used within `LaunchSettingsProvider` to signal when the first data snapshot is available to callers of `WaitForFirstSnapshot`.
The previous code would signal completion _before_ setting the field. This might seem to create an impossibly narrow window for a race condition to occur, however by default `TaskCompletionSource` schedules its continuations to run synchronously. This means that code waiting for the snapshot to arrive would be executed before the field was set. That code is likely to immediately query the snapshot, which will be null. Such code might expect the value to be non-null*, resulting in exceptions.
---
*There are issues with the null annotations in this type which should be addressed separately. Specifically:
```diff
diff --git …
```
=> Fix race condition in LaunchSettingsProvider

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDebugLaunchProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectLaunchTargetsProviderTests.cs
Fixes: [AB#1245470](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1245470)
Related: https://github.com/dotnet/project-system/pull/6443#pullrequestreview-458792319
Currently, `ProjectNotRunnableDirectlyException` is thrown when the project cannot be debugged, such as a class library. Then, this exception is explicitly caught in `CanBeStartupProjectAsync`. If caught, it cannot be a startup projects (returns false). Otherwise, the method returns true.
This exception is thrown in `GetTargetCommandAsync`. Working up the call stack, this is used in the 2 public methods, `QueryDebugTargetsForDebugLaunchAsync` and `QueryDebugTargetsAsync`. These implement a couple of provider interfaces for the `ProjectLaunchTargetsProvider`. So, anything that calls these …
=> Remove ProjectNotRunnableDirectlyException

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/ActiveLaunchProfileNameValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/LaunchSettingsValueProviderBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/LaunchTargetPropertyPageValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Shipped.txt, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ILaunchSettingsProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProviderTests.cs
This is a follow up to #6872.
Currently, the `ILaunchSettingsProvider` interface claims that the `CurrentSnapshot` property and `WaitForFirstSnapshot` method will always return a non-null `ILaunchSettings`. Unfortunately, neither is true.
In practice, creating an `ILaunchSettings` snapshot requires knowing the active profile name, and this is stored in a property in the .user file (if it exists). Retrieving the property requires an evaluation; as such we can't produce an `ILaunchSettings` until at least one evaluation has occurred and we have a chance to process it.
It is possible for a consumer of `ILaunchSettingsProvider` to request the `CurrentSnapshot` before this has occurred, in which case they will receive `null`. Note that the implementation of this property (in the …
=> Update null annotations

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs
Adds a catch for CanBeStartupProjectAsync to suppress all exceptions. This is the 16.9 fix of https://github.com/dotnet/project-system/pull/6890, which is the 16.10 fix. We're doing 2 different fixes since we don't know what other potential exceptions might be thrown. The 16.10 fix works specifically for the issues filed in that PR. The PR here is to simply add the catch that was previously there as to suppress any potential exceptions for the 16.9 release.
=> Suppress exceptions in CanBeStartupProjectAsync

tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/OnceInitializedOnceDisposedUnderLockAsyncTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/WindowsForms/WindowsFormsEditorProviderTests.cs
The `_` character is no longer treated as a parameter identifier, so can be repeated in a parameter list, or where another discard otherwise exists in the same scope.
=> Use C# 9 lambda discards

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ProjectContextCodeModelProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/ProjectFileOrAssemblyInfoPropertiesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ActiveWorkspaceProjectContextHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IWorkspaceProjectContextHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/AssemblyAttributeProperties/AbstractProjectFileOrAssemblyInfoPropertiesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/AssemblyAttributeProperties/AssemblyInfoProperties.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IActiveWorkspaceProjectContextHostFactory.cs
`IWorkspaceProjectContextHost.OpenContextForWriteAsync` can return null.
This means that several other methods can return null too. Looking at usages of those methods, they seem to expect null values, as they handle them.
=> Fix IWorkspaceProjectContextHost annotations

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/SolutionExplorer/ProjectNodeCommandHandler.cs
[AB#1245680](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1245680)
The issue:
Neither the NodeMoniker nor the NodeFullMoniker contain the required path
to find the project file on the server to use it with OpenDocumentAsync()
The change:
This small change replaces NodeMoniker with the local uri full path that is required
for OpenVisualStudioRemoteFile on the client.
How this change fixes the issue:
OpenVisualStudioRemoteFile will use the local full path to allow the command Edit Project File to find the corresponding project file
on the server.
=> Fix the command Edit Project File on nexus client to open the file.

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfilesProjectItemProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ILaunchSettingsProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchProfilesProjectItemProviderTests.cs
This is the first (small) step in exposing individual launch profiles as CPS project items (i.e., instances of `IProjectItem`). CPS has a lot of built in support for managing project items: things like source files, resource files, references--really anything that is described in an MSBuild file as an item. This includes support for adding and removing items, renaming items, accessing item metadata, and binding Rules to items to expose and edit their properties in various ways.
Each "item type" (Compile, EmbeddedResource, etc.) needs to be handled by an implementation of `IProjectItemProvider`. In practice all MSBuild items that represent files on disk are handled by the same default `IProjectItemProvider` owned by CPS, and it has its own extensibility points for customizing the behavior …
=> Launch Profiles project item provider

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs
This field is never null. It may be empty, but never null.
=> Remove redundant null check

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/LanguageService.xaml
Relates to issue #6820.
Replaces PR #6893.
Roslyn needs a way to identify which workspace project context a given dependencies tree node relates to. Ideally we would store the project context ID on the node itself for Roslyn to query, however we are late in the 16.9 cycle and the magnitude of that change would likely make it too risky. For now, we pass the `TargetFramework` property value (aliased as `TemporaryDependencyNodeTargetIdentifier`) to the language service, so it can match the value against the `$TFM:net5.0`-style value found in the node's capabilities property value.
=> Allow language service to identify dependency tree target nodes

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/DependenciesTreeProjectSearchContext.cs
In #6873 we changed the dependencies tree to no longer use the `TargetFrameworkMoniker` to identify per-target branches of the dependencies tree. This fixed an issue where `net5.0` and `net5.0-windows` would merge into one, because they have identical `TargetFrameworkMoniker` values.
Code in `DependenciesTreeProjectSearchContext` was missed during that change. This commit brings it up to date.
Missing this usage broke searching in the dependencies tree for multi-targeting projects, causing such searches to return no results within the dependencies tree.
=> Use correct project value when finding target node

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextProvider.cs
In https://github.com/dotnet/roslyn/issues/51016 @jasonmalinowski explains that disposal of `IWorkspaceProjectContext` is free threaded.
=> Don't switch to UI thread to dispose workspace project context

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs
We spoke about this during the CPS sync up meeting and concluded that this pattern is not needed here.
=> Remove execution context suppression

src/Microsoft.VisualStudio.Editors/PropPages/CodeAnalysisPropPage.Designer.vb, src/Microsoft.VisualStudio.Editors/PropPages/CodeAnalysisPropPage.resx, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.cs.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.de.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.es.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.fr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.it.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.ja.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.ko.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.pl.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.ru.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.tr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.zh-Hant.xlf
For some reason, adding it via the designer saved us other accessibility bugs around that combo box (if I added it directly into the resource file, I got this error twice in the Accessibility Insights tool: An onscreen element must not have a null BoundingRectangle property).
Accessibility pass
On whole pane:
On Analysis level combo box:
=> Added accessible name to AnalysisLevelComboBox.

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ExecutableDebugPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ProjectDebugPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf
Fixes [AB#1278242](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1278242)
Without a `Description`, the new Project Properties UI shows a checkbox with no label, which results in an accessibility failure:
> An onscreen element must not have a null BoundingRectangle property.
=> Add description to SQL Debugging property

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/TreatWarningsAsErrorsValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf
Related to #6720.
The C# compiler provides a switch allowing the user to specify whether or not warnings _in general_ should be treated as errors. In addition to that, specific warnings can be treated as errors, or _blocked_ from being treated as errors. In the project file, these settings are stored in the `TreatWarningsAsErrors`, `WarningsAsErrors`, and `WarningsNotAsErrors` properties, respectively.
Currently, the project property pages only expose the first two of these. This change adds support for the third, `WarningsNotAsErrors`.
The first thing to note is that all we have to do to get the new control to show up in the UI *and* to get the property persisted to the right place in the project file is to add a new `StringProperty` element to BuildPropertyPage.xaml. The `Name` …
=> Implement WarningsNotAsErrors in the new property pages

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs
Fixes #6974
Currently, the logic is to construct these subscriptions _only_ when the `TargetFramework` or `TargetFrameworks` properties change.
For a regular .NET project this is fine as that property will be defined, and when it is first observed it will trigger the subscriptions that allow the Dependencies node to function correctly.
For a project type that does not define these properties (i.e. WAP projects) this logic is incorrect.
This fix ensures a `AggregateCrossTargetProjectContext` when the current instance is null.
=> Fix dependency node when no TargetFramework(s) property exists in the project

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerEditorFactory.vb, src/Microsoft.VisualStudio.AppDesigner/Common/Utils.vb
This will fire an event every time we call to create an editor instance. The flag `shouldUseNewEditor` will help us identify when it's being asked to delegate to the new editor.
=> Add telemetry when we call CreateEditorInstance.

src/Microsoft.VisualStudio.Editors/PropPages/CodeAnalysisPropPage.Designer.vb
This change would fix the accessibility bug "The Name property of a focusable element must not be null" in [AzDO#1247585](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1247585), and will not require a localization pass.
=> Add accessible name to AnalysisLevelComboBox

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsChangeTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcher.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectTreeExtensions.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectValueDataSource.cs
1. Prevent NRE if used after dispose. Build started showing these warnings now, although the underlying problem existed for some time.
2. Fix nullable annotation warnings.
=> Fix nullable field access

.gitignore
During a build, WPF creates `_wpftmp.csproj` files in the source tree (not under `obj`). If you query the git repo's status during a build, it can show these as untracked files.
We should never have these in version control. This commit causes them to be ignored.
=> Make git ignore WPF temporary projects

build/import/Packages.targets
This will enable usage of the latest CPS APIs
=> Update CPS references to latest 16.10 SDK

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/ConfiguredProjectLanguageServiceTelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/ConfiguredProjectPackageRestoreTelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/UnconfiguredProjectLanguageServiceTelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/UnconfiguredProjectPackageRestoreTelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/VsTelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/ITelemetryService.cs
As of 16.10, CPS now exposes the UnconfiguredProjectExtensions.GetProjectGuidAsync method, which can be used to get project GUIDs even when the language service and package restore components are being initialized. This PR replaces path hashes with the GUIDs from this newly exposed API.
=> Replace project path hashes with project GUIDs

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/DebuggerTraceListener.cs
[CPS PR 291660](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/291660) converted the TraceUtilities.Source field into a property. The managed project system code now needs to detect this property. This PR also replaces the Assumes.NotNull calls with Assumes.Fail so that a helpful error message is written to the activity log detailing exactly why the managed project system package failed to load successfully. This can be improved once https://github.com/microsoft/vs-validation/issues/78 has been addressed.
=> Search for a Source property instead of field in DebuggerTraceListener

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ApplicationManifestKindValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/PackagePropertyPage/PackageLicenseKindValueProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ApplicationManifestKindValueProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptedProjectProperties/PackagePropertyPage/PackageLicenseKindValueProviderTests.cs
Fixes #7001.
Currently, the drop downs to choose the kind of application manifest (custom, none, or default) and the kind of package license expression (none, expression, or file) are not working properly: when the user chooses picks a different option, the UI resets to the default value almost immediately.
The issue is that these are synthetic properties--they don't have any direct representation in the project, and instead compute their values based on the values of _other_ properties. If those properties don't yet have values, then the next time we retrieve the value of the synthetic property we will get its default. That's what's happening here: the user changes the property, the UI sends that property change and requests an update, it gets the default value back, and resets the UI. …
=> Properly handle changes to synthetic properties

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/IPropertyPageQueryCache.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/ProjectSetUIPropertyValueActionCore.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageByIdDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageProviderState.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageQueryCache.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyProviderState.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/QueryProjectPropertiesContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyByIdProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyFromPropertyPageDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyValueDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyValueFromUIPropertyDataProducer.cs, test.csx, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IPropertyPageQueryCacheFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/ProjectActionProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/PropertyPageDataProducerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/UIPropertyValueDataProducerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/QueryProjectPropertiesContextTests.cs
When retrieving properties through the CPS properties system three pieces of data are needed:
- A configured project (represented by a `ConfiguredProject`) which represents the "world" in which the property retrieval occurs
- A `Rule` describing _which_ properties to retrieve, including metadata about how to retrieve them and how the consumer should interpret them
- A binding context that both identifies the entity that you want to investigate, and the context in which to investigate it. This is represented by an `IProjectPropertiesContext` (which is a somewhat misleading name for reasons I will get to in a moment).
The binding context requires further explanation. Some examples may help. An `IProjectPropertiesContext` may refer to:
- The project as a whole, in which case the properties …
=> Update Project Query API data providers to understand the binding context

src/Microsoft.VisualStudio.ProjectSystem.Managed/Annotations.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs
Adds newer nullability attributes:
- `MemberNotNullAttribute`
- `MemberNotNullWhenAttribute`
Uses them in one class to avoid null forgiveness operation (`!`) via better annotations.
There will be more places we can use these new attributes to tidy and tighten logic.
=> New annotation attributes

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Frameworks/SupportedTargetFrameworksProvider.cs
Related: https://github.com/dotnet/project-system/issues/6989
Related: https://github.com/dotnet/project-system/issues/7025
This changes the display ordering for the target framework dropdown. The order of values provided by CPS is still preserved. This is only a hotfix to do this. The proper solution is in the [second related link](https://github.com/dotnet/project-system/issues/7025). This PR is only until a proper solution is created.
| Before | After
| ----------- | -----------
| ![image](https://user-images.githubusercontent.com/17788297/111219122-de876000-8594-11eb-8278-863c0304c14b.png) | ![image](https://user-images.githubusercontent.com/17788297/111219164-efd06c80-8594-11eb-8a4c-91c0f2afcf2d.png)
| ![image](https://user-images.githubusercontent.com/17788297/111219136-e515d780-8594 …
=> Hotfix for target framework ordering in property pages

build/import/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/CategoryDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/CategoryFromPropertyPageDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/DebugUtilities.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileCategoryDataProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileDataProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileFromProjectDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileTypeDataProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileUIPropertyDataProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/ProjectSetUIPropertyValueActionCore.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageProviderState.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyFromPropertyPageDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfileProjectItemProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfileProjectPropertiesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfilesProjectPropertiesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ExecutableDebugPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ProjectDebugPropertyPage.xaml, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchProfilesProjectItemProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchProfilesProjectPropertiesProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/CategoryDataProducerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/PropertyPageDataProducerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducerTests.cs
Now that the Project Query API has been updated to represent launch profiles, this change implements basic support for querying the launch profiles. This involves the following pieces:
1. Implementing Project Query API data providers that allow us to map from:
1. A project to a set of "launch profile types"--that is, the different kinds of launch profiles (e.g., Project, Executable, IIS, IISExpress, etc.).
2. A project to the actual set of launch profiles--that is, the individual profiles in the launchSettings.json file as exposed through the `ILaunchSettingsProvider` interface.
3. A launch profile to a set of properties
4. A launch profile to a set of categories (for organizing the properties)
2. Implementing an `IProjectPropertiesProvider` that can expose the launch settings to the …
=> Implement basic launch profile support in the Project Query API

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs
Fixes #7036.
We cannot call CheckForInitialized in this method, as this method may be invoked during initialization.
=> Fix invalid state check

docs/repo/property-pages/property-specification.md, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hant.xlf
This ensures that searches in the Project Properties UI for the string "tfm" match these properties.
cc @terrajobst who pointed out that searching for TFM returned no results during a meeting earlier today.
=> Add "TFM" search term metadata

docs/repo/property-pages/property-specification.md, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml
Historically in legacy projects, the _Assembly Name_ and _Default Namespace_ properties were manually kept in sync with the project by the user.
With SDK-style projects, it's more common to go with the default behaviour of picking up the `MSBuildProjectName` property, which is computed from the project's file name.
Given these properties are far less likely to be user edited, we move them further down the UI, allowing more commonly modified properties to rise to the top.
| Before | After |
|-|-|
| ![image](https://user-images.githubusercontent.com/350947/112084021-3862d800-8bdc-11eb-956f-47a83a1413f2.png) | ![image](https://user-images.githubusercontent.com/350947/112084087-4f092f00-8bdc-11eb-8e3f-bc4bf586f6b8.png) |
=> Reorder properties on Application page

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/QueryProjectPropertiesContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchSettingsProvider3.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfileProjectPropertiesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/LaunchSettingsValueProviderBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Unshipped.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/SequentialTaskExecutor.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs
The `LaunchSettingsProvider` allows multiple concurrent changes to a project's launch settings by forcing them into a serialized order (via the `SequentialTaskExecutor`). However, two different changes to the same launch profile or global setting could still stomp over each other as there is no way to read and update these settings as a single operation.
Say operation A and operation B want to update different parts of the same launch profile. They each grab the current state, P0. They then each make their own changes to produce PA and PB, respectively. Then they both call `AddOrUpdateProfileAsync` to apply their changes. This method replaces the entire profile at once, so depending on the order in which the calls are processed we'll either end up with PA (in which case B's changes are …
=> Atomically read and update profiles and global settings

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerEditorFactory.vb
So far the new Project Properties UI has good support for most C# project types. VB (#6935) and F# (#6936) support has not been addressed yet.
This change prevents delegation from the legacy editor to the new editor unless the `CSharp` capability is present. This will be important as we start to roll out by default to more MS internal folks.
=> Only enable the new Project Properties UI for C# projects

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/DebugUtilities.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileFromProjectDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ExecutableDebugPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ProjectDebugPropertyPage.xaml
1. When populating the `Name` property of a launch profile entity we were incorrectly using the "item type" which will always be "LaunchProfile". Here we fix this to return the actual name.
2. I discovered a quirk in the CPS properties system. Basically, if you try to set a property value on a specific item (as opposed to the project) but the `DataSource` used in that operation is not tied to a specific item _type_, the system thinks you are accidentally trying to set the property for all items with that particular name. E.g., you could have a `<None>` item and an `<EmbeddedResource>` item with the same name, and unless the `DataSource` is bound to one or the other the system thinks you're trying to change both. The system blocks the operation by effectively treating the property as …
=> Fix bugs and quirks

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ExportLaunchProfileExtensionValueProviderAttribute.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ExportLaunchProfileExtensionValueProviderScope.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/IGlobalSettingExtensionValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchProfileExtensionValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchProfileExtensionValueProviderMetadata.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfileProjectProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfileProjectPropertiesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfileProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ProjectLaunchProfileExtensionValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Unshipped.txt, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IGlobalSettingExtensionValueProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ILaunchProfileExtensionValueProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ILaunchProfileExtensionValueProviderMetadataFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchProfilesProjectPropertiesProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchProfilesProjectPropertiesTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/ProjectLaunchProfileExtensionValueProviderTests.cs
`ILaunchProfile` has a few pre-defined properties (like ExecutablePath, CommandLineArgs, LaunchBrowser, etc.) but it also supports storage of arbitrary objects via the `ImmutableDictionary<string, object>` accessible via the `OtherSettings` property, and in practice the bulk of the properties we care about are stored there. Separately, `ILaunchSettings.GlobalSettings` is another `ImmutableDictionary<string, object>` storing launch settings that are global (that is, not tied to a particular launch profile).
There are a few operations we need to support:
1. In each case the property value comes in as a `string`, but needs to be stored in the dictionary as an `object`. While we could store it as a `string` by default this would be incorrect in many cases, and so we need a converter for each …
=> Support reading/writing arbitrary values to launch profiles

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
Quite a few calls into `LaunchSettingsProvider.WaitForFirstSnapshot` pass `Timeout.Infinite`. If such a wait is initiated, and the `LaunchSettingsProvider` is disposed, the wait operation would never complete.
This change ensures the `TaskCompletionSource` via which the wait is implemented is cancelled if it hadn't otherwise completed during disposal of the `LaunchSettingsProvider`, ensuring such hangs can not occur.
=> Fix a potential hang in LaunchSettingsProvider

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfileProjectProperties.cs
I had copy-pasted the use of `<c>null</c>` previously, instead of using `<see langword="null"/>`. This fixes those doc comments.
=> Update <c>null</c> to <see langword="null"/>

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ExecutableDebugPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ProjectDebugPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf
Add `VisibilityCondition` metadata to launch profile rule files so that remote-debugging properties are only visible when remote debugging is enabled.
Also removes _"Only applicable when 'Use remote machine' is enabled."_ from the descriptions of these properties, as we can now show the user that, rather than tell them.
=> Use conditional visibility for remote debugging properties

build/ci/official.yml
Indexing of sources in this pipeline needs to be enabled until there is a different process in place that handles this.
=> Enable indexing of sources when publishing symbols

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileByIdDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileDataProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileFromProjectDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/QueryProjectPropertiesContext.cs
The `LaunchProfileFromProjectDataProducer` can take an `UnconfiguredProject` and produce a set of Project Query API entities representing the launch profiles in that project. However, we currently lack a way to map from an entity ID representing a launch profile to the actual entity. This is necessary in order to support actions on launch profiles via the Project Query API, namely, setting the value of a property in a launch profile. The query engine first tries to look up the launch profile based on its ID, and then applies the action.
The code to create and populate the actual `LaunchProfileValue` is needed in both scenarios (project -> launch profiles, and entity ID -> launch profile) and has been extracted into a new `LaunchProfileDataProducer` type.
With this change, the new property …
=> Support looking up a Launch Profile by ID

build/import/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/AddLaunchProfileAction.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/DuplicateLaunchProfileAction.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/LaunchProfileActionBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/LaunchProfileActionProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/RemoveLaunchProfileAction.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/RenameLaunchProfileAction.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/SetLaunchProfilePropertyAction.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/ProjectActionProvider.cs
Handles actions to add, remove, rename, and duplicate launch profiles.
The remaining action to handle is setting a property, but the API for that is in a bit of flux at the moment.
=> Handle actions for launch profiles

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/AbstractReferenceHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/AssemblyReferenceHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/IReferenceCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/PackageReferenceHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/ProjectReferenceHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/ReferenceCleanUpInvoker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/ReferenceCleanupService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/RemoveReferenceCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/SetAttributeCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/UnSetAttributeCommand.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/References/ReferenceCleanupServiceTests.cs
Add the command design pattern for Remove Unused References.
This will enable the user to press ctrl+z, and remove the previous changes to references done in the csproj file.
=> Undo redo reference clean up service

docs/repo/property-pages/property-specification.md, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/OpenLaunchProfilesEditorValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/DebugPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.zh-Hant.xlf
This PR adds a link action that invokes a command in CPS to show the new Launch Profile UI. The link is displayed on the "Debug" page of the new Project Properties UI.
Sibling CPS PR (Internal): https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/310621
=> Add a link to show the new Launch Profile UI

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml
Related: https://github.com/dotnet/project-system/issues/6989
Currently, there is a CPS bug (TODO: create bug and link here) that causes a yellow banner to appear asking for the project to reload when changing `TargetFramework` to `TargetFrameworks` or visa-versa. This would happen as soon as you un/checked the `Target multiple frameworks` checkbox. To avoid this currently (since multi-targeting is a more advanced scenario anyway), the easiest solution is to hide the checkbox. The visibility of the dependent properties still works the same way, based on the `TargetMultipleFrameworks` value, but the user can no longer modify this value in the property pages, since this checkbox is hidden. The code to calculating this value is still ran, and thus will show the proper property, …
=> Hide `Target multiple frameworks` checkbox

docs/repo/dependencies-node.md, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesTreeViewProvider.cs
Fixes #6604
Previously `IProjectTreePropertiesProvider` implementations would only be invoked on _updates_ to tree nodes. With this change, they are invoked on both _creation_ and updates.
This change also improves performance in the common case by avoiding allocating instances of `ProjectTreeCustomizablePropertyContext` and `ReferencesProjectTreeCustomizablePropertyValues` when no relevant `IProjectTreePropertiesProvider` imports exist. Most projects will not have such an import.
Finally, we add a documentation file for the dependencies node, and include an example showing how to customize nodes.
---
This change supports the WAP team who are integrating with the dependencies tree in 16.10.
=> Fix dependency tree node customization via extensions

ProjectSystem.sln
Without these files being registered in the solution, it is considerably more difficult to search their contents, which can make configuring the build and other project aspects more complex than it needs to be.
=> Add miscellaneous files as solution items

tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/ExportedRuleTests.cs
In #6885 we updated the version number we provide to the project system assemblies. However, the new number had only two parts (16.10) while the old number had three (16.8.1). This led us to generate a somewhat malformed assembly name stored in `ThisAssembly.FullName`. For example, we expected:
```
Microsoft.VisualStudio.ProjectSystem.Managed, Version=16.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
```
but actually generated:
```
Microsoft.VisualStudio.ProjectSystem.Managed, Version=16.10.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
```
Note the version has only three parts instead of the usual four.
We utilize the `ThisAssembly.FullName` constant in the `ExportRuleAttribute`, which is used to tag certain XAML `Rule`s that should be embedded in the assembly rather than …
=> Update an Assembly.Load

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesTreeViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/IProjectDependenciesSubTreeProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/DependenciesViewModelFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/IDependenciesViewModelFactory.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/AnalyzerRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/AssemblyRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/ComRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/DependenciesRuleHandlerBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/FrameworkRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/ProjectRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/SdkRuleHandler.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IMockDependenciesViewModelFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectDependenciesSubTreeProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/DependenciesViewModelFactoryTests.cs
Fixes #7089
#7078 fixed a bug that meant exports of `IProjectTreePropertiesProvider` were not being reliably called when nodes were added to the dependencies tree. This interface is not being used in WAP projects to rename the "Projects" node as "Applications".
When the dependencies tree updates itself, it uses the caption to identify the group node to which the update applies. This search was previously using the caption, and if an extension point renamed the node's caption it would not be found, leading to duplicate nodes appearing in the tree.
This fix introduces an internal `IProjectDependenciesSubTreeProvider2` interface via which our rule handlers may specify a `ProjectTreeFlags` value that uniquely identifies the group node. When this implementation is found, it will be used. If it …
=> Fix duplication of group nodes when filtering captions

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml
Fixes #7103
CPS's `ProjectNode` handles VS hierarchy requests on behalf of the project. For several of those hierarchy properties, the value comes from the project evaluation.
In order for CPS to retrieve the evaluated value, the corresponding MSBuild property must be defined in our ConfigurationGeneral.xaml rule file.
This commit adds several missing properties so that CPS can provide the correct value in response to hierarchy queries.
=> Add properties to support CPS VS hierarchy queries

NuGet.config, build/ci/official.yml, build/import/Packages.targets, build/import/Versions.props, build/proj/internal/RestoreIBCMerge.csproj
We are currently using private feeds as workarounds for dev 17. Our current restore feed has a feed specified which doesn't include vssdk-unifiedPIAs. By using this task we can specify which feeds to use in the restore.
=> Restore tools from nuget.config

build/ci/official.yml
Task used to publish symbols fails with `ErrorCode: get_user_name_failed`
=> Fix Publishing Symbols to Artifact Services

docs/repo/property-pages/property-specification.md
Include extra information about adding a XAML file to the project, the root element, data source, categories and so on.
Also moves the examples to the top of the document, as that will likely be a good place to start for many folks.
=> Improve property specification documentation

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/AbstractBuildEventValueProvider.AbstractBuildEventHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/AbstractBuildEventValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/PostBuildEventValueProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/PreBuildEventValueProviderTests.cs
Fixes #5953 
Add build event interception support for unevaluated value. Previously, the interception code for pre/post build event properties only handled requests for the _evaluated_ value of these properties. For the new Project Properties UI we need both the evaluated _and_ unevaluated values.
Also previously, requests for the evaluated property value were actually returning the unevaluated property value.
Document use of properties/tasks for pre/post build events.
Adds entries to the Build page for events.
Produces:
```xml
<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
<Exec Command="echo &quot;Pre-build&quot; &#xD;&#xA;echo &quot;Configuration: $(Configuration)&quot;" />
</Target>
<Target Name="PostBuild" AfterTargets="PostBuildEvent">
<Exec Command="echo …
```
=> Add pre/post build events to the Build page

docs/repo/property-pages/property-specification.md
Adds documentation for the capability added in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/317111.
=> Document the use of monospace fonts in multi-line string editors

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/StartupObjectsEnumProvider.cs
Fixes: [AB#1280068](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1280068)
Combines the select statements and makes them aware of possible null `entryPoints`, which is likely the cause of this failure.
=> Select statement failure in StartupObjectEnumGenerator

Directory.Build.props
This produces a `ref` folder (e.g. `bin/Debug/ref/Project.dll`) that contains the surface API of the project. Other projects which reference that assembly may avoid rebuilding themselves when the referenced project's surface area did not change, even if its internals did. This can help prevent cascading project builds when simple changes are made at low levels in the dependency graph.
=> Use `ProduceReferenceAssembly` for faster incremental builds

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/TreatWarningsAsErrorsValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf
These changes were reverted in https://github.com/dotnet/project-system/pull/7091. That was done because it was thought to be the cause of the insertion failure from the other week. We found it these changes were not the culprit. So, this is to un-revert (reintroduce) the changes from https://github.com/dotnet/project-system/pull/7053.
=> Unreverting changes from https://github.com/dotnet/project-system/pull/7053

docs/repo/property-pages/visibility-conditions.md, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/DebugPropertyPage.xaml
This uses the new `has-project-capability` conditional visibility function, introduced in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/317749.
We hide:
- properties related to launch profiles when the `LaunchProfile` project capability is absent, and
- the `GeneratedDocumentationFile` property when the `GeneratedDocumentationFile` project capability is absent.
---
This should not be merged until the corresponding CPS PR has inserted.
=> Hide some properties based on project capabilities

build/import/Packages.targets, build/import/Versions.props, tests/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/DependencyNodeIntegrationTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Resources/ResourceTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactoryTests.cs
Updating to latest available packages which allow us to enable tests again. We still need to use private feeds so builds are expected to fail but internal users can validate using [this build](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4682651&view=results).
Additionally one test is still failing due to workarounds that are still in place for breaking changes. These will be addressed in the next PR but I'm merging this to unblock partners.
=> Update to latest PIAs and re-enable tests

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/DebugTypeValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf
Relates to #6720
Adds a drop down list with options that controls how debug symbols are omitted.
There are currently no good docs on the `DebugType` variable to link to. I've left a TODO to come back to that, as we should do a pass to review all the help links before GA.
=> Add the DebugType property to control debug symbol generation

NuGet.config, build.cmd, build/ci/official.yml, build/import/Packages.targets, build/import/Versions.props, src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPageUserControlBase.vb, src/Microsoft.VisualStudio.Editors/MyApplication/MyApplicationProperties.vb, src/Microsoft.VisualStudio.Editors/PropPages/WPF/ApplicationPropPageVBWPF.vb, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VsProject_VsLangProjectProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IOleAsyncServiceProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/ComponentComposition.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/ComponentVerificationTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactoryTests.cs
I'm now consuming the proper packages from the correct feeds. Things still missing:
- Re-enable warningsaserrors once we get an update on Microsoft.VisualStudio.ProjectSystem.Query since the only type of warning now looks as such: 
`CSC : warning CS1762: A reference was created to embedded interop assembly 'Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' because of an indirect reference to that assembly created by assembly 'Microsoft.VisualStudio.ProjectSystem.Query, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Consider changing the 'Embed Interop Types' property on either assembly. [G:\project-system\tests\Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests\Microsoft.VisualStudio.Project …
=> All packages are finally consumed from public feeds

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/DebugPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.zh-Hant.xlf
Helps with #7133
As launch profiles have moved to a dedicated UI, users attempting to search for these terms in the Project Properties UI would not previously have seen a match. This commit adds some keywords which will direct the user to the new Launch Profiles UI when they search.
=> Add search terms for launch profile properties

build/import/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducer.cs
Relates to #7035
The `UIProperty.IsReadOnly` property was recently added to CPS's project model. We extend our data provider to include this data.
=> Populate UIProperty.IsReadOnly

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Log.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.TimestampCache.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
General performance work on the fast up-to-date check. Breaks down into the following categories:
1. Use `ImmutableArray` over `ImmutableHashSet`.
In several places the in-memory state of the up-to-date check used the immutable hash set, which internally stores its data as a binary tree. This tree structure introduces two pointers per element, which requires a lot of additional memory. **This is especially the case for 64-bit VS.** Items in the tree may also be scattered through memory, creating extra work for the GC and losing the benefits of locality of reference. This PR converts to array storage instead, meaning items are packed closely together into less overall memory. Our usage does not include "contains" or other set-based operations, so there is no algorithmic degredation here, …
=> Fast up-to-date check performance

build/ci/official.yml
Reverts dotnet/project-system#7164 and opens #7163 
There's more work needed than just changing the queue
=> Revert "Use Scale Set pools for Build Pipelines"

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs
Current implementation gets the command line arguments from from the rules and this changes the order of the arguments which causes Build to behave differently.
When using the _WarningsNotAsErrors_ feature from Intellisense some errors and warnings were showed as warnings in the Error List, but as errors in the Output window.
We can get the correct order of command line arguments by subscribing to `ProjectBuildSnapshotService`, and then parse the output result from the build target, but since the structure implies iterating over all the elements, extract the arguments, and also changes some interfaces we are  not using this approach, unless we want to preserve ALL the arguments in the same order.
A simple change is to change move _warnaserror+_ to the end of the command line arguments to …
=> Move warnaserror+ to the end of the command line arguments.

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IApplyChangesToWorkspaceContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IApplyChangesToWorkspaceContextFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectBuildSnapshotFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectBuildSnapshotServiceFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContextTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextHostInstanceTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextHostTests.cs
What are the changes:
Get the command line arguments from IProjectBuildSnapshotService instead of IProjectSubscriptionService.
Subscribe to the ProjectBuildSnapshotService directly using the build targets, instead of rules.
What is the bug:
Getting the data from the rules changes the order of the commands which causes the Build to behave differently.
How this change fixes the bug:
Get the original order from ProjectBuildSnapshotService and pass it directly to roslyn.
=> Keep the order of command line arguments for build.

setup/ProjectSystemSetup/Properties/launchSettings.json
Add a launch profile that turns off NGEN images but _doesn't_ include native debugging.
=> Add a launch profile

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/StartupObjectsEnumProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1320092.
The property pages for executables include a "Startup object" property where you can specify which `Main` method or `Form` to run at startup. In both the old and new UI, the drop down displays all applicable methods and forms. The old UI includes a "(Not set)" item representing the empty value; however, the new UI does not. If you set it to one of the other options there is no way to unset it.
The old UI gets the values for the drop down from the `StartupObjectsEnumProvider`, but then explicitly adds in the "(Not set)" value in the UI code. Since the new UI is generated, this option isn't available to us. Instead, we need `StartupObjectsEnumProvider` to include "(Not set)" along with all the other values, but only when …
=> Fix "Startup object" UI

build/import/Versions.props
change to version 17.0.1 on Preview 2 packages. This will make it easier in identifying packages for our partners
=> Add a version differentiator for P1 and P2 packages

build/import/HostAgnostic.props
=> Make XliffTasks and RoslynTools.SignTool have PrivateAssets=all

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IOleAsyncServiceProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactoryTests.cs
Restores back to using `QueryServiceAsync` as we did before the merged interop work. This will correctly get the service from the guid
=> Correctly use IAsyncServiceProvider after merged interop work

src/Microsoft.VisualStudio.AppDesigner/Common/ShellUtil.vb, src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPageUserControlBase.vb, src/Microsoft.VisualStudio.Editors/Common/CodeModelUtils.vb, src/Microsoft.VisualStudio.Editors/Common/DTEUtils.vb, src/Microsoft.VisualStudio.Editors/Common/ShellUtil.vb, src/Microsoft.VisualStudio.Editors/DesignerFramework/BaseDesignerLoader.vb, src/Microsoft.VisualStudio.Editors/MyApplication/MyApplicationCodeGenerator.vb, src/Microsoft.VisualStudio.Editors/MyApplication/MyApplicationProperties.vb, src/Microsoft.VisualStudio.Editors/MyExtensibility/MyExtensibilityProjectSettings.vb, src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPageBase.vb, src/Microsoft.VisualStudio.Editors/PropPages/WPF/ApplicationPropPageVBWPF.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/Resource.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorRootDesigner.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourcesFolderService.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResxItemWizard.vb, src/Microsoft.VisualStudio.Editors/SettingsDesigner/ProjectUtils.vb, src/Microsoft.VisualStudio.Editors/SettingsGlobalObject/SettingsGlobalObjectProvider.vb
While the Dev17 interop work was ongoing we needed to make some adjustments to the VB code to make progress, notably referring to some interop methods and properties with different names and making use of `Option Strict Off`. Now that the interop work has settled a bit these are no longer needed and should be backed out.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1327354/.
=> Fix up VB code

docs/repo/property-pages/property-specification.md, docs/repo/property-pages/visibility-conditions.md, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ExecutableDebugPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/PackagePropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ProjectDebugPropertyPage.xaml
Fixes #7021
Currently we have a visibility condition function `evaluated` which returns a single evaluated value for a property.
However a project may produce different evaluated values per configuration. Currently, if that happens, the `evaluated` function throws an exception.
We also have an `has-evaluated-value` function which returns true if any of the evaluated value matches an argument. This will never throw the above exception.
The original idea was that we would use `evaluated` for properties which self-identify as non-configurable (and therefore would only have a single value).
The problem is that a project can still be manually constructed that produces different values across configurations for any property. If we use `evaluated` then there will always be a "valid" project that …
=> Remove usage of the 'evaluated' visibility condition function

.gitignore
These files are created during build, and should never be committed to the repository. Add them to the .gitignore file so they will not be.
We had previously added temporary WPF csproj files.
=> Ignore temporary WPF vbproj files

src/Microsoft.VisualStudio.AppDesigner/Common/Utils.vb
Telemetry property/event names are converted to lower case during publishing. By using a string which is not already lowercase, we trigger allocation of new strings.
=> Telemetry property/event names in lower case

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerEditorFactory.vb, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.CSharp.DesignTime.targets
Fixes #7171
In Dev16 we only enabled the new UI if a feature flag was enabled.
In Dev17 we will only support this new UI, so no longer need to check the feature flag. The flag will be removed once this change inserts.
=> Use new Project Properties UI by default in Dev17
