- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Designers/Input/AbstractProjectCommand.cs
> Assert when ProjectCommand's aren't marked with [ProjectCommandAttribute]

- src/Microsoft.VisualStudio.Editors/Resources/Microsoft.VisualStudio.Editors.Designer.Designer.vb
- src/Microsoft.VisualStudio.Editors/Resources/Microsoft.VisualStudio.Editors.Designer.resx
- src/Microsoft.VisualStudio.Editors/SettingsDesigner/DesignTimeSettings.vb
Fixes: https://github.com/dotnet/roslyn/issues/10985.
> Initial setting "name" in the Settings Designer should be localized

- src/ProjectSystemSetup/AssemblyRedirects.cs
- src/ProjectSystemSetup/ProjectSystemSetup.csproj
- src/ProjectSystemSetup/ProvideBindingRedirectionAttribute.cs
- src/ProjectSystemSetup/project.json
This enables us to F5 and override binaries in VS install enabling us to test AppDesigner and Editors.
> Add code base binding redirects for the project system binaries

- src/Microsoft.VisualStudio.Editors/AddImportsDialogs/AddImportDialogBase.vb
- src/Microsoft.VisualStudio.Editors/ComponentModel/AbstractControlTypeDescriptionProvider.vb
- src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj
- src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.resx
- src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.vb
- src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPageBase.vb
Tweaked the layout of the build property page:
- Aligned all labels horizontally with controls, removed 3 "design pixels" prefix that each label had
- Aligned "Generate serialization assembly" label vertically with its control
- Changed gaps between controls to match standard spaces (6 "design pixels" vertically between related controls)
To do this, I needed to do a few things first:
1. Added DependentUpon to the RESX so that they group under their controls
2. Needed to add the ability to design "abstract" controls via AbstractControlTypeDescriptionProvider
3. Needed to upgrade Form/resx from "2.0" -> "4.0"
Each of these are in their own commit if you're interested in the details (the churn for 3 is quite great).
> Tweaked the build property page layout

- src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPageUserControlBase.vb
- src/Microsoft.VisualStudio.Editors/PropPages/AdvancedServicesDialog.vb
- src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPage.vb
- src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPageBase.vb
- src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPageVBBase.vb
- src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPageVBWinForms.vb
- src/Microsoft.VisualStudio.Editors/PropPages/AssemblyInfoPropPage.vb
- src/Microsoft.VisualStudio.Editors/PropPages/BuildEventCommandLineDialog.vb
- src/Microsoft.VisualStudio.Editors/PropPages/BuildEventCommandLineDialogService.vb
- src/Microsoft.VisualStudio.Editors/PropPages/BuildEventsPropPage.vb
- src/Microsoft.VisualStudio.Editors/PropPages/CompilePropPage2.vb
- src/Microsoft.VisualStudio.Editors/PropPages/DebugPropPage.vb
- src/Microsoft.VisualStudio.Editors/PropPages/PropPage.vb
- src/Microsoft.VisualStudio.Editors/PropPages/ReferencePathsPropPage.vb
- src/Microsoft.VisualStudio.Editors/PropPages/ReferencePropPage.vb
- src/Microsoft.VisualStudio.Editors/PropPages/SKUMatrix.vb
- src/Microsoft.VisualStudio.Editors/PropPages/ServiceReferenceComponent.vb
- src/Microsoft.VisualStudio.Editors/PropPages/ServicesAuthenticationForm.vb
- src/Microsoft.VisualStudio.Editors/PropPages/ServicesPropPage.vb
- src/Microsoft.VisualStudio.Editors/PropPages/ServicesPropPageConfigHelper.vb
- src/Microsoft.VisualStudio.Editors/PropPages/TargetFrameworkMoniker.vb
- src/Microsoft.VisualStudio.Editors/PropPages/UnusedReferencePropPage.vb
- src/Microsoft.VisualStudio.Editors/PropPages/VBDescriptionAttribute.vb
- src/Microsoft.VisualStudio.Editors/PropPages/VBDisplayNameAttribute.vb
- src/Microsoft.VisualStudio.Editors/PropPages/WebReferenceComponent.vb
Format the property pages code to correct casing, remove line continuation chars, etc so that VS stops doing it when we change them.
> Format property pages

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests/ProjectSystem/PropertiesFolderProjectTreePropertiesProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests/ProjectSystem/ProjectTreeParserTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeParser/ProjectTreeFormatError.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeParser/ProjectTreeParser.MutableProjectTree.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeParser/ProjectTreeParser.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeWriter.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreeWriterOptions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AbstractSpecialItemProjectTreePropertiesProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.UnitTests/ProjectSystem/MyProjectFolderProjectTreePropertiesProviderTests.cs
Fixes the expanded icon for AppDesigner folder ("My Project", "Properties") to match csproj/msvbprj.
This involved changing the ProjectTreeWriter/ProjectTreeParser to write/parse Icon and ExpandedIcon.
> AppDesigner folders have the wrong expanded icon

- src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.vb
Something that has annoyed me to no end.
> Stop upper casing XML doc extension in Build property page

- src/Microsoft.VisualStudio.AppDesigner/Common/Utils.vb
We're going to silently watson these: https://github.com/dotnet/roslyn/issues/11229.
While these null refs are "leaking" - they are immediately swallowed, while I completely hate the pattern of swallowing exceptions, at least the current model shows an "Error Page" with the exception. We'll end up watsoning when we've implemented the issue above.
> Stop treating NullReferenceException as unrecoverable

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Input/ProjectCommandAttribute.cs
Double-clicking the Properties folder/right-click -> Open no longer opened the AppDesigner.
CPS made a contract break for the IAsyncCommandGroupHandler's metadata where Group changed from a string to a GUID. This caused CPS to no longer see OpenProjectDesignerOnDefaultActionCommand or OpenProjectDesignerCommand.
> Fixed can't "open" Properties folder

- src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj
- src/Microsoft.VisualStudio.Editors/PropPages/DebugPropPage.vb
- src/Microsoft.VisualStudio.Editors/PropPages/TextBoxWithWorkaroundForAutoCompleteAppend.vb
Fixes: https://github.com/dotnet/roslyn/issues/7894.
This is a workaround until the WinForms/Shell bug (filed internally) is fixed.
> Fixes CTRL + A clears text boxes

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/LanguageServices/CSharpLanguageServiceHost.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/LanguageServices/VisualBasicLanguageServiceHost.cs
The contract changed for AutoLoad components from `void Initialize` -> `Task Initialize`: https://github.com/Microsoft/VSProjectSystem/pull/127.
Make note VB source files are still ending up in misc workspace -need to figure out what's going wrong.
> Fixed: language service host wasn't being initialized

- build.cmd
1. Use `bin` folder for binaries as projects.
2. Use `VS150COMNTOOLS` environment variable for developer command prompt script location.
3. Fix typo.
> Improve build script

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests/ProjectSystem/PropertiesFolderProjectTreePropertiesProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/ProjectSystem/ProjectTreePropertiesProviderExtensions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ProjectRootImageProjectTreeModifierTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AbstractAppDesignerFolderProjectTreePropertiesProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.UnitTests/ProjectSystem/MyProjectFolderProjectTreePropertiesProviderTests.cs
Fixes: https://github.com/dotnet/roslyn-project-system/issues/163.
We already had tests for this, but due to the way we produce test "IProjectTree", we were comparing the wrong thing. Our ProjectTreeParser returns "Mutable" project tree instances - so when our properties provider was mutating the tree it was changing the original tree and we were asserting that the same tree matched the same tree.
Started to look at making these test trees fully immutable - but it's a non-trivial effort, with lots of surface area, as you basically have to fix up children and parents. Just ended up cloning the tree before passing it down to the properties provider.
> Do not treat folder as AppDesigner folder if not part of the project

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests/ProjectSystem/PropertiesFolderProjectTreePropertiesProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IUnconfiguredProjectCommonServicesFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UnconfiguredProjectCommonServicesTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IUnconfiguredProjectVsServicesFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/UnconfiguredProjectVsServicesTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IUnconfiguredProjectVsServices.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/AbstractLanguageServiceHost.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/ProjectDesignerService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UnconfiguredProjectVsServices.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IUnconfiguredProjectCommonServices.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UnconfiguredProjectCommonServices.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.UnitTests/ProjectSystem/MyProjectFolderProjectTreePropertiesProviderTests.cs
This gives access to the current project, so you don't need to import it and this service.
I also added "Vs" to the IVsUnconfiguredProjectVsService properties to distinguish them.
> Add IUnconfiguredProjectCommonServices.Project

- src/Microsoft.VisualStudio.AppDesigner/DesignerFramework/BaseDialog.vb
BaseDialog was overriding GetService in design mode, which the designer uses to pull services from the Form's site. Which would cause the designer to deadlock and fail to open the designer.
Call the base if in the designer.
> Enable dialogs drived from BaseDialog to open in designer

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Imaging/CSharpProjectImageProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Imaging/CSharpProjectImageProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectCapabilitiesServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ProjectRootImageProjectTreeModifierTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectCapabilitiesService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Imaging/ProjectImageKey.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapabilitiesService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectRootImageProjectTreePropertiesProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests/ProjectSystem/VS/Imaging/VisualBasicProjectImageProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/Imaging/VisualBasicProjectImageProvider.cs
We were setting shared project icons to C#/VB project icons, instead of the shared project icons - only to be overridden again by CPS. Moved CPS's logic for setting the C#/VB icons to us and will remove theirs in #170.
> Set shared project icons

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests/ProjectSystem/PropertiesFolderProjectTreePropertiesProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AbstractAppDesignerFolderProjectTreePropertiesProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/AppDesigner.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/AppDesigner.xaml.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.UnitTests/ProjectSystem/MyProjectFolderProjectTreePropertiesProviderTests.cs
This was going to be a large change, but decided to split it up into a more manageable chuck. This moves the AppDesigner Folder property into it's own rule file so that it can be consumed outside of the other properties (for when AppDesigner becomes it's own capability). There will be a few another properties that will be added to this in a future change.
> Moved AppDesigner folder in own rule file.

- src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/DesignerTabControlRenderer.vb
This isn't used since they moved to IVsUIShell5.
> Remove dead code

- src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/SpecialFileCustomView.Designer.vb
- src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/SpecialFileCustomView.resx
- src/Microsoft.VisualStudio.AppDesigner/PropPages/VSThemedLinkLabel.vb
- Changed Link labels in AppDesigner to follow correct theme colors
- Stop fullscreening link label for resources/settings (this prevents mouse over on the link label from occurring as soon as it enters the property page)
- Stop always showing focus cues unless it's actually got focus via the keyboard
> Link labels to follow theme colors

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/ManagedDebuggerImageTypeServiceTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/GlobalSuppressions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ManagedDebuggerImageTypeService.cs
CPS already adds the pause if it knows you are a console application, implement the required interface to tell them we are.
This brings in line the project system with vslangproj.
Fixes #138
> Add implicit pause to console window on CTRL+F5

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/GlobalSuppressions.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/CSharpProjectGuidProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/GlobalSuppressions.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/VisualBasicProjectGuidProvider.cs
Opt'd C# and VB into legacy project's Add Item template guid and project type guid, so that correct C#/VB templates show up. Also opt'd them into returning their legacy equivalent of project type guid, so that other features start showing up because they think we're legacy C#/VB projects.
> Add Item now shows correct C#/VB templates

- build/Nuget/Microsoft.VisualStudio.ProjectSystem.VSInsertionNuget.proj
- build/build.proj
- Stopped logging so much during build, now we only output the actual output, similar to other projects
- Fixed NuGet up-to-date check so that it actually works and stops rebuilding the package even though nothing has changed. Make note - we added all the assembloes, pdb, xml, etc outputs as a input so that we rebuild in that case.
- Fixed clean so that it only deletes what it actually created
> Make NuGet packaging play nicely with build

- build.cmd
Added a check for the VSSDK to build.cmd. This avoids a bunch of meaningless errors in the build.
> Added check for VSSDK to build.cmd

- src/Dependencies/VisualStudio/project.json
Fixes #276
TraceSource package injects a reference into the build, which conflicts with the reference that the NuGet build task injects, this causes the NuGet build task to remove the reference, causing VS to fail to resolve the reference and complain.
Prevent Telemetry and hence TraceSource from injecting build targets.
> Prevent TraceSource package from injecting reference

- src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPageUserControlBase.vb
- src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPage.vb
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/OutputTypeEnumProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/OutputTypeEnumProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
- src/ProjectSystem.sln
The output type value for class libraries is "Library" and not "dll" as the CPS XAML files defines it. Also I had the enum values wrong which caused the wrong values to get selected in the OutputType combobox of the app property page.
> Fix the output type enum values for class libraries

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/ManagedDebuggerImageTypeServiceTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ManagedDebuggerImageTypeService.cs
Fixes a small class-cast issue with the debug run. This fixes #279.
> Fixes a class cast issue that was causing CTRL+F5 to not work. Addresses #279.

- build.cmd
This change helps us give detailed msbuild log in the file logger and there is no change to the console logger
Taggin @dotnet/project-system for quick review
> Increase the verbosity of msbuild for file logger

- src/ProjectSystemSetup/ProjectSystemSetup.csproj
- src/VisualStudioEditorsSetup/VisualStudioEditorsSetup.csproj
Setting this value makes the binary references for the vsix to be picked from
Output rather than Obj
Tagging @dotnet/project-system for review
> Make Vsix references to Copy local

- src/Targets/Microsoft.CSharp.DesignTime.targets
- src/Targets/Microsoft.VisualBasic.DesignTime.targets
Update design time targets to look in the current folder for XAML files by default.
Using this approach to unblock us for next preview. Later we need to move the XAML files into language specific folders to support localization (#128)
> Update design time targets

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectPropertiesFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/ApplicationManifestValueProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/ImplicitProjectPropertiesProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptedProjectProperties/AssemblyOriginatorKeyFileValueProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptedProjectProperties/InterceptedProjectPropertiesProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationManifestValueProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/InterceptedProjectProperties.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
The application manifest is backed by two MSBuild properties. This change adds an intercepting property provider that maps back and forth from the MSBuild properties. 
> Add ApplicationManifest property to the application page

- src/ProjectSystemDogfoodSetup/ProjectSystemDogfoodSetup.csproj
- src/ProjectSystemDogfoodSetup/VisualStudio/Packaging/DogfoodProjectSystemPackage.DebuggerTraceListener.cs
- src/ProjectSystemDogfoodSetup/VisualStudio/Packaging/DogfoodProjectSystemPackage.cs
- src/ProjectSystemDogfoodSetup/source.extension.vsixmanifest
Register a CPS trace listener that listens to CPS events and writes them to the Debugger output.
Make note this is currently blocked on a PR to the CPS code base where I've turned on TRACE for their assemblies.
> Register a CPS trace listener

- build/Targets/VSL.Imports.targets
This is a temporary fix to enable us to continue building in Microbuild
This is becoming a constant issue. I will look into other ways so that we dont depend on the version number. I think Roslyn does it but it is a little complicated.
Tagging @srivatsn @davkean for review
> Update Microbuild version

- build/Targets/ProducesNoOutput.Imports.targets
- build/Targets/ProducesNoOutput.Settings.targets
- build/Targets/References.targets
- src/Dependencies/Json.net/Json.net.csproj
- src/Dependencies/Json.net/project.json
- src/ProjectSystem.sln
Small check in which adds a dependency on Json.Net  8.0.3. Also fixes the incremental compilation problem.
@abpiskunov @davkean
> Add json.net dependency, fix incremental build

- src/Targets/Microsoft.Managed.DesignTime.targets
Also fix an issue with the path to the rules having an extra newline that causes the rules to not get loaded.
> Enable seamless reload and globbing capabilities

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/ImplicitProjectPropertiesProvider.cs
This fixes the ImplicitProjectPropertiesProvider to use one instance of the caching dictionary across all ImplictProjectProperties instances. This fixes a bug where the ProjectGuid would get set by the VS in one instance of ImplicitProjectProperties, but any future property access that got a new ImplicitProjectProperties wouldn't see that value. This fixes #392.
> ImplicitProjectPropertiesProvider Fix

- build/Targets/Settings.targets
- build/Targets/VSL.Imports.targets
SDK imports have moved from C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK to [VSInstallDir]MSBuild\Microsoft\VisualStudio\v15.0\VSSDK. They have redirect logic that redirects causes them to look in both locations for imports. We were skipping that logic based on setting/using VSToolsPath. 
Directly use the MSBuildExtensionPath32 property so that the redirect kicks in. Also, need to check if the targets exist due to NuGet restore not respecting that same logic: https://github.com/NuGet/Home/issues/3387.
After this change, today's build should work from the command-line.
> Enable repro to build with new installer

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AnalyzerDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AssemblyDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/ComDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesChange.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProjectContextProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/PackageAnalyzerAssemblyDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/PackageAssemblyDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/PackageDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/PackageFrameworkAssembliesDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/PackageUnknownDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/ProjectDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SdkDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SharedProjectDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SubTreeRootDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UI/RelayCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/IJsonSection.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ICreateFileFromTemplateService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ExportInterceptingPropertyValueProviderAttribute.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/IInterceptingPropertyValueProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/IInterceptingPropertyValueProviderMetadata.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/StringExtensions.cs
We are going to create NuGet packages for the project system dlls and so we need to make sure the public APIs are really meant to be public. I've flipped a bunch of stuff to be internal in this PR. The only APIs that are public now are:
@BillHiebert @abpiskunov  does this sound like the right set?
> Hide a bunch of APIs that arent intended to be public

- netci.groovy
Once the tests and infrastructure are working fine, we can switch them to run for every pr commit.
Cloned and edited from https://github.com/dotnet/roslyn-internal/blob/master/netci.groovy#L143
> Add new VSI job to trigger VSI netcore tao integration tests on explicit request.

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/ImplicitProjectPropertiesProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/ImplicitProjectPropertiesProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/ImplicitProjectPropertiesStore.cs
The ImplicitProjectPropertiesProvider sits at the configured project level. However, the project guid is set once per UnconfiguredProject. When a different configuration was used from the initial default configuration, this guid wasn't being retained. This introduced a store that sits at the UnconfiguredProject level that the ImplicitProjectPropertiesProvider imports, sharing properties like the project guid among all configured projects. This fixes #392 when switching build configurations, and should fully fix it.
> Added an ImplicitProjectPropertiesStore to sit at the UnconfiguredProject level

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/Packaging/CSharpProjectSystemPackage.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/VSPackage.resx
This fixes the XProj Migration factory showing up in the new project dialog. Addresses #466.
Tagging @dotnet/project-system for review.
> Removed the name and default path elements from XProj factory registration

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/IInterceptingPropertyValueProviderMetadata.cs
As the title says. IInterceptingPropertyValueProviderMetadata needs to be public so TypeBuilder can get at it for MEF importing. Part of the fix for #470.
@srivatsn @davkean
> Made IInterceptingPropertyValueProviderMetadata public to fix #470

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/ImplicitProjectPropertiesProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/ImplicitProjectPropertiesProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/ImplicitProjectPropertiesStore.cs
`ProjectSystemContractAttribute` doesn't actually do anything in terms of determining what scope a component lives at. Reverted the addition of it to go back to importing an `UnconfiguredProject`. Actually fixes #470.
> Fix implicit project properties store

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/ImplicitProjectPropertiesProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ProjectFileInterceptedProjectPropertiesProvider.cs
- Fix "there is no project properties provider for 'ImplictProjectFile'
- ProjectFileWithInterception should only be applied to C# and VB
> Implicit project file

- build/Targets/VSL.Imports.targets
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectDependenciesSubTreeProviderMock.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProjectContextProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesSubTreeProviderBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/IDependenciesGraphProjectContext.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/IDependenciesGraphProjectContextProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/IProjectDependenciesSubTreeProvider.cs
- use ProjectCapability for GraphProvider (assuming everyone is on WPT now)
- use generic EventHandler #454 
- hide more APIs
> Minor fixes: use ProjectCapability for graph provider;hide more public interfaces;use generic EventHandler

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchSettingsProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettings.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.Designer.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.resx
Added a few methods to the LaunchSettingsProvider which allows web projects (and others ) to add or update the existing set of profiles. This is needed so that web projects can add an IIS Express profile and provide the additional settings needed by it.
@srivatsn
> Add methods to allow updating profiles prgrammatically

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/ProjectLockFileWatcherTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectLockFileWatcher.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml
For project with PackageReferences, restore3 will generate a project.assets.json file in the obj directory. Update the lockfilewatcher to look for that if it doesn't find a project.json.
@dotnet/project-system @natidea
> Change ProjectLockFileWatcher to look for project.assets.json as well.

- src/Targets/Microsoft.CSharp.DesignTime.targets
- src/Targets/Microsoft.VisualBasic.DesignTime.targets
This doesn't matter mostly because it's not called in the outer build but when restore fails or in some other weird cases, I see an error in the IDE about the Compile target missing. Either way it's a safe change to say don't run this during the outer build. 
@dotnet/project-system @nguerrera
> Ensure that the design time targets only run in the inner build

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ConfiguredProjectFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectFaultHandlerServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectServicesFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IUnconfiguredProjectFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Build/TargetFrameworkGlobalBuildPropertyProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/TargetFrameworkGlobalBuildPropertyProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configurations/TargetFrameworkProjectConfigurationDimensionProvider.cs
Ensure that for cross targeting projects we clear out the "TargetFramework" global property during explict builds in VS so that we build for all configurations. We do so by implementing a build-only properties provider that checks if the project configuration specifies "TargetFramework" as a dimension or not, and clear out the TargetFramework property if the dimension exists.
Fixes #504
> Cross targeting: Projects build all TFMs from VS

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Xproj/MigrateXprojProjectFactoryTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/Packaging/CSharpProjectSystemPackage.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/MigrateXprojProjectFactory.cs
This fixes the flaky tests that were removed from yesterdays commit by properly disposing of file system objects, thanks @tannergooding. This also adds more tests for the rest of the migration functionality.
Tagging @dotnet/project-system @srivatsn for review.
> XProj Migration Testing

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProviderTests.cs
Skip flaky test which has reached my threshold of flakiness.
tag @dotnet/project-system @abpiskunov
> Skip flaky DependenciesGraphProvider_GetChildrenAsync test

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Xproj/MigrateXprojProjectFactoryTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/MigrateXprojProjectFactory.cs
The cli dropped the `-p` arg in favor of it being the default argument. This updates that.
Tagging @dotnet/project-system @srivatsn @brthor for review.
> Updated xproj migration factory args to match changes to the cli

- src/VsixV3/EditorsPackage/Microsoft.VisualStudio.Editors.swr
Reverts dotnet/roslyn-project-system#546
Looks like we can't depend on MinShell without changing some validation logic in microBuild itself
> Revert "Add dependency on MinShell"

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/Mocks/ProcessRunnerFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Xproj/MigrateXprojProjectFactoryTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/MigrateXprojProjectFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/ProcessRunner.cs
Package restore isn't needed during migration, so we skip first time setup to save a bunch of time and fix #548. First time setup appears to hang when not running as a shell host.
Tagging @dotnet/project-system @srivatsn for review, /cc @livarcocc.
> Skip first time setup during migration

- src/Targets/Microsoft.CSharp.DesignTime.targets
- src/Targets/Microsoft.VisualBasic.DesignTime.targets
IsCrossTargeting is only defined in the outer build as true and is empty in the inner build. The condition was incorrect. Fixing this causing intellisense to come back again
> Fix design time build.

- src/VsixV3/EditorsPackage/Microsoft.VisualStudio.Editors.swr
- src/VsixV3/EditorsPackage/Microsoft.VisualStudio.Editors.vsmanproj
- src/VsixV3/ProjectSystemPackage/Microsoft.VisualStudio.ProjectSystem.Managed.swr
- src/VsixV3/ProjectSystemPackage/Microsoft.VisualStudio.ProjectSystem.Managed.vsmanproj
Add dependency on MinShell and disable package validation as MinShell doesn't exist in the repository.
Without this dependency VSIXInstaller may not be around on uninstall, causing it to fail
> Add dependency on MinShell

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ProjectContextCodeModelProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ILanguageServiceHost.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs
Fixes #480 
Tests are blocked by the InternalsVisibleTo support that I added a few weeks ago and will add them in: https://github.com/dotnet/roslyn-project-system/issues/483
> Add CodeModel support for language service

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectThreadingServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectPropertiesFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/DteFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDteServicesFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IServiceProviderFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IUnconfiguredProjectVsServicesFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/ProjectFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/SolutionFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/CreateFileFromTemplateServiceTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/DteServicesTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/CreateFileFromTemplateService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/DteServices.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IDteServices.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/Interop/VsHierarchyExtensions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml
- src/Targets/Microsoft.CSharp.DesignTime.targets
- src/Targets/Microsoft.VisualBasic.DesignTime.targets
Instead of hardcoding C#/VB for the template language based on the CodeModel object - we now read this from design-time targets.
tag @srivatsn @dotnet/project-system
> Read TemplateLanguage from design-time targets 

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/CommandLineItemHandler.cs
This should fix the issue where we are not correctly setting the options.
[SplitCommandLineIntoArguments](http://source.roslyn.io/#Microsoft.CodeAnalysis/CommandLine/CommonCommandLineParser.cs,691) splits arguments based on whitespace characters.
> Fix command line item handler to use whitespace to concatenate arguments

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/References/AlwaysAllowValidProjectReferenceCheckerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/References/AlwaysAllowValidProjectReferenceChecker.cs
We're moving to a model where p2p references are validated by MSBuild in builds and design-time builds. Stop validating them in VS.
tag @dotnet/project-system @nguerrera
> Stop validating p2p references

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/FileRenameTracker.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Renamer.cs
Fixed a leak and a few other changes, dig into each commit for more context if you want to see why I made the change.
Avoid leaking a Renamer when renaming non-source files 
Path.GetExtension doesn't return null for paths 
Avoid unnecessary transition to the UI thread
Remove unneeded async state machine
Remove defensive coding against possible CPS bugs  …
> Avoid leaking a Renamer when renaming non-source files

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Properties/CSharpProjectGuidProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/CSharpProjectGuidProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests/ProjectSystem/VS/VisualBasicProjectGuidProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/VisualBasicProjectGuidProvider.cs
- src/Targets/Microsoft.CSharp.DesignTime.targets
- src/Targets/Microsoft.VisualBasic.DesignTime.targets
CPS reads AddItemTemplatesGuid from the design-time targets in ProjectNode if there's no implementation of IAddItemTemplatesGuidProvider. Move it there similar to other properties to reduce number of C#/VB components.
Verified that both Add Item dialog correctly showed the right templates.
> Read AddItemTemplatesGuid from design-time targets

- build.cmd
- build/build.proj
Latest SWIX plugin doesn't support building them with the same msbuild command.
> Split building v2 and v3 VSIXes into separate commands

- src/Microsoft.VisualStudio.AppDesigner/Common/Utils.vb
- src/Microsoft.VisualStudio.Editors/Common/Utils.vb
- src/Microsoft.VisualStudio.Editors/DesignerFramework/BaseDesignerLoader.vb
- src/Microsoft.VisualStudio.Editors/ResourceEditor/Resource.vb
- src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceListView.vb
1. Follow the naming conventions for post fault entity name
2. Remove crash reporting at places where we are generating 10,000+ AI events, we are actually handling the exception and passing it back up to the callers, so these are not too useful.
Fixes VSO [278184](https://devdiv.visualstudio.com/DevDiv/_workitems/index?_a=edit&id=278184&triage=true)
> Telemetry fault logging fixes

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/NuGet/ProjectRestoreInfoBuilderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/NuGetRestorer.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectRestoreInfoBuilder.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml
TargetFramework property is absent from Dimension Provider in non-cross targeting projects.
Add TargetFramework property to configuration general rules and use when target framework dimension is absent.
/cc @dotnet/project-system 
/cc @MattGertz for Ask Mode Approval
/cc  @alpaix @rrelyea @emgarten for Fyi
> Use TargetFramework Property in Nominate Restore when it is missing from Dimension Provider

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/DotNetCliToolReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PackageReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ProjectReference.xaml
This is needed for NuGet to correctly restore PackageReference\ProjectReference items that have these attribute.
@dotnet/project-system @natidea 
@MattGertz for ask mode approval.
/cc @alpaix @rrelyea @emgarten for Fyi
> Add some metadata that PackageReference\ProjectReference items can have  

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx
Fix the way we launch the application to get the run information from the SDK properties. Addresses issue https://github.com/dotnet/roslyn-project-system/issues/423
@srivatsn @abpiskunov 
Also Fixes https://github.com/dotnet/roslyn-project-system/issues/589
> https://github.com/dotnet/roslyn-project-system/issues/423

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
Fixes #655
@BillHiebert @jinujoseph 
The debug properties page is setting the `commandName` in `launchSettings.json` to `Executable`, while the `ConsoleDebugTargetsProvider` wasn't coded to expect that.
> Fix launching debugger when Launch type is set to Executable

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/Packaging/CSharpProjectSystemPackage.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/DplOptOutRegistrationAttribute.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/Packaging/VisualBasicProjectSystemPackage.cs
Deferred Project Load is yet to support globbing so we are opting .Net Core Projects out of DPL.
@srivatsn @dotnet/project-system for review
> Opt .Net Core Projects out of DPL

- build/Targets/Settings.targets
- build/Targets/VSL.Imports.targets
- build/Targets/VSL.Versions.targets
- src/Dependencies/Toolset.Previous/Toolset.Previous.csproj
- src/Dependencies/Toolset.Previous/project.json
- src/Dependencies/Toolset/project.json
- src/ProjectSystem.sln
- src/ProjectSystemDogfoodSetup/source.extension.vsixmanifest
- src/ProjectSystemSetup/source.extension.vsixmanifest
- src/VisualStudioEditorsSetup/source.extension.vsixmanifest
- Instead of using the VSSDK on the machine, use the NuGet packages.
- Building using RC packages fails on a Preview5 machine because it's still not cleanly separated out. Use a hack (that Roslyn put in today as well) to identify RC and switch packages based on that.
- Add Prerequisites section so that it builds with the RC package.
- Remove an errant BuildNumber property that broke local build versioning of 42.42.42.42
@dotnet/project-system @mavasani @333fred @RaulPerez1
> Switch to building the repo with VSSDK NuGet packages.

- build/Targets/VSL.Versions.targets
Tagging @dotnet/project-system @srivatsn @mavasani for review. I'm not sure if this needs @MattGertz's approval, since this is a local-build-only change, but I'll tag anyway just in case. This fixes the local build to use the 42.42.42.42 version number for produced VSIX's, ensuring F5 works as expected.
> Fixed local builds to use the 42.42.42.42 version number.

- src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorDesignerLoader.vb
Settings mtSvr to Nothing causes the Access Level combobox to be disabled, but a full fix will require changes that won't make the RC bar. ResX code-behind is successfully generated on save. We can also change the access level by manually setting the SingleFileGenerator for the file to be the PublicResXFileCodeGenerator. Follow up work to fix MultiTargetService is tracked by #686.
> Temporary fix for #419

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/LanguageServices/CSharpVsContainedLanguageComponentsFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/AbstractHostObject.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ConfiguredProjectHostObject.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ProjectHostProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/UnconfiguredProjectHostObject.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactoryBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IProjectHostProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/UnconfiguredProjectContextProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/LanguageServices/VisualBasicVsContainedLanguageComponentsFactory.cs
1. Return active intellisense project host object from VsContainedLanguageComponentsFactoryBase.GetContainedLanguageFactoryForFile.
2. AbstractHostObject implements IVsProject and delegates to the inner hierarchy for all implementations - Roslyn `ContainedDocument` assumes that the host object implements this interface.
Fixes #677
> Fix razor intellisense that broke after combined intellisense support

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectTreeProviderFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/ProjectLockFileWatcherTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectLockFileWatcher.cs
Making a COM call in the MEF constructor can potentially cause deadlocks. At the very least it can perf problems by blocking background initialization.
@dotnet/project-system @lifengl
> Don't initialize the file watcher in the MEF constructor.

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependenciesSubTreeProviderBaseTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependencyNodeIdTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependencyNodeTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/NuGetDependenciesSubTreeProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/ProjectDependenciesSubTreeProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AnalyzerDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AssemblyDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/ComDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesSubTreeProviderBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyNodeId.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyNodeResolvedStateComparer.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/IDependencyNodeExtensions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/NuGetDependenciesSubTreeProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/PackageAnalyzerAssemblyDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/PackageAssemblyDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/PackageDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/PackageFrameworkAssembliesDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/PackageUnknownDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/ProjectDependenciesSubTreeProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/ProjectDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SdkDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ProjectReference.xaml
#We had to revert my changes over the weekend to review and complete a PR properly. Undoing a "revert" commit 79f0fadc10c44f7e2157ab711e8c9c8f972c4971..  This was original PR https://github.com/dotnet/roslyn-project-system/pull/671 
Fixes #663, Fixes #412, Fixes #431 and Fixes #635
> Undo revert of dependencies bug fixes to complete PR

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/NuGetRestorer.cs
To block the build while a restore operation is happening.
Fixes #654: A deadlock can occur if the user builds while a restore operation is happening
Requires change from NuGet
/cc @alpaix @dotnet/project-system @rrelyea 
/cc @MattGertz
> Register Nominate Restore as a Critical Project System Task

- src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneralFile.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneralFile.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Content.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Content.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/DebuggerGeneral.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/DebuggerGeneral.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/EmbeddedResource.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/EmbeddedResource.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Folder.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Folder.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/SourceControl.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/SourceControl.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/SpecialFolder.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/SpecialFolder.xaml
- src/Targets/Microsoft.Managed.DesignTime.targets
Project Guids get stamped into the project. Many property pages show up disabled. Many other features that depend on getting project properties are broken. The reason is that because of a change in order of files being imported, our CPS rules for project properties weren't getting imported.
Fixes #681, Fixes #676 
Users have to hand edit the target files which is risky
This change is creating a replica of all the common xaml rules in Roslyn Project System. So minimal risk.
None
Yes
A recent change that we made to change the order of importing targets files in MSBuild caused this regression. We need integration tests to catch these issues.
Ad hoc testing
@srivatsn @333fred @jinujoseph @dotnet/project-system for review
> Override common xaml rules in Project System

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/Packaging/CSharpProjectSystemPackage.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/VSPackage.resx
When a user attempts to open an xproj directly, they cannot see it (if using VS->Open Project), or get an error (if they use any other method).
#691
The user can open the solution file instead of opening the project file. However, we think this is a core scenario that should work correctly, and there is no way to open the project file directly without modifying the registry manually.
This is low risk. It's just affecting the generated pkgdef for the xproj type, no other project types are affected.
Very low. The only change is that instead of parsing through 65 (as of this PR) types of projects, initial load will have to parse through 66.
Not a regression.
This was found by internal adhoc testing.
Tagging @dotnet/project-system.
> Fixed migration to allow opening a .xproj directly

- netci.groovy
This changes the ci only archive results when the build fails or is aborted. Tagging @dotnet/roslyn-infrastructure @mavasani for review. /cc @dotnet/project-system. @MattGertz, this is a CI-only change. Do you need a full escrow write-up and a bug?
> Only archive on failure/abort

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Xproj/MigrateXprojProjectFactoryTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/MigrateXprojProjectFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx
When a user opens a solution with multiple .xproj projects in it, they expect all to migrate successfully. Currently, they might not, depending on ordering.
#703.
The user can migrate from the command line instead of using VS and manually edit their .sln file, but this is a very bad experience.
This is low risk. It's only affecting migration code paths, which only run the first time an xproj is opened.
Negligible. This simply adds another flag to the call to dotnet migrate.
Yes.
This was caused when dotnet/cli added the backup feature, which deletes the original `project.json`, causing issues later on as we migrate project-by-project. Integration tests are needed to ensure that the cli command keeps working.
This was found by @jinujoseph as part of build validation.
Tagging …
> Added --skip-backup to migration calls.

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs
This is the same as #713 but against master
> Switch LoadedProject to LoadedProjectAsync to avoid a deadlock

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Reload/ReloadableProject.cs
Prevent corrupting the users project in the event of DeepCopyFrom throwing. We do this by testing DeepCopyFrom on a temp project, so that if it does throw we will not have touched the users project yet. This is a slight performance hit, but this code is not run often and it is much more preferable than the alternative of several error dialogs being shown. In the event it does throw the user will be prompted to reload the project.
DeepCopyFrom _shouldn't_ throw and if it does it is a bug on MSBuild. However, there is currently an issue with it always throwing if there is any metadata as an attribute in the project. Microsoft/msbuild#1319
> Handle failure in DeepCopyFrom when reloading project

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IFileSystemMock.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/AbstractEditProjectFileCommandTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Editor/EditProjectFileCleanupFrameNotifyListener.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/AbstractEditProjectFileCommand.cs
This fixes #704. Old structure:
`%TEMP%\tmp.1234.csproj`
New structure:
`%TEMP%\tmp.1234\ConsoleApp1.csproj`.
Tagging @dotnet/project-system @jinujoseph for review.
> Project file temp is now put in a temp folder, named correctly. 

- src/Targets/Microsoft.CSharp.DesignTime.targets
- src/Targets/Microsoft.VisualBasic.DesignTime.targets
Reverts dotnet/roslyn-project-system#727. This is apparently unnecessary, as #606 no longer repros.
> Revert "Use the shared project AddItemTemplatesGuid for shared projects."

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs
> Removing the UseSpecificRuntime option from debug properties page

- netci.groovy
With this change, the Jenkins machines will be moved to RC build. VSIX project will have to go through a fix to build on RC, without which any other PR Jenkins build will fail. The fix will be checked-in as soon as this change gets in.
@srivatsn @dotnet/project-system for review
> Move the jenkins machine to RC

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs
fixes #657   & fixes #656 
IISExpress is not supported so taking that out of the condition too.
@dsplaisted
> Preserving the Executable path field in debug properties page.

- netci.groovy
* relativeTargetDir moves to "extensions node" and is renamed
* credentials node now has proper id rather than randomly generated string
> Fix two breaking changes in server move [To be merged Thursday Night]

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Folder.xaml
It looks like the Folder rule was updated in the MSBuild location after we forked. Update it in the project system so that folders show properties.
@dotnet/project-system @adrianvmsft
Fixes #751
> Update folder rule from the msbuild copy so that properties work

- README.md
I noticed the badge was a broken link. This fixes it to point to the new ci. @dotnet/project-system, /cc @dotnet/roslyn-infrastructure. 
skip ci
> Fixed the readme badge

- build/Targets/Settings.targets
- src/Dependencies/Toolset/project.json
- src/ProjectSystemSetup/source.extension.vsixmanifest
- src/VisualStudioEditorsSetup/source.extension.vsixmanifest
- src/VsixV3/EditorsPackage/Microsoft.VisualStudio.Editors.vsmanproj
- src/VsixV3/ProjectSystemPackage/Microsoft.VisualStudio.ProjectSystem.Managed.vsmanproj
The VSSDK that we were consuming so far produced a V3 packageid using the ID of the VSIX which is a guid. The VS authoring however uses human readable names. The latest RC VSSDK lets us specify a human-readable packageid. Updating to that version.
@dotnet/project-system @basoundr
> Updating Vsix manifests to include a PackageId

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/NuGet/ProjectRestoreInfoBuilderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/NuGetRestorer.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectRestoreInfoBuilder.cs
Refresh active configuration when TargetFramework(s) changes so that subscriptions are properly reset; do not nominate restore during intermediate states when targetframework is unavailable following a change from TF to TFs.
Fixes #750 
> Fix Auto Restore when Changes are made to TargetFramework(s)

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml
Changed casing of debug property page labels to match Windows/VS sentence case guidelines.
> Change casing of debug property page labels

- src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPage.resx
- src/Microsoft.VisualStudio.Editors/PropPages/CSharpApplicationPropPage.resx
- src/Microsoft.VisualStudio.Editors/PropPages/ReferencePropPage.resx
Application page was setting the Font multiple times, causing WinForms to scale the page multiple times, to bad effects. Stop doing that across all pages.
This is one that I noticed and figured out the cause while I was investigating the Debug property page scaling issue.
Before: 
After:
> Fix Application page layout under high DPI

- build/Targets/GenerateAssemblyInfo.targets
Our signed builds are currently blocked by following category of errors:
`2016-11-22T22:35:48.6280082Z obj\Release\GeneratedAssemblyInfo_2.0.0.2016112201.cs(17,59): error CS7035: The specified version string does not conform to the recommended format - major.minor.build.revision [E:\A\_work\1\s\src\Dependencies\Composition\Composition.csproj]`
Unblocking the build by suppressing this error and also starting a discussion with VS setup team to figure out if the build version number really matters, and if so what is the recommended value for it.
> Fix signed build by suppressing CS7035/BC42366

- src/Microsoft.VisualStudio.Editors/PropPages/DebugPropPage.vb
The Debug property page was manually scaling the MaximumSize and MinimumSize properties - yet these are automatically scaled by the WinForms layout engine. This was resulting in the Debug property page in being forced into either too large or too size than normal.
I suspect this is the root cause of #427, but been unable to actually get VS in a state where it will down scale the property pages enough to repro. It looks like to do this would require a combination of a smaller Icon font size (which VS uses for its font) plus a smaller DPI than 96 (something Win10 no longer lets you do). This requires more investigation and plan on finding a machine in this state.
Here's an example of up scaling (this is on a Surface book where it's screen is Primary set to 200%, and opening VS on the …
> Stop double scaling MaximumSize/MinimumSize

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsProjectFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/CreateFileFromTemplateServiceTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/CreateFileFromTemplateService.cs
We weren't setting cFilesToOpen when calling AddItemWithSpecific, causing CPS to end up getting passed an empty array from the shell.
This takes Fred's change from here: https://github.com/dotnet/roslyn-project-system/pull/768 and partially fixes: https://github.com/dotnet/roslyn-project-system/issues/576 when the Properties folder already exists.
> Fix project fault when adding a resource

- src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPageInternalBase.vb
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
@srivatsn @davkean @dotnet/project-system
> Hide the targetframework selection option for projects which have multiple targetframeworks defined.

- netci.groovy
Also move forward the roslyn-internal LKG commit against which our tests are executed.
Similar to roslyn-internal commit: https://github.com/dotnet/roslyn-internal/commit/faee0bb6389989b6811eb95ff1a71d82954b763c
> Move project-system VSI jobs to no longer use static machines 

- netci.groovy
See https://github.com/dotnet/roslyn-internal/blob/master/netci.groovy#L163 for reference.
> Update BuildAndTest.cmd args for VSI runs to match roslyn-internal

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/NuGet/ProjectRestoreInfoBuilderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/VsItemList.cs
NuGet was causing us to throw two first-chance exceptions on startup - move to a non-throwing path. Not KeyedCollection doesn't have TryGetValue yet (it's coming soon), so needed to define our own.
> Stop throwing first-chance exceptions on startup

- netci.groovy
1. Enlist into SDK repo and install templates to RoslynDev hive
2. Patch all the MSBuild xaml and targets files from the current roslyn-project-system commit into VS install dirs.
> Changes to netci.groovy for VSI tests

- src/Microsoft.VisualStudio.Editors/PropPages/TargetFrameworkMoniker.vb
fixes #869 
Already reviewed at #863
**Escrow Template:**
Customer scenario – Properties page missing .net core app 1.1 from the list of options.
Bugs this fixes: #869
Workarounds - none
Risk – Low.
Performance impact - None.
Is this a regression? - No
Root cause analysis - The option was missed out from the list of options provided.
How was the bug found? - Internal testing.
@MattGertz for RC.2 Approval
> Adding .netcoreapp1.1 to the list of tfms

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
I turned Visibility to False to address #389 , which hides the property from the browse object but CPS doesn't handle the changes to those properties due to a different descriptor being fired. Till we find a better fix, reverting the change to address #841, #814 
@srivatsn @davkean 
**Escrow Template:**
Customer scenario – Edit to the property pages are not persisted.
Bugs this fixes: #841, #814 
Workarounds - none
Risk – Low.
Performance impact - None.
Is this a regression? - Yes
Root cause analysis - Turning the visibility to false to hide from browser object , triggers different descriptor which CPS needs to handle. This is reverting the changes i did #775
How was the bug found? - Internal testing.
@MattGertz  for RC.2 Approval
> Reverting the change to turn BrowseObject Visibility to false.

- netci.groovy
Sync roslyn-internal upfront as we use the VsixExpInstaller from roslyn-internal repo to install VSIXes built from SDK repo into RoslynDev
> Update netci.groovy for VSI tests

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ConfiguredProjectFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PropertyPages/BuildMacroInfoTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/BuildMacroInfo.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPage.cs
Fixes the Visual Studio crash when the user tries to edit pre/post build events. Note that they still can't be edited (changes aren't saved) due to #857
Escrow Template:
Customer scenario – Visual Studio crashes when the user tries clicking edit Pre/Post build events. 
Bugs this fixes: #405 
Workarounds - N/A
Risk – Low. This implements a COM interface (IVsBuildMacro) for the IVsHierarchy object for the project
Performance impact - None. This only executes when the hierarchy is casted to the interface  which only happens for the scenario above.
Is this a regression? - From the old project system.
Root cause analysis - The old project system implemented this interface on the IVsHierarchy object and that hadn't been implemented in the new project system.
How was the bug found? - N/A
> Fix build events crash

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectItemProviderFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractSpecialFileProvider.cs
Without the fix, we were always assuming that the Root node's file path is the folder containing the project file but the root node is actually the project file. Hence, when constructing the file path for new files, check if the filepath for the node, which is used for calculating the path, is a folder or a file and extract the folder path appropriately.
@dotnet/project-system @srivatsn for review
This change will fix the [Bug 286604:Adding Settings file crashes VS](https://devdiv.visualstudio.com/DevDiv/_workitems?id=286604&triage=true&_a=edit) but the issue #572 will be there.
> Construct a path with just the folder name of the project root filepath

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectLockFileWatcher.cs
As diagnosed by @lifengl, an ObjectDisposedException can happen when the project is unloading while the forked task in `ProjectLockFileWatcher.FilesChanged` is running.
Put forked notify project change task into a LoadedProjectAsync() context 
Fixes [#296591](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/296591)
**Customer scenario** – A Watson is reported when project is unloaded while project system is responding to changes in project assets file (e.g. soon after a restore.) NOTE: I have not been able to repro this manually.
**Bugs this fixes**:  [#296591](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/296591)
**Workarounds** - N/A
**Risk** – Low
**Fix** - We wrap the FileChanged handler in a LoadedProjectAsync context as recommended by CPS team, and further wrap that …
> Fix Watson crash caused by project unload while ProjectLockFileWatcher.FilesChanged is running

- build.cmd
- netci.groovy
- src/ProjectSystemDogfoodSetup/ProjectSystemDogfoodSetup.csproj
- src/ProjectSystemSetup/ProjectSystemSetup.csproj
- src/VisualStudioEditorsSetup/VisualStudioEditorsSetup.csproj
With the new VSSDK bits, build fails when we build the solution with deploy extension set to true in Jenkins. This change will help us pass Jenkins. Once this VSSDK issue gets fixed, we can remove this flag.
@dotnet/project-system @jinujoseph @mavasani @srivatsn for review
> This change introduces a flag to not deploy extension during build. Default behavior will be true.

- src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceListView.vb
Fixes #877
If the user has never shown the image thumbnails, the Resource Editor crashes Visual Studio when changing themes.
> Fix crash when changing theme in resource editor

- src/VisualStudioEditorsSetup/VisualStudioEditorsSetup.csproj
- src/VisualStudioEditorsSetup/source.extension.vsixmanifest
VSSDK is no longer using the Ngen Action to Ngen the binaries. This is the new recommended way to ngen the binaries
@mavasani @tannergooding @dotnet/project-system for review
> Ngen the editor binaries

- src/Microsoft.VisualStudio.ProjectSystem.CSharp/ProjectSystem/SpecialFileProviders/CSharpAssemblyInfoSpecialFileProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractSpecialFileProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AppConfigFileSpecialFileProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/ResourcesFileSpecialFileProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/SettingsFileSpecialFileProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic/ProjectSystem/SpecialFileProviders/BasicAssemblyInfoSpecialFileProvider.cs
We never diff the filename/template based on the special file - so turn methods -> properties. I suspect this was done to original differ between C#/VB, however, now we have separate components for those.
> Simplify special file/template name lookup

- netci.groovy
These are only triggered on explicit request. Note that the VSI jobs are currently broken due to us requiring to move to RC2 for building the project system repo with VSIX deployment.
> Add VSI PR jobs in Jenkins

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs
Internal bug #262666. This introduces a basic string parsing state machine, which does not quote any characters that are inside a quoted string. Tagging @BillHiebert @dotnet/project-system for review.
Tagging @MattGertz for ask mode approval.
> Fixed launching when the containing path contains a ^ or &.

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectDebuggerProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectDebuggerProvider.cs
Addresses https://github.com/dotnet/roslyn-project-system/issues/740
@srivatsn @abpiskunov
> Fix for ProjectDebuggerProvider.QueryDebugTargetsAsync should wait for first snapshot

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ICreateFileFromTemplateServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/CreateFileFromTemplateServiceTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/CreateFileFromTemplateService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ICreateFileFromTemplateService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractSpecialFileProvider.cs
In preparation for retrieving app designer folder from a special file handler (in a future change), which returns a path, we now take a "parentDocumentMoniker" instead of a IProjectTree to CreateFileFromTemplateService to avoid having to look up in the tree multiple times.
> Change CreateFileTemplateService to take document moniker

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IFileSystemMock.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/EditProjectFileCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/FileSystem.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/IFileSystem.cs
We were calling through Path.GetTempFileName which creates a zero byte file on disk, only to delete it so that it was suitable for a directory name.
tag @dotnet/project-system @333fred
> Stop creating zero byte files to get temp dir name

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/AppDesignerFolderProjectTreePropertiesProviderTests.cs
This was resulting in a warning while running tests.
> Remove duplicate test case

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ICreateFileFromTemplateServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IFileSystemFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectItemProviderFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/DataFlowExtensionMethodWrapperMock.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IActiveConfiguredProjectSubscriptionServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDebugLaunchProviderFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDebugLaunchProviderMetadataViewFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectValueDataSourceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsAddProjectItemDlgFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsStartupProjectsListServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/RegistrationContextFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/CreateFileFromTemplateServiceTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/DebugTests/StartupProjectRegistrarTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/DteServicesTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Generators/GeneratorExtensionRegistrationAttributeTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Generators/RemoteCodeGenerationRegistrationAttributeTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/AbstractAddClassProjectCommandTests.cs
Move mocks from "Mocks" namespace to the same namespace as the thing they are mocking. It makes it *much* easier to find them when writing new tests.
tag @dotnet/project-system
> Move mocks from "Mocks" namespace

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Xproj/MigrateXprojProjectFactoryTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/Packaging/CSharpProjectSystemPackage.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/MigrateXprojProjectFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp/ProjectSystem/SpecialFileProviders/CSharpAssemblyInfoSpecialFileProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IFileSystemFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IFileSystemMock.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Editor/MsBuildModelWatcherTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/EditProjectFileCommandTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Editor/EditProjectFileVsFrameEvents.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Editor/MsBuildModelWatcher.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/EditProjectFileCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/FileSystem.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/IFileSystem.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/Win32FileSystem.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractSpecialFileProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AppConfigFileSpecialFileProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/ResourcesFileSpecialFileProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/SettingsFileSpecialFileProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic/ProjectSystem/SpecialFileProviders/BasicAssemblyInfoSpecialFileProvider.cs
- Move IFileSystem/FileSystem -> Microsoft.VisualStudio.IO namespace  …
- Utilities has become a grab bag of everything - it's not a great namespace name, and something we avoided using on the BCL.
- Updated doc comments for FileSystem/IFileSystem
- Rename "FileSystem" -> "Win32FileSystem"  …
- This better describes it's implementation.
> Move IFileSystem/FileSystem

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/NuGetRestorer.cs
Introduce Code Marker that is fired when project restore completes for Performance tests
Fixes #590
WIP: Currently validating if this approach works
> Introduce Code Marker that is fired when project restore completes

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/MigrateXprojProjectFactory.cs
This prevents a console window from popping up during every migration, which can be very annoying when migrating a large solution. Tagging @dotnet/project-system for review.
> Stop showing the console window during migration

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
Fixes #895 in conjunction with https://github.com/dotnet/sdk/pull/511
@nguerrera FYI - There's a new string in the rule
> Add TreatSpecificWarningsAsErrors to the rules

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/GetProfileNameDialog.xaml.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPage.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/WpfBasedPropertyPage.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/ObservableList.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettings.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
We're turning on the naming/code style rules by default (see https://github.com/dotnet/roslyn-project-system/pull/1002), the following fixes the naming issues across the tree.
> Attempt to get clean on naming

- build.cmd
- netci.groovy
- src/ProjectSystemDogfoodSetup/ProjectSystemDogfoodSetup.csproj
- src/ProjectSystemSetup/ProjectSystemSetup.csproj
- src/VisualStudioEditorsSetup/VisualStudioEditorsSetup.csproj
Jenkins machines have been moved over to RC2 which supports deploying extensions while building VSIX projects.
@tannergooding @srivatsn @jinujoseph @mavasani  @dotnet/project-system for review
> Enable Extension deployment in Jenkins build

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PhysicalProjectTreeStorageTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PhysicalProjectTreeStorage.cs
IFolderManager was in the configued scope, which caused IPhysicalProjectTreeStorage and ultimately IPhysicalProjectTree to appear in the configured scope.
> Fix shared boundary violation

- build/build.proj
xUnit was returning 4 when there were test failures, as a result we were calling this a "successful build". Any non-zero exit code from xUnit will now break the build.
> Any error from xUnit should break build

- build.cmd
- netci.groovy
- src/ProjectSystemDogfoodSetup/ProjectSystemDogfoodSetup.csproj
- src/ProjectSystemSetup/ProjectSystemSetup.csproj
- src/VisualStudioEditorsSetup/VisualStudioEditorsSetup.csproj
Reverts dotnet/roslyn-project-system#918. The auto-imaged machines are having licensing issues. @tannergooding is working on it, but until then, deploying extensions will randomly fail. Tagging @dotnet/project-system for review.
> Revert "Enable Extension deployment in Jenkins build"

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependenciesGraphProjectContextProviderFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectDependenciesSubTreeProviderMock.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependencyNodeIdTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/ProjectDependenciesSubTreeProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyNodeId.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/ProjectDependenciesSubTreeProvider.cs
There were several issues with Project nodes hierarchy:
- when A -> B and B is several levels above A, like ..\..\..\b.csproj, progression code cut node id string when converted it toUri.LocalPath. We need to Escape . with some other symbol (*) to avoid that.
- other issue is we need to use Project B dependency providers when querying hierarchy nodes under project A Dependencies to show hierarchy correctly: A -> B (and B has packages specific to B) . Before we used providers from project A and they did not know about nodes specific to B and worked only when A also had same packages as B.
> Bug fixes for Project nodes hierarchy

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs
With code styles on by default, these were now starting to show in the Error List.
Interestingly enough these weren't found originally when I fixed https://github.com/dotnet/roslyn-project-system/pull/1011.
Still confused about when or how things show up in the Error List.
> Added 'async' to StartupProjectRegistrar async methods

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Reload/ProjectReloadManager.cs
Remove the unnecessary ExecuteSynchronously call which wrapped the async operations.
> Bug 294208 : VS hangs while trying to reload a project in the background

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/EditAndContinue/EditAndContinueProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ExportProjectNodeComServiceAttribute.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Generators/SingleFileGeneratorFactoryAggregator.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/BuildMacroInfo.cs
This simplifies the logic for exporting a ProjectNode service.
Ran into this implementing the new IVsDesignTimeAssemblyResolution service, and pulled it out to simplify the review.
> Add ExportProjectNodeComServiceAttribute

- build/Targets/GenerateAssemblyInfo.targets
- build/Targets/VSL.Versions.targets
Match Roslyn PR https://github.com/dotnet/roslyn/pull/16208 to ensure correct version numbers for 2017.
This also fixes #798.
> Fix our official build version numbers

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/SimpleRenamerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/AbstractRenameStrategy.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/IRenameStrategy.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/SimpleRenameStrategy.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Renamer.cs
fixes #363 , fixes #1063
@davkean @srivatsn @dotnet/project-system
> Don't trigger rename of code element if filename has not been changed.

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsSolutionBuildManager2Factory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsUpdateSolutionEventsFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/AbstractGenerateNuGetPackageCommandTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/GenerateNuGetPackageProjectContextMenuCommandTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/GenerateNuGetPackageTopLevelBuildMenuCommandTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/AbstractGenerateNuGetPackageCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/GenerateNuGetPackageProjectContextMenuCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/GenerateNuGetPackageTopLevelBuildMenuCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/GeneratePackageOnBuildDesignTimeBuildPropertyProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/GeneratePackageOnBuildPropertyProvider.cs
Fixes #998
I verified that "Pack" command kicks off a *real* solution build for the selected project with "GeneratePackageOnBuild" property set to true, and is correctly reset to false at the end. Once NuGet implements https://github.com/NuGet/Home/issues/4145, this command should generate a NuGet package.
> Implement Pack command

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PropertyPages/DebugPageViewModelTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/ExecutableLaunchSettingsUIProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/ProjectLaunchSettingsUIProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.Designer.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.resx
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchSettingsUIProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/IWritableLaunchProfile.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/IWritableLaunchSettings.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfile.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettings.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/WritableLaunchProfile.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/WritableLaunchSettings.cs
The high level design notes are:
1. The list of commands which appear in the Launch dropdown are provided by the set of ILaunchSettingsUIProvider's. There are implementations for Project and executable in the base project system to support Console\ClassLibraries
2. The providers can optionally add Custom UI to the dialog to make it easy to set custom values. This UI appears after the default values. 
3. Default properties can be hidden if they don't apply using the EnableProperty method
4. Sequence
a. Dialog loads the providers to build the dropdown list. If there are commands in the current launch settings for which there isn't a provider installed, the command will be shown when that profile is active, but other profiles can't be converted to it. All fields are disabled and it becomes …
> Supported for extending the debug property pages

- src/Microsoft.VisualStudio.AppDesigner/Microsoft.VisualStudio.AppDesigner.vbproj
- src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj
New package property page showing up nicely:
Also spot checked translation of other pages line up with previous VS versions (for French at least).
@srivatsn @dotnet/project-system 
@jinujoseph This is the change that needs the temporary editors satellite change in VSO undone. Ideally, we could add the insertion of this and my other two loc PRs to that PR and test that PR build in English and Loc.
> Generate satellites for editors vsix

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IGraphContextFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsHiearchyItemFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependencyNodeTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IProjectTreeExtensions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AnalyzerDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AssemblyDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/ComDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/NuGetDependenciesSubTreeProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/PackageDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/ProjectDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SdkDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SharedProjectDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SubTreeRootDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/ManagedPathHelper.cs
- support automation (VSLangProj.References) by switching to IProjectItemTree instead of IProjectTree. This is needed since CPS uses IProjectItemTree nodes with Reference flag to implement VSLangProj.References. (Note: this still would need some matching CPS changes to make sure we work OK for regular references (assemblies and projects) and packages (for packages CPS needs to listen for package xaml rules and add e new reference type). Note: i reuse a Folder xaml type for custom dependency nodes (implemented outside of managed project system), however we might want to create a separate BrowseObject xaml rule "GenericDependency" to be precise and add there standard set of properties.
- organize dependency nodes flags: all generic (implemented by us nodes) will have CPS's Reference flags …
> This change fixes several issues:

- build/Targets/References.targets
- src/Dependencies/VisualStudio/VisualStudio.csproj
- Fix conflict warning around JSON.NET
- MSBuild was outputting a warning around JSON.NET because our VS dependencies had conflicting dependencies on JSON.NET, and it couldn't figure out which one to pick. Force it to version use 8.0, which means that MSBuild will favor it.
- Fix conflict warning around System.dll
- MSBuild was outputting a warning around System because our nuget dependencies had conflicting dependencies on System.dll between portable and full framework, and it couldn't figure out which one to pick. Force our dependencies to reference the core assemblies from the framework, causing them to become primary and win over the portable versions.
Fixes: #892
> Fix build warnings around conflicting versions

- build/Targets/Settings.targets
MSBuild made a change where they started setting BaseIntermediateOutputPath (https://github.com/Microsoft/msbuild/issues/1525) in props instead of targets, this caused us to think that an individual project had set the base intermediate path and respect it. This caused us to output them into the default location (obj in the project directory).
Stop respecting a project's ability to override the intermediate path and hence, not inheriting the one from props - no one was doing it anyway.
> Stop building intermediates building into the source tree

- build/Targets/References.targets
- build/Targets/VSL.Imports.targets
- src/Dependencies/Toolset/Toolset.csproj
After #7a8718d, a warning was introduced in the Error List when opening the ProjectSystem.sln around "System not being able to referenced". This occured due to the way the legacy NuGet build task adds/removes framework assemblies for project.json. It does it during design-time builds which confuses csproj, and results it spitting out a warning. This was occuring to the toolset project only due to the unneeded framework assemblies coming from the analyzers references (https://github.com/dotnet/roslyn-analyzers/issues/1092).
Adding a new dependency type as a workaround of this issue.
> Fix "System cannot be referenced" in Error List

- build/Targets/ProducesNoOutput.Settings.targets
- src/Dependencies/xUnit.net/xUnit.net.csproj
The dependency projects product an output solely to make csproj's up-to-date check happy. Stop deploying them the output directory.
> Stop building unused dependencies dlls to output 

- src/VsixV3/EditorsPackage/Microsoft.VisualStudio.Editors.vsmanproj
- src/VsixV3/ProjectSystemPackage/Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.swixproj
- src/VsixV3/ProjectSystemPackage/Microsoft.VisualStudio.ProjectSystem.Managed.vsmanproj
vsmanproj/swixproj projects were importing ProductsNoOutput for what appears to be just because it's provides an output path. This broke when the output path changed in #ebdfe8a. These projects shouldn't be importing that project - it's for projects that produce no output.
This fixes the current build break.
> Import VSL.Settings.targets instead of ProducesNoOuput.targets/VSL.Version.targets

- build/build.proj
- src/Dependencies/Toolset/project.json
- src/NuGet.config
VSMan projects were limited to only building inside MicroBuild, which lead to issues being caught after things had merged.
This is going to fail until the build break is fixed due to https://github.com/dotnet/roslyn-project-system/pull/1107.
Fixes: #1111
> Always build vsman projects

- src/VisualStudioEditorsSetup/VisualStudioEditorsSetup.csproj
Change the target SatelliteDllsProjectOutputGroup to SatelliteDllsProjectOutputGroupWithFinalOutputPath, which will include the resources from the final output path rather than the intermediate path and hence will include the signed satellite assemblies
All the satellite assemblies wont be signed for the MS.VS.Editors.dll and MS.VS.AppDesigner.dll
either VSO or GitHub links)
[VSO Link](https://devdiv.visualstudio.com/DevDiv/_workitems?_a=edit&id=366133&triage=true)
There are no workarounds
**Risk**
Low risk. This only affects the resources dll
None
The resources dlls are new for the Editors and AppDesigner
VS Sign …
> Add the resources final output path to the VSIX

- build/Targets/References.targets
- src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorDesignerLoader.vb
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/ProjectFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/Reference3Factory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/VSProjectFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/References/DesignTimeAssemblyResolutionTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/DesignTimeAssemblyResolution.ResolvedReference.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/DesignTimeAssemblyResolution.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/Interop/VsHierarchyExtensions.cs
New implementation of IVsDesignTimeAssemblyResolution that overrides CPS's version, it can be accessed via:
- By casting the hierarchy to IVsDesignTimeAssemblyResolution (no one in the tree that I can find uses this, but this is solely to override CPS's version)
- By looking up SVSDesignTimeAssemblyResolution via IVsProject.GetItemContext(any id).
This will enable us (along with a VSTypeResolutionChange and CPS change), enable to resolve the following issues:
#1076
#660
#747
> Adds a new implementation of IVsDesignTimeAssemblyResolution

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ProjectContextCodeModelProvider.cs
Customers get the following dialog when attempting to add a new resource or rename a resource within the Resource Designer:
```
---------------------------
Microsoft Visual Studio
---------------------------
The method or operation is not implemented.
---------------------------
OK   
---------------------------
```
https://github.com/dotnet/roslyn-project-system/issues/752
Click OK on the dialog.
**Risk**
Low
None
No
There were lots of blockers that prevented the Resource Designer from working, now that we started peeling the onion - we're finding more issues.
Ad hoc.
**Dev Notes**
Old legacy project …
> Get a not-implemented popup when you attempt to rename a resource in RESX

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/NuGetRestorer.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PackageReference.xaml
- src/Targets/Microsoft.Managed.DesignTime.targets
This is needed to get https://github.com/dotnet/sdk/pull/633 to work in VS.
See https://github.com/dotnet/sdk/pull/633 for the escrow template.
@davkean @natidea @basoundr @dotnet/project-system
> Restore based on a design time build instead of evaluation to get PackageReferences

- build/Targets/VSL.Versions.targets
Post RC.2 we fixed our versioning to use the correct revision field, but this causes RC.2 version to be treated as higher then our latest version. This causes the VS upgrade from RC.2 to RC.3 to not upgrade our Project System and Editor assemblies. To workaround this, we are bumping up Build portion of the version from 0 to 1.
https://github.com/dotnet/roslyn-project-system/issues/1187
Users need to do a clean install of RC.3 or manually uninstall and install the VSIXes.
**Risk**
Minimal, we are just upgrading the version
None
We didn't test this upgrade path.
Dogfooding
> Bump up the version of our assemblies from 2.0.0.XXX to 2.0.1.XXX

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Editor/MSBuildXmlAccessor.cs
When the user edits the project file in VS, a UTF-16 xml header is added to the file, although there isn't one on disk. When the project is saved, MSBuild will change the format of the file based on this header, so future saves will be UTF-16 instead of UTF-8, causing issues with VCS.
Temporary workaround for https://github.com/dotnet/roslyn-project-system/issues/1168.
Edit the project file with an external editor, not inside VS.
**Risk**
Relatively low. It checks to see if the project file has an XML header, and strips it if it exists. If the user manually put in the header it will strip that as well, so this cannot be the permanent fix.
Minor. We're doing a string comparison on the first 5 …
> Strip the xml header

- build/Targets/VSL.Imports.targets
This is an infrastructure only change. It fixes the ` error MSB3541: Files has invalid value "c:\Users\frsilb\Documents\git\roslyn-project-system\bin\obj\Unused\Debug\\Rules\**\". Illegal characters in path.` issue that many of us were seeing. Tagging @nguerrera @dotnet/project-system for review. /cc @cdmihai.
> Removed extra trailing slash that breaks building on some machines

- src/VsixV3/EditorsPackage/Microsoft.VisualStudio.Editors.vsmanproj
- src/VsixV3/ProjectSystemPackage/Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.swixproj
- src/VsixV3/ProjectSystemPackage/Microsoft.VisualStudio.ProjectSystem.Managed.vsmanproj
Move the setup projects to Framework 4.6 like the rest of the projects. 
The sign build machines did not build because they did not have the targeting pack for 4.0
Install the machine with the required targeting pack
**Risk**
Infrastructure work - No risk
None
Signed build started failing
> Set TargetFramework to 4.6 for the setup Vsix

- src/Dependencies/CPS/CPS.csproj
- src/Dependencies/Immutable/project.json
PR https://github.com/dotnet/roslyn-project-system/pull/1140, upgraded our MSBuild dependency which resulted in 20 build warnings due to us depending on a lower version of System.Collections.Immutable than our dependencies.
> Clean up build warnings

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/AbstractHostObject.cs
Undoing a rename using the file renamer code fix, fails.
#1216 
Partially fixes: https://github.com/dotnet/roslyn/issues/16546
The workaround is for the user to manually undo the changes that the code fix made to the project.
**Risk**
Low.
None.
No
We only started using the code fixes against .NET Core projects.
Customer reported.
**Dev Notes**
Implement IVsProject4 on the hierarchy that we pass to Roslyn so that it can remove items from the project.
> Implement IVsProject4 on AbstractHostObject

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/Reference3Factory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/References/DesignTimeAssemblyResolutionTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/DesignTimeAssemblyResolution.cs
Clicking Publish, opening a project or generally interacting with the project system (such as opening a RESX) with unresolved references shows a dialog stating:
```
The project system has encountered an error.
An internal error occurred. Please contact Microsoft Product Support Services.
```
https://devdiv.visualstudio.com/DevDiv/_workitems?id=368836&_a=edit
https://github.com/dotnet/roslyn-project-system/issues/1223
Fix/remove the unresolved reference. While clicking OK in some situations will result in no behavior change - other situations such as not being able to open a RESX will have no workaround other than fixing the reference[1].
[1] Note: In some situations, which I'm still debugging, certain references …
> Fix assert in DTAR when a project has unresolved assembly

- src/VsixV3/ProjectSystemPackage/Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.swixproj
- src/VsixV3/ProjectSystemPackage/ext.xproj.swr
I've copied the extension registration format from csproj, https://devdiv.visualstudio.com/DevDiv/_git/VS.ref_archive?path=%2Fsrc%2FSetupPackages%2FCoreIde%2FCommunity%2Fres%2FFileAssociations%2Fext.csproj.swr&version=GBmaster&_a=contents, adjusting for the existing icon and present for xproj. Tagging @dotnet/project-system @basoundr for review. /cc @jinujoseph.
When attempting to open an xproj from the file explorer, the file icon is correct, but double-clicking results in a "no program installed" popup.
Fixes https://github.com/dotnet/roslyn-project-system/issues/1143.
Open the solution file, or open from inside VS.
**Risk**
Low. There are no code changes here, only registering a file handler. …
> Added swr registration for .xproj files

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Editor/TempFileTextBufferManager.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs
Currently, we strip whitespace from project files, and don't respect whitespace changes when deciding if the project file editor buffer is up to date. This change reacts to https://mseng.visualstudio.com/DefaultCollection/VSIDEProj/_git/VSIDEProj.CPS/pullrequest/175897, enabling us to preserve all project file formatting.
Fixes https://github.com/dotnet/roslyn-project-system/issues/1094, https://github.com/dotnet/roslyn-project-system/issues/743, https://github.com/dotnet/roslyn-project-system/issues/512. 
Edit with an external editor, and don't use the NuGet UI to add packages.
**Risk**
Very little risk on our side, the main risk is in CPS/MSBuild. 
We actually improve performance with this change, …
> Fully Preserve Project File Formatting

- src/Common/Test/App.config
Tests were failing inside VS due to Immutable mismatch - CPS expects version 1.2, but due to MSBuild dependency we deploy 1.2.1.
Make note this wasn't causing us to fail command-line runs because they run inside the xUnit appdomain (due to xunit.AppDomain == denied) and looks like (according to fuslog) it's failing back to a LoadFrom bind to the exact binding in the directory next to the test when the Load bind fails.
> Add binding redirect for Immutable for tests

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
Fixes #1293
Customers that rename .NETStandard/.NETCore projects subsequently experience Restore and Build breaks until they close the solution.
#1293
https://github.com/NuGet/Home/issues/4287
Close and reopen the solution, or Visual Studio
**Risk**
Low. This fix simply adds another MSBuild property to the list of properties we listen to when choosing to Nominate restore
Low
No
The breaks occur because NuGet has not been nominated to restore following the project name change, hence the new project name is not in NuGet's cache. The NuGet restorer only nominates a restore operation when tracked properties change. This list mostly …
> Add MSBuildProjectFile to NuGetRestore rules

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Xproj/GlobalJsonRemoverTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Xproj/MigrateXprojProjectFactoryTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.csproj
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/GlobalJsonRemover.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/MigrateXprojProjectFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsSolutionFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/ProjectItemFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/SolutionFactory.cs
During migration, we remove the global.json file from the disk, but not from the solution, leaving a broken link.
Fixes final issue in https://github.com/dotnet/roslyn-project-system/issues/1184.
The user can manually delete the file from the solution after migration.
**Risk**
We don't have any downstream dependencies for this.
Low. We add one extra observer for solution state, which runs a quick delete after the migration has been completed and the solution has been fully loaded. We also unsubscribe from events immediately after finishing deletion.
No, known limitation of the new migration features.
MVP/internal testing. …
> Added removing global json from the solution after migration

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
Editing profiles on the debug page can change the active profile, however, the debug drop down does not reflect the change. Thus when they run their application they think that are running say, profile1, when in fact they are running profile 2. 
https://github.com/dotnet/roslyn-project-system/issues/1265
The workaround is to change the selection in the debug dropdown however, it is not obvious that is the problem.
**Risk**
Low.  A simple change to the save function to keep the active profile stable. Only affects saving profiles
None. One or two small comparisons on save.
Regression …
> Property page save bug. Issue 1265

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
Fixes #1132 
.NET core users can version projects that produce packages by doing:
```xml
<PackageVersion>1.2.0</PackageVersion>
```
However, this version information is not currently passed on to parent projects in P2P scenarios. Instead the project is always listed as having version 1.0.0. This ultimately means the version numbers in *.deps.json files will be incorrect. NuGet is working on a fix that requires us to add package verison information to restore nomination.
#1132, Part of Fix for https://github.com/NuGet/Home/issues/3901 
None
**Risk**
Low. This just adds rules with more MSBuild properties that are picked up in a property bag by existing code
None
**Is …
> Add PackageVersion to support NuGet's Project Version compute heuristics

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.Designer.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.resx
Debug properties page is not currently localized.
https://github.com/dotnet/roslyn-project-system/issues/1286
None
**Risk**
Low 
Low
No
Page was copied over from old system. Missed seeing the strings not being localized.
ad hoc testing
> Moving the hardcoded strings from the Debug UI to Resources file

- src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/BuildProperty.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/TurnOffUseHostCompilerIfAvailableBuildPropertiesProvider.cs
.NET Core projects and other CPS-based C#/VB assemblies are always considered out-of-date. This means that we always call C#/VB compiler to output the binary regardless of whether it's up-to-date or not. 
This also has the impact of causing non-CPS based projects to also be considered out-of-date, causing every downstream proejct, and so forth to be rebuilt, increasing builds times and otherwise, making devs sad and unhappy.
NOTE: This does not add/fix the "fast up-to-date check" as called out by feature https://github.com/dotnet/roslyn-project-system/issues/62. We will still continue to shell out to MSBuild, and rely on it being up-to-date.
#825
Devs can set the `$(UseHostCompilerIfAvailable)` property inside their …
> Fix CoreCompile is never up-to-date

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/ExecutableLaunchSettingsUIProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/ProjectLaunchSettingsUIProvider.cs
The project and executable settings show the launch URL checkbox for Console\Classlibary projects. Since the this field is not hooked up internally, it does nothing. Customers will wonder why launch url is enabled yet their browser is not launched.
https://github.com/dotnet/roslyn-project-system/issues/1264
Just ignore the field
**Risk**
Low. Very simple change to hide this field for these providers
None. Just UI updating
No. We shipped previous versions with this enabled. It was an oversight.
Not much adhoc testing of the property pages
Adhoc testing of the web extensions to the property pages
> Remove the Launch URL checkbox from console apps debug page

- build/Targets/Settings.targets
- src/Dependencies/Toolset/project.json
- src/VisualStudioEditorsSetup/VisualStudioEditorsSetup.csproj
On newer builds of VS, our repo is failing to deploy to VS with:
VSSDK1043: There was a problem finding the extension with a VSIX identifier of "F6B5EACA-7FA1-4591-8D40-A38234763621". Value does not fall within the expected range.
Upgrading our build tools version to a build that contains this fix.
> Upgrade build tools to fix deployment on new builds

- build/Targets/References.targets
#450b7a64 removed the Shell.14 reference, this removes the unused alias.
Fixes: #142
> Remove unused Alias of Microsoft.VisualStudio.Shell.14

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/RuleDataSourceTypes.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedAnalyzerReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/cs/ResolvedAnalyzerReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/de/ResolvedAnalyzerReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/es/ResolvedAnalyzerReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/fr/ResolvedAnalyzerReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/it/ResolvedAnalyzerReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ja/ResolvedAnalyzerReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ko/ResolvedAnalyzerReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pl/ResolvedAnalyzerReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pt-BR/ResolvedAnalyzerReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ru/ResolvedAnalyzerReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/tr/ResolvedAnalyzerReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hans/ResolvedAnalyzerReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hant/ResolvedAnalyzerReference.xaml
Properties for top level packages were missing. They were broken by addin DT build for PackageReference xaml rule. Logic in References and Dependencies nodes relied on fact that all unresolved references were not coming from DT build and all resolved did come from DT build. 
Change is to bring all dependency rules to consistent persistence. Now all resolved xaml rules should have persistence ResolvedReference. This would help to differentiate between rules having same ItemType.
https://github.com/dotnet/roslyn-project-system/issues/1258
**Risk**
minimal
> Fix for 1258, return properties for top level packages

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/NuGetRestorer.cs
Customers may experience a hang when closing a .NET Core solution if auto restore is running in the background.
This change was requested by NuGet team as part of their efforts to resolve this hang in https://github.com/NuGet/NuGet.Client/pull/1154. This change passes a CPS cancellation token that is cancelled when a project is unloaded to NuGet's solution restore service, which in turn passes it down to core algorithms.
https://github.com/NuGet/Home/issues/4257
None
**Risk**
Project System side of this fix is low risk, since we are just passing a CPS cancellation token to an existing API.
None
No
Part of ongoing investigations …
> Pass UnloadCancellationToken to Solution Restore Service

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/ProjectLockFileWatcherTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectLockFileWatcher.cs
Two main scenarios:
- Opening a Shared Project without the following import, crashes Visual Studio.
``` XML
<Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
```
- Opening a .NET Core project with an empty or malformed "SDK" attribute crashes Visual Studio.
This can also occur while the project is already open by editing the SDK attribute and saving it with malformed contents.
#1129
**Risk**
Low
None
No
We made assumptions about the values of certain properties (in this case, intermediate path) …
> Don't crash when intermediate output isn't set

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependenciesSubTreeProviderBaseTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesSubTreeProviderBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/IEnumerableExtensions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/INuGetPackagesDataProvider.cs
When user changes dependency in project file , if dependency became unknown , icon did not reflect that.
https://github.com/dotnet/roslyn-project-system/issues/865
**Risk**
Minimal
> Fix for 865, when broken references changes did not have correct icons

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Properties/CSharpProjectDesignerPageProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Properties/CSharpProjectDesignerPageProvider.cs
Customer scenario
Editing values in this page can lead up to broken builds across multiple machines as the paths are saved on the .user file and are hardcoded to the paths in the machine.
Bugs this fixes:
#1071 
Workarounds, if any
No workarounds, currently the page will always show.
Risk
Low Risk - This only affects property pages
Performance impact
Low - This removes the page altogether so there's no initialization for it
Is this a regression from a previous update?
Not a regression.
Root cause analysis:
See above.
How was the bug found?
Dogfooding
> Disable the ReferencePaths property page

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesSubTreeProviderBase.cs
There are multiple reports of issues with the dependencies node where it doesn't show all the nodes or shows stale\wrong data. 
Also, when an user adds a Shared project reference to core app it did was not added to Dependencies\Projects sub tree node. 
This fix improves overall tree events data flow which appeared to be flacky and could produce some random missing data according to @lifengl. Now we:
- using suppressVersionOnlyUpdates: false, to allow all kinds of events to be send to SynkLink 
- PropagateCompletion = true for our data blocks to allow failures to be propagated to us
- merging data source versions accross all sub tree providers using CPS helper API and posting consistent merged sets of data sources versions after each tree update
- added NameFormat for …
> Fix for 954 Adding/removing a Shared Project does not update the dependency node

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Properties/CSharpProjectDesignerPageProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/Properties/VisualBasicProjectDesignerPageProvider.cs
Opening the properties page of a C# or VB Shared Projects, opens the AppDesigner and displays an error.
Fixes: #833
Fixes: #1325
You can change properties by opening the Properties Window tool window itself and selecting the Shared Project in Solution Explorer.
**Risk**
Low
None
Yes
Shared Projects and .NET Core share the same code base. A component was incorrectly marked as applying to all "C#" and "VB" projects, when it really only applied to C#/VB projects that support the Application Designer.
With this change, shared projects revert to their VS 2015 behavior which is to display the Project Properties tool window.
**How was …
> Show properties window for shared projects

- src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DataFlowUtilities.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
Sometimes when opening or creating an asp.net core project the launch settings don't appear in the debug dropdown. 
https://github.com/dotnet/roslyn-project-system/issues/1395
and is a work around for https://devdiv.visualstudio.com/DevDiv/_workitems?id=375276
Close and re-open the project
**Risk**
Low. Captures the execution context at the time the dataflow connection is established, and reapplies this context  when changes to the dataflow are received. This avoids leakage of execution state across the dataflow boundary.
Simple change with no extra allocations
No
This is an intermittent problem so difficult to catch in unit or …
> Fix for launch settings failing to load

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Editor/TempFileTextBufferManagerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Editor/ProjectFileEditorPresenter.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Editor/TempFileTextBufferManager.cs
Tagging @davkean @dotnet/project-system for review. This fixes a bug in how we were resetting state flags when updating the buffer in place, ensures that undo is correctly handled by saving the file on disk, and saves the project file an extra time to ensure we don't race if saving dirty changes on project close.
If the user makes a change programmatically (such as changing a property page setting) with the project file editor open, and then presses undo from inside the project file editor, the editor is not considered dirty and does not prompt to save changes if the project is unloaded causing data loss.
Fixes https://github.com/dotnet/roslyn-project-system/issues/1401.
The user can manually save the file, or not undo the …
> Correctly manage editor dirty state after refresh

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Xproj/MigrateXprojProjectFactoryTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/MigrateXprojProjectFactory.cs
Tagging @dotnet/project-system for review. FYI @livarcocc.
If a customer has a solution file and a project file in the same directory, we fail migration. This is because the Backup directory is put in the same locations as the project files, and when we ask migration to migrate the directory it will migrate both the actual project and the backed up project.
https://github.com/dotnet/roslyn-project-system/issues/1399
Migrate from the command line. The reason I believe this is worth the fix is that the error is completely silent: nothing appears in the log that would indicate a migration failure, but the solution does not load.
**Risk**
Very low. We just specify the project.json explicitly, which causes the CLI to only …
> Specify the project.json to migrate explicitly to address #1399

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
Error dialog complaining about mismatched data sources versions in the tree pops up at random points in time.
https://github.com/dotnet/roslyn-project-system/issues/1449
**Risk**
No one listens for Dependnecies tree updates and we can send null for data sources version for RTM. 
none
> Fix for 1449: mute data sources versions, since we still getting mismatches

- build.cmd
We keep regressing the warnings in the tree, MSBuild has added a new switch that let's us treat warnings as errors. Turn it on by default.
> Turn MSBuild warnings to errors

- src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.cs.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.tr.xlf
Bug 368857:[CSY] The ‘Title’ and ‘Neutral language’ option have the same
hot-key: <ALT + N> in Assembly Information dialog
Bug 368001:[TRK] The 'Title', ‘Assembly version’, ‘Neutral language’ &
‘Make assembly COM-Visible’ items have the same hot-key 'Alt + B' in
Assembly Information dialog
> LOC CHECKIN | dotnet/roslyn-project-system | 20170206 | bugfix

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/NuGetRestorer.cs
Fixes #1501
A customer that tries to save a solution while auto restore is running may run into a deadlock. This change drops Save as one of the operations that should wait for restore to complete (Build, Unload, and Rename still have to wait). From #1501:
> This is important because "Save" is done in a sync method in VS, but NuGet is running scripts in the background that depend on RPC to finish some tasks on the UI thread, so it can easily run into dead locks.
#1501 
N/A
**Risk**
Low. No change in behavior for Build, Rename and Unload, and the current arrangement is more deadlock prone for Save, according to the analysis from CPS team.
None
No
**Root …
> Critical task registration for Solution Restore service should exclude Save operation

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesSubTreeProviderBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/NuGetDependenciesSubTreeProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/ProjectDependenciesSubTreeProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SdkDependenciesSubTreeProvider.cs
When user has multiple TFMs , switching the active one would have different SDKs and some SDK oculd appear as packages, since for other TFM they are not marked as implicit packages. To solve it we add a property in common SDK targets to hardcode list of known SDK implicit packages.
https://github.com/dotnet/roslyn-project-system/issues/1456
N/A
**Risk**
Low
We resolve packages form assets.json file several times for unresolved and resolved SDK resolution.
> Fix for 1456 Dependencies are confusing with multiple TFMS

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/Reference3Factory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/References/DesignTimeAssemblyResolutionTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/DesignTimeAssemblyResolution.cs
Avoid searching SDK references in DTAR
SDK references return "assembly" as their Reference.Type for compatibility reasons. We shouldn't be looking at them as we're only looking for assemblies.
Hit this as part of: https://github.com/dotnet/roslyn-project-system/issues/1555.
> Avoid searching SDK references in DTAR

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependenciesChangeDiffFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependencyNodeFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/INuGetPackagesDataProviderFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependenciesSubTreeProviderBaseTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependencyNodeTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/NuGetDependenciesSubTreeProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/ProjectDependenciesSubTreeProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProjectContextProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesSubTreeProviderBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/IDependenciesGraphProjectContext.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/IDependencyNode.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/IDependencyNodeExtensions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/NuGetDependenciesSubTreeProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/ProjectDependenciesSubTreeProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SdkDependenciesSubTreeProvider.cs
Random nodes in the dependency tree in solution explorer might not appear after some dependent project changes or have incorrect icons (resolved vs unresolved). This gives the impression of poor quality and one cannot trust the data in solution explorer.
https://github.com/dotnet/roslyn-project-system/issues/1423 or similar
Reload project
**Risk**
Even though it introduces a breaking change for web tools, change on web side is small and we just need to do insertions from core and web with matching bits.
Original implementation was working ok, but then we introduced async dependencies accross sub tree providers which would need immutable data
> Make IDependencyNode.Children immutable;Add other breaking changes for IDependencyNode public API

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProvider.cs
Search for web packages provided by external provider ended up with stackoverflow crash
https://github.com/dotnet/roslyn-project-system/issues/1580
N/A
**Risk**
Minimal
Nona
Yes
We did not match correctly results returned form external provider and returned null when progression asked to find a tree node. By some reason progression kept asking us again and again which resulted in stack overflow. Fix is on our side, however possibility of overflow still hidden in progression if consumers don't do things right..
Internal dogfooding.
> Fix for 1580 stack overflow crash during search

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProvider.cs
Search in the Solution Explorer tree was super slow and looked like a UI hang when user had some common query strings like "system"
https://github.com/dotnet/roslyn-project-system/issues/1581
N/A
**Risk**
Minimal
Perf is improved, however results are linear and not as informative as hierarchies that we showed for dependencies before
No
Progression code that does search in Solution explorer was not designed to work well with deeper hierarchies and becomes very slow with depth increasing
Internal dogfooding - it was known for a while, however no improvemennts were planned in Dev15 in Solution Explorer
> Fix for 1581 show linear search results instead of hierarchy to avoid progression delays

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/cs/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/de/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/es/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/fr/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/it/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ja/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ko/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pl/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pt-BR/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ru/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/tr/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.cs.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.de.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.es.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.fr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.it.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.ja.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.ko.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.pl.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.pt-BR.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.ru.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.tr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.zh-Hans.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.zh-Hant.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hans/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hant/GeneralConfiguredBrowseObject.xaml
When you click on .net core projects properties -> Build properties , output path browse button.
you get a VS Crash.
https://devdiv.visualstudio.com/DevDiv/_workitems?id=384363&_a=edit
https://github.com/dotnet/roslyn-project-system/issues/1589 
none
**Risk**
low
low
yes 
we split the properties to configuration specific file and missed to carry this property over.
dogfooding
> Fix build outputpath browse crash

- netci.groovy
Moving the Roslyn-Internal source-control pointer forward to consume the latest changes in Roslyn-Internal; including the enablement of 'CSharpProjectSystem' VSI test.
> Moving the Roslyn-Internal source-control pointer forward.

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/cs/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/de/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/es/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/fr/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/it/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ja/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ko/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pl/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pt-BR/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ru/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/tr/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hans/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hant/NuGetRestore.xaml
Fixes  #1532 
PackageId is not honored when restoring from Visual Studio (but is honored by `msbuild /t:restore` and `dotnet restore`). Hence given two projects, one with PackageId:
```xml
<Project Sdk="Microsoft.NET.Sdk">
<TargetFramework>netstandard1.4</TargetFramework>
<PackageId>ReferencedProjectPackageID</PackageId>
</Project>
```
and a second project referencing this by package id:
```xml
<Project Sdk="Microsoft.NET.Sdk">
<TargetFramework>netstandard1.4</TargetFramework>
<ItemGroup>
<ProjectReference Include="..\ReferencedProject\ReferencedProject.csproj" />
<PackageReference Include="ReferencedProjectPackageID" Version="1.0.0" />
</ItemGroup>
</Project>
```
opening in Visual Studio produces a …
> Add PackageId to NuGetRestore rules

- build/Targets/Settings.targets
- src/Dependencies/Toolset/Toolset.csproj
Incremental build is broken due to some bad interplay with the package version of the compiler and the compile cache introduced for SDK projects, see: https://github.com/Microsoft/msbuild/issues/1757
This removes usage of the package version of the compiler which was only needed while the language was changing - now that we should be on RC4+, we can use the inbox version.
This reduced `build /release /no-multi-proc` from ~3:30 minutes to ~1:59 minutes on my box.
> Use in-box compiler to fix incremental build

- build/Targets/VSL.Versions.targets
- src/Dependencies/CPS/project.json
- src/Dependencies/VisualStudio/project.json
- src/NuGet/Microsoft.VisualStudio.AppDesigner/Microsoft.VisualStudio.AppDesigner.nuspec
- src/NuGet/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.nuspec
- src/NuGet/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.nuspec
- src/NuGet/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.nuspec
- src/NuGet/NuGet.proj
Nugets that we produce today are built using the Pre-release version of some of the dependencies. This change will remove those Pre-release version dependencies and hence will enable us to release release-versioned Nuget packages for Roslyn Project system. The binaries that get built and packaged into the Nuget will be available to insert into VS
[388822](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/388822)
No. All VS nugets are non-pre release so it makes sense to release non-pre release nugets for Project system as well
**Risk**
There has not been much code churn with the dependencies and we are taking a dependency over VS release quality package. So we hope the risk is minimal. We will do manual validation in …
> Release Roslyn Project System and Nugets which are Release versioned

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/ProjectDependenciesSubTreeProvider.cs
Fixes: #1623
Before:
After:
The warning icon is being tracked here: https://github.com/dotnet/roslyn-project-system/issues/1627
> Fix icon for shared projects in nested hierarchy

- src/NuGet.config
VS settings on my box were preventing us from restoring because I'd disabled a source in VS which broke our repo. Prevent that, like we prevent VS registered sources from breaking us.
> Prevent user disabled package sources

- src/DeployTestDependencies/DeployTestDependencies.csproj
This is to prevent a downgrade error when running on a machine with https://github.com/dotnet/sdk/pull/893.
Filed https://github.com/NuGet/Home/issues/4703 to track the large number of warnings/errors this case caused.
> Upgrade RuntimeInformation from 4.0 -> 4.3

- build/Targets/References.targets
- build/Targets/VSL.Imports.targets
- build/Targets/VSL.Versions.targets
These were accidentely removed when we removed the dependency projects and prevented us from restoring these packages on clean machines.
> Add package references to MicroBuild

- build/Targets/References.targets
- build/Targets/Settings.targets
- build/Targets/VSL.Imports.targets
This was removed in the dependency removal, and caused Jenkins to stop deploying VSIX.
> Add BuildTools package reference

- build/build.proj
- 	Stop explictly setting DeployExtension=false for MicroBuild 
- 	Stop passing properties to inner builds
See commits for more details
> Remove unneeded global properties [dev15.1.x]

- src/Microsoft.VisualStudio.AppDesigner/Microsoft.VisualStudio.AppDesigner.vbproj
- src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj
This lets these projects be opened on VS 2017 RTM without the selector VSIX to be installed. When the selector is installed, it will be opened in CPS.
There are still some caveats (for example, source files don't show in the VB projects) with this approach that I'll plan on documenting on the Getting Started.md.
> Add back ToolsVersion/xmlns to VB projects

- netci.groovy
1. moving the Roslyn-Internal pointer forward to consume the latest changes; adding 2 VSI tests & a fix to Raul's codemarker stuff
2. temporary workaround for the microbuild.plugins.swixbuild cache build error in Roslyn-Project-System
> Jenkins groovy file changes:

- build/Targets/GenerateAssemblyInfo.targets
When the build is run in Microbuild, we use the property RunningInMicroBuild and not OfficialBuild.
@natidea Today, the official binary has the product version as Developer build. Should we take this for 15.1?
> Use RunningInMicroBuild instead of OfficialBuild

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IServiceProviderExtensions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesGraphProjectContextProvider.cs
- Import IProjectServiceAccessor directly instead of GetService indirection
We're a MEF component, we can just import it directly instead of asking through IComponentModel.
> Import IProjectServiceAccessor directly instead of GetService indirection

- build/Targets/VSL.Versions.targets
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
Fixes https://github.com/dotnet/roslyn-project-system/issues/1373#issuecomment-285260349 and TFS bug 393230. 
Instead of unsubscribing for provider events in Dispose , do it in ProjectUnloading event and don't process event if current object is Disposing.
> Fix ObjectDisposed exception for dependencies tree

- src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests/ProjectSystem/ProjectTreeParserTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs
Fixes: #1765
These tests hard-code strings with new embedded new lines. Ignore these differences so that clone with Git set to use \n doesn't cause them to fail.
> Ignore line ending differences

- build.cmd
Robocopy has a success return ranging from 0-7 which build.cmd was not handling. Fixing the script.
> Handle Robocopy success code

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/AbstractAddClassProjectCommandTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/AbstractAddClassProjectCommand.cs
- Pass empty as add item template GUID instead of project
AddItemDialog isn't expecting the project GUID - it's expecting the Add Item Template GUID. We pass empty here - as it ends up asking the hierarchy for it, see CAddProjectItemDlg::AddProjectItemDlgTitledEx.
> Pass empty as add item template GUID instead of project GUID in AbstractAddClassProjectCommand

- build/Targets/References.targets
- build/Targets/VSL.Versions.targets
- src/NuGet.config
- src/NuGet/Microsoft.VisualStudio.AppDesigner/Microsoft.VisualStudio.AppDesigner.nuspec
- src/NuGet/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.nuspec
- src/NuGet/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.nuspec
- src/NuGet/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.nuspec
- src/NuGet/NuGet.proj
With this change, the nuget version of the package that are referenced both in the project and Nuspec will moved to one single properties group rather than listed in all places(`References.targets and `*.Nuspec``). The advantage is, user edits one place, the change propagates everywhere.
Without this change, the Nuget version of the packages listed in the nuspec dependency will start deviating from the actual version that is used to build the product. This already happened for System.Collections.Immutable.
This change does move all the package reference version to the property group. It moved just the packages which are referenced in more than one place.
@dotnet/project-system @davkean for review.
@RaulPerez1, you might want to get this change before you make the changes through #1771. …
> Move the Nuget Version value from hard coded value to a variable

- src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.Designer.vb
- src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.resx
- src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.vb
Scale Build property page using Font
The Build property page was using .NET 1.0-era DPI scaling. This had two issues:
1) Under DPIs less than 96 DPI, this was downscaling the page.
2) Under DPIs greater than 96 DPI, this wasn't scaling the TableLayout columns, resulting in squashed columns.
Opt into the .NET 2.0-era Font scaling similar to the rest of WinForms dialogs and pages around Visual Studio, this results in more accurate scaling across all DPIs, and used by other pages such as the Application page.
Also removed the manual DpiHelper scaling - this was compensating for the lack of scaling of the columns and actually causing it to be too wide on high DPIs resulting in a horizontal scroll bar.
Fixes: #820 #1374
Before at 200% on a 96 DPI machine:
After at 200% on a 96 DPI machine:
> Scale Build property page using Font

- src/Microsoft.VisualStudio.Editors/PropPages/AdvBuildSettingsPropPage.resx
- src/Microsoft.VisualStudio.Editors/PropPages/CSharpLanguageVersion.vb
- src/Microsoft.VisualStudio.Editors/PropPages/CSharpLanguageVersionUtilities.vb
cc @davkean @jcouv @VSadov @jaredpar 
This adds 7.1 language version, and a "Latest" option. More details in https://github.com/dotnet/roslyn/issues/17173
A few notes, please let me know if I missed something.
1. Noticed this area is not covered by any tests.
2. The strings are not localized as well (default item).
3. This version is intended for VS 15.3. Is `master` the correct branch to use?
> Add C# 7.1/Latest versions to project system

- src/Microsoft.VisualStudio.Editors/PropPages/DebugPropPage.Designer.vb
- src/Microsoft.VisualStudio.Editors/PropPages/DebugPropPage.resx
- src/Microsoft.VisualStudio.Editors/PropPages/DebugPropPage.vb
Scale Debug property page using Font
Opening the Debug property page on machines with a DPI less than 96 makes the page unusable.
Opening the Debug property page on machines with a DPI greater than 96 makes the middle column of the page squashed and too small.
Fixes: #427
None
**Risk**
Low but if done incorrectly could result in making >96 DPI unusable. The page is unusable under 96 DPI, so there's very little risk of making that worse.
None.
We made the dialog worse in VS 2017 on machines under 96 DPI when we changed the layout slightly.
The Debug property page was using .NET 1.0-era DPI scaling. This had two issues:
1) Under …
> Scale Debug property page using Font

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/EditProjectFileCommandTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/EditProjectFileCommand.cs
Project.EditProjectFile was only enabled when the root node was selected in Solution Explorer, and Solution Explorer had focus. Instead, it should be enabled regardless of which node is selected, this makes make it available from Project/Command window when editor has focus or when one or many project items are selected. This is how other project-level commands work such as Add Reference.
This doesn't cause it to appear on the context menu of an item - by default it doesn't show up unless the user adds it to that context menu.
Fixes: https://github.com/dotnet/roslyn-project-system/issues/1828.
> Project.EditProjectFile should be always available

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/Packaging/CSharpProjectSystemPackage.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/Packaging/VisualBasicProjectSystemPackage.cs
Turn off asynchronous tree loading to bring the behavior of the project system in line with the legacy project system. This lets extensions query for project items after the project load event has fired and get correct results.
Make note, that the tree was being published anyway during load in variety of places anyway:
1) File -> New always published the tree due to wizards expecting the project to be done by the time they were called
2) The LanguageServiceHost would already publish not too much after the Project factory had "completed", so depending on the when the component looked, sometimes you'll get correct results, and sometimes you wouldn't. This is going to be removed as a part of https://github.com/dotnet/roslyn-project-system/issues/1655. This change makes it always consistent.
> Make sure the tree is published before the project has finished loading

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/Packaging/CSharpProjectSystemPackage.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/MigrateXprojProjectFactory.cs
The package doesn't need to know about the project type of xproj - that's the factory's job.
> Move xproj project type usage to factory

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/RoslynServices.cs
This is unneeded async code generation, when we can return the result Renamer.
> Remove unneeded await

- src/Microsoft.VisualStudio.Editors/PropPages/TargetFrameworkMoniker.vb
Adds .NET Core and .NET Standard 2.0 to project property lists that already contain earlier versions of those two targets. For #1672. Also adds code to have a nice name for targets, for #1595 (until VS supports them).
> Add .NET Core 2.0 and fix naming

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Utilities/SequencialTaskExecutorTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/SequencialTaskExecutor.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/SequencialTaskExecutor.cs
Addresses https://github.com/dotnet/roslyn-project-system/issues/495
Addresses VS feedback bug https://vsfeedback/comment/803555
Added a task executer which guarantees scheduled tasks are run in sequence. 
Changed the saving code in launchsettingsprovider.cs to use this scheduler.
> Make launch provider more robust

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectChangeDescriptionFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IWorkspaceProjectContextFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/SourceItemHandlerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/FileItemServices.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractLanguageServiceRuleHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/CommandLineItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/ProjectPropertiesItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/SourceItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ILanguageServiceRuleHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs
We used to publish and look up the project tree to find the effective path of a `<Compile/>` to pass to Roslyn. Originally I did this to handle that fact that some trees _might_ result in different view of the files (think Venus Web Sites where all files end up in App_Code). This ended up being quite complex, slow and due active configurations changing, or multi-targeting, could result in incorrect data being passed to Roslyn. For example, in multi-targeting projects, if a file was conditioned out of the current configuration the folder names for that file would never be found because it would never show be shown in the "Active" tree.
Instead we just get the folder names from the item itself, looking at Link metadata if specified, here's some examples:
```
<Compile Include="File.cs" /> …
```
> Stop publishing tree just to get folder names for the language service

- src/Targets/Microsoft.CSharp.DesignTime.targets
- src/Targets/Microsoft.VisualBasic.DesignTime.targets
We have our own copy of rules that are also being imported by MSBuild. I'm adding a flag to msbuild to disable importing these rules and setting that here. See https://github.com/Microsoft/msbuild/pull/1938 for the MSBuild change.
> Turn off rules coming from CSharp\VB targets in MSBuild.

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ConfiguredProjectFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IActiveConfiguredProjectProviderFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectConfigurationsServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IUnconfiguredProjectCommonServicesFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IUnconfiguredProjectServicesFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectConfigurationFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/UnconfiguredProjectFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ActiveConfiguredProjectsProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredProjectsProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IActiveConfiguredProjectsProvider.cs
As a future change, I'm changing TargetFrameworkProjectConfigurationDimensionProvider to be the only component that understands that `<TargetFramework>` contributes to our how we determine configurations. This will remove ActiveConfiguredProjectsProvider, LanguageSevice, NuGetRestorer and debugging understanding of the `<TargetFramework>` property. To reduce churn and review time when I do that, I'm putting out my refactoring of the ActiveConfiguredProjectsProvider class which I did to prepare for that change.
Changes in this PR:
- Previously GetActiveConfiguredProjectsAsync/GetActiveProjectConfigurationsAsync would delegate onto GetActiveConfiguredProjectsMapAsync. However, this was the wrong dependency and meant that to get just the "active configurations" you needed to load all the …
> Refactor ActiveConfiguredProjectsProvider

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VsProject.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VsProject_VsLangProjectProperties.cs
With VSProject being internal, InvalidCast exception was thrown if the object was tried to be marshalled to other processes
Fix #1901 
Tag @dotnet/project-system @srivatsn @davkean @tmeschter @natidea for review. I tested this change and it works.
FYI, @abpiskunov @BillHiebert
> Make VSProject public

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/TargetFrameworkProjectConfigurationDimensionProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/TargetFrameworkProjectConfigurationDimensionProvider.cs
We were using the absence of the TargetFramework as indicating a multi-targeting project - but that's not true. TargetFramework will be set in the inner builds. So just look for the presence of TargetFrameworks.
@dotnet/project-system @RaulPerez1 @natidea
> Change the way we identify multi-targeting projects to create configurations

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetSubscriptionHostBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/AnalyzerReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/AssemblyReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ComReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedAnalyzerReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedAssemblyReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedCOMReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedSdkReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/SdkReference.xaml
- add new IsImplicitlyDefined property to xaml rules files (sdk can send it, but we forgot to update schema)
- fix bad merge issue that messes up aggregate snapshot update in single target app (if user updates target in the single target app, it keeps old one too; change now handles that and allows new aggregate snapshot to be generated)
> Minor changes to dependencies 

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/TargetFrameworkProjectConfigurationDimensionProvider.cs
This fixes a MEF cache break due a bad merge.
> Implement IActiveConfiguredProjectsDimensionProvider on TargetFrameworkProjectConfigurationDimensionProvider

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectTreeProviderFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractSpecialFileProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AppManifestSpecialFileProvider.cs
This is needed by the VB application page - it has a button to bring up the app,manifest file which queries the special file handler for it.
This is basically a straightforward handler except if the ApplicationManifest property is specified - in that case, the path specified by that property is used. If that file is not found, we fall back to the regular logic of finding a special file including creating in default location (Verified the behavior with legacy ps).
Fixes #83
> Implement special file handler for app.manifest. 

- src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPageVBWinForms.vb
- src/Targets/Microsoft.Managed.DesignTime.targets
The VB app page makes a call to query the hierarchy for VSHPROPID_SupportedOutputTypes. CPS used to return nothing which is why the VB app page wasn't showing up at all. I've made a change to CPS to instead return the value of a property called `SupportedOutputTypes` . Setting that property in our design time targets to set the defaults to Exe;WinExe;Library. Note that the C# prop page also respects this property. 
Also making a change to disable the assemblyinfo button if the Pack capability is set since we'll show the package page.
Fixes #940 
(Note: I had originally planned to bring up the C# application for VB as well to keep it simple. However, it looks there code in the VB page that has some special handling for Root namespace - it strips that out of startup objects for eg and makes …
> Add supported output types property to get the VB application page to show up.

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Telemetry/VsTelemetryServiceTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/ITelemetryService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/VsTelemetryService.cs
Telemetry events were being double-prefixed, one from the event name being passed to the service, and one within the service itself.
> Do not double-prefix telemetry events [dev15.2]

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependenciesChangesFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/SdkAndPackagesDependenciesSnapshotFilterTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetRuleSubscriberBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetSubscriptionHostBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/Actions/GraphActionHandlerBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/ViewProviders/GraphViewProviderBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/ViewProviders/ProjectGraphViewProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/SdkAndPackagesDependenciesSnapshotFilter.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySubscriptionsHost.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/ProjectRuleHandler.cs
Customer scenario
Random or stale dependency nodes in the tree. 
Bugs this fixes:
Fixes https://github.com/dotnet/project-system/issues/1980
Workarounds, if any
No
Risk
Small 
Performance impact
Low
Is this a regression from a previous update?
Yes
Root cause analysis:
New changes were pushed to support crosstargeting for dependencies tree and there are some adjustments needed.
After testing merged changes i saw several tree update quirks:
- when target changes old flow events still sent to dependencies rules subscribers and might end up in some old nodes be displayed in the tree
- avoid unnecessary closing project and sdk nodes
- when tracking change in graph nodes, skip all invisible dependencies to avoid showing them in lower level hierarchies
How was the bug found?
Testing new build
> Fix for Dependencies tree stability issues

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Telemetry/VsTelemetryServiceTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/ITelemetryService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/VsTelemetryService.cs
Telemetry events were being double-prefixed, one from the event name being passed to the service, and one within the service itself.
> Do not double-prefix telemetry events [master]

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralConfiguredBrowseObject.xaml
This is a follow up PR for #2004. Only the last commit is a new commit and the rest of the commits are part of 2004.
Enable VB advanced compile options page. 
#346 
None
**Risk**
Low risk - since this just affects that page
None - since this is a new page, which just reflects the msbuild properties like any other page.
**Is this a regression from a previous update?** N/A
**Root cause analysis:** N/A
**How was the bug found?** N/A
> Enable VB Advanced Compile Options page

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralConfiguredBrowseObject.xaml
This is a follow up PR for #2004. Only the last commit is the new commit and the rest of the commits are part of #2004 and #2005.
Enable VB Compile page - Build events page.
#346 
None
**Risk**
Low risk - since this just affects that page
None - since this is a new page, which just reflects the msbuild properties like any other page.
**Is this a regression from a previous update?** N/A
**Root cause analysis:** N/A
**How was the bug found?** N/A
> Add VB compile build events

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ActiveConfiguredProjectsProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredProjectsProvider.cs
ActiveConfiguredProjectsProvider doesn't need IUnconfiguredProjectCommonServices and I'm changing IUnconfiguredProjectCommonServices to use IActiveConfiguredProjectsProvider.
> Use UnconfiguredProject instead of IUnconfiguredProjectCommonServices

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/UnconfiguredProjectContextProvider.cs
When a project has multiple targets we differentiate between them by
appending the specific target to the display name, like so:
> MyProject(netstandard1.4)
> MyProject(net45)
Note the lack of space between the project name and the target. This
commit adds the space back in:
> MyProject (netstandard1.4)
> MyProject (net45)
N/A
None
**Risk**
Low
None; just a string change.
No.
N/A
Ad hoc testing
> Fix project display name for multi-targeting

- build/Targets/ProducesNoOutput.Imports.targets
- build/Targets/ProducesNoOutput.Settings.targets
- src/DeployTestDependencies/DeployTestDependencies.csproj
- src/ProjectSystem.sln
- src/ProjectSystemSetup/Properties/launchSettings.json
- src/Targets/Targets.csproj
- src/VsixV3/ProjectSystemPackage/Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.swr
Changing rules\targets is a pain today because we have to change the actual copy in msbuild and we often forget to test with that leading to bugs. This change deploys all the targets and rules into a directory under the output directory and then sets env variables to make msbuild pick up these targets\rules in the RoslynDev instance instead of the copy in msbuild.
With this now, one can change a rule, F5 and the new instance will have the changed rule\target take effect.
@dotnet/project-system - looking at this commit by commit might be easier.
> Use just built rules\targets in the RoslynDev hive

- build/Targets/VSL.Versions.targets
Infrastructure change only to set distinguishing versions for NuGet packages when we publish them.
> Set NuGetMoniker to beta1 for 15.3.x

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/TargetFrameworkMonikerValueProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/TargetFrameworkMonikersValueProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
.NET Core projects have added a new concept of being able to target multiple frameworks in a single project. We have asks from some MVPs to invest more in that feature and we need to make decisions on investment based on this data.
https://github.com/dotnet/project-system/issues/1764
None
**Risk**
Low.  This exposes a property that CPS will log telemetry on
Low. This exposes a property that CPS will log telemetry on
No
> Add new project property "TargetFrameworkMonikers" that lists all specified target monikers in the project.

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs
See #1831.
See #1831.
**Risk**
_Non fully qualified_ executable paths (e.g. "notepad") don't work ("The system cannot find the file specified") because previously it worked via PATH-expansion in cmd.exe. But: Exactly the same is true for F5 (with debugger) because here also happens no PATH-expansion. Therefore I think if this is a problem (for non fully qualified paths), it should be handled in a new bug and PR.
Almost none.
It is a regression from the old project system.
Customer reported it.
> Fix Ctrl F5 for "Run Executable"

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/AnalyzerReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedAnalyzerReference.xaml
- src/Targets/Microsoft.Managed.DesignTime.targets
Currently when expanding the "Analyzers" node in Solution Explorer you will only see analyzers that have been added directly to the project--analyzers from NuGet packages will not be shown. To get to those you would need to dig through the "NuGet" node and then the individual packages to find what you want.
A major reason we show analyzers in the Solution Explorer is to allow the user to expand them, see the diagnostics each one supports, and adjust the severity. Forcing the user to dig through the NuGet packages would make this effectively impossible as the user would need to know ahead of time which packages include which analyzers, or else they have to spend a lot of time clicking around until they find what they want.
To simplify this experience, we should just …
> Show all analyzers in Solution Explorer

- build/Targets/VSL.Versions.targets
Infrastructure change only to set distinguishing versions for NuGet packages when we publish them.
/cc @basoundr @srivatsn
> Update NuGetMoniker to beta2 for master

- netci.groovy
We've been running into build issues on Jenkins caused by node reuse, including:
- Using an old compiler
- CodeTaskFactory failures
> Turn off MSBuild node reuse

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IActiveConfiguredProjectsProviderFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContextProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ActiveDebugFrameworkServices.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IActiveConfiguredProjectsProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/UnconfiguredProjectContextProvider.cs
(Preparing to make IActiveConfiguredProjectsProvider public for the VSTest guys)
This method will be removed in a future PR, want to avoid any new dependencies on it.
> Obsolete IActiveConfiguredProjectsProvider.GetActiveConfiguredProjectsMapAsync

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/EditAndContinue/EditAndContinueProvider.cs
Instead of receiving the call for ENC and reforwarding the call to AbstractProject, MEF export the AbstractProject as EnC interface.
None. This change removes a bunch of code which was unnecessary in the first place
#1019
N/A
**Risk**
None since no functional change
None
**Is this a regression from a previous update?** N/A
**Root cause analysis:** N/A
N/A
Tagging @dotnet/project-system for review
> Return AbstractProject which implements ENC interface for EnC Service

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Properties/CSharpProjectDesignerPageProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Properties/CSharpProjectDesignerPageProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS.UnitTests/ProjectSystem/VS/Properties/FSharpProjectDesignerPageProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS/ProjectSystem/VS/Properties/FSharpProjectDesignerPageProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests/ProjectSystem/VS/Properties/VisualBasicProjectDesignerPageProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/Properties/VisualBasicProjectDesignerPageProvider.cs
Xamarin folks do not define LaunchProfiles and want to hide the Debug property page when it is not present.
> Debug property page under LaunchProfiles capability

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ConfiguredProjectHostObject.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ProjectHostProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IProjectHostProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/UnconfiguredProjectContextProvider.cs
Roslyn handles multi-targeting scenarios by creating multiple projects in the workspace, one for each target. In order to show the correct set of diagnostics on the correct set of analyzers in the Solution Explorer in these scenarios we need to be able to find the correct Roslyn project for a given target. 
When asking the Roslyn Language Service to create a project we pass it a `ConfiguredProjectHostObject` to represent the project hierarchy. This change updates the host object to be aware of its TargetFrameworkMoniker, and expose it through the `IVsHierarchy` interface via the `__VSHPROPID4.VSHPROPID_TargetFrameworkMoniker` property.
Related to #88.
N/A
**Risk**
Low
None
**Is this a regression …
> Store TargetFrameworkMoniker in the ConfiguredProjectHostObject

- build/Scripts/copyOutput.cmd
- build/Targets/Settings.targets
- build/build.proj
- src/NuGet.config
- src/ProjectSystem.sln
- src/Templates/DeployNupkgs/DeployNupkgs.csproj
- src/Templates/Microsoft.NetCore.CSharp.ProjectTemplates/ClassLibrary-CSharp-NetCoreApp.vstemplate
- src/Templates/Microsoft.NetCore.FSharp.ProjectTemplates/ClassLibrary-FSharp-NetCoreApp.vstemplate
- src/Templates/Microsoft.NetCore.VB.ProjectTemplates/ClassLibrary-VB-NetCoreApp.vstemplate
- src/VsixV3/ProjectTemplates1.x/Microsoft.VisualStudio.NetCore.ProjectTemplates.1.x.swixproj
- src/VsixV3/ProjectTemplates1.x/Microsoft.VisualStudio.NetCore.ProjectTemplates.1.x.swr
- src/VsixV3/ProjectTemplates1.x/Microsoft.VisualStudio.NetCore.ProjectTemplates.1.x.vsmanproj
- src/VsixV3/ProjectTemplates1.x/Templates.pkgdef
Customer installs Visual Studio but does not install dotnet CLI tools, without this change no netcore templates will be installed
related to https://github.com/dotnet/project-system/pull/2053
none
**Risk**
Low
> Creating a package to deploy the 1.x templates

- src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPageInternalBase.vb
- src/Microsoft.VisualStudio.Editors/PropPages/TargetFrameworkMoniker.vb
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Xproj/GlobalJsonRemoverTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectLockServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectXmlAccessorFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectItemFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/SupportedTargetFrameworksEnumProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectXmlAccessor.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/MSBuildXmlAccessor.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/SupportedTargetFrameworksEnumProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
The customer does not have the .NET Core 2.0 installed. They open a .NET Core 1.1 project and open the application property page. The target framework dropdown will contain a hardcoded entry for .NET Core 2.0 (even though .NET Core 2.0 is not installed). If they choose that, their project will no longer build and they will get errors about missing framework types. There will be no indication as to what went wrong, they will just thing .NET Core 2.0 is busted.
#1516 
VSO - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/428151
The only workaround is to know that you haven't installed .NET Core 2.0 and not choose the .NET Core 2.0 entry in the dropdown.
**Risk**
Low. The code is isolated to just this single dropdown …
> Dynamically populate Target Framework dropdown from SDK

- src/Templates/Microsoft.NetCore.CSharp.ProjectTemplates.Test/MSTest-CSharp-NetCoreApp.vstemplate
- src/Templates/Microsoft.NetCore.CSharp.ProjectTemplates.Test/XUnitTest-CSharp-NetCoreApp.vstemplate
- src/Templates/Microsoft.NetCore.FSharp.ProjectTemplates.Test/MSTest-FSharp-NetCoreApp.vstemplate
- src/Templates/Microsoft.NetCore.FSharp.ProjectTemplates.Test/XUnitTest-FSharp-NetCoreApp.vstemplate
- src/Templates/Microsoft.NetCore.VB.ProjectTemplates.Test/MSTest-VB-NetCoreApp.vstemplate
- src/Templates/Microsoft.NetCore.VB.ProjectTemplates.Test/XUnitTest-VB-NetCoreApp.vstemplate
This enables the VSTemplates to be created with the new template engine
None
**Risk**
Low, this is just an update to the metadata in the vstemplate files, it is well isolated from other components.
Churn in the new template engine
> only use ProjectGroup when defining templates

- src/Targets/Microsoft.VisualBasic.DesignTime.targets
VB Framework projects needs references to the Core libraries, without which Object and all the essential types will be missing. This reference was added by VisualBasic Project in the legacy world. This change will perform a similar functionality.
Tagging @srivatsn @dotnet/project-system for review
Without this change, the language service for all of VB framework projects is broken
#1961 
None
**Risk**
Low. This change is only for VB framework projects.
None. There is no complex computation. 
No. This scenario could not have worked before unless the Core libraries were added by mistake.
This is parity behavior of the VB Legacy …
> Add Runtime assemblies for VB Framework projects

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/VsOptionalServiceTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IVsOptionalService`1.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IVsOptionalService`2.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IVsService`1.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IVsService`2.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsOptionalService`1.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsOptionalService`2.cs
Added IVsOptionalService where GetService returning null for a given service is expected and not a product bug.
I considered different approaches for this; such as returning a different property/methpd from IVsService that didn't throw - I ended up liking this approach from a consumption standpoint, this leaves it to look like Lazy<T>.Value.
> Add IVsOptionalService

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsOptionalServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsOutputWindow2Factory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsOutputWindowFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsOutputWindowPaneFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Logging/ProjectOutputWindowPaneProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/VsOptionalServiceTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IVsOptionalService`1.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IVsOptionalService`2.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IVsService`1.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IVsService`2.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Logging/IProjectOutputWindowPaneProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Logging/ProjectOutputWindowPaneProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsOptionalService`1.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsOptionalService`2.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/Interop/IVsOutputWindowExtensions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx
This is 2 of 4 PRs for the new logging infrastructure. The PR's have been split up to reduce the amount of code to be reviewed.
This PR includes a new interface & implementation called IProjectOutputWindowPaneProvider/ProjectOutputWindowPaneProvider that provides access to the a new "Project" Output Window pane that we will be writing to via a logger. ProjectOutputWindowPaneProvider simply provides a access to a singleton IVsWindowOutputPane across the project system, it does not write it or hide it behind an option - that's coming in a future PR. 
The idea is that this pane will be turned on when we need to get more information from a customer's machine. I have a future PR where the language service writes to this to help chase down some the issues that are not repro'ing inside the …
> Add service to create/return "Project" Output Window pane

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/TargetFrameworkMonikersValueProvider.cs
We added telemetry data in 15.2 to identify multi-tfm projects and the frameworks being targeted by them. When this code merged into the 15.3 branch it broke. This change adds back that telemetry point.
[VSO 430121](https://devdiv.visualstudio.com/DevDiv/_workitems?id=430121&fullScreen=false&_a=edit)
None
**Risk**
Low
Low
Yes from 15.2
We were MEF importing a type that was being exported as a concrete type in 15.2 but through an interface in 15.3. When the merge happened there was no conflict because they were in different files and we didn't get any error.
Looking at MEF composition errors in 15.3 …
> Fix missing TargetFrameworks telemetry that was broken due to a mismerge

- build/Targets/Settings.targets
In D15PreRel, there are breaking changes in IOperation that are causing the Roslyn analyzers to fail with about 29 AD0001s. Turning off rules entirely to get the solution to build. 
@jinujoseph @mavasani - do we have a feed with packages that are fixed up for the breaking changes?
> Turn off analyzers since there are breaking changes in IOperation causing rules to fail

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/BuildOptions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IParseBuildOptions.cs
These do not need to be public and are not part of our public API.
> Make BuildOptions/IParseBuildOptions internal

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/AdditionalFiles.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/AnalyzerReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/AssemblyReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ComReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Compile.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/EmbeddedResource.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/None.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PackageReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ProjectReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedAnalyzerReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedAssemblyReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedCOMReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedPackageReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedProjectReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedSdkReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/SdkReference.xaml
Update a bunch of property descriptions that are obviously different from those used in the old project system. We're not going for absolute consistency here, but unless what we have is clearly better we should just stick with the descriptions used in the old system.
Customers using the new project system will see text in the Properties Window that is arbitrarily different from what we had in the old project system.
Fixes #59.
N/A
**Risk**
Low.
None; these are simply string changes.
No.
N/A
Dogfooding
> Update property descriptions

- netci.groovy
The templates have been moved to Project system. Remove the explicit step to build the templates from the SDK.
The VSI tests still try to build the SDK templates from SDK and have been [failing](https://ci.dot.net/job/dotnet_project-system/view/Official%20Builds/job/master/job/vsi/). Remove that step. This is just infra change.
@jmarolf  @srivatsn @davkean @dotnet/project-system to make sure I am not missing anything else.
> sdk-templates are no longer present in SDK. Modify groovy script to reflect that change.

- src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerView.vb
- src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerWindowPane.vb
- src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/DesignerTabControl.vb
- src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/DesignerTabControlRenderer.vb
- src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/SpecialFileCustomViewProvider.vb
- src/Microsoft.VisualStudio.AppDesigner/Common/ShellUtil.vb
- src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerView.vb
- src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPage.vb
- src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPageUserControlBase.vb
- src/Microsoft.VisualStudio.AppDesigner/PropPages/VSThemedLinkLabel.vb
This updates the ApplicationDesigner to support "themed" property pages. This, or something similar, will be required to ensure we meet the accessibility requirements around color contrast ratios.
A relevant comment that was in "PropPageDesignerView" was:
> 'We used to use a lighter color than SystemColors.Control (and we would get it from the color service).
>            '  But that causes issues because a) we can't control disabled control colors, b) we have problems when our
>            '  pages are hosted in another property page frame with different colors (e.g., C++), and c) we have problems
>            '  when hosting a native property page over which we have no color control.
>            'So now we simply use SystemColors.Control all the time (constant on …
> Add support for properly theming the property page controls

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/UserFileInterceptedProjectPropertiesProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/UserFileWithXamlDefaultsInterceptedProjectPropertiesProvider.cs
Using the AlwaysAvailable capability might mean that these components could get loaded in non-C#\VB\F# scenarios. Changing it to be specific to C#\VB\F#
Fixes https://github.com/dotnet/project-system/issues/1697
N\A
**Risk**
None.
None 
No
@dotnet/project-system @MattGertz for approval.
> Don't use the AlwaysAvailable capability

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Properties/CSharpProjectConfigurationPropertiesTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Properties/CSharpProjectConfigurationProperties.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/AbstractProjectConfigurationProperties.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests/ProjectSystem/VS/Properties/VisualBasicProjectConfigurationPropertiesTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/Properties/VisualBasicProjectConfigurationProperties.cs
Tagging @srivatsn @tmeschter @davkean @dotnet/project-system for review
Add CSharp and VB Project Configuration Properties. These are the Project Configuration Properties which backs the Automation Objects obtained through DTE. We need this change to support 2 scenarios(As of now, we have 2. There will be more.)
1. Enable Codefixer to change the Language Version of a C# version to newer version = #2137 
2. Enable changing the severity of an analyzer rule from the Analyzer Node - #2114 
Fixes #2137 Fixes #2114 Fixes #1919 
None
**Risk**
Low - we are enabling a feature which did not work previously.
Low - since the new code does not deal with allocations or any of the known hot paths
**Is this a …
> Add CSharp and VB Project Configuration Properties for Automation

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/CommandLineItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs
- Stop resetting workspace context for single TFM changes
- Pass 'removes' from failed design-time builds onto Roslyn
Partially fixes #2148 and refixes #1445.
We were making a couple of assumptions here;
1) **TFM changes are the only things that cause design-time builds errors (they aren't)**
The original fix of #1445 basically was a workaround, it attempted to reset the workspace context to avoid duplicate references/source files ending up in the workspace context. However, it was incomplete - design-time builds can break for any reason - so while we got a "fresh" start for TFM changes, other failed builds still caused us to be in an inconsistent state. Instead of doing this, and ignoring these design-time build results, we simply alway pass the results onto Roslyn - thereby removing all …
> [WIP] Stop resetting workspace context for single TFM changes

- src/Microsoft.VisualStudio.ProjectSystem.CSharp/ProjectSystem/LanguageServices/CSharpParseBuildOptions.cs
- src/Microsoft.VisualStudio.ProjectSystem.FSharp/ProjectSystem/LanguageServices/FSharpParseBuildOptions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/MetadataReferenceItemHandlerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/SourceItemHandlerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/BuildOptions.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic/ProjectSystem/LanguageServices/VisualBasicParseBuildOptions.cs
- Move properties below constructor
- Replace IEnumerable<T> -> ImmutableArray<T>
- We were boxing the ImmutableArray<T> unnecessarily.
- Remove "Common" from BuildOptions
- This was left over the original review.
> [LanguageService] Stop boxing ImmutableArray<T> in BuildOptions

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs
Stop tracking evaluation data for design-time builds, we're not using it. This was left over from the original language service that waited until design-time builds to push evaluation data to Roslyn. We don't.
> [LanguageService] Stop tracking evaluation data during design-time builds

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/SourceItemHandlerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractLanguageServiceRuleHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AdditionalFilesItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AnalyzerItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/CommandLineItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/MetadataReferenceItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/ProjectPropertiesItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/SourceItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ICommandLineHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IEvaluationHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHandlerManager.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/RuleHandlerType.cs
Moved the logic for updating language service handlers into separate component.
A future PR will move from each handler handling *all* contexts, to handling a single context.
Note: This change includes the handler renames - they make much more sense in a future PR where the command-line handling is merged into this new LanguageServiceHandlerManager component.
> [LanguageService] Move logic for updating "handlers" into a separate component

- build/Targets/GenerateAssemblyInfo.targets
@srivatsn @davkean @dotnet/project-system for review
In the image above, we should see the commit ID in the Product version field.
**Risk**
Low, since this does not affect the production code
None - This is infra change
Ad-hoc
> Use ShouldSignBuild instead of RunningInMicroBuild

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/ProjectPropertiesItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/SourceItemHandler.cs
Status checks aren't running on merges into non-mainline branches, missed this in a merge.
> [LanguageService] Fix build break due to bad merge

- build/Targets/References.targets
- src/Microsoft.VisualStudio.ProjectSystem.FSharp/ProjectSystem/LanguageServices/FSharpParseBuildOptions.cs
- src/NuGet.config
This enables simple F# command line parsing.  There are only 4 different things that can be parsed which makes this parser very small:
1.  Metadata references.  For fsc.exe these all start with `-r:` or `--reference:`.
2.  Analyzer references.  F# doesn't support these so it's always an empty collection.
3.  Source files.  Non-option arguments (e.g., no leading `-`) that end in `.fs`, `.fsi`, etc.
4.  Additional files.  F# doesn't support these so it's always an empty collection.
This required updating the Roslyn references to bring in the newly exposed constructors in `CommandLineSourceFile` and `CommandLineReference`.
@KevinRansom @davkean @srivatsn 
Edit: I've verified these changes locally along with dotnet/roslyn#19566.
> simple F# command line parser

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectValueDataSourceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/NuGet/ProjectAssetFileWatcherTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectAssetFileWatcher.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml
Today we get dataflow for some of the data but get other data by querying the project. This can lead to some race conditions and also causes us to load the catalog twice. This changes it to just query from dataflow. This will also fix the Watson crash where the project was unloaded when we were querying for the project data as we are not querying the project at all anymore
Fixes #645, Fixes #1768 and VSO 296591
None
**Risk**
Low 
Might improve perf since we won't compute catalogs twice.
No
Didn't understand that we couldn't mix dataflow and live project.
Code review.
@dotnet/project-system @natidea …
> Dont mix dataflow and querying live project in the ProjectAssetsFileWatcher

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandler.cs
We only update our book keeping of files after we've called Roslyn. This avoids us getting out of sync in the face of bugs.
> [LanguageService] Keep Roslyn/bookkeeping in sync

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ContextHandlerProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AdditionalFilesItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AnalyzerItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/MetadataReferenceItemHandler.cs
This implements the same behavior as legacy project system, however this is short term behavior. Long term behavior will be determined by https://github.com/dotnet/project-system/issues/2230.
This stops Roslyn throwing when we attempt to add duplicates, long term I would like these to be errors the same as the command-line.
> [LanguageService] Stop sending duplicate references, additional files and analyzers to Roslyn

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/AssemblyReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ProjectReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedAssemblyReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedProjectReference.xaml
Make sure we show the same set of properties for resolved and unresolved assembly references, and for resolved and unresolved project references.
In a .NET Standard or .NET Core project, if a customer clicks on an unresolved assembly or project reference they will see a different set of properties in the Properties window than they would on a resolved assembly or project reference. In some cases this prevents editing a property, because it just isn't there.
#1480 
Opening and editing the *proj file directly.
**Risk**
Low.
Little to no impact.
No.
Not clear. I imagine we've been more focused on just adding the properties needed …
> Fix reference properties

- src/Microsoft.VisualStudio.AppDesigner/PropPages/VSThemedLinkLabel.vb
- src/Microsoft.VisualStudio.Editors/MyExtensibility/MyExtensibilityPropPage.vb
- src/Microsoft.VisualStudio.Editors/PropPages/ServicesPropPage.Designer.vb
- src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsDesignerView.vb
Customers with certain vision impairments may not be able to properly read the text.
https://devdiv.visualstudio.com/DevDiv/_workitems?id=391644
None
**Risk**
Minimal, this just changes the color used by the link label controls to ensure they are accessibile.
Minimal to None
No
The VSThemedLinkLabel control assumed that the background color was itself themed. This was not the case for the majority of our property pages.
Known accessibility issue
Accessibility Tenant
> Updating the VSThemedLinkLabel to use SystemColors.HotTrack for pages that aren't themed.

- src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerView.resx
- src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerView.vb
For configuration pages, we need to ensure the configuration panel receives focus and not the property page itself. This allows a screen reader to give the page context before reading the values of any properties themselves. 
https://devdiv.visualstudio.com/DevDiv/_workitems?id=382395
User can first tab through the entire page.
**Risk**
Minimal. This just changes which control gets focus first.
Minimal to none.
No
Known accessibility issue.
Accessibility tenant.
> Updating the PropPageDesignerView to ensure the ConfigurationPanel gains focus first for config pages.

- build/Targets/VSL.Imports.targets
Every build of ProjectSystem.Managed and VSIX projects were unnecessarily copying extra files. Prevent that to speed up-to-date builds.
Also respected the same properties that we use in CopyFilesToOutputDirectory.
Note: I attempted to replace this target with the default copying that MSBuild does for `<None/>` without success. Spent over an hour debugging it and could not figure out why it wouldn't copy these items and gave up.
> [Infrastructure] Stop copying unchanged files

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/UnconfiguredProjectContextProvider.cs
This removes a [previous hack](https://github.com/dotnet/project-system/blob/360a009390105ad50695ae595ddb62dbd56b87b3/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/UnconfiguredProjectContextProvider.cs#L278) that enabled a project context to be created for F#.
**NOTE:** This PR is dependent upon dotnet/roslyn#19667 being merged _and_ inserted into official VS builds.
@srivatsn @KevinRansom
> remove hack around CreateProjectContext for F#

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Logging/ProjectOutputWindowProjectLogger.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Logging/IProjectLogger.cs
- Update xml docs for IProjectLogger to reflect IsEnabled changes
- Format the text *before* Forking, which avoids us throwing exceptions after we've forked and pushed to the UI thread
> [Logging] Format the text *before* Forking

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/cs/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/de/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/es/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/fr/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/it/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ja/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ko/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pl/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pt-BR/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ru/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/tr/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hans/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hant/NuGetRestore.xaml
Pass the property `EmitAssetsLogMessages` to NuGet to indicate that diagnostics will be emitted to error list through an SDK-based task, instead of through NuGet
When the changes in https://github.com/dotnet/sdk/pull/1228 are merged, SDK-based projects will see NuGet warnings repeated twice: once from the new task in that PR and once from NuGet's existing logger. We recently decided the mechanism to turn off the NuGet logging is to pass this flag which is set by the SDK. Legacy (none SDK) projects will continue to use existing NuGet logging.
Part of https://github.com/dotnet/project-system/issues/1660
Fixes https://github.com/dotnet/project-system/issues/2225
Users can filter out warnings without an Error code to hide the …
> Pass EmitAssetsLogMessages to NuGet

- src/Templates/Microsoft.NetCore.VB.ProjectTemplates/ClassLibrary.vstemplate
Customer is unable to determine difference between Vb Net Core class Library and VB netstandard class library as both have identical descriptions
https://github.com/dotnet/project-system/issues/2222
None
**Risk**
None
None
Yes
Copy/Paste error
ad hoc testing
> fix incorrect ID on VB NetCore project template

- src/Templates/Microsoft.NetCore.CSharp.ProjectTemplates/ClassLibrary.vstemplate
- src/Templates/Microsoft.NetCore.FSharp.ProjectTemplates/ClassLibrary.vstemplate
- src/Templates/Microsoft.NetCore.VB.ProjectTemplates/ClassLibrary.vstemplate
Fixes #2146
Project creation rolls up .NET Core class libraries, causing 3 types of class libraries to be presented to the user
https://github.com/dotnet/project-system/issues/2146
None
**Risk**
this change does not effect other parts of the project system.
None
Yes
Previously the VB project templates were rolled up a level and the C# ones were not.  The VB templates never got inserted into VS but were the implementation consulted when moving the templates to the project system repo
ad hoc testing
> Do not rollup .Net Core class library templates

- build/Targets/References.targets
- src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/Microsoft.VisualStudio.ProjectSystem.IntegrationTests.csproj
This gets rid of the NuGet restore downgrade warnings.
> Unify dependencies on LanguageServices

- src/Targets/Microsoft.Managed.DesignTime.targets
Tagging @srivatsn @RaulPerez1 @dotnet/project-system for review
This change does not affect any customer scenario. This change removes a hack that was placed in the product until the actual fix flowed from SDK and msbuild into the product.
Fixes #1772 
None
**Risk**
None. Just removing redundant code.
None. Nothing related to perf.
> Remove workarounds for Configurations in DesignTime Targets

- src/ProjectSystemSetup/ProjectSystemSetup.csproj
- src/Templates/Microsoft.NetCore.CSharp.ProjectTemplates.Test.Vsix/Microsoft.NetCore.CSharp.ProjectTemplates.Test.Vsix.csproj
- src/Templates/Microsoft.NetCore.CSharp.ProjectTemplates.Vsix/Microsoft.NetCore.CSharp.ProjectTemplates.Vsix.csproj
- src/Templates/Microsoft.NetCore.FSharp.ProjectTemplates.Test.Vsix/Microsoft.NetCore.FSharp.ProjectTemplates.Test.Vsix.csproj
- src/Templates/Microsoft.NetCore.FSharp.ProjectTemplates.Vsix/Microsoft.NetCore.FSharp.ProjectTemplates.Vsix.csproj
- src/Templates/Microsoft.NetCore.VB.ProjectTemplates.Test.Vsix/Microsoft.NetCore.VB.ProjectTemplates.Test.Vsix.csproj
- src/Templates/Microsoft.NetCore.VB.ProjectTemplates.Vsix/Microsoft.NetCore.VB.ProjectTemplates.Vsix.csproj
- src/Templates/Microsoft.NetStandard.CSharp.ProjectTemplates.Vsix/Microsoft.NetStandard.CSharp.ProjectTemplates.Vsix.csproj
- src/Templates/Microsoft.NetStandard.FSharp.ProjectTemplates.Vsix/Microsoft.NetStandard.FSharp.ProjectTemplates.Vsix.csproj
- src/Templates/Microsoft.NetStandard.VB.ProjectTemplates.Vsix/Microsoft.NetStandard.VB.ProjectTemplates.Vsix.csproj
- src/VisualStudioEditorsSetup/VisualStudioEditorsSetup.csproj
This broke recently and building projects was deploying to the Exp hive. 
@dotnet/project-system @jmarolf
> Deploy to the RoslynDev hive when not running integration tests

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Properties/CSharpProjectConfigurationPropertiesTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/AbstractProjectConfigurationProperties.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests/ProjectSystem/VS/Properties/VisualBasicProjectConfigurationPropertiesTests.cs
Tagging @dotnet/project-system @srivatsn for review
The default implementation of the configuration properties provided by CPS had this property implemented. Since these properties are accessed using String, we did not see other teams using this property.
This change implements OutputPath property so that people who were consuming this property can continue to use this property.
Customers using the automation object to get the OutputPath will be affected
#2293 vso_bug [441321](https://devdiv.visualstudio.com/DevDiv/_workitems?id=441321&fullScreen=false&_a=edit)
None.
**Risk**
Low risk. This is a simple implementation and the changes do not modify the behavior of any component.
**Is this a regression from a previous …
> Implement OutputPath for ProjectConfigurationProperties

- build/Targets/VSL.Imports.targets
- build/Targets/VSL.Versions.targets
- build/ToolsetPackages/InternalToolset.csproj
- src/ProjectSystemSetup/ProjectSystemSetup.csproj
We are seeing close solution take longer because the property pages are not optimized.  
https://devdiv.visualstudio.com/DevDiv/_workitems?id=360010
None
**Risk**
Minimal, this change is only about using the latest optprof data.
This should improve performance when these assemblies are ngen'd on install other than that there is no perf impact for assemblies that do not have optprof data.
No but this is a regression from Dev14
Optprof data was not setup for the project system repo
This was identified late in the cycle in a perf run
> pulling down optprof data and using it in our build

- src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerView.vb
- src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPageUserControlBase.vb
The experience is "visually poor" for unthemed property pages under one of the three default themes.
https://github.com/dotnet/project-system/issues/2288
None
**Risk**
Minimal, this just changes the default background color for unthemed property pages back to what it was before theming support was added.
None
Yes
There was a deployment bug in the project system repo
Ad Hoc Testing
> Updating the PropPageDesignerView and PropPageUserControlBase to use `SystemColors.Control` as the fallback/unthemed color.

- build/Targets/References.targets
- build/Targets/VSL.Imports.targets
This is an infrastructure change to move as many references to package refs as possible.
The following items still need to be converted to package refs:
```
VsWebSite.Interop
Microsoft.VSDesigner
Microsoft.VisualStudio.TemplateWizardInterface
Microsoft.VisualStudio.XmlEditor
Microsoft.VisualStudio.VSHelp
Microsoft.VisualStudio.DataTools.Interop
```
> updating project system to use package refs when available

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AnalyzerItemHandler.cs
In the refactoring we broke analyzers and were passing them as additional files.
tag @dotnet/project-system
> Pass analyzers to Roslyn as analyzers

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/NuGetRestorer.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/DisposableBag.cs
NuGet restore fails for multi-tfm projects. This has regressed because of a change in CPS. We setup a dataflow block that synchronizes on version of each TFM's project to get the information about packagerefs\projectrefs that we send to NuGet. CPS made a change where they added an identity for that project as part of the version. This causes the versions of the sources to never be in sync and so we never call NuGet. The fix chains in a block into nuget restore dataflow that removes the identity from the version. We also remove the ConfiguredProjectVersion from the version because that's also not guaranteed to sync between the projects and cause sporadic restore failures.
Fixes https://github.com/dotnet/project-system/issues/1503
**Workarounds, …
> Make nuget restore work again for multi-tfm projects

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.Designer.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.resx
Addresses customer confusion between the Launch url and the application url in web projects. 
https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=220227
N/A
**Risk**
Just changing the name of the label from Launch url to Launch browser.
None
No
customer reported
> Remove confusion about launch Url and application Url

- src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPage.resx
- src/Microsoft.VisualStudio.Editors/PropPages/BuildEventsPropPage.resx
- src/Microsoft.VisualStudio.Editors/PropPages/ReferencePathsPropPage.resx
Users relying on screenreaders will not understand the name and purpose of the button if the name property is inappropriate.
https://devdiv.visualstudio.com/DevDiv/_workitems?id=441876
None
**Risk**
Low, this just changes the text displayed from "..." to "Browse...", which is inline with what we do elsewhere
None
No
Known accessibility issue
Accessibility Tenant
> Fixing some of the property pages to use "Browse..." rather than "..."

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedAnalyzerReference.xaml
If a project includes an analyzer where the path is not normalized, then it shows up with a warning icon in solution explorer. This can happen with nuget packages for eg where extra backslashes can get appended.
The cause of this bug is that the dependencies node first gets the unresolved reference and then the resolved reference and it matches the OriginalItemSpec on the resolved reference to see if there's an unresolved reference corresponding to it. If so, it shows the resolved one. In the case of Analyzers, we were using the FullPath property for the OriginaltemSpec which is normalized. So it wouldn't match the unresolved reference path if that wasn't normalized. Switching to the Identity property just gets the evaluated value of whatever was in the project file. …
> Fix warning icons that show up incorrectly some analyzers in solution explorer.

- src/Microsoft.VisualStudio.Editors/ResourceEditor/Resource.vb
This is a bit of a hack to allow the designer to work properly with netstandard2.0 projects.
Our multi-targeting support quite correctly tells us that types like System.String are found
in netstandard.dll. However, VS (and thus the resx designer) and resgen.exe run on the net462
framework, which does not have a netstandard.dll. As such the designer doesn't understand the
types involved and crashes while trying to create or update resource strings. Even if we
could get past that, resgen.exe would see the references to netstandard.dll in the .resx
file, fail to locate it, and die while trying to produce the .designer.cs file.
The workaround here is to check if the assembly-qualified type name refers to a type in
netstandard.dll, and if it does swap in mscorlib.dll instead. This allows the …
> Redirect netstandard types in the designer

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/BuildUpToDateCheck.cs
In a project with Content files that are CopyToOutputDirectory Never (for example, web projects), we fail the fast up to date check always because we are checking files that are never copied to the output.
#2345
None, fast up to date check doesn't work.
**Risk**
Low, this makes a scenario that doesn't work, work.
Low, just checking an extra field when collecting inputs/outputs.
No
Ad hoc testing
> Don't check files that aren't copied for fast-up-to-date check

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/cs/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/de/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/es/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/fr/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/it/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ja/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ko/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pl/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pt-BR/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ru/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/tr/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hans/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hant/NuGetRestore.xaml
These additional properties will be used to pass source and fallback folders from the SDK to NuGet restore.
https://github.com/NuGet/Home/wiki/%5BSpec%5D-NuGet-settings-in-MSBuild
Fixes #2360 
N/A
**Risk**
Low, another pair of values added to project property bag.
No
More properties emerging from NuGet work
/cc @dotnet/project-system 
/cc @Emgarten
> Pass additional fallback folder properties during nominate

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/BuildUpToDateCheck.cs
A user adds or removes files from a .NET Core project that uses globs. The project system thinks the project is up to date and doesn't build it when the user requests a build.
#2347 
User would have to manually touch the project file to make it out of date.
**Risk**
Low, only affects the bug scenario.
Low, doesn't change the amount of work we're doing for up to date checks.
No
Ad hoc testing
> Fail fast up to date check if items changed

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/cs/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/de/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/es/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/fr/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/it/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ja/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ko/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pl/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pt-BR/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ru/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/tr/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hans/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hant/NuGetRestore.xaml
Another property for NuGet, AssetTargetFallback,  is the successor for PackageTargetFallback and will be used by the SDK to allow compatibility with net461 for netcoreapp2.0
#2363 
N/A
**Risk**
Low
No 
/cc @dotnet/project-system 
/cc @emgarten
> Pass AssetTargetFallback during nomination

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/cs/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/cs/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/de/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/de/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/es/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/es/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/fr/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/fr/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/it/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/it/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ja/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ja/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ko/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ko/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pl/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pl/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pt-BR/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pt-BR/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ru/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ru/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/tr/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/tr/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hans/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hans/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hant/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hant/NuGetRestore.xaml
If a user goes to the build property pages and enters a warning number in the "Treat Warnings as errors" textbox then those warnings weren't being treated as errors.
This is because the prop page was persisting the warnings to a property called TreatSpecificWarningsAsErrors in the project file - however, the compiler only understands a  `WarningsAsErrors` property. Making the prop page persist the warnings as WarningsAsErrors instead.
@natidea @emgarten - note that this means that NuGet needs to read the WarningsAsErrors property as well. I've updated the nomination rule as well so that we send WarningsAsErrors to NuGet.
https://devdiv.visualstudio.com/DevDiv/_workitems?id=435264&_a=edit&triage=true
Manually edit the …
> Make warnaserror work from the property pages.

- src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerView.vb
- src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/DesignerTabButton.vb
- src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/DesignerTabControl.vb
- src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/DesignerTabControlRenderer.vb
- src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/PropertyPageSite.vb
- src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerView.vb
Customers who rely on keyboard navigation will not be able to navigate through the available property pages.
https://devdiv.visualstudio.com/DevDiv/_workitems?id=409661
None
**Risk**
Low, this adds the DesignerTabControl to the list of tab stops, but it requires some manual focus invocations to get it functioning with the existing codebase.
Low, this only adds a couple of additional checks on the existing code paths to determine if the keyboard based navigation is being used.
No
Known accessibility issue
Accessibility Tenant
> Updating the DesignerTabControl to allow keyboard navigation on the DesignerTabButton(s)

- build/Targets/VSL.Imports.targets
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/MetadataReferenceItemHandlerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/SourceItemHandlerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AdditionalFilesItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AnalyzerItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/MetadataReferenceItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/ProjectPropertiesItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/SourceItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ICommandLineHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IEvaluationHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHandlerManager.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Logging/ProjectLoggerExtensions.cs
Added logging to the language service. With logging turned on we fire up a "project" category, and log something like the following for evaluation/design-time builds:
```
Processing language service changes for 'C:\Users\davkean\Source\Repos\ConsoleApp27\ConsoleApp27\ConsoleApp27.csproj' [Debug|AnyCPU]...
Version:         0
Source:          DesignTimeBuild
IsActiveContext: True
Processing rule 'CompilerCommandLineArgs'...
Last design-time build suceeeded, turning semantic errors back on.
Options: /reference:C:\Users\davkean\.nuget\packages\system.buffers\4.3.0\lib\netstandard1.1\System.Buffers.dll /warn:4 /reference:C:\Users\davkean\.nuget\packages\system.runtime.interopservices.runtimeinformation\4.3.0\ref\netstandard1.1\System.Runtime.InteropServices.RuntimeInformation.dll /warnaserror- …
```
> [Logging] Language service logging

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml
Visually impaired users wont be aware about the name of the element.
https://devdiv.visualstudio.com/DevDiv/_workitems?id=408106
None
**Risk**
Minimal. This just adds a new attribute which is only used by accessibility tools
None. This just adds a new attribute which is only used by accessibility tools
No
Known accessibility issue
Accessibility Tenant
> Adding the remaining AutomationProperties.Name attributes to the DebugPropertyPage.

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/MockIDependenciesTreeServices.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/TreeView/GroupedByTargetTreeViewProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GroupedByTargetTreeViewProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/IDependenciesTreeServices.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/IDependenciesTreeViewProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/DependenciesViewModelFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/TreeViewProviderBase.cs
After installing one of the 15.3 Previews customers will start experiencing more "random" UI delays in normal VS operations including:
- Expanding nodes in Solution Explorer
- Add new and removing items to and from the tree
- Opening C# source files
- Opening XML files
- Typing
- Opening and closing the solution
This particular case is tracked by: https://github.com/dotnet/project-system/issues/2389 and affects cross-targeting projects..
None
**Risk**
Low. This simply replaces an _async -> synchronous -> async_ call with _async -> async_.
This will …
> 	Remove JoinableTaskFactory.Run usage in GetRule

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContextProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/UnconfiguredProjectContextProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectAsyncLoadDashboardExtensions.cs
Users may experience a hang when closing a project if the `ProjectLoadedInHost` task is still pending. This is because the Dependency node and Language service wait on this task, and it never resolves if the project is unloaded beforehand.
[Bug 395991](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/395991) VS hung when closing solution
N/A occasional hang
**Risk**
Low. The fix wraps the task in a helper that cancels the task if an Unload cancellation token is triggered
Low
The instance in the language service has existed for multiple releases, however the instance in the dependency node was introduced in 15.3. The call stack …
> Fix Hang on VS Close (Enable ProjectLoadedInHost waits to be cancelled)

- docs/repo/debugging-tips.md
Add some notes on how to test a locally-produced SDK with msbuild.exe and VS. This is only a change to the repo documentation.
> Add notes on testing a locally-produced SDK

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/ConfigurationProjectConfigurationDimensionProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/PlatformProjectConfigurationDimensionProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/TargetFrameworkProjectConfigurationDimensionProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/AssemblyInfoPropertiesProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Build/LanguageServiceErrorListProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/OutputTypeExValueProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/OutputTypeValueProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests/ProjectSystem/VS/Properties/MapDynamicEnumValuesProviderTests.cs
`async void` methods do not return a `Task` object which xUnit could possibly examine for exceptions. xUnit cannot even track the completion of a particular `async void` method, as opposed to an `async Task` method.
Moreover, `async void` methods do not throw exceptions on the same stack frame, even for exceptions thrown from the synchronous part of the method. Rather, exceptions are propagated to the current synchronization context via `SynchronizationContext.Post` (in case `SynchronizationContext.Current != null)`, or otherwise via `ThreadPool.QueueUserWorkItem`.
This is an infrastructure only change.
> remove async void test methods

- src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPage.Designer.vb
- src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPage.vb
Visually impaired users may get confused when focus order is not in logical
https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems?id=448943
None
**Risk**
Low, this just ensures a text box when the corresponding radio button is not checked
None
No
Accessibility issue
Accessibility Tenet
> Ensure that the ManifestExplanationLabel is disabled when the corresponding radio button is unchecked

- src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPage.vb
Visually impaired users who depend on keyboard will not be able to access radio button by using up down arrow
https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems?id=448954
Exclusively use the Up arrow key to navigate between radio buttons.
**Risk**
Low. This just updates the handling of the Up/Down arrow keys to explicitly move between the radio buttons
Low.
Partial.
Previously, pushing down would move focus from the first radio button to the second and pushing 'Up' would move focus back. However, pushing 'Down' a second time would not move focus back and would instead move to the Resource File text box.
Presently, pushing …
> Updating the ApplicationPropPage to properly cycle through the radio buttons

- src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/DesignerTabButton.vb
Users who rely on the narrator will not know when the DesignerTabButtons get focus.
https://devdiv.visualstudio.com/DevDiv/_workitems?id=409661
Use a different narrator (such as NVDA)
**Risk**
Low. This just updates the accessibility object to properly report that the control is focusable.
None
No
It was thought that the Windows Narrator not reading the control text was due to a bug in Windows Narrator. It was later determined that it is because Windows Narrator is dependent on the accessibility object reporting that a control is focusable (where-as other narrators just read the text of the currently focused object).
**How was …
> Updating the custom accessibility object for DesignerTabButton to properly report 'Focusable'

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/DiagnosticDependencyModelTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependencyTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/UnsupportedProjectsSnapshotFilterTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/DiagnosticDependencyModel.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Dependency.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/UnsupportedProjectsSnapshotFilter.cs
Customers observe spurious and confusing warning icons in dependency node when there should not be any, or do not observe warning icons when there should be. This collection of small targeted fixes addresses the most common cases, including:
- referencing a .NET Framework project always warns even though these P2P refs are valid, which is a regression from 15.2
- valid P2P refs sometimes do not expand (particularly to cps-based .NET Framework projects) because of invalid IDs being passed around
- (NuGet) diagnostics do not bubble up correctly
One side-effect: P2P references to incompatible projects should have a warning icon but does not (however, there are warning messages in the error list). Three separate bugs in NuGet, SDK and Project System are preventing this …
> Fix spurious warnings in dependency node

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/TargetFrameworkProvider.cs
Customer notices that projects take a very long time to load.
Fixes https://github.com/dotnet/project-system/issues/2421
None
**Risk**
This is changing MEF imports so I would need manual verification of the scenario to ensure that nothing has regressed.
**Regression**
This is a perf regression in 15.3 because of new code in the dependencies node.
This will improve perf for project load and restore.
Perviously we would switch to the UI thread, acquire the component catalog, and manually pick out the types we needed from the catalog while still on the UI thread.  Since we were in a pumping wait this would not deadlock the operation, but all threads waiting for this opertation …
> remove OnceInitializedOnceDisposed and instead import services via MEF

- src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/BuildUpToDateCheck.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ProjectItemsSchema.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/UpToDateCheckInput.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/UpToDateCheckInput.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/UpToDateCheckOutput.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/UpToDateCheckOutput.xaml
- src/Targets/Microsoft.Managed.DesignTime.targets
In the old project system, a project file can specify UpToDateCheckInput and UpToDateCheckOutput items that add items into inputs or outputs that the fast up-to-date check uses. It's a kind of escape hatch for special project extensions that the project system is not aware of.
Fixes #2380 
In cases where these items would be used, the user would have to manually rebuild if their project was out of date but the project system didn't see it that way.
**Risk**
Low, it just adds two new item types that are only used in exotic situations.
Low, only impacts exotic situations.
No.
> Up-to-date checks: UpToDateCheckInput and UpToDateCheckOutput

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/cs/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/de/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/es/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/fr/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/it/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ja/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ko/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pl/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pt-BR/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ru/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/tr/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hans/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hant/NuGetRestore.xaml
NuGet requests us to pass this property during nomination. SDK uses this to set the target framework used to restore cli tools, and NuGet [reads this property](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L306) when restoring with `GetRestoreDotnetCliToolsTask`
Fixes #2427 
N/A
**Risk**
None
No
New request from NuGet
> Nominate DotnetCliToolTargetFramework to NuGet 

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/IDependenciesSnapshotFilter.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/ImplicitTopLevelDependenciesSnapshotFilter.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySubscriptionsHost.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Build/BuildUtilities.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectXmlAccessor.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/MSBuildXmlAccessor.cs
After installing one of the 15.3 Previews customers will start experiencing more "random" UI delays in normal VS operations including:
- Expanding nodes in Solution Explorer
- Add new and removing items to and from the tree
- Opening C# source files
- Opening XML files
- Typing
- Opening and closing the solution
This particular bug is tracked by: 2379
None
**Risk**
Low. 
This will reduce UI delays and reduce the number of active threads.
Yes, the dependency node was rewritten in 15.3.
**Root cause …
> Remove synchronous call in DependencySubscriptionsHost

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetSubscriptionHostBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/SemaphoreSlimExtensions.cs
After installing one of the 15.3 Previews customers will start experiencing more "random" UI delays in normal VS operations including:
- Expanding nodes in Solution Explorer
- Add new and removing items to and from the tree
- Opening C# source files
- Opening XML files
- Typing
- Opening and closing the solution
This particular issue is being tracked by: https://github.com/dotnet/project-system/issues/2383.
None
**Risk**
Low.
This will reduce UI delays and reduce the number of active threads.
Yes, the …
> Fix VS becomes unresponsive opening large project

- build/Targets/VSL.Imports.targets
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
This removes most usage of ExecuteSynchronously from LaunchSettingsProvider, which can cause threadpool exhaustion. In some dumps debugging sessions that I investigated for Roslyn/ProjectSystem I saw large amounts of threads (> 60) waiting on these paths. 
After installing one of the 15.3 Previews customers will start experiencing more "random" UI delays in normal VS operations.
This particular PR fixes https://github.com/dotnet/project-system/issues/1342
None
**Risk**
Low. 
This will reduce UI delays and reduce the number of active threads.
**Is this a regression from a …
> Remove ExecuteSynchronously from LaunchSettingsProvider

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Compile.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/cs/Compile.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/de/Compile.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/es/Compile.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/fr/Compile.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/it/Compile.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ja/Compile.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ko/Compile.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pl/Compile.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pt-BR/Compile.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ru/Compile.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/tr/Compile.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hans/Compile.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hant/Compile.xaml
Copying a file from the legacy project system (say .NET Framework/UWP) to new the project system (.NET Core) would display an error:
```
---------------------------
Microsoft Visual Studio
---------------------------
"FullPath" is a reserved item metadata, and cannot be redefined as a custom metadata on the item.
---------------------------
OK   
---------------------------
```
Fixes: #2386
Manually copy the file using file explorer, and then manually add the same metadata that was applied to in the original project.
**Risk**
Very Low
None
Yes, this was regressed when we added the fast up-to-date check.
We don't have great …
> Mark FullPath as read-only

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetSubscriptionHostBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs
`_tasksService.LoadedProject()` assumes that all logic run inside the using is correct and never causes a deadlock.  `_tasksService.LoadedProjectAsync` explicitly uses JTF to ensure no deadlocks occur.
`GetService` blocks the calling thread where as `GetServiceAsync` will try several techniques to acquire the service in a non-blocking way before falling back to a blocking approach.
`AddSubscriptionsAsync` was locking but then calling asynchronus methods and not waiting for them to complete.  This could have led to races or interactions with the project after it had closed.
@davkean to double check my understanding of this threading code
Ask mode template forthcoming
> fixing up some threading cases

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/BuildUpToDateCheck.cs
As of recent builds of d15prerel, the up to date check for SDK-based projects is broken due to composition errors.
None, up to date checks won't work.
**Risk**
Low, restores functionality that is broken.
Low, restores functionality that is broken
Yes
The up to date checker imports a contract through MEF from CPS. This contract had two scopes associated with it, but the up to date checker didn't specify a scope on import. This worked by accident until changes on the CPS side caused this bug to surface. The fix is to add a proper scope to the import.
Ad hoc testing.
> Fix contract for up to date check

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchSettingsProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchSettingsProvider2.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AppDesignerFolderSpecialFileProvider.cs
Opening certain ASP.NET Core projects can deadlock.
Unloading and reloading an ASP.NET Core project always deadlocks.
Partially fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/index?id=451907. ASP.NET tooling also need to make a change on their side.
For projects that open first time, a workround is not to unload/reload project.
For projects that don't open first time, there is no workaround.
**Risk**
Low. Changing async -> sync -> async to async -> async.
Low perf impact, no extra complexity.
Yes
In a previous change, https://github.com/dotnet/project-system/pull/2317, we introduced a new code path that caused a …
> Add public async replacement for LaunchSettingsFile

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/PostBuildEventValueProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/PreBuildEventValueProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Utilities/StringExtensions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/AbstractBuildEventValueProvider.AbstractBuildEventHelper.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/AbstractBuildEventValueProvider.Helper.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/AbstractBuildEventValueProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/PostBuildEventValueProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/PreBuildEventValueProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
User wants to have their pre-build and post build events use MSBuild variables but they are evaluated as empty strings without this fix
https://github.com/dotnet/project-system/issues/1569
https://github.com/dotnet/project-system/issues/1879
User can manually modify their project file.
**Risk**
this only affects the project file if the user writes pre or post build events from the properties pages.  risk is low.
Code is only called when the user changes the value in the property page.  Risk is low.
It is a regression from the native project system
Targets are now implicitly imported to MSBuild variables do not exist.  The fix …
> make pre build events post build events work using targets

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/BuildUpToDateCheck.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml
- src/Targets/Microsoft.Managed.DesignTime.targets
The user's SDK-based project uses a ruleset as input to project analyzers. The user changes the ruleset to include rules that would cause the project to no longer build due to new errors. The user builds but because we didn't take into account the change to the ruleset, we think the project is up to date and the build is incorrectly successful.
Fixes #2374 
User would have to perform a rebuild.
**Risk**
Low, this just adds a new file into the up to date check. Biggest risk is that we would think a project was not up to date when it was, resulting in calling MSBuild.
Low, looks at one additional file.
No.
> Add ruleset as input to fast up to date

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedPackageReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/cs/ResolvedPackageReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/de/ResolvedPackageReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/es/ResolvedPackageReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/fr/ResolvedPackageReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/it/ResolvedPackageReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ja/ResolvedPackageReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ko/ResolvedPackageReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pl/ResolvedPackageReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pt-BR/ResolvedPackageReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ru/ResolvedPackageReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/tr/ResolvedPackageReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.cs.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.de.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.es.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.fr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.it.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.ja.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.ko.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.pl.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.pt-BR.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.ru.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.tr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.zh-Hans.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.zh-Hant.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hans/ResolvedPackageReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hant/ResolvedPackageReference.xaml
Customers using 15.3 will see new, more organized warnings from NuGet, including NU1605 package downgrade warnings. Users can suppress these and other warnings globally through the property pages or using XML in the project file. Users can also suppress these warnings per package, but right now this can only be done through using XML in the project file.
NuGet requested that we make it possible to edit this property from the Property Grid when the user selects the package in solution explorer. After some investigation, this ended up being a simple change to the ResolvedPackageReference XAML rule file. While there, we also made it possible to edit some more properties: IncludeAssets, ExcludeAssets and PrivateAssets. The new property grid looks like:
**Bugs this …
> Enable per-package warning suppression using Properties Pane

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependencyFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependencyTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TestDependency.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Dependency.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/ImplicitTopLevelDependenciesSnapshotFilter.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/IDependency.cs
Implicit package references show up in the dependency tree with an expander arrow:
However the package does not expand to reveal its dependencies/contents as other package references do. 
This specifically applies to implicit package references that are set in an imported target file -- the dependency node makes them implicit by cloning the original dependency and changing some properties in the model. A bug in the cloning process meant that the resulting dependency IDs were of the form `tfm\provider\tfm\provider\modelId` instead of `tfm\provider\modelId`. This bug would also affect any other places where this cloning occurs, such as when a package reference is aliased.
Additionally, fixing this bug revealed that making a node implicit changes the icon (to a locked …
> Show contents of implicit package references (regression)

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/DependencyModelTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependencyTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TestDependency.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/TreeView/GroupedByTargetTreeViewProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/TargetFramework.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependencyNodeInfo.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/DependencyModel.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Dependency.cs
Call through StringComparer.GetHashCode instead of allocating a string to get its hash code.
I also:
- Removed unneeded checked blocks
- Did not fix DependencyModel.GetHashCode which doesn't look well distributed.
> Stop allocating in GetHashCode

- src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb
1. Add a new RESX resource file, add a new empty PNG image resource. Save and close Resource Editor.
2. Immediately double click on the RESX file to open Resource Editor.
3. Result: 'Parameter is not valid' error.
https://devdiv.visualstudio.com/DevDiv/_workitems?id=452557
Wait for a short period of time and launch Resource Editor again.
**Risk**
Low, this change affects a private class of Resource Editor View.
Low performance impact because the assets returned by Image Service may stay a little bit longer, but GC will collect them because Image Service only keeps weak references to them.
Regression from VS 2015.
- Resource …
> Fix 'Parameter is not valid' error when reopen Resource Editor

- build/Targets/VSL.Versions.targets
- build/build.proj
FYI. @jmarolf, @dotnet/project-system
> Updating VSIXExpInstaller to 0.4.0-beta and ensure we explicitly uninstall old (locally-deployed) vsixes before installing new ones.

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/BuildUpToDateCheck.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheckLogger.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/CopyToOutputDirectoryType.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckItemComparer.cs
A project -- for example, Roslyn -- has files that are either Content or None. These files are not handled correctly and either cause up to date to fail when it shouldn't (more common), or cause up to date to succeed when it shouldn't (less common). Building Roslyn in an up-to-date state still results in about 12 projects getting MSBuild called when it should be 0.
**Description of fix**
This fix:
- No longer looks at the Content output group as it doesn't actually give any useful values.
- No longer looks at Content/None files when calculating the up-to-dateness of the project output (i.e. .dll or .exe) since they are not part of the build.
- If any kind of file is marked to always be copied to the output directory, we always fail the up to date check. This is …
> Handle non-compilations files correctly in up to date check

- build/Targets/VSL.Versions.targets
- build/build.proj
- src/DeployIntegrationDependencies/DeployIntegrationDependencies.csproj
- src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/Microsoft.VisualStudio.ProjectSystem.IntegrationTests.csproj
This enables a few things:
- Integration dependencies are now deployed on build
- You can change the version of roslyn that deploys with the `RoslynIntegrationVsixVersion` variable under `build/Targets/VSL.Versions.targets`
- You can disable integration deployment entirely if you have binaries installed to a custom hive by setting the condition on the `DeployIntegrationDependencies` target to always be false.
> have deploy project install vsixes

- src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS/ProjectSystem/VS/Properties/FSharpProjectDesignerPage.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/cs/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/cs/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/de/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/de/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/es/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/es/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/fr/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/fr/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/it/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/it/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ja/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ja/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ko/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ko/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pl/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pl/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pt-BR/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pt-BR/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ru/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ru/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/tr/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/tr/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hans/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hans/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hant/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hant/GeneralConfiguredBrowseObject.xaml
The application page needs rules for a couple of F# specific properties around FSharp core versions.
The build page was not marked as configuration-specific and that was causing it to blow up. Also added a rule for Tailcalls which is the only F# specific property in that page.
There are still three things left to do but they all require changes outside of this repo:
- https://github.com/Microsoft/visualfsharp/issues/3276 - The TargetFramework dropdown is empty in the application page. This is because it asks the multi-targeting service for the TFMs and the multi-targeting service doesn't know about .NET Core\Standard. We made a [change to C#\VB pages](https://github.com/dotnet/project-system/pull/2097/commits/aee40ba336d0b94a20f416060213e0b9cf6369a1) augment that list from the SDK. The …
> Make F# application and build prop pages work

- src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS/ProjectSystem/VS/Imaging/FSharpProjectImageProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS/ProjectSystem/VS/Imaging/FSharpSourcesIconProvider.cs
For F# NetCore projects, solution explorer doesn't show the F# icons - makes it hard to distinguish between fs and fsi files.
None
**Risk**
Low - just adds an icon provider for the fs, fsi and fsx extensions
Low - just adds an icon provider for the fs, fsi and fsx extensions
No, this is part of the F# .NET Core support.
> Make the F# icons show up in solution explorer for F# source files

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContext.cs
Certain projects consumes large amount of CPU while the project is open.
There are many ways to represent a "friendly name" of a target framework in the `<TargetFrameworks>` element. For example, .NET Framework 4.0, can be represented as:
``` XML
<TargetFrameworks>net4</TargetFrameworks>
```
-or-
``` XML
<TargetFrameworks>net4.0</TargetFrameworks>
```
-or-
``` XML
<TargetFrameworks>net40</TargetFrameworks>
```
If you enter a form that is not canonical from what we get from NuGet (ie the first two), we continually process data forever, consuming larges amounts of CPU. 
Fixes https://github.com/dotnet/project-system/issues/2388
Change the element to be in the canonical form. It is not obvious this is the cause.
**Risk**
Low …
> Fix VS consumes large amount of CPU 

- build/Rulesets/NonShippingProjectRules.ruleset
- build/Rulesets/Roslyn.ruleset
- build/Targets/Settings.targets
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/DebugProfileEnumValuesGeneratorTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/DebugProfileDebugTargetGenerator.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/DebugProfileEnumValuesGenerator.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Logging/ProjectOutputWindowProjectLogger.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectAssetFileWatcher.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/TargetFrameworkMonikerValueProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/GetProfileNameDialog.xaml.cs
Tuned off the following in our codebase:
- VSTHRD010 this analyzer has a list of vs services that it believes must be called on the UI thread.  Perhaps this is the true, in which case our codebase has a major problem
- VSTHRD103 analysis here seems faulty.  The only cases it caught were false positives where we had named methods similarly but the async version was not equivalent to the sync version.
- VSTHRD200 we not follow this convention in the codebase so I left it off.
> Adding threading  analyzers.

- src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/DesignerTabButton.vb
The user who completely rely on the keyboard, won't know which control has focus when using the Up/Down keys to navigate.
https://devdiv.visualstudio.com/DevDiv/_workitems?id=409661
Use Tab/Shift+Tab rather than Down/Up
**Risk**
Minimal, this just updates the code to additionally display focus cues when navigation happens via the Up/Down keys.
None
No, this was missed in the original fix.
Navigation via up/down was not listed as a requirement in the original bug.
Accessibility
> Fixing the AppDesigner TabButtons to show focus cues when navigation happens via Up/Down.

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/ProjectRuleHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/StringComparers.cs
We were searching all project's top-level dependencies to determine if we need to update the toplevel dependency. In some projects in Roslyn and ProjectSystem, this can be up to hundred dependencies and can result in a lot of garbage due to the allocations in GetActualPath.
Fixes part of https://github.com/dotnet/project-system/issues/2533.
This reduces the amount of allocations in this path from 500 KB -> 100 KB opening ProjectSystem.sln.
Note, there's still a lot of wins to be had in GetActualPath which allocates a lot for what it's doing, I'm tracking that via: https://github.com/dotnet/project-system/issues/2536.
> Only look at projects when updating Dependencies -> Projects

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/IDependencyExtensions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/ManagedPathHelper.cs
We were making two allocations (GetDirectoryName, EnsureTrailingSlash) calling PathHelper.MakeRooted to handle a case it already handles for us.
Given a base path, "C:\Project\Project.csproj" and path "Foo.cs", it already returns "C:\Project\Foo.cs"
- There are already unit tests for these cases.
- Partially fixes: https://github.com/dotnet/project-system/issues/2533. There are still more wins to be made inside of MakeRooted itself.
> Reduce 20% of allocations opening ProjectSystem.sln

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IProjectTreeExtensions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GroupedByTargetTreeViewProvider.cs
- Rewrote FindNodeByPath to reduce three allocations; OfType iteractor, Func<T, TResult> and the class to carry the captured tree. This reduces allocations by 3.3% (65 MB) opening ProjectSystem.sln.
- Renamed it to be consistent with existing methods on IProjectTree itself.
A change to the FindNodeByCaption will occur in a different change as it's not perf related, and not a fast path.
> Rewrite FindNodeByPath to reduce allocations

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Logging/ProjectOutputWindowProjectLoggerTests.cs
This was resulting in a warning during test runs.
> Remove a duplicate test

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GroupedByTargetTreeViewProvider.cs
Simplify FindByPathInternal  …
In CPS project tree terms, the dependency node looks like this (with only ever 3 nodes deep)
Dependencies
Analyzers
Analyzer
Projects
Reference
We were attempting to walk into the children of Analyzer and Reference - even though that code never gets hit.
Replaced this walk with just a call to GetSelfAndDescendentsBreadthFirst - it's simpler and ends up resulting in the exact same number of allocations (5) as we're not walking each child's children twice.
> Simplify FindByPathInternal

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/TreeView/GroupedByTargetTreeViewProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GroupedByTargetTreeViewProvider.cs
When called via IVsProject.IsDocumentInProject/ParseCanonicalName/IProjectTreeProvider.FindByPath, we walking the tree twice:
- Once with the path we were passed (ie C:\Project\Foo.cs")
- Once with the path we were passed, but relative to the project directory (Foo.cs, or ..\Analyzer.dll)
The later will never result in a match as we were comparing against "IProjectTree.FilePath" which is always a rooted path.
> Stop walking dependency tree twice

- build/Targets/References.targets
- build/Targets/Settings.targets
- build/Targets/VSL.Versions.targets
- src/Common/Integration/App.config
- src/DeployIntegrationDependencies/DeployIntegrationDependencies.csproj
- src/NuGet.config
This resolves https://github.com/dotnet/project-system/issues/2528
I am waiting to hear back from @jasonmalinowski, @Pilchie, or @jaredpar on whether Roslyn is staying 2.6.0 or if it will be moving back to 2.5.0
> Updating the Roslyn dependencies to 2.6.0-beta1-61907-05

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/IDependencyExtensions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/ProjectRuleHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/ManagedPathHelper.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/StringComparers.cs
User experiences UI delays and general performance delays during solution load and for a short period afterwards. Changes to projects, such as changing branches or installing/changing NuGet packages can also cause delays.
https://github.com/dotnet/project-system/issues/2533.
No workaround.
**Risk**
Low.
This reduces the amount of data we allocate opening a solution and for a short period after we open by 39%.
Opening Roslyn.sln, and waiting for ~9 minutes after it has loaded (until we'd stopped processing data) this made the following improvements:
|Metric|Before Fix|After Fix|Reduction|
|----|---:|---:|---:|
|% CPU Time paused for GC|16%|10.5%|35%
|Total CPU Time paused for GC|82 secs|54 secs|34% …
> Reduce the amount of data we're allocating on project open by 39%

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphProvider.cs
The type returned here are immutable, not mutated and we don't need to recreate the enumerator every time it's called.
> Cache DependenciesGraphProvider.GetCommands

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/ProjectRuleHandler.cs
A bad merge from 15.3 -> master resulted in us filtering twice. Taking the change rom 15.3 as it removed two allocations.
> Stop filtering dependencies twice

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectThreadingServiceMock.cs
The reflection code doesn't do anything useful. The property info it fetches isn't actually used to call the property getter.
> Remove useless code in IProjectThreadingServiceMock

- src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/DesignerTabButton.vb
Customer closes a solution with the property page still open, reopens the solution, and then tries to navigate to a new tab using the keyboard.
Ticket: https://devdiv.visualstudio.com/DevDiv/_workitems?id=466671
Bug: https://devdiv.visualstudio.com/DevDiv/_workitems?id=467800
User can close the property page, close and reopen the solution, and then reopen the property page.
**Risk**
Minimal
None
New functionality which was fixing an accessibility bug
It seems that the `System.Windows.Forms.Control.ShowFocusCues` property has some odd behavior, such as returning `true` if the underlying handle has not been created yet.
**How …
> Fixing the DesignerTabButton to only use `Focused` and `GotFocusFromKeyboardNav` when determining whether to draw focus cues.

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/cs/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/de/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/es/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/fr/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/it/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ja/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ko/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pl/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pt-BR/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ru/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/tr/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hans/NuGetRestore.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hant/NuGetRestore.xaml
Needed to support Escrow NuGet scenario
#2605 
N/A
**Risk**
Low
None, just adding another rule
No
Requested by partner team
/cc @srivatsn 
/cc @emgarten
> Add exclude source and fallback folder properties to restore nomination

- src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ApplicationDefinition.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ApplicationDefinition.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Page.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Page.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ProjectItemsSchema.xaml
- src/Targets/Microsoft.Managed.DesignTime.targets
FYI. @Srivatsn, @dotnet/project-system 
Still waiting on final confirmation from the CPS guys, but it seems like the following is true:
* For any item type to display in the solution explorer, you must define a rule file and have an 'ItemType' entry in a ProjectSchemaDefinition file.
* For an extension to have a default item type (other than none) you must define a rule file and have a 'FileExtension' entry in a ProjectSchemaDefinition file.
> Adding Rule files and ProjectItemsSchema entries for 'ApplicationDefinition' and 'Page' files.

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/AppDesignerFolderSpecialFileProviderFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AppDesignerFolderSpecialFileProvider.cs
Fixes: 461771.
We were deadlocking by switching to the UI thread while DebugProfileDebugTargetGenerator is trying to calculate it's data. Avoid calling into SpecialFilesManager.GetFiles which goes via IVsProjectSpecialFiles on the UI thread, and just call the AppDesignerSpecialFileProvider directly.
This is just a targeted change, with the real change to be switching to an entirely dataflow chain of providing this data. See: #2316.
> Avoid deadlock in DebugProfileDebugTargetGenerator

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependencyFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependencyExtensionsTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependencyTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TestDependency.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/UnsupportedProjectsSnapshotFilterTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/ViewProviders/ProjectGraphViewProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Dependency.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/UnsupportedProjectsSnapshotFilter.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/IDependency.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/IDependencyExtensions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/ProjectRuleHandler.cs
This reduces the number of total allocations to TryMakeRooted from approx 9.1% (141 MB) of opening/closing solution -> 0.3% (2 MB), by introducing a new property called FullPath on IDependency that is cached and remembered between calls. This is called and only accessed for top level dependencies.
> Reduce allocations in OnOtherProjectDependenciesChanged significantly

- src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsDesigner.vb
- src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/Win32FileSystem.cs
`GetDirectories` and `GetFiles` call `Enumerate` -> `new List` -> `ToArray` to get the `string[]`
Since the result is then `foreach` over, just go direct to Enumerate.
> Enumerate rather than GetDirectories/GetFiles

- build/Scripts/copyOutput.cmd
Instead publish to an internal nuget feed. This step will be a microbuild step.
The microbuild team will be stopping the write access to \\cpvsbuild shortly and publishing through internal feed will be the only way to do it.
Since we are not making significant changes to the Editors and AppDesigner which are the nugets used in VS, it is ok to not publish the packages momentarily until the nuget task is added. This work also be tracked by the same issue #2607 
fixes 2607 
Adding @dotnet/project-system for review
> Stop publishing nugets to Cpvsbuild directly

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfile.cs
Addresses issue: https://github.com/dotnet/project-system/issues/1125
Native debugging is enabled by adding "nativeDebugging" : true to the launch profile as follows
```
{
"profiles": {
"ConsoleApp3": {
"commandName": "Project",
"nativeDebugging": true
}
}
}
```
This property will automatically be picked up by the LaunchSettingsManager and added to the OtherProperties property bag. This change does not add any UI support.
> Add support for native debugging

- build/Scripts/copyOutput.cmd
Infrastructure Only change
Port #2642 to dev15.4.x to fix build break
> Stop publishing to Cpvsbuild directly

- build/SignToolData.json
- build/Versions.props
The build produces two kinds of VSIXes - ones marked "experimental" the others not. We need to sign both.
Fixes VS insertion.
> Sign VSIXes inserted into VS

- build/Versions.props
Update to the latest version of ModifyVsixManifest that correctly updates hash in the patched VSIX. See https://github.com/dotnet/roslyn-tools/pull/50
> Fix VSIX manifest hashing

- build/Versions.props
VSIX hashes in vsman files need to be calculated after signing. Fixes insertion validation failure.
Change in RepoToolset: https://github.com/dotnet/roslyn-tools/pull/51
> RepoToolset v36 - fix vsman hashes

- build/build.ps1
MicroBuild machines now have msbuild 15.3, which supports binary log.
> Use msbuild binlog in MicroBuild

- src/Targets/Microsoft.Managed.DesignTime.targets
Adding this capability enables the WinRT References service which knows
how to handle the WinRT assemblies
Customer cannot add Winmd references to .Net Core/Standard projects through Reference Dialog
#2495
The users can hand edit the project file
**Risk**
The risk is low because the impact is localized
Should enable a few services in CPS but it should not affect perf significantly
Customer reported
> Add WinRTReferences Project capability

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
Customer builds a test project and it always shells out to MSBuild and is never considered up-to-date from within Visual Studio.
Customer adds an item to a project, and changes "Copy to Output Directory" to "Copy if Newer" and now the project always shells out to MSBuild and is never considered up-to-date from within Visual Studio.
#2717
#2743
No workarounds.
**Risk**
Low.
Low, and very little impact.
No.
Up-to-date is new and we missed a few cases in our implementation.
Customer bugs and we also found it in testing.
> Fix up-to-date for "Copy to output directory" items

- build/build.ps1
This will help us diagnose why microbuild jobs fail on some lab machines.
> Print location of msbuild in CI build

- build/SignToolData.json
- src/Microsoft.VisualStudio.AppDesigner/Directory.Build.props
- src/Microsoft.VisualStudio.AppDesigner/Microsoft.VisualStudio.AppDesigner.vbproj
- src/Microsoft.VisualStudio.Editors/Directory.Build.props
- src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj
- src/VisualStudioEditorsSetup/Directory.Build.props
We used wrong certificate for signing Editors and AppDesigner assemblies.
> Fix strong name and certificate for Editors, AppDesigner

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/cs/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/de/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/es/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/fr/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/it/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ja/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ko/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pl/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/pt-BR/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ru/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/tr/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hans/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/zh-Hant/GeneralBrowseObject.xaml
This change will ensure back compat. This is similar to the change #2223
FullPath property used to return the path of the project folder with a slash at the end. With the new project system, the FullPath property was backed by a MSBuild property which did not end with the slash. This breaks all the components that consumed the FullPath property based on the assumption that the path ends with a slash. To ensure back compatibility, this change will bring back the old behavior of returning the project folder path with a slash at the end.
This issue was found as part of the bug #2344 where path parsing was getting messed up because of the change in the value provided for the property Project FullPath
#2344
Edit the path of …
> Fullpath property backed by property ProjectDir, which ends in a slash

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/SdkDependencyModelTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/SdkDependencyModel.cs
Currently we include the version number in the caption for _package_ items under the Dependencies node in Solution Explorer, like this:
> StyleCop.Analyzers (1.0.2)
However, we don't do the same thing for items under the SDK node. In this case the model for SDK dependencies supports a version number; we just need to update the caption to show it.
Note that the SDK dependencies are ultimately backed by items produced by the `CollectSDKReferencesDesignTime` task in the [dotnet/sdk](https://github.com/dotnet/sdk) repo, and these items currently do not include `Version` metadata. That will go in as a separate change (see https://github.com/dotnet/sdk/pull/1572), and only once both of these changes come together will you see the version number in Solution Explorer. …
> Show version number for "SDK" packages in Solution Explorer

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetSubscriptionHostBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/TargetFramework.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySubscriptionsHost.cs
Using a non-canonical name as your target framework (for example, net4.7 instead of net47) results in VS continually consuming CPU.
https://github.com/dotnet/project-system/issues/2713
[VSFeedback](https://developercommunity.visualstudio.com/content/problem/105265/high-cpu-usage-with-a-tiny-project-opened.html) | [488045](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/488045)
Use a canonical name in `<TargetFramework>` property, however, it is not an obvious workaround.
**Risk**
Low.
This stops CPU spinning forever - so improves performance a lot.
Regression from 15.2 -> 15.3.
Dependency tree was rewritten in 15.3, as …
> Using non-canonical name results in high CPU usage

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
Commit 334dcf6a updated us to consume a 15.5 version of the CPS
binaries. This includes changes to support specifying a sort order on
tree nodes, needed by F#.
When we moved over our calls in the Dependencies tree code
to the `NewTree` method started binding to new overloads that can take
a value indicating a sort order, and return an instance of the new
`IProjectTree2` or `IProjectTreeItem2` interfaces. However, these new
overloads aren't available at runtime on VS builds prior to 15.5,
leading to "method not found" exceptions when trying to run locally
built project-system bits on top of a 15.4 Preview VS.
Since there are no publicly available 15.5 builds and the Dependencies
tree doesn't need to specify its own sort order, this commit updates
the calls so we will use the overloads …
> Use NewTree overloads available prior to 15.5

- src/ProjectSystemSetup/ProjectSystemSetup.csproj
.NET Core users cannot see icons in dependency tree. This is because the setup authoring of Project System changed to place its components in `Common7\IDE\CommonExtensions\Microsoft\VisualStudio\Editors`. This fixes the incorrect setup authoring.
[495585](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/495585)
None
**Risk**
Low, puts things back the way they were in 15.4
None, puts things back the way they were in 15.4
Yes, from 15.4
Likely copy-and-paste error from recent refactoring of our build system infrastructure to use https://github.com/dotnet/roslyn-tools.
Vendor validation
**Dev …
> Remove extension installation root and folder from ProjectSystemSetup

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/GetProfileNameDialog.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.Designer.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageResources.resx
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.cs.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.de.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.es.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.fr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.it.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.ja.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.ko.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.pl.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.pt-BR.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.ru.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.tr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.zh-Hans.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/xlf/PropertyPageResources.zh-Hant.xlf
Users who depend on localization may not be able to create new debug profiles.
https://devdiv.visualstudio.com/DevDiv/_queries?id=473107&triage=true&_a=edit
None.
**Risk**
Low.
Low
No
This was likely missed when the localization effort was done.
Customer reported
> Updating the GetProfileNameDialog to support localization.

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContextProvider.cs
Fixes NRE in AggregateCrossTargetProjectContextProvider
Customers using barebones CPS projects without a TargetFramework do not see an expandable dependencies node. This fix unblocks some CTI team tests.
[426406](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/426406)
Add a target framework to the template
**Risk**
Low. This prevents a Null Reference Exception
Low, this is not a mainline scenario for us.
Yes, Regressed in 15.3 after rewriting dependencies node
`GetTargetFramework` can return null, but not all code paths accounted for this. I went through and looked at the other paths as well to confirm …
> Return empty target framework when one is not found

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PackageReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedPackageReference.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.cs.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.de.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.es.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.fr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.it.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.ja.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.ko.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.pl.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.pt-BR.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.ru.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.tr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.zh-Hans.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/PackageReference.xaml.zh-Hant.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.cs.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.de.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.es.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.fr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.it.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.ja.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.ko.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.pl.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.pt-BR.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.ru.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.tr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.zh-Hans.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ResolvedPackageReference.xaml.zh-Hant.xlf
We already have the Path to a PackageReference, we just need to surface it in the Properties window by making it a visible property.
Also adds a description.
Note that this only adds the Path to the Properties window for top-level NuGet packages in Solution Explorer. Nested NuGet packages are internally represented as graph nodes, and these have a completely different mechanism for surfacing properties. We don't have time to implement that for 15.5, but this simply change will still be a big (albeit incomplete) improvement.
Customer adds a NuGet package to a .NET Core or Standard project, then selects the package's node in Solution Explorer and examines its properties. The resolved path to the NuGet package does not show.
Related to #927. …
> Show paths to PackageReferences

- build/Versions.props
We found an issue with the CPS SDK where `ProjectTypeRegistrationAttribute` would generate this key in the pkgdef: 
```
[$RootKey$\NewProjectTemplates\TemplateDirs\{3347bee8-d7a1-4082-95e4-38a439553cc2}\/1]
@="#1"
"SortPriority"=dword:00000064
```
This key is the old way of supplying project templates to VS, which has been replaced with assets in vsix manifest. It is causing an images loaded regression, and since the key is not needed we are removing it. See the CPS PR [here](https://mseng.visualstudio.com/VSIDEProj/_git/VSIDEProj.CPS/pullrequest/261699?_a=overview) which removes the key and explains all the issues with it.
Regression in New Project. CPS assemblies are needlessly loaded.
[Perf: ManagedLangs_CS_DDRIT.0800.Close Solution regressed …
> Update CPS Sdk, removing uneeded pkgdef key

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Telemetry/VsTelemetryServiceTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/DesignTimeTelemetryLogger.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/DesignTimeTelemetryLoggerProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/TargetRecord.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/VsTelemetryService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/ITelemetryService.cs
This adds telemetry to record target performance for design-time builds. This helps us determine problems that customers are seeing with design-time builds.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/492017
None.
**Risk**
Low. This adds a logger that matches the one that exists in the native project system (most the code is the same).
Low, the logger only listens to target events and sticks them in a dictionary. We already do this on the native side.
No.
> Add design time telemetry for managed project system

- build/Versions.props
- src/DeployIntegrationDependencies/DeployIntegrationDependencies.csproj
- src/DeployTestDependencies/DeployTestDependencies.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.csproj
- src/ProjectSystemSetup/ProjectSystemSetup.csproj
- src/Templates/Directory.Build.props
- src/VisualStudioEditorsSetup/VisualStudioEditorsSetup.csproj
Infrastructure only change. 
The new version comes with a fix for including OptProf data and more efficient symbol store publishing.
It introduces PublishOutputToSymStore property that is true by default and can be set to false for projects whose outputs (DLL/EXE/PDB) should not be published to symbol server (non-shipping binaries).
> Update to RepoToolset 43

- build/Versions.props
- src/Directory.Build.props
- src/ProjectSystemSetup/ProjectSystemSetup.csproj
Visual.Studio.Editors dll is larger on disk when install completes NGEN than previous builds.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/495600
None
**Risk**
With new optimization data Visual.Studio.Editors will be aboutl half the size on disk.
Yes.
Optimization data goes out of date over time as code changes.  We crossed a threshold where our old data wasn't being used.
Detected by Regression Prevention System
> updating project system optimization data

- docs/design-time-builds.md
This is a documentation-only change but I wanted to run it by @davkean. This adds a pointer to the build log viewer for VS 2017 15.4+ in the design-time build recommendations.
> Update documentation on how to diagnose design-time issues

- src/Templates/Microsoft.NetCore.FSharp.ProjectTemplates.Test/MSTest.vstemplate
- src/Templates/Microsoft.NetCore.FSharp.ProjectTemplates.Test/XUnitTest.vstemplate
- src/Templates/Microsoft.NetCore.FSharp.ProjectTemplates/ClassLibrary.vstemplate
- src/Templates/Microsoft.NetStandard.FSharp.ProjectTemplates/ClassLibrary.vstemplate
The Icons for F# Net Sdk class library and test libraries. were wrong.
This gets them from the F# project system.
> Fix Icon for F# templates and F# Test Templates

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedPackageReference.xaml
Customers adding NuGet packages through the NuGet package manager see version in "Element" style instead of "Attribute" style. This is a regression from 15.4.
[507675](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/507675)
N/A
**Risk**
Low, just updates some data source properties for the Version rule, similar to what was done in https://github.com/dotnet/project-system/pull/728
None, and returns VS to 15.4 behavior
Yes
This is ultimately a limitation in CPS. It is not able to distinguish between PackageReference.xaml and ResolvedPackageReference.xaml for representing package references, and has just been selecting the …
> Add attribute persistence style to Resolved Package References

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsProjectDesignerPageService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/ProjectDesignerServiceTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/ProjectDesignerService.cs
Avoid COM interface in SupportsProjectDesigner.
Avoiding calling through the COM interface in SupportsProjectDesigner to fix #2911.
> Avoid COM interface in SupportsProjectDesigner

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Imaging/CSharpProjectImageProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Imaging/CSharpProjectImageProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS.UnitTests/ProjectSystem/VS/Imaging/FSharpProjectImageProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Imaging/AppDesignerFolderProjectImageProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests/ProjectSystem/VS/Imaging/VisualBasicProjectImageProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/Imaging/VisualBasicProjectImageProvider.cs
This lets non-managed projects opt-into the AppDesigner folder and have the correct icon show.
Fixes: #2948.
> Make AppDesigner icon show outside of C#/VB

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectTreeCustomizablePropertyContextFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Order/TreeItemOrderPropertyProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Order/TreeItemOrderPropertyProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Order/TreeItemOrderPropertyProviderSource.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/CommonConstants.cs
Needed for FSharp projects where the order of source files in the project file is significant, and should be reflected in the solution explorer. This implementation also accounts for folders by pre-ordering each sub folder and item. The limitation of this is that duplicate folders in different parts of the tree will receive the same ordering.
FSharp .NET Core projects list source files in alphabetical order in the solution explorer. But the order in the project file is significant and should be preserved to facilitate program comprehension.
#2793 
[517046](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/517046)
N/A
**Risk**
Low, changes only applied to projects that declare the `SortByDisplayOrder` capability
**Is …
> Implement dataflow to order solution tree by display order property.

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/ITelemetryServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetRuleSubscriberBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyTreeTelemetryService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/IDependencyTreeTelemetryService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs
This change supercedes https://github.com/dotnet/project-system/pull/2879
This implements simplified telemetry to detect resolved dependency tree based on whether the corresponding snapshot has unresolved dependencies.  It includes a telemetry service that maintains some light state for each Target Framework to keep track whether all expected rules have been observed; this information is passed as a property of the telemetry event and can be used to determine if the 'resolved' event is fired too early (so sessions can be appropriately filtered).
Dependency node population can be slow in some solutions. This telemetry can be used to get statistical information about how long it takes to populate the Dependencies node. The telemetry will be used as part of planned A/B …
> Implement basic resolved dependency tree telemetry

- src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPageUserControlBase.vb
- src/Microsoft.VisualStudio.AppDesigner/interop/NativeMethods.vb
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VsProject.cs
Implementing ConnectionPoint to enable AppDesigner to receive property change notifications. This works in combination with new implementation on the CPS side.
Current change delegates the connection point implementation to the CPS implementation.
Note that AppDesigner also expects that CSharpProjectConfigurationProperties implements connection point. This change does not address that additional work. 
#1259
Close and reopen app designer will usually refresh the values displayed.
**Risk**
Low
Performance impact is driven by the CPS implementation.
CPS doesn't specify which individual property has changed. That means, AppDesigner will refresh all properties. Also, for correctness, CPS may trigger the …
> Connection point support

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ConfiguredProjectReadyToBuild.cs
Handle when there is no active config during solution load.
Fixes: https://github.com/dotnet/project-system/issues/2895 and https://github.com/dotnet/project-system/issues/2437
> Avoid ArgumentNullException

- build/Versions.props
This moved the project system to build with the same compilers that ship in the 15.5 previews.
> update toolset compilers and analyzers

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DuplicatedDependenciesSnapshotFilterTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/DuplicatedDependenciesSnapshotFilter.cs
NOTES: Look at last two commits only - the rest are just things from `master` that need to come into `post-dev15.5`.
Opening a large solution a lot of entries in the dependencies nodes.
#2596 
none
**Risk**
Low - just re-wrote some code to avoid `string.Format` and Linq.
Currently this method is responsible for 6.6% of the allocations involved in opening the project-system repo. 
No
Need more performance tests for new project system
Profiling
> Reduce allocations in DuplicatedDependenciesSnapshotFilter.BeforeAdd

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs
When debugging multiple dotnet core applications, when the first one exits, all the others are terminated as well. E.g. an aspnet core web app, and a dotnet core console and starting both in the same debug session. Once the console exits the web application is terminated as well.
This change allows debuggin to continue if one of the applications being debugged terminates.
see: https://developercommunity.visualstudio.com/content/problem/88707/debugging-multiple-dotnet-core-applications-all-te.html
> Allow debugging multiple donet core apps

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckItemComparer.cs
When a project has a content file that has the <Link> metadata, that metadata can change the file's relative path or name in the output directory. The fast-up-to-date check doesn't look at that metadata, so it always thinks such files are out of date. This causes ~23 projects in Roslyn never to be considered up to date.
#2413 and #2518 
None, short of removing the file from the build.
**Risk**
Low. Currently up-to-date checks don't work with these files, the worst that would happen is it still would not work.
None, we're still checking the same number of files.
No.
Ad hoc testing.
> Fix up to date check for linked files

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.CSharp.DesignTime.targets
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.VisualBasic.DesignTime.targets
FYI. @Pilchie, @davkean.
This resolves https://github.com/dotnet/project-system/issues/256.
I've also tagged you on the CPS side change.
> Adding the 'ClassDesigner' capability to the C# and VB design time targets.

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IMockDependenciesViewModelFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/DependenciesViewModelFactoryTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContextProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/ITargetFramework.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/TargetFramework.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/TargetDependencyViewModel.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/ProjectRuleHandler.cs
In preparation for removing short name comparisons (https://github.com/dotnet/project-system/issues/2795), clean up ITargetFramework to remove unused code.
> Cleanup TargetFramework

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/MetadataReferenceItemHandler.cs
Write a different message when adding an assembly that is embedded vs referenced.
> Log difference between link/reference

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IFileSystemMock.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/IFileSystem.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/Win32FileSystem.cs
This is in response to this customer feedback item: https://developercommunity.visualstudio.com/content/problem/145118/specifying-dotnet-for-the-executablepath-in-launch.html
From my investigation this could never have worked reliably in Visual Studio as there was no code to resolve where to find non-rooted exes.  To support cross-platform solutions, it is necessary to avoid putting in paths or file extensions when specifying the executable.
So, the change is if the specified exe has no path separator elements, it will append .exe if not already specified, and check the current working directory first (I verified that if the VS process working directory contains the exe, it works today), otherwise search the path for the exe. If the exe can't be found it does what it …
> Add logic to resolve non-rooted exe's specified in a profile

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/NuGetRestorer.cs
Add logging for NuGetRestorer to capture information sent to NuGet during nomination
To assist investigations of problems in interactions between project-system and NuGet, add logging to specify what information is sent. Users can turn on logging with existing `set PROJECTSYSTEM_PROJECTOUTPUTPANEENABLED=1` flag
**Risk and Performance impact**
None, only active when debugging flag is on
> Add logging for NuGetRestorer

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Legacy project system displays duplicate items in solution explorer for files that are included in EmbeddedFiles item group in order to be embedded to the PDB.
VSO [490111](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/490111)
Set the Visible attribute manually in .csproj file
Small.
None.
Customer reported.
N/A
> Hide EmbeddedFiles

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHandlerManager.cs
Opens a solution with LUT enabled and CPS based projects, but LUT is unable to use it's cache, since projects don't have their references set yet.
None directly in this repo.
Manually restart LUT.
**Risk**
Low - just re-ordering some events.
Should improve LUT startup, since the cache should be able to be re-used more often.  This may also help support batching of events for initializing the language service during solution load .
No
Missing performance tests.
Performance investigations
> Don't set design time build flag until after processing changes

- .editorconfig
Enforce our [current naming styles](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md) via .editorconfig.
Ended up filing the following bugs as result of this:
["pascal_case" capatilization style only enforces "first_word_upper"](https://github.com/dotnet/roslyn/issues/23706)
[Should be able to specify two naming styles for a given symbol](https://github.com/dotnet/roslyn/issues/23707)
[Cannot refer to "private protected" in "applicable_accessibilities"](https://github.com/dotnet/roslyn/issues/23709)
[Add a way to enforce naming of type parameters](https://github.com/dotnet/roslyn/issues/23710)
[Add real world examples to "Naming Conventions for EditorConfig" topic ](https://github.com/MicrosoftDocs/visualstudio-docs/issues/378)
> Enforce naming styles via .editorconfig

- .editorconfig
See: https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md.
> We only use var when it's obvious what the variable type is (i.e. `var stream = new FileStream(...)` not `var stream = OpenStandardInput()`).
> Turn off "var" suggestion when not apparent

- src/ProjectSystemSetup/Properties/launchSettings.json
Turn on native debugging for the project system by default.
> Turn on native debugging

- build/Versions.props
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/TargetFrameworkProjectConfigurationDimensionProvider.cs
One of many changes as we move to using the new IActiveConfigurationGroupService which returns all the configurations that we consider "active" for a multi-targeting scenarios (replacing IActiveConfiguredProjectsProvider).
- Mark "target framework" as a variant dimension
This marks "target framework" dimension as a variant dimension; ie a configuration dimension that when present is effectively ignored when calculating "active configurations" returned by IActiveConfigurationGroupService:
For example, given the following multi-targeting project:
-> All known project configurations:
Configuration Platform    TargetFramework
-------------------------------------------
Debug |   AnyCPU  |           net45
Debug |   AnyCPU  |           net46
Release |   AnyCPU  |           net45
Release | …
> Mark "target framework" as a variant dimension

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ProjectItemsSchema.xaml
The presence of the generator in the item schema for embedded resources, overrides the extensibility point in CPS which allows project extenders to block adding a single file generator, or change the generator which is used.
Verified C# and VB projects continue to apply the generator with this entry removed. 
F# didn't apply the generator before this change and I verified it continued to work as before.
> Remove hardcoded generator

- src/DeployIntegrationDependencies/DeployIntegrationDependencies.csproj
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests/Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.FSharp.UnitTests/Microsoft.VisualStudio.ProjectSystem.FSharp.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.FSharp.VS.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/Microsoft.VisualStudio.ProjectSystem.IntegrationTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.UnitTests/Microsoft.VisualStudio.ProjectSystem.VisualBasic.UnitTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests.csproj
In the move to the new toolset (fcca201) two things changes;
- Tests no longer caused the product binaries to be deployed. This resulted in tests running against previous versions of the product. Add back references to the DeployXXXDependencies projects.
- Test projects had a default namespace that matched their project name. Add back the previous default namespace.
> Make sure product binaries are deployed when tests are built

- build/Versions.props
This enables parallel project load for .netcore projects (our ProjectTypeRegistrationAttribute will generate a new key in the pkgdef to point to the CPS prefetch factory). Parallel loading is a new feature in 15.6 that gives project system authors a chance to pre-load their projects before the solution calls CreateProject. How it works is the solution will call into CPS with the information of all projects we will be loading for a given solution (that say they enable prefetch support). CPS will then begin loading all projects on the background in parallel (we will limit it to 1-4 projects at a time). In testing Roslyn.sln, this provided a ~5s improvement during solution load.
I hope to bring this change into 15.6 preview 2 (escrow)
N/A - I can …
> Update CPS SDK, enabling parallel load for .netcore projects

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IActiveConfigurationGroupServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IConfigurationGroupFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectCommonServicesFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IUnconfiguredProjectTasksServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectValueDataSource.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectValueDataSourceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ActiveConfiguredProjectsLoaderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredProjectsLoader.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ForceLoadActiveConfiguredProjects.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IUnconfiguredProjectTasksService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UnconfiguredProjectTasksService.cs
(this depends on and includes https://github.com/dotnet/project-system/pull/3020, just look at the last commit)
CPS always force loads the _active_ configuration during project initialization and when the active configuration changes. This makes sure that any `ConfiguredProjectAutoLoad` services are created and run.
This is the equivalent, except for all configurations that we consider "active".  For example in the following multi-targeted project:
```
-> All known project configurations:
Configuration Platform    TargetFramework
-------------------------------------------
Debug |   AnyCPU  |           net45
Debug |   AnyCPU  |           net46
Release |   AnyCPU  |           net45
Release |   AnyCPU  |           net46
-> Active solution configuration:
Debug |   AnyCPU
```
These …
> Force load active configured projects

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphProviderFactory.cs
Prevent multiple DependenciesGraphProvider instances from being created
Multiple DependenciesGraphProvider instances were being created because Progression imports IGraphProvider as non-shared, while IDependenciesGraphActionHandler were importing as shared. This resulted in IGraphProvider and IDependenciesGraphActionHandler  seeing different instances.
This was never issue because IDependenciesGraphActionHandler instances never relied on DependenciesGraphProvider being initialized when they called it. In #3063 this changed though and broke this.
> Prevent multiple DependenciesGraphProvider instances from being created 

- build/Default.ruleset
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectDebuggerProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageElementHost.cs
Fixes #241.
<details>**Customer scenario**
**Risk**
(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")
**Is this a regression from a previous …
> Re-enable CA1825 - Don't allocate zero length arrays

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphProvider.cs
Fixes: https://github.com/dotnet/project-system/issues/3054.
The image service is free-threaded and thread-safe for registration APIs, stop blocking a background thread to switch to the UI, instead grab the service during initialization and register in background.
Also simplified the way we register the icons to avoid requiring a lock and lots of intermediate objects.
~**Note**: This is currently blocked due to multiple instances of DependenciesGraphProvider being created due to progression importing the parts as non-shared, and so that the thing that registers the icons is actually a different instance from the thing that gets initialized by progression. Fixing this now.~ 
Fixed in https://github.com/dotnet/project-system/pull/3064.
> Prevent blocking background thread to register image monikers in dependency node 

- src/ProjectSystemSetup/ProjectSystemSetup.csproj
Project system binaries are not profiled by Optprof, and later optimized, because they are not installed into a well defined path. Instead they are dropped into an anonymous path under  `Common7\IDE\Extensions`
Fixes #2850 
N/A
**Risk**
Low
Will eventually improve performance after profiling
No
> Move project system to well defined path

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs
Changed the  default working directory to be the output folder rather than the project root.  This addresses issue https://github.com/dotnet/project-system/issues/2239.
Note that there is a very slight behavior change. If the executable path specified in the profile is a relative path, it is assumed to be relative to the working directory (whether is comes from msbuild, the profile, or the default). This means that if no working directory is specified, it is now relative to the output directory rather than the project root - which I think makes more sense anyway.
> Change default working directory to the output folder

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
After opening a project, it takes two builds of a .NET Core/.NET Standard project before the fast up to date check will recognize the project is up to date.
#2698 
None. User has to build twice.
**Risk**
Low, this fix just loads the up to date checker when the project opens rather than when the project first builds.
This doesn't add any work but moves it slightly earlier (after project opens rather than after project first builds).
No.
Ad hoc testing.
> Fix second up to date build

- build/Versions.props
Fixes version overflow in signed build caused by new year.
> Update RepoToolset to 1.0.0-beta-62503-02

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/NuGetRestorer.cs
Replace IActiveConfiguredProjectsProvider usage with IActiveConfigurationGroupService, which means that the NuGetRestorer will now react correctly to changes in active configs, such as switching from debug -> release. Also removes all knowledge that TFM drives config changes.
Moving this to a dynamic component (to react to PackageReferences) will occur in a follow up change.
Fixes: https://github.com/dotnet/project-system/issues/2217.
> Replace IActiveConfiguredProjectsProvider usage

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/NuGetRestorer.NuGetRestorerInstance.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/NuGetRestorer.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AbstractProjectDynamicLoadComponent.AbstractProjectDynamicLoadInstance.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AbstractProjectDynamicLoadComponent.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs
Turns NuGetRestorer into a dynamic component based on the PackageReferences capability.
This is replacement of https://github.com/dotnet/project-system/pull/2479 by @jmarolf.
Fixes: #2231 and first item of #2491.
Note this includes https://github.com/dotnet/project-system/pull/3093, so only review from https://github.com/dotnet/project-system/pull/3097/commits/799fdabd1e5ff1619c60c2d5c497aa180f268a2c onwards.
> Make NuGetRestorer a dynamic component

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/NuGetRestorer.NuGetRestorerInstance.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/NuGetRestorer.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/PackageRestoreInitiator.PackageRestoreInitiatorInstance.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/PackageRestoreInitiator.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AbstractProjectDynamicLoadComponent.AbstractProjectDynamicLoadInstance.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AbstractProjectDynamicLoadComponent.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs
This includes https://github.com/dotnet/project-system/pull/3093 and https://github.com/dotnet/project-system/pull/3097, so only look at https://github.com/dotnet/project-system/commit/06def82e15666294f75c71f25b16c237202d8271 and https://github.com/dotnet/project-system/commit/1f23b3f3005fc0df2b55510f1800f9e12fca5332.
Rename NuGetRestorer to PackageRestoreInitiator to be better describe what it actually does; it does not perform a package restore, it only initiates it.
> Rename NuGetRestorer -> PackageRestoreInitiator

- src/Microsoft.VisualStudio.Editors/PropPages/AssemblyInfoUtils.vb
SemVer 2.0.0 package versions should be supported, but an error is shown when saving the project properties, if the package version has build metadata.
Fixes #2591
N/A
**Risk**
Low
Low, this PR only adds an additional Split operation on package version validation.
No
Packages didn't support SemVer 2.0.0 versioning.
Customer reported
> Added support for SemVer 2.0.0 metadata in package version.

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
When creating a shared project, there is a NullReferenceException in the up to date checker.
#3096
None.
**Risk**
Low, fixes a null reference exception by not pre-loading the up to date checker for shared projects.
None.
Yes,
We have a work item to create a test for up to date. #2452 
Ad hoc testing.
> Don't instantiate up to date for shared projects

- src/Microsoft.VisualStudio.Editors/PropPages/ReferencePropPage.vb
Fixes internal bug 509520 - an automatic crash dump for an IndexOutOfRangeException.
I *suspect*, though can't tell from the crash dump I've been looking at that the issue here
is that the VSLangProj "Imports" collection has a different number of items than what is
passed to the compiler and retrieved from the compilation.
To fix, I cleaned up the logic, and stopped relying on the data from the compiler, instead
just collecting the items from the VSLangProj "Imports".
<details>
(either VSO or GitHub …
> Clean up the logic to save the imports in the VB references page.

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectAccessor.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectAccessor.cs
IProjectXmlAccessor is an unconfigured project service that also acts upon other different unconfigured projects, as well as a grab bag of methods that should just be extension methods on a core API. It was added so that we could unit test taking a lock and has organically grown. This API is stab at pulling out the core pieces of which extension methods/helpers can be built on top.
Future PRs will replace IProjectXmlAccessor usage.
NOTE: This helper exists because the APIs are not unit testable, hence there are no unit tests.
> Add IProjectAccessor as replacement for IProjectXmlAccessor

- build/Versions.props
1) Fixes issue with publishing insertion manifests, which is blocking insertion.
2) Updates PDB converter to the latest version. This new version includes SourceLink in the converted Windows PDBs along with legacy srcsvr info. The former is picked up by VS Debugger the latter by WinDBG (which ignores SourceLink). This change will allow to debug Roslyn with Windows PDBs without enabling legacy srcsvr in VS debugger options.
**Risk**
Small.
None.
> Update RepoToolset to 1.0.0-beta-62506-01

- build/Versions.props
Infrastructure only change: The toolset supports building SourceLink for code imported from latest Roslyn source packages.
> Update RepoToolset to 1.0.0-beta-62512-01

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
The customer makes a change to their .NET Core project and runs. The project system thinks the project is up to date and doesn't rebuild, so the customer doesn't see their changes.
#3050 
Customer has to do a rebuild.
**Risk**
Low, this is correcting a call into CPS that was wrong.
None, makes things work the way they're supposed to.
Yes.
The underlying CPS code we call will sometimes return correct results even with incorrect parameters, so the fact we were passing in the wrong parameter was masked during testing.
Customer report
> Fix dataflow for up to date output groups

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs
This addresses issue: https://github.com/dotnet/project-system/issues/3139 
**Risk**
This is low risk. 
None
No
As described in the issue, this was not found before because all the custom UI controls were shared across the same launch type (IIS express in this case). IIS Express server bitness is per profile and why that showed up.
Found during ad-hoc testing
> Inform UIProviders when profile changes

- src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/UpToDateCheckBuilt.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/UpToDateCheckBuilt.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.cs.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.de.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.es.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.fr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.it.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.ja.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.ko.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.pl.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.pt-BR.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.ru.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.tr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.zh-Hans.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.zh-Hant.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
There are a number of scenarios where the up to date check fails for projects that are actually up to date (see bugs listed below). This is because the up to date check uses the Built output group to determine the outputs of the build. However, the Built output group: a) includes things that are not always built by the projects (used to include things in the pack), and b) does not include things in the bin directory, only the obj. So, instead of using the more general mechanism, we need to fall back to the csproj strategy of hardcoding the things we're looking for: output assembly, pdb, and xml doc file.
This is done in this PR by hooking up a new DT build target that will collect the outputs and return them to the up to date checker.
#2695, …
> Change how the up to date check calculates outputs

- src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.pkgdef
In a code inspection, I couldn't find any code that looked like it was supposed to run on upgrade.  Risk is that maybe someone somewhere else does a QS for something that it proffers?
> Stop autoloading editors package on solution upgrade

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/TargetFrameworkProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/PackageRuleHandler.cs
Projects created with non-canonical target frameworks (e.g. netstandard20 instead of netstandard2.0) can leave dependency tree in unresolved state. Two bugs conspired to make this possible (1) TargetFrameworkProvider caches duplicate target frameworks in the face of non-canonical short names (2) comparison operator overload does not work with interfaces, hence in PackageRuleHandler two identical (i.e. duplicate) target frameworks are treated as unequal.
Fixes #2772 
N/A
**Risk**
Low
Slight improvement since cache is working
No
When caching, we use the canonical shortname, even if the input was non-canonical. This means future …
> Fix TargetFramework caching and comparison in PackageRuleHandler

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Dependency.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Text/StringBuilderExtensions.cs
Traces showed this taking upward of 1% of allocations of opening a solution.
Fixes #2918.
<details>**Customer scenario**
**Risk**
(with a brief justification for that assessment (e.g. "Low perf impact because no extra …
> Use a pooled StringBuilder in Dependency.GetID

- src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/UpToDateCheckBuilt.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/UpToDateCheckBuilt.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.cs.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.de.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.es.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.fr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.it.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.ja.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.ko.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.pl.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.pt-BR.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.ru.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.tr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.zh-Hans.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/UpToDateCheckBuilt.xaml.zh-Hant.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
NOTE: I just realized that these bug fixes were merged into `master`, not `dev15.6.x`, even though they were all marked for 15.6. This just ports those fixes to the correct branch.
There are a number of scenarios where the up to date check fails for projects that are actually up to date (see bugs listed below). This is because the up to date check uses the Built output group to determine the outputs of the build. However, the Built output group: a) includes things that are not always built by the projects (used to include things in the pack), and b) does not include things in the bin directory, only the obj. So, instead of using the more general mechanism, we need to fall back to the csproj strategy of hardcoding the things we're looking for: output assembly, pdb, …
> Portuptodate

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/PackageRestoreInitiator.PackageRestoreInitiatorInstance.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetRuleSubscriberBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/ICrossTargetRuleHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependenciesRuleHandlerBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/PackageRuleHandler.cs
A race condition in CPS is resulting from data flow action blocks being executed in the wrong capabilities context. This race condition may have been around for a while but is occurring much more frequently. CPS expects us to explicitly chain dataflows to the right capability context, so we are doing so in a number of cases where the symptoms of this race condition have become more pronounced. This PR fixes two cases:
1. After opening .NET Core projects, NuGet restore fails to run, and all dependencies are unresolved. In this case, running in the wrong capabilities context causes a NuGet check for compatibility to fail so that it does not recognize .NET Core projects.
2. Opening .NET Core projects sometimes produces spurious warnings in the dependencies tree, or an empty dependencies tree …
> Chain capabilities snapshot to nominate restore and dependency tree dataflows

- src/Microsoft.VisualStudio.ProjectSystem.FSharp/ProjectSystem/LanguageServices/FSharpParseBuildOptions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHandlerManager.cs
Multi-targeting doesn't work correctly in the F# IDE.
The reason is the IDE doesn't know how to identify the correct cached references and source files.  Currently it uses the project file name, this is insufficient because in a multi-targeting project there is in fact an in memory project for each target framework.
The project tracker can identify the correct in memory project using the binpath of the project output file.  In the project system the context object also identifies the binpath for the project being "design-time" built.
This change modifies the CommandLine notification to send the binpath rather than the project path.
/cc @Pilchie ,  can we see if this makes the bar for preview 4?
It also will require an F# update.
Thanks
> Use binpath for communication with IDE

- src/Microsoft.VisualStudio.Editors/PropPages/CSharpLanguageVersion.vb
- src/Microsoft.VisualStudio.Editors/PropPages/CSharpLanguageVersionUtilities.vb
Set the language version for a project to C# 7.3 (shipping in 15.7).
Fixes https://github.com/dotnet/project-system/issues/3200
Edit the csproj manually
**Risk**
Low. This is a trivial change following the same pattern we used for every point release (for example [7.2](https://github.com/dotnet/project-system/pull/2334)).
> Add LanguageVersion for C# 7.3

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/SdkDependencyModel.cs
Version was unset for earlier releases, but is set for the first time in .NET Core 2.1 (by https://github.com/dotnet/sdk/pull/1572) creating problems matching SdkDependencyModel to NuGet Package references. See https://github.com/dotnet/project-system/issues/3184#issuecomment-361791926 for more details
This fix overrides base class implementation and ignores version information. It turns out this approach is used in other derived classes as well. I also considered a fix in which the broken filter checks for SDK using an Id without version and one with version, but this approach seems more consistent with other models in this project. 
At this point, it is unclear why the base class implementation needs to include version in its ID since many of its derived classes ignore version or leave …
> Set up Sdk Dependency Model Ids to ignore version information

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectAssetFileWatcher.cs
I was debugging and saw multiple reevaluations right after project load due to this. I imagine it is a decent perf hit in large solutions. This will prevent unnecessary reevaluations by first comparing the contents of project.lock.json on disk before dirtying the project. Not sure what release or branch you want this in.
Projects reevaluate multiple times (typically 2 additional times) after being loaded. In larger solutions this is a perf hit. I haven't measured the perf hit though, so no idea how big it is.
Don't have one.
None.
**Risk**
Low risk.
Perf improvement
Not sure when this was first introduced.
How did we miss it? …
> Prevent reevaluations when project.lock.json is touched without changing on disk

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectAccessorFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectXmlAccessorFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/SupportedTargetFrameworksEnumProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectXmlAccessor.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/MSBuildXmlAccessor.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/SupportedTargetFrameworksEnumProvider.cs
Continuation of https://github.com/dotnet/project-system/pull/3107.
> Move SupportedTargetFrameworksEnumValuesGenerator to use IProjectAccessor

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/BaseProjectConfigurationDimensionProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/TargetFrameworkProjectConfigurationDimensionProvider.cs
Makes it easier to replace IProjectXmlAccessor usage in a future change.
> Call through a common helper

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
This change fixes an issue when trying to add a custom debugger to an extension - the DebuggerFlavor property gets overridden by the default target.
> fix default target DebuggerFlavor property

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs
Fixes: #3253
Avoids crash when browse for an executable when we load a profile without an executable path. This can occur when the user didn't set an initial one, or removed it explicitly from the file.
All launch profile properties can be null - searched the code base for other similar usages, and this was the only one that didn't handle null.
> Avoid crash when loading profile without executable

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/ImplicitlyActiveConfiguredProjectReadyToBuild.cs
It seems that Clean is hidden if the project isn't ready to build, but VS only
asks once. Having switched to using dataflow, we would return false on the very
first call.
Reverts the changes in 36e5c6c2.
Create a new ASP.NET Core project.  The "Clean" button will be missing until the solution is reloaded.
[VSTS Bug 550183](https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workitems/edit/550183)
Reload the solution.
**Risk**
Low - reverts to previous implementation used for 15.5.
Low - just tracking configuration changed events.
Yes, it's a regression from 15.5, related to moving the service to use DataFlow.
It …
> Fix missing "Clean" command in new projects

- src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/DesignerTabButton.vb
@Pilchie 
"Pulling back into 15.6 based on Accessibility team's recommendation."
https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_queries?id=433488&_a=edit&triage=true
None
**Risk**
Low
None
No
We missed a scenario for Accessibility  
Originally found through Integration Tests
> Allow Project settings AppDesigner tabs to be activated via UI automation

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/ConfigurationProjectConfigurationDimensionProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/PlatformProjectConfigurationDimensionProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/TargetFrameworkProjectConfigurationDimensionProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/Ordering/OrderingHelperTests.cs
Works around https://github.com/Microsoft/msbuild/issues/2997.
These aren't actually needed for the tests.
> Remove MSBuild Sdk usage from tests

- build/Versions.props
Changes checksum algorithm of source files in PDBs built for Project System binaries.
Enabling this in our build allows us to dogfood more and increase confidence in making SHA256 the default.
Small.
Small.
> Update to RepoToolset 1.0.0-beta-62615-02

- src/Directory.Build.props
Fixing the official build version to not longer go over 65535
Infrastructure only change.
Confirmed this change fixes build break: [20180215.7](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/index?buildId=1390168&_a=summary)
/cc @Pilchie @tmat @tannergooding
> Port version fixes from RepoToolset to 15.5

- src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/CSharp/CSharpErrorListTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/CSharp/CSharpProjectFileEditTest.cs
- src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/CSharp/CSharpSquigglesTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/VisualBasic/VisualBasicErrorListTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/VisualBasic/VisualBasicSquigglesTest.cs
- src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/WorkspaceTests.cs
We've never enabled the integration tests as a check-in blocker - nor have they ever passed as far as I can see on the jenkins runs - every single build that it has history on has failed. Disable them to avoid reduced confidence by those that are new to the tree.
Filed https://github.com/dotnet/project-system/issues/3286 to track reenabling them.
> Disable integration tests

- .editorconfig
For the product code we only allow `var` usage when the type is apparent. However, this is too strict in our tests which make heavy use of `var` to reduce test churn as we remove/rename/change types. Turn off enforcement, and favor `var`.
> Turn off "var" enforcement in tests

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/DebugFrameworksDynamicMenuCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/DebugFrameworksMenuTextUpdater.cs
This is a valid usage - only wrapped for test purposes.
> Suppress usage of JoinableTaskFactory.Run

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/DotNetCoreProjectCompatibilityDetector.cs
Simple change to update the FWLinks for the learn more links.
Addresses bug https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=566972
> Update FWLinks for DotNet 2.1 detector learn more links

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Sort property page schema items so that it's easier to quickly see the different types of them.
There is no behavior change - just moved items around. This will make it easier to split file/browse object rules to fix https://github.com/dotnet/project-system/pull/3100.
> Sort property page schema items

- Directory.Build.props
- src/Microsoft.VisualStudio.AppDesigner/Microsoft.VisualStudio.AppDesigner.vbproj
- src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj
The Roslyn Workspaces and above layers all depend on 4.6.1 already, and all
workloads that include the project system also require it.
> Target .NET 4.6.1 instead of 4.6.0.

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs
This is intended to replace the "Managed" capability to represent the primary .NET languages C#, VB and F# . "Managed" is overloaded and defined by C++, even though they support very little of the managed features that traditional .NET languages support.
This change, combined with https://github.com/dotnet/project-system/pull/3274, enables the Publish command for F# projects.
> Add new ".NET" capability

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Adding the project capability "Publish" to Roslyn project system.
Looked at all the capabilities for .NET core project and 'Publish' is missing. VS will be using at this capability to determine whether the publish command should be displayed.
@BillHiebert @davkean 
/cc @mlorbetske
> Adding "publish" capability to Roslyn project system

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/FSharp.ProjectItemsSchema.xaml
Customer adds a ".fsi", F# signature file, to their F# project and it by default will not be part of compilation.
https://github.com/dotnet/project-system/issues/3207
Edit the "fsproj" file to change the item type.
**Risk**
No risk
No performance impact
No
F# devs typically don't create ".fsi" a lot.
Testing adding files.
---
I haven't been able to get this to work, or be able to test this. I'm certain this change is what associates file extensions with item types, according to here: https://github.com/Microsoft/VSProjectSystem/blob/master/doc/extensibility/custom_item_types.md
I also followed the …
> Added .fsi, .ml, .mli file extensions to F# schema

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/Ordering/OrderingHelperTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AbstractAddItemCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddExistingItemAboveCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddExistingItemBelowCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddExistingItemCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddNewItemAboveCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddNewItemBelowCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddNewItemCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/OrderingHelper.cs
Adding items to empty folders. Adding multiple items to a folder. Currently, doing these actions can cause invalid ordering of files.
(n/a)
Modifying the .proj file directly.
**Risk**
Low risk. Modified the ordering code slightly.
None
No
Missed it due to lack of specific testing; the specifics were not defined in the file ordering spec.
We should add these scenarios in the file ordering spec.
When trying to implement paste ordering.
> Fixed an ordering bug dealing with empty folders and adding multiple items

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/AbstractAddClassProjectCommandTests.cs
This variable wasn't being used and left over previously removed code.
> Remove ProjectGuid usage from tests

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Properties/CSharpProjectTypeGuidProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/CSharpProjectTypeGuidProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS/ProjectSystem/VS/FSharpProjectTypeGuidProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests/ProjectSystem/VS/VisualBasicProjectTypeGuidProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/VisualBasicProjectTypeGuidProvider.cs
This better describes what it returns; it returns Project's *Type GUID*, not a Project's GUID.
> Rename ProjectGuidProvider -> ProjectTypeGuidProvider

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/OrderPrecedenceImportCollectionExtensions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IActiveConfiguredProjectSubscriptionServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IAsyncServiceProviderMoq.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDebugLaunchProviderFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectGuidService2Factory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectSubscriptionUpdateFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsStartupProjectsListServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/VsStartupProjectsListService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/DebugTests/StartupProjectRegistrarTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/NuGet/ProjectAssetFileWatcherTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs
- Removed need to keep state if the project is debuggable or not, IVsStartupProjectsListService is designed to no op if the project has already been added or removed.
- Removed need to switch to UI thread. IVsStartupProjectsListService is free-threaded.
- Stop listening to project GUID changes - the project GUID rule is being removed to fix https://github.com/dotnet/project-system/issues/2940.
- Listen to all properties not just output type. If not using launch profiles, output type doesn't actually influence whether you are debuggable or not. It's based on the debugger properties such as executable, etc.
> Simplify StartupProjectRegistrar and remove ProjectGuid property usage

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/ProjectPropertiesItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/UnconfiguredProjectContextProvider.cs
Partially fixes: #2940.
The actual removal of the rule property and taking a lock while setting the project guid will be in a followup change.
> Remove project guid property usage from language service

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectAccessorFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectAccessor.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectAccessor.cs
Lets callers modify the evaluation project.
This is a straight cherry-pick of IProjectAccessor additions from master to 15.7 as they are required for the ProjectGuid changes.
> Add IProjectAccessor.OpenProjectForWriteAsync (15.7)

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/Ordering/OrderingHelperTests.cs
Works around https://github.com/Microsoft/msbuild/issues/2997.
Back ports this from master, and fixes the additional ones that were added this week.
> Remove SDK references from tests

- build/Versions.props
- build/build.ps1
Without this change new users will see the following error when running `build.cmd`
```
Downloading vswhere
The request was aborted: Could not create SSL/TLS secure channel.
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
at LocateVisualStudio, C:\source\project-system\build\Build.ps1: line 87
at <ScriptBlock>, C:\source\project-system\build\Build.ps1: line 156
at <ScriptBlock>, <No file>: line 1
```
> Fix powershell

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectGuidService2Factory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/DebugTests/StartupProjectRegistrarTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/UnconfiguredProjectContextProvider.cs
When C++ is installed, StartupProjectRegistrar and UnconfiguedProjectContextProvider fail to be instantiated breaking startup project registration and language service.
Fixes: #3341 
This was a regression.
> Import IProjectGuidService2 as ImportMany

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectChangeDiffFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectLogger.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/UnconfiguredProjectFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandlerTests.ConcreteAbstractEvaluationCommandLineHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandlerTests.EvaluationCommandLineHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandlerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandler.cs
This includes https://github.com/dotnet/project-system/pull/3346, so just review https://github.com/dotnet/project-system/commit/a1ce728734f6458fa2092d7444f5e79de7423cfc.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/537755.
When evaluating in quick succession, Visual Studio can hang when attempting to throw away old evaluation results.
This can occur when AbstractEvaluationCommandLineHandler receives results in the following order:
1. Evaluation (Version 1)
2. Evaluation (Version 2)
3. Design Time Build (Version 1) <-- Hang attempting to throw away results from in step 1
It will continually loop the previous evaluations neither discarding them or breaking from the loop.
>  Fix hang in language service integration when latter evaluation occurs before design-time build 

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Menus.vsct
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/MoveDownCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/MoveUpCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.cs.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.de.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.es.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.fr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.it.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.ja.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.ko.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.pl.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.pt-BR.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.ru.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.tr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.zh-Hans.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/Menus.vsct.zh-Hant.xlf
This fixes an issue where alt+up/down hotkeys for legacy F# projects wasn't working anymore.
https://github.com/Microsoft/visualfsharp/issues/4405
Don't use hotkeys, or use Tools\Options\Environment\Keyboard and remap them (but this means you need to use different keybinding for non-Core and Core F#.
**Risk**
Low risk.
None.
Yes.
How did we miss it?
Didn't check legacy projects for F#.
https://developercommunity.visualstudio.com/content/problem/204016/vs-156-preview6-alt-updown-arrows-do-not-repositio.html
> Added fix for FSharp hotkeys in legacy projects

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Order/TreeItemOrderPropertyProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Order/TreeItemOrderPropertyProvider.cs
Customers sometimes reference the same file in projects.
https://github.com/dotnet/project-system/issues/3218
Don't include duplicate files in the same project.
**Risk**
Very Low
None
Yes.
We missed it due to no testing duplicate files. In the future, we should try to get more F# users on the preview builds.
Customer report
> Fixed duplicate items for FSharp

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/Ordering/OrderingHelperTests.cs
Removes SDK references in OrderingHelperTests. We need this for builds to pass now.
> Removed SDK references from OrderingHelperTests

- build/Versions.props
Infrastructure only.
Changes included in the toolset:
https://github.com/dotnet/roslyn-tools/commits/pre-SDK/sdks/RepoToolset
Previous update was 1bc665575121187618aabc26cdc35afde255d1f5
> Update RepoToolset to 1.0.0-beta-62705-01

- Test.cmd
- build.cmd
This resolves https://github.com/dotnet/project-system/issues/3187.
FYI. @tmat, @davkean, @jaredpar
> Updating the build scripts to supppot paths with spaces in the name

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ISafeProjectGuidServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandlerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectAsyncLoadDashboardFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectGuidService2Factory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectGuidServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/DebugTests/StartupProjectRegistrarTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/AvoidPersistingProjectGuidStorageProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/VsSafeProjectGuidServiceTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsSafeProjectGuidService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ISafeProjectGuidService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/UnconfiguredProjectContextProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectAsyncLoadDashboardExtensions.cs
The project GUID can be set by the solution right up to the point it fires IVsSolutionEvents.OnAfterOpenProject (IProjectAsyncLoadDashboard.ProjectLoadedInHost completes) in reaction to a clash with another project. Add a singleton API that is intended as a wrapper around IProjectGuidService/IProjectGuidService2 that waits for the project to be loaded before retrieving the GUID..
Fixes: #3338
Updated services to consume that.
Still testing this, but code is complete.
> Add a safe way to grab the project GUID

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPropertyPage.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/IPageMetadata.cs
- Remove unused export
This was ported over when the debug property page was ported, but is not used anywhere in our tree or outside. Property pages are populated by IVsProjectDesignerPageProvider instances and not are imported.
- Obsolete unused public interface
This interface was ported when Debug property page was ported, and is a mirror of Microsoft.VisualStudio.ProjectSystem.VS.Properties.IPageMetadata. I believe it was added to make the ported code compile (the namespace changed between 14.0 -> 15.0), but is not used anywhere. Will remove in 15.8.
> Remove unused export

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Extensibility/ProjectExportProvider.cs
This property had incorrect spelt name, and it doesn't need to be a property.
> Rename & convert to field

- src/Microsoft.VisualStudio.Editors/PropPages/AssemblyInfoUtils.vb
This PR fixes #3128 
The fix orders the language list used to define assembly neutral language.
> Adds ordering to assembly neutral language combobox

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
The up to date check for .NET Core projects is currently too aggressive -- we currently check the project against all imported target files. MSBuild, however, only checks the projects listed in $(MSBuildAllProjects). So you can get into a situation where a targets file has been touched and the project will never be considered up to date because the build won't regenerate the output (since MSBuild thinks it's up to date).
#3273
User would have to do a manual rebuild.
**Risk**
Low to moderate. This should be more precise, but it's possible there is some quirk about $(MSBuildAllProjects) that might cause the up to date behavior to be wrong.
Low, we'll be checking fewer targets files than before.
**Is …
> Fix up to date check of imports

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/ActiveDebugFrameworkServicesTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Reload/ProjectReloadInterceptorTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/DebugProfileEnumValuesGeneratorTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PropertyPages/PropertyPageTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/DebugProfileEnumValuesGenerator.cs
These tests live in VS assembly and hence namespace.
> Remove tests/types to correct namespace

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
Add the URL property to GeneralBrowseObject. This is to support in-memory editor. XML language service queries this property to find the canonical name of the project.
Not a bug fix.
None
**Risk**
Low
None. Adds support for another property via already used method.
No
> Add URL property to GeneralBrowseObject

- build/Versions.props
This change should have been about revving the
`$(PreReleaseVersionLabel)` from `beta3` to `beta4`, but it turns out
that we haven't updated version numbers in a while. So instead
`$(PreReleaseVersionLabel)` is already at `beta4` and staying there,
while `$(VersionBase)` is being revved to 15.7.0/2.7.0.
> Bump the version in dev15.7.x branch

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/ConfigurationProjectConfigurationDimensionProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/PlatformProjectConfigurationDimensionProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/TargetFrameworkProjectConfigurationDimensionProviderTests.cs
removing `Sdk=""Microsoft.NET.Sdk""` from project xml in tests so they don't sporatically fail looking for the SDK resolver
> fixing tests

- src/Microsoft.VisualStudio.Editors/Common/Utils.vb
Fixes #2991.
<details>
**Risk**
(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")
**Is this a regression from a …
> Don't crash on "DISP_E_MEMBERNOTFOUND" in the VB references page

- build/SignToolData.json
Infrastructure only change. NuGet packages are required to be signed.
**Risk**
(E.g. customer reported it vs. ad hoc testing)
> Enable NuGet package signing

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Installing a NuGet package no longer causes the compiler to pick up the new dlls.
No viable workaround.
**Risk**
Low
None
**Is this a regression from a previous update?** 
Yes, the new design-time build caching only triggers a design-time build if items in the project have changed. It's unaware of the logic that we have that causes a reevaluation if project.assets.json changes - this change makes it aware of that file.
We didn't miss it - it was a fallout of the design.
Ad hoc testing and customers have started running into it.
> Trigger design-time buld when project.assets.json file changes

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectInstancePropertiesProviderFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptedProjectProperties/InterceptedProjectPropertiesProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/InterceptedProjectPropertiesProviderBase.cs
CPS has a new optimization that goes through CommonProperties, and without this we
don't get a chance to intercept these values.
<details>
**Risk**
(with a brief justification for that assessment (e.g. …
> Also support GetCommonProperties from InterceptedProjectPropertiesProvider

- src/Directory.Build.targets
regsvr32 has a race condition which can cause parallel test execution to fail when OpenCover is used with -register:user. For 32-bit test scenarios, use -register:path32 instead to force the exclusive use of 32-bit profiling.
See https://github.com/OpenCover/opencover/issues/557#issuecomment-193205134
> Avoid using the registry for OpenCover in 32-bit tests

- build/Codecov.proj
Pull request builds use the variable `ghprbTargetBranch`, while primary branch builds use `BranchName`. This pull request updates the build script to support both cases as opposed to just the former.
> Report the correct branch name to codecov.io

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/Ordering/OrderingHelperTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AbstractAddItemCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddExistingItemAboveCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddExistingItemBelowCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddNewItemAboveCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddNewItemBelowCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/OrderAddItemHintReceiver.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/OrderingHelper.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/OrderingMoveAction.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/PasteOrdering.cs
When pasting copied, cut, or dropped F# files into a project or folder, those files need to be moved to the top of it's parent; parent being a project or folder.
(n/a)
Modify fsproj
**Risk**
Low
None
No
(n/a)
(n/a)
> Added Paste Ordering

- build/Versions.props
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/ConfigurationProjectConfigurationDimensionProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/PlatformProjectConfigurationDimensionProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/TargetFrameworkProjectConfigurationDimensionProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/AvoidPersistingProjectGuidStorageProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Build/BuildExtensions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Build/BuildUtilities.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/BaseProjectConfigurationDimensionProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/ConfigurationProjectConfigurationDimensionProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/PlatformProjectConfigurationDimensionProvider.cs
To determine the configurations when loading a project, we need to read the project for the dimensions (the `<Configurations>`, `<Platforms>` and `<TargetFrameworks>` properties). This leads to a chicken and egg problem; to figure out all configurations for a given project you need to load at least one configuration to evaluate. CPS made a change to read the same config as the one active in the solution, however, this pattern doesn't work for multi-targeting projects as TargetFramework dimension is never "active", this results us loading an unneeded config that matches the solution just to grab the actual real configurations, see: #2711.
To avoid unnecessarily loading this unneeded config, we "guess" what the defaults will be based on reading the the first value in Configurations, …
> Avoid loading additional configurations for multi-targeting projects

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralBrowseObject.xaml.cs.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralBrowseObject.xaml.de.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralBrowseObject.xaml.es.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralBrowseObject.xaml.fr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralBrowseObject.xaml.it.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralBrowseObject.xaml.ja.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralBrowseObject.xaml.ko.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralBrowseObject.xaml.pl.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralBrowseObject.xaml.pt-BR.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralBrowseObject.xaml.ru.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralBrowseObject.xaml.tr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralBrowseObject.xaml.zh-Hans.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralBrowseObject.xaml.zh-Hant.xlf
- Made project's properties in Properties tool window consistent with project items & legacy project system, favoring the former where they disagreed (such as "Project File").
- Add new "Full Path" property that shows the entire file name of the project
Before:
After:
> Add "Full Path" to project properties

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs
Convert ManagedProjectSystemPackage to use '.NET' for it's load context
capability.
> Fix load of ManagedProjectSystemPackage in F#

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Binary projects were opt'ing into .NET capability previously via the project type. This opts C#/VB Shared Projects into it.
Unblocks: https://github.com/dotnet/project-system/pull/3299
> Opt Shared Projects into ".NET" capability

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/Ordering/OrderingHelperTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/OrderingHelper.cs
This fixes the issue with F# files not able to be added in the ASP .NET Core projects. The cause was due to the ASP .NET Core project including a file that was part of props file, and our ordering logic did not account for files that are not associated with the main project. We now, simply skip them when doing ordering, but their display order will still be correct.
Changes in the PR:
- Skipping item elements if they are imported when getting elements 
- Defensive null checks in other places where we call TryGetReferenceElement
- Greatly simplified TryMoveElementsToTop that accounts for skipping imported item elements
Here is the reported bug:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/612703
Here is the F# issue:
https://github.com/Microsoft/visualfsharp/issues/4851
> Fixed inability for F# files to be added in ASP .NET Core projects

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/GenerateNuGetPackageProjectContextMenuCommandTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/GenerateNuGetPackageTopLevelBuildMenuCommandTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/Ordering/MoveDownCommandTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/Ordering/MoveUpCommandTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Input/CommandGroup.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Input/FSharpProjectCommandId.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Input/ManagedProjectSystemCommandId.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Input/ManagedProjectSystemOrderCommandId.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/DebugFrameworksDynamicMenuCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/DebugFrameworksMenuTextUpdater.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/GenerateNuGetPackageProjectContextMenuCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/GenerateNuGetPackageTopLevelBuildMenuCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddExistingItemAboveCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddExistingItemBelowCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddNewItemAboveCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddNewItemBelowCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/MoveDownCommand.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/MoveUpCommand.cs
Commands have nothing to do with the package, move them alongside the command groups and ids.
>  Move command groups and ids out of package

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs
While we were an async package, we were still being loaded synchronously when UI context was made active.
Fixes: 592856.
> Load package asynchronously when UI context is made active

- src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb
- src/Microsoft.VisualStudio.Editors/package/VBPackage.vb
This addresses the issue reported in #3492 by defaulting the path to the path of the resource file.
This also caches the last selected path for the resource on a per project basis in the ```VBPackage``` so that it does not reset if you close and re-open the resource editor.
The cache is cleared on solution/project close, project unload and on closing VS.
> Make Resource Editor "Add Existing File..." default path more intuitive

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.cs.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.de.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.es.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.fr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.it.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.ja.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.ko.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.pl.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.pt-BR.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.ru.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.tr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.zh-Hans.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/GeneralConfiguredBrowseObject.xaml.zh-Hant.xlf
Fixes: #2732 for the new project system.
I have no idea why we have two properties here; one for consumed by CSharpProjectConfigurationProperties and one consumed by AppDesigner but I left the exercise for a latter time.
Changes:
``` XML
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
<LangVersion>latest</LangVersion>
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
<LangVersion>latest</LangVersion>
```
to
``` XML
<LangVersion>latest</LangVersion>
```
While the code fix still loops configurations, it just overwrites the same property again and again.
> Make LangVersion configuration-agnostic

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.FSharp.DesignTime.targets
We're making a change in CPS to start pulling from this property to start populating VSHPROPID_PreferredLanguageSID, make sure F# returns the correct value.
> Set LanguageServiceId property for F#

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Automation/CSharpExtenderCATIDProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Automation/CSharpExtenderCATIDProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/AbstractExtenderCATIDProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests/ProjectSystem/VS/Automation/VisualBasicExtenderCATIDProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/Automation/VisualBasicExtenderCATIDProvider.cs
Implement IExtenderCATIDProvider for C#/VB. F# is being tracked by https://github.com/dotnet/project-system/issues/3561.
Also filed https://github.com/dotnet/project-system/issues/3560 to implement support for ProjectConfigurationBrowseObject and implemented ConfigurationBrowseObject here https://devdiv.visualstudio.com/DevDiv/Default/_git/CPS/pullrequest/123753?_a=overview.
> Return CATID's for project system extenders

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/AdditionalFiles.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ApplicationDefinition.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Compile.BrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Content.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/EmbeddedResource.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Folder.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralConfiguredBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/None.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Page.xaml
This causes Properties on files and project to behave exactly like legacy by open the Properties Browser instead of Properties window on **Properties**.
Shell ends up querying browse object, which based on this setting decides whether the Properties Browser is used instead of Properties Window.
~This includes https://github.com/dotnet/project-system/pull/3484 and is blocked on it, so only review https://github.com/dotnet/project-system/commit/a0a636bf8a5087904162914892921e7f4e0d48b2 and https://github.com/dotnet/project-system/pull/3566/commits/faf75b8cf40f3e10805cce62c5a2b656a6d1e32e.~
~We need https://devdiv.visualstudio.com/DevDiv/Default/_git/CPS/pullrequest/124002?_a=overview to make this fix complete~ and fix #3498. This is merged in.
> Use Properties Browser instead of Properties Window 

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectAssetFileWatcher.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/DependenciesGraphProvider.cs
GlobaProvider returns a provider per-thread, if you are called off the UI thread - you are going to have empty services. Graph Providers are now instantiated off the UI thread, based on the changes that were made to load them async by platform. Just import the new async service provider that was exported in 15.8.
> Do not use GlobalProvider off the UI thread

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralConfiguredBrowseObject.xaml
Fixes: #2720
The SDK automatically appends to DefineConstants with implicit constants after the project's definition of DefineConstant. When we attempt to read the value at the end of project file ("AfterContext") we think that user's value is set to include those and pick these up in the dialog which sets the property.
Instead move to reading the value *at the point* it was defined in the project file, which causes us to ignore framework implicit defines.
> Avoid picking implicit framework defines

- ProjectSystem.sln
VS picks the first project in the solution as startup project on first open - make it so that first users get the "right" project as startup.
> Change default startup project

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralConfiguredBrowseObject.xaml
Fixes: #2177
The SDK automatically appends to OutputPath with implicit framework and runtime values, when we attempt to read the value at the end of project file ("AfterContext") we think that user's value is set to include those and pick these up in the dialog which sets the property.
Instead move to reading the value at the point it was defined in the project file, which causes us to ignore any values that the SDK appends.
> Avoid picking up implicit output path

- Directory.Build.props
- Launch.cmd
- build.cmd
CPS always deploys to "Exp" to enable testing project system and CPS together have them deploy to the same hive.
> Change the default hive to "Exp"

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.CSharp.DesignTime.targets
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.FSharp.DesignTime.targets
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.VisualBasic.DesignTime.targets
Fixes: #3535.
For C# and Visual Basic, generators in the legacy project system are looked up based on their package (not project type) - use that GUID.
For F#, generators in the legacy project system are looked up based on project type, use that.
C# and VB activate a UI context (VSHPROPID_CmdUIGuid) that matches their package GUID (not their project type) when the project is active.
F# activates a UI context that matches its project type GUID when the project is active.
This is blocked on: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/122410?_a=overview.
> Look up single file generators and set CmdUIContext via legacy locations

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VsProject_VsLangProjectProperties.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/AbstractProjectConfigurationProperties.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralConfiguredBrowseObject.xaml
Earlier version's of [EF's Update-Database script](https://github.com/aspnet/EntityFrameworkCore/blob/release/2.0/src/EFCore.Tools/tools/EntityFrameworkCore.psm1) did a Project.Kind check to determine if .NET Core and if so read properties directly from via GetCommonProperties. In recent builds this kind changed to return legacy project system, but we missed this usage because it's since been changed to a "CPS" check. Downlevel packages, however, are still broken.
Implement the properties that they need:
#669
#667
#665 
Previous:
```
PM> Install-Package Microsoft.EntityFrameworkCore.Tools -Version 2.0.3
PM> Update-Database
Could not load assembly ''. Ensure it is referenced by the startup project ''.
```
New (which @bricelam tells me indicates that it worked):
```
PM> Install-Package …
```
> Handle properties that "Update-Database" script from EntityFramework needs

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs
When called on a library, IVsQueryDebuggableProjectCfg.QueryDebugTargets was failing preventing Test Explorer from pulling the current debug settings.
QueryDebugTargetsAsync is called in two situations:
- When launching
- When someone queries the available debug targets
Similar to legacy project system, only fail when called during launch so that we can continue to show an error on F5'ing a library, but also be able to hand back launch data to consumers, such as Test Explorer.
Fixes: #3647.
Note, we now fall back the target path similar if RunCommand is not specified. This brings the behavior in line with legacy when called on a library.
> Do not fail IVsQueryDebuggableProjectCfg.QueryDebugTargets when called on library

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs
Fixes: #3649
Stop wrapping CTRL+F5 launches with cmd.exe unless you are console app. This matches legacy behavior.
> Do not wrap non-console apps with cmd.exe

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Threading/Tasks/TaskDelaySchedulerTests.cs
On the build server this test was failing because the scheduled task delay was too short, causing us to start running the task before we'd cancelled.
Also simplified the test - it looked like it was attempting to test something as well, but OperationCancelledException was never thrown in any circumstances; if we'd already started running the task, CancelPendingUpdates would not cancel the token.
@BillHiebert On this - CancelPendingUpdates, is that supposed to cancel running tasks? Because the logic inside TaskDelayScheduler does not do that.
> Fix reliability of CancelPendingUpdates_PendingTasksAreNotRun

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Threading/Tasks/TaskDelaySchedulerTests.cs
These are failing often on Jenkins builds.
> Improve reliability of TaskDelayScheduler tests

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/AbstractProjectDynamicLoadComponentFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/JoinableTaskContextNodeFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/AbstractProjectDynamicLoadComponentTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AbstractProjectDynamicLoadComponent.AbstractProjectDynamicLoadInstance.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AbstractProjectDynamicLoadComponent.cs
We weren't initializing the "outer" object, which I ran into the language service hookup rewrite.
Also filled out the tests.
> Make sure we initialize when calling LoadAsync in AbstractProjectDynamicLoadComponent

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IImplicitlyActiveServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ConfiguredProjectImplicitActivationTrackingTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ConfiguredProjectImplicitActivationTracking.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IConfiguredProjectImplicitActivationTracking.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IImplicitlyActiveService.cs
See: https://github.com/dotnet/project-system/pull/3423/files#r178951672.
It became clear that consuming the activated/deactivated events in a manner that was thread-safe was difficult. Instead replace it with an service interface that automatically gets Activated/Deactivated when the configured project becomes implicitly activate or deactivated.
> Replace ImplicitlyActivated/Deactivated events with IImplicitlyActiveService

- build/Versions.props
This version includes now required `signers` entry to Willow package manifest.
[VSO 642948](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/Acquisition%20Foundation/_workitems/edit/642948)
> Update SwixBuild to 1.0.422

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/AbstractMultiLifetimeComponentFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/AbstractMultiLifetimeComponentTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/PackageRestoreInitiator.PackageRestoreInitiatorInstance.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/PackageRestoreInitiator.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AbstractMultiLifetimeComponent.AbstractMultiLifetimeInstance.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AbstractMultiLifetimeComponent.cs
This component is being/will be used by IProjectDynamicLoadComponent and IImplicitlyActiveService instances.
> Rename AbstractProjectDynamicLoadComponent to AbstractMultiLifetimeComponent

- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/Rename/CSharpSimpleRenamerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/Threading/Tasks/TaskTimeoutExtensions.cs
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests/ProjectSystem/VS/Rename/VisualBasicSimpleRenameTests.cs
I suspect the renaming tests are blocking runs, this will at least help chase down the cause - and prevent runs being blocked for 60 minutes.
> Add timeouts to renaming tests

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Build/PublishableProjectConfigProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/PublishableProjectConfigProvider.cs
It's never valid to call a IPublishProvider if IsPublishSupportedAsync returns false.
> ClickOnce provider should throw from Publish/ShowPublishPromptAsync

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectAccessorFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectAccessor.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectAccessor.cs
Adds the last usage of WriteLockAsync under a unit testable mockable method.
There will be follow-up PRs that consume this. Centralizing all write locks usage let's us react to this change in an easier way than CPS: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/132369.
> Add IProjectAccessor.EnterWriteLockAsync

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectAccessorFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IUnconfiguredProjectCommonServicesFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UnconfiguredProjectCommonServicesTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/UnconfiguredProjectVsServicesTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectAssetFileWatcher.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UnconfiguredProjectVsServices.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectAccessor.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IUnconfiguredProjectCommonServices.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectAccessor.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UnconfiguredProjectCommonServices.cs
This includes https://github.com/dotnet/project-system/pull/3726 and https://github.com/dotnet/project-system/pull/3725, so only review https://github.com/dotnet/project-system/commit/c7fac9f3723f0ef23cd7fb07acd477d33114d313.
Change ProjectAssertFileWatcher to call through IProjectAccessor and removed last direct usage of IProjectLockService.
> Change ProjectAssertFileWatcher to call through IProjectAccessor

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectAccessorFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectAccessor.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectAccessor.cs
Note: This includes https://github.com/dotnet/project-system/pull/3725, so only review https://github.com/dotnet/project-system/commit/66dfc46402d700a94723a3a32b7bdcce39bd176d.
Dispose synchronously blocks the thread until the write lock is released. Under the covers the project service yields on this path, which under thread pool exhaustion situations can cause Dispose to be blocked for a long time, exacerbating the problem. Await on ReleaseAsync so that the current thread isn't blocked and can be released back to the pool.
See https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/132369 for the CPS-version of this change.
>  Avoid blocking thread on releasing write lock

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/UnconfiguredProjectFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Imaging/ProjectImageProviderAggregatorTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs
Fixes: https://github.com/dotnet/project-system/issues/2015.
We were never actually verifying that project was being consulted for capabilities. Stop pretending that we are.
> Remove unused "capabilities" argument

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/BuildOptionsFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/AdditionalFilesItemHandlerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/AnalyzerItemHandlerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/CommandLineHandlerTestBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/EvaluationHandlerTestBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/MetadataReferenceItemHandlerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/ProjectPropertiesItemHandlerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/SourceItemHandlerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/SourceItemHandler_CommandLineTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/SourceItemHandler_EvaluationTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ContextHandlerProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractWorkspaceContextHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AdditionalFilesItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AnalyzerItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/MetadataReferenceItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/ProjectPropertiesItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/SourceItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ICommandLineHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IEvaluationHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IWorkspaceContextHandler.cs
The new language service hookup MEF imports the handlers, whereas the old version still manually creates them. Support both versions.
> [Language Service] Turn evaluation/command line handlers into MEF components

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SDKVersionTelemetryServiceComponent.SDKVersionTelemetryServiceInstance.cs
The new SDK telemetry started faulting configuration in at a time that it previously wasn't loaded, which uncovered some race conditions. Wait until the project is loaded before we run.
This is considered the least risky change vs fixing the race conditions which we will do at a later time.
> [15.8] Fix telemetry loading configuration too early

- src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.it.xlf
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/653172.
Italian had a bad placeholder causing this path to crash when you entered a resource with a bad identifier.
> Fix Resources Designer crashes under Italian

- src/Microsoft.VisualStudio.Editors/ResourceEditor/FileWatcher.vb
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/653144.
The other events do not suffer from the same problem.
You can see how this behavior occurs here: https://referencesource.microsoft.com/#System/services/io/system/io/FileSystemWatcher.cs,541.
> Handle renames events without new name and old name

- src/Microsoft.VisualStudio.Editors/DesignerFramework/DesignerDataGridView.vb
- src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceStringTable.vb
This PR does two things:
1. Fixes the bug described in #2881.
2. Changes the `ResourceStringTable` to automatically change the size of its rows to show the complete cell value immediately upon committing edits to a cell; previously you had to manually click out of and back into an affected cell to have the row resize. This makes editing long strings in resx files much less annoying.
If there is a way to ensure that the text box used to edit the value itself similarly resizes to fit its text, I'm all ears, but I don't know if that is possible. Thanks!
> Resx string editor quality-of-life improvements

- src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceTypeEditorBitmap.vb
- src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceTypeEditorImageBase.vb
- src/Microsoft.VisualStudio.Editors/Resources/Microsoft.VisualStudio.Editors.Designer.Designer.vb
- src/Microsoft.VisualStudio.Editors/Resources/Microsoft.VisualStudio.Editors.Designer.resx
- src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.cs.xlf
- src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.de.xlf
- src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.es.xlf
- src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.fr.xlf
- src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.it.xlf
- src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.ja.xlf
- src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.ko.xlf
- src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.pl.xlf
- src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.pt-BR.xlf
- src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.ru.xlf
- src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.tr.xlf
- src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.zh-Hans.xlf
- src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.zh-Hant.xlf
Does just what the title says. I tested it with a metafile of my own creation, and it is added to the resx file, and from there to a PictureBox on a Form, with no issues.
Note: If you need a metafile to test with, just run `sc Sample.wmf $null` at a PowerShell prompt, then double-click the resulting empty file to open it in Paint. Add some content, then save, and poof: you now have a valid WMF file.
Fixes #3795.
> Add support for metafiles to the Resx editor

- Launch.cmd
From:
Launching Visual Studio under the 'Exp' hive
To:
Launching Visual Studio under the 'Exp' hive
C:\Program Files (x86)\Microsoft Visual Studio\15.9stg\Enterprise\Common7\IDE\devenv.exe
I have lots of VS versions installed, it helps to know which was was launched.
> echo devenv.exe location from Launch.cmd

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs
Fixes #1484
- Added support for launching a class library project using the run project command. This allows running a class library project using the `RunCommand` project property without needing to create a launch profile.
> Added support for launching a class library project using the run project command

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml
Fixes this VS bug: 
- [622505](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/622505)
Fix description:
- Today we do not set the tab ordering for the debug page.  This change sets the first item on the debug page as a place for tab ordering to stop at as well as indicating that it should be first in the tab order
> fixing tab ordering in debug options page

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/PostBuildEventValueProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/PreBuildEventValueProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/AbstractBuildEventValueProvider.AbstractBuildEventHelper.cs
This PR fixes the AbstractBuildEventValueProvider to properly escape MSBuild metachraacters signs added to the pre-build or post-build event strings in the Project Properties window of a .NET Core project.
Fixes #3506.
> URL-escape percent signs in pre/post build events

- build/Versions.props
As part of this pr (https://github.com/dotnet/project-system/pull/3706) we attempted to pad the version numbers so 15.8 version number would line up correctly.
Unfortunately this logic was wrong as BUILD_BUILDNUMBER can come in one of the two formats:
- 20180102.03
- 20180102.3
This change accounts for the shorter format (10 characters).
> handle  version number calculation

- .vsts-ci.yml
- build/Versions.props
- build/build.ps1
Initial work needed to get https://github.com/dotnet/project-system/issues/3646 fixed.
> generate dependent assembly versions for insertion tool

- .vsts-ci.yml
place builds in
`\\CPVSBUILD\drops\Roslyn\DotNet-Project-System\$(SourceBranchName)\$(Build.BuildNumber)` instead of
`\\CPVSBUILD\drops\Roslyn\Roslyn-Project-System\DotNet-Project-System\$(Build.BuildNumber)`
Example:
`\\CPVSBUILD\drops\Roslyn\DotNet-Project-System\master\20180808.1`
vs.
`\\CPVSBUILD\drops\Roslyn\Roslyn-Project-System\DotNet-Project-System\20180808.1`
> Use Per Branch Build Folder

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractWorkspaceContextHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AdditionalFilesItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AnalyzerItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/MetadataReferenceItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/ProjectPropertiesItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/SourceItemHandler.cs
We already use EnsureInitialized in OnceInitializedOnceDisposed to mean "initialize this instance if its not already", not "make sure we're initialized, otherwise, throw".
> [Language Service]  Rename "EnsureInitialized" to "VerifyInitialized"

- src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/StringExtensions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IConfigurationDimensionDescriptionMetadataViewFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/ImplicitlyActiveDimensionProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/IConfigurationDimensionDescriptionMetadataView.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/IImplicitlyActiveDimensionProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/ImplicitlyActiveDimensionProvider.cs
Returns a set of implicitly active dimensions from specified set of dimensions, which can be used for disambiguation purposes. For example, in multi-targeting projects, the language service will use it in the context switch to distinguish in the following cases:
ClassLibrary (net45)
ClassLibrary (net46)
Consumption comes in a later PR.
> [Language Service] Add IImplicitlyActiveDimensionProvider

- netci.groovy
Without this change, a test failure will not cause an archive to happen
> set the archive trigger after the test results trigger

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IImplicitlyActiveDimensionProviderFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectChangeDiffFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectConfigurationFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/EvaluationHandlerTestBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/ProjectFilePathAndDisplayNameEvaluationHandlerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/ProjectFilePathAndDisplayNameEvaluationHandler.cs
Handles changing the file name and display name in reaction to a project file being renamed. This unifies all logic of setting touching IWorkspaceProjectContext in handlers, which lets us coordinate changes and prevent overlapping.
> [Language Service] Add ProjectFilePathAndDisplayNameEvaluationHandler

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContextTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs
ApplyChangesToWorkspaceContext was being rejected because each language provides a command-line parser, import them as an ImportMany.
> [LanguageService] Fix ApplyChangesToWorkspaceContext MEF rejection

- build/Versions.props
- src/Microsoft.VisualStudio.Editors/Common/Utils.vb
- src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj
- src/Microsoft.VisualStudio.Editors/OptionPages/GeneralOptionPageControl.xaml
- src/Microsoft.VisualStudio.Editors/OptionPages/GeneralOptionPageControl.xaml.vb
- src/Microsoft.VisualStudio.Editors/OptionPages/GeneralOptionPageResources.Designer.vb
- src/Microsoft.VisualStudio.Editors/OptionPages/GeneralOptionPageResources.resx
- src/Microsoft.VisualStudio.Editors/OptionPages/GeneralOptions.vb
- src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.cs.xlf
- src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.de.xlf
- src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.es.xlf
- src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.fr.xlf
- src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.it.xlf
- src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.ja.xlf
- src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.ko.xlf
- src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.pl.xlf
- src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.pt-BR.xlf
- src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.ru.xlf
- src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.tr.xlf
- src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.zh-Hans.xlf
- src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.zh-Hant.xlf
- src/VisualStudio.props
- Adding UserPreviewSdk option to .Net Core options page. 
- This setting has dynamic default value depending if VS was installed from Preview or Release channel.
- When user changing setting value, we create a sdk.txt file in the local AppData VS instance folder containing UsePreviews=True|False with current setting value. Absence of the file means setting has default value. Out-proc components will be able to determine default value by checking VS channel in the same way we do here.
> TFS611255 add UsePreviewSdk option

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectPropertiesFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IConfiguredProjectHostObjectFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IOleAsyncServiceProviderFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectHostProviderFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IUnconfiguredProjectVsServicesMock.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsContainedLanguageFactoryFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsProject_Factory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsTaskFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactoryTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/PropertyExtensions.cs
- Only look up IVsContainedLanguageFactory/LanguageServiceId once
- Remove base class, only need to just wait on InitializeAsync from the language service
- Move to CPS pattern of sync method calling async method
Tests forecoming as it doesn't have any. Confirmed that Razor plays nicely with these changes.
> Simplify VsContainedLanguageComponentsFactory logic

- src/CodeCoverage.runsettings
- src/Directory.Build.props
This makes Code Coverage work in Visual Studio again, also updated code coverage settings to match CodeCov.
> Get Visual Studio code coverage working

- build/Test.ruleset
'Var' usage in test code is marked as "refactoring-only" but due to https://github.com/dotnet/roslyn/issues/27819, all explicit type usage is marked as an error.
> Turn off IDE0001 in test code due to regression

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
Since We (NuGet) is working on enabling NuGet project lock file for VS 15.9, this PR is to SDK projects to pass lock file options during nomination for restore.
Feature Spec - https://github.com/NuGet/Home/wiki/Enable-repeatable-package-restore-using-lock-file#extensibility
Let me know if this isn't the right branch to target 15.9. Also, the feature is already approved for 15.9.
> Enabling NuGet project lock file options for NetCore SDK projects

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyTreeTelemetryService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/DesignTimeTelemetryLogger.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/VsTelemetryService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/ITelemetryService.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryEventName.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryPropertyName.cs
We have complicated logic inside VsTelemetryService to avoid allocating event and property names, centralize all names into a static class.
> Centralize telemetry events

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
Fixes #3568 
Prior code logged the fact that the project was not up to date, but didn't signal that information back to the calling method. If any items are `CopyAlways` then the up-to-date check can be short circuited.
Questions for reviewers:
1. Code in checks immediately above this change use the `Fail` method to capture a telemetry event. Should this also happen when we detect a `CopyAlways` item?
1. Unit tests... I looked into adding tests for this class. It's quite a meaty one with substantial dependencies, and I'm new to the code. Please advise!
> Never report up-to-date if CopyAlways item exists

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectSystemOptions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectSystemOptions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
The implementations don't do much, but in case of cancellation it may avoid an operation on the main thread.
> Propagate cancellation via IProjectSystemOptions

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Models/SubTreeRootDependencyModelTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyIconSet.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/AnalyzerDependencyModel.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/AssemblyDependencyModel.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/ComDependencyModel.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/DependencyModel.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/DiagnosticDependencyModel.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/PackageAnalyzerAssemblyDependencyModel.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/PackageAssemblyDependencyModel.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/PackageDependencyModel.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/PackageUnknownDependencyModel.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/ProjectDependencyModel.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/SdkDependencyModel.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/SharedProjectDependencyModel.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/SubTreeRootDependencyModel.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Dependency.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/AnalyzerRuleHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/AssemblyRuleHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/ComRuleHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/PackageRuleHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/ProjectRuleHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/SdkRuleHandler.cs
Currently every `Dependency` and `DependencyModel` stores four `ImageMoniker`s specifying the set of icons associated with the dependency. As each `ImageMoniker` is a struct containing a `GUID` and an `int` , each `Dependency` and `DependencyModel` ends up with at least 80 bytes of icon information.
While effectively each `Dependency` instance is unique there aren't that many distinct sets of icons--just one or two per type of dependency. We can thus save a fair bit of memory by breaking the icons out into a new type, `DependencyIconSet`, replacing all 80 bytes of `ImageMonikers`  with references to those sets, and reusing instances of `DependencyIconSet` where possible.
For context, before this change loading the dotnet/project-system solution results in 6,836 instances of `Dependency` …
> Move sets of ImageMonikers into their own type

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContextProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetRuleSubscriberBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetSubscriptionHostBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/ICrossTargetRuleHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/ICrossTargetSubscriber.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependenciesRuleHandlerBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs
I need to consume the new Microsoft.VisualStudio.Threading package in the language services, and the new analyzers are flagging certain usage within the dependency node because it's not awaiting results in certain places.
Looking at this usage, this entire infrastructure has no async code whatsoever and other code is not used at all, just remove all async from these code paths and removed unused methods.
Fixes two violations in https://github.com/dotnet/project-system/issues/3921.
> Remove async'ness of ICrossTargetSubscriber

- build/Default.ruleset
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/PackageRestoreInitiator.PackageRestoreInitiatorInstance.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectAssetFileWatcher.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AbstractMultiLifetimeComponent.cs
Per https://github.com/dotnet/project-system/pull/3908#discussion_r212955729, this rule is mostly noise for project-system because we derive from OnceInitializedOnceDisposed/OnceInitializedOnceDisposedAsync.
There's other usages of `#pragma warning disable` that I left because they aren't actually disposing the field that has been suppressed, such as https://github.com/dotnet/project-system/blob/dfe534a3e7803efb763ba9dcd35c5ce60c9104a5/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetRuleSubscriberBase.cs#L20. 
Note, that even after we dispose these usages, the rule will still fire - hence why we're turning it off. I left these suppressions so that we can find them, and using https://github.com/dotnet/project-system/issues/3927 …
> Turn off "CA2213: Disposable fields should be disposed" due to noise

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/DesignTimeAssemblyResolution.cs
The bug the workaround was referrring to was fixed in 15.3 and verified that the part no longer gets rejected.
> Remove workaround in DesignTimeAssemblyResolution

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectSystemOptions.cs
This reverts commit 765e42d97e35616cf4e2a73a536931d9d4df26f0.
Turns out that `SwitchToMainThreadAsync` does throw in the token is cancelled.
https://github.com/Microsoft/vs-threading/pull/368
> Revert "Throw if cancellation requested"

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.csproj
This was defaulting to assembly name.
> Set default namespace for Managed.UnitTests

- src/Microsoft.VisualStudio.Editors/ResourceEditor/Resource.vb
Rather than turn off the validation altogether, we now validate with the same method that re-writes the resource name for codegen. I couldn't actually get a validation failure this way as the codegen is pretty resilient, but it feels more future-proof.
Fixes #3954
> Validate after replacing invalid chars

- build/build.ps1
makes script run from vs command prompt even if relative path variables are used
> root paths for VSIX installation

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IApplyChangesToWorkspaceContextFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IEvaluationHandlerFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContextTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandlerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/EvaluationHandlerTestBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/ProjectFilePathAndDisplayNameEvaluationHandlerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/ProjectPropertiesItemHandlerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/SourceItemHandler_EvaluationTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceContextHostInstanceTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ContextHandlerProvider.Handlers.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ContextHandlerProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/ProjectFilePathAndDisplayNameEvaluationHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/ProjectPropertiesItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/SourceItemHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IApplyChangesToWorkspaceContext.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IContextHandlerProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IProjectEvaluationHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHandlerManager.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/RuleHandlerType.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceContextHost.WorkspaceContextHostInstance.cs
As a part of https://github.com/dotnet/project-system/issues/3425, I need to create public API with build/design-time & evaluation terminology. For better or worse, CPS refers to "design-time builds" as "project build" and as "evaluation" as "project evaluation" or just "project" so to try be consistent with it, I've gone and applied these terms across the new language service hookup. I avoided touching the old code - as it will be deleted when we turn the new one on.
> Rename "evaluation" and "design-time" usage in new language service hookup

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/ActiveWorkspaceProjectContextTrackerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ActiveWorkspaceProjectContextTracker.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IActiveWorkspaceProjectContextTracker.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/StringComparers.cs
This tracks Roslyn's active context by handling VSHPROPID_ActiveIntellisenseProjectContext - consumption in a future PR.
> Add ActiveWorkspaceProjectContextTracker

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/Web/DefaultHttpClient.cs
This is both good practice ([blog post](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/)) but also made the download of the file actually work in my dev environment. Previously I would regularly get task cancellations.
> Don't disponse HttpClient

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependencyFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/DependencyIconSetTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependencyTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/ImplicitTopLevelDependenciesSnapshotFilterTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TestDependency.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyIconSet.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependencyIconSetCache.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Dependency.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/ImplicitTopLevelDependenciesSnapshotFilter.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/IDependency.cs
When we create a `Dependency` from another `Dependency` or a `DependencyModel` we re-use their existing `DependencyIconSet`s. This greatly reduces memory consumption related to `ImageMoniker`s as there are usually only a couple dozen distinct icon sets in use within a solution, even with tens of thousands of dependencies.
However, this doesn't help when we're creating a `Dependency` from an `IDependencyModel` supplied by another component--for example, the NPM/Bower package dependencies added by ASP.NET tooling. In those cases we always create a new `DependencyIconSet`.
This change reduces memory usage for those implementations by adding a cache of `DependencyIconSet`s. Every time a `Dependency` creates a new `DependencyIconSet` it runs it through the cache to see if there is an existing …
> Add an icon set cache

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IFileSystemMock.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectItemSchemaFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectItemSchemaServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ItemType.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Composition/DeconstructionExtensions.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckItemComparer.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/StringComparers.cs
Here's a test suite that gives ~~55%~~ 95% coverage of `BuildToToDateCheck`. ~~I want to add more tests, but also want to get it in front of other eyeballs for feedback.~~ I've now added as many tests as I think are necessary.
Apart from the tests there are a few functional changes I'd like more knowledgable folks to review:
- 98b75a3aaad95172d3dba20a8d9d35aa9788a1e3 introduces `StringComparers.ItemTypes` and uses it in a few places where `Paths` was used previously, or none was specified.
- ea06eea323e09d3178363797d116392221b575b4 clears down the `_copiedOutputFiles` collection upon refreshing, as previously it would only ever be added to.
- 329b5f4937507f703eef8c9458556265461f7635 partially reverts a change I made in #3919 so that a file name appears in the log message correctly (the …
> Add tests for BuildUpToDateCheck

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/PackageRuleHandler.cs
Fixes #3915.
`PackageRuleHander` has a couple of helper methods, `GetEnumMetadata` and `GetBoolMetadata`, that look up some metadata on an item and return value as an enum or bool, respectively. They each take a `defaultValue` parameter, which is the value to return if the metadata is not found or can't be parsed properly. The way these methods are written, however, means that `defaultValue` is always ignored--in the case that `Enum.TryParse` or `bool.TryParse` fail we will instead get whatever default value _they_ choose for their `out` params.
This commit updates the methods so they no longer take a default value and instead return a nullable value. Now the call with either succeed with a value, or fail and return a null. The callers have been updated to use the null coalescing operator …
> Don't ignore default values

- src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerPanel.vb
When you open the Resources page in the AppDesigner and the default RESX is already open in another editor, we display a message that it's already open. If it happens to be uninitialized tab - we crashed because our check skipped it. Avoid that by also asking for uninitialized tabs when we check if the document is open.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/654708
> Avoid crashing when RESX already open in uninitialized tab

- build/Versions.props
- src/DeployIntegrationDependencies/DeployIntegrationDependencies.csproj
- src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/OpenProjectTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/TestBase.cs
Integration tests were;
- Expecting that VsRootSuffix was alway passed to it from config settings - it's not. We respect the ROOTSUFFIX environment variable, or default to 'Exp'
- Always running against the last build installed, not the build from which you run the test. We now respect the environment settings set via VS to pick the right version when running in UI. Will not affect outside of VS.
- VS was left running. I have no idea how Apex is supposed to work, but right now we only have a single test - I just close it after it by opting into DTE mode (I can't figure out how to do this outside of that), we'll need to think about how to do this for multiple tests. What is the expectation here?
- Introduced TestBase class, MSTest has a really weird init model and won't let me put …
> Allow integration tests to run from VS

- src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/OpenProjectTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/TestBase.cs
- Use default VisualStudio host
- Avoid second instance of Visual Studio opening
- Simplify test initialization (just use AssemblyInitialize, instead of ClassInitialize)
- Shutdown Visual Studio automatically after each test rather than making each test do it
> Simplify integration tests

- build/Versions.props
Cherry-pick of https://github.com/dotnet/project-system/pull/3942 to fix code coverage for 15.9.
> Update to codecov.exe that supports gzip

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs
We pass LanguageService as a fixed capability to CPS - but rather as raw capability it was an expression which caused them to ignore the capabilites. Fix it so that we continue to pass raw capability to project factory.
> [Master] Fix "fixed" capabilities not being set

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs
We pass LanguageService as a fixed capability to CPS - but rather as raw capability it was an expression which caused them to ignore the capabilites. Fix it so that we continue to pass raw capability to project factory.
> [LanguageService] Fix "fixed" capabilities not being set

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependencyExtensionsTests.cs
The `dependency2` var was unused. I believe it was intended to be used in this assertion. The test passes either way however.
> Fix copy/paste bug in test code

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/LanguageServiceErrorListProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ProjectContextCodeModelProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredProjectsLoader.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/ImplicitlyActiveConfiguredProjectReadyToBuild.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/TurnOffUseHostCompilerIfAvailableBuildPropertiesProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ILanguageServiceHost.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs
- Remove unused cancellation token, which simplifies a change I'm making in the future
- Opt components/services into both new and old language service, so when I turn on LanguageService2 they still turn on
- Remove "LanguageService" from dynamic capabilities
- This capability is always a fixed capability (comes from project factory registration), so this change has zero impact on the product, but prevents me from manually switching from LanguageService -> LanguageService2 while testing.
> Minor changes to get language service working

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Menus.vsct
These menus are defined in CPS so we don't need them. Verified edit project menu items work in context menu and Project menu after this change.
> Remove menus that already exist in CPS

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Threading/Tasks/TaskDelaySchedulerTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/AvoidPersistingProjectGuidStorageProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SDKVersionTelemetryServiceComponent.SDKVersionTelemetryServiceInstance.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/TaskDelayScheduler.cs
These are occasions where we have a cancellation token in flight and were calling a method that supports cancellation without passing the token.
> Pass cancellation tokens

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.CSharp.DesignTime.targets
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.FSharp.DesignTime.targets
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.VisualBasic.DesignTime.targets
Replaces #4024.
Following Microsoft/msbuild#3605, it's no longer necessary to append project paths to `MSBuildAllProjects`.
This PR removes our modification to that property in the input graph.
/cc: @AndyGerlicher, @jeffkl, @Pilchie
> Don't append project paths to MSBuildAllProjects

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/EditAndContinue/EditAndContinueProvider.cs
Enforce UI-thread for EditAndContinueProvider. Underlying edit & continue makes the assumption that this is only ever called on UI thread. Enforce that.
Need to change this implementation to consume new APIs for language-service and it's less churn if I pull this out into its own change.
> Enforce UI-thread for EditAndContinueProvider

- docs/repo/debugging/logging.md
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectSystemOptions.cs
- src/ProjectSystemSetup/Properties/launchSettings.json
Fixes #4021
- Remove `#if DEBUG`, control via environment variable only
- Configure launch settings for `ProjectSystemSetup` to set this variable
- Update documentation
> Show project output panel in release builds

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ConfiguredProjectImplicitActivationTrackingTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ConfiguredProjectImplicitActivationTracking.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IConfiguredProjectImplicitActivationTracking.cs
This was originally named to somewhat mimic IConfiguredProjectActivationTracking.ActivationTask, but everywhere else we avoid the "Task" suffix.
> Rename "IsImplicitlyActiveTask" -> "ImplicitlyActive"

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GroupedByTargetTreeViewProvider.cs
Fixes #3996.
The `GroupedByTargetTreeViewProvider.CreateOrUpdateProjectItemTreeNode` takes `additionalFlags` and `excludedFlags` parameters and uses them to update `viewModel.Flags`. However, the updated flags are not currently used.
This commit updates the method to make use of the flags. This will not change the current behavior as we do not actually pass in any relevant values for `additionalFlags` and `excludedFlags` but we want to avoid any surprises if/when we start to do so.
> Use computed flags

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IActiveWorkspaceProjectContextHostFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Build/LanguageServiceErrorListProviderTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactoryTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/LanguageServiceErrorListProvider.ErrorListDetails.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/LanguageServiceErrorListProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/EditAndContinue/EditAndContinueProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ProjectContextCodeModelProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/ProjectFileOrAssemblyInfoPropertiesProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IActiveWorkspaceProjectContextHost.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs
This interface will represent the "host" that matches the current configuration, and will eventually let me swap old integration with new integration.
> Rename ILanguageServiceHost -> IActiveWorkspaceProjectContextHost

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceContextHostInstanceTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceContextHostTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IWorkspaceProjectContextHost.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceContextHost.WorkspaceContextHostInstance.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceContextHost.cs
This lets consumers (error list, edit & continue, etc) run code against context while protecting against being disposed.
Consumption in a latter PR.
> Add IWorkspaceProjectContextHost

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependenciesSnapshotFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependencyFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDependencyModelFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IMockDependenciesViewModelFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/ITargetedDependenciesSnapshotFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GroupedByTargetTreeViewProvider.cs
There are a number of places where we have a nullable value type and we're performing a null check like so:
``` C#
struct Foo { ... }
Foo? f = ...
if (f != null && h.HasValue) { ... }
```
Unless the `Foo` type has an operator that takes a `Foo?` as a parameter this check is redundant; we don't need both the null check and the call to `HasValue`.
This commit removes the null check in these cases.
> Remove redundant check

- src/Microsoft.VisualStudio.Editors/PropPages/CSharpLanguageVersion.vb
- src/Microsoft.VisualStudio.Editors/PropPages/CSharpLanguageVersionUtilities.vb
Notes:
- I intend this change to go into dev16 preview1. Let me know if this is not the appropriate branch to achieve that.
- I did not make the "beta" label localizable. I don't think that's needed. Let me know if you think otherwise.
- dev16 RTM will ship with C# 8.0 marked as beta. The "beta" label will be removed in a later version.
Fixes https://github.com/dotnet/project-system/issues/3569
> Add LanguageVersion for C# 8.0 (beta)

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf
Previous message looks like it was written assuming compat information was updated early, but these days bits are available _very_ early.
Reported(?) on Twitter: https://twitter.com/ben_a_adams/status/1049847644745584641
Possibly the compat file should be updated to look further ahead than 3.0? Looks like @AngelosP owns that.
> Change default wording of the not supported version fallback message

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectItemSchemaServiceFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectValueDataSource.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/DebugProfileDebugTargetGenerator.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/PackageRestoreInitiator.PackageRestoreInitiatorInstance.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectAssetFileWatcher.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetRuleSubscriberBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Order/TreeItemOrderPropertyProviderSource.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredProjectsLoader.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ConfiguredProjectImplicitActivationTracking.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DataFlowUtilities.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
There is now a `DataflowBlockSlim` class that exists to reduce memory pressure associated with using dataflow types.  This PR switches to use it instead of creating new dataflow objects.
> Refactor blocks

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/LanguageServiceErrorListProvider.ErrorListDetails.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/LanguageServiceErrorListProvider.cs
Unneeded dependency here, just parent the files with the current project file.
> Stop using IWorkspaceProjectContext version of the project file name

- src/Microsoft.VisualStudio.Editors/OptionPages/GeneralOptionPageControl.xaml
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/WpfBasedPropertyPage.cs
ScrollViewer's are focusable by default, which means that you if you click them, they get focus rectangles. Turn this off, and turn them into WinForms-like panels, which still have scrollbars (and can be scrolled by paging through the controls).
Before:
After:
> Prevent ScrollViewer from being focusable

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPage.cs
Fixes: #2122 
Fixes: #646 
WPF will automatically inherit Windows Forms fonts https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/windows-forms-and-wpf-property-mapping. Make sure we set the Control.Parent if it's available, which sets this up.
> Inherit Font/Colors in WPF property pages

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Telemetry/SDKVersionTelemetryTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SDKVersionTelemetryServiceComponent.SDKVersionTelemetryServiceInstance.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryEventName.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryPropertyName.cs
This broke when d897cd2d merged into master, this code path changed to no longer automatically add the event prefix. Change this code to use the same pattern everywhere else.
This was only broken in Dev16.
> SDKVersion was pushing telemetry under wrong name

- src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsDesignerLoader.vb
- src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsDesignerView.vb
(This PR is easier to consume if you look at a commit at a time.)
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/706537.
If you edit the settings designer while debugging the project, Visual Studio crashes because checkout throws an ApplicationException when debugging.
There's two case that turn the "setting designer" into read-only mode; building the project (IsReadOnly) and debugging the project (!IsDesignMode). This change centralizes all usage of these cases into a single "IsDesignerEditable" property to avoid cases where we check one of those cases and not the other. Also removes the need to check these when we attempt to check-out the project. 
This crash has about 32 hits over the past month, so putting it in for 15.9 candidate.
>  Avoid crashing when editing settings while debugging

- src/Microsoft.VisualStudio.Editors/PropPages/DebugPropPage.vb
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/705763
When StartProgram has invalid characters and remote debugging is enabled, there are certain cases where the property page crashes during validation. When remote debugging is disabled, the validation check was being done in File.Exists which will always return false for invalid characters and would never hit this case.
~Merging into 15.9~, because this is our highest watson, with about ~100 hits in the past month.
> Avoid crash when StartProgram has invalid characters

- src/Directory.Build.props
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs
More leftovers from #4134. Apologies, these should have been removed in #4135
> Remove unused double click capability

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/TreeView/TestProjectTree.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContextProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GraphNodes/Actions/SearchGraphActionHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GroupedByTargetTreeViewProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/IDependenciesTreeServices.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/IDependenciesTreeViewProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Dependency.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/IDependenciesSnapshot.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySubscriptionsHost.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/TreeViewProviderBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Order/TreeItemOrderPropertyProvider.cs
Fixes #4140.
More changes made while reading through dependency node code. Easier to review commit-by-commit.
Starts out with removing unused code, tweaking documentation and some formatting.
I focussed on `DependenciesProjectTreeProvider`. It converts dependency snapshots into tree updates for CPS, among other things.
Some private methods were converted to local functions (as discussed over breakfast in Redmond with @davkean and @davidwengier). I generally find that if a private method is only used in one other member, it's a great candidate for conversion to a local function, and doing so often helps identify further opportunities. Unfortunately these transformations wreak havoc on the overall diff, hence being pulled out to separate commits: 7a46b4d6e5556d427656ee149e2dab92c9f8d3ce, …
> Dependency node grooming

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContext.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContextProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetSubscriptionHostBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/IAggregateCrossTargetProjectContextProvider.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/ITargetedProjectContext.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/TargetedProjectContext.cs
Fixes #4162 
- f92766180468a67f2b4cb992099b5ffcd2aea3b4 removes `IDisposable` from the interface and all code related to that
- 5a7a2b7a47033ff55221f8004cbe6d1e05f6541d makes `IAggregateCrossTargetProjectContextProvider.ReleaseProjectContextAsync` non-async
> ITargetedProjectContext isn't IDisposable

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/ImplicitTopLevelDependenciesSnapshotFilterTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/DependenciesSnapshotFilterBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/DuplicatedDependenciesSnapshotFilter.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/IDependenciesSnapshotFilter.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/ImplicitTopLevelDependenciesSnapshotFilter.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/SdkAndPackagesDependenciesSnapshotFilter.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/UnresolvedDependenciesSnapshotFilter.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/UnsupportedProjectsSnapshotFilter.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencySubscriptionsHost.cs
Unlike `IDependenciesSnapshotFilter.BeforeAdd`, it doesn't make sense for `IDependenciesSnapshotFilter.BeforeRemove` to modify the dependency. It either removes the dependency or does not.
Updated documentation to hopefully make the meaning of return and `out` vars clearer.
> IDependenciesSnapshotFilter.BeforeRemove returns bool

- Directory.Build.props
- Directory.Build.targets
- build/Codecov.proj
- build/Internal/Toolset.csproj
- build/Packages.targets
- build/Toolset.proj
- build/Versions.props
- setup/Directory.Build.targets
- setup/Microsoft.VisualStudio.NetCore.ProjectTemplates.1.x/Microsoft.VisualStudio.NetCore.ProjectTemplates.1.x.csproj
- src/DeployIntegrationDependencies/DeployIntegrationDependencies.csproj
- src/DeployTestDependencies/DeployTestDependencies.csproj
- src/Directory.Build.targets
- src/HostAgnostic.props
- src/Microsoft.VisualStudio.AppDesigner/Microsoft.VisualStudio.AppDesigner.vbproj
- src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj
- src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.csproj
- src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS/Microsoft.VisualStudio.ProjectSystem.FSharp.VS.csproj
- src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/Microsoft.VisualStudio.ProjectSystem.IntegrationTests.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.csproj
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj
- src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.csproj
- src/ProjectSystemSetup/ProjectSystemSetup.csproj
- src/VisualStudio.props
This is an updated attempt at simplifying the package reference versioning. This will make the move to Dev16 a lot simpler as we won't need to copy around the XXXVersion pattern.
> Simplify package reference version

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetRuleSubscriberBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetSubscriptionHostBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/ICrossTargetRuleHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependenciesRuleHandlerBase.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/PackageRuleHandler.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/SemaphoreSlimExtensions.cs
Many of these changes are in the cross-target code that @davkean points out is set to be cut, but for now I'm debugging in here and these changes help me focus and keep simple call stacks.
> Make some methods non-async

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GroupedByTargetTreeViewProvider.cs
In `GroupedByTargetTreeViewProvider` we call `ApplyProjectTreePropertiesCustomization` which enumerates `IProjectTreePropertiesProvider` instances, calling `CalculatePropertyValues`, allowing them to update an instance of `ReferencesProjectTreeCustomizablePropertyValues`.
However we don't then apply any customisations back to the `IProjectTreeNode`.
//cc: @abpiskunov -- do you know whether this was intentional? In testing I didn't find any providers that actually modified values.
Providers can also specify `Flags`. Should we applying them too too?
If there is a valid reason to not be applying these customised properties let me know and I'll document the fact in the code. I suspect this is an oversight that's been harmless so far.
> Use custom properties for project tree node

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs
This class needs to be made async, which prevents lock from being used in async methods. It does not need to be thread-safe as the only consumer of it, WorkspaceContextHostInstance, prevents overlap.
> Remove thread-safeness from ApplyChangesToWorkspaceContext

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IApplyChangesToWorkspaceContextFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContextTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceContextHostInstanceTests.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IApplyChangesToWorkspaceContext.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceContextHost.WorkspaceContextHostInstance.cs
This includes https://github.com/dotnet/project-system/pull/4187, so just review https://github.com/dotnet/project-system/commit/79d7b4a5f0c66271d5d7a84fd7baabca5e8a915a.
In preparation of making IWorkspaceProjectContext async, plumb through async in ApplyChangesToWorkspaceContext. Handlers will come next.
>  Make IApplyChangesToWorkspaceContext async

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
This handles the case where the project folder path goes invalid during a branch switch while the project is loading. This addresses the following feedback issue: https://developercommunity.visualstudio.com/content/problem/361196/project-system-encounters-a-fault-after-a-branch-s.html
> Add try/catch around setting up the file watcher

- src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/MultipleValuesStore.vb
- src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPageUserControlBase.vb
- src/Microsoft.VisualStudio.AppDesigner/PropPages/SKUMatrix.vb
- src/VisualStudio.props
To reduce conflicts when making package changes, it must easier for each project to redeclare their dependencies on a package than making use of package inheritance. To do that I have all VisualStudio projects (Managed.VS, CSharp.VS, etc) just declare their dependencies on packages in HostAgnostic instead of inheriting from their project reference to these projects.
> Reference HostAgnostic.props from VisualStudio.props

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Resources/ManagedImagesMonikers.cs
Adds `DebuggerDisplay` attributes for `ImageMoniker` and `ProjectImageMoniker` that produce strings such as `SdkWarning` for instances of these types in the debugger.
Previously the debugger would just show the type name, and when expanded the GUID and Id.
These changes have no effect unless a debugging.
Before:
After:
You can still see the GUID and Id if you expand the node.
> Improve image moniker debugging

- build/Default.ruleset
- build/Packages.targets
- src/DeployIntegrationDependencies/DeployIntegrationDependencies.csproj
- src/HostAgnostic.props
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.DebuggerTraceListener.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextProvider.ForegroundWorkspaceProjectContext.cs
Update Roslyn to the version currently in Preview 1 so that we can consume the new APIs for Razor.
> Update Roslyn dependencies

- src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectAccessorFactory.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectAssetFileWatcher.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectAccessor.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectAccessor.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCheckoutOption.cs
Fixes: https://github.com/dotnet/project-system/issues/4200.
This was regressed in https://github.com/dotnet/project-system/commit/c7fac9f3723f0ef23cd7fb07acd477d33114d313#diff-286141d8d6dce9c17a55788e87581b6d. To trigger reevaluation, we mark the MSBuild project as dirty, and call ConfiguredProject.NotifyProjectChange. Previously this did not checkout the project, but did so when we moved it to use ProjectAccessor. Avoid checking out the project on this path.
> Avoid checking out project when assets file changed

- src/Microsoft.VisualStudio.Editors/PropPages/BuildEventCommandLineDialog.vb
Fixes: [646597](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/646597) and [646592](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/646592)
Previously, after expanding or collapsing the macro list, the tab order would move down to the OK button instead of staying on the Macro button. This PR fixes that behavior.
After clicking on Macros >> before fix:
It moves to the OK button.
After clicking on Macros >> After fix:
It stays on the (now visible)  << Macros Button.
It also fixes it in the reverse case.
> Fix Tab Order on Build Event Command Line Prop Page

- src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.resx
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.cs.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.de.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.es.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.fr.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.it.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ja.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ko.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.pl.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.pt-BR.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ru.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.tr.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.zh-Hans.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.zh-Hant.xlf
Fixes [646505](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/646505)
I confirmed that Narrator and and Inspect have the correct behavior.
The actual string to add can be changed, I added what I thought was intuitive:
Specific Warnings: "Specific Warnings To Treat As Errors"
XML documentation file: "XML Document File Path"
> Added Accessible Names For Build Prop Page

- src/Microsoft.VisualStudio.Editors/PropPages/AssemblyInfoPropPage.resx
- src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.resx
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.cs.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.de.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.es.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.fr.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.it.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.ja.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.ko.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.pl.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.pt-BR.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.ru.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.tr.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.zh-Hans.xlf
- src/Microsoft.VisualStudio.Editors/PropPages/xlf/AssemblyInfoPropPage.zh-Hant.xlf
Fix for: [646509](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/646509)
Changed the .AccessibleName to the recommended names for the Assembly Version and File Version. Before, the narrator would only read "Major, Minor, Build, Revision" instead of saying whether it was Assembly or File Version.
Now, Narrator will announce which one you are changing. 
I confirmed that Narrator and and Inspect have the correct behavior.
> Assembly Information Property Page Accessible Name Change

- .vsts-dnceng.yml
Against dev16.0.x so that if any other PRs to that run into trouble we'll already have it there.
> Also publish the raw test result log files directory

- build/build.ps1
This is an alternative to https://github.com/dotnet/project-system/pull/4176, this handles both Dev15/Dev16. It does not, however, make uninstalling of the integration tests work - we'll need a follow up for that.
> Correctly locate MSBuild on Dev16

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/ProjectFileOrAssemblyInfoPropertiesProvider.cs
We can use the new IWorkspaceProjectContext.Id property.
> Remove usage of AbstractProject

- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceContextHost.WorkspaceContextHostInstance.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextProvider.cs
Roslyn will avoid updating VisualStudioWorkspace until after a batch has finished.
> Wrap context usage in a batch

- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/ITargetFramework.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/TargetFramework.cs
- src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/TargetFrameworkProvider.cs
`IVsFrameworkCompatibility.GetNearest` throws `ArgumentNullException` when we pass it `null`.
These changes should avoid exceptions seen as part of [this ticket](https://developercommunity.visualstudio.com/content/problem/366616/high-cpu-when-idle.html) ([internal issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/714441)).
(Really looking forward to nullable reference types!)
> Prevent ArgumentNullException when FrameworkName is null
