src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsDataSource.cs
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1113.md
=> RCS1113: Use 'string.IsNullOrEmpty' method

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/BuildMacroInfo.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/FrameworkReferenceIdentity.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/Interop/VsProjectExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependencyIconSet.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsUpgradeLoggerFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectLaunchTargetsProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/WindowsForms/WindowsFormsAddItemFilterTests.cs
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1032.md
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1123.md
=> RCS1032/RCS1123: Add parentheses when necessary/Remove redundant parentheses

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchSettingsUIProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IActiveEditorContextTracker.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectTreeProviderExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/IProjectDesignerService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryPropertyName.cs
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1243.md
=> RCS1243: Duplicate word in a comment

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/WritableLaunchSettings.cs
Find is faster apparently.
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1077.md
=> RCS1077: Optimize LINQ method call

tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IActiveConfiguredProjectProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectTreeProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectTreeServiceFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/UnconfiguredProjectFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ActiveConfiguredProjectsProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/DependencyRuleTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshotTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client.UnitTests/SolutionExplorer/ProjectNodeCommandHandlerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectTreeCustomizablePropertyContextFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/VisualBasicNamespaceImportsListFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcherTests.cs
These were missed by https://github.com/dotnet/roslyn/issues/46992
=> Code Analysis messages

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/SolutionExplorer/ProjectNodeExtender.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/DebugFrameworksDynamicMenuCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/DebugFrameworksMenuTextUpdater.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/StartupProjectHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/AggregateContainsRelationCollectionSpan.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Commands/ReferenceManagerCommandHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VersionCompatibility/DotNetCoreProjectCompatibilityDetector.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WindowsForms/WindowsFormsEditorProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredProjectsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ActiveDebugFrameworkServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/MetadataExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/AppDesignerFolderProjectTreePropertiesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.ImplicitProjectCheck.cs, tests/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/ProjectLayoutTestBase.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/ExportedRuleTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/MiscellaneousRuleTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/ComponentVerificationTests.cs
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1146.md
=> RCS1146: Use conditional access

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/RenamerProjectTreeActionHandler.cs
This includes https://github.com/dotnet/project-system/pull/6549, so just review https://github.com/dotnet/project-system/commit/e353438339081998be9c4a199d19d5e9d82795a2.
=> Extract Publish into a separate method

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/IRelatableItem.cs
Instances of this interface are not exposed via MEF.
=> Remove invalid ProjectSystemContract attribute

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/AppDesigner.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/AppDesignerFolderRenameHandler.cs
Fixes: https://github.com/dotnet/project-system/issues/81
=> Fix AppDesignerFolder when renamed

src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.Designer.vb, src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.resx, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.cs.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.de.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.es.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.fr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.it.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ja.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ko.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.pl.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ru.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.tr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf
See https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/Warnversion%20Warning%20Waves.md
=> Update WarningLevel values to include 5

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/CrossTarget/IDependenciesRuleHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/DependenciesRuleHandlerBase.cs
=> Minor cleanup in DependenciesRuleHandler

build/import/Packages.targets
=> Bump compiler to 3.8.0-4.20464.1

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerEditorFactory.vb
Some small fixes observed while looking at our the app designer editor factory a while back.
=> Editor factory tidying

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
=> Use correct state object to prevent race condition

.editorconfig
Due to: https://github.com/dotnet/roslyn/issues/48236
=> Turn off crashing analyzer

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Frameworks/TargetFramework.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/LaunchTargetPropertyPageEnumProvider.cs
=> Remove redundant code

build/import/Packages.targets
=> Upgrade compiler to 3.8.0-4.final

build/import/Packages.targets
=> Move to latest version of Code Style analyzers

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectLaunchTargetsProviderTests.cs
This makes it easier to filter these exceptions out during debugging sessions.
=> Throw specific exception type

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/Tree/SpecialWebFolderFlag.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/Tree/SpecialWebFolderPropertiesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/Tree/SpecialWebFolderPropertiesProviderDataSource.cs
=> Plumb through code folders

build/import/Packages.targets
=> Update VS validation and threading packages

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.State.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Utilities/SetDiff.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
This additional logging info will help debug certain situations such as that described in #6647.
=> Up to date check logs changed item info

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/WebConfigSpecialFileProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AppConfigSpecialFileProvider.cs
This enables ASP.NET web context to find the web.config and modify it when needed.
=> Add a special file provider for "web.config"

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/Menus.vsct
Fixes [AB#1218044](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1218044)
Add missing command.
=> Add Edit Project File command to menu Project in Nexus client.

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/IWebProject.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/IWebProjectProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/IWebProjectServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/IntelliSense/Interop/IVsCodeBehindEventBinding.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/IntelliSense/Interop/IVsWebApplicationProject.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/IntelliSense/Interop/WebContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/IntelliSense/WebApplicationProject.Instance.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/IntelliSense/WebApplicationProject.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/IntelliSense/WebProjectContextHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/WebProjectProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Web/WebProjectServices.cs
Stubbed implementation of IVsWebApplicationProject which fires up an IVsWebProjectContext for legacy ASP.NET and Razor intellisense.
This is not ready for review.
=> Stubbed implementation of IVsWebApplicationProject

src/Microsoft.VisualStudio.AppDesigner/GlobalSuppressions.vb, src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerEditorFactory.vb
There is no concept of cancellation via this argument. It's role is to pass flags when creating the document in the RDT.
This PR does not change anything functionally. It just removes something that's confusing.
=> Simplify prop page designer

docs/repo/property-page-architecture.drawio.svg, docs/repo/property-page-architecture.md
Add a document describing the architecture of the new project property
pages at a high level, along with a layer diagram.
=> Initial version of new property page documentation

build/import/Packages.targets
Fixes #6738 
We are getting the feeds to these packages from the other sources so removing myget to avoid any confusion.
=> Remove references to myget

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/ProjectFilePathAndDisplayNameEvaluationHandler.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/ProjectFilePathAndDisplayNameEvaluationHandlerTests.cs
Reverts dotnet/project-system#6736
=> Revert "Code cleanup - handle key not found"

build/import/Packages.targets
=> Bump several build/test package versions

src/Microsoft.VisualStudio.ProjectSystem.Managed/Build/BuildUtilities.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Build/BuildUtilitiesTests.cs
=> Remove 'delimiter' handling

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/CategoryByIdDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/CategoryFromPropertyPageDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/ConfigurationDimensionDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/ConfigurationDimensionFromPropertyDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageByIdDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageFromProjectDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/QueryDataByIdProducerBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/QueryDataFromProviderStateProducerBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/SupportedValueDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/SupportedValueFromPropertyDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIEditorMetadataFromValueEditorProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIEditorMetadataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyByIdProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyEditorByIdDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyEditorFromUIPropertyDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyFromPropertyPageDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyValueFromUIPropertyDataProducer.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/ConfigurationDimensionDataProducerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/SupportedValueDataProducerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/UIEditorMetadataProducerTests.cs
This refactoring actually reduces code (gasp!). It may be best to examine the changes one commit at a time.
=> More refactoring of the Project Query API implementation

ProjectSystem.sln, build/ci/SignToolData.json, setup/SharedSetup/AssemblyRedirects.cs, setup/SharedSetup/SharedSetup.csproj, setup/SharedSetup/source.extension.vsixmanifest, src/Microsoft.VisualStudio.ProjectSystem.Managed.Shared/Microsoft.VisualStudio.ProjectSystem.Managed.Shared.csproj, src/Microsoft.VisualStudio.ProjectSystem.Managed.Shared/Packaging/ManagedProjectSystemSharedPackage.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.Shared/PublicAPI.Shipped.txt, tests/Microsoft.VisualStudio.ProjectSystem.Managed.Shared.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.Shared.UnitTests.csproj
It's currently just a placeholder as it doesn't contain nor do anything but we'll eventually need it so adding a stub for now.
=> Create new shared assembly

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshotTests.cs
Relates to https://github.com/dotnet/project-system/issues/6777
=> Improve error message to assist debugging

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/PackageContentProjectTreePropertiesProvider.cs
=> Reuse ProjectTreeFlags field rather than create instance

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.cs
Minor cleanup following #6814.
This method is moderately complex. This change helps make logic slightly clearer.
=> Simplify PackageDependencyModel construction

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/DisposableBag.cs
=> Remove unnecessary suppressions

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreUnconfiguredInputDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/LinqExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectConfigurationExtensions.cs
Clearing these out of my workspace.
=> Remove some minor redundancies in code

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
Fixes https://github.com/dotnet/project-system/issues/6845
cc @drewnoakes @jjmew 
fyi @olgaark @zivkan & @wli3
=> Add CLRSupport to the nomination data sent to NuGet

build/ci/richnav.yml, build/ci/unit-tests.yml
=> Add `main` branch trigger to yml files

src/Common/BannedSymbols.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/TargetFrameworkMonikerValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TargetFrameworkProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Frameworks/ITargetFrameworkProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Frameworks/TargetFramework.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesTreeViewProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependencyTreeTelemetryService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/TargetDependencyViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.ContextTracker.cs, tests/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/DependencyNodeIntegrationTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IMockDependenciesViewModelFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/DependenciesViewModelFactoryTests.cs
Reverts dotnet/project-system#6712 and #6840
=> Revert "Remove target framework moniker parsing code"

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Subscription.cs
Fixes #6881.
Prior to #6852, there was a race condition between the first request to `IsUpToDateAsync` and check's input dataflow. It was possible to query the up-to-date status before the first input data had been ingested. When that occurred a build would be scheduled, which was generally harmless as we (currently, may change for #6633) always schedule the first build to be requested for each project.
In #6852, code was added that caused the caller of `IsUpToDateAsync` to wait until the first input data had been received. This was a step towards #6185 and #6633.
In "command line" mode, several VS capabilities are not enabled, including design-time builds. When CPS invokes our `IBuildUpToDateCheckProvider` in this command line mode, this new wait on input data hangs indefinitely. Without …
=> Fix up-to-date check hang in command line mode

.github/workflows/teams-notifications.yml
=> Try fixing notifications

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/ProjectItemsSchema.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/ProjectItemsSchema.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/ProjectItemsSchema.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/ProjectItemsSchema.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/ProjectItemsSchema.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/ProjectItemsSchema.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/ProjectItemsSchema.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/ProjectItemsSchema.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/ProjectItemsSchema.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/ProjectItemsSchema.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/ProjectItemsSchema.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/ProjectItemsSchema.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/ProjectItemsSchema.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/ProjectItemsSchema.xaml.zh-Hant.xlf
~I'm not sure that this value is actually displayed anywhere in reality, and it doesn't appear to be localised.~
=> Fix typo in ProjectItemsSchema

docs/repo/property-pages/property-specification.md
Add a link to #6971 to the property page documentation.
=> Add an example to property-specification.md

docs/repo/property-pages/property-specification.md
- Fix heading level
- Describe the editor used for file/directory properties
=> Update Property Specification documentation

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextProvider.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IWorkspaceProjectContextFactoryFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextProviderTests.cs
=> Partially revert #6979 due to DDRITs failures

build/ci/official.yml
=> Remove blocking task

build/ci/official.yml
Reverts dotnet/project-system#7058
=> Revert "Remove blocking task"

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ExecutableDebugPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ProjectDebugPropertyPage.xaml
=> Set distinct icons for launch profile kinds

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesProjectTreeProvider.cs
Fixes #7079
Reuses the `IProjectTreeActionHandler` interface with custom contract name `"DependencyTreeRemovalActionHandlers"` via which extensions may prohibit or be notified of dependency removals from the tree.
---
An example of such an extension is:
```c#
[Export("DependencyTreeRemovalActionHandlers", typeof(IProjectTreeActionHandler))]
[AppliesTo(ProjectCapabilities.AlwaysApplicable)]
internal sealed class ProjectReferenceRemovalHandler : IProjectTreeActionHandler
{
public bool CanRemove(IProjectTreeActionHandlerContext context, IEnumerable<IProjectTree> nodes, DeleteOptions deleteOptions = DeleteOptions.None)
{
// Block removal if required. This should be fast, as it will be called on the UI
// thread as part of QueryStatus for commands.
return true;
}
public Task …
```
=> Add extension point for dependency tree item removal

build/import/Packages.targets, build/import/Versions.props, build/script/SetVSEnvironment.cmd, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ProjectContextCodeModelProvider.cs
Updating more packages as they become available. Additionally we're renaming our packages to have the 17.0 suffix.
This is still not functional, it's WIP but publishing it to unblock others
=> Update packages regarding Merged PIAs

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/TreatWarningsAsErrorsValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf
Reverting changes from https://github.com/dotnet/project-system/pull/7053.
=> Reverting changes from https://github.com/dotnet/project-system/pull/7053

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/LanguageServiceErrorListProvider.cs
Handle null values properly to remove squiggles.
=> Code cleanup.

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProvider.cs
=> Remove some allocations in LaunchProfilesDebugLaunchProvider

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210424034853427 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210424034853427 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210424114742479 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210424114742479 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210424194706918 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210424194706918 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210425114729191 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210425114729191 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210426034605373 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210426034605373 to main

build/import/Versions.props, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/VsContainedLanguageComponentsFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IOleAsyncServiceProviderFactory.cs
Fixes [AB#1318210](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1318210)
=> Fixes Yellow bar after opening .net core solution 

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210427194704851 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210427194704851 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210427194737890 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210427194737890 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210427194815751 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210427194815751 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210427194909485 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210427194909485 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210427195027653 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210427195027653 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210427195232062 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210427195232062 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs
I will push a new implementation to fix this issue.
=> Revert github3680

build/import/Versions.props
Signing is taking excessively long. Trying to update the tool to see if this fixes the issue.
=> Update version of SignTool

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/DebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513034711787 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513034711787 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/DebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513034731664 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513034731664 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/DebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513034832823 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513034832823 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/DebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513034929822 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513034929822 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/DebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513035115993 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513035115993 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/DebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513114618091 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513114618091 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/DebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513114634374 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513114634374 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/DebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513114655897 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513114655897 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/DebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513114729415 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513114729415 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/DebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513114827538 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513114827538 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/DebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513115018602 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513115018602 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/DebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513034756544 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210513034756544 to main

build.cmd, build/import/HostAgnostic.props, build/import/Packages.targets, build/import/Versions.props, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducer.cs
Relevant work to stabilize preview 1. Fixes #7190
=> Update packages and set warnings as errors again

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/es/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ko/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pt-BR/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ru/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/DebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/DebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/DebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/DebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/DebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/DebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/DebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210514030400514 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210514030400514 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hans/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/DebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210514114657299 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210514114657299 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/it/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pl/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/DebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/DebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/DebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/DebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210518034620722 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210518034620722 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1146599

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf
=> Add ProduceReferenceAssembly property to Build section

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProjectTypeCapabilities.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs
Depends on https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/313873.
=> Add new CachedProjectEvaluation capability to default capabilities

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/AddLaunchProfileAction.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/DuplicateLaunchProfileAction.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/ILaunchSettingsActionService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/LaunchProfileActionBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/LaunchSettingsActionService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/RemoveLaunchProfileAction.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/RenameLaunchProfileAction.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileFromProjectDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ILaunchSettingsProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/LaunchProfiles/LaunchSettingsActionServiceTests.cs
There are a few different but related changes here; I recommend reading the commits one at a time.
=> Improve handling of Launch Profile actions

tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Resources/XliffTests.cs
We were using an xUnit 'theory' for this, but it was producing too many cases which resulted in this warning being logged:
> No of subresults in test case: `Microsoft.VisualStudio.Resources.XliffTests.ResourceStringsDoNotContainMultipleAcceleratorMnemonics` are more than supported limit 1000, truncating remaning ones.
Changing this to a regular fact removes the warning and cleans up our build log.
These warnings appear here, for example:
=> Fix warning when running unit tests

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/AbstractReferenceHandler.cs
- Fix potential `NullReferenceException`
- Remove unused local variable
=> Fixes in abstract reference handler

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ConfigurationGeneralPage.xaml
This conflict was causing the issue seen in #7275.
=> Rename rule to differentiate it

build/import/Packages.targets
=> Bump CPS packages to 17.0.610-pre

docs/repo/property-pages/visibility-conditions.md
https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/327513 adds several new functions. They are documented here.
=> Document new visibility condition functions

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210605034814771 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210605034814771 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/es/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ko/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210604144729888 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210604144729888 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ru/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210606194711086 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210606194711086 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pl/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210606114711449 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210606114711449 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/it/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210606034703776 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210606034703776 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hans/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210605194642685 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210605194642685 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pt-BR/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210604194655930 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210604194655930 to main

docs/launch-profiles.md
A brain dump of information about launch profiles and how they are used in VS.
=> Add some basic information about launch profiles

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/ApplicationPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210608114658408 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210608114658408 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/ApplicationPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210609194702661 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210609194702661 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ApplicationPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210609114634788 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210609114634788 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/cs/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ko/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pt-BR/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hant/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210622034852567 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210622034852567 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/DebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/DebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/DebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ProjectDebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210623194711937 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210623194711937 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1197416

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/DependenciesTreeSearchProvider.cs
[ADO work item]( https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1343688/)
Related PR: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/332572
New order: DependenciesTreeSearchProvider, HierarchySearchProvider, GraphSearchProvider
=> Add order attribute for DependenciesTreeSearchProvider

build/ci/official.yml
fixes #7163
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_wiki/wikis/DevDiv.wiki/12566/Using-Scale-Set-pools-for-Build-Pipelines
=> Changing to using the Scale Set Pools

build/ci/official.yml
=> Temporary workaround to remove ibc

src/Microsoft.VisualStudio.Editors/PropPages/xlf/ru/ApplicationPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ru/ApplicationPropPageVBWinForms.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ru/AssemblyInfoPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ru/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ru/compileproppage2.xlf.lcl, src/Microsoft.VisualStudio.Editors/Resources/xlf/de/Microsoft.VisualStudio.Editors.Designer.xlf.lcl, src/Microsoft.VisualStudio.Editors/Resources/xlf/fr/Microsoft.VisualStudio.Editors.Designer.xlf.lcl, src/Microsoft.VisualStudio.Editors/xlf/ru/Menus.vsct.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210628114702612 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210628114702612 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/TargetPlatformMonikersValueProvider.cs
on the VS Win side, it needs to include the version for the target platform.
Before 
•	vs.solution.project.targetplatformmonikers="ios;android;windows"
After
•	vs.solution.project.targetplatformmonikers="ios;android;windows10.0.19041.0"
=> Add target platform version to "vs/solution/project/used"

setup/ProjectSystemSetup/Properties/launchSettings.json
=> Remove unnecessary profiles for Dotnet Project System

setup/ProjectSystemSetup/ProjectSystemSetup.csproj
Fixes: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1331873.
These were made priority 1 to match CPS.
=> Opt into NGEN for Managed.dll and Managed.VS.dll

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManager.cs
There are going to be times when Hot Reload is in use and the process(es) need to be restarted. Maybe the user has made a code change that was applied to the process, but they don't have a good way of invoking the modified code. In that case we may provide a "Restart Hot Reload" button. Alternatively, they may make a "rude edit"--a code change that would compile, but is outside of the ability of Hot Reload to apply to a running process. In that case we show a dialog offering them the option of restarting. Either way, we need to shut down all the processes associated with a Hot Reload session and then execute a Ctrl+F5 to build and start the processes again. If we don't shut them down first, the build will fail.
The only part of this the project system is responsible for is shutting down …
=> Kill Hot Reload processes when requested

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileFromProjectDataProducer.cs
Make use of the changes in #7482.
=> Eliminate a potential allocation

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf
Move various Hot Reload strings to resources so they can be translated.
=> Move strings to resources

docs/repo/property-pages/property-specification.md
=> Document use of PasswordString editor type

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf
=> Add 'Advanced' section to build property page

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/SequentialTaskExecutor.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Threading/Tasks/SequentialTaskExecutorTests.cs
Fixes #3853. See that issue for a description of the problem and its resolution.
This change will contribute towards [AB#1370097](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1370097)
=> Use JoinableTaskContext in SequentialTaskExecutor

docs/repo/property-pages/property-specification.md
This interface was previously internal to CPS. https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/347718 makes it public and changes the signature as shown.
=> Update link action handler docs

build/import/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/ReferenceCleanupService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/Interop/VsHierarchyExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ImmutableCollectionLinqExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/LinqExtensions.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsCompilerTests.cs
Bumps to the latest stable compiler/analyzers and fixes up consequent warnings.
=> Update Roslyn package versions

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1338485

src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/Win32FileSystem.cs
Enables the open of the stream to occur asynchronously.
=> Pass useAsync as true for file streams

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManager.cs
We have a bug in `HotReloadSessionManager.ActivateSessionAsync` such that it is possible for the process to exit _after_ we've hooked the `Process.Exited` event but before we've started the session. The event handler could end up running on another thread and calling `StopSessionAsync` before the session has started. Then `ActivateSessionAsync` ends up starting a session for the exited process--and because the `Exited` event has already fired we don't get another chance to stop it.
To fix this we need to prevent concurrent access to the `HotReloadSessionManager` state. We already protected the `ImmutableDictionary` of active sessions through the use of `ImmutableInterlocked` but this does nothing to protect the state of the objects _within_ the dictionary. In this change we introduce an …
=> Fix a race in starting Hot Reload sessions

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/DebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/DebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/DebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/DebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/DebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/DebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/DebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210910212216797 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210910212216797 to main

src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb
[AB#1398006](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1398006)
=> Replace 'white list' with 'safe list'

src/Microsoft.VisualStudio.Editors/PropPages/xlf/cs/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/de/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/es/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/fr/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/it/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ja/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ko/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/pl/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/pt-BR/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ru/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/tr/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/zh-Hans/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/zh-Hant/CodeAnalysisPropPage.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210913155036254 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210913155036254 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreDataSource.cs
=> Remove redundant null suppressions

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/ImplicitlyTriggeredBuildManager.GlobalPropertiesStore.cs
This class returns one of two values. Rather than compute those values over time, we can precompute them and track which to provide using a single boolean.
=> Remove allocations and locking

build/import/Packages.targets, build/import/Versions.props
=> Updating version of OpenCover

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/es/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/it/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ko/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pl/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pt-BR/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ru/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hans/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210924212323175 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20210924212323175 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManager.cs
Fixes [AB#1397443](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1397443).
Currently, if the user unloads a project or closes the solution while a Hot Reload session is in progress the session remains, but we now lack any way to interact with it. In some situations this "zombie" session can block changes to later sessions or cause other problems.
The fix here is to end a project's active sessions when the project is unloaded and the `ProjectHotReloadSessionManager` is disposed. Note that we don't wait for the call to `StopSessionAsync` to complete as we just need the session to be stopped sometime soon.
=> Stop Hot Reload on project unload

build/ci/TSAConfig.gdntsa, build/ci/compliance.yml
Define a basic pipeline that runs PoliCheck.
The point here is just to get PoliCheck to run. Later commits will expand on this.
=> Define a basic compliance pipeline

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/CompoundTargetFrameworkValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml
Addresses [AB#1374662](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1374662) and [AB#1404849](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1404849).
This PR contains improvements on the TargetFramework experience.
I.e. MAUI project.
=> Address TargetFramework feedback.

src/Microsoft.VisualStudio.ProjectSystem.Managed/Collections/EnumerableExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs
This improves the reusability of that fix.
See suggestion at https://github.com/dotnet/project-system/pull/7646#discussion_r719858545
=> Make helper method from #7646 an extension method

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureDetector.ProjectChecker.cs
Fixes [AB#1430106](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1430106)
The previous code assumed that there was only a single export of `IBuildUpToDateCheckProvider` in each configured project scope. The definition of that interface indicates it is an "extension" point, meaning there may be potentially many such exports.
In cases where multiple exports existed, an `InvalidOperationException` would be raised within `ActiveConfiguredValue<T>.GetValue` due to the use of `Enumerable.SingleOrDefault` in the `GetExportedValueOrDefault` extension method.
It turns out that we are only interested in knowing whether the check that also implements `IBuildUpToDateCheckValidator` is enabled, so it is simpler (and more correct) to import the single validator …
=> Fix assumption about cardinality of exports

src/Microsoft.VisualStudio.Editors/ResourceEditor/Resource.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceListView.vb
Addresses [AB#1417218](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1417218).
=> Remove user input from telemetry event.

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/it/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hans/VSResources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20211105212247235 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20211105212247235 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureDetector.ProjectChecker.cs
Fixes #7747
When a solution contains both .NET and C++ projects, some projects may not export an instance of `IBuildUpToDateCheckValidator`. This change handles such cases.
=> Handle absent IBuildUpToDateCheckValidator export

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureDetector.cs
This is a VS service, so accessing it from the package's service collection is not necessary.
=> Use IVsService to access SBM

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/CodeAnalysisPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20211112222335024 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20211112222335024 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1474568

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/CodeAnalysisPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20211119222210368 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20211119222210368 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.fr.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1478929

build/ci/unit-tests-template.yml
These show up as errors in VS:
=> Trim trailing white space in YML

src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/WindowsRegistry.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/LinqExtensions.cs
=> Use using declaration

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsCompiler.CompilationQueue.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/ProjectConfigurationDimensionProviderTestBase.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/ComponentVerificationTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/VisualBasic/MapDynamicEnumValuesProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/References/ReferenceCleanupServiceTests.cs
=> Use destructuring

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/StartupProjectHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/PropertyPageElementHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/LaunchProfileActionBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/DebugUtilities.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/RelationAttachedCollectionSourceProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VersionCompatibility/DotNetCoreProjectCompatibilityDetector.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/ExportedRuleTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/ConfigurationDimensionDataProducerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/UIEditorMetadataProducerTests.cs
Converts code to use newer C# pattern matching.
=> Use pattern matching

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/LaunchSettingsQueryVersionProvider.cs
The collection is never queried.
=> Remove unused collection of LaunchSettingsTrackers

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProjectTypeCapabilities.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IGlobalSettingExtensionValueProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ILaunchProfileExtensionValueProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ILaunchProfileExtensionValueProviderMetadataFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ILaunchSettingsProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IRemoteAuthenticationProviderFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDebuggerSettingsFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IRemoteDebuggerAuthenticationServiceFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/PostBuildEventValueProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/PreBuildEventValueProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Waiting/VisualStudioWaitContextTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Waiting/VisualStudioWaitIndicatorTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Telemetry/SDKVersionTelemetryTests.cs
=> Use static classes where possible

src/Microsoft.VisualStudio.ProjectSystem.Managed/Delimiter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/ITaskDelayScheduler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/TaskDelayScheduler.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Threading/Tasks/TaskDelaySchedulerTests.cs
Follows the discovery of unused code in #7789.
=> Delete unused code

CONTRIBUTING.md, docs/repo/getting-started.md, docs/up-to-date-check.md
=> Reference VS2022 in documentation

build/import/Packages.targets
=> Unify some MS.VS package versions

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
Fixes #7813
If a new project's first build is a rebuild, we were showing an invalid warning about a broken incremental build.
This occurred because the up-to-date check fails if it has never been run before. During rebuild, we skip up-to-date checks (the build is forced), so when that rebuild completes and we run the up-to-date check again, it would decide it had never been run before, and would fail and log the warning.
This fixes that edge case by passing a flag that disables this first-run check for validation runs.
=> Fix invalid incremental build warning

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProvider.cs
Fixes #7596.
`LaunchProfilesDebugLaunchProvder.GetActiveProfileAsync` current throws an exception if there is no active launch profile. This is a problem, as there is _no_ guarantee that there will always be a launch profile.
We do try to provide a default launch profilewhen the launchSettings.json file doesn't exist (and this is normal when creating a new project--there's no reason to require a mostly empty launchSettings.json just so the user can run the project they just created with default settings). But that profile can be deleted or replaced by other components, and it may even be possible to ask for the launch settings before we've had a change to add that default.
So in the general case we need to handle the possibility that there are no launch profiles at all, and thus no active …
=> Handle missing launch profile

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/cs/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/de/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/es/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/fr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/it/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ja/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ko/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pl/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pt-BR/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ru/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/tr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hans/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hant/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20211224222241270 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20211224222241270 to main

docs/up-to-date-check.md
See commit titles for details of changes.
=> Fast up-to-date check documentation improvements

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml
Adding 2 links to the TargetFramrwork properties to the Microsoft Docs website.
=> Add documentation links to TFM properties.

src/Microsoft.VisualStudio.ProjectSystem.Managed/LinqExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DataflowUtilities.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.ProjectChange.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs
A set of small changes, pulled out from larger work to follow in a subsequent PR.
=> Small changes

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/cs/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/de/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/es/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/fr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/it/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ja/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ko/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pl/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pt-BR/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ru/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/tr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hans/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hant/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220128222317076 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220128222317076 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1579333

src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.resx, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.cs.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.de.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.es.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.fr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.it.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ja.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ko.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.pl.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ru.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.tr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.zh-Hant.xlf
=> Add accessible name to Suppress warnings textbox.

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ISourceItemsHandlerFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContextTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextHostInstanceTests.cs
Cherry-pick of #7889 for the 17.2 branch, to take to the QB in order to fix Razor language in 17.2 preview 1.
=> [17.2] Fix source item reporting

.github/ISSUE_TEMPLATE/branch-checklist.md
Some changes to the checklist that I would have found helpful while creating the `17.2.x` branch today. I've also updated the OneNote separately.
@tmeschter please take a look as the most recent person to use this check list.
=> Update branch checklist

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/AssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ProjectReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1582980

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/AssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ProjectReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1583660

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/AssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ProjectReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1587135

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/AssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ProjectReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1587139

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/AssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ProjectReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1587143

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/AssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ProjectReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1591890

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/AssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ProjectReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1592346

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/AssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ProjectReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1592531

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/AssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ProjectReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1593187

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/AssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ProjectReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1594264

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/AssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ProjectReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1597150

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/AssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ProjectReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1601237

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/AssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ProjectReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedAssemblyReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedCOMReference.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Dependencies/xlf/ResolvedProjectReference.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1601467

src/Microsoft.VisualStudio.Editors/OptionPages/xlf/cs/GeneralOptionPageResources.xlf.lcl, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/de/GeneralOptionPageResources.xlf.lcl, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/es/GeneralOptionPageResources.xlf.lcl, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/fr/GeneralOptionPageResources.xlf.lcl, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/it/GeneralOptionPageResources.xlf.lcl, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/ja/GeneralOptionPageResources.xlf.lcl, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/ko/GeneralOptionPageResources.xlf.lcl, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/pl/GeneralOptionPageResources.xlf.lcl, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/pt-BR/GeneralOptionPageResources.xlf.lcl, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/ru/GeneralOptionPageResources.xlf.lcl, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/tr/GeneralOptionPageResources.xlf.lcl, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/zh-Hans/GeneralOptionPageResources.xlf.lcl, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/zh-Hant/GeneralOptionPageResources.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/cs/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/de/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/es/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/fr/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/it/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ja/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ko/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/pl/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/pt-BR/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ru/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/tr/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/zh-Hans/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/zh-Hant/BuildPropPage.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220211222349263 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220211222349263 to main

src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.cs.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.de.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.es.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.fr.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.it.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.ja.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.ko.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.pl.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.ru.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.tr.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.zh-Hant.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.cs.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.de.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.es.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.fr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.it.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ja.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ko.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.pl.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ru.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.tr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1611647

src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.cs.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.de.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.es.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.fr.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.it.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.ja.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.ko.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.pl.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.ru.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.tr.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/OptionPages/xlf/GeneralOptionPageResources.zh-Hant.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.cs.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.de.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.es.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.fr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.it.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ja.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ko.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.pl.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ru.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.tr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1612278

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckStatePersistence.cs
Replaces #7929.
Previously we would block the main thread while waiting for serialization of the fast up-to-date check's persistent state to occur.
This change:
- Ensures persistence happens on a background thread, not the main thread.
- Ensures solution close is not held up on the writing of this file by starting during `OnBeforeCloseSolution` and joining that async work in `OnAfterCloseSolution`.
=> Improve solution close performance

src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/IFileSystem.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Log.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.Designer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf
I'm preparing a PR for a larger bit of work. These changes have been pulled out of that work, to make that later PR easier to review.
See commit messages for summary of changes.
=> Small bits pulled from larger work

docs/repo/property-pages/visibility-conditions.md
We have added four new functions to be used in visibility condition expressions.
=> Update visibility condition documentation

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1636510

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/es/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/it/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ko/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pl/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pt-BR/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ru/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hans/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220305012501398 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220305012501398 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1647957

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1663409

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1672963

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/cs/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/de/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/es/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/fr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/it/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ja/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ko/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pl/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pt-BR/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ru/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/tr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hans/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hant/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220318212359058 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220318212359058 to main

docs/repo/dependencies-node-roadmap.md
Adds some additional structure, information and a diagram using GitHub's new Mermaid support.
=> Extend dependencies node documentation

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1682678

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ProjectDebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220325212351804 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220325212351804 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1682142

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1682970

src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerView.vb, src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourcesFolderService.vb
=> Fix encoding errors in doc comments

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/es/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/it/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ko/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pl/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pt-BR/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ru/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hans/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/PackagePropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/PackagePropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/PackagePropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/PackagePropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/PackagePropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/PackagePropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/PackagePropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/PackagePropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/PackagePropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/PackagePropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/PackagePropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/PackagePropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/PackagePropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220415212432873 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220415212432873 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1723126

docs/repo/property-pages/README.md, docs/repo/property-pages/property-specification.md, docs/repo/property-pages/string-property-validation.md
Provide an example of string property validation, and brief explanation
=> document string property validation

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.tr.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1733665

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/LaunchProfileActionBase.cs
Part of fix for regressions in launch profiles (my bad).
=> Ensure launch profile pages request new visibility condition properties

build/import/Versions.props
Update the version for 17.3 Preview 1.
=> Update version for 17.3 Preview 1

build/import/Versions.props
Update the version to indicate that we are now targeting 17.3 Preview 2.
=> Update version for 17.3 Preview 2

tests/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/Construction/Solution.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Build/BuildUtilitiesTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/ProjectConfigurationDimensionProviderTestBase.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/AssemblyInfoPropertiesProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/DependenciesTreeViewProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/VisualBasic/RenamerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsDataSourceTests.cs
Converts test data given in multi-line strings to C#'s new raw strings. They are easier to read and require less escaping of values.
=> Convert to raw strings

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.tr.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1733672

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/CodeAnalysisPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220408212403960 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220408212403960 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.tr.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1733720

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.tr.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1733724

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.tr.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1733739

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1737762

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1739254

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1740241

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1745108

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1748064

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1748851

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1752560

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1752797

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1752968

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1755318

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ProjectDebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220506223501758 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220506223501758 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1760267

docs/repo/property-pages/README.md, docs/repo/property-pages/property-specification.md, docs/repo/property-pages/property-value-interception.md
=> Add documentation on property value interception

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Collections/ConcurrentHashSet.cs
This PR implements the Clear() method to remove all elements in the set.
---
Note: This will be used in #8127.
=> Implement Clear() in ConcurrentHashSet<T>

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1760920

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1760949

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Acquisition/MissingSetupComponentRegistrationService.cs
Refactor `MissingSetupComponentRegistrationService` to improve readability of the intention of `ShouldDisplayMissingComponentsPrompt()`
--------
Note: This pr should go before #8127.
=> Code cleanup in MissingSetupComponentRegistrationService

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1766361

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1764079

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1765327

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1765672

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsJsonEncoding.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsJsonEncodingTests.cs
There are a few changes here:
- Increase our test coverage for processing of launchSettings.json data.
- Fix a bug where a global setting could be written more than once.
- Fix serialization of complex types in "other settings" data (fixes #8160).
=> Fix launch profile serialization of "other settings"

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1774592

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/es/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/it/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ko/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pl/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pt-BR/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ru/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hans/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220520221418649 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220520221418649 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1782540

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1782621

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ISafeProjectGuidService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Log.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/VsSafeProjectGuidService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryPropertyName.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ISafeProjectGuidServiceFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Telemetry/SDKVersionTelemetryTests.cs
Contributes to #8213 
Adds:
- Project identifier
- Check number
See linked issue for context.
=> Extend fast up-to-date check telemetry

build/proj/Build.proj
Replaced the logic to determine if we want to publish CodeCov during the build to use a boolean variable.
=> Code coverage adjustment

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/cs/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/de/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/es/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/fr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/it/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ja/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ko/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pl/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pt-BR/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ru/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hans/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220527215935087 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220527215935087 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1804143

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ActiveConfiguredProjectsProviderTests.cs
This duplicates one from CPS, with a different name. We only used it once in test code.
=> Remove capability constant

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/StartupObjectsEnumProvider.cs
Fixes [AB#1556918](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1556918)
=> Handle null pointer in PropertyPages when getting StartupObjecs for VB

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.VisualBasic.DesignTime.targets
Adds the `ProjectCapability` that turns on the new property pages for VB projects.
=> Turn on the new property pages for VB

.github/fabricbot.json
Update fabricbot.json to apply the 17.4 milestone to changes in main and the 17.3 milestone to changes in 17.3.x.
=> Update milestone tracking

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSResources.xlf.lcl
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1857583

build/import/Versions.props
Update the pre-release version to indicate that we are targeting 17.4 Preview 1, not 17.4 Preview 3.
=> Update pre-release version

docs/up-to-date-check.md
=> Document each of the fast up-to-date check's build reasons

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1869345

src/Microsoft.VisualStudio.Editors/PropPages/xlf/zh-Hans/PackagePropPage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/es/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/it/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ko/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pl/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pt-BR/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ru/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hans/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/PackagePropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220715212509613 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220715212509613 to main

src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.zh-Hans.xlf
=> Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1884487

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/UniversalRemoteAuthenticationProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs
=> Add string capability for SupportUniversalAuthentication

docs/up-to-date-check.md
A customer understandably reported this as a point of confusion. I wrote this explanation to share with them, and as a reference for future people who might hit this quirky behaviour.
=> Document potential discrepancies between FUTDC logging and build summary

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Acquisition/MissingSetupComponentRegistrationService.cs
Fixes [AB#1587569](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1587569)
=> Handle null pointer

docs/repo/property-pages/property-conditions.md
Documents the new has-evaluated-values for ConfiguredVisibilityConditionEvaluator, for #8354
=> Document has-evaluated-values function

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureOutputWindowReporter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureTelemetryReporter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/FeatureFlagNames.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/FeatureFlags.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreDataSource.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PackageRestore/PackageRestoreDataSourceTests.cs
=> Put all feature flags definitions in one place.

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryPropertyName.cs
=> Add telemetry properties for NuGet restore cycle detector.

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Add well known contexts for xaml rules in CPS
=> Add description of Contexts for xaml rules in CPS

eng/pipelines/templates/build-official-release.yml, eng/pipelines/templates/build-pull-request.yml, eng/pipelines/templates/publish-assets-and-packages.yml
Update some of the outdated comments. Added a few extra links.
=> Comments update for pipelines

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/cs/Resource.BrowseObject.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/de/Resource.BrowseObject.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/es/Resource.BrowseObject.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/fr/Resource.BrowseObject.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/it/Resource.BrowseObject.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/ja/Resource.BrowseObject.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/ko/Resource.BrowseObject.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/pl/Resource.BrowseObject.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/pt-BR/Resource.BrowseObject.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/ru/Resource.BrowseObject.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/tr/Resource.BrowseObject.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/zh-Hans/Resource.BrowseObject.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/xlf/zh-Hant/Resource.BrowseObject.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220829102729646 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220829102729646 to main

build/ci/integration-tests.yml, build/ci/one-loc-build.yml, build/ci/richnav.yml, build/ci/unit-tests.yml
This change is required for builds to continue working in the new org, dev.azure.com/dnceng-public.
=> Update public pool names

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs
Fixes [AB#1600327](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1600327)
Previously we checked whether we were running in command line mode only during the initialisation of `LanguageServiceHost`.
Another code path that requires this check is the `ProjectAutoLoad` method. Without that check, a task is registered via `PrioritizedProjectLoadedInHostAsync` that will not complete, blocking project load indefinitely.
This change adds such a check. It also adds validation on other public methods to ensure they are not called while in command line mode. These checks convert bugs from hangs to exceptions, making them easier to diagnose and fix.
=> Fix language service blocking load in command line mode

.github/ISSUE_TEMPLATE/branch-checklist.md
Infrastructure changes have modified the accounts involved in these PRs. The prior URL only showed old insertion PRs.
=> Fix insertion PR URL in branch checklist issue template

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs
Back-ports two changes for 17.4 preview 2:
- #8455
- #8456
=> [17.4 preview 2] Language service updates

eng/pipelines/templates/analyze-api.yml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs
Similar to #8461 except actually targets the correct branch this time.
Also includes @MiYanni's API scan timeout change, in the hopes of making CI pass properly.
=> [17.4 preview 2] Language service updates (take two)

eng/pipelines/official.yml
Disabling APIScan for the time being.
=> Disable APIScan

eng/pipelines/official.yml
Disabling APIScan for the time being.
=> Disable APIScan - 17.4-preview2

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/FileMoveNotificationListener.cs
This is recursively iterating through all directories to get the list of files.
Repro:
The fix:
=> Allow update namespace to files when folder move

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/FeatureFlagNames.cs
This makes it easier to find one of these strings when we search for them.
Similar to #8480
=> Inline feature flag name prefix field

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSPackage.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.zh-Hant.xlf
Relates to #7761
Replaces #7764
These strings are no longer in use and should be removed.
=> Remove unused template resource strings

src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorTelemetry.vb
=> Track resource comment and link counts in telemetry

docs/repo/coding-conventions.md
=> Improve formatting of coding convention document

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf
=> Remove NU1108 from message in NuGet restore cycles detection

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/IUpToDateCheckStatePersistence.cs
=> Fix typo in doc comment

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hans/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220928212957366 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220928212957366 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220930214321259 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20220930214321259 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20221003214157056 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20221003214157056 to main

.github/fabricbot.json
=> Add milestone tracking for 17.4.x

.github/fabricbot.json, ProjectSystem.sln, version.json
Bump the version number of the `main` branch to 17.5, and update the milestone tracking.
=> Update version number

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
Fixes https://github.com/dotnet/project-system/issues/8568
We are targeting 17.5 with this. I imagine main is the correct branch, but happy to retarget if needed.
=> Add WarningsNotAsErrors to nomination

ProjectSystem.sln
Add the nuget.config file to the solution-level "items" folder.
=> Add nuget.config to the solution

eng/imports/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ExternalContracts.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/Editors/ImplicitUsingsEditor/CSharpImplicitUsingsControl.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/Editors/PropertyEditorBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/ProjectImports/ImportTreeCommandGroupHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WPF/AppDotXamlDocument.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WPF/ApplicationXamlFileAccessor.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WindowsForms/MyAppFileAccessor.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/WPF/Converters/Converters.LambdaConverter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/WPF/Converters/Converters.LambdaMultiConverter.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfileEnvironmentVariableEncoding.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/VBWarningsValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PageItemRuleProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/TreatWarningsAsErrorsRuleProvider.cs
The newer compiler and analyzers produced new diagnostics on our code, which have also been addressed to remain free of warnings.
=> Bump compiler and analyzer versions

eng/imports/HostAgnostic.props, eng/imports/Packages.targets
These are the complete set of code and comment changes needed to address CPS' new namings. In reviewing, if you'd like to try out some manual scenarios, please go here: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/427756?_a=files - check out the PR branch and build.
=> CPS breaking changes refactor

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectTreeExtensions.cs
=> Fix typo in local variable name

eng/imports/Packages.targets, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Setup/PackageContentTests.ProjectSystem.verified.txt, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Setup/PackageContentTests.VisualStudioEditorsSetup.verified.txt
=> Bump VSSDK build tools package

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/ProjectPropertiesItemHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/LanguageService.xaml
=> Document LanguageService XAML rule and related code

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureDetector.ProjectChecker.cs
=> Code cleanup - remove unnecesary parameter in the constructor

eng/scripts/GetInsertionPRDescription.ps1
- Fix small bug with Diff link
- I didn't realize that question mark `?` was valid as part of a variable name in PowerShell
- Allow Squash and Merge PR titles to be included in the description
- Realized this when this insertion had no PRs listed: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/431632
- You can see the title difference when looking at the commit log for the repo:
- https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6875452&view=results
- https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/431812?_a=overview
- This fixed the diff link. I can't test the 'squash and merge' listing without actual PRs that are merged that way.
=> Insertion Description - Minor Fixes

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Runtimes/MissingSdkRuntimeDetector.cs
Improve readability in source code.
=> Code cleanup missing runtime detector

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IMissingSetupComponentRegistrationService.cs
=> Add comments to IMissingSetupComponentRegistrationService

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Acquisition/MissingSetupComponentRegistrationService.cs
=> Improve readability of MissingSetupComponentRegistrationService

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/cs/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/de/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/es/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/fr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/it/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ja/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ko/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pl/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pt-BR/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ru/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/tr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hans/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hant/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20221102212616962 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20221102212616962 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/ImplicitlyTriggeredDebugBuildManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/DebugFrameworksDynamicMenuCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/DebugFrameworksMenuTextUpdater.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/AuthenticationModeEnumProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/DebugProfileDebugTargetGenerator.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/DebugProfileEnumValuesGenerator.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/IRemoteDebuggerAuthenticationService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/IStartupProjectHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/OutputTypeChecker.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/OutputTypeCheckerTest.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IRemoteDebuggerAuthenticationServiceFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IStartupProjectHelperFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/DebugFrameworksDynamicMenuCommandTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/DebugFrameworksMenuTextUpdaterTests.cs
This is part of https://github.com/dotnet/project-system/issues/8571
=> Refactor - move Vs independent code to project system managed.

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ReferencesPage.VisualBasic.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20221109222939018 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20221109222939018 to main

src/Microsoft.VisualStudio.Editors/PropPages/xlf/cs/PackagePropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/de/PackagePropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/es/PackagePropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/fr/PackagePropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/it/PackagePropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ja/PackagePropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ko/PackagePropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/pl/PackagePropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/pt-BR/PackagePropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ru/PackagePropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/tr/PackagePropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/zh-Hans/PackagePropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/zh-Hant/PackagePropPage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20221114222723524 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20221114222723524 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/BindingBehavior.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/KeyValuePairListEncoding.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceFactoryTests.cs
These were appearing as errors in the IDE.
=> Fix IDE diagnostics about usings within namespaces

eng/scripts/GetInsertionPRDescription.ps1
Related: https://github.com/dotnet/project-system/pull/8639
In my previous set of VS insertion description fixes, I allowed for 'squash and merge' PRs to show up. However, I didn't realize the `body` of those is empty. This fixes that by using the text part of the `subject` as the `body`.
https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/436225
With this fix, [that commit](https://github.com/dotnet/project-system/commit/4b6b283280a3a55f62f3ecb620dd8ac45478c3cb) should show up as:
> - [8670: Revert ImportedNamespaces to use DynamicEnumProperty](https://github.com/dotnet/project-system/pull/8670)
=> Fix 'squash and merge' insertion description

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ReferencesPage.VisualBasic.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20221116231851365 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20221116231851365 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/cs/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/de/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/es/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/fr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/it/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ja/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ko/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pl/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pt-BR/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ru/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/tr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hans/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hant/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20221205230137615 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20221205230137615 to main

tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/ProjectPropertiesRuleTests.cs
Drew caught a minor bug in the unit tests I merged last week: https://github.com/dotnet/project-system/pull/8713/commits/2130b9598b67ea85d69aed39f69811e1063bdf4e#r1045348839.
=> Minor logic fix in loc unit tests

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Setup/PackageContentTests.cs
=> Add GenerateAssemblyInfo property

eng/imports/Packages.targets
=> Use stable version of compiler

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20221230222619570 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20221230222619570 to main

docs/repo/debugging/design-time-builds.md
I find this code useful on occasion and wanted to document it somewhere public, rather than keeping it in my private notes.
=> Document full-fidelity binlogs from DTBs

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/cs/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/de/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/es/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/fr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/it/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ja/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ko/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pl/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pt-BR/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ru/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/tr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hans/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hant/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230106132000618 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230106132000618 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
=> [17.5] Two fixes for the QB

.github/fabricbot.json, version.json
Noticed we are tagging merged PRs as 17.5 with the msftbot. 
This updates it to tag it as 17.6. It also updates our version.json file.
=> Update version number.

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckStatePersistence.cs
Fixes [AB#1577423](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1577423)
The FUTDC cache file could, for any number of reasons, contain invalid data that leads to an error during deserialisation.
This change adds error handling to prevent such errors causing user-visible issues. If an error is detected, we discard the cache. It will be rebuilt automatically.
(Easier to review if you ignore white space.)
=> Handle errors when deserialising FUTDC cache data

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.VisualBasic.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ReferencesPage.CSharp.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ReferencesPage.VisualBasic.xaml
=> Fix duplicate order number

docs/build-acceleration.md, docs/up-to-date-check.md
Provides guidance for verbose build acceleration logs, and tips for diagnosing problems.
=> Document build acceleration log analysis

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/it/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230124125933032 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230124125933032 to main

src/Common/GlobalAssemblyInfo.cs, src/Common/GlobalAssemblyInfo.vb, src/Directory.Build.props, src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/WindowsFileExplorer.cs
Resolves https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1712534/
=> Secure ShellExecute/DLLImport

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ko/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/tr/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230127222934845 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230127222934845 to main

src/Microsoft.VisualStudio.Editors/PropPages/CodeAnalysisPropPage.resx, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.cs.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.de.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.es.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.fr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.it.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.ja.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.ko.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.pl.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.pt-BR.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.ru.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.tr.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.zh-Hans.xlf, src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/CodeAnalysisPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.zh-Hant.xlf
See https://github.com/dotnet/roslyn/issues/66788
=> Enforcing code style on build is no longer experimental

src/Microsoft.VisualStudio.Editors/PropPages/xlf/cs/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/de/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/es/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/fr/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/it/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ja/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ko/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/pl/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/pt-BR/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ru/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/tr/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/zh-Hans/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/zh-Hant/CodeAnalysisPropPage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/CodeAnalysisPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/CodeAnalysisPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230215022251661 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230215022251661 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/cs/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/de/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/es/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/fr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/it/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ja/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ko/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pl/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pt-BR/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ru/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/tr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hans/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hant/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230217225434453 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230217225434453 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependencyRulesSubscriberBase.cs
The class `DependencyRulesSubscriberBase` is responsible for subscribing to data from configured projects, and releasing those subscriptions when needed.
Previously, the code was written in a way that would only work if there was one subscription at the `UnconfiguredProject` level. However, for multi-targetted projects, there may be multiple such subscriptions (one per `ConfiguredProject`). The code would only remember the last one, replacing the reference to any prior subscription.
This meant that operations that triggered the reconstruction of subscriptions would not properly clean up the old ones, leaking dataflow chains indefinitely.
This change ensures that multiple subscriptions are disposed properly when needed.
=> Fix subscription leak in dependencies tree

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/es/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/it/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ja/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pt-BR/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ru/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/tr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hant/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230224224227972 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230224224227972 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/cs/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/de/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/fr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ko/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pl/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hans/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230227222724829 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230227222724829 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/cs/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ja/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ko/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ru/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hans/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230301225844381 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230301225844381 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/de/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/es/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/fr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/it/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pl/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pt-BR/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/tr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hant/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230303223212111 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230303223212111 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/RenamerProjectTreeActionHandler.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/RenamerTestsBase.cs
This code path was instantiating the Roslyn package along this path and causing Launch Profiler to take longer to initialize than it should take.
```
mscorlib.dll!System.Lazy<Microsoft.VisualStudio.ProjectSystem.IProjectTreeActionHandler>.CreateValue() Unknown
mscorlib.dll!System.Lazy<Microsoft.VisualStudio.ProjectSystem.IProjectTreeActionHandler>.LazyInitValue() Unknown
Microsoft.VisualStudio.ProjectSystem.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.ProjectTreeActionContext.GetAddNewItemDirectory(Microsoft.VisualStudio.ProjectSystem.IProjectTreeActionHandlerContext context, Microsoft.VisualStudio.ProjectSystem.IProjectTree target) Line 107 C#
Microsoft.VisualStudio.ProjectSystem.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.Desig …
```
=> Avoid instantiating Roslyn package via RenamerProjectTreeActionHandler

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230308222634747 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230308222634747 to main

docs/repo/property-pages/property-specification.md, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ExecutableDebugPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ProjectDebugPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hant.xlf
Fixes #8034 (for good this time).
See https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/455702 for more details
=> Text-wrap by default for command line arguments

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ExecutableDebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230313212641270 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230313212641270 to main

eng/imports/Packages.targets
This reflects the version change in VS which impacts all in-proc code.
=> Bump Newtonsoft.Json to 13.0.3

eng/imports/Packages.targets, src/Microsoft.VisualStudio.Editors/OptionPages/GeneralOptionPage.vb, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/ImplicitlyActiveConfiguredProjectReadyToBuild.cs
=> Bump dataflow and threading

docs/up-to-date-check.md
Adds a brief note that other project systems have different approaches to handling their up-to-date checks, and links to a useful document for VC projects.
=> Cross reference VC docs on incremental build

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Shipped.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Unshipped.txt
=> Updates to API

src/Common/BannedSymbols.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/TaskResult.cs
We have our own properties for these.
=> Ban TplExtensions.True/False tasks

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/IHotReloadDiagnosticOutputService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/IProjectHotReloadAgent.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/IProjectHotReloadSessionManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/IProjectHotReloadUpdateApplier.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/TargetFrameworkMonikerValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/QueryDataProviderBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Commands/DependenciesContextMenuProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Commands/HideAddReferenceCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Commands/ReferenceManagerCommandHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Commands/SuppressObjectBrowserForPackageReferenceCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/ProjectImports/ImportTreeCommandGroupHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/IInterceptingPropertyValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/LaunchProfiles/IGlobalSettingExtensionValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/LaunchProfiles/ILaunchProfileExtensionValueProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/IProjectBuildEventListener.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/ISolutionBuildContextProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/ISolutionBuildEventListener.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/WPF/IApplicationXamlFileAccessor.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/WinForms/IMyAppFileAccessor.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Workloads/IWebWorkloadDescriptorDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/TaskResult.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TestDependencyExtensions.cs
Addresses all instances of this diagnostic in the IDE. Made via fix-all in VS.
=> Fix IDE0002 across solution, simplifying names

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/BuildPropertyPage.VisualBasic.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230405223119149 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230405223119149 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/BuildPropertyPage.VisualBasic.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230407213001853 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230407213001853 to main

eng/imports/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/GenerateNuGetPackageTopLevelBuildMenuCommand.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/OrderingHelper.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/ReferenceCleanupService.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/RenamerProjectTreeActionHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Imaging/FSharp/FSharpProjectImageProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/AssemblyAttributeProperties/AbstractProjectFileOrAssemblyInfoPropertiesProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/PackagePropertyPage/PackageFilePropertyValueProviderBase.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/AssemblyInfoPropertiesProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Order/TreeItemOrderPropertyProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProviderTests.cs
=> Bump compiler and analyzers

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Workloads/WebMissingWorkloadDetector.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Workloads/IWebWorkloadDescriptorDataSource.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Workloads/WebWorkloadDescriptorDataSource.cs
=> Improve use of dataflow and general perf in missing workload detection

eng/scripts/GetInsertionPRDescription.ps1
There were a few things related to the insertion description that Drew pointed out to me over the last couple months. I wanted to address them here.
- The PR list would bug out when double quotes (`"`) were included.
- This was found [in this insertion](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/459691). The [build log](https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=7502428&view=logs&j=d58a6a34-8c26-597b-aa5c-b9a7e66e5056&t=9f7ffec7-f238-54a1-42ea-53b7cfb882d6) shows the correct description (see images below). Looking into it, it seems that [passing the description](https://devdiv.visualstudio.com/Engineering/_git/MicroBuild?path=/src/Tasks/InsertVsPayload/plugin.ps1&version=GBmain&line=243&lineEnd=245&lineStartColumn=5&lineEndColumn=6&lineStyle=plain&_a=content …
=> A few "Quality of Life" insertion description changes

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/cs/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/de/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/es/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/fr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/it/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ja/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ko/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pl/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pt-BR/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ru/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/tr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hans/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hant/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230424213043354 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230424213043354 to main

eng/imports/HostAgnostic.props, eng/imports/Packages.targets, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/LanguageServiceErrorListProvider.ErrorListDetails.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/ProjectLaunchProfileHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/DesignTimeTelemetryLogger.cs
Reverts dotnet/project-system#8991
=> Revert "Update package versions"

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/PackagePropertyPage/PackageFilePropertyValueProviderBase.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1748809
In certain situations, the user can provide values to the Package Readme and Package Icon properties that are MSBuild evaluated to be empty (such as an MSBuild property that doesn't exist). CPS doesn't allow the `Include` attribute of a None item to be empty. This will throw an NFE in this scenario. This wraps our logic that attempts to do this in a try/catch so that we simply don't take action if the operation throws. We'll return the current value so it doesn't affect the user negatively.
Testing this, there is one side-effect. If it evaluates the value as empty, it still creates the property. This seems to be how `AddAsync` is implemented on the `IProjectItemProvider`. If this isn't acceptable, I think a change on …
=> Fix for NFE on Package properties (Readme/Icon)

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.VisualBasic.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230508212744353 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230508212744353 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesTreeBuilder.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesTreeProvider.cs
@MiYanni provided a review on #9008 shortly after it was merged. This PR addresses his feedback.
=> Changes from code review

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/Snapshots/ImmutablePropertyCollection.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ImmutableCollectionLinqExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/Snapshots/RestoreBuilder.cs
Changes described in each of the commits. Probably easiest to review commit-by-commit.
=> Reduce allocations in package restore code

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/BuildPropertyPage.VisualBasic.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230526214318922 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230526214318922 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependencyGroupType.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/SharedProjectDependencySubscriber.cs
- [Remove unused constructor parameters](https://github.com/dotnet/project-system/commit/69f74152663101a05b0bf8488e61ae92609b2b13)
- [Remove unneeded upstream data source joins](https://github.com/dotnet/project-system/commit/2d7b17b0ba9e11b23942c0a9d7e8839694157392)
- [Document DependencyGroupType properties](https://github.com/dotnet/project-system/pull/9047/commits/d01200efe3822ca8c5b870f0663ea40d71dc586d)
=> Minor clean up in SharedProjectDependencySubscriber

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/VBDefineConstantsEncoding.cs
=> Avoid using try-catch for program flow

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/AbstractProjectConfigurationProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/CSharp/CSharpProjectConfigurationProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/ProjectLaunchProfileHandler.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileDataProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileTypeDataProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/ProjectActionProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageDataProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageFromProjectDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyValueDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/BindingBehavior.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Extensibility/IProjectExportProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Waiting/WaitIndicatorResult.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/Text/LazyStringSplit.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IConfigurationGroupFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/ISolutionBuildManagerFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/PreBuildEventValueProviderTests.cs
This applies a codefix solution-wide, to address some warnings shown in the IDE.
=> Simplify names

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/cs/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/de/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/es/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/fr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/it/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ja/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ko/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pl/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ru/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hans/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hant/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230602212912689 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230602212912689 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pt-BR/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/tr/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230605213348355 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230605213348355 to main

eng/tools/OneLocBuildSetup/Program.cs
=> Add StringComparison arg in localization project

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/ProjectDebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230609213259466 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230609213259466 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ProjectDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ExecutableDebugPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ProjectDebugPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230614212501164 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230614212501164 to main

eng/imports/OptProf.targets
=> Run Optprof only for net472

spelling.dic, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/PackagePropertyPage/PackageFilePropertyValueProviderBase.cs
Test PR following #9103 to validate the the spelling.dic file's encoding works correctly with git and GitHub, making reviews/merges easier. It looks promising on the command line.
=> Minor spelling updates

docs/repo/joy-of-dataflow.md
Add a new recipe describing how to transform or filter existing dataflows.
=> Add a new recipe

eng/pipelines/official.yml
=> Set auto complete to off in insertion PRs to vs-green

eng/pipelines/official.yml
Which contains fix for dotnet test failing with CodeQL
The only way we will know it works is when it is merged to main and CodeQL creates new database next time. (Occurs every few days)
=> Manually upgrade the CodeQL CLI version

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/es/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/it/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ko/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pl/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pt-BR/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ru/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hans/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSPackage.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230628212633867 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230628212633867 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSPackage.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230630213928030 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230630213928030 to main

eng/pipelines/official.yml
The name of variable to disable nuget multifeed warning was changed so we use new name now.
=> Disable nuget multifeed warning

Directory.Packages.props, eng/tools/OneLocBuildSetup/Arguments.cs, eng/tools/OneLocBuildSetup/LocProject.cs, eng/tools/OneLocBuildSetup/OneLocBuildSetup.csproj, eng/tools/OneLocBuildSetup/Program.cs
Our localization project which generates xlf & locproject file. This project is not part of our main solution. This PR makes sure that this project also uses nuget central package management. (Existence of file in root, makes build to fail if any project is not on CPM).
Also fix few warning in the project.
=> Update localization project

eng/imports/RepoLayout.props, setup/Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles/CommonFiles.swr, setup/Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles/Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.swixproj, setup/ProjectSystemSetup/ProjectSystemSetup.csproj, setup/ProjectSystemSetup/UnifiedSettings/ManagedProjectSystem.registration.json, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSPackage.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.zh-Hant.xlf, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Setup/PackageContentTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Setup/SwrTests.cs
This reverts commit 2eca63192ccf7467fd866b23cdcc7557155612cf.
=> Re-add unified settings (revert commit reverting it before 17.7 snap)

eng/pipelines/pull-request.yml
=> Run PR build for each PR

.github/fabricbot.json
Adds rules for 17.5 and 17.7, and updates PRs merged to main to be given milestone 17.8.
=> Update fabricbot config for newer branches

ProjectSystem.sln
This enables Find in Files to find package versions, and makes editing them easier in VS.
=> Add Directory.Packages.props to solution

version.json
=> Update version to 17.8

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
This is a recreation of https://github.com/dotnet/project-system/pull/9167 which I accidentally set to target `main` instead of `dev17.7.x`.
---
In some cases (such as when FUTDC logging is enabled) we run a validation pass to report to the user when their projects appear out of date despite just having been built. This feature alerts users to overbuild and provides useful diagnostic information to correct it.
#9130 fixed a bug related to F5 builds. It introduced a race condition that can lead to the error reported in #9152.
Our `CurrentSolutionBuildContext` value is set when the SBM starts the solution build, and cleared to `null` when it completes.
Our validation logic runs async, and can complete after the SBM completes. In such cases, it can observe a null …
=> [17.7] Avoid bug during FUTDC validation after solution build completes

src/Microsoft.VisualStudio.ProjectSystem.Managed/Text/IncrementalHasher.cs
This method is vectorized, which will give better performance than the hand written loop we had previously.
=> Use SequenceEqual to compare byte arrays

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/es/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/it/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ko/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pl/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pt-BR/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ru/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hans/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230719212607455 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230719212607455 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/cs/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/de/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/es/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/fr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/it/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ja/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ko/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pl/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pt-BR/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ru/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/tr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hans/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hant/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230726213655354 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230726213655354 to main

src/Microsoft.VisualStudio.Editors/AttributeEditor/PermissionSetService.vb
This diagnostic was causing command line builds to fail. For some reason this was not the case in CI or VS builds.
=> Fix CA1822 diagnostics about making methods static

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230728212701029 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230728212701029 to main

eng/pipelines/configuration/TSAConfig.gdntsa, eng/pipelines/official.yml
Related to [AB#1852100](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1852100).
Update our TSA configuration (TSAConfig.gdntsa) per the information in https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/3212/TSA-Onboarding. Also enable TSA reporting of CodeQL issues.
=> Update TSA options

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230731212606581 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230731212606581 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Acquisition/MissingSetupComponentRegistrationService.cs
There will be corresponding PR in VS to light this up.
=> Add net8.0 as a component for IPA

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.VisualBasic.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/BuildPropertyPage.VisualBasic.xaml.xlf.lcl
- OptionCompare
- OptionExplicit
- OptionInfer
- OptionStrict
This replaces on/off/text/binary keywords according to bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1817057/
=> Replace keyword translations in four properties:

src/Microsoft.VisualStudio.Editors/PropPages/xlf/cs/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/de/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/es/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/fr/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/it/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ja/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ko/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/pl/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/pt-BR/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/ru/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/tr/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/zh-Hans/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.Editors/PropPages/xlf/zh-Hant/BuildPropPage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/de/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/fr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/it/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ja/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pl/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pt-BR/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ru/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/tr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hant/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230807221800864 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230807221800864 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs
Fixes [AB#1833295](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1833295)
Fixes #9220
The dependencies tree code uses CPS's "slice" concept to access project data across all implicitly active configurations. We also use the unconfigured project's `ActiveConfiguredProject` datasource to know which of the current slices is "primary".
We cannot synclink across these two sources of data as we remove all configured-project versions from the per-slice data in order to synclink datasources across those slices. This allows for a situation where the observed primary active project configuration is not present in the set of per-slice data.
Previously this was not believed to be possible, and the code would throw if such a scenario was observed. We see that …
=> Prevent NFE when primary slice unknown

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/cs/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/es/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hans/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230809212429188 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230809212429188 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ko/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230811212733148 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230811212733148 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/es/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/it/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ko/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pl/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pt-BR/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ru/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hans/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230828212644163 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20230828212644163 to main

eng/pipelines/official.yml
Now we have test coverage to verify things work.
=> Set autocomplete for insertion into C# dev kit

eng/pipelines/official.yml
The version in pipeline has been updated
=> Remove work-around for CodeQL issue with dotnet test

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs
=> Avoid delegate and closure allocation

Directory.Packages.props, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/KnownProjectImageMonikers.cs
=> Revert "Add missing image monikers"

setup/ProjectSystemSetup/UnifiedSettings/ManagedProjectSystem.registration.json
done for Josh Stevens - see https://devdiv.visualstudio.com/DevDiv/_git/dotnet-project-system-Trusted/pullrequest/496235
=> Add legacy page ID to sdk-style projeccts

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/BuildPropertyPage.VisualBasic.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20231018212527020 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20231018212527020 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/Handlers/AbstractEvaluationCommandLineHandler.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/Handlers/AbstractEvaluationCommandLineHandlerTests.cs
_This is a cherry-pick of bea583e0b0c072009b27588013b6d8e8ebc7595d for bug [AB#1909792](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1909792)._
This change requires a good bit of background.
The Solution Explorer builds its tree from the evaluation model of the "active" configuration and only the active configuration, and there can only be one active configuration. Items (source files, resource files, etc.) that aren't part of the active configuration won't be displayed.
In MAUI projects, the items under the "Platforms" folder are meant to be platform-specific (by which we really mean target framework-specific), with each relevant platform getting its own subfolder. Items in the "Android" subfolder should not be included in the "iOS" build, for …
=> Handle changes to ExcludeFromCurrentConfigurationProperty

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/BuildPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/BuildPropertyPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20231103212823155 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20231103212823155 to main

src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsDesigner.vb
=> Remove file path from fault data

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/it/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ko/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ReferencesPage.VisualBasic.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ReferencesPage.VisualBasic.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20231116183715033 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20231116183715033 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/es/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pl/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pt-BR/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ru/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hans/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20231115223032282 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20231115223032282 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/BuildPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20231117222630359 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20231117222630359 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSPackage.resx, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.zh-Hant.xlf
Fixes [AB#1949205](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1949205)
- Categories should use title case
- Settings should use sentence case
- Omit the word "settings"
=> Update unified settings strings

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ko/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pl/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pt-BR/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ru/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hans/VSPackage.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20240202222803862 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20240202222803862 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/es/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/it/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSPackage.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20240205222610589 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20240205222610589 to main

docs/dependencies-tree.md, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredProjectsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/LaunchProfiles/LaunchProfileProjectProperties.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencySubscriber.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs
=> Typos and fix IDE suggestions around type name use

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/BuildPropertyPage.VisualBasic.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20240226222656897 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20240226222656897 to main

eng/pipelines/templates/analyze-compliance.yml, eng/pipelines/templates/build-official-release.yml, eng/pipelines/templates/build-pull-request.yml
=> Remove unnecessary task / param, configure MerlinBot

Directory.Packages.props, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/LanguageServiceHost.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/LaunchProfileActionBase.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageDataProducer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfile.cs
=> Update VSThreading packages in anticipation of future Roslyn packages upgrade

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/InterceptedProjectProperties.cs
Traces show this code is contributing a fair amount to CPU during solution load. We should investigate this more deeply to understand if we can reduce how often this is called. For now, we can improve this a little by removing use of immutable dictionary here, as it's not needed.
=> Replace immutable dictionary with mutable dictionary

eng/pipelines/optprof-scheduled.yml
Failure: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9391209&view=results
Based on how MSBuild has fixed their pipeline issue: https://github.com/dotnet/msbuild/pull/9969/files
=> Update OutProf to fix pipeline failure.

.editorconfig, tests/Common/ThrowingTraceListener.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/ComponentVerificationTests.cs
I turned on solution-wide analysis and these appeared in the error list.
=> Fix some warnings in the IDE

eng/pipelines/optprof-scheduled.yml
Bringing this change to 17.9.
Change in main has been merged here: https://github.com/dotnet/project-system/pull/9444
=> Update resource pipeline name.

src/Microsoft.VisualStudio.ProjectSystem.Managed/Collections/DictionaryEqualityComparer.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/GeneratePackageOnBuildDesignTimeBuildPropertyProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/GeneratePackageOnBuildPropertyProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/StartupProjectSingleTargetGlobalBuildPropertyProvider.cs
=> Minor documentation fixes

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/es/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/it/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ko/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ru/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hans/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20240503212730819 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20240503212730819 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pl/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pt-BR/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSResources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20240506212743531 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20240506212743531 to main

src/Microsoft.VisualStudio.Editors/xlf/cs/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.Editors/xlf/de/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.Editors/xlf/es/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.Editors/xlf/fr/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.Editors/xlf/it/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.Editors/xlf/ja/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.Editors/xlf/ko/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.Editors/xlf/pl/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.Editors/xlf/pt-BR/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.Editors/xlf/ru/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.Editors/xlf/zh-Hans/VSPackage.xlf.lcl, src/Microsoft.VisualStudio.Editors/xlf/zh-Hant/VSPackage.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20240607212754770 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20240607212754770 to main

src/Microsoft.VisualStudio.Editors/xlf/tr/VSPackage.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20240610213521710 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20240610213521710 to main

eng/pipelines/templates/build-official-release.yml
=> Increase drop retention days

version.json
=> Update version to 17.12

Directory.Packages.props
via https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2134950/?view=edit
=> Bump Microsoft.IO.Redist package version

.editorconfig, .gitattributes
https://github.com/VerifyTests/Verify?tab=readme-ov-file#text-file-settings
=> make verified files as lf and utf8

Directory.Packages.props, eng/imports/HostAgnostic.props, src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.csproj
[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9928834&view=logs&j=3de96e8d-b8d1-5108-47b8-f6a54739db67&t=231d26a0-c7d2-5657-57ee-d8a355d2408a)
For [bug](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2134951/?view=edit) and [bug](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2134950/?view=edit)
=> Bump System.Formats.Asn1 version and add Microsoft.IO.Redist to HostAgnostic.props

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.VisualBasic.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.zh-Hant.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf
For [Task](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2060489)
This new property only applies to project that target .NET framework ad have an executable output. 
This is what the UI looks like, let me know if there is a better fitting description.
=> Add PreferNativeArm64 property

eng/pipelines/official.yml, eng/pipelines/templates/build-official-release.yml
=> Avoid codesign validation bootstrapper

eng/pipelines/templates/analyze-compliance.yml
=> Use cloud symbol server for API Scan

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
See: https://github.com/NuGet/Home/issues/13700. 
Relevant for falling back to the old restore dependency resolver. 
cc @jeffkl
=> Add RestoreUseLegacyDependencyResolver to nomination

CONTRIBUTING.md
The link was dead. I don't think this model is being created anymore.
=> Remove IntelliCode section

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20240927212727752 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20240927212727752 to main

Directory.Packages.props, eng/imports/Versions.props
=> Upgrade CPS and related package versions

version.json
=> Bump version to 17.13

eng/imports/Versions.props
=> Bump CPS package version

Directory.Packages.props
=> Upgrade most of VS related packages to their latest version

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Setup/SetupComponentProvider.cs
Two recent PRs merged and caused a simple build break, which is fixed here.
- https://github.com/dotnet/project-system/pull/9561
- https://github.com/dotnet/project-system/pull/9552
=> Fix compile error in main

src/Microsoft.VisualStudio.ProjectSystem.Managed/StringComparers.cs
=> Remove unused string comparers

Directory.Packages.props, eng/imports/VisualStudio.props
fix https://devdiv.visualstudio.com/DevDiv/_componentGovernance/112417/alert/10373789?typeId=12707329
=> Update MessagePack version to 2.5.187

src/Microsoft.VisualStudio.Editors/MyApplication/MyApplicationDataSerializer.vb
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2293692
=> Fix incorrect property name typo

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/es/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/it/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ru/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSResources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20241113223414592 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20241113223414592 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ko/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pl/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pt-BR/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hans/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20241115223500242 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20241115223500242 to main

eng/imports/HostAgnostic.props, eng/imports/VisualStudio.props
=> pin MessagePack in HostAgnostic.props

Directory.Packages.props, eng/imports/HostAgnostic.props
Fixes [2298321](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2298321/?view=edit)
[Pipeline Component Governance Passing] (https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10602694&view=logs&j=3de96e8d-b8d1-5108-47b8-f6a54739db67&t=231d26a0-c7d2-5657-57ee-d8a355d2408a)
=> bump system.text.json version

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
Related to https://github.com/NuGet/NuGet.Client/pull/6210. 
We need it in combination with SdkAnalysisLevel.
=> Add NetCoreSdkVersion to nomination

version.json
=> Bump version to 17.14

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/DesignTimeBuilds/DesignTimeBuildLoggerProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
Two fixes for 17.13 to take to the QB.
Includes:
- #9627 
- #9633
=> 17.13 fixes

.github/policies/resourceManagement.yml
Updates automation following the creation of the `dev17.13.x` branch. `main` is now targeting 17.14. Also fix a typo in a previous entry.
=> Update automation for latest PR versions

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckImplicitConfiguredInput.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2434021
In https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/587251, CPS made a change to deduplicate items from different rules mapping to the same item type. This inadvertently broke incremental builds for WPF projects, where changes to `.xaml` files (`Page` items) would not cause the project to be considered as needing to build (underbuild) which is very frustrating and confusing for users.
During the investigation of this issue it was discovered the items returned by CPS's `SourceItemsRuleSource` come from both the `File` and `Project` catalogs. Historically the FUTDC has only checked the `File` catalog for these items. When CPS introduced deduplication in that PR, the `Page` rule for WPF projects became present in …
=> FUTDC finds source items in both File and Project schema

.github/policies/resourceManagement.yml
Merged PRs should target 17.15, not 17.14.
=> Update milestone on merged PRs

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/es/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/it/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ko/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pl/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pt-BR/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ru/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hans/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/cs/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/de/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/es/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/fr/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/it/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ja/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ko/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pl/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/pt-BR/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ru/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/tr/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hans/ApplicationPropertyPage.xaml.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/zh-Hant/ApplicationPropertyPage.xaml.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20250611212721236 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20250611212721236 to main

global.json
=> Bump SDK version to 9.0.107

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Shipped.txt, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
Fix some minor compilation warnings that snuck in recently.
=> Fix compile warnings

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/cs/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/de/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/es/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/fr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/it/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ja/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ko/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pl/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/pt-BR/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/ru/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/tr/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hans/Resources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/zh-Hant/Resources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20250625212200673 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20250625212200673 to main

Directory.Packages.props, docs/hot-reload-architecture.md, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/ISolutionBuildManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/SolutionBuildManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadBuildManager.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UnconfiguredProjectVsServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfileExtensions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/HotReload/IProjectHotReloadSessionInternal.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/HotReload/ProjectHotReloadSession.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IUnconfiguredProjectCommonServices.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UnconfiguredProjectCommonServices.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectHotReloadSessionManagerFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectThreadingServiceFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchProfileExtensionsTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IUnconfiguredProjectVsServicesFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Build/SolutionBuildManagerTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectLaunchTargetsProviderTests.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/HotReload/ProjectHotReloadBuildManagerTests.cs
https://github.com/microsoft/vscode-dotnettools/issues/2133
=> Update debug package and implement IManagedHotReloadAgent5

eng/pipelines/templates/build-official-release.yml
For new PME enforcement signing requirements.
=> Update signing to use signWithProd: true

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.CSharp.DesignTime.targets
Part of https://github.com/dotnet/razor/issues/11834
=> Allow Razor cohosting to work with non-Razor SDK projects

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.CSharp.DesignTime.targets
Reverts https://github.com/dotnet/project-system/pull/9733
Due to performance regression: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2560715
=> [dev18.0.x] Revert "Merge pull request #9733 from davidwengier/RazorForNonRazorSdk"

nuget.config
=> Add URL for package web UI to NuGet.config file

eng/pipelines/templates/build-official-release.yml
=> Change channel name for VS Bootstrapper build

.github/policies/resourceManagement.yml
Updated milestone tracking for Pull Requests and adjusted auto-merge conditions.
#9783
=> Updated milestone tracking for Pull Requests to 18.1

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/es/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/it/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ko/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pl/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pt-BR/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ru/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hans/VSResources.xlf.lcl, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl
LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20250926212843737 to main with localized lcls
=> LEGO: Pull request from lego/hb_2e0ba28b-e52b-4d33-9068-18489e7532e9_20250926212843737 to main

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/FeatureFlagNames.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectSystemOptions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/HotReload/ProjectHotReloadAgent.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/HotReload/ProjectHotReloadSession.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectSystemOptions.cs, tests/Common/Test/App.config, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectHotReloadSessionWebAssemblyCallbackFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectSystemOptionsFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/TestBrowserRefreshServerAccessor.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/HotReload/ProjectHotReloadSessionTests.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2571149
=> Do not set IsDebuggedProcess for legacy WASM debugger

eng/pipelines/templates/publish-symbols.yml
Per guidance at: https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/49030/Migrating-Managed-Identities-to-WIF-Service-Connections?anchor=microbuild-symbols-archive-task
=> Bump MicroBuildArchiveSymbols task in pipeline

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/FeatureFlagNames.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectSystemOptions.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/HotReload/ProjectHotReloadAgent.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/HotReload/ProjectHotReloadSession.cs, src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectSystemOptions.cs, tests/Common/Test/App.config, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectHotReloadSessionWebAssemblyCallbackFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectSystemOptionsFactory.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/TestBrowserRefreshServerAccessor.cs, tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/HotReload/ProjectHotReloadSessionTests.cs
=> Do not set IsDebuggedProcess for legacy WASM debugger (#9804)
