dotnet/project-system

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/EnvironmentHelper.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/IEnvironmentHelper.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IEnvironmentHelperFactory.cs

- `IEnvironmentHelper.GetEnvironmentVariable` can return `null`
- `IEnvironmentHelper.Is64BitOperatingSystem` is unused

Update environment helper

---

build/import/Packages.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/AbstractProjectState.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/CategoryByIdDataProducer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageByIdDataProducer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/QueryProjectPropertiesContext.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyByIdProducer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyEditorByIdDataProducer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/QueryDataByIdProducerBase.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/PropertiesAvailableStatusFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/CategoryDataProducerTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducerTests.cs

Part of #7251. Alternative to #7266.
In order to show/hide properties based on project-level metadata such as `TargetPlatformIdentifier` or `LangVersion`, we need to plumb that data through to the UI for use in visibility condition expressions. Our approach for this is to have non-visible properties in the UI whose data is available to the visibility condition evaluator.
CPS PR https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/325905 added an `IsVisible` property to the Project Query API's project model.
This PR populates that property when queried.
It also changes the query provider to return non-visible properties.
Future work will be to add non-visible properties (probably in a new well-known `ConfigurationGeneralPropertyPage.xaml` in which all properties are non-visible), …

Populate IsVisible and return non-visible properties

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/cs/VSResources.xlf.lcl
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/de/VSResources.xlf.lcl
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/es/VSResources.xlf.lcl
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/fr/VSResources.xlf.lcl
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/it/VSResources.xlf.lcl
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ja/VSResources.xlf.lcl
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ko/VSResources.xlf.lcl
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pl/VSResources.xlf.lcl
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/pt-BR/VSResources.xlf.lcl
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/ru/VSResources.xlf.lcl
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/tr/VSResources.xlf.lcl
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hans/VSResources.xlf.lcl
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/zh-Hant/VSResources.xlf.lcl
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml

When a customer clicks a link to documentation, they expect to see it in their own language (where applicable).
This commit removes the assumption on en-US culture from the URLs we allow customers to navigate to.
More information at https://review.docs.microsoft.com/help/contribute/links-how-to?branch=master#locale-codes-in-external-links

Don't assume en-US culture for customer-facing URLs

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml

Relates to https://github.com/dotnet/project-system/issues/7251
Items backed by a visibility condition have non-visible UI elements allocated to them. Setting `Visible="False"` makes them permanently non-visible, which is more optimal.

Use Visible property over visibility condition

---

setup/ProjectSystemSetup/source.extension.vsixmanifest

VS no longer ships .NET Framework 4.6. We require 4.7.2.

Bump requires .NET Framework to 4.7.2

---

src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerWindowPane.vb

Fixes: https://github.com/dotnet/project-system/issues/7267
With the change to 64-bit, it seems this `WParam` value can be above Int32 now. Good news is that `Keys.KeyCode` is an enum set to `65535` in *System.Windows.Forms*, so that isn't changing... ever. Therefore, doing a *binary-and* against `65535` means the value will always be equal to or below `65535`, well within the range of Int32. Here, I just *binary-and* the Int64 with the enum, and do `CInt` so that the cast to `Keys` is aware the value produced an Int32. This no longer causes the System.OverflowException to occur.

Fixes System.OverflowException being thrown from old csproj.dll-based property pages

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml

Contributes to #6989.
Nullable reference types were introduced in C# 8.
This change uses a newly introduced visibility condition function to hide the `Nullable` property from the UI when `LangVersion` is less than 8.0.

Restrict 'Nullable' property to C# 8+

---

build/import/Packages.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextProvider.ProjectContextInitData.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextProvider.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IWorkspaceProjectContextFactoryFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextProviderTests.cs

Discussed via email.
Roslyn would benefit from knowing the project's evaluated `AssemblyName` property. This change provides it.

Pass evaluated AssemblyName during Roslyn workspace construction

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hant.xlf

Fixes #7239. Contributes to #7279.
The `UseWindowsForms` and `UseWPF` properties are only applicable when targeting .NET Core 3.0 or later.
Until recently, we did not have a means to express a visibility condition based upon target framework.
Now that we have one, we can add these properties to the UI and have them behave correctly.
cc @RussKie

Add UseWindowsForms and UseWPF properties

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml

Fixes #7227.
We want to show the new platform properties on .NET 5 (or greater) projects, which can be easily achieved with the conditional visibility metadata.

Condition platform properties to .NET 5 or greater.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hant.xlf

Fixes #5940.
On .NET Framework projects, a user will now be able to enable or disable automatic binding redirection by setting the `AutoGenerateBindingRedirects` property in the Project Propeties UI.

Introduce AutoGenerateBindingRedirects property.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/PackagePropertyPage.xaml

Fixes #7262.
I went through our rule files to 
1. Create a fwlink URL if needed.
2. Verify that the URL doesn't reference a particular cutlure (i.e. `en-us`) in our link manager website.

Create fwlink URLs for properties with HelpUrls.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf

The description of a bool property is displayed as the label of a check box.
The majority of properties we specify use a directive form.
This updates remaining bool properties to use directive forms. It also shortens some descriptions to make them more concise.
---
Examples of this form:

Use directive description for bool properties

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfileExtensions.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/LaunchProfiles/ProjectLaunchProfileExtensionValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ProjectDebugPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/LaunchProfiles/ProjectLaunchProfileExtensionValueProviderTests.cs

In general we expect Hot Reload to be enabled by default for projects using the "Project" launch command, but there may be situations where users would like to turn it off. This change includes the following:
1. Defines the `hotReloadEnabled` value that will be stored in a launch profile in the launchSettings.json file.
2. Updates the `ProjectLaunchProfileExtensionValueProvider`, responsible for exposing settings in `ILaunchProfile.OtherSettings` to the CPS properties system, to expose that value as the `HotReloadEnabled` property. If not defined in the launch profile, the value defaults to "true".
3. Updates the ProjectDebugPropertyPage.xaml to include a checkbox surfacing the value to the user.

Add Hot Reload UI

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/DebugPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.zh-Hant.xlf

This makes it easier for people to find the new Launch Profile UI when searching for common launch profile operations in the Project Property UI.

Add more search aliases to the debug property

---

docs/repo/property-pages/property-specification.md
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyEditorDataProducer.cs

Fixes #7331
`StringProperty` may specify a `SubType`, which modifies how it is displayed in the UI. It turns out that rule files commonly use both `path` and `directory`, and these appear to be equivalent in semantics.
This is the root cause of the failure to show a "browse" button alongside the "working directory" property's editor.
Previously a value of `folder` would be ignored. This commit makes it equivalent to `directory`.

Treat 'folder' as an alias of 'directory'

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectLaunchTargetsProviderTests.cs

Currently, `ProjectLaunchTargetsProvider.CanBeStartupProjectAsync` works by querying for the set of debug settings as though we were, in fact, about to start the project. If we can create the debug settings the project is startable, but if we get back `null` the project is not.
This is very straightforward, but there are downside. First, we end up doing a fair bit of work figuring out the debug settings, and most of those settings have no impact on whether or not the project is startable. Second, this approach obscures our intent. That is, you should be able to read the code and figure out when we _intend_ a project to be startable. Right now that isn't possible.
Supporting Hot Reload on Ctrl+F5 requires that we do even more work to setup debug settings and prepare other parts of the Hot …

Simplify CanBeStartupProjectAsync

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/LanguageServiceErrorListProvider.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Build/LanguageServiceErrorListProviderTests.cs

In d17, we will be starting an experiment to switch away from direct Roslyn integration with the error list / tagger and over to an LSP based implementation.  In the new LSP based implementation, Roslyn will no longer be publishing build diagnostics and instead they will be published by CPS.  Once the feature flag fully roles out, this provider can be deleted.
To allow the CPS IVsErrorListProvider to take over, we check the appropriate feature flag and return NotHandled (as the CPS provider has Order(1) but this provider has Order(10)).
I considered implementing the check in roslyn, but there is no way to report NotHandled via the IVsLanguageServiceBuildErrorReporter2 interface.

Add feature flag to disable sending build diagnostics to roslyn when the new LSP pull diagnostics system is enabled

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/IDebugProfileLaunchTargetsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/IDebugProfileLaunchTargetsProvider4.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Unshipped.txt

Currently, the `LaunchProfilesDebugLaunchProvider` calls `IDebugProfileLaunchTargetsProvider.OnBeforeLaunchAsync` right before launching processes, and `IDebugProfileLaunchTargetsProvider.OnAfterLaunchAsync` right after. The idea is that, in addition to creating the launch settings for the processes, the launch targets provider may want to do something special right before or right after processes launch like turn on some logging or show some UI.
There is some information available that isn't currently passed to the launch targets provider. One is the set of `IDebugLaunchSettings` objects that is actually going to be passed to CPS (and then on to the debugger) to start the processes, and the other is the set of `VsDebugTargetProcessInfo`s providing info about the started processes. We're …

Expose process information

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/LaunchProfiles/ProjectLaunchProfileExtensionValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ExecutableDebugPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ProjectDebugPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hant.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/LaunchProfiles/ProjectLaunchProfileExtensionValueProviderTests.cs

Fixes #7333.
Update the ProjectDebugPropertyPage.xaml and ExecutableDebugPropertyPage.xaml to support WebView2 debugging. This is present in the legacy property pages but had not yet been implemented in the new Launch Profiles UI.
Screenshot:

Support WebView2 debugging

---

build/import/Packages.targets
build/import/VisualStudio.props
src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextProvider.ProjectContextInitData.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextProvider.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IWorkspaceProjectContextFactoryFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextProviderTests.cs

Cherry-pick of #7216 for 16.11.

[16.11] Pass evaluated AssemblyName during Roslyn workspace construction

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf

Fixes: https://github.com/dotnet/project-system/issues/6989
Adds the Prefer32Bit property to the Build property page. This property only applies to .NET framework and executables. Information can be found on either of these pages:
- https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/output#platformtarget
- https://docs.microsoft.com/en-us/dotnet/framework/tools/corflags-exe-corflags-conversion-tool#parameters
- https://dzone.com/articles/what-anycpu-really-means-net
- https://stackoverflow.com/questions/12066638/what-is-the-purpose-of-the-prefer-32-bit-setting-in-visual-studio-and-how-does

Add Prefer32Bit property

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/DefaultLaunchProfileProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/IDefaultLaunchProfileProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Unshipped.txt
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs

As specified in https://github.com/dotnet/project-system/issues/7327, we
need a way to remove de default launch profile for project systems
where it doesn't represent a valid option. This commit adds an extension
point for providing a new provider that lets extensions proide a
different default that will make more sense for their projects, or no
provider at all.

Added new IDefaultLaunchProfileProvider

---

build/ci/official.yml

If we need to update a servicing branch to build using the Scaled Set pools this is the change that needs to be done in this repo.
Additionally you'll have to change the matching release pipeline and add the Publish Symbols stage (look at the release pipeline for main as reference). 
It's *very* important that you make sure the Agent Pool here is set to VSEng-ReleasePool
You will then add the task for MicroBuild Archive Symbols
and you'll also have to add the Project System Symbols variable group

Use Scaled Set Pool in servicing branches

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/TargetPlatformMonikersValueProvider.cs

Fix [AB#1332261](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1332261)
Target Platform Monikers suffix is used primarily in MAUI projects to enable targeting of the the project to different app platforms
and currently there is no provider for this value.
This implementation will intercept the project property  `"TargetPlatformMonikers"` and to a generate a string with all suffixes as requested by the Maui team i.e `vs.solution.project.targetplatformmonikers="ios;android;windows10.0.19041.0"`

Add a project property provider for Target Platform Monikers

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs

When creating the `DebugLaunchSettings` that control how an app starts up, we set the `DebugLaunchOptions.MergeEnvironment` flag to indicate that we want to merge the environment variables in `DebugLaunchSettings.Environment` with whatever environment variables would be inherited from the system and/or VS (as the parent process). If we do not, the set of environment variables in `DebugLaunchSettings.Environment` will instead _replace_ the system/VS environment variables.
However, we only set this flag if at least one environment variable is specified, and we set the flag rather early in the method.
The Hot Reload support adds several environment variables, but that support was added near the _end_ of the method. So in practice, if Hot Reload is enabled the launched app will see _only_ the …

Merge environment variables

---

build/import/Packages.targets

Looks like this happened during a merge.

Remove duplicate PackageReference

---

build/import/Packages.targets
build/import/VisualStudio.props

During work to integrate bits for Dev17, these packages were added to all projects in the solution.
The host-agnostic layer should not take a dependency upon any host-specific (i.e. VS) packages.
This change enforces that layering, so we don't accidentally take a dependency in future that we should not.

Ensure only the VS layer uses VS packages

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/TargetPlatformMonikersValueProvider.cs

This is a code cleanup.
Currently this value is not used, so this change should not affect other teams using it.

Fix  wrong canonicalization for TargetPlatform

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Frameworks/SdkSupportedTargetPlatformIdentifierEnumProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Frameworks/SdkSupportedTargetPlatformVersionEnumProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Frameworks/SupportedTargetFrameworksEnumProvider.cs

This PR renames the classes to match the exported EnumValuesProvider, to improve discoverability. Thanks @drewnoakes for this suggestion (https://github.com/dotnet/project-system/pull/7395#discussion_r668473290).

Improve discoverabililty for EnumProviders.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Frameworks/SupportedTargetFrameworkAliasEnumProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Frameworks/SupportedValuesProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreConfiguredInputDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreUnconfiguredInputDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsChangeTracker.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredProjectsLoader.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DropConfiguredProjectVersionDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckConfiguredInputDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInputDataSource.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ActiveConfiguredProjectsLoaderTests.cs

Fixes #7409
These types derive from `OnceInitializedOnceDisposed` which supports both sync and async disposal. If async disposal is requested, the dispose call is made via `Task.Run`, causing it to occur on a background (thread pool) thread.
Async disposal can free up the UI thread during solution close.
Looking through these usages of synchronous disposal, it seems they can all be made async.
cc @lifengl @davkean for your expertise on whether this may be an unsafe change. I've verified that all these changes result in some actual disposal occurring, and left instances where the dispose operation was a no-op, which will be faster to do sync.

Remove most usages of synchronous disposal

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/RunPostBuildEventValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf

Fixes #7413
The property system does not currently support `IEnumValue.IsDefault`. For now, set the default explicitly via an interceptor so that we don't display an empty drop-down list in the UI.
Also add display strings for enum values so that we don't show untranslated strings in the UI for this property.

Set the default RunPostBuildEvent value via interception

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/LaunchProfiles/LaunchProfileProjectProperties.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ILaunchSettingsProviderFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/LaunchProfiles/LaunchProfilesProjectPropertiesTests.cs

Fixes #7384.
Right now, if you want to create a .xaml file for a particular kind of launch profile you also need to create an implementation of `ILaunchProfileExtensionValueProvider` and/or `IGlobalSettingExtensionValueProvider` to handle reading and writing the property value. Most developers outside of the dotnet/project-system team who need to do this will just store their properties as-is in the `ILaunchProfiles.OtherSettings` dictionary; writing an extension value provider to do this isn't hard but does involve some amount of boilerplate.
Instead, in the absence of an extension value provider for a particular property we should just default reading and writing it to `ILaunchProfile.OtherSettings`. We do need to know the storage type of the property, but this can be determined based …

Support reading and writing properties directly to OtherSettings

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/IProjectHotReloadSession.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/IProjectHotReloadSessionManager.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSession.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManager.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Unshipped.txt
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectHotReloadSessionManagerFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectLaunchTargetsProviderTests.cs

1. Extract the logic for creating and tracking Hot Reload sessions to a new type, `IProjectHotReloadSessionManager`. The `ProjectLaunchTargetsProvider`'s role in Hot Reload to now reduced to requesting that a pending session be created, and informing the manager of when the pending session should be activated. Inside the manager, `HotReloadState` serves as to associate a session with a `Process` and also implements `IProjectHotReloadSessionCallback`. In general it redirects all operations to the manager for actual handling, though.
2. Support multiple sessions. Currently, If a Hot Reload session is active for a project and the user runs the project again with Ctrl+F5 we kill the previous process and session, and then run the new one. This is deviation from the previous (non-Hot-Reload) …

Support multiple Hot Reload sessions

---

build/import/Packages.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/WpfBasedPropertyPage.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UnconfiguredProjectTasksService.cs

The update is needed in order to use the new constructor in `ChainedProjectValueDataSourceBase `that will be used in the implementation of `IVsProjectRestoreInfoSource`.
The two warnings [VSTHRD110 ](https://github.com/microsoft/vs-threading/issues/233) detected were suppressed.

Update cps packages

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs

Fixes #1308
The boolean argument for `validateSettings` controls whether class libraries are considered launchable or not.
The changed invocation here is only used when computing items to appear in the startup project list. When `validateSettings` is `false` (as before) then all projects appear, including class libraries. When `validateSettings` is `true` (as now) then they are excluded.

Class libraries cannot be startup projects

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckHost.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Subscription.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/IUpToDateCheckHost.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInputDataSource.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTestBase.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInputTests.cs

Fixes #6185
We use Dataflow blocks to process project data through various transformations, ultimately producing the data needed for the fast up-to-date check. Dataflow processes data asynchronously, fanned across threads.
Previously the output of the Dataflow "graph" was cached to a field on the subscription type. When a query was made, this field was read. It was possible that the Dataflow graph hadn't finished pushing data through its transformations at the time the query was made, meaning the query's result could be based on old data.
With this change, the fast up-to-date check now ensures that the most recent configured project data has flowed through the graph, so that the answer is always based on the latest data.
One complexity of this change relates to Visual Studio's "command …

Fast up-to-date check uses latest data

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependencyTreeTelemetryService.cs

Fixes #7412 
During shutdown we compute and publish telemetry about project dependencies. Previously this code would run on the UI thread, although that is not necessary.
This change uses the `OnceInitializedOnceDisposed` base class which uses async disposal by default, running that work on the thread pool.

Send telemetry on a thread pool thread

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/DynamicItemHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IApplyChangesToWorkspaceContext.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ISourceItemsHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceContextHandlerType.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.ProjectChange.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IApplyChangesToWorkspaceContextFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/DynamicItemHandlerTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/SourceItemsHandlerTestBase.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextHostInstanceTests.cs

Fixes https://github.com/dotnet/project-system/issues/7411
Fixes https://github.com/dotnet/aspnetcore/issues/34188
This changes the DynamicItemHandler for Razor so that instead of being hardcoded to the `Content` item type, it now uses CPSes SourceItemsService (via an ISourceItemsHandler) so that it can see all items in any type that is considered a source file. Essentially my understanding is that this will now see any file that is in the project tree. This solves various issues from enterprise solutions:
* OrchardCore includes Razor files in the `EmbeddedResource` item type
* Bing has Razor files in the `None` item type (ie, the default from the SDK) and uses custom build targets and tasks to process them at build time
* MAUI uses a custom item type added by `AvailableItemName`
I'm …

Allow Razor files to appear in any source item type

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Logging/BatchLogger.cs

Replace AppendFormat with Append
```
System.AggregateException: Project system data flow 'DataflowBlockSlim (ActionBlockSlimSync`1 : 35808177)' closed because of an exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
at System.Text.StringBuilder.AppendFormat(String format, Object[] args)
at Microsoft.VisualStudio.ProjectSystem.VS.BatchLogger.WriteLine(String text)
at …
```

Fix System.FormatException

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ExternalContracts.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreConfiguredInputDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreDataSource.ProjectRestoreInfoSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreSharedJoinableTaskCollection.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/Snapshots/PackageRestoreConfiguredInput.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/UnconfiguredProjectFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsSolutionRestoreService4Factory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/PackageRestoreConfiguredInputFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PackageRestore/PackageRestoreDataSourceTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PackageRestore/Snapshots/PackageRestoreDataSourceMocked.cs

This pr is a coordinated effort between NuGet and Project-system to [Add a contract for identifying a restore source, to help nuget better batch restores/branch switches](https://github.com/NuGet/Home/issues/10807) to fix #AB1283992
**The problem:**
Current implementation of NuGet Restore has some performance issues.
1) The excessive number of design time builds are largely coming from excessive number of NuGet restoring work. During that time frame, CPU is usage is very heavy, and it gets worse because the power usage throttling and thermal throttling of the laptop kicks in due to the excessive work, which makes it even worse.
2) NuGet uses a simple slide window to group projects for restoring. The time limitation is around 20s. If the gap to provide restore data between two projects are …

Implements IVsProjectRestoreInfoSource

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/PackagePropertyPage/PackageReadmeFileValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/PackagePropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.zh-Hant.xlf

Fixes: https://github.com/dotnet/project-system/issues/6457
Related: https://github.com/dotnet/project-system/pull/7422
This is a quick implementation of the [PackageReadmeFile](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile) property. It is copy-pasted logic from the PackageIcon property that I implemented recently. I'd recommend we extract this logic into some shared code between the 2 providers, but I'll do that in a follow-up PR. For now, this adds the PackageReadmeFile property and the associate None item (and metadata) to the project.
I also did some very minor cleanup to the PackageIcon value provider as I realized I can describe it more accurately and generically at the same time.
The package is loading both PackageReadmeFile and PackageIcon …

Add package readme property

---

docs/repo/up-to-date-check-implementation.md
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckStatePersistence.ConfiguredProjectComparer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckStatePersistence.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.ItemHashing.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/IUpToDateCheckStatePersistence.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInputDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/StringComparers.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

Fixes #6633
Fixes #3826
Previously, the first up-to-date check that runs after a project loads always reports that a build is required. This avoided an uncommon yet serious potential issue.
Consider a project that brings in all `.cs` files via a glob, with the following steps:
1. Load the project
1. Build the project
1. Close the project
1. Delete one of the input `.cs` files from disk
1. Reopen the project
If the fast up-to-date check only considered the timestamps of input and output files, the project would appear up-to-date. However, it is not.
If an item is removed while Visual Studio has the project loaded, the change is observed and handled correctly.
Note that it is also possible to trigger this situation by adding a file, however usually when a file is added its timestamp is …

Fast up-to-date check works on solution open

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs

Fixes #7423
Avoid holding off sending us evaluation results (fast) until the build (slow) results appear.

Remove the build Snapshot service from dataflow related to evaluation.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Subscription.cs

In #7427 we change the fast up-to-date check to make it wait for the latest project data before returning its answer.
This involved a call to `GetLatestVersionAsync`, which is then awaited.
That implementation had a bug that caused a hang while waiting. The up-to-date check is called on the UI thread. It is possible that the dataflow graph, while producing the value we are waiting for, needs access to the UI thread. As we are holding it while waiting, progress cannot be made.
The fix is to "join" the two set of joinable tasks, such that the UI thread is shared between them.

Fix hang during up-to-date check

---

docs/repo/property-pages/property-specification.md
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/PackagePropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.zh-Hant.xlf

Fixes #7420
In https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/341091 we add support for properties to specify specific file extensions to be used as filters in the "open file dialog" we use when clicking "Browse" next to certain file path properties.
This PR adds the metadata to drive that feature, and documents its use for future.

Specify extensions for dialog shown for file properties

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextProvider.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IWorkspaceProjectContextFactoryFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextProviderTests.cs

Fixes: .NET Project System's side of https://github.com/dotnet/project-system/issues/353.
Roslyn already immediately switches to the UI thread CreateProjectContextAsync, so this should be a no-op. However, this enables the above bug to be moved over to Roslyn and for them to remove the UI thread dependency in the future.

Remove unneeded UI thread dependency

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

Having this information available in logs can help when diagnosing issues related to the up-to-date check.

Log item kinds ignored by up-to-date check

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInputDataSource.cs

The FUTD check restores state from disk, and requires the UI thread in order to determine the location of the .vs folder in which the file is stored.
Dataflow blocks do not run their async delegates within JTF, for performance reasons. Most dataflow blocks do not require the UI thread. In this case, because the block can require the UI thread, we must use a JTF.RunAsync call to join that work with the block and its upstream sources.
Without this, a build scheduled soon after project load can cause a hang due to a deadlock for the UI thread.

Fix hang in fast up-to-date check

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs

Fixes #7372.
Before Hot Reload, there was _XAML_ Hot Reload--changes to your .xaml files would immediately be reflected in your process during debugging. We want to enable the same feature during Ctrl+F5 Hot Reload, and to do so we need to set the "ENABLE_XAML_DIAGNOSTICS_SOURCE_INFO" environment variable to "1" to light up the functionality in the running process.

Enable XAML Hot Reload

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/LanguageService.xaml

This fixes part of the issue [AB#1361354](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1361354)
The other part of the fix is in https://github.com/dotnet/roslyn/pull/55244

Pass TargetRefPath to Roslyn language service

---

build/import/Packages.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/IProjectHotReloadSession.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/IProjectHotReloadSessionManager.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSession.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManager.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Unshipped.txt
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectHotReloadSessionManagerFactory.cs

Currently, we only enable Hot Reload in non-debugging (i.e., Ctrl+F5) scenarios, and equivalent functionality is provided by Edit and Continue (EnC) in debugging scenarios. Under the hood, however, EnC and Hot Reload are use mostly the same code paths and are really just two different names for the same feature.
And now that the feature is orthogonal to debugging, we would like to have one way to turn it on that is not tied to whether or not we are debugging the running process. Here we remove the check in `ProjectLaunchTargetsProvider` that limited Hot Reload to Ctrl+F5 scenarios.
However, there are some aspects of Hot Reload that need to understand whether or not the process is running under the debugger, and we are now also responsible for passing that information along. This is …

Enable Hot Reload during debugging

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/FSharp/FSharpProjectSelector.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPropertyPage.cs

https://github.com/dotnet/project-system/pull/7447 opt'd Managed.VS into NGEN image.
Before this change, this dll used to be attempted to be loaded in two ways;
- Load context via the MEF cache
- LoadFrom via the [PackageRegistration] and [ProjectObject]
The latter would actually just respect the existing binary in the Load context resulting in a single load.
After NGEN, however, this changed - a Fusion limitation caused to actually load the IL image in the second step, resulting in two versions of the same assembly loaded.
This change forces the second step to use the Load context.

Opt into Load context binds for package

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/SetAttributeCommand.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/SetTreatAsUsedAttributeCommand.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/UnSetAttributeCommand.cs

This reverts the logic when setting the property TreatAsUsed in csproj

Fix SetAttributeCommand in Remove Unused References

---

setup/ProjectSystemSetup/ProjectSystemSetup.csproj

This reverts commit f3351acbd822c1b852d901e52b657509cf4107b8.
While NGen is the right approach for these assemblies, it regresses performance as we don't currently have OptProf configured.
We will revisit this once we have OptProf configured for our assemblies.

Revert "Opt into NGEN for Managed.dll and Managed.VS.dll"

---

setup/ProjectSystemSetup/ProjectSystemSetup.csproj

This reverts commit 1342777891a0e80c2e401532cf197834df98ce56 and opts project-system into NGEN again. We're going to accept the refset regression due to lack of opt-prof - we've decided the gain outweighs the loss.

Revert "Revert "Opt into NGEN for Managed.dll and Managed.VS.dll""

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ProjectDebugPropertyPage.xaml

Fixes #7474.
The _Enable Hot Reload_ launch profile option will only be displayed for projects having the `SupportsHotReload` project capability defined.

Only show Enable Hot Reload setting when supported

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Content.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/EmbeddedResource.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/None.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.ItemComparer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.ItemHashing.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/ItemRuleTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTestBase.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

Fixes #7276
Source items which participate in `CopyToOutputDirectory` may specify `TargetPath` metadata to control their location relative to the output directory.
Historically, `Link` metadata has been used to control this, and that was supported here. Now, we support both `TargetPath` and `Link`.

Fast up-to-date check supports TargetPath for CopyToOutputDirectory items

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/IProjectLaunchProfileHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/ProjectLaunchProfileHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileByIdDataProducer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileDataProducer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileFromProjectDataProducer.cs

Consolidate most of the interesting code in `LaunchProfileByIdDataProducer`, `LaunchProfileFromProjectDataProducer` and `LaunchProfileDataProducer` into a new type, `ProjectLaunchProfileHandler`.
The first two types do a lot of similar operations to create entities for launch profiles, suggesting that their functionality should be consolidated into the same type. And the third type only exist because similar functionality is split between the other two.
Also, there were a lot of calls to the project's `ExportProvider` to retrieve `UnconfiguredProject`-level services, and any failure to obtain a service was silently ignored. The new `ProjectLaunchProfileHandler` type also exists within the `UnconfiguredProject` scope, allowing us to import them into the constructor and turning any failure …

Consolidate code

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManager.cs

Multiple code paths end up flowing into `ProjectHotReloadSessionManager.StopProjectAsync`. In one scenario, the higher levels of the Hot Reload feature detect that the session and process need to be stopped. For example, a rude edit can lead to stopping the sessions and processes, rebuilding, and re-running with Ctrl+F5. In this case the session and process are both running when `StopProjectAsync` is called.
In another scenario, the process exits and the project system is notified so it can clean up the session. In this case the session is still running when `StopProjectAsync` is called but of course the process is not.
Currently we always try to end the process via `CloseMainWindow` or `Kill`. If the process is already stopped these will throw an `InvalidOperationException` which we …

Check if the process has exited

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ApplicationIconValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml

Fixes: https://github.com/dotnet/project-system/issues/7167
This allows the ApplicationIcon property to function similarly to how it did in the old property pages. How it worked was, if the file was within the project directory structure (project directory and below), it would use a relative path (from the project directory) to that file and set that as the ApplicationIcon's value. If the file was not within the project directory structure, it would copy it to the project directory and then simply have the filename as the path (which is effectively a relative path to the file). This implementation does that same interaction.
One minor difference here is, in the old pages, if the file already existed in the project directory when trying to copy it, it would show this error.
In this …

ApplicationIcon property fix

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs

Currently we enable Hot Reload for both local and remote debugging. While it is not infeasible to make it work for remote debugging, our tooling does not currently support this. I doubt the Hot Reload transport layer currently supports moving the IL and metadata changes to a remote system, but more to the point for this bug we end up setting environment variables on the remote process with file paths that only make sense on the local machine. This causes the remote process to fail immediately as it isn't able to find the relevant file.
The fix here is to disable Hot Reload when remote debugging.

Don't enable Hot Reload when remote debugging

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/LaunchProfileActionBase.cs

Fix a bug where I'm failing to await the result of an asynchronous
operation so the subsequent pattern match will always fail. The end
result is that the update query will not actually be updated with any
new launch profiles.

Fix a silly bug

---

docs/repo/property-pages/how-to-add-a-new-launch-profile-kind.md

Adds steps for using embedded XAML property pages when defining new launch profile types.

Add steps for using embedded XAML property pages

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ProjectDebugPropertyPage.xaml

Follows #7497 where this same check is made in the project launch target provider.

Hide the Hot Reload check box when Remote Debugging is checked

---

src/Microsoft.VisualStudio.AppDesigner/Common/Utils.vb
src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropertyPageSerializationService_Store.vb
src/Microsoft.VisualStudio.Editors/Common/Utils.vb
src/Microsoft.VisualStudio.Editors/DesignerFramework/GenericComponentSerializationStore.vb
src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb
src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceSerializationService_Store.vb

Fixes: https://github.com/dotnet/project-system/issues/7349
Since we don't use BinaryFormatter anymore, the telemetry when we do serialization is no longer needed. This was only added during investigation of BinaryFormatter usage.

Remove BinaryFormatter telemetry

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/BaseProjectConfigurationDimensionProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/IProjectConfigurationDimensionsProviderInternal.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Reload/ProjectReloadInterceptor.cs

Renames the internal configuration dimensions provider to internal to keep the public  interface chain continuous.

Rename IProjectConfigurationDimensionsProvider5 to *Internal

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/CompoundTargetFrameworkValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/DebugTypeValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/RunPostBuildEventValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/TreatWarningsAsErrorsValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/PackagePropertyPage/BaseVersionValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/TargetFrameworkValueProvider.cs

The base methods here just wrap a parameter in a task and return it.
Avoid such allocations by inlining the argument at the call site.

Remove redundant calls to base method

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/ImplicitUsingsValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/TaskResult.cs

Addresses the aspect of #7488 that we will tackle in 17.0.
This adds a single check box that enables/disables this feature.
In future we should add UI to allow modifying the set of usings directly.
We will also need to add logic to support VB separately, as that uses a different property to control this.

Initial support for global implicit usings

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/IDebuggerSettings.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/RegistryBasedDebuggerSettings.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/Interop/IVsShellUtilitiesHelper.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/Interop/VsShellUtilitiesHelper.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/IRegistry.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/WindowsRegistry.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IDebuggerSettingsFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectLaunchTargetsProviderTests.cs

Currently we enable Hot Reload by default for both F5 and Ctrl+F5 scenarios when executing the "Project" launch command, and we support turning it on and off on per launch profile. However, there are also going to be VS-wide settings that we need to honor as well. For F5 scenarios, we should only turn Hot Reload on if Edit and Continue is enabled. For Ctrl+F5 we need to check a new "Hot Reload in Ctrl+F5" setting that is separate from the EnC setting.
The debugger team is adding the underlying options and related UI, but there is currently no API we can call to retrieve the setting (at least, not for the new option). Instead, we need to read the registry values. This involves hiding the registry behind a new interface, `IRegistry`, consuming that in implementations of a new …

Honor VS-wide Hot Reload settings

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProvider.cs

Fixes [VS 1370386](https://devdiv.visualstudio.com/devdiv/_queries/edit/1370386).
Fixes [VS 1386457](https://devdiv.visualstudio.com/devdiv/_queries/edit/1386457).
The `ILaunchSettingsProvider` exposes launch settings as a series of `ILaunchSettings` instances exposed to TPL data flows via the `SourceBlock` property. For convenience, it also exposes the current instance (if any) through the `CurrentSnapshot` property, and supports waiting for the first snapshot to become available via the `WaitForFirstSnapshot` method. `WaitForFirstSnapshot` accepts a timeout in millseconds. If no snapshot becomes available in this time it bails out and returns `null`.
Meanwhile, the `LaunchProfilesDebugLaunchProvider` is responsible for telling CPS if a project can be a startup project. It does this by …

Remove a time out

---

build/import/Packages.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/Web/VersionCompatibilityData.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfileData.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettings.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/WritableLaunchSettings.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IJsonModel.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/AbstractMultiLifetimeComponentTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchProfileDataTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextHostInstanceTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/DebugTests/StartupProjectRegistrarTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/VersionCompatibility/VersionCompatibilityTests.cs

Also fix warnings after updating `Newtonsoft.Json`. Version 13 contains null annotations, which identified a few places where we could have had unexpected null values.

Update CPS package versions

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/Web/RemoteCacheFile.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VersionCompatibility/DotNetCoreProjectCompatibilityDetector.cs

Fixes [AB#1371899](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1371899) where a file read is performed on the UI thread, which can lead to UI delays.
We also avoid reading the file in one scenario, where we only want to verify the existence of the file and would ignore the read contents anyway.
There is also a URL download that has moved from the UI thread to a background thread, however this was an async path so less likely to block.
The file read here is synchronous, so this change will unblock the UI thread while the file is being read. #7549 tracks making this (and other) file IO async, so it won't block thread pool threads either.

Don't perform file access on UI thread

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/DebugPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/DebugPropertyPage.xaml.zh-Hant.xlf

Fixes #7337
This guides users towards additional ways to open the Launch Profiles UI, as going via the Project Properties UI is slower than the alternatives.

Explain alternative gestures to open the Launch Profile UI

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/Web/RemoteCacheFile.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VersionCompatibility/DotNetCoreProjectCompatibilityDetector.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/IFileSystem.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/Win32FileSystem.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PhysicalProjectTreeStorage.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IFileSystemFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IFileSystemMock.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PhysicalProjectTreeStorageTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectLaunchTargetsProviderTests.cs

Contributes to #7549.
Our file system abstraction does not provide asynchronous methods for reading and writing files. We should avoid such synchronous operations and use async ones instead, as file IO tends to be "slow", and blocking threads during IO can prevent other useful work from occurring.
This PR adds new async methods for reading and writing files. It also removes the synchronous read/write methods, along with a bunch of other abstraction methods we do not currently use.

Use asynchronous IO for file reads and writes

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets

This avoids errors about the target GetSuggestedWorkloads not existing in non-SDK projects.
Note: the GetSuggestedWorkloads target is defined in https://github.com/dotnet/sdk/blob/release/6.0.1xx/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.ImportWorkloads.targets

Condition the CollectSuggestedWorkloads target on SDK projects with MissingWorkloadPacks

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs

This constructor was importing `UnconfiguredProject` more than once, which makes no sense. The same object is passed for both arguments. We only need one of them.

Remove duplicate import of configured project

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ConfiguredProjectImplicitActivationTracking.Instance.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ConfiguredProjectImplicitActivationTracking.cs

Fixes #7468
During project load, we have several implicitly activated components (implementations of `IImplicitlyActiveConfigurationComponent`) who may themselves contribute to operation progress. It's important that we give them a chance to do so before operation progress completes.
Previously that was not guaranteed. Our `IProjectDynamicLoadComponent.LoadAsync` method in `ConfiguredProjectImplicitActivationTracking` would indirectly set up a dataflow before completing, but that dataflow would have to pump before the `IImplicitlyActiveConfigurationComponent` instances could be activated. Until those messages arrived, there existed a window during which operation progress could complete before the component (e.g. `PackageRestoreProgressTrackerInstance`) could register its data source with …

Make ConfiguredProjectImplicitActivationTrackingInstance contribute to operation progress

---

build/import/HostAgnostic.props
build/import/Packages.targets
build/import/VisualStudio.props

Code cleanup
NuGet merged `NuGet.SolutionRestoreManager.Interop` into `NuGet.VisualStudio`

Remove unnecessary package

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectFileClassifier.cs

The `ProjectFileClassifier` parses a semicolon-delimited list of paths to NuGet package folders. As we will use these strings in a prefix test to determine whether a file exists within one of these paths, each path must have a trailing slash (directory separator) in order to prevent accidentally matching a file.
This bug is unlikely, but possible. For example, if the path is `A/B/C` then we could match a file `A/B/C.txt`. By ensuring a trailing slash, this can not happen.

Ensure trailing slash in ProjectFileClassifier paths

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs

Fixes #6675
This is a top NFE as reported by CPS.
As discussed in https://github.com/dotnet/project-system/issues/6675#issuecomment-913578589 the imports tree shows project file names as captions in the tree. While there are no duplicate paths, two different paths in a given level of the tree may have the same file name. That is supported on the initial population of the tree, as we also differentiate them by display order. However if these items are reordered, we attempt to update their display orders which can produce a transient state in which duplicates exist, which results in the _The node to add collides with a node already present_ error message we see.
The primary fix here is to look for duplicate file names in any given level of the tree and disambiguate them by including their …

Fix NFE in the imports tree

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VersionCompatibility/DotNetCoreProjectCompatibilityDetector.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/VersionCompatibility/DotNetCoreProjectCompatibilityDetectorTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/VersionCompatibility/TestDotNetCoreProjectCompatibilityDetector.cs

Fixes [AB#1388556](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1388556)
When a solution contains both VC and SDK-style projects, the `DotNetCoreProjectCompatibilityDetector` can unwittingly force VS to fully load projects rather than serve them from the cache.
It does this by retrieving the `UnconfiguredProject` from the `IVsHierarchy`, which internally QIs a `IVsBrowseObjectContext` interface, which loads the project.
We avoid that load by performing a capability query on the project instead.

Don't force load of VC projects

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContext.cs

When the activeTargetFramework is missing in the targetFrameworks array passed to the AggregateCrossTargetProjectContext, it would be helpful to know what the active target framework was when diagnosing this failure.
This would be helpful for failures like [#1398765](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1398765.)

Log the missing activeTargetFramework alias in error message

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs

This will allow external project like WAP to implement this interface and make them visible in the startup project drop-down.
Using `CanLaunchAsync `as a fallback if none of providers implement `IStartupProjectProvider`

Fix WAPPPROJ not in Startup Project

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.FSharp.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.zh-Hant.xlf

```xml
<FSharpPreferNetFrameworkTools>true</FSharpPreferNetFrameworkTools>
<FSharpPrefer64BitTools>true</FSharpPrefer64BitTools>
```
(F# Pull Request: https://github.com/dotnet/fsharp/pull/11998)
@KevinRansom - Please, have a look and let me know if the following look OK (I've used wording you've sent in the e-mail):
```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
<FSharpPreferNetFrameworkTools>true</FSharpPreferNetFrameworkTools>
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
<FSharpPreferNetFrameworkTools>true</FSharpPreferNetFrameworkTools>
```
```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'"> …
```

Added new F# build properties

---

docs/repo/property-pages/how-to-add-a-new-launch-profile-kind.md

Adds a missing step that is required for embedding the xaml rule.

Add MS.VS.ProjectSystem.SDK.Tools step

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManager.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml

In .NET Core startup hooks allow code to run _before_ the application entry point (e.g. `static void Main(...)`) runs. This is used to inject the application-side parts of Hot Reload into the app without requiring changes to the user code or more invasive process control such as that done by the debugger. Startup hooks are turned on by default in the runtime, but as a runtime feature switch then can be turned off.
One case where this happens is if the user turns on trimming. Trimming reduces the size of a self-contained application (one that bundles its own complete copy of the runtime and framework) by stripping out types and methods not used by the application. The actual trimming of an application happens during publishing, not as part of the build, so it generally does not affect …

Check StartupHookSupport

---

docs/up-to-date-check.md

Add a section explaining how to enable logging from the fast up-to-date check in legacy (csproj) projects.
Thanks to @adrianvmsft for help with the `vsregedit` command line.

Document up-to-date logging for legacy projects

---

build/ci/official.yml

The VSEngSS-MicroBuild2019 pool is being phased out in favor of a new pool, VSEngSS-MicroBuild2019-1ES. This should be exactly the same setup, just managed by the 1ES team.
We have until the end of September 2021 to switch over, so if we experience problems with this new pool we can fall back to the old one while they are worked out.

Update build queue

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContext.cs

Contributes to [AB#1378497](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1378497) and [AB#1398765](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1398765).
This adds the set of targetFramework values that are actually present, to help debugging.
Also avoids allocating a message string when no error will be thrown.

Add more information when the activeTargetFramework is not present

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/RenamerProjectTreeActionHandler.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/RenamerTestsBase.cs

Fixes #7610.
Ensure that unloading the project will cancel `PublishLatestSolutionAsync`, preventing a potential hang.

Fix hang in RenamerProjectTreeActionHandler

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManager.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml

Builds on #7604.
Display a message in the Hot Reload output pane when it is disabled because startup hooks are disabled:

Display message about Hot Reload being disabled

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/CodeAnalysisPropertyPage.xaml

Fixes #7535.
Update the last few `HelpUrl`s that need fwlinks.

Add fwlinks

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hant.xlf

Fixes #7517.
To distinguish the "Resources" category on the Application property page from the "Resources" page, we're renaming the former "Win32 Resources". This reflects that it deals with Windows-specific concepts.

Update "Resources" -> "Win32 Resources"

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/IInterceptingPropertyValueProvider.cs

All interfaces used for MEF exports should be annotated with details of their scope, their provider, and their cardinality.
I discovered this was not annotated while investigating something for the Xamarin folks. Will let CI run the unit tests.

Annotate IInterceptingPropertyValueProvider MEF contract

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs

Fixes #7635
Previously we handled the `ProjectUnloading` event, which fired on the UI thread. As called out in #7635, this accounts for 111ms of UI delay when closing Roslyn.sln.
`DependenciesSnapshotProvider` is in the `UnconfiguredProject` scope and will be disposed along with the rest of the project's MEF parts without this special handling. That disposal happens async, on the thread pool.
By removing the `ProjectUnloading` hook, disposal happens a little later, and off the UI thread.

Avoid disposing DependenciesSnapshotProvider on the UI thread

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs

Fixes #7645
This prevents System.ArgumentExceptions when there are duplicate entries in the import list.

Replace Enumerable.ToDictionary in GetCaptionByProjectPath

---

src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsDesignerView.vb
src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsTypeCache.vb

1. Pin configuration type names to the desktop identities so not only we can create necessary configuration sections and serialize data, but also that we can deserialize those as well.
Affected types:
- `System.Configuration.ApplicationSettingsGroup`
- `System.Configuration.ClientSettingsSection`
- `System.Configuration.UserSettingsGroup`
Fixes #6784
Resolves dotnet/winforms#4308
2. Remove ability to browse and serialize arbitrary types, and restrict the set of type to the the known list
Resolves https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1388857/
Manual using a multi-project solution including
- .NET Framework C# 4.0 (Console) and C# 4.7.2 (WinForms), 
- .NET C# (WinForms) 3.1, 5.0, 6.0
- .NET VB (WinForms) 5.0, 6.0
https://user-images.githubusercontent.com/4403806/135218957-a …

Make Settings usable in .NET scenarios

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/PropertyPageDataProducer.cs

Fixes #7627
Some versions of the .NET SDK include a Razor property page that appears in the UI. This page is not intended for display.
We cannot remove this page from existing versions of the SDK, so have to explicitly exclude it from query results so that it doesn't appear in any UI.

Exclude Razor property pages explicitly

---

build/ci/compliance.yml

Update the compliance pipeline to publish the analysis output. This can be helpful in understanding the work items generated by the analysis tools.

Publish analysis artifacts

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/DefaultPlatformPropertyValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/PlatformTargetBuildPropertyPageEnumProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf

Fixes #7521, #7081
Convert PlatformTarget to DynamicEnumProperty and creates an interception to set the default value for _PlatformTarget_.

Convert PlatformTarget to DynamicEnumProperty.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/HotReloadDiagnosticOutputService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/IHotReloadDiagnosticOutputService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSession.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManager.cs

Fixes [AB#1412179](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1412179).
It is possible to run into a deadlock if you start a project with Hot Reload turned on, exit the process, and then quickly start the project again. On a thread pool thread we'll be processing the `Exit` event for the process, and have entered the semaphore that protects our internal Hot Reload state (in `ProjectHotReloadSessionManager`). We then try to write a message to the Output Windows which requires a transition to the UI thread. Meanwhile, on the UI thread we trying to create a new Hot Reload session for the second project start, but to do that we need to enter the semaphore. And there's the deadlock: the main thread is blocked waiting for the semaphore, but the …

Fix a deadlock in Hot Reload

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/HotReloadDiagnosticOutputService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/IHotReloadDiagnosticOutputService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSession.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManager.cs

Fixes [AB#1412179](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1412179).
It is possible to run into a deadlock if you start a project with Hot Reload turned on, exit the process, and then quickly start the project again. On a thread pool thread we'll be processing the `Exit` event for the process, and have entered the semaphore that protects our internal Hot Reload state (in `ProjectHotReloadSessionManager`). We then try to write a message to the Output Windows which requires a transition to the UI thread. Meanwhile, on the UI thread we trying to create a new Hot Reload session for the second project start, but to do that we need to enter the semaphore. And there's the deadlock: the main thread is blocked waiting for the semaphore, but the …

Fix Hot Reload deadlock (Dev17.0)

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/HotReloadDiagnosticOutputService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/Interop/IVsOutputWindowPaneExtensions.cs

In code review for #7681, it was suggested to change from `OutputString` to `OutputStringNoPump`. My testing of that change only involved a single project, so the message printed was the last in the Output Window. However the no-pump version of this method does not include a trailing newline character, meaning that had there been another log message, it would have commenced on the same line that the incremental build failure warning finished on.
The change here makes our `OutputStringNoPump` extension method behave identically to `OutputString` in terms of what it writes to the output pane.
The bug being fixed here manifested in `IncrementalBuildFailureOutputWindowReporter`, which is not present in this diff:
https://github.com/dotnet/project-system/blob/04474df00ebd742e05d31f8e487d6ed4ac8 …

Fix missing newline in output window

---

build/ci/integration-tests.yml

Related: https://github.com/dotnet/roslyn-tools/pull/1116
We have to do these manually when the pool is changed so that the history has the right information about the pool name. ☹
After this is merged, I can re-enable auto-merging. I also fixed the casing on the one image name to match the others. Otherwise, no code changes.

17.0 manual merge to main

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Workloads/MissingWorkloadDetector.cs

Minor cleanup inspired by @MiYanni's point about random files in the top level ProjectSystem folder

Move the MissingWorkloadDetector into the Workloads folder

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInputDataSource.cs

The change in #7687 optimised the fast up-to-date check in the case that the check is disabled, but introduced a logic bug. When disabled, the state hash will be null. Here we convert the assertion to a check, to allow for that case.

Fix exception when fast up-to-date check is disabled

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/CodeAnalysisPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.zh-Hant.xlf

see related PR here: https://github.com/dotnet/msbuild/pull/6996
cc: @mavasani

update property page enum values to match msbuild xsd

---

build/import/Packages.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs

Contributes to [AB#1370097](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1370097).
Replaces #7506.
The previous `EndBatch` method internally uses blocking locks to protect access to its solution-level workspace data. When opening a solution with many projects, each project make requests to update workspaces. Those updates pass through this interface so that we can serialize them in order to reduce blocking lock contention on the thread pool from concurrent update requests.
Using the `EndBatchAsync` allows calling threadpool threads to make progress on other useful work while waiting for this shared resource.

Use asynchronous batch disposal

---

build/import/Packages.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs

Reverts dotnet/project-system#7713
The Roslyn side of this does not actually appear to have been inserted. I am seeing:
```
System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask Microsoft.VisualStudio.LanguageServices.ProjectSystem.IWorkspaceProjectContext.EndBatchAsync()'.
at Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.<ApplyProjectChangesUnderLockAsync>d__24.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.ApplyProjectChangesUnderLockAsync(ProjectChange change, WorkspaceContextHandlerType …
```

Revert "Use asynchronous batch disposal"

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureDetector.IProjectChecker.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureDetector.ProjectChecker.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureDetector.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/IBuildUpToDateCheckValidator.cs

Fixes #7746 
The previous code was incorrectly identifying the build type, then not conditioning behaviour on the value anyway. This fixes the check and ensures we don't run the check when performing a clean.

Don't detect incremental build failure on clean 

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureDetector.ProjectChecker.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs

In #7749 a `NullReferenceException` was fixed by checking for a null export.
A better solution is to filter the calling MEF component such that it is not created for projects that do not themselves have the .NET Project System's up-to-date check. This is more idiomatic, and avoids a small allocation for each project to which the check does not apply.
Includes #7750 so only review 302c821b58d11c86023ae71a1906edf22d184d52.

Use capabilities to filter exports

---

build/import/Packages.targets

We see intermittent `AccessViolationException`s during CI builds on stacks related to Moq codegen.
For example:
```
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at System.Reflection.Internal.MemoryBlock.PeekCompressedInteger(Int32 offset, Int32& numberOfBytesRead)
at System.Reflection.Metadata.BlobReader.ReadCompressedIntegerOrInvalid()
at System.Reflection.Metadata.Ecma335.BlobHeap.GetDocumentName(DocumentNameBlobHandle handle)
at System.Diagnostics.StackTraceSymbols.GetSourceLineInfoWithoutCasAssert(String assemblyPath, IntPtr loadedPeAddress, Int32 loadedPeSize, IntPtr inMemoryPdbAddress, Int32 inMemoryPdbSize, Int32 methodToken, Int32 ilOffset, String& sourceFile, Int32& sourceLine, Int32& …
```

Update moq package to 4.16.1

---

NuGet.config
build/import/Packages.targets

This makes all our feeds come from blessed internal sources, which resolves the Azure Artifacts Configuration Check as described in https://docs.opensource.microsoft.com/tools/nuget_security_analysis/azure_artifacts_checks/

Remove unused "external" feeds

---

src/Directory.Build.targets

Added an after-build target to flush the Unshipped API contents into Shipped. This applies to projects in the `src` directory. This means we no longer need to manually flush these files.
Originally, I wanted to deleted the `PublicAPI.Unshipped.txt` file. Unfortunately, the analyzer (PublicApiAnalyzers) requires the file to be there:
```
1>------ Rebuild All started: Project: Microsoft.VisualStudio.ProjectSystem.Managed, Configuration: Debug Any CPU ------
1>CSC : warning AD0001: Analyzer 'Microsoft.CodeAnalysis.PublicApiAnalyzers.DeclarePublicApiAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
1>CSC : error CS2001: Source file 'C:\Code\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\Pu …
```

Flush Unshipped API contents into Shipped on build

---

docs/repo/property-pages/how-to-add-a-new-launch-profile-kind.md
docs/repo/property-pages/how-to-add-a-new-project-property-page.md

Update our property page and launch profile documentation to explain how to use `IRuleObjectProvider` to define `Rule`s in code.

Update property page documentation

---

docs/repo/property-pages/README.md
docs/repo/property-pages/ui-architecture.md

These features are now available in public builds, so this comment is no longer helpful.

Remove "under development" references from docs

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ImmutableCollectionLinqExtensions.cs

This method is provided by the `ImmutableArrayExtensions` class in the immutable collections library itself. We don't need to duplicate it here.

Remove unused extension method

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

The fast up-to-date check's "Minimal" log level is a good default for everyday development for those developers who like to keep an eye on their build to ensure things are working as expected.
This change includes the item type in several failure messages.
Before:
> Input 'path/to/input' is newer (23/11/2021 14:02:21) than earliest output 'path/to/output' (23/11/2021 14:01:41), not up to date.
After:
> Input **Compile item** 'path/to/input' is newer (23/11/2021 14:02:21) than earliest output 'path/to/output' (23/11/2021 14:01:41), not up to date.
This will allow extracting more information from build output in customer reports.

Log item type in FU2D minimal message

---

build/ci/official.yml

Move our 16.11.x builds to the proper build pool; the one we're using is
being retired.

Move to new build pool

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/DependenciesTreeSearchProvider.cs

For 17.1 Preview 2, I've implemented the ability to delay instantiation of solution explorer search providers based on project capabilities or UI context.
Similar functionality already existed for attached collection source providers (which you already take advantage of), and it is now available for search providers.
So with this change here, if you load a solution that has no project with DependenciesTree capability, when you do a search in solution explorer we will not instantiate this provider, which means we avoid loading the managed project system assemblies.
Comparison of loaded assemblies after doing a solution explorer search of a solution with a python project:
Before this change:
After this change:

Add AppliesToProject attribute to DependenciesTreeSearchProvider

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreDataSource.ProjectRestoreInfoSource.cs

The previous code would lose the original stack trace, making it harder to debug the root cause of any exception raised in this code path.

Don't rethrow exception

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets

Fixes #6758
SDK-style console app projects that target .NET Framework create `bin\Debug\net48\MyApp.exe.config` (for example) even when no input `App.config` file exists. If we create an `UpToDateCheckBuilt` item that has empty `Original` metadata, the up-to-date check assumes that every build will produce this file, which is not the case. When the `Original` metadata is present, the up-to-date check assumes the file is copied, and so won't continue scheduling builds. However with empty `Original` metadata, we assume it's produced on every build.
The fix is to exclude this item when the `AppConfig` value (which would populate the `Original` metadata) is empty.

Prevent overbuild for .NET Framework console apps

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IVsService`1.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IVsService`2.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsService`1.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsService`2.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/Interop/IVsShellUtilitiesHelper.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/Interop/VsShellUtilitiesHelper.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IVsServiceFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/DebugTests/StartupProjectRegistrarTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/VsServiceTests.cs

This reverts commit 5370595a5e5df3ca9c6e9e7e25ff776660190534 from #7808.
Moving to the platform's implementation of `IVsService<>` caused the issue reported in [AB#1448794](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1448794).
We will temporarily reverts the change. We will reinstate that once safe to do so.

Revert "Use VS platform's IVsService"

---

setup/ProjectSystemSetup/source.extension.vsixmanifest

In 17.0 we've seen a number of reports where users try to start a project with F5/Ctrl+F5. When I've looked into these I've found that the VS components related to Hot Reload (i.e. Microsoft.VisualStudio.HotReload.Components) are not installed. This leads to a short chain of MEF composition errors that results in us being unable to instantiate a `ProjectLaunchTargetsProvider`, which in turn means we don't know how to handle launch profiles using the "Project" or "Executable" command.
It is not entirely clear how we get into this situation as I have not yet been able to create a VS installation that _doesn't_ include Microsoft.VisualStudio.HotReload.Components, either through choosing workloads in the UI or by importing a .vsconfig file.
This is a low-cost attempt to fix the problem by …

Declare a prerequisite

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInputDataSource.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTestBase.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInputTests.cs

At some point in the history of the fast up-to-date check we used `AdditionalDependentFileTimes` data to track files such as `.editorconfig`, `global.json`, and other similar files.
Currently we do not use this data. This change removes the tracking and storage of this data, along with some commented code and skipped unit tests related to it.
We may wish to revert this PR in future as part of a potential fix for #6227. Until then it is avoidable overhead.

Remove AdditionalDependentFileTimes from fast up-to-date check

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Log.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

Fixes #7820
Moves all strings to resource dictionaries. A few strings were slightly modified to be more likely to succeed in other languages.
The lack of indentation for items within sets in verbose logging was also addressed.

Localise fast up-to-date check logging

---

README.md

Update some links in README.md to use direct link instead of redirected from old link.
For example: https://github.com/microsoft/msbuild to https://github.com/dotnet/msbuild.

Update some links in README.md to use direct link

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf

Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1531874

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/AttachedCollectionItemBase.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Shipped.txt

I am working to show `.props` and `.targets` files within NuGet package nodes in the Dependencies tree (#7838). It feels natural to want to double-click these to open them in the editor.
Currently that is not possible on the NuGet side as the explicit implementation of `IInteractionPatternProvider.GetPattern` could not be overridden. This PR changes that, however it will take a while for code to flow through to where I can consume it on the NuGet side. To avoid that delay, this PR also adds `IInvocationPattern` to the set of supported patterns. At runtime there is no behaviour change for types that do not actually implement IInvocationPattern. However those that do will now work correctly, meaning the NuGet scenario becomes unblocked.
The "interaction pattern" here means support for …

Enable external "related items" to use the interaction pattern

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectConfigurationExtensions.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Log.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInputDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ProjectConfigurationExtensionsTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInputTests.cs

Fixes #7839 
Now as the check cycles through the various target frameworks in the project, the log specifies each target in its own section.

Impove up-to-date check logging for multi-targeting projects

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Waiting/VisualStudioWaitContext.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Waiting/IWaitContext.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Waiting/VisualStudioWaitContextTests.cs

#7816 made me curious about how we handle threaded wait dialogs in the .NET Project System.
While looking at our code for that, I noticed buggy and unused code. This PR removes it, and tidies.
The `IWaitContext.AllowCancel` property is unused and will not work correctly. If a dialog was created that did not allow cancellation, then this property is later set to true, the backing cancellation token will not be updated. Further, it's unlikely that a consumer of this type would re-query the token after setting the property. It feels like a safer design, and a cleaner implementation, to remove this unused property and avoid potential future bugs.
Note that we don't use the `IWaitContext.Message` property either, but the implementation of that property appears to be correct so I left it in.

Remove IWaitContext.AllowCancel

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs

In the CPS NFE report we have an item with stack:
```
Microsoft.VisualStudio.ProjectSystem.LanguageServices.ApplyChangesToWorkspaceContext.ProcessOptions(IProjectBuildSnapshot)
Microsoft.VisualStudio.ProjectSystem.LanguageServices.ApplyChangesToWorkspaceContext.<ApplyProjectBuildAsync>d__11.MoveNext()
```
There are a few places where a null value could creep in. This change will allow us to better root cause the issue, in the absence of a repro.

Uncover source of NullReferenceException

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs

In #7848 we introduced a mechanism to skip sending empty batches to the language service. That change introduced a bug where a skipped batch would also fail to provide operation progress with the data source versions.
This could result in a case where the last language service update was empty, we wouldn't notify operation progress of that update's version, and operation progress would run indefinitely.
This change ensures we always notify operation progress.
Note that this code is going to change in the next PR (already submitted as #7855). I will rebase that PR on this change once merged, and add unit tests to cover this scenario.

Notify operation progress even when we skip batches

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextHostInstanceTests.cs

Fixes #7860.
The previous code was tracking the active project/active editor state and notifying Roslyn when these changed. However, the individual "apply to workspace" implementations were not taking this change into account, so this change tracking would lead to redundant batch updates.

Don't track context changes

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs

This assertion seems logically sound but is failing in practice in some cases. I will investigate the reason for this in future. For now, it is harmless to continue in such cases. The only downside might be redundant batches being sent to Roslyn, but we had many more such updates only a week ago, so even if some of these slip through we are still in a much better state than before.

Remove assertion

---

build/ci/official.yml

The build is currently failing because the optimization data doesn't exist with the current history in `main`. Basically, merging the OptProf PR with `Squash and Merge` meant that the history is different. Why does that matter? Because OptProf looks up to a certain amount of commits away from the current commit to find the optimization data. It was working fine on my separate branch, but the history changed on main and it has no context of where to find the optimization data now.
The branch in this PR already has a set of optimization data with this history. So, the build when merging this PR should succeed. Additionally, I've made the ability to skip optimization a runtime parameter. This means that if you manually queue a build in CI, you can skip optimization if this issue ever arises …

Add SkipOptimize runtime parameter

---

build/import/HostAgnostic.props
src/Microsoft.VisualStudio.AppDesigner/Microsoft.VisualStudio.AppDesigner.vbproj

Follows from an internal email chain.
This makes our analyzer package references use private assets, so that consumers of those packages do not transitively take on dependencies on those analyzers too.
This PR also removes the `Microsoft.VisualStudio.ProjectSystem*` package references from the App Designer projects, where they are not needed.

Make analyzer package assets private and remove some package references

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/ImplicitlyTriggeredDebugBuildManager.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IProjectSystemOptionsWithChanges.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectSystemOptions.cs

Visual Studio settings are exposed through the `Microsoft.VisualStudio.Settings.ISettingsManager`. We hide this behind our `IProjectSystemOptions` interface, partly so we can access these options in the Microsoft.VisualStudio.ProjectSystem.Managed project (which doesn't depend on VS-specific interfaces). Currently, our implementation of `IProjectSystemOptions` treats `ISettingsManager` as being bound to the UI thread, which means it explicitly transitions to the UI thread before retrieving the service or calling methods on it.
However, this is unnecessarily restrictive, as the `ISettingsManager` documentation explicitly states that its methods may be called on any thread. Here we remove the transitions to the main thread, and access `ISettingsManager` through an `IVsService<T>` instead of …

Don't require the UI thread for settings

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextHostInstanceTests.cs

Reverts dotnet/project-system#7862
Turns out that change causes an issue when opening `.razor` files in a new Blazor WebAssembly project, for example.
Thanks to @ryanbrandenburg for finding and doing the initial diagnosis.
cc @davkean who was interested in this change.
I'll re-open #7860 too.

Revert "Don't track context changes"

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml

Fixes [AB#1470720](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1470720).
As with most of the other settings on the "Build" property page, the `DebugType` property is meant to be configuration-dependent. While the default for .NET Core projects is to always produce a portable PDB, this supports the common practice of producing a PDB for debug builds and no PDB for release builds.
We also need this property value to go through interception (see the `DebugTypeValueProvider` for details) and so we need to add a property-specific `DataSource` and set the `Persistence` to "ProjectFileWithInterception". When we add a property-specific `DataSource` we typically set the `HasConfigurationCondition` value again as we are no longer inheriting it from the …

Make DebugType config-dependent

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContext.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ISourceItemsHandlerFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContextTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextHostInstanceTests.cs

Fixes [AB#1468419](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1468419)
Fixes #7860
https://github.com/dotnet/project-system/pull/7855 introduced a bug that stopped dynamic files (such as `.razor` files) being passed to Roslyn. The change incorrectly passed the evaluation project update to the source item handlers, rather than the source items update. There was no unit test for this scenario.
This fixes the bug by passing the right data to the right handler, and adding a unit test to ensure coverage of this behaviour.
This PR also re-instates #7862 which we previously reverted.

Fix broken source item reporting

---

build/import/Packages.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/ProjectLaunchProfileHandler.cs

Move to a newer version of CPS that includes the new `LaunchProfileValue.DisplayName` property and populate it. For the moment it will be the same as the `Name` property, but a future change will make `Name` a unique, persistent identifier for a launch profile.
Note this is the second step of a set of staged changes. CPS now defines the `LaunchProfileValue.DisplayName` property but can't take a dependency on it because the .NET Project System doesn't populate it at all. And since CPS can't depend on it, the project system can't be updated to make `Name` a persistent, unique value and handle renames as expected. This interim change allows CPS to move forward without a user-visible break or change in behavior.

Populate LaunchProfileValue.DisplayName

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureDetector.cs

The use of these cookies was inverted, meaning these components could remain active in memory.
In practice this is not a major issue, as this is a global service which is only disposed when VS shuts down.

Prevent memory leak

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureDetector.ProjectChecker.cs

Previously we would use `RunAndForget` on the UI thread, then have that continuation switch to the thread pool.
By using `ForkOptions.StartOnThreadPool` we can invoke directly on the thread pool.
This also allows removing a state machine.

Run operation directly off the UI thread

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs

When the Fast Up-to-Date Check needs to check multiple configurations (because we're targeting multiple frameworks and we have one configuration per framework) we output `UpToDateCheckImplicitConfiguredInput.ProjectConfiguration` to the log. We have an `Assume.NotNull` asserting that the `ProjectConfiguration` cannot be `null` at this point, and a comment stating that the property will only be `null` if the FUTD Check is disabled--and if it is we wouldn't have gotten that far.
The assertion and comment are fundamentally incorrect, though it is true that `ProjectConfiguration` will be `null` when the check is disabled. Checking whether or not the FUTD Check is disabled doesn't happen until a later call to `CheckGlobalConditions`. And indeed, if you create a multi-targeting project and set …

Fix an incorrect assumption in the Fast Up-to-Date Check

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/AbstractExtenderCATIDProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/CSharp/CSharpExtenderCATIDProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VisualBasic/VisualBasicExtenderCATIDProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AbstractAddItemCommand.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/OrderingHelper.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/FlagsStringMatcher.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Build/BuildUtilities.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Imaging/CSharp/CSharpProjectImageProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Imaging/VisualBasic/VisualBasicProjectImageProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/FSharp/FSharpCommandLineParserService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/ActiveLaunchProfileExtensionValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/LaunchProfiles/ProjectLaunchProfileExtensionValueProvider.cs

Relates to: https://github.com/dotnet/project-system/pull/7907
I went through all the switch statements (not switch expressions) in the C# code in our repo.
- 18 switch statements were present prior to this PR; 7 remain after this PR
- 1 switch statement in `FlagsStringMatcher.cs` had redundant `{ }` blocks for the cases; removed them
- Many switch statements could be replaced with switch expressions
- Some switch statements could be replaced with pattern matching
- Added a comment for some switch statements in which the value was discarded after conversion to switch expression
Criteria used:
- If all cases returned a value and were a single statement within the case (the exception being the `default` case), then I converted them to switch expressions
- If there were more than 3 cases …

Simplify or refine existing switch statements

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml

This PR makes the MSBuild ActiveDebugProfile (currently active launch profile) accessible to CPS so that CPS can select the active launch profile when the debug property page opens. Related to #7595

Add ActiveDebugProfile to properties accessible to CPS

---

.editorconfig

This makes VS format case blocks the way we seem to do them in this repo.
```c#
switch (foo)
{
case Bar:
{
// block content
break;
}
}
```
```c#
switch (foo)
{
case Bar:
{
// block content
break;
}
}
```

Don't indent case contents when block

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckStatePersistence.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/IUpToDateCheckStatePersistence.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInputDataSource.cs

Fixes [AB#1484422](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1484422)
The file operations can take a while to complete. The previous code protected these operations and data structures using a monitor lock, which blocks threads. This could lead to thread pool threads being blocked
This change uses an async semaphore, which allows threads that are not granted access to the critical section to yield and do other useful work until they are able to gain access.

Don't block thread pool threads during file IO

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/RenamerProjectTreeActionHandler.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/RenamerTestsBase.cs

- Remove unnecessary asyn
- rename method to follow naming guidelines.
- Replace string literals with const string.

Code cleanup RenamerProjectTreeActionHandler.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ConfigurationGeneralPage.xaml

We use the `ConfigurationGeneralPage` to expose project properties to visibility conditions.
For MAUI we need the ability to condition properties on the target platform.
Adding this property here makes it available. The function can then be added in CPS.
cc @japarson

Make TargetPlatformIdentifier available to visibility conditions for MAUI

---

build/ci/official.yml

In our `official.yml` pipeline, we see this warning:
I started an email conversation with the team that makes this plugin. Apparently, the plugin is supposed to default to `latest` when it has no version specified. I have informed that team this clearly is not happening, as every pipeline I've looked at shows this warning. To remove this warning for the time being, we are explicitly setting the `bootstrapperCoreVersion` to `latest`.

Fix pipeline warning about Build VS Bootstrapper version

---

build/import/Packages.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/FileMoveNotificationListener.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/RenamerProjectTreeActionHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Waiting/VisualStudioWaitContext.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Waiting/VisualStudioWaitIndicator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Waiting/IWaitContext.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Waiting/IWaitIndicator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Waiting/WaitIndicatorResult.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Waiting/VisualStudioWaitContextTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Waiting/VisualStudioWaitIndicatorTests.cs

This PR adds a feature where after moving compile items between folders (by drag drop on Solution Explorer), the user is prompted to update the namespaces.
Requires VS PR: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/CPS/pullrequest/378467
Requires CPS PR: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/CPS/pullrequest/378467
Two new options are added to control this behaviour:

Feature update namespace

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/CompoundTargetFrameworkValueProvider.cs

Fixes [AB#1473348](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1473348).
The platform value is needed to be added to the `TargetFramework` value for WPF and Windows Forms projects to be able to build properly. We have been adding this value for .NET 5 and 6; this change extends this behavior for .NET 7.

Add windows platform to TargetFramework value for .NET 7 when needed.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckInputItem.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectCatalogSnapshotFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTestBase.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

Fixes #6508
The fast up-to-date check tracks project items. When these items have `CopyToOutputDirectory` metadata, the check ensures the destination file exists. If it does not, a build is scheduled.
MSBuild only considers four item types when copying files to the output directory: `None`, `Content`, `Compile` and `EmbeddedResource`.
This change restricts the fast up-to-date check to only consider these four item types when assessing which items to copy to the output directory.

Fix redundant build (overbuild) loop issue in the fast up-to-date check

---

build/ci/official.yml

Working build from these changes: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5861305
There was a change in the dependencies for the VS Bootstrapper task. This change was made to help those doing SBOM. Because of our reliance on RepoInsertionTool, we can't update the MicroBuild SwixBuild plugin, which is now necessary to use VS Bootstrapper task at the moment. Since we need this task to produce OptProf data, we have to disable OptProf until we can remove our reliance on RepoInsertionTool and use the latest MicroBuild SwixBuild plugin.
Along with disabling these tasks, the trigger for the [OptProf release pipeline](https://devdiv.visualstudio.com/DevDiv/_release?definitionId=3197) will also be disabled:
OptProf release trigger disabled:

Disable OptProf to fix build

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/PackagePropertyPage.xaml

Fixes [AB#1494063](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1494063).
Use the `MultiLineString` editor for the `PackageReleaseNotes` property, just as we do for `Description`. Otherwise you can't type new lines into the editor and would have to fall back to editing the project by hand.

Use the MultiLineString editor

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Log.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryPropertyName.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

It would be useful to know how widespread use of this logging is for a few reasons:
- We enable incremental build failure logging when set to a level higher than 'None'.
- When analysing the check's duration, we would expect the duration to be higher when verbose logging is enabled. Once we know the log level, we can filter or group accordingly.

Include up-to-date check log level in telemetry

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Log.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs

When a project is configured to validate for incremental build failures, we run the fast up-to-date check a second time after the build. If the project is not up-to-date, then there is an incremental build failure.
For that second run, we should not send the regular check's telemetry. We have different telemetry to track the failure.

Don't send up-to-date check telemetry during validation

---

build/ci/compliance.yml
build/ci/integration-tests.yml
build/ci/official.yml
build/ci/one-loc-build.yml
build/ci/richnav.yml
build/ci/unit-tests-template.yml
build/ci/unit-tests.yml
build/loc/Directory.Build.props
build/loc/OneLocBuildSetup.csproj

- Updated all pipelines to use VS2022 images
- VS 2022 images needed for C# 10
- Updated all builds to no longer use `build.cmd`, which allows for explicit use of x86 MSBuild
- Running MSBuild as x86 unblocks allowing C# 10 to be used, such as from here: https://github.com/dotnet/project-system/pull/7786
- The primary issue is described here on why the C# 10 changes were causing build failures, which works around that issue that is not fixed on our internal images (`VSEngSS-MicroBuild2022-1ES`): https://github.com/dotnet/msbuild/issues/7108
- Updated `OneLocBuildSetup.csproj` to .Net 6 and made it ignore the root `Directory.Build.props`
- RichNav: https://dev.azure.com/dnceng/public/_build/results?buildId=1659895
- OneLocBuild: https://dev.azure.com/dnceng/public/_build/results?buildId=165 …

Update pipelines to use VS 2022 images

---

src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsDesigner.vb
src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsSingleFileGeneratorBase.vb

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1289213/ by replacing spaces in the namespace/class name of the VB settings file with underscores.
Test as follows:
- Create new WPF VB project
- Create new folder (My Project)
- Create new settings file (Settings.settings)
- Click show all files 
- Observe no errors in the generated Settings VB file

Strip out spaces in VB settings class/member .settings properties

---

build/import/VisualStudio.XamlRules.targets

PR #7959 fixed an overbuild issue seen in our repo. That fix highlighted a bug in our build where embedded rule files were inivisible to the fast up-to-date check.
This change ensures `XamlPropertyRuleNoCodeBehind` items are added to the `UpToDateCheckInput` item group, so that we build correctly when one of these files is changed.

Changing embedded rules trigger project build

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/CollectedPackageReference.xaml

In https://github.com/NuGet/NuGet.Client/pull/4426 I added a new attribute to `<PackageReference />` to allow the ability to override a centrally defined package version.  This change adds the property to nomination in project system

Passing VersionOverride metadata as part of nomination

---

build/import/Workarounds.targets

Since commit 1f2f03e5 we've removed copies of xunit.abstractions.dll from the "None" group during evaluation (see that commit and the related issues for the background on why). We specify the files to remove using a globs of the form:
`$(Pkgxunit_runner_visualstudio)\**\xunit.abstractions.dll`
and
`$(Pkgxunit_runner_console)\**\xunit.abstractions.dll`
The `Pkgxunit_runner_visualstudio` and `Pkgxunit_runner_console` specify the locations of the restored xunit.runner.visualstudio and xunit.runner.console NuGet packages, respectively. The globs are meant to allow us to remove xunit.abstractions.dll without taking a dependency on the layout of the files within those packages.
This removal is in Workarounds.targets which is imported by every one of our projects. However, the …

Fix bad globbing

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ProjectDebugPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectLaunchTargetsProviderTests.cs

Fixes #7392  by making the CommandLineArguments StringProperty multiline, and then stripping out the newlines in ProjectLaunchTargetsProvider

Allow newlines in command line arguments prop

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf

Localized file check-in by OneLocBuild Task: Build definition ID 981: Build ID 1673665

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSession.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/MetadataExtensions.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependenciesChangesBuilder.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/DependenciesRuleHandlerBase.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PhysicalProjectTreeStorageTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/References/AlwaysAllowValidProjectReferenceCheckerTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviders/AbstractFindByNameUnderAppDesignerSpecialFileProviderTestBase.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/AppDesignerFolderProjectTreePropertiesProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/ProjectRootImageProjectTreeModifierTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/PackageRestoreConfiguredInputFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/AbstractAddItemCommandHandlerTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/AbstractGenerateNuGetPackageCommandTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/AbstractOpenProjectDesignerCommandTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/GenerateNuGetPackageProjectContextMenuCommandTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/GenerateNuGetPackageTopLevelBuildMenuCommandTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/Ordering/MoveDownCommandTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/Ordering/MoveUpCommandTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/ActiveEditorContextTrackerTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/ProjectDesignerServiceTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/References/DesignTimeAssemblyResolutionTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/FlagsStringMatcherTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/WindowsForms/WindowsFormsEditorProviderTests.cs

Roslyn flagged these as redundant, and they were removed via a codefix.
Three categories of casts were removed:
1. C# 10 does a better job of inferring the type for ternary conditional expressions, based on the target type
2. Casts that were previously required for nullable reference types
3. Casts of zero to enum types are not required

Remove redundant casts (solution-wide codefix)

---

build/import/Packages.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreConfiguredInputDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Collections/ImmutableStringHashSet.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DataflowUtilities.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectChangeDiff.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/CrossTarget/RuleSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependencyRulesSubscriberBase.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInputDataSource.cs

Reverts dotnet/project-system#7993
Moving to `JointRuleDataflowLinkOptions` came with a change in behaviour that breaks some core components. We need to back this out pending further investigation.

Revert "Avoid race condition in JointRuleSource"

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/WarningLevelOverriddenValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/WarningLevelOverriddenValueProviderTests.cs

Fixes #7977.
Related to [AB#1459442](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1459442).
Historically, the `WarningLevel` property (corresponding to the `-warn:<n>` switch) controlled what set of warnings would be produced by the C# compiler. "0" meant produce no warnings (only errors). "1" meant produce only the most severe warnings. "2" meant produce all the warnings in 1, plus a set of less severe warnings. "3" meant all the warnings in 2 (and 1) plus additional, even less severe warnings. And so on. The default for a long time was "4" which effectively turned on all warnings the compiler could produce. The general idea was that, if need be, the user could pick a low `WarningLevel` to identify and subsequently fix the most impactful warnings …

Rework WarningLevel property

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckBuildEventNotifier.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Subscription.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/IBuildUpToDateCheckProviderInternal.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

Fixes #7700
Fixes #7821
Improves #7803 by breaking loop
The fast up-to-date check cannot rely solely on file timestamps to identify when a build is required. We also need to know when a build has occurred following a change in the project's items.
Historically we tracked the time the project's set of inputs changed, then compared that to the latest build output's time. This allowed an overbuild performance bug to occur, where the change in the set of items would not correspond with a change in build outputs. In this state, the project would build on every invocation.
PR #7906 recently fixed issue [AB#1471474](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1471474), where we would schedule a build after a rebuild occurred. The fix required adding build …

Fix overbuild loop when the set of inputs changes, but outputs aren't updated by build

---

build/ci/official.yml

Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1497655
OptProf was disabled because it required the VS Bootstrapper task. This task was silently updated during SBOM changes and caused our build to start failing. To allow us to continue checking in code, I disabled OptProf which uses the VS Bootstrapper task. The VS Bootstrapper task required an updated MicroBuild Swix plugin, which at the time, I believed could not be updated because an old version is required by RepoToolset.
I did some investigation and found that the version of the Swix plugin we were installing via the DevOps task was `1.1.87`. However, if you look at the build logs, the version used by RepoToolset is `1.1.37`. This means the task we have in our pipeline was **only** being used by VS Bootstrapper, and …

Re-enable OptProf

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependencyRulesSubscriberBase.cs

Previously, an intermediate Dataflow block was created for the sole purpose of specifying rule names. It's more to configure this directly during the `SyncLink` operation.

Remove intermediate Dataflow block

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml

This was missed as part of https://github.com/dotnet/project-system/pull/7985 but I added some properties that need to also be passed to NuGet restore:
https://github.com/NuGet/NuGet.Client/pull/4426 added a property to enable/disable the use of `VersionOverride`: `CentralPackageVersionOverrideEnabled`
https://github.com/NuGet/NuGet.Client/pull/4025 added a property to enable/disable the feature to "pin" transitive versions: `CentralPackageTransitivePinningEnabled`

Pass CentralPackageTransitivePinningEnabled and CentralPackageVersionOverrideEnabled to NuGet restore

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/DependenciesRuleHandlerBase.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.cs

Fixes [AB#1506157](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1506157)
Refactoring in #7988 made an incorrect assumption, which is fixed here.
The assumption was that a non-null `Func<string, bool>? isEvaluatedItemSpec` value indicates a resolved dependency. However that is not true, as for analyzer references, `AnalyzerRuleHandler` overrides `ResolvedItemRequiresEvaluatedItem` to return `false`. This means that for analyzer references that are resolved, `isEvaluatedItemSpec` is null.
The fix is to thread the `isResolvedItem` through the code explicitly, rather than inferring it.

Fix analyzer references appearing as unresolved

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextProvider.cs

Fixes #8027
Fixes [AB#1511966](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1511966)
Changes made to the workspace context are synchronised within Roslyn IDE's language service. We generally use batches to ensure we don't block threads during these updates.
This is one case we missed. @sharwell observed one-thread-per-project blocked within the called code. This change will allow the thread pool thread to yield, so other productive work can be performed and thread pool starvation is avoided.

Use batch to update language service

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/AnalyzerDependencyModel.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/AnalyzerDependencyModelTests.cs

In 17.2, CPS made a change to how paths are used for non-file items in the tree. These changes improve the performance of searching the dependency tree by path, as the pseudo-id used for items not having paths allows a fast lookup.
That change broke the ability for Roslyn to determine the correct file path for analyzer nodes (via `CanonicalName`), which then broke the ability to attach child nodes to the analyzer in Solution Explorer (for example, to show source generators and the files they create).
In this commit, we add the `FileSystemEntity` flag to analyzer nodes. This causes CPS to preserve the full path provided on the `IProjectTree`, which restores the `CanonicalName` for Roslyn.

[17.2] Fix broken analyzer child nodes in Solution Explorer

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/PackagePropertyPage/PackageLicenseFileValueProvider.cs

Fixes: https://github.com/dotnet/project-system/issues/7846
Added property interceptor for PackageLicenseFile to correctly add the file to the project and update the property accordingly. It reuses the base interceptor logic for doing this kind of property, which has been used for other Packaging properties.

Fix PackageLicenseFile property's file inclusion

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Acquisition/MissingSetupComponentRegistrationService.cs

The reason behind it is that the task failed in our future VS prototype branch, as VS setup component is not yet working.  Reporting the project has limited service will put the project into a state where several import features are disabled (like operation progress).  This should not have any impact on normal function of this code.
Basically, a failure to display a missing component doesn't need leave the project system to the partial failure state, so we can limit the impact of this missing feature until setup component is fixed.

Update fault event level, when DisplayMissingCompnents failed.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependencyRulesSubscriberBase.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs

Previously the code went to lengths to prevent unload during processing.
With this change, we allow the project to unload, and wire through a cancellation token that is cancelled as the project unloads.

Cancel dependencies tree processing on project unload

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets

Fixes #8015
There was an attempt two years ago to fix this, in #5994. I don't see how that fix could have ever worked.
The MSBuild item that modelled the `App.config` source/destination paths had an invalid condition. It was verifying that the an `AppConfig` _item_ existed, while it should have been verifying an `AppConfig` _property_ existed.

Fix up-to-date tracking for App.config files

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf

While investigating a customer feedback ticket, it was unclear why a launch profile handler was not claiming support for the given profile. It would be useful to see the profile name in the error message sent by the customer. This change includes that detail.

Include launch profile command name in error message

---

Directory.Build.props
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

The fast up-to-date check unit tests validate the log output produced in each test scenario.
Previously we only validated "info" level logs. This change increases that to "verbose" to get better coverage of the underlying behaviour.
The tests are also modified to specify the entire log output as a single raw string (using a preview compiler feature), rather than an array of strings.
Further, some test data was modified to be more realistic and hopefully highlight problems that might manifest as paths are composed in the system under test.

Expand fast up-to-date check test coverage

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/PackagePropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.zh-Hant.xlf

These properties support the creation of .NET tools, which are special NuGet packages that may be installed on a machine and executed from the command line.

Add PackAsTool and ToolCommandName properties to the Package page

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/PackagePropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.zh-Hant.xlf

Fixes #2709
This property allows specifying the path on disk where package files are dropped when the project is packed.

Add the PackageOutputPath property to the Package page

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/PackagePropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.zh-Hant.xlf

When packing a project, the tooling supports producing an additional package containing debug symbols.
This change adds a boolean property to opt in to this feature, and a drop down to select the format of this package.

Add properties to control symbol packages

---

Directory.Build.props

Related to #8074.
Warnings about duplicate PackageReference items are being promoted to errors in build.cmd and thus breaking our build. Here we suppress the warning until we can remove the duplicates.

Suppress NU1504

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/PackagePropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.zh-Hant.xlf

Fixes #2937
This property allows specifying an optional display name for a package, to be used on nuget.org and in the Visual Studio Package Manager.

Add the Title property to the Package page

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml

The `WarningLevelOverridden` property should never be visible. This was being achieved with a visibility condition. However that requires the UI to create and maintain an object for the property, re-evaluating its visibility as the UI updates.
By setting the `IsVisible` property to false, the UI can be slightly more efficient here.

Express always-hidden property with static data

---

docs/repo/property-pages/back-end-architecture.md
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/ProjectSetEvaluatedUIPropertyValueAction.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/ProjectSetUnevaluatedUIPropertyValueAction.cs

Similar to evaluated property values, this allows null-set unevaluated property values. This does not preclude an empty unevaluated value from being set.
This is for #6920

Allow null set on unevaluated property value

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VsBuildManager.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/OrderingHelper.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/AbstractBuildEventValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configuration/BaseProjectConfigurationDimensionProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/LaunchTargetPropertyPageEnumProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UnconfiguredProjectTasksService.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IConfigurationGroupFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ActiveConfiguredProjectsProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Build/PublishableProjectConfigProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PhysicalProjectTreeTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/LaunchProfiles/LaunchProfilesProjectItemProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviders/AbstractFindByNameSpecialFileProviderTestBase.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviders/AbstractFindByNameUnderAppDesignerSpecialFileProviderTestBase.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IActiveConfiguredProjectSubscriptionServiceFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IRoslynServicesFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectLaunchTargetsProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/ProjectDesignerServiceTests.cs

This PR applies the automated codefix for IDE0200 across the solution.
Historically, Roslyn would not cache the delegate generated when converting a method group to a delegate. This changed recently and our version of the compiler now does so.

Remove unnecessary lambda expressions

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

This opportunity was identified as a result of work in #8054.
In #8005 we changed how the fast up-to-date check handled changes in the set of project items. That change means we no longer check against build output times.
As a consequence of that, we can do this check sooner, before we scan outputs. In the case that this check fails, it will fail a little faster. It also has the benefit that we only run the check once in the case that we have multiple sets of inputs/outputs, as previously we performed the check for each set.

Fast up-to-date check handles changed items sooner

---

src/Microsoft.VisualStudio.Editors/OptionPages/SDKStyleProjectOptionsData.vb
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectSystemOptions.cs

Change the default value of "Prefer single-target builds on launch" from false to true. Now that MAUI testing is complete we can have this on by default.
Related to [AB#1438932](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1438932).

Change default

---

build/import/Packages.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyValueDataProducer.cs

The new metadata property ValueDefinedInContext needs to be passed back to CPS from the project-system side

update CPS and pass ValueDefinedInContext back to CPS

---

tests/Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests/ProjectSystem/ProjectTreeParserTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectSubscriptionUpdateFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/ApplyChangesToWorkspaceContextTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/DynamicItemHandlerTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/ProjectFilePathAndDisplayNameEvaluationHandlerTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/ProjectPropertiesItemHandlerTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PhysicalProjectTreeTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Reload/ProjectReloadInterceptorTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviders/AbstractAppXamlSpecialFileProviderTestBase.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviders/AbstractFindByNameSpecialFileProviderTestBase.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviders/AbstractFindByNameUnderAppDesignerSpecialFileProviderTestBase.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviders/AppDesignerFolderSpecialFileProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/AppDesignerFolderProjectTreePropertiesProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/ProjectRootImageProjectTreeModifierTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Automation/VisualBasic/VisualBasicNamespaceImportsListTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/AbstractAddItemCommandHandlerTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/AbstractGenerateNuGetPackageCommandTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/AbstractOpenProjectDesignerCommandTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/GenerateNuGetPackageProjectContextMenuCommandTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/GenerateNuGetPackageTopLevelBuildMenuCommandTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/Ordering/MoveDownCommandTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/Ordering/MoveUpCommandTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Input/Commands/Ordering/OrderingHelperTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PackageRestore/Snapshots/RestoreBuilderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/AvoidPersistingProjectGuidStorageProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/PostBuildEventValueProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/PreBuildEventValueProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsChangeTrackerTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/WindowsForms/WindowsFormsEditorProviderTests.cs

Recently this change was made in c62261b947dc6406f4f6f8178095d2bfd4583e6a to launch settings test data, which was a nice clean up. This commit applies it to remaining test data.

Use raw strings in test data

---

Directory.Build.props
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureDetector.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IProjectServiceExtensions.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckBuildEventNotifier.cs

Fixes [AB#1527166](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1527166)
Two components in the .NET Project System listen to build events. When notified about a project's build progress, they are passed `IVsHierarchy` objects.
Previously we used `AsUnconfiguredProject` to obtain the project from a hierarchy, however when this method is invoked on a VC++ project it forces that project to fully load. This is a performance regression for mixed .NET/VC++ solutions.
With this change, we use `IProjectService2.GetLoadedProject` to obtain the project. CPS won't make any operation against an external project system in this case, so there's no chance of inadvertently loading any unloaded components.
We also validate that the project has the required …

[17.2] Don't load VC++ projects during build

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/DebuggerTraceListener.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/DebugProfileEnumValuesGenerator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/FSharp/FSharpProjectSelector.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IPackageService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/DebugFrameworksMenuTextUpdater.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AbstractAddItemCommand.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddExistingItemAboveCommand.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddExistingItemBelowCommand.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddExistingItemCommand.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddNewItemAboveCommand.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddNewItemBelowCommand.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/AddNewItemCommand.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/PackageCommandRegistrationService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/ProjectDesignerService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcher.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/DependenciesTreeSearchProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Commands/NavigateToProjectCommand.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsSolutionEventListener.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Xproj/XprojProjectFactory.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/DesignTimeTelemetryLoggerProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesProjectTreeProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/TaskDelayScheduler.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectThreadingServiceFactory.ProjectThreadingService.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Threading/Tasks/TaskDelaySchedulerTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/ProjectDesignerServiceTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcherTests.cs

Historically one of the MS.VS namespaces had its own `Task` class, which conflicted with `System.Threading.Tasks.Task`.
Whenever this conflict occurred, we had to add a `using` alias in the code.
With the change to 17.0 the `Task` type was removed from the VS SDK. These aliases are no longer needed.

Remove redundant Task aliases

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets

Fixes #8092
On Windows, an executable may specify an `app.manifest` file that factors into the compilation of the output. Changes to this file must trigger a build.
This change adds such a file, if specified, to the list of inputs that the fast up-to-date check considers.
Change `app.manifest` and build:
```
Build started...
1>FastUpToDate: Adding UpToDateCheckBuilt outputs: (ConsoleApp404)
1>FastUpToDate:     C:\Users\drnoakes\source\repos\ConsoleApp404\ConsoleApp404\bin\Debug\net6.0\ConsoleApp404.pdb (ConsoleApp404)
1>FastUpToDate:     C:\Users\drnoakes\source\repos\ConsoleApp404\ConsoleApp404\bin\Debug\net6.0\ConsoleApp404.dll (ConsoleApp404)
1>FastUpToDate:     C:\Users\drnoakes\source\repos\ConsoleApp404\ConsoleApp404\obj\Debug\net6.0\ConsoleApp404.pdb (ConsoleApp404)
1>FastUpToDate: …
```

Fast up-to-date check considers ApplicationManifest

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Log.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryPropertyName.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

When an indirect build occurs (for debug or unit test runs) a global property containing optional kinds of FUTD inputs to ignore is specified. This modifies the FUTD check such that subsequent full builds still occur.
This change adds the list of ignore kinds to the telemetry data we publish.

Add FUTD "ignore kinds" to telemetry data

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj

We missed this item update in our .csproj file. As a consequence, for a clean clone of our repo, CPS creates a .user file that contains this metadata for the project. This means the project becomes immediately out-of-date, and we report an incremental build failure.
Adding this into the .csproj file fixes this issue.
The `.csproj.user` file has the following content:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<PropertyGroup />
<ItemGroup>
<Compile Update="PropertyPages\PropertyPageControl.cs">
<SubType>UserControl</SubType>
</Compile>
</ItemGroup>
</Project>
```

Prevent a .csproj.user file being created during build

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ExecutableDebugPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ProjectDebugPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hant.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf

Fixes #7330
When we moved launch profiles to the new UI, we regressed the editing experience for environment variables. Previously we had an editable grid of values:
With the update to the new UI, this was collapsed into a single string with specific rules around encoding and escaping:
CPS PR https://dev.azure.com/devdiv/DevDiv/_git/CPS/pullrequest/394046 adds a new editor type for grid-based editing of properties.
This change configures the launch profiles UI to use that new editor for environment variable properties.
Here's how the whole feature works, end to end:

Restore the editing experience for environment variables in launch profiles

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/CSharp/CSharpAppConfigSpecialFileProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/VisualBasic/VisualBasicAppConfigSpecialFileProvider.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviders/CSharp/CSharpAppConfigSpecialFileProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/SpecialFileProviders/VisualBasic/VisualBasicAppConfigSpecialFileProviderTests.cs

Fixes #7772.
An app.config file should be created when a setting is created/modified and the project doesn't have an app.config file already.
The issue was that it tries to create one but it doesn't find the template in the given folder [AppConfigurationInternal](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=/src/vsproject/Templates/Windows/VisualBasic/ItemTemplates/AppConfigurationInternal) because that is specific to Visual Basic. Instead, it should be looking at the [AppConfigInternal](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=/src/vsproject/Templates/Windows/CSharp/ItemTemplates/AppConfigInternal) folder.

Correctly retrieve app.config template for C# projects.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/Compile.xaml
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/MetadataFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandlerTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/ItemRuleTests.cs

Related to [dotnet/maui #6681](https://github.com/dotnet/maui/pull/6681).
Related to [AB#1525249](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1525249).
This is an alternative to the approach in #8112.
Currently MAUI includes platform-specific files are for every platform in the MSBuild evaluation, and then at build a target removes _all_ these items and then adds back the ones for the current platform.
This works for an actual build but screws up VS, as the Project System doesn't properly handle a `Compile` item that is present in evaluation but removed during a build. The end result is that the platform-specific files are not actually treated as platform-specific, leading to a number of user-visible issues:
1. Platform-specific files incorrectly …

Ignore certain items from evaluation

---

docs/repo/property-pages/property-specification.md

We recently added support for name/value pair editing (https://dev.azure.com/devdiv/DevDiv/_git/CPS/pullrequest/394046). We started using this for launch profiles in https://github.com/dotnet/project-system/pull/8084. This commit documents the new capability so that others can more easily discover and use it.

Document use of NameValueList property editor

---

.editorconfig

Using Rider, the rule `externally_visible_members_must_be_pascal_cased` competes with `interfaces_must_be_pascal_cased_and_prefixed_with_I`
The scope is (as far as i can see) not used anywhere else

Remove "interface" from externally_visible_symbols in .editorconfig

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VisualBasic/VisualBasicNamespaceImportsList.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VisualBasic/VisualBasicVSImports.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/OrderAddItemHintReceiver.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IMissingSetupComponentRegistrationService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/IDependenciesViewModelFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/ComponentComposition.ScopeComponents.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/ComponentComposition.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/ComponentVerificationTests.cs

For types imported and exported through MEF, we use the `[ProjectSystemContract]` attribute to capture scopes, purpose and cardinality.
We have a set of unit tests in `ComponentVerificationTests` that inspect our types and validate these constraints so we catch any issues before changes are merged into `main`.
While reviewing #8127 I noticed that `IMissingSetupComponentRegistrationService` was missing this annotation, and wondered why our tests didn't catch that omission.
This PR fixes the tests to cover all scenarios.
In response to the test being fixed, several missing annotations were discovered and added.

Extend component verification test coverage

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.zh-Hant.xlf

Related to #7237.
Define the properties of the VB "Compile" page (called "Build" in C#/F#) and arrange them into categories. A couple of things to note:
- The goal is to get everything stubbed out so we have controls to interact with in future changes and so we can start to discuss the look and feel of the page. Most of these properties do not yet read and write values correctly.
- Items are likely to move around in future commits. This change puts _most_ items in the same order as the old Compile property page, with the exception of "Generate XML documentation file" and "Register for COM interop". The old page visually located these under "Warning configurations" even though they have nothing to do with warnings. Here we put them in the "General" category instead.
- I found VB to be …

Define properties for the VB Compile (Build) page

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/EnvironmentHelper.cs

`launchSettings.json` may contain both `%VAR%` for environment variable and `$(Prop)` for MSBuild properties, and these values are substituted at runtime.
The vast majority of values do not use substitution, so often we can avoid allocating new strings and data structures and just re-use the previous, immutable instances.
It turns out that [`Environment.ExpandEnvironmentVariables`](https://docs.microsoft.com/en-us/dotnet/api/system.environment.expandenvironmentvariables?view=net-6.0) allocates a new string, [even when no replacement occurs](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWAChiA3CZAAgHtkoBzSgXkoCIAJAUwBtvrWA3GQqUAzqmCiEUBKgScAJs0oBRGKSjJqMMJxgIAdCoAeABwgwFajVp16EANQpQIwbp1EAKWgwCUQkiIsPABOTwAlTgAzTmQ9AGNOFQBHVAhuLx96ODEJKRk5RV9/IA). This was allocating new strings, …

Reduce allocations during value substitutions

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsJsonEncoding.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsJsonEncodingTests.cs

Fixes #8168
While the JSON standard does not technically allow comments, they are not uncommon.
This change allows our parsing to tolerate such comments without throwing exceptions. It achieves this by subclassing `JsonTextReader` to skip any comment JTokens it encounters.

Allow launchSettings.json to include comments

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.VisualBasic.xaml

The "Option explicit", "Option strict", "Option compare", and "Option infer" settings were being treated as configuration-dependent, but the existing VS property pages treat them as configuration-independent. Update the new page to match.
Related to #7237.

Make options configuration independent

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Acquisition/MissingSetupComponentRegistrationService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IMissingSetupComponentRegistrationService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Runtimes/MissingSdkRuntimeDetector.cs

Fixes [AB#1523369](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1523369) threadpool starvation due to incorrect synchronization.
The issue here is that s_listOfMissingRuntimes was not thread-safe.
This PR:
- Renames `s_listOfMissingRuntimes` to `_missingRuntimesRegistered `
- Changes the type to use a thread-safe collection.
- Moves `_missingRuntimesRegistered`  to `MissingSetupComponentRegistrationService` that fits the lifetime of this global variable.

Add lock to protect s_listOfMissingRuntimes.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/VBDisableAllWarningsValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/VBWarningsValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/VBWarningsValueProviderTests.cs

The VB "Compile" property page doesn't allow you to disable individual warnings or promote individual warnings to errors. Instead, it groups related warnings into sets and lets the user adjust the severity of the whole set at once. This commit adds the `VBWarningsValueProvider` interceptor, which converts back and forth from the "None", "Warning", and "Error" values for the various warning sets displayed on the VB compile page, and the values of the "NoWarn" and "WarningsAsErrors" properties (among others) persisted to the project file.
This also adds the `VBDisableAllWarningsValueProvider`, a simpler interceptor that maps between the "Disable all warnings" checkbox on the property page, and the "WarningLevel" property in the project file.
Related to #7237.

Make VB warning sets work

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectLaunchTargetsProviderTests.cs

This fixes #8167. VS editor escapes user-input `\r\n` as `\\r\\n`, whereas newlines in the editor are `\r\n`. Since VS Windows is Windows-only, we do not need to be OS-agnostic about newlines and can assume we just need to escape `\r\n`.

Only escape \r\n in command line args

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AdditionalFilesItemHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AnalyzerConfigItemHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AnalyzerItemHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/DynamicItemHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/MetadataReferenceItemHandler.cs

In #8181 we moved these handlers from `ConfiguredProject` scope to `UnconfiguredProject` scope in preparation for further work on #7541.
However five of our handler implementations have per-context (per-configuration) state. `ApplyChangesToWorkspaceContext` (in `ConfiguredProject` scope) handles this correctly by using an `ExportFactory` to create private (non-shared) instances of the handlers for each configuration. However that left these exports advertising themselves as safe for use in `UnconfiguredProject` scope, which is only true if they are not shared.
This commit annotates the exports to prevent accidental sharing in future. It has no runtime impact today.

Prohibit sharing of certain IWorkspaceContextHandler implementations

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckStatePersistence.cs

Fixes [AB#1543048](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1543048)
CPS's NFE reporting shows the previous `Assert.NotNull` call in `StoreStateAsync` could fail.
This change does two things:
- Handles a null in this position gracefully.
- Replaces the semaphore with the locking mechanism from `OnceInitializedOnceDisposedUnderLockAsync` so that we have a single lock around initialisation, dispose, and critical operations.
The diff is easier to read if you hide white space changes.

Prevent NFE in UpToDateCheckStatePersistence

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Acquisition/MissingSetupComponentRegistrationService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/IRegistry.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IMissingSetupComponentRegistrationService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Runtimes/MissingSdkRuntimeDetector.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Runtimes/RegistryReaderRuntimesVersions.cs

Scenario to fix [AB#1460328](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1460328) : A user installs a standalone package downloaded from the msft website, then after that the user installs VS and creates a project using a specific runtime version. VS will not be able to detect if a runtime is already installed, so VS might prompt the gold bar in the solution explorer suggesting to install the missing runtime even thought it might be already installed.
One way to detect the packages installed in a machine is with deep detection, but it is complex and costly in terms of the size of the implementation and performance. Even if we cached the results, we might see a regression on Perf DDRITs.
A workaround is to rely on …

Detect runtimes outside vs

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/IProjectHotReloadSessionInternal.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/IProjectHotReloadUpdateApplier.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSession.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManager.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Shipped.txt
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManagerTests.cs

- In order to support static asset file updates in Winforms and WPF projects, I added a new interface which provides a generic mechanism to apply those updates to all running hot reload sessions, without exposing internal details of the project system.
- The IProjectHotReloadUpdateApplier interface is exported from IProjectHotReloadSessionManager since this is the object which track hot reload sessions. It has a boolean method which returns true if sessions are active, and a second method to apply updates.
- The apply update function takes an async delegate which will be called once for each active session.  The delegate is passed the active IDeltaApplier for that session, and the assumption is the delegate can apply its update via that object.
- Doing it this way means the manage project …

Expose a mechanism to apply custom hot reload updates

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ApplicationFrameworkValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.VisualBasic.xaml

Related to https://github.com/dotnet/project-system/issues/7379 and https://github.com/dotnet/project-system/issues/7236.
The `UseApplicationFramework` property gets saved to the project file as `<MyType>`; when enabled, the value `WindowsForms` is saved; when disabled, the value `WindowsFormsWithCustomSubMain` is saved.
To test it, enable the `ProjectPropertiesEditor` ProjectCapability in the Ms.VisualBasic.DesignTime.targets file.
Note: changes to this property also ipact the myapp file; I'll bring this up in an upcoming PR.

ApplicationFramework property interceptor.

---

build/import/Packages.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/LaunchProfileActionBase.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ApplicationIconValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/PackagePropertyPage/PackageFilePropertyValueProviderBase.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/LaunchProfiles/LaunchProfileProjectItemProvider.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/LaunchProfiles/LaunchProfilesProjectItemProviderTests.cs

This is to fix an issue where the property is not obtained in the launch profile page.

Require valuedefinedincontext property for launch profile page

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WPF/AppDotXamlDocument.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf

Port AppDotXamlDocument.vb in Microsoft.VisualStudio.Editors to Microsoft.VisualStudio.ProjectSystem.Managed.VS. In the old property pages for WPF projects, this type supports getting and setting the "Startup URI" and "Shutdown Mode" properties by reading and writing to the Application.xaml via an `IVsTextLines` instance. We will need the same functionality in the new property pages, but also the option to make changes that are not backwards compatible with the old pages. So rather than trying to understand and re-create the behavior in new code I've opted for a straight port of the existing code to C#.
I've opted to move it to C# with only minor changes so we can get the WPF properties working end-to-end as soon as possible, and then we have the option of iterating on the implemenation. …

Port AppDotXamlDocument

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Log.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

Fixes #8211
Previously we used the default `DateTime` formatting, which shows whole seconds. Some kinds of investigation benefit from seeing millisecond level timing information.
---
Note, for some reason on my local machine several tests in `BuildUpToDateCheckTests` are failing due to a different enumeration order of internal immutable collections. I'm unclear on what changed to cause this problem, and am equally unclear on whether we'll see these failures in CI.

Add milliseconds to fast up-to-date check log timestamps

---

.github/fabricbot.json

FabricBot is moving away from a designer to "config-as-code". This change takes our existing configuration and copies it as-is to the blessed location in the repo; FabricBot will automatically pick it up from there. See https://1esdocs.azurewebsites.net/datainsights/merlinbot/extensions/Fabricbot_Overview.html for more information.
Many of the tasks are disabled, and we should clean them up at some future point.

Add fabricbot.json

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/TupleTaskExtensions.cs

Following discussion: https://github.com/dotnet/project-system/pull/8216#pullrequestreview-992880814
When two async tasks can be run concurrently, we should run them that way to reduce overall time. The usual way of doing this is not very ergonomic (see below). Allowing a tuple to be awaited is quite nice. Examples follow.
This is slower than it needs to be as the second task cannot start until the first completes.
```c#
var result1 = await DoSomethingAsync();
var result2 = await DoAnotherTaskAsync();
```
This runs both tasks concurrently, but is harder to read than before.
```c#
var task1 = DoSomethingAsync();
var task2 = DoAnotherTaskAsync();
await Task.WhenAll(task1, task2);
var result1 = await task1;
var result2 = await task2;
```
This commit enables awaiting a tuple of tasks. The …

Add extension for awaiting tuples of tasks

---

build/import/VisualStudio.props
build/import/VisualStudioDesigner.props
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WPF/AppDotXamlDocument.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WPF/ApplicationXamlFileAccessor.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ApplicationFrameworkValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/CreateOrOpenApplicationXamlValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/WPFValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/PageItemEnumProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PageItemRuleProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hant.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/WPF/IApplicationXamlFileAccessor.cs

Related to #7379.
1. Update the `AppDotXamlDocument` type to support reading and writing the "Startup URI" and "Shutdown Mode" properties. This also involves a change to return `null` when one of these properties is not set in the file, rather than the empty string. This lets the caller distinguish between the value not being set, and being set to an actual empty value.
2. Introduce an `IApplicationXamlFileAccessor` interface and related implementation to manage access to a project's Application.xaml file. This type handles loading the Application.xaml file into a `DocData`, managing the lifetime of the `DocData`, and creating the `AppDotXamlDocument` as needed.
3. Add the `WPFValueProvider` interceptor that uses the `IApplicationXamlFileAccessor` to expose "Startup URI" and "Shutdown …

Add WPF-related properties

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectCapability.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ProjectFileInterceptedProjectPropertiesProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ProjectFileInterceptedViaSnapshotProjectPropertiesProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/UserFileInterceptedProjectPropertiesProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/UserFileWithXamlDefaultsInterceptedProjectPropertiesProvider.cs

Non-.NET projects want to be able to use the property infrastructure, such as .esproj.
Today, they're unable to use property interception because they don't define the .NET project capability.
This change introduces a new capability for these features, and adds that capability to managed projects. This allows other (non-.NET) project types to add this capability to their own design-time targets.

Add project capability for the property system

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckBuildEventNotifier.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Subscription.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/IBuildUpToDateCheckProviderInternal.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

Fixes #8231
Fixes [AB#1550661](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1550661)
The fast up-to-date check tracks the set of configurations that are built, in order to remember the time of the last successful build in each configuration.
This needs to be tracked per-configuration because we support single-target builds, for MAUI for example.
Previously, we weren't tracking the last set of configurations in the case of rebuilds. This change corrects that.

Track project configurations during rebuilds

---

setup/Directory.Build.targets

There seems to have been a change that happened between Wednesday (8th) and Friday (10th) last week that is a breaking change for the ManifestGeneratorTask DevOps task. This is causing our build to fail.
When setting up the task, you can specify a value for `ManifestDirPath` which sets where the manifest will be output. The default value for this parameter is `${BuildDropPath}/_manifest`. What has happened is specifying our own `ManifestDirPath` instead of outputting to the directory we specified, now outputs to `${ManifestDirPath}/_manifest`. Meaning, it will always output to a subdirectory of `_manifest` no matter what value you set for the parameter.
I've let VS Eng know that this was changed as it seems like a bug. For now, we can simply change the SBOM script I have to look in the …

Fix SBOM manifest directory

---

src/Microsoft.VisualStudio.Editors/DesignerFramework/AccessModifierComboBox.vb
src/Microsoft.VisualStudio.Editors/DesignerFramework/DesignerMenuCommand.vb

- Remove unused code in `AccessModifierCombobox.TrySetCustomToolValue`()
- Rename `ImposterDesignerMenuCommand `to `DummyDesignerMenuCommand`
It seems project system doesn't use the concept of _imposter_ 
- Set proper camel capitalization to local variables
- Rename some local variables to give more context
- Rename `GetCurrentValue()` to `GetCurrentAccessibilityValue()`
- Rename `SetCurrentValue()` to `SetCurrentAccessibilityValue()`
- Order methods in chronological order
----------
Note: all this code cleanup is to make `AccessModifierComboBox` more readable
why? Prepare the code to fix [AB#1243638](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1243638) in another pr.

Code cleanup in AccessModifierCombobox

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IIncrementalBuildFailureReporter.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureDetector.ProjectChecker.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureOutputWindowReporter.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureTelemetryReporter.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckStatePersistence.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/Delimiter.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Log.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/IBuildUpToDateCheckValidator.cs

The previous incremental build failure warning message did not include a detailed reason for not being up-to-date. This change adds that description to assist diagnosis.
> WARNING: Potential incremental build failure in 'WebApplication52.csproj'. See: https://aka.ms/incremental-build-failure
> WARNING: Potential incremental build failure in 'WebApplication52.csproj'. Input 'C:\Users\drnoakes\source\repos\WebApplication52\WebApplication52\WebApplication52.csproj.user' (2022-06-10 22:23:38.773) has been modified since the last successful build started (2022-06-10 22:23:38.695), not up-to-date. See https://aka.ms/incremental-build-failure.

Improve incremental build failure message

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WindowsForms/MyAppDocument.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WindowsForms/MyAppFileAccessor.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ApplicationFrameworkPropertiesValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ApplicationFrameworkValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hant.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/WinForms/IMyAppFileAccessor.cs

WinForms project have specific Applcation Framework properties that need to be read and saved in the corresponding Application.myapp file. For now, we will intercept those properties via the `ApplicationFrameworkPropertiesValueProvider`, but ideally we would like to implement a `IProjectPropertiesProvider` to access the myapp file.
Addresses #7236.

Intercept WinForms properties

---

src/Microsoft.VisualStudio.Editors/DesignerFramework/AccessModifierComboBox.vb

Fixes [AB#1243638](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1243638) 
Scenario: 
When a user has any C# project type, containing more than two nested folders and a resX file located inside the nested folder. If the user opens the resX file, and keep it open while the user moves (drag & drop) the resX file from the folder to the root of the project, cps will throw the exception `KeyNotFoundException` because item id is invalid. 
This is a limitation of Cps. In some cases Cps is not able to maintain the same item id for items, causing them to not be found.
In some scenarios (i.e., when the item is moved), it ends up having a different id, so the older one can't be found anymore.
Since this is not easy to fix in Cps, and it is better to handle this …

Handle exception when a resx file is moved from a folder to root

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hant.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.zh-Hant.xlf

We had a typo in the property `DefineTrace` and a request to remove XP from the `EnableVisualStyles` property's DisplayName.

Small edits on DisplayNames

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureDetector.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/SolutionBuildManager.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/AsyncDisposable.cs

Some improvements to how we register and unregister from solution build events.
These follow investigation into the crash described in [AB#1535665](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1535665).
That crash comes from some native code and it's unclear to me whether the changes here would influence that crash at all, but these changes do improve our correctness by:
1. Avoiding a double-dispose that might potentially request unadvise more than once
2. Ensuring that exceptions don't stop us treating our pair of subscriptions in such a way that one of the two is left dangling
3. Not unadvising events if we somehow have a nil cookie

Better hygiene for solution build event subscriptions

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.VisualBasic.xaml

We can hold from showing these 3 new properties from the UI until we have the correct logic in place in the code generator for the Application.Designer.vb that will come in 17.4.
This is how it would look like:
Note: we agreed that it was okay to hide these 3 properties as they weren't surfaced in the old experience, and we want to ensure the end-to-end scenario works before introducing them.

Hide new properties from Application Framework category.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml

Currently, the property only shows up if the following condition is satisfied: `(has-evaluated-value "Build" "PlatformTarget" "AnyCPU")`
However, even though the value is saved to the csproj as AnyCPU, the actual unevaluated/evaluated value of AnyCPU is _Any CPU_. This change simply renames AnyCPU to Any CPU in the visibility condition.
Fixes #8016

Make sure Prefer 32 Bit property is appearing when it should

---

build/import/Packages.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/LaunchProfileActionBase.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyDataProducer.cs

This is a compliment to [this](https://devdiv.visualstudio.com/DevDiv/_git/CPS/commit/411f55af22664adfdb61c1591c61c7cde9f9837d) CPS commit that adds EditabilityCondition as UIProperty metadata. It passes the EditabilityCondition back to CPS, including on launch pages.

Update CPS version, pass EditabilityCondition metadata back to cps

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf

The previous message could be interpreted as meaning the build failed in some way. This message should make the nature of the warning more obvious.
Thanks @y87feng for the feedback on this.

Improve the incremental build warning message

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Runtimes/NetCoreRuntimeVersionsRegistryReader.cs

Fixes [AB#1552807](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1552807).
The project system tries to check if projects in the solution depend on a version of the .NET runtime that isn't installed, and if so pops up a gold bar with a link to the appropriate component in the VS installer. As part of this, the `NetCoreRuntimeVersionsRegistryReader` attempts to find globally-installed .NET runtimes (that is, runtimes installed _outside_ the VS installer) by enumerating registry keys under a well-known path.
It turns out this path is correct on an x64 system, but not on an ARM64 system. The end result is that even if you have, say, the .NET 5.0 runtime installed on your ARM64 system we won't properly detect it, and we'll incorrectly pop up the gold bar. …

Check correct registry key on ARM64

---

version.json

Documentation here: https://github.com/dotnet/Nerdbank.GitVersioning/blob/main/doc/versionJson.md#file-format
Public package feed (for reference): https://dev.azure.com/azure-public/vside/_artifacts/feed/vs-impl/NuGet/Microsoft.VisualStudio.ProjectSystem.Managed
This removes `publicReleaseRefSpec` for `main` from the `version.json` since we don't actually create non-prerelease `.nupkg` currently. Creating non-prerelease packages causes the build to fail as we rely on prerelease packages. The way NuGet pack works is that *release packages cannot depend on prerelease packages*. Removing  `publicReleaseRefSpec` from `version.json` will only affect the `.nupkg` version number and no other version numbers in the build. I checked that interaction by looking the build I did yesterday from the …

Set .nupkg version as prerelease

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/SharedProjectDependencyModel.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/SharedProjectDependencyModelTests.cs

Fixes #8305
Relates to #8045 and #8202
In 17.2, CPS made a change to how paths are used for non-file items in the tree. These changes improve the performance of searching the dependency tree by path, as the pseudo-id used for items not having paths allows a fast lookup.
As these shared project dependency tree items were created without the `ProjectTreeFlags.FileSystemEntity`, they were not having their `IProjectTree.FilePath` property populated, which meant that attempts to manually remove the shared project reference from the project failed, as the item to be removed could not be identified.
This change adds a flag to these items so that the `FilePath` property is populated, which allows removal to occur correctly.

Fix broken removal of shared project references

---

.github/ISSUE_TEMPLATE/branch-checklist.md
eng/pipelines/official.yml

Prerequisite PR: https://github.com/dotnet/project-system/pull/8328
Our new version numbering (via [Nerdbank.GitVersioning](https://github.com/dotnet/Nerdbank.GitVersioning)) will not change the version number if there are no new commits in a build. When running our [official pipeline](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=9675), this will cause the build to fail as it will try to publish the package again to the `azure-public` feed. To avoid this failure, we use `allowPackageConflicts: true` which tells the task not to fail when a *409 Conflict* occurs when it tries to upload the same package again. We had this flag on for our `DevDiv/VS` publish, but not our `azure-public` one.

Fix duplicate package publish

---

docs/feature-comparison.md

[This link](https://msdn.microsoft.com/en-us/library/0y92k2w2.aspx) is very old and has slow redirection. Updated to have [current link](https://docs.microsoft.com/previous-versions/0y92k2w2(v=vs.140)) directly to the doc.

Old (slow) link causes intermittent link check failures

---

.editorconfig
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Workspace.cs

Follows from #8321
Previously the code intended to make build updates wait for the application of initial evaluation data had two problems:
1. The `await` occurred within the `ApplyProjectBuild` callback provided to `OnProjectChangedAsync`, however that method attempts to dereference the `ContextId` which is invalid until the first evaluation data has been applied. This commit moves the `await` earlier to prevent this.
2. The `ApplyProjectBuild` callback was `async void` which is an anti-pattern in general. In this particular case, it broke the expectation that a lock is held throughout the operation, as the first yield within the async method would return control to the caller, which would then release the lock while the remainder of the `async void` method continued unprotected.

Fix scheduling of evaluation/build data application

---

.github/workflows/markdown-link-check-config.json

The https://github.com/dotnet/roslyn-tools/blob/main/src/GitHubCreateMergePRs/config.xml link from [branch-checklist.md](https://github.com/dotnet/project-system/blob/main/.github/ISSUE_TEMPLATE/branch-checklist.md) intermittently is getting a 406 response. We'll just ignore it. Also reduced whitespace to make reading the patterns easier.

Ignore intermittent 406 response on markdown link

---

eng/eng.shproj

Fix shared project after rename from "build" to "eng"

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsJsonEncoding.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsJsonEncodingTests.cs

Fixes #8360
Other settings do not always need to have string values. Docker Compose projects use arrays here. This used to work, and was broken during a rewrite of the JSON parsing code.
This commit fixes the issue and extends our test coverage to ensure it doesn't regress again in future.

[17.4] Fix launch profile JSON parsing

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WindowsForms/MyAppFileAccessor.cs

This PR modifies the MyAppFileAccessor to check if the Application.myapp file exists in the project when obtaining a MyAppDocument instance (when reading/setting a property). If none exists, one is created with the contents being the default winforms template.
Fixes #8258

Create Application.myapp if none exists during property access/set

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsJsonEncoding.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsJsonEncodingTests.cs

Fixes #8360
Other settings do not always need to have string values. Docker Compose projects use arrays here. This used to work, and was broken during a rewrite of the JSON parsing code.
This commit fixes the issue and extends our test coverage to ensure it doesn't regress again in future.

[17.3] Fix launch profile JSON parsing

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureDetector.IProjectChecker.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureDetector.ProjectChecker.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureDetector.cs

Previously, we assumed that all builds we were checking for incremental build failures were building the active configuration.
This is not always the case. For example, when publishing an application, you can configure the publish to occur in "Release" configuration, while VS's active configuration is "Debug".
The prior discrepancy could potentially cause us to incorrectly identify builds that occur for publish to have incremental build failures.
This commit fixes that by obtaining the specific `ConfiguredProject` being built via the `IVsCfg` object passed via the Solution Build Manager to our build event handler.

Ensure incremental build failure checks use correct configuration

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

Fixes #8342
If a project has disabled the fast up-to-date check, we should not be validating the correctness of its incremental build.
> WARNING: Potential build performance issue in 'Foo.csproj'. The project does not appear up-to-date after a successful build: The 'DisableFastUpToDateCheck' property is 'true', not up-to-date. See https://aka.ms/incremental-build-failure.
```
Build started...
1>FastUpToDate: The 'DisableFastUpToDateCheck' property is 'true', not up-to-date. (NoTargetsProject)
1>FastUpToDate: Up-to-date check completed in 0.2 ms (NoTargetsProject)
1>------ Build started: Project: NoTargetsProject, Configuration: Debug Any CPU ------
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

Don't fail incremental build validation when disabled

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.ItemHashing.cs

Current implementation of `GetStableHashCode()` is broken for Linux or Mac (depends on UTF-8 strings) while the CLR may have chosen to stick with Utf16.
Removing the unsafe codes removes the dependency upon the internal representation of the string in memory.
This is to make it work correctly on any platform.
-----------------------------
Benchmark
|                   Method |     Mean |     Error |    StdDev |
|------------------------- |---------:|----------:|----------:|
| GetStableHashCodeUnsafe | 7.068 ns | 0.1463 ns | 0.1796 ns |
| GetStableHashCodeSafe | 9.247 ns | 0.1851 ns | 0.1641 ns |
| CalculateStringGetHashCode | 6.655 ns | 0.1581 ns | 0.2110 ns |

Removing the unsafe code from the stable hash algorithm.

---

src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorTelemetry.vb
src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceFile.vb

This causes events for:
- Load (including the number of resources)
- Add / Rename / Change / Remove (including the friendly type name of the resource, such as `System.String`)

Add basic telemetry on resource editor usage

---

.gitattributes
eng/imports/Packages.targets
nuget.config

This is part of an effort for [Central Feed Services (CFS)](https://eng.ms/docs/cloud-ai-platform/developer-services/one-engineering-system-1es/1es-docs/secure-supply-chain/project-artemis/central-feed-services-cfs). The tooling they make for validating feeds being used in a repo rely on a `nuget.config` file at the root. I've moved our feeds from being declared in `RestoreSources` in Packages.targets to a nuget.config at the root. Currently, public feeds in Azure DevOps do not support upstream sources, so this won't be consolidated to a single feed yet.
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6542168&view=results

Use nuget.config instead of RestoreSources

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/FeatureFlags.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/NuGetRestoreCycleDetector.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UI/InfoBarService/IInfoBarService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UI/InfoBarService/InfoBarUI.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UI/InfoBarService/InfoBarUIKind.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UI/InfoBarService/VsInfoBarService.InfoBarEntry.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UI/InfoBarService/VsInfoBarService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/IVsShellServices.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/VSShellServices.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryEventName.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PackageRestore/PackageRestoreDataSourceTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PackageRestore/Snapshots/PackageRestoreDataSourceMocked.cs

Fixes #8326
Avoid infinite NuGet restores.
Scenario:
Projects might have a package that sets `AssetTargetsFallback` value that can cause a certain `PackageReference` to be included. This package contains a props file that changed the `AssetTargetFallback` property value, and the `PackageReference` Condition was no longer true, causing it to be removed. Once removed, the `AssetTargetFallback` value from the `csproj` was used again, causing an infinite restore -> design time build -> restore loop.
This change:
Since DotNet ProjectSystem can detect changes in NuGet restores by calculating a hash, we can use this hash to detect changes in `AssetTargetFallBack` and check when this value gets repeated.
This pr makes use of the `NuGetRestoreCycleDetector` to keep the last N hashes, and once it …

Avoid NuGet restore cycles

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.zh-Hant.xlf

Fixes #8244 😄 we just forgot to put descriptions for these properties, so when there is no variance, no description can be shown (leading to no checkbox context)

add descriptions to BuildPropertyPage.VisualBasic.xaml BoolProperties

---

src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsSingleFileGeneratorBase.vb

To fix https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1589004?src=WorkItemMention&src-action=artifact_link, we need to add "My" namespace to the MySettings class. 
This works for .net framework 4.8 VB, as well as .net core VB and .net core C#, but before approving it, another pair of eyes on the generated file would be nice

add "My" namespace to generated settings type

---

src/Microsoft.VisualStudio.Editors/MyApplication/MyApplicationCodeGenerator.vb
src/Microsoft.VisualStudio.Editors/MyApplication/MyApplicationData.vb
src/Microsoft.VisualStudio.Editors/MyApplication/MyApplicationDataSerializer.vb
src/Microsoft.VisualStudio.Editors/MyApplication/MyApplicationProperties.vb
src/Microsoft.VisualStudio.Editors/PublicAPI.Unshipped.txt
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ApplicationFrameworkValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hant.xlf

Relates to #8283, where we hid this property as we were not ready with the code generation part.
This PR consists of two commits:
- In the first one, we make the property visible in the UI. Additionally, we simplify the way the enum values are stored: instead of translating from integer to string and back again, we only keep the integer that represents the value. Later in the code generation, we will translate to the proper string, as that's the point in time where we actually need it.
- In the second one, we make the proper changes to read/write from the xml file (App.myapp file), save it into a property and later use its value to generate the necessary code for the Application.Designer.vb file. Note that we had to implement an override function for the `AddFieldAssignment`: we are not …

Enable HighDpiMode property in the Project Properties UI.

---

src/Microsoft.VisualStudio.Editors/PublicAPI.Shipped.txt
src/Microsoft.VisualStudio.Editors/PublicAPI.Unshipped.txt

Code cleanup.
After I updated my local dotnet project system repo, and build it solution the file PublicAPI.Shipped.txt was modified to add some missing apis.
Perhaps this was part of a previous change.

Add missing public api to PublicAPI.Shipped.txt

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/LanguageServiceHostEnvironment.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/ILanguageServiceHostEnvironment.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs

Fixes #3832.
When VS is running in command line mode (i.e. `devenv.exe /build`) we don't need to fire up the language service.

Don't activate the language service in command line mode

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/DebugProfileDebugTargetGenerator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsChangeTracker.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcher.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.SnapshotUpdater.cs

Handles #8411, #8410 
This is useful when identifying root cause of problems from NFEs.
cc: @lifengl

Add names to broadcast blocks missing a name

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractFindByNameUnderAppDesignerSpecialFileProvider.cs

It is confusing this is not an abstract class

Mark AbstractFindByNameUnderAppDesignerSpecialFileProvider as an 'abstract' class.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/StartupObjectValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/StartupObjectsEnumProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WindowsForms/MyAppFileAccessor.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ApplicationFrameworkValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hant.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/WinForms/IMyAppFileAccessor.cs

Note: this PR has the same initial commits already reviewed as #8355. Please review the last commit.
The `StartupObject` property has a different behavior compared to the C# experience. This setting doesn't get serialized exclusively to the project file; in certain scenarios, it also needs to be serialized into the myapp file.
**Scenarios**
- If the `ApplicationFramework` is enabled, the value `Sub Main` should be serialized to the project file.
- If the user chooses a Form from the dropdown, this setting gets serialzed into the myapp file, which then generates the `Application.Designer.vb` code with the selected Form.
- If the `ApplicationFramework` is disabled, these settings get serialized into the project file.
We have been showing a correct set of values in the dropdown. The expected …

Intercept StartupObject property for VB WinForms projects

---

eng/pipelines/pull-request.yml

This change is required for builds to continue working in the new org, dev.azure.com/dnceng-public.

Update public pool names

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/FileMoveNotificationListener.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/RenamerProjectTreeActionHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsToolsOptions.cs

Fixes #8441 
Fix wrong behavior in Enable symbolic renaming
if "Don't show again" is checked,
--  then persist UNcheck "prompt for symbolic renaming when renaming files"
-----   if "Yes", then persist check "enable symbolic renaming when renaming files"
-----   if "No", then persist UNcheck "enable symbolic renaming when renaming files"
If "Don't show again" is UNchecked, don't make changes to persisted values.

Fix wrong behavior in Symbolic Renaming prompt

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs

Fixes [AB#1594395](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1594395)
Fixes [AB#1597595](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1597595)
This code path was missed during recent work on the language service. We must ensure that Roslyn's `IWorkspaceProjectContext` objects are disposed when the project is unloaded.

Dispose Roslyn workspaces when project unloads

---

eng/pipelines/templates/analyze-api.yml

Added a retry with timeout mechanism to APIScan task. This task has been timing out recently (going beyond 90 mins). Here, I remove the timeout for the job itself and instead, add a 2 hour timeout for the APIScan task, with the retry count of 2. This means it'll run 3 times total before failing.
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6660256&view=results

Add APIScan retry mechanism

---

eng/pipelines/templates/analyze-api.yml

Made it so ApiScan will actually retry now. Also made it so that if it fails, the failures are ignored.

APIScan with retries and ignoring failure

---

eng/pipelines/templates/analyze-api.yml

Made it so ApiScan will actually retry now. Also made it so that if it fails, the failures are ignored.

APIScan with retries and ignoring failure - 17.4-preview2

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Workspace.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceFactory.cs

Fixes [AB#1586247](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1586247)
In the language service host, we need to process evaluation data before design-time build data. We need an evaluation to create the Roslyn workspace object, and we need that workspace to apply build data.
In practice, build data can arrive first. This may be due to caching, for example. We see this unexpected ordering more on perf lab machines too, interestingly.
The previous code didn't handle the out-of-order case correctly. If build data arrived first, it would block waiting for evaluation data. However the upstream TPL action block serialises callbacks, so any future update that might unblock the build data handler cannot run, leading to deadlock.
The fix here uses a …

Ensure the first workspace update is from evaluation

---

Directory.Build.props
eng/imports/HostAgnostic.props
eng/imports/Packages.targets
src/Microsoft.VisualStudio.Editors/Microsoft.VisualStudio.Editors.vbproj
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj

Fixes: https://github.com/dotnet/project-system/issues/5619
Adds the SourceLink functionality to our NuGet packages. It also makes our build marked with the deterministic flag.
I used the [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) to verify the packages. When they started, they looked like this:
I enabled SourceLink but it was still showing issues. Seems I needed the `EmbedUntrackedSources` setting.
After adding `EmbedUntrackedSources`, the build was broken. After some investigation, I found an issue that was reported for the problem, but no workaround: https://github.com/dotnet/sourcelink/issues/492 \
I looked into how the generated `.g.cs` files wanted to reference the `.xaml`. Then, I determined how to output them to that path. I added those …

Add SourceLink to NuGet packages

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Workspace.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceFactoryTests.cs

This is the 17.4p2 version of #8475. See that PR for a description.

[17.4p2] Ensure the first workspace update is from evaluation

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/DependenciesTreeConfiguredProjectSearchContext.cs

Fixes [AB#1613079](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1613079)
That feedback ticket showed a stack overflow when populating the parent items of a given search hit. While I do not yet have a repro for the bug, it appears this would only have been possible if an item was its own parent. I do not know how this might occur in practice, but we should defend against it in theory.
The fix here is to ensure that the `ContainedByCollection` property is non-null earlier, as we test this property on the parent to see whether we need to recur. If the parent and the child were the same, previously we would have seen a null and invoked the recursion. With this change, we set the value to non-null before walking parents, which prevents this error.

Fix stack overflow in dependencies tree search

---

README.md
eng/scripts/GetMSBuildPath.ps1
setup/Directory.Build.props

Resolves: https://github.com/dotnet/project-system/issues/8319
- Remove the recommendation and inclusion of [Visual Studio Build Tools](https://visualstudio.microsoft.com/downloads/?q=build+tools#build-tools-for-visual-studio-2022) as an option for building the repo.
- This was decided in the linked issue above to be our desired outcome, since users can install VS Community edition for free if they want to build our repo.
- Set DeployExtension to only happen locally.
- This was pointed out by @wade0016 to save time on CI builds, since deploying the extensions we build (to the experimental hive) are not used by the CI machines in any way.

VS Build Tools 'removal' + no longer deploy to exp-hive in CI

---

eng/pipelines/pull-request.yml

Remove excluding certain paths that only contain changes in a PR. 
@tmeschter ran into [this situation](https://github.com/dotnet/project-system/pull/8440#issuecomment-1238817230) recently with some PRs where the only changes were document related. The issue is, the PR pipeline was filtering out running builds for that situation; but running the PR builds is a `required` check. Thus, the PR is never able to be 'green'. To merge, he had to override the checks and merge it manually. The situation looks similar to this:
After some research, I found the recommended solution for this: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks …

Path exclusion removal for PRs

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsSolutionEventListener.cs

There are currently two places we might attempt to set the results on our TaskCompletionSource. I've observed, in a debugger, an exception when we set this state twice.
This change uses `TrySetResult` rather than `SetResult`, as the former will not throw an exception if a result has already been set (or the result cancelled/faulted).

Fix potential exception handling solution events

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceFactoryTests.cs

#8475 added new logic to correctly order workspace update objects between separate evaluation and build data sources.
This change adds unit tests for the new code to verify it works correctly. No change to the implementation was required, beyond extracting an internal method so the test could call it.

Add unit tests for new workspace update ordering logic

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureOutputWindowReporter.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureTelemetryReporter.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsCompiler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/DesignTimeTelemetryLogger.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/VsTelemetryService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependencyTreeTelemetryService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/SDKVersionTelemetryServiceComponent.SDKVersionTelemetryServiceInstance.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Log.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryEventName.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryPropertyName.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Telemetry/VsTelemetryServiceTests.cs

Previous code used string concatenation and helper functions to create name strings for telemetry events and properties.
This meant that it wasn't possible to search for the full event name and find the source code that produced it.
With this change, telemetry event names and their property names appear as full string literals in the source code and are easily found during search.
This also removes the `BuildPropertyName` method, so that there's no runtime computation of these strings when the type loads during VS start.
I also broke the telemetry property names class up into smaller nested static classes to provide some kind of namespacing on these property names.

Use full-form literals for telemetry const strings

---

.github/ISSUE_TEMPLATE/branch-checklist.md

The `..` syntax does not render correctly on GitHub as a way to reference source files in the repo.

Fix broken links in issue template

---

src/Microsoft.VisualStudio.Editors/MyApplication/MyApplicationCodeGenerator.vb
src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsSingleFileGeneratorBase.vb
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.VisualBasic.xaml

This includes two fixes, as noted in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1591002/
1: HighDpiMode is not a valid property name for some netframework versions. It needs to be removed.
2: The generated My.Settings() property (shown below) was missing the "My" identifier if generated in a VB project. This has now been added
This has been tested for:
WPF netframework VB: yes
WinForms netframework VB:
WPF netcore VB: yes
WinForms netcore VB: yes
WPF netframework C#: yes
WinForms netframework C#: yes
WPF netcore C#: yes
WinForms netcore C#: yes

Myapp and Settings file generator fixes

---

eng/pipelines/official.yml
eng/pipelines/templates/analyze-api.yml
eng/pipelines/templates/analyze-vulnerabilities.yml
eng/pipelines/templates/publish-assets-and-packages.yml
eng/pipelines/templates/publish-richnav.yml

This PR turns APIScan back on. It sets the timeout to 3 hours. So far, I've seen APIScan go above 2 hours, and we're working with a dev to investigate why it is taking so long.
We also had RichNav fail recently because of timing out, but that seems to be a separate issue. To avoid non-critical jobs from causing the entire build to fail, I've marked the following jobs with `continueOnError: true` which allows the build pipeline to continue, even when these jobs time out:
- `analyze-api.yml` (APIScan)
- `analyze-vulnerabilities.yml` (CodeQL, but we don't run this yet)
- `publish-richnav.yml` (RichNav)
I tested that this works by setting APIScan temporarily for a 5 minute timeout. You can see here that APIScan stopped at 5 mins but the next stage (VS Insertion) that requires the Compliance …

Re-enable APIScan and allow timeouts (for certain jobs) to not cause build failures

---

src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorTelemetry.vb
src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceFile.vb

Additional counts for different types of resources, such as strings, bitmaps, icons, audio files and other.
These new properties will need GDPR classification. They do not yet appear in the tool.

Extend resource editor telemetry

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSPackage.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSPackage.zh-Hant.xlf

Reverts dotnet/project-system#8484
An insertion containing this PR is associated with a DDRITs regression, blocking the insertion.
The image `Microsoft.VisualStudio.ProjectSystem.Managed.VS.ni.dll` is being loaded in _ManagedLangsVS64.AddNewProject.0100.Add New Project_ and _UWP64.ProjectManagement.0200.Xaml Designer Load_, where it was previously not loaded.
I'll create an insertion attempt with this reversion and monitor it. If the regression persists, we'll try reverting #8438 as well.

Revert "Remove unused template resource strings"

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IWorkspaceFactory.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Workspace.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceTests.cs

Fixes [AB#1600170](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1600170)
When project system components outside the language service host want to write to the Roslyn project context, we block those operations until the `Workspace` object is initialised with both evaluation and build data.
This state is signalled via a `TaskCompletionSource`, unblocked by the arrival of the first build data for that project slice.
Previously we used `JTF.RunAsync` in an attempt to join work between components that acquire a lock over the `Workspace`. That does not correctly join the two operations. What we need to do is temporarily join the `JoinableTaskCollection` used within the dataflow handling logic. This allows dataflow to keep pumping on the main thread, even …

Avoid deadlock between CodeModel API and build data

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs

Fixes [AB#1597866](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1597866)
When slices change, we receive updates to both the slices and the active configured project, from two separate data sources that we sync link. That sync link does not actually ensure the active configured project has a corresponding slice in the linked data.
Fixing that in CPS will likely be expensive. This commit introduces a workaround. When the active workspace is removed from the project, we set the workspace associated with the first slice provided as primary instead. This way, we will not have a null primary workspace, and therefore not encounter the bug in the linked issue.

Workaround incorrect active configured project data

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/CreateOrOpenAppManifestValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hant.xlf

This PR adds a string property with a LinkAction editor to create or open the appmanifest file with the Windows Settings, in order to keep the previous experience:
[CPS-side PR](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/423880) to hook this action the LinkActionHandler.

Create hyperlink button to create or open the app manifest file.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs

Any caller of `IWorkspaceWriter.WhenInitialized` from the main thread could conceivably hit a hang with the prior code. We are not aware of any instances of this occurring, however.
This fix ensures that any JTF work scope of the caller is joined with the language service's own dataflow JTF work, such that the main thread may be shared between both work streams, allowing forward progress.

Fix potential hang in language service

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/LanguageServiceErrorListProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IWorkspaceWriter.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IWorkspaceWriterFactory.cs

Fixes #8500
In some cases the language service host environment may signal that language services should not be enabled. Command line mode /build is an example of this.
Users of the language service receive exceptions when attempting to use its APIs when it is disabled.
This change allows callers to validate that the language service is enabled in order to avoid such exceptions.
---
#8502 tracks using project capabilities instead of this manual check. As part of that work, we would revert this change, instead updating the project capabilities on `LanguageServiceErrorListProvider` itself (or just making the `LanguageServices` capability dynamic).

Prevent exception when language service not enabled

---

Editors.slnf

Editors are kind of independent project from dotnet project system, and we can treat them independently.

Add a solution filter for editors only

---

docs/repo/property-pages/property-specification.md

Code cleanup to add `UserFile` and `LaunchProfile` to the documentation.

Add missing documentation for possible values in properties Persistence

---

eng/imports/Packages.targets
eng/tools/OneLocBuildSetup/OneLocBuildSetup.csproj

Remove some PackageReferences items added in c71988886996789cd3b3b8c6d1f781110da559f6. Older versions of the NuGet.VisualStudio package depended on these, but they duplicated assemblies that we pulled in from other (more official) packages. This led to double-writes during build, where two files from different locations (but the same name and ostensibly the same content) would get copied to the same destination. This is undesirable as--at best--all but one of the copies are pointless. At worst you get an unstable build where which one "wins" is non-deterministic. By declaring our own PackageReferences to these with `ExcludeAssets="All"` we can prevent the build from copying files out of these packages.
The downside is that this adds package dependencies we don't actually need, and is …

Remove unnecessary PackageReferences

---

eng/pipelines/official.yml
eng/pipelines/templates/build-official-release.yml

Resolves: https://github.com/dotnet/project-system/issues/8421
[CodeQL](https://github.com/github/codeql) is an analysis tool for vulnerabilities. This PR is enabling a version of a CodeQL AzDO task called [CodeQL 3000](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/configuring-codeql3000-ado-pipelines). There is another CodeQL task created by Guardian (same set of tools for the rest of our compliance checks), but this is not that task. This CodeQL task is auto-injected into the pipeline (a dynamic task that is not directly declared in the pipeline YML).
Unfortunately, I cannot directly test the auto-injected run of this task. [According to the documentation](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/con …

Enable CodeQL 3000

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredProjectsLoader.cs

It wasn't obvious to me why we required the ".NET" and "LanguageService" project capabilities to be present on the project in order to load its configurations.
I asked @davkean who explained this is to prevent loading configurations of shared projects.
I've captured that information here for future.

Document project capability on configuration load

---

tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceTests.cs

In #8498 we changed the required conditions for initialisation of a language service workspace. This unit test should have been updated at the same time. For some reason, the CI build for that PR passed.
This change updates the test to reflect the new behaviour.

Fix unit test

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredProjectsLoader.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DataflowUtilities.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/ActiveConfiguredProjectsLoaderTests.cs

Components like the NuGet restore (only do restore when all target frameworks are available) can benefit from this data.
This is one part of the fix for #7288.

Publish loaded configured projects

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsJsonEncoding.cs

Fixes [AB#1599326](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1599326)

Fix launchSettings parser to read date as string in environment variables

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsJsonEncoding.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsJsonEncodingTests.cs

This is an alternative to #8530 that modifies the default JSON.NET behaviour of deserialising a string containing an ISO format date as a `System.DateTime` rather than `System.String`.
Also adds a unit test.

Disable date deserialisation in launchSettings.json

---

src/Microsoft.VisualStudio.Editors/PropPages/compileproppage2.resx

Partially fixes the accessibility issue here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1614439
If the screen resolution is low and/or window scaling is high, condition and notification table in "Compile" property page can get too small: enough to disappear completely.
This PR makes sure that the table is at least 200 pixels high.

Condition and notification table shouldn't shrink to zero height.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hant.xlf

This string wasn't translated as it was missing from the VB-specific file.
Issue #8552 will ensure this doesn't happen in the future.

Add Resources category to ensure its DisplayName is correctly translated.

---

src/Microsoft.VisualStudio.Editors/PropPages/BuildEventsPropPage.resx
src/Microsoft.VisualStudio.Editors/PropPages/BuildEventsPropPage.vb

**Problem:** On small screens, build events property page won't fit the window. As a result:
- Some parts of the page are clipped,
- Some of the content gets behind the "OK" and "Cancel" buttons, causing an overlap.
**Cause:** The issue is caused by the owner window [PropPageUserControlPage](https://github.com/dotnet/project-system/blob/main/src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPageUserControlBase.vb#L2880), scaling the minimum size of the property page up based on the font:
-> [SetDialogFont(ScaleDialog As Boolean)](https://github.com/dotnet/project-system/blob/main/src/Microsoft.VisualStudio.AppDesigner/PropPages/PropPageUserControlBase.vb#L3541)
-> [MinimumSize = ScaleSize(MinimumSize, dx, dy)](https://github.com/dotnet/project-system/blob/main/src/Microsoft.VisualStudio …

Build events property page buttons shouldn't overlap

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ApplicationManifestKindValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ApplicationManifestPathValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/CompoundTargetFrameworkValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ResourceSpecificationKindValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/TargetMultipleFrameworksValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/GenerateDocumentationFileValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/TreatWarningsAsErrorsValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/VBWarningSeverityValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/InterceptingPropertyValueProviderBase.cs

1. **Avoid allocating task on each call.**
Reuse our singleton instance.
2. **Avoid allocating a copy of the collection.**
The runtime type returned by `GetDirectPropertyNamesAsync` is actually `List<string>`. On my machine it typically has 108 values. Rather than calling `ToArray` to copy it, we can sniff for `IReadOnlyCollection<string>` and use that interface directly.
If the concrete type changes in future, we will fall back to calling `ToList`.

Eliminate some allocations

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Workspace.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceTests.cs

Fixes #8343
There may be projects that do not provide enough information for us to create the workspace. An example of this is `.ilproj`. We should not fault the project in such cases by throwing. Instead, we dispose the workspace which tears down its dataflow and cleans up gracefully.
This restores the behaviour we had prior to the changes made to the language service code to improve performance of configuration switches.

[17.4] No fault when insufficient data to create workspace

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs

We assert that a value is not `DateTime.MinValue`, however we have code that sets that value when the check is disabled.
Using `null` instead fixes a bug that results in:
> System.ArgumentException: Must not be DateTime.MinValue. Parameter name: itemsChangedAtUtc
That exception was thrown in `UpToDateCheckStatePersistence.StoreItemStateAsync` here:
https://github.com/dotnet/project-system/blob/2b89a8976d977f1089dbe7a9df9f03e8a4e07b52/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckStatePersistence.cs#L89
The regression was introduced in 17.3.

[17.4] Fix bug when disabling fast up-to-date check

---

eng/imports/HostAgnostic.props
eng/imports/Packages.targets
src/Microsoft.VisualStudio.AppDesigner/Common/Utils.vb
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/StartupObjectsEnumProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/FileMoveNotificationListener.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/RenamerProjectTreeActionHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/RoslynServices.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Workspace.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IWorkspaceProjectContextFactoryFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceTests.cs

@tmat and I designed a new API for the interaction between the .NET Project System and Roslyn when creating instances of `IWorkspaceProjectContext`.
This new API:
- Allows Roslyn to (generally) request additional properties from the project system, without requiring a corresponding change in the project system.
- Avoids having to create a wasteful batched update immediately after constructing the workspace.
This PR updates the API we use.
Bumping that package pulled the thread on a whole bunch of other package upgrades, including analyzer changes that lead to `.editorconfig` changes, some naming guideline changes, and some suppressions.

Use newer Roslyn APIs in the language service

---

tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceTests.cs

Related to #8592.
This test fails intermittently causing PR and CI builds to fail. Here we disable the test until it can be investigated and fixed.

Skip WriteAsync_CompletesWhenDataReceived

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IUnconfiguredProjectTasksService.cs

The `IProjectAsyncLoadDashboard` interface comes from the VS layer of CPS, but we have a reference to it in a doc comment in Microsoft.ProjectSystem.VisualStudio.Managed.csproj. This removes the reference in order to enforce proper layering.
While I was at it, I updated the affected file to use a file-scoped namespace.

Remove reference to IProjectAsyncLoadDashboard

---

eng/pipelines/official.yml

When testing infrastructure changes, it is common for it to be unnecessary to run compliance checks. To speed up testing, I've added a parameter to skip compliance checks to our `official.yml` pipeline.
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6823223&view=results

Add skip compliance parameter to build pipeline

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs

Relates to [AB#1357805](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1357805)
To avoid hangs, we must ensure that the LanguageServiceHost's upstream data sources are joined.
Thanks to @adrianvmsft for discovering this issue.

[17.4] Join upstream data sources in LanguageServiceHost

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Runtimes/MissingSdkRuntimeDetector.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Workloads/MissingWorkloadDetector.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Workloads/WebMissingWorkloadDetector.cs

Replace a few uses of the `UnconfiguredProject.GetProjectGuidAsync()` extension method with the `ISafeProjectGuidService` instead. The extension method comes from the VS layer of CPS and so we really shouldn't be using it in these locations anyway, and the `ISafeProjectGuidService` ensures that the project has loaded to the point where the GUID isn't going to change after we get it.

Use ISafeProjectGuidService

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/UIImageService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Shipped.txt
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/TypeForwards.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/FileIconProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/IFileIconProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/IUIImageService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Shipped.txt

Refactor `FileIconProvider` type to isolate dependencies with Vs
Move `FileIconProvider` to `Microsoft.VisualStudio.ProjectSystem.Managed` project.
This is part of https://github.com/dotnet/project-system/issues/8576

Refactor ProjectSystem/VS/Tree

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs

Split out of https://github.com/dotnet/project-system/pull/8550 to simplify review.
The action block serialises updates, so they won't overlap. There's no race condition with the dispose method either, as the dispose logic just tears down the dataflow links.

Don't lock for dataflow updates

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreProgressTracker.PackageRestoreProgressTrackerInstance.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreProgressTracker.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/Snapshots/ProjectProperties.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/Snapshots/ReferenceItems.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/Snapshots/ReferenceProperties.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/Snapshots/TargetFrameworks.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/IPackageRestoreDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/NuGetRestoreCycleDetector.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/Snapshots/ImmutablePropertyCollection.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/Snapshots/RestoreData.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IPackageRestoreServiceFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PackageRestore/PackageRestoreProgressTrackerInstanceTests.cs

move Vs independent code to `ProjectSystem.Managed` project.
None of these are public interfaces/classes
This is part of https://github.com/dotnet/project-system/issues/8574

Refactor ProjectSystem/VS/PackageRestore

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Workspace.cs

Split out of #8550 to simplify review.

Add dataflow block name and some API docs

---

src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsDesignerView.vb

DataGrid in Settings property page traps the keyboard and won't allow selecting the link label using tab key.
The fix repurposes the tab key to be used by navigating between other controls in the page while leaving the job of navigating within the data grid to arrow keys.
Before:
Tab key will get you into the data grid and stops functioning after all the cells in the table are traversed.
After:
Tab key will first visit the link label, then go into the table. Pressing the tab key will then move back to the label. To navigate within the table, user will need to use the arrow keys instead of the tab key.

LinkLabel on Settings PropPage should be accessible by tab key

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml

Roslyn recently added a new required property they wish to consume during `IWorkspaceProjectContext` construction. Because this property is listed in our ConfigurationGeneral rule file, any value in the project is not provided to Roslyn when requested, leading to an exception.
This change adds that property so that requests for it will succeed.
This PR is an alternative to #8622 and avoids the use of `ProjectInstance`. Once @lifengl is back in the office, we will discuss whether there is valid cause for concern around the use of `ProjectInstance` as done in that PR.

Add OutputAssemblyForDesignTimeEvaluation property for Roslyn

---

eng/pipelines/official.yml
eng/pipelines/templates/generate-insertion.yml
eng/scripts/GetInsertionPRDescription.ps1

Continuation of: https://github.com/dotnet/project-system/pull/8517
The original solution in the linked PR above did not actually work. The multi-repo trigger mechanism for tagging required that the YAML file also be within the same AzDO org (this is not documented). After explaining this situation to the team, I realized the logic used for the tagging mechanism I made in the previous PR can simply be directly added to the insertion job. Thus, we can create the insertion description without the use of tagging.
The reason I didn't arrive at this solution originally was that checking out the VS repo is quite large and time consuming. Not only that, but we need to checkout up to a certain commit depth so we can find the previous insertion. (*For the sake of this PR, I've set the commit depth …

Create VS insertion description without using tags

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/EvaluationUpdate.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Workspace.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceFactory.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceUpdate.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/LanguageService.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceFactoryTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceTests.cs

Historically, the set of project properties we passed to Roslyn when initialising an `IWorkspaceProjectContext` was hard-coded in the project system. We changed this recently in #8499, and introduced a means for Roslyn to request whatever properties they wanted, allowing Roslyn to make changes without requiring a synchronised change in the project system.
With that change, we serviced property value requests using `ProjectRuleSource` data. This limited Roslyn to only those properties present in our `ConfigurationGeneral` XAML rule file.
This commit uses a `ProjectInstance` to service such requests instead. This means that Roslyn can add new projects in their own props/targets, and not need the project system to make any changes in order to provide those values.
Motivated by a bug exposed …

Allow Roslyn to request arbitrary project properties

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

This indentation makes the output harder to understand as it implies a relationship with the previous line that does not exist.

Remove indentation from log output

---

eng/imports/Packages.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Workspace.cs

Roslyn needs the ability to query item specs during `IWorkspaceProjectContext` construction. This change implements that facility.

Implement EvaluationData.GetItemValues

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

Fixes #8642
Two facts conspired here to motivate this change:
1. Items were stored in data structures that order based on hash codes.
2. Unit tests validate the verbatim log output from the FUTDC to validate correct behaviour.
This means that in different environments, unit tests would enumerate items in different orders and the log output would change in subtle ways, leading to unit test failures.
This change ensures we enumerate (and therefore log) items in a deterministic order. This ensures our tests don't fail in certain environments. It may also help to compare log output between machines/environments/runs for the same project.

Make order of checked items deterministic

---

README.md

The status badges were linking to our previous PR build pipeline, which is odd because that pipeline (AFAIK) didn't build from our branches. It only built via pull requests, which are generated by GitHub. Here, I've opted to use the status of our internal builds, which is more accurately represents our build status. The statuses can be displayed publicly, but to actually follow the links, you need access to the internal project.
I've made them show the primary stages of the pipeline. I decided to not add Optimization and Insertion since those are only ran on a schedule. We can add them if we want. Builds prior to 17.4 will not have this stage information, so they only have the primary pipeline status being shown in the Build column. I've also added the 17.4 branch to the list. And I …

Fix ReadMe status badges

---

docs/launch-flow.md

Add launch-flow.md to document the interaction between CPS, the .NET Project System, the debugger, and the rest of VS when launching/debugging a project.

Add documentation on the launch flow

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Frameworks/SupportedTargetFrameworksEnumProvider.cs

I suspect an earlier version of the codefix for converting from `var` to an explicit type added the `?` everywhere.
Here we remove them to prevent confusion. These values will never be null.

Declare local vars as non-nullable

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs

The previous code would allocate a new ImmutableHashSet on every call to the property's getter. This is essentially constant data, so can be allocated once and reused in order to reduce allocations.
During builds, the property would be called several times per project, per target framework.

Convert property to field to reduce allocations

---

src/Microsoft.VisualStudio.Editors/PropPages/PackagePropPage.resx
src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.cs.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.de.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.es.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.fr.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.it.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.ja.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.ko.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.pl.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.pt-BR.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.ru.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.tr.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.zh-Hans.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.zh-Hant.xlf

Fixes a simple typo.
These are `AccessibleName` values, so would be exposed via UIA, for example to screen readers.

Fix typos in legacy package property page

---

eng/pipelines/official.yml
eng/pipelines/pull-request.yml

Disabling RichNav due to issue with the task. See: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1659507
Disabling this erroring task will no longer cause the build to 'Partially Succeed' which causes scheduled builds to run multiple times on the same commit.
I have details about this, but it was all shared on an internal Teams chat. The errors state how they can't find certain DLLs. The issues started on September 24th 2022 and became completely broken on October 13th 2022. The team I spoke with stated that it is only problematic for GitHub repos.

Disable RichNav

---

docs/repo/property-pages/property-specification.md
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ReferencesPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ReferencesPage.VisualBasic.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ReferencesPage.VisualBasic.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ReferencesPage.VisualBasic.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ReferencesPage.VisualBasic.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ReferencesPage.VisualBasic.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ReferencesPage.VisualBasic.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ReferencesPage.VisualBasic.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ReferencesPage.VisualBasic.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ReferencesPage.VisualBasic.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ReferencesPage.VisualBasic.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ReferencesPage.VisualBasic.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ReferencesPage.VisualBasic.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ReferencesPage.VisualBasic.xaml.zh-Hant.xlf

This PR reverts changes making ImportedNamespaces a StringProperty. This is so we pick up all of the unselected namespaces again.

Revert ImportedNamespaces to use DynamicEnumProperty

---

docs/up-to-date-check.md

In VS17.5 @YuliiaKovalova added support for reference assemblies in legacy CSPROJ projects.
This commit updates our guidance to reflect that fact.

Update FUTDC docs on reference assemblies and legacy projects

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/AggregateContainsRelationCollection.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/LinqExtensions.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectFileClassifier.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/InterceptingPropertyValueProviderBase.cs

This adds an overload for the extension method so that calling code doesn't have to allocate a closure object on the heap. Instead, additional state for the predicate can be passed on the stack.
We also update existing callers to avoid such allocations. This applies primarily in the Solution Explorer and FUTDC (during solution open).

Allow allocation-free Array.Any call

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs

Fixes #8690
See that issue for details on this change. The short version is that we now ignore inputs that come from "non-modifiable" locations such as the NuGet cache, Windows directory and Program Files folders.
```
1>FastUpToDate: Adding AdditionalFiles inputs: (DeployIntegrationDependencies)
1>FastUpToDate:     C:\Users\drnoakes\.nuget\packages\microsoft.visualstudio.sdk.analyzers\16.10.10\build\AdditionalFiles\vs-threading.MainThreadSwitchingMethods.txt (DeployIntegrationDependencies)
1>FastUpToDate:     C:\Users\drnoakes\.nuget\packages\microsoft.visualstudio.threading.analyzers\17.4.16-alpha\build\AdditionalFiles\vs-threading.MainThreadAssertingMethods.txt (DeployIntegrationDependencies)
1>FastUpToDate:     C:\Users\drnoakes\.nuget\packages\microsoft.visualstudio.sdk.analyzers\16.10 …
```

Ignore "non-modifiable" fast up-to-date check input files

---

docs/up-to-date-check.md
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

In 17.2 we added an optimisation for the handling of "CopyAlways" items, so that they would no longer automatically trigger the project to be built regardless of whether the file in question had changed.
Out of caution, we added support for an option to disable this behaviour.
We have had no negative feedback about this feature. Telemetry shows zero usage of this option over the last seven days. This commit removes the option, making the new behaviour non-optional, and simplifying the code a little.

Remove unused option in the FUTDC

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Workspace.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceTests.cs

[AB#1644056](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1644056)
In 17.4 we saw an exception in the dataflow chain that would result in a hang. The cause of that exception has been addressed, however it highlighted a potential hang in the workspace if such an exception occurred during workspace initialisation.
This change hooks dataflow faults and passes those exceptions on to any code waiting for initialisation to complete, preventing a hang and allowing those callers to observe the fault.

Ensure dataflow faults don't hang the language service during initialisation

---

eng/pipelines/official.yml
eng/pipelines/templates/generate-insertion.yml
eng/pipelines/templates/publish-assets-and-packages.yml

We have a few warnings to deal with in our official build.
- After doing an insertion (via `MicroBuildInsertVsPayload`), we need to clear the VS repo files from the build machine prior to the job finishing.
- I've confirmed with VS engineering that we do not need to indefinitely retain our drops we provide via insertion. They modify the retention policy on drops depending on the build the component is inserted into. I've set this duration to ~~30~~ 60 days, which is the recommended duration (from VSEng).
- https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7066598
- Insertion: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/440450?_a=overview

Fix some build warnings

---

tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/ProjectPropertiesRuleTests.cs

In the past, we've received a couple of localization bugs around categories not being localized. This PR adds unit tests to ensure we identify those type of bugs.
Checks:

Add localization unit tests.

---

.editorconfig
src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPageInternalBase.vb
src/Microsoft.VisualStudio.Editors/PropPages/TargetFrameworkMoniker.vb
src/Microsoft.VisualStudio.Editors/PropPages/TargetFrameworks/FrameworkMultiTargetProvider.vb
src/Microsoft.VisualStudio.Editors/PropPages/TargetFrameworks/ISupportedTargetFrameworksProvider.vb
src/Microsoft.VisualStudio.Editors/PropPages/TargetFrameworks/TypeConverterTargetProvider.vb
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Configuration/ProjectConfigurationDimensionProviderTestBase.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Properties/VisualBasic/MapDynamicEnumValuesProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Setup/SwrTests.cs

This is a pattern that comes up in PR review fairly often. It's easy to inadvertently enumerate a lazy sequence more than once in code, which can have undesirable performance characteristics, or produce invalid behaviour.
This change enables an analyzer that catches such issues, and fixes the existing occurrences of it in our code base.

Add analyser to catch multiple enumeration

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/CopyItemAggregator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/ICopyItemAggregator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInputDataSource.cs

Fixes #8721
When the FUTDC is disabled, we don't produce snapshot data for the project therefore we don't have copy items to give to the copy item aggregator.
The previous code had some diagnostic code that would enumerate the copy items. When disabled, this would have the value of `default(ImmutableArray<CopyItem>)` which is not valid for enumeration, leading to a `NullReferenceException`.
This commit removes the diagnostic code, which was intended for removal prior to release. However that diagnostic code actually helped locate the error in this case, as otherwise the enumeration would have occurred quite a bit later, making it harder to identify the root cause.
To ensure this error doesn't occur again, we add some more focussed validation of the argument.
The actual fix is to not call …

Fix exception in FUTDC dataflow when DisableFastUpToDateCheck is true

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs

Fixes #8719
Fixes #8716
`ProjectReference` items can be modified with metadata that modifies how items the project produces are copied to the referencing project's output directory.
This PR improves handling of such metadata, to avoid two problems:
1. Incorrectly expecting certain items in the output directory and scheduling builds (overbuild)
2. Copying too many files to the output directory when using Build Acceleration
Three kinds of metadata are covered here:
1. `Private="False"`
2. `EmbedInteropTypes="True"`
3. `ReferenceOutputAssembly="False"`
Here we filter such projects from the graph.
In reality, the situation is more subtle, as mentioned in the code comment. We will make some additional changes here to improve fidelity in the near future.

FUTDC learns some new metadata on ProjectReference items

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ApplicationFrameworkValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/StartupObjectValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/PropertyNameProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/PropertyNames.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/WPFValueProvider.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectCapabilitiesScopeFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptingProjectProperties/ApplicationPropertyPage/WPFValueProviderTests.cs

Addresses #8436 and [AzDO#1597634](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1597634).
This PR checks for `UseWindowsForms` property before assuming a project is a WPF one. This avoids the scenario where both `UseWPF` and `UseWindowsForms` are set to true and an error message appear when opening the project properties UI, as reported in the linked issues.

Ensure a WPF project does not have UseWindowsForms set to true.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/NameQuotedValuePairListEncoding.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptingProjectProperties/BuildPropertyPage/NameQuotedValuePairListEncodingTests.cs

Fixes [AB#1706419](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1706419)
Removing the Format Exception thrown in the NameValueListPairEncoding as the user cannot enter an input in which this error will be thrown as the intermediate steps feed in such a format where it will not be encountered by a user.

Removing the FormatException thrown for the empty case in the NameValueListPairEncoding

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Log.cs

Recent changes to the FUTDC logging made having a third level of nesting common. We provide special-case prefixes for nesting depths of zero, one or two. This change adds a case for three.
I have no observed any instances of nesting levels of four or below.

Reduce allocations during verbose FUTDC logging

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.FileSystemOperationAggregator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Log.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryPropertyName.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

Captures the status of the Build Acceleration (BA) feature any time the build is up-to-date. May be one of:
- Disabled, not candidate
- Disabled, candidate
- Enabled, not accelerated
- Enabled, accelerated
Builds that are not up-to-date log the reason, some of which could be helped by BA. We don't know for sure in this case however, as the check works differently when it encounters a copyable file depending upon whether BA is enabled or not.
- When enabled and we hit a copyable file, we remember the file and continue checking, then if we get to the end of the file and only have files to copy, we copy them.
- When disabled and we hit a copyable file, we return immediately on the first failure, even if the file was copyable. For that reason, we don't know for sure whether there were other …

Add Build Acceleration telemetry

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets

VSIX projects are not eligible for Build Acceleration, as their build steps cannot be satisfied by simply copying files to the output directory.
Ideally the VSSDK would set this property in their props/targets, however users of older versions of the VSSDK would not pick up this behaviour. By setting it here, we ensure these projects work correctly when Build Acceleration is enabled at the solution level.

Disable Build Acceleration for VSIX projects

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/CopyToOutputDirectoryItem.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.FileSystemOperationAggregator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Log.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/CopyItem.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/CopyItemAggregator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/ICopyItemAggregator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

Contributes to #8733
Build Acceleration is a new feature that requires opt in.
When adding that feature, we started checking a larger number of potential inputs to projects. This included files like the output assemblies of referenced projects, along with their debug symbols and documentation files.
We need to check such files for the Build Acceleration feature, but when it is disabled there is no need to check them and doing so creates additional overhead that makes the FUTDC slower.
This change adds new metadata to those items, `BuildAccelerationOnly`, so the FUTDC can decide whether to check them or not.
That change filters all items from many projects during builds, leading to confusing messages being logged. Quite a bit of the diff here relates to moving logging code around to …

Optimize copy item checking when build acceleration is disabled

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Log.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryPropertyName.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

In current telemetry we report a single duration for the FUTDC. In practice, there are two interesting components to this number:
1. Time spent waiting for project data. The subscription object calls GetLatestVersionAsync for project data, which can take a while.
2. Time spent executing the check itself, iterating over files and so forth.
With this change, we add another measure to our telemetry that captures only the wait time. This will allow us to subtract this from the previously reported number (which we continue to report unchanged) so we can more easily identify wait time versus the check's actual execution time.

Identify FUTDC time spent waiting for project data

---

docs/design-time-builds.md

The table of targets that run during design-time builds was quite out of date. This change updates it and adds some more information.
None of the new entries have a "Normal target" equivalent, so I've removed that detail from the table.
Instead, I've added which component defines the target.

Update documented DTB targets

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

In order to aid discovery of the Build Acceleration feature, we log a message to the console when we believe that a project might be a candidate for acceleration.
This change ensures we only log the message when the project doesn't specify the AccelerateBuildsInVisualStudio property at all. This ensures that we don't suggest the feature for projects that have explicitly opted out of the feature.

Improve Build Acceleration logging

---

eng/scripts/GetInsertionPRDescription.ps1

Our current insertion failed because it couldn't parse the JSON from the insertion description script.
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7154640&view=results
That happened because this commit had backslashes in the commit description.
https://github.com/dotnet/project-system/commit/e259c18f9b5ccdaed5cd50c496fbcde9dd0e9b92
I've added a step to escape backslashes in commit entries. This ignores the correct newlines (\r\n) in the JSON text.
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7156938&view=logs&j=d58a6a34-8c26-597b-aa5c-b9a7e66e5056&t=9f7ffec7-f238-54a1-42ea-53b7cfb882d6
https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/444149?_a=overview

Fix insertion description script for escaping backslashes

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/PackageRestoreSharedJoinableTaskCollection.cs

This satisfies the threading guideline: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/24027/Threading?anchor=%E2%9C%94%EF%B8%8F-**do**-set-%60joinabletaskcollection.displayname%60-to-speed-up-dump-and-hang-analysis
There was only one call to JTC.CreateCollection in our repo that didn't specify a display name. This commit gives it one to assist in future debugging.

Ensure all JoinableTaskCollections have a DisplayName value

---

Directory.Build.props
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Acquisition/MissingSetupComponentRegistrationService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureDetector.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/ISolutionBuildManager.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/ImplicitlyTriggeredDebugBuildManager.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/SolutionBuildManager.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Editor/IRunningDocumentTable.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Editor/RunningDocumentTable.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckBuildEventNotifier.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckStatePersistence.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsSolutionEventListener.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ISolutionService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Utilities/AsyncDisposable.cs

There are two definitions of `IAsyncDisposable`:
1. `System.IAsyncDisposable`
2. `Microsoft.VisualStudio.Threading.IAsyncDisposable`
We only want to use the first. This commit adds an alias for the symbol so that it's hard to accidentally use the wrong version. If we ever do need to use the other definition, we can still do so by being explicit about it.

Use the correct IAsyncDisposable by default

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/FileMoveNotificationListener.cs

Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1515450/
The prompt for "Sync namespace to folder structure?" allowed you to also select the "Don't show again" checkbox. However, the selection of `Yes` or `No` on this dialog did not correspond to the actual enability of the namespace update feature. Here, I check to see if the user has ticked that checkbox and set the setting (Tools -> Options -> Projects and Solutions -> General) to enable/disable it based on them selecting Yes/No.

Fix namespace update setting based on prompt selection

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs

Fixes [AB#1680186](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1680186)
Fixes [AB#1712009](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1712009)
CPS uses immutable dictionaries to model snapshot data. The default implementations of these reorder their items (by hash code, which is essentially random).
Snapshot data that comes from CPS builds is backed by interface `IDataWithOriginalSource<>` which allows access to data in the original order.
It turns out this interface is not available on data sourced from evaluation.
Because the FUTDC uses the `JointRuleSource` it receives a mix of both evaluation and build data. Therefore in a given snapshot we cannot guarantee item ordering.
This change attempts to use …

Up-to-date check doesn't require ordered snapshot data

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/CompilerCommandLineArgs.xaml

This doesn't seem to be causing any problems, but I can imagine it might surface a hard-to-diagnose bug one day.
Searching other `ItemType` attributes shows this is the only one with white space.

Remove stray space

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsSolutionEventListener.cs

This prevents code from unintentionally running on the UI thread when waiting on the `TaskCompletionSource`.

Ensure continuation runs asynchronously

---

docs/design-time-builds.md

This change updates our documentation on design-time builds to clarify what is meant by "CPS" and "legacy project system". An internal user was using this document for guidance on how to check for a design-time build and was confused by these terms as they aren't defined or explained.

Clarify CPS vs. legacy project system

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/MiscellaneousRuleTests.cs

Fixes #8793.
On the VB "Build" property page we have a property named "Output path". Note that is not the text displayed to the user, but the actual ID of the property on the page. When the user attempts to set this property they'll get exceptions from MSBuild complaining that MSBuild property names cannot include spaces; this is because the property name on the page is used as-is for the property name in the underlying MSBuild file.
Here we fix the property name on the .xaml file, and add a unit test that scans all our .xaml files and verify that none of the property names contain spaces.

Fix a property name

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/FaultExtensions.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/FaultExtensionTests.cs

Our fault handling logic wraps exceptions raised on Dataflow blocks and reports them via `IProjectFaultHandlerService`.
The previous implementation was constructing that wrapper exception such that its `Message` contained the full `ToString()` of the inner exception. That inner string can be enormous for deep stacks, or deeply nested chains of exceptions (or both).
Lifeng observed instances of this exception string crowding the Large Object Heap, and this fix should address that by simplifying the message of the wrapper exception.

Reduce exception message size

---

setup/Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles/Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.csproj
setup/ProjectSystemSetup/ProjectSystemSetup.csproj
setup/VisualStudioEditorsSetup/VisualStudioEditorsSetup.csproj

Our common targets now specify these for all builds within Visual Studio. We don't need to opt-out explicitly here anymore.
https://github.com/dotnet/project-system/blob/d03b401d72a79f3d970cfe33e51a0adf41e03132/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets#L28-L29

Remove explicit build acceleration overrides

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

Fixes #8799
These URLs guide users towards documentation for the Build Acceleration feature.

Add documentation link to verbose log output

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesProjectTreeProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs

Two components of the dependencies tree were initialized via different means.
1. `DependenciesProjectTreeProvider` was initialized via the CPS `PhysicalProjectTreeProvider`.
2. `DependenciesSnapshotProvider` was initialized when the project factory completes (`ProjectAutoLoad`).
There was an implicit contract between these components that they were initialized in that specific order. If that contract is broken, there are runtime exceptions due to the use of an uninitialized instance of `DependencyRulesSubscriber`.
This change causes both initializations to occur in a single path, so that the initialization order is enforced directly within the dependencies node's own code, rather than relying on environmental support.

Prevent race condition during dependencies tree initialization

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs

Fixes #8805
Items in certain locations on disk are considered non-modifiable, and therefore are not inspected for changes during the fast up-to-date check. The fewer files we check, the faster the check will be.
Previous work in this area filtered various references, such as framework assemblies, using our `ProjectFileClassifier`.
This change extends the behaviour to input items, primarily to exclude items added via NuGet packages such as `Compile` and `AdditionalFiles` items.
```
FastUpToDate:     Adding AdditionalFiles inputs: (Microsoft.VisualStudio.Editors)
FastUpToDate:         D:\repos\project-system\src\Microsoft.VisualStudio.Editors\PublicAPI.Unshipped.txt (Microsoft.VisualStudio.Editors)
FastUpToDate:         C:\Users\drnoakes\.nuget\packages\microsoft.visualstudio.sdk.analyzers\1 …
```

FUTDC excludes non-modifiable input items

---

setup/Directory.Build.targets

Fixes: https://github.com/dotnet/project-system/issues/8350
This error would occur on builds that did not either have the `/m` flag when calling MSBuild or non-deterministically for our current build (which uses `/m` in `build.cmd`). That flag determines if the projects build in parallel or in series (`/m` is parallel, without `/m` is series).
I compared the builds side-by-side and diffed all the properties and inputs to the failing target. That target is `CreateVsixContainer`, specifically for the `VisualStudioEditorsSetup.csproj`. Nothing was different. Then, I built the actual MSBuild task source code (for `CreateVsixContainer`) and debugged it. I didn't see anything awry. I found the exact line that was failing, and looked at the path again shown in the error:
> Could not find part of …

Fix build without /m error

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs

Avoids allocating a heap object for these updates.

Use value tuples for dataflow objects

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets

Fixes #2374
Adds any resolved `.ruleset` file to the set of `UpToDateCheckInput` items considered by the fast up-to-date check.
---
A previous attempt at this caused a performance regression and was reverted. We take a slightly different approach here which I hope won't have the same issue:
- The [`ResolveCodeAnalysisRuleSet` target](https://github.com/dotnet/msbuild/blob/7bf511372af6bc80510e1ee6711661c2e0683fe0/src/Tasks/Microsoft.CSharp.CurrentVersion.targets#L125-L135) is fairly minimal and only run when a `CodeAnalysisRuleSet` property exists.
- The [`ResolveCodeAnalysisRuleSet` task](https://github.com/dotnet/msbuild/blob/7bf511372af6bc80510e1ee6711661c2e0683fe0/src/Tasks/ResolveCodeAnalysisRuleSet.cs) is likewise quite minimal.

Up-to-date check considers .ruleset files

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets

The `ResolveCodeAnalysisRuleSet` MSBuild target is only defined for C# and VB projects. This meant that F# projects encountered failing design-time builds with error:
> error MSB4057: The target "ResolveCodeAnalysisRuleSet" does not exist in the project.
This change ensures the target is only added to `DependsOnTargets` for projects with language C# and VB.

Fix ruleset discovery error for F# projects

---

docs/build-acceleration.md

I just added a label for issues relating to build acceleration. This change adds a link to open issues with that label from our BA docs, to make it easier for folks to like and subscribe.

Link to open Build Acceleration issues from docs

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/FileMoveNotificationListener.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/RenamerProjectTreeActionHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/RoslynServices.cs

Fixes: https://github.com/dotnet/project-system/issues/8591
Replaces the use of the deprecated overload for `RenameDocumentAsync`/`RenameSymbolAsync`. The new overload takes in a `DocumentRenameOptions`/`SymbolRenameOptions`. I looked at the code in Roslyn and these options are simply defaulted (new instance with no parameters) in our current use of the deprecated overload. Given that, for each of our classes, I simply made a static default field for the class to use.

Replace deprecated uses of RenameDocumentAsync/RenameSymbolAsync

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredProjectsLoader.cs

This class monitors CPS's `ActiveConfigurationGroupSource` block and forces CPS to eagerly load the project for all configurations in the project.
CPS is looking at moving this logic to within CPS itself, giving greater control over when configured projects (across all dimensions) are loaded, for example to prevent various race conditions.
The previous implementation had two distinct behaviours:
1. Use `[ProjectAutoLoad]` to link an action to the `ActiveConfigurationGroupSource` that forces loads to occur.
2. Export a `ChainedProjectValueDataSourceBase<>`, which allows it to participate in Dataflow so that other blocks can subscribe to its output (`IEnumerable<ConfiguredProject>`).
This change keeps 1 and removes 2. That way, when CPS adds the behaviour of 1, we can be sure we don't need …

Simplify ActiveConfiguredProjectsLoader

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/IDependenciesRuleHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/AnalyzerRuleHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/AssemblyRuleHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/ComRuleHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/DependenciesRuleHandlerBase.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/FrameworkRuleHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/ProjectRuleHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/SdkRuleHandler.cs

This interface is not specific to "cross targeting". It's more closely aligned with the subscriptions, and is implemented within a subnamespace of the target namespace.

Move IDependenciesRuleHandler

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/TaskExtensions.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Threading/Tasks/TaskExtensionsTests.cs

Fixes [AB#1745651](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1745651)
Ensure that we don't hang while waiting for snapshot data to arrive when the project is unloaded before that data can be produced.
Thanks @adrianvmsft for analyzing the dump and routing this bug to us with enough analysis to make the fix straightforward.

Prevent hang in LaunchSettingsProvider

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/IDependenciesRuleHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/AnalyzerRuleHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/AssemblyRuleHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/ComRuleHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/FrameworkRuleHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/ProjectRuleHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/SdkRuleHandler.cs

Contract names are used when the CLR type is not enough to uniquely identify the part for import. For example, when we use an interface in multiple scopes, we use explicit contract names to control which exports of the interface to import in each scope.
In the case of `IDependenciesRuleHandler`, there is no such need for this contract name. This commit removes it.

Remove explicit contract name from MEF part

---

docs/repo/dependencies-node-roadmap.md

Adds a mermaid class diagram covering how the various classes come together, which I found helpful while looking at this code again after a while.

Add dependency node class diagram to docs

---

docs/build-acceleration.md
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.FileSystemOperationAggregator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/CopyItemAggregator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/ICopyItemAggregator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

Fixes #8798
Build acceleration relies heavily upon the presence of reference assemblies. If a referenced project does not produce a reference assembly, we will be unable to accelerate the case where that referenced project had a private (non public-API) change.
This change introduces a log message when we detect this scenario, directing the user to consider a change that would improve their incremental build performance.

Warn if build acceleration enabled but not reference assemblies

---

README.md

- Remove the gitter link as it has not seen any use in years and we don't frequent it. The image is also dead, which looks bad.
- Convert `docs.microsoft.*` to `learn.microsoft.*`
- Remove `en-us` from MS docs links so that users in other locales see localised content.
- Update some links that redirected to different URLs.
- Changed some links from HTTP to HTTPS.

Update README links and remove gitter link

---

eng/pipelines/templates/analyze-api.yml
eng/pipelines/templates/analyze-compliance.yml

When checking if files are signed appropriately, we do 2 scans which use different tasks. The first only checks if the *DLLs* are signed appropriately. The second checks to see if the package (and all contents within it) are signed appropriately. The first check had a copy-paste bug where the `ProjectSystem` was missing out of the filepath to search for files. This PR adds that back it so it is verified in the first signing check.
The same copy-paste issue was in APIScan for downloading the required files. This fixes that too.
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7392601&view=results

Fix DLL signing verification + ApiScan

---

docs/build-acceleration.md
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.FileSystemOperationAggregator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/CopyItemAggregator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/ICopyItemAggregator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

Fixes #8880
Build acceleration works best when all referenced projects produce a reference assembly each. We recently added a message highlighting when this was not the case, but didn't explain which project needed to be modified in order to fix this issue.
This change tracks and logs which projects need updating. The `TargetPath` is printed for those projects, which will generally also identify the target framework and so is therefore more helpful than just the `.csproj` file.

Log details of referenced projects not producing a reference assembly

---

src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb

Fixes [AB#1757141](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1757141)
When dragging a file from Solution Explorer into the Managed Resources editor, the file path is written to the `.resx` file in lower case.
This is because the "drop data" provided by Solution Explorer contains a lower-case path (both for SDK-style and legacy projects).
To fix this, we walk the path, using `Path.EnumerateFileSystemEntries` to produce a correctly cased path for the file being dragged. Unfortunately there's no better way I could find to achieve this. I tried quite a few different approaches and this seemed like the least rubbish. The approach used in `GetFileNameInActualCase` elsewhere in the resource editor only handles the file name, not any directories above …

Write file reference with correct capitalisation

---

src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsSingleFileGeneratorBase.vb

If the user has not defined a default namespace in VB .net framework, it will default to "My". We want to avoid My.My. being generated in the file generator.

Avoid duplicating My in settings type if no root namespace exists

---

eng/imports/HostAgnostic.props
eng/imports/Packages.targets
eng/imports/VisualStudioDesigner.props
eng/imports/VisualStudioIntegration.props

Sort the `PackageReference` items in our shared .props and .targets files. So long as we keep these sorted as we add new ones it will reduce the possibility of merge conflicts.

Sort PackageReferences

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hant.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/ProjectPropertiesRuleTests.cs

Addresses [AzDO#1675354](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1675354).
By default, properties are visible so the `Visible` attribute would not be specified.
Therefore, if we cannot parse it, it means it's visible and we should check for the `Category` attribute.
Also, we ignore launch profile property pages as they don't use categories.

Fix localization unit test

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/Handlers/AbstractEvaluationCommandLineHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/Handlers/CompileItemHandler.cs

The language service's `CompileItemHandler` is created multiple times within the unconfigured project &mdash; once per project configuration slice. We annotate it here with an attribute to advertise this fact.
This shouldn't have any impact to the current code as we use an `ExportFactory` to create instances of this part as needed, however annotating it is good practice and makes the type consistent with its peers.

Annotate MEF part as non-shared

---

docs/repo/property-pages/property-specification.md
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml

Problem: we may have properties where it is not possible/should not be allowable to actually use one of the property configuration commands.
This is a problem, for example, with C# DefineConstants, as the values across dimensions will _always_ vary.
This documents 3 new EditorMetadata properties to allow disabling each kind of command (single value, dimensions, reset property value). Associated with CPS PR (https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/456951)
Under the new behavior (seen below), you are not allowed to select the top command for DefineConstants
Fixed #8901

Document property editor metadata for disabling commands, add it to C# DefineConstants property

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/DebugTokenReplacer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/IDebugTokenReplacer.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/DebugTokenReplacerTests.cs

Contains the documentation changes from #8907 (which is being abandoned).
Moves documentation to the interface, which is public, rather than on the implementation. The IDE will show inherited documentation within the implementation anyway.
Also update some of the text to be more helpful.

Consolidate and extend documentation

---

setup/ProjectSystemSetup/ProjectSystemSetup.csproj
setup/VisualStudioEditorsSetup/VisualStudioEditorsSetup.csproj

Fixes: https://github.com/dotnet/project-system/issues/8912
I didn't dig into this too deeply into this one. I always thought having `ReferenceOutputAssembly` to `false` to be suspicious, since the DLLs from these projects are not used. Related to the bug, building `ProjectSystemSetup` after making changes to our normal `Managed`/`Managed.VS` projects weren't causing the VSIX to be recreated. Setting `ReferenceOutputAssembly` to `true` resolves this.
1. Rebuild solution
2. Observe `ProjectSystemSetup` correctly creates a VSIX
3. Create change in `Managed` project code (any code file)
4. Build `ProjectSystemSetup` only
5. Observe that no new VSIX was created
6. Change `ReferenceOutputAssembly` to `false` to `true`
7. Repeat steps 1 to 4
8. Observe that a new VSIX is being created correctly …

Force setup projects to reference their outputs

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/ITelemetryOperation.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/ITelemetryService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/ManagedTelemetryService.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Telemetry/ManagedTelemetryServiceTests.cs

Our `ITelemetryService` offers various helper methods to simplify interactions with the VS telemetry system, such as a `PostProperty` method to post an event with a single property.
This change adds support for operations with associated start and end events. Calling `BeginOperation` marks the start of the operation and returns an `ITelemetryOperation` representing it. From there, consumers can call `SetProperties` to associate properties with the "end" event, and `End(TelemetryResult)` to mark the end of the event with a corresponding result (e.g. success, failure, canceled, etc.).
`ITelemetryOperation` derives from `IDisposable` as a way to help ensure the operation is posted to the telemetry system even if the consumer forgets to call `End`, and in debug builds the `Dispose` method …

Add support for reporting operations via telemetry

---

eng/pipelines/official.yml

Requested by: @drewnoakes
When doing a manual insertion (non-scheduled), you can set which VS branch you want to insert into. The field for this is just a `string`. If you input the VS branch name incorrectly, you won't know it until the entire build and all compliance checks finish, when it goes to run the *Insertion* stage. It'll fail saying that the remote branch doesn't exist. To have a slightly less stressful process, I've added a stage called *Validate* that only runs when doing these manual insertions. This stage will check to see that the VS insertion branch name you provided is valid. This stage runs prior to the main *Build* stage. If it fails, it'll fail the rest of build, and let you know much, much earlier than it would previously.
- Failure Test: input `bacon-in-the-house` …

Add Validate for VS insertion branch name

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/IProjectHotReloadNotificationService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadNotificationService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManager.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Unshipped.txt
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IProjectHotReloadNotificationServiceFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManagerTests.cs

- The CSS hot reload system needs a way to know when the project system has entered hot reload mode - has at least one active hot reload session, and when it the project is no longer in hot reload mode. Currently the CSS hot reload system runs autonomously, but there is a desire to have it honor the hot reload button. In order to support this, it needs to register and unregister itself as a hot reload agent which requires knowing when the project has entered and exited hot reload mode.
- I added an IProjectHotReloadNotificationService interface to support this. It is exported by the managed project system and has a method to set the current hot reload state of the project and has an AsyncEvent which consumers can listen for changes in hot reload state. 
- The CSS hot reload subsystem …

Addition of a hot reload notification service

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/ManagedTelemetryService.cs

`TelemetryOperation` implements `IDisposable` so we can guarantee that `TelemetryScope.End` is called even if not explicitly done so in code. However, we should call it in `Dispose` if it has already been called elsewhere.

Avoid multiple calls to TelemetryScope.End

---

nuget.config

This is needed for migration from vs-impl and vssdk, as they are changing their feed structure

Add archived feeds

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/BuildPropertyPage/GenerateDocumentationFileValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.zh-Hant.xlf

Fixes the feedback ticket https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1773467
This PR handles the scenario where there is no value to recover and set the `unevaluatedPropertyValue` as the value. I also followed the non-configurable setting that C# has for the same property, but I'm also okay leaving it configurable.
Before: you cannot set the property.
After: you can set the property and see it in the project file.
Open to discuss: do we want to also bring in the `DocumentationFile` property over to the VB Build property page, so the user sets it. It does have a comment saying that we wanted to remove that property all together, but I'm unsure the reason behind it. https://github.com/dotnet/project-system/blob/18ee5d2985bb0b7f438945f829ff9abf0bbbbbbe/src/Microsoft.VisualStudio.P …

Set the Generate XML Documentation property correctly.

---

src/Common/BannedSymbols.txt
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/Workspace.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/ProjectRuleSnapshotExtensions.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs

Fixes [AB#1761872](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1761872)
CPS build data generally implements the `IDataWithOriginalSource<T>` interface, allowing us to obtain items in their actual order.
There is a bug in CPS where when a snapshot is empty, it might not implement this interface. We would assert that the interface was present and throw.
This change does two things:
1. Permit an empty snapshot to not implement this interface, which should work around the bug.
2. Ban direct use of the `IDataWithOriginalSource<T>` interface and require all use to go through one of two new extension methods that handle these scenarios properly.

Work around empty build data snapshot bug

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/DebugProfileEnumValuesGenerator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/ProjectRuleSnapshotExtensions.cs

A recent version of C# supports using nameof in attributes where the symbol is a parameter of the attributed method. This commit is an automated solution-wide fix of the diagnostic.

Use updated nameof

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/DebugProfileDebugTargetGenerator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/DebugProfileEnumValuesGenerator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchSettingsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfile.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs

Some refactoring and tidy ups made while watching the showcase.
The biggest change here is the simplification of the dataflow source in [DebugProfileDebugTargetGenerator](https://github.com/dotnet/project-system/commit/c5c1c533a9a25a5dc0f8dc04bda72d6224597060), which deletes a bunch of code and avoids registering the data source.
Other than that, reduced allocations, improved docs, formatting.
Easiest to review commit-by-commit.

Debug subsystem tidying

---

src/Microsoft.VisualStudio.Editors/MyApplication/MyApplicationCodeGenerator.vb
src/Microsoft.VisualStudio.Editors/MyApplication/MyApplicationData.vb
src/Microsoft.VisualStudio.Editors/MyApplication/MyApplicationDataSerializer.vb
src/Microsoft.VisualStudio.Editors/MyApplication/MyApplicationProperties.vb
src/Microsoft.VisualStudio.Editors/PublicAPI.Shipped.txt
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ApplicationFrameworkValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/VisualBasic/SplashScreenEnumProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.VisualBasic.xaml

Addresses #8286, part of #8766, [AB#1565607](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1565607)
This PR:
- makes the splash screen properties visible
- creates a `IDynamicEnumProvider` for the splash screen property, where it gets the valid entry points from the `IEntryPointFinderService`.
- saves the splash screen property as the name of the entry point, without any namespaces, as that's the way the myapp file needs it to generate the code for the Designer (in contrast to the C# way we do it for the `StartupObject` property.)
- tracks the `StartupObject` in the `ConfigurationGeneral` xaml rule to later be used in the `IDynamicEnumValuesGenerator` to remove the selected value (if any) from the splash screen enum value list.
**Pending:**
I'll add …

Enable splash screen properties for VB WinForms projects.

---

.github/fabricbot.json
version.json

Noticed we are tagging merged PRs as 17.6 with the msftbot.
This updates it to tag it as 17.7; it also updates our version.json file.

Update version number when tagging PRs.

---

docs/up-to-date-check.md
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs

Following discussion in #8935. This property cannot be specified in the project file. It's intended to be passed as a global property by some VS component.
Also use the correct comparer in collection. In this case both `SetNameComparer` and `KindNameComparer` resolve to the same value. But this change makes the code more semantically consistent.

Improve FastUpToDateCheckIgnoresKinds documentation

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/IVsHierarchyItemExtensions.cs

Adds two `RegexOptions` flags to a `Regex` instance:
1. **Only capture explicit groups in regex**
We only need to read out our named group. Capturing data about other groups is wasteful. https://learn.microsoft.com/dotnet/standard/base-types/regular-expression-options#explicit-captures-only
2. **Match with invariant culture**
For this pattern we do not need to take cultures into account when matching. https://learn.microsoft.com/dotnet/standard/base-types/regular-expression-options#compare-using-the-invariant-culture

Refine regex flags

---

ProjectSystem.sln
docs/up-to-date-check.md
setup/Directory.Build.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets

Fixes: https://github.com/dotnet/project-system/issues/8912
The scenario being addressed here is when you make a change in our product code and then attempted to debug in Visual Studio. Without telling the things to explicitly build, it would not build our *Setup* projects (`ProjectSystemSetup`/`VisualStudioEditorsSetup`). Therefore, it wasn't creating or deploying a new VSIX package into the experimental hive and your changes were not present there.
After investigation with Drew, it was determined that the inputs into the VSIX and the package itself needed to be tracked as UpToDate items. The changes to get this working properly:
- Updated `Microsoft.Managed.DesignTime.targets` to allow changing the defined `DependsOn` for the targets that collect the UpToDate items
- Added targets for …

Add VS Extension Project items to UpToDate check mechanism

---

eng/pipelines/templates/generate-localization.yml

This allows the OneLocBuild task to automatically reused existing localization PRs instead of continually creating new ones. Communication about this flag was sent out on 10/25/2021, but I misunderstood the communication around it, believing it was an Arcade-only feature. My bad.
Reference of change in Arcade: https://github.com/dotnet/arcade/pull/8095/files

Localization: Reuse existing PR if available

---

eng/pipelines/templates/build-official-release.yml

Related: https://github.com/dotnet/arcade/issues/13070
We're experiencing intermittent failures on NuGet package restore in AzDO stating, "The author primary signature validity period has expired." Looking into it, there is an environment variable to retry NuGet package restoration when certain types of errors occur. This should apply in this situation. It doesn't fix the issue but it should help to reduce the number of build failures. I'm only adding this to our official build for the time being.
https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=7655011&view=results

Add NuGet restore automatic retry

---

setup/Directory.Build.props

There is an intermittent build issue where the build fails because SBOM generation fails. The output looks like this:
From [this build](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7665662&view=logs&j=3de96e8d-b8d1-5108-47b8-f6a54739db67&t=a16cdda0-c78c-5fd9-f5e9-cb04cb362077), looking at the binlog reveals that each `GenerateSbom` task for the 2 projects (`ProjectSystemSetup` and `VisualStudioEditorsSetup`) references the other one's SBOM manifest file. Meaning, the one project's SBOM generation was trying to access the other project's SBOM file while it is being generated.
To remedy this, I moved the SBOM generation up a directory (to the `bin` folder instead of `bin\Dlls`) so that the output of `GenerateSbom` isn't consumed as part of that task for any project …

Fix SBOM file conflict issue

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml

NuGet recently added a feature to warn about packages with known vulerabilities on restore. We need two more project properties for this feature to work.
NuGet.Client feature implementation: https://github.com/NuGet/NuGet.Client/pull/5136
Feature spec: https://github.com/NuGet/Home/blob/dev/proposed/2022/vulnerabilities-in-restore.md

Add NuGetAudit properties to NuGet nominations

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ActiveConfiguredProjectsLoader.cs

While investigating #8993 I noticed this instance was not made explicit. Making it so helps avoid confusion about when this will be called.
There's no change in behaviour here.

Make load event checkpoint explicit

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckHost.cs

When running `devenv <sln> /populateSolutionCache /build`, the FUTDC should produce its cache file such that the first build using the generated caches is considered up-to-date.
The FUTDC has historically disabled itself when running in command line mode. Historically command line mode has not run any design-time builds, and therefore no FUTDC snapshot data becomes available. The FUTDC would avoid waiting for snapshots when it detected command line mode is active.
Solution cache population is now an exception to this. It's a form of command line mode for where design-time builds do run, and for which we do want the FUTDC to run in full.
This change teaches the `UpToDateCheckHost.HasDesignTimeBuildsAsync` method about the `/populateSolutionCache` command line argument, so that the …

Fix FUTDC solution cache population for DevBox

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ApplicationFrameworkValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WindowsForms/MyAppDocument.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WindowsForms/MyAppFileAccessor.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hant.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/WinForms/IMyAppFileAccessor.cs

Fixes [AB#1803253](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1803253).
This PR adds a validation to the `MinimumSplashScreenDisplayTime` property is an integer or is empty. It uses the `ValueEditor` to opt into value validation, and if it fails it shows the validation message.

Validate that value is an integer or empty.

---

eng/pipelines/templates/build-pull-request.yml
eng/scripts/GetInsertionPRDescription.ps1

This is the same fix as done in this PR: https://github.com/dotnet/project-system/pull/8983
- Adds the NuGet retry environment variable for PR build pipeline
- Linked PR above was for the Official build pipeline
- Minor word change on insertion description condition
- More accurate to use "abandon" since that is the name of the state used in AzDO

Add NuGet retry for PR build

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UnconfiguredProjectTasksService.cs

Fixes [AB#1810458](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1810458)
(Thanks @lifengl for reporting this issue.)
Our `UnconfiguredProjectTasksService` class listens for project factory completion and signals this to other components that may wait on that status.
The class uses `[ProjectAutoLoad]` to receive this notification from CPS, however it was asking to be notified _before_ the project factory completed rather than _after_.
One identified consequence of this is that the `SDKVersionTelemetryServiceComponent` class would wake up earlier than intended, request `ActiveConfiguredProjectProperties`, then immediately block. This makes a thread-pool thread unavailable for other productive work during project/solution load.
The fix here is to …

Fix early signalling of loaded state

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/IOutputTypeChecker.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/OutputTypeChecker.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IOutputTypeCheckerFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectLaunchTargetsProviderTests.cs

While making other changes I noticed that we were sometimes creating a new `OutputTypeChecker` rather than importing an `IOutputTypeChecker` and letting MEF handle the creation for us. This change defines `IOutputTypeChecker` and updates all of our code to use it.
The main effect is that the tests around the `ProjectLaunchTargetsProvider` have gotten somewhat simpler as we are no longer dealing with the dependencies of `OutputTypeChecker` but can instead create a mock `IOutputTypeChecker` with our desired behavior.

Replace OutputTypeChecker with IOutputTypeChecker

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IPropertyPagesCatalogFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ProjectPropertiesFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/PropertyPageData.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsProviderTests.cs

Fixes [AB#1815584](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1815584).
The `LaunchSettingsProvider` looks for the launchSettings.json file within the project's "app designer" folder, and so to read the file it needs to find the location of that folder on disk. Ultimately this is controlled by the "AppDesignerFolder" property in MSBuild. In the case of C# this defaults to "Properties"; for VB it is called "My Project".
Currently the `LaunchSettingsProvider` does not read this property directly. Instead, it imports the `IAppDesignerFolderSpecialFileProvider`, and the implementation of that (`AppDesignerFolderSpecialFileProvider`) utilizes project tree. It searches the project tree for certain flags denoting the app designer folder; these flags were …

Remove dependency on the project tree

---

eng/pipelines/templates/build-official-release.yml

The VS Bootstrapper task has had an acquisition issue recently. To fix it, it needed to make a breaking change; thus, updating the task version. This PR updates the task version and causes the task to work properly again. Looks like the Bootstrapper.json is the same, except with an added `QBuildSessionId` value.
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7797012&view=results

Update the VS Bootstrapper task version

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/PublishItemsOutputGroupProvider.cs

This class would take a project read lock, copy every MSBuild target name into an `ImmutableHashSet<string>`, then release the lock. Later it would check whether a single item existed in that collection, then free the collection.
For a simple console app there were 500 such targets. `ImmutableHashSet<>` builds a tree structure internally, which is particularly inefficient. This would run for every configuration of every project.
This change rewrites the class to just query the project for the target it wants, eliminating the collection allocation entirely, and holding the read lock on the project for a shorter time.
---
Prior code in the debugger:

Reduce allocations in PublishItemsOutputGroupProvider

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/PackageRestoreConfiguredInputDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/Snapshots/RestoreBuilder.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/EvaluatedProjectReference.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/EvaluatedProjectReference.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/RuleExporter.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PackageRestore/Snapshots/RestoreBuilderTests.cs

Fixes #8930.
C++/CLI projects use our NuGet restore/nomination code, without providing all our on-disk rules. The prior code required a non-embedded `ProjectReference` rule, which would work for .NET projects, but not for C++/CLI where the rule would not be found. Running with `set CPS_DiagnosticRuntime=1` would output to the "Project" pane of the Output window:
```
CPS Warning: 25816 :
Rule 'ProjectReference' was not resolved when it is subscribed through the ProjectJointSubscriptionService.
CPS Error: 25816 :
Generating snapshot for rule "ProjectReference" failed because the rule was missing from the project.
```
This commit creates a new `EvaluatedProjectReference` rule which _is_ embedded, and uses that in the NuGet restore code. The _Evaluated_ prefix is meant as an analog to …

Embed "ProjectReference" item rule for NuGet restore

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/MSBuildDependencyCollection.cs

Fixes [AB#1820857](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1820857)
While this case is unexpected, it's not worth faulting the dataflow and therefore the project in this case. This change replaces a throw with an assert in debug builds.
This is a workaround for a state that's not well understood yet, but getting this in for 17.7p2 will unblock some folks that don't need to be blocked.

Replace fault with assertion

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Workloads/WebMissingWorkloadDetector.cs

This is an interpolated string, so we have to escape the braces in `{1}` to have them passed through.

Fix dataflow block name format string in WebMissingWorkloadDetector

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectSystemOptions.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WindowsForms/WindowsFormsEditorProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectSystemOptions.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/WindowsForms/WindowsFormsEditorProviderTests.cs

Removing the default forces the caller to think about cancellation when consuming the API. They may still pass a default if they wish to.
This change plumbs through cancellation in `WindowsFormsEditorProvider`.

Avoid default cancellation token on interface

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IIncrementalBuildFailureReporter.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureOutputWindowReporter.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/Diagnostics/IncrementalBuildFailureTelemetryReporter.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/LanguageServiceErrorListProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/FeatureFlagNames.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectSystemOptions.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectSystemOptions.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/PackageRestoreCycleDetector.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PackageRestore/PackageRestoreCycleDetectorTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Build/LanguageServiceErrorListProviderTests.cs

Fixes [AB#1825661](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1825661)
The `IVsFeatureFlags` service is free threaded. We don't need to switch to the UI thread in order to call into it.
This removes three such switches and converts our imports from `IVsUIService` to `IVsService` accordingly.

Don't switch to UI thread to check feature flags

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/CommandLineArgumentsOverriddenWarningValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ExecutableDebugPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ProjectDebugPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ExecutableDebugPropertyPage.xaml.zh-Hant.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ProjectDebugPropertyPage.xaml.zh-Hant.xlf

Fixes #8937
Fixes https://developercommunity.visualstudio.com/t/Conflict-with-user-and-launchSettings/1329683
When command line arguments for launch are present in both the `launchSettings.json` file and the `StartArguments` MSBuild property, the latter wins. Yet the former is the more visible in the UI, and this leads to confusion. It's not clear why the value specified in the UI is not being picked up during debugging.
This change adds a warning in that UI when the StartArguments property is non-empty, which explains the issue to the user and allows them to fix it if they want to.

Warn when StartArguments conflict with launchSettings.json

---

eng/pipelines/official.yml
eng/pipelines/pull-request.yml
eng/pipelines/templates/build-pull-request.yml
eng/scripts/AddNpmToPath.ps1

Exclude C# dev kit branch - dev/PortToNET6 from official build. We have separate pipeline for build and insertion.
Update PR build pipeline to ensure npm & copy over test results so we can run C# dev kit PRs in same pipeline.

Update build pipelines for C# dev kit

---

src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.resx

Note that this is on the legacy property pages.
This change was done manually in the `BuildPropPage.resx` instead of its designer; editing in the `BuildPropPage.vb` designer caused many other properties being changed that had nothing to do with it.
Before:
After:
Fixes [AB#1823714](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1823714)

Fix label layout to be anchored to the left margin.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/CompoundTargetFrameworkValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml

Fixes #8931 and [AB#1430819](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1430819). 
This PR:
- Parses the `TargetFrameworkAlias` property into a double and check if it's higher than 5.0 (instead of doing a string comparison).
- Includes the `UseWinUI` property when validating when to add the `-windows` platform value to the `TargetFramework` value.

Minor fixes in TargetFramework validation.

---

setup/ProjectSystemSetup/Properties/launchSettings.json

Getting binlogs is actually quite easy. You only have to set two environment variables to make it work. However you also have to remember what those two variables are, or remember where to find them. And you have to remember to escape backslashes in the path within the JSON.
This change adds the environment variables, commented out, to our `launchSettings.json` file so that it's easier to opt in to this when you want it.

Simplify getting binlogs from the exp hive

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Legacy/LegacyDependencySubscriber.cs

This fixes a regression from the dependency tree rewrite in #9008.
Implementations of the legacy extension point `IProjectDependenciesSubTreeProvider.CreateRootDependencyNode()` return an `IDependencyModel` holding various values to be applied to the group's node. One such value is `IDependencyModel.Flags` which should be applied to the group node. This change fixes that.

Pass legacy root node ProjectTreeFlags

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs

Fixes https://github.com/dotnet/project-system/issues/9124
Fixes [AB#1761194](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1761194)
Fixes [AB#1827475](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1827475)
When the user presses F5 the Solution Build Manager (SBM) calls the Fast Up-to-date Check (FUTDC) twice, for some reason I don't fully understand. If you invoke build directly, it's only called once.
In the debug case, the first of the two calls occurs *before* any SBM events are fired, which breaks an assumption that was made about the sequence of events. Specifically we assumed that the FUTDC would only be called between calls to `IVsUpdateSolutionEvents.UpdateSolution_StartUpdate` and …

Fix FUTD check of copy items when building for debug

---

eng/imports/HostAgnostic.props
eng/imports/Packages.targets
eng/imports/Versions.props
eng/pipelines/official.yml

This file will be used alongwith built version of project-system in C# dev kit for version upgrades

Introduce Versions.props file to control version of CPS packages

---

.github/workflows/markdown-link-check.yml

I was configuring this check for the VSProjectSystem documentation repo and realised we have quite an old version. There's no reason to upgrade that I know, but there have been many updates since the version we last consumed, so I'm curious if it catches anything new. I'm also just interested to learn more about GitHub actions.

Bump github-action-markdown-link-check version

---

src/Microsoft.VisualStudio.Editors/DesignerFramework/AccessModifierComboBox.vb

Adds the following warning before being allowed to change the class accessibility:
This is an auto-generated linked file, and per comment in this folder "We actually don't want users to edit Form RESX file." There is a warning when modifying the values of this file, this editor will eventually be replaced, it's behavior we don't support anyway, and not a trivial fix, so I think adding the warning is enough. The correct behavior for users is to not modify the file at all - doesn't really make sense why it wasn't just made readonly.
Fixes #9034

Add file modification warning to change accessibility combobox in legacy resx editor

---

Directory.Packages.props
eng/imports/HostAgnostic.props

Moving to CPVM requires that extra properties specified on actual package reference now
This package ended up in our package and is blocking our VS insertion because we are using newer version.

Mark IsExternalInit as private assets

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj

Fixes [AB#1839581](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1839581)
We have two ways of distributing .xaml files: on disk, and as embedded resources. Each has its own benefits and challenges.
On-disk files are relatively simple: we distribute them with the .NET Project System design-time targets files, and have those targets files include them as `PropertyPageSchema` items. We can also use MSBuild logic in load in a localized version of the .xaml file instead of the English. On the downside we need additional setup authoring to include the .xaml files in our setup package.
Embedding .xaml files as a resource avoids the setup authoring issues, but does require that we specify an appropriate MEF import to make CPS aware of the resource. We are …

fix: Address a missing .xaml file

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs

Fixes #9152
In some cases (such as when FUTDC logging is enabled) we run a validation pass to report to the user when their projects appear out of date despite just having been built. This feature alerts users to overbuild and provides useful diagnostic information to correct it.
#9130 fixed a bug related to F5 builds. It introduced a race condition that can lead to the error reported in #9152.
Our `CurrentSolutionBuildContext` value is set when the SBM starts the solution build, and cleared to `null` when it completes.
Our validation logic runs async, and can complete after the SBM completes. In such cases, it can observe a null `CurrentSolutionBuildContext` value, which is not supported by the current code.
This change captures the `CurrentSolutionBuildContext` value early on to ensure …

Avoid bug during FUTDC validation after solution build completes

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Setup/PackageContentTests.NpmPackage.verified.txt

Related to [AB#1839423](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1839423).
This commit updates our build to include the Microsoft.VisualStudio.ProjectSystem.Managed resource DLLs in locale-specific directories within the NPM package. This is the layout that the .NET resource manager generally expects for automatic discovery of locale-specific resources.
Here our existing `AddFilesForNpmPackage` target takes a dependency on the `SatelliteDllsProjectOutputGroup` target. The latter creates `SatelliteDllsProjectOutputGroupOutput` items representing each locale-specific .resource.dll, and the former converts these to the `NpmContent` items used by later tasks to actually create the package.

feature: Add resource DLLs to NPM package

---

.github/workflows/markdown-link-check.yml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs

This is a backport of #9161 for 17.7.
I also included the GitHub actions changes from #9141 to ensure we don't get build failures for this PR. Those changes don't effect shipping code, just an optional check on GitHub to validate dead links in markdown files.

[17.7] Avoid bug during FUTDC validation after solution build completes

---

src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsSingleFileGeneratorBase.vb

Fixes:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1708985
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1845024
We got a couple of feedback tickets around VB projects having their namespace wrongly generated to the `My` namespace on the `Settings.Designer.vb` file, instead of their custom namespace.
[Back in 2022](https://github.com/dotnet/project-system/pull/8391/commits/0d007c1af0e6234418379e3d7236f73ea3a7cbd7), we added some logic to the `SettingsSingleFileGeneratorBase.vb` to include the `My` namespace if the project was VB; we forgot to include a consideration for custom namespaces, which would be found in the `DefaultNamespace` parameter when calling `Create`.

Check if a custom namespace has been specified when generating the Settings designer class.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/FeatureFlagNames.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectSystemOptions.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectSystemOptions.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

Contributes to #9106. A change is also needed in VS to define the feature flag.
This change adds code that checks the `ManagedProjectSystem.EnableBuildAccelerationByDefault` feature flag when a project does not explicitly define the `AccelerateBuildsInVisualStudio` MSBuild property. This allows users to enable the feature at the IDE level, rather than the project level.
If a project defines the `AccelerateBuildsInVisualStudio` property, then that value overrides any feature flag value.

Allow enabling Build Acceleration via a feature flag

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/DependencyExtensions.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/MSBuildDependencyCollection.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/MSBuildDependencyFactoryBase.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/MSBuildDependencyCollectionTests.cs

Fixes [AB#1820619](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1820619)
Due to a copy/paste bug, certain modifications of the project file could not be reflected in the tree. The fix is straightforward.
For example, changing `Version` or `NoWarn` metadata on a `PackageReference` item in such a way to introduce or remove a diagnostic would not update the tree correctly before this fix.

Fix application of build data item changes to dependency tree

---

eng/pipelines/official.yml

The CodeQL task in auto-injected into our official builds in order to check for known code vulnerabilities. A bug in CodeQL was causing "dotnet test" to fail (see https://twcsecurityassurance.visualstudio.com/Semmle/_workitems/edit/24228), and while it has been fixed in a newer version of CodeQL it will be a while before the pipeline task picks up the new version. In the meantime we can specify a version with the fix by setting Codeql.CLIVersion and Codeql.CLIHash in our official.yml file.
However, the injected CodeQL task is now complaining that "Hash verification failed" and disabling CodeQL. The issue is the text "// sha256 hash for windows CLI" at the end of the CLIHash value; it is being treated as part of the hash rather than a comment. This change removes the comment.

Fix CodeQL in build

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/BuildPropertyPage/TrimmingEnumProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/StartupObjectsEnumProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/VisualBasic/SplashScreenEnumProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf

Partially covers #9101.
Introduces `PublishAot` and `Trimming` properties into the Build page.
Their HelpUrls redirect to: https://learn.microsoft.com/dotnet/core/deploying/native-aot/
Also, introduces `IsTrimmable` and `IsAotCompatible` properties into the Build page.
Their HelpUrls redirect to: https://learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming

Introduce Native AOT properties.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj

Versions of System.Security.Cryptography.Pkcs prior to 7.0.2 contain a vulnerability that could lead to a DOS attack. We pull this in through CPS, which is getting it from MSBuild. As best I can tell MSBuild is the only component in the chain that actually uses System.Security.Cryptography.Pkcs; the rest of us are just getting transitive dependencies and so we're getting flagged by Component Governance.
Here we attempt to make Component Governance happy by forcing System.Security.Cryptography.Pkcs to a good version. Since we don't actually want to use the package in any way we specify ExcludeAssets="all".

Resolve a Component Governance issue

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets

These are single values and don't need a delimiter.

Remove semicolons from item specs

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs

Previous code was using a schema name rather than a property name. They just happened to have the same value, so there's no runtime change here. It's just more semantically correct.

Use correct constant for metadata name

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

The FUTDC checks the current project file. It also checks the most recently modified import.
Previously the FUTDC would check both the `MSBuildProjectFullPath` (i.e. the current `.csproj` file's path) and the first item of the `MSBuildAllProjects` property, which MSBuild sets to the newest of all imported project files.
As the FUTDC is only interested in the newest input, we only need to check that `MSBuildAllProjects` value and not the `MSBuildProjectFullPath` value. If the project file is newest, it will be covered by `MSBuildAllProjects`. If not, we don't need to check it.
This can save a little time by avoiding a file system check. It also reduces the log output a little. It also removes a localised string.
```
FastUpToDate:     Adding project file inputs:
FastUpToDate: …
```

FUTDC avoids checking the same file twice

---

tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Utilities/DisposableBagTests.cs

I was trying to do something else with the `DisposableBag` class but discovered it wouldn't work. These unit tests can at least be kept.

Add DisposableBag unit tests

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/Workspace.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/WorkspaceTests.cs

Contributes to [AB#1861138](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1861138)
`WorkspaceFactory` is responsible for creating instances of `Workspace` and setting up their dataflow subscriptions.
General guidance when constructing a dataflow chain is to establish the first link last. In that way, the chain is fully constructed at the point data starts to flow into it.
In the case of the language service, we have two sources — one for evaluation data, and another for build data. This means we cannot prevent data from flowing during construction.
While investigating a dump from a hang, @adrianvmsft and I observed an `ObjectDisposedException` coming from the call to `ChainDisposal`. It appears that something within `Workspace.OnWorkspaceUpdateAsync` …

Avoid ObjectDisposedException in language service

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/LanguageServiceHost.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/WorkspaceFactory.cs

Fixes [AB#1861138](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1861138)
Includes #9201 as I had to modify the same code here too. That's only a tiny PR thankfully.
Components such as CodeModel can wait on the language service to initialise. In particular, they need the first "primary" workspace to be available, so that it can be interacted with.
Currently that readiness is signalled with a `TaskCompletionSource`.
If the first data update causes an exception in the handler, the previous code would neither complete nor fault that `TaskCompletionSource`, leaving any waiting code to wait indefinitely (hang).
This change ensures that any fault on the handling block causes that `TaskCompletionSource` to be faulted, if it isn't already complete.
We also …

Don't hang when update handling throws, and report NFE

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/LanguageServiceHost.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/WorkspaceFactory.cs

In `DataflowBlockSlimBase.ToString`, CPS passes two arguments for the formatting of these strings. `{0}` is the type name and `{1}` is the instance's hash code, which uniquely identifies the block instance. When debugging a heap dump want the instance details, as we can see the type name.

Fix invalid nameFormat patterns

---

Directory.Packages.props
eng/imports/Versions.props

Update the referencedversion of CPS (and some dependent packages) to pick up a new launch target for use in C# Dev Kit

Update CPS version

---

docs/build-acceleration.md
src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/BuildAccelerationIncompatiblePackage.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/BuildAccelerationIncompatiblePackage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/RuleExporter.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInputDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs

Contributes to #9106
While rare, it's possible for a NuGet package to include `.props` and/or `.targets` files that customise the build in a way that's not compatible with Build Acceleration. Ideally such packages would also set `AccelerateBuildsInVisualStudio` to `false`, however that's not always an option.
To address this situation, this change introduces the ability to specify NuGet packages that, when present in a project, will disable Build Acceleration.
We add one known package (`Microsoft.VSSDK.BuildTools`, for VSIX projects) to our design-time `.targets` file, but SDKs and customers may add their own items too.
For example, if `MyPackage` is known to be incompatible with Build Acceleration, adding a `BuildAccelerationIncompatiblePackage` item  to your `Directory.Build.props` will …

Disable Build Acceleration for known incompatible packages

---

src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.Designer.vb
src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.resx
src/Microsoft.VisualStudio.Editors/PropPages/SeparatorGroupBox.vb
src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.cs.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.de.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.es.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.fr.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.it.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ja.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ko.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.pl.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.pt-BR.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ru.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.tr.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.zh-Hans.xlf
src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.zh-Hant.xlf

The **Build** property page used for legacy projects was essentially a flat list of components separated into sections by labels: **General**, **Errors and warnings**, **Treat warnings as errors**, **Output**. This posed a problem to accessibility tools like screen readers, which did not recognize these labels to be groupings, leading to incomplete and confusing voice output. For example, when navigating to the **Treat warnings as errors** section, the reader would announce just "None" without context.
This PR introduces a new `SeparatorGroupBox` control. It has the same appearance as separator labels but it can have children, allowing for proper control hierarchy. The Build property page is restructured to take advantage of the new control.
```
overarchingTableLayoutPanel
|
|- …
```

Restructure legacy Build property page for accessibility

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Frameworks/SupportedTargetFrameworksEnumProvider.cs

NFE data shows it's possible to hit a `KeyNotFoundException` in the `SupportedTargetFrameworksEnumProvider`. This could happen if the `ConfigurationGeneral` doesn't have the required set of properties.
This change makes the code fail gracefully in such cases.

Fix KeyNotFoundException in enum provider

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs

Fixes [AB#1847450](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1847450)
The project system uses rule files to define a schema for the properties and items it needs to extract from the project. We use these rules in code when retrieving such values.
The rules are also extension points, and project types may replace or extend these rules for their own purposes.
Replacing a core rule file (like `ConfigurationGeneral`) is a bad idea as it can fall out of date when we take dependencies upon properties that are expected to be there, and the replacement rule does not include them.
That appears to be what's happening from our NFE data. Some project kind is using the FUTDC while not defining the `TargetPath` property in the `ConfigurationGeneral` rule.
I'll …

Avoid NFE when ConfigurationGeneral rule is modified to remove expected property

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml

An improvement to #9139.
Related to #9101.
I have changed the project capability condition to include `NativeAOTProperties` to projects targeting .NET 8 or higher. 
We later exclude/include class libraries when checking the visibility condition: 
- The `IsTrimmable` and `IsAotCompatible` properties should only be shown to class library projects. 
- The `Trimming` and `PublishAot` properties should not be shown to class library projects.
Update: I moved the `ProjectCapability` and its property to the SDK: https://github.com/dotnet/sdk/pull/34485.

Update visibility conditions Native AOT properties in rule; migrate ProjectCapability to SDK.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Legacy/LegacyDependencySubscriber.cs

Fixes #9227
Implementations of the `IProjectDependenciesSubTreeProvider` interface may extend the dependencies tree with additional dependency types.
The rewrite in 17.7 introduced a subtle change in bevahiour where removing the last dependency in a group added via this interface would leave the group node visible in the tree.
This change ensures we remove the group altogether when the last item is removed.

Fix empty dependency group node for external dependencies

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Setup/PackageContentTests.NpmPackage.verified.txt

We can request builds of the C# Dev Kit repo (vs-green) that collect code coverage numbers during integration test runs. In order for this to work, however, the code coverage system needs to be able to find the .pdb files for our managed assemblies. Here we update the project to include all the symbol files in the `DebugSymbolsProjectOutputGroupOutput` item group in our NPM package. This includes the most important file for this repo, Microsoft.VisualStudio.ProjectSystem.Managed.pdb, and, I believe, will also include the .pdb files of other referenced projects (if and when we reference other projects).
Note that the C# Dev Kit extension will not include .pdb files in what gets installed on a user's system so there is no downside to including the .pdbs.
This also updates the test to verify …

Include .pdb files in our NPM package

---

tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Utilities/RepoUtil.cs

Avoids doing file system operations multiple times during test runs. This value won't change during the lifetime of the process.

Cache repo root path

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Runtimes/MissingSdkRuntimeDetector.cs

This PR fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1867244 as well as addresses 1 of 2 gaps in our missing component tracking.
The root cause of the linked issue is that `RegisterSdkNetCoreRuntimeNeededInProjectAsync` is called within `InitializeCoreAsync`. `IsInitialized` isn't true until after `InitializeCoreAsync` completes, so this will always be false. Because `RegisterSdkNetCoreRuntimeNeededInProjectAsync` only runs once, on configured project load, we never register missing runtimes.
The simple solution was to eliminate the block, but... looking into this area, I realized there were two gaps:
1. If you modify the project runtime identifier _after the project is loaded_ to one that you do not have installed on your machine, we do not show the missing component UI. …

Subscribe to project changes to check for missing runtimes

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/CompoundTargetFrameworkValueProvider.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptingProjectProperties/ApplicationPropertyPage/CompoundTargetFrameworkValueProviderTests.cs

Fixes [AB#1846189](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1846189).
We are resetting the platform properties when a target framework is changed; instead, we should keep them if the new value is `.NET 5` or higher.
Unit tests are included: instead of mocking the project services this provider uses, I mocked the provider methods that access data. At the end of the day, these tests only cover the `OnSetPropertyValueAsync()` logic and what I really want to ensure is that we compute the correct value in `ComputeValueAsync()`.

Delete platform properties when targeting lower than .NET 5.

---

Directory.Packages.props
spelling.dic
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/PackageRestoreConfiguredInputFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchSettingsTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PropertyPages/PropertyPageTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsBuildManagerBridgeTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsCompiler.CompilationQueueTests.cs

Update to newer compiler packages, and fix new warnings.
Pulled out of #9229.

Bump compiler version

---

Directory.Packages.props

This reverts commit 9fceaf559b2ef79a8eec825761bbfa4a84799e0c from #9242 - Microsoft.CodeAnalysis and Microsoft.VIsualStudio.LanguageServices versions are higher than the currently used ones from VS. 
This is blocking our M2 insertion, so out of caution reverting the entire commit

Revert "Bump package versions"

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/FileMoveNotificationListener.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/RenamerProjectTreeActionHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Waiting/VisualStudioWaitIndicator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Waiting/IWaitIndicator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Waiting/WaitIndicatorResult.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Waiting/VisualStudioWaitIndicatorTests.cs

JTF.Run should only be used when implementing legacy APIs that cannot be made asynchronous. In our internal `IWaitIndicator` these two methods can be made async and their usages updated to avoid the use of JTF.Run.

Remove use of JTF.Run in wait indicator

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Acquisition/MissingSetupComponentRegistrationService.cs

It turns out that `IVSShellUtilitiesHelper.IsVSFromPreviewChannelAsync` takes an incredibly long amount of time to execute. Since `DisplayMissingComponentsPromptIfNeeded` was being called even in the case where a project already had a missing component, this method call ended up causing a noticeable perf impact. 
This code change only calls `DisplayMissingComponentsPromptIfNeeded` if a project's missing workload/sdk value was actually changed

Don't call DisplayMissingComponentsPromptIfNeeded if missing sdk/workload didn't change

---

docs/build-acceleration.md
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets

We have a feature that disables Build Acceleration when certain NuGet packages are detected. This change adds the ability to set `EnableDefaultBuildAccelerationIncompatiblePackages` to `false` in order to disable this behaviour. This allows customers to more easily disable this default behaviour.

Allow opting out of package-based Build Acceleration disablement

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets

Fixes #8886
Slow Cheetah _can_ work with Build Acceleration, so long as `TransformOnBuild` items don't have `CopyToOutputDirectory` set to `Always`. When that occurs, Build Acceleration thinks it is supposed to copy the untransformed item to the output directory, which will overwrite any transformation done when a real build occurs.
A [GitHub code search](https://github.com/search?type=code&q=%3CTransformOnBuild%3Etrue%3C%2FTransformOnBuild%3E+language%3AXML) suggests that this `Always` metadata is not uncommon on such items, and so we should disable Build Acceleration out of caution whenever we detect that package is in use.

Disable Build Acceleration for Slow Cheetah

---

Directory.Packages.props
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/KnownProjectImageMonikers.cs

Fixes #8946
Bump package versions in order to be able to reference newly added image monikers for dependency nodes.

Add missing image monikers

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/IUpToDateCheckStatePersistence.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckImplicitConfiguredInputDataSource.cs

Previously the FUTDC was split between two layers, with `IUpToDateCheckStatePersistence` coming from the VS layer. The consumer didn't assume that the VS layer was present, so used `AllowDefault = true` on that import.
Since then, we moved the FUTDC into the VS layer. So now, we can assume `IUpToDateCheckStatePersistence` will always be present and non-null.

MEF component will never be null

---

src/Microsoft.VisualStudio.Editors/DesignerFramework/BaseDesignerLoader.vb
src/Microsoft.VisualStudio.Editors/DesignerFramework/DesignerWindowPaneProviderBase.vb
src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorDesignerLoader.vb
src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorRootDesigner.vb

This PR aims to make a few small changes to how the Resource Designer is loaded to make it compatible when it is opened asynchronously.
1. The undo service gets enabled twice if the docdata is loaded first.
- Fix: Instead of enabling the undo service when the OnCreate is called, enable it wherever we populate the view.
2. The view helper is registered before the `IVsWindowFrame` service is available. The hack to use BeginInvoke is not robust enough.
- Fix: Use a window frame event as a signal to register the view helper.

Fix Resource Designer For Async Open

---

src/Microsoft.VisualStudio.Editors/DesignerFramework/BaseDesignerLoader.vb
src/Microsoft.VisualStudio.Editors/DesignerFramework/DesignerWindowPaneProviderBase.vb
src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorDesignerLoader.vb
src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorRootDesigner.vb

See context in #9267 - we had bugs in both the Resource Designer and Settings Designer after #9265 was merged, and do not want to take the risk of additional issues appearing after P3. We can come back to async load at a future date.
cc: @rafaci

Revert async load changes

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml

We changed the name of the `ProjectCapability` in the SDK side, so this just renames what we expect on the rule file.
https://github.com/dotnet/sdk/pull/35710

Rename NativeAOTProperties to NativeAOT.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/LanguageServiceHost.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/Workspace.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsSolutionEventListener.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/ImplicitlyActiveConfiguredProjectReadyToBuild.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UnconfiguredProjectTasksService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/TaskCompletionSource.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsChangeTrackerTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsCompilerTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcherTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Utilities/TestUtil.cs

.NET Core defines a non-generic `System.Threading.Tasks.TaskCompletionSource`. This would be handy in .NET Framework too, so we defined our own version of this as a polyfill. However ours was in the `Microsoft.VisualStudio.Threading.Tasks` namespace.
Once we started multi-targeting to .NET Framework and .NET Core, this mismatch created issues. That was worked around with an alias. The approach in this change reduces the friction and improves discoverability of this type. With this, we won't see "ambiguous type" warnings in new code any more.

Simplify using non-generic TaskCompletionSource polyfill

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/AnalyzerDependencyFactory.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/AssemblyDependencyFactory.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/ComDependencyFactory.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/FrameworkDependencyFactory.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/PackageDependencyFactory.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/ProjectDependencyFactory.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/SdkDependencyFactory.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/SharedProjectDependencySubscriber.cs

Fixes #9281
A project might use the dependencies tree but not support a specific dependency type. This commit removes what would otherwise be a redundant component from the system in such cases by making the capabilities more specific to the relevant feature that provides that dependency.

Tighten AppliesTo filtering in dependencies tree

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/BuildUpToDateCheck.Log.cs

Fixes #9279
When incremental build failure detection is enabled, we can log a warning that includes paths and timestamps. However if FUTDC logging is disabled, the conversion from UTC to local time could be bypassed, making the log message harder to understand and potentially misleading (as there's no mention of UTC in the message).
This change fixes that issue by ensuring any times are converted to local time prior to being displayed.

Ensure warning message uses local time

---

eng/pipelines/templates/publish-symbols.yml

v1 of task is being deprecated. We are asked to move to v4.
Validating changes in official pipeline.

Move to Archive Symbols task v4

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/Handlers/AbstractEvaluationCommandLineHandler.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/Handlers/AbstractEvaluationCommandLineHandlerTests.cs

This change requires a good bit of background.
The Solution Explorer builds its tree from the evaluation model of the "active" configuration and only the active configuration, and there can only be one active configuration. Items (source files, resource files, etc.) that aren't part of the active configuration won't be displayed.
In MAUI projects, the items under the "Platforms" folder are meant to be platform-specific (by which we really mean target framework-specific), with each relevant platform getting its own subfolder. Items in the "Android" subfolder should not be included in the "iOS" build, for example.
The most straightforward way to approach this would be to conditionally include the various `<Compile>` items under Platforms based on the target framework. That would work …

Handle changes to ExcludeFromCurrentConfigurationProperty

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ApplicationFrameworkValueProvider.cs

Fixes [AB#1882665](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1882665)
When you disable and then re-enable "Application Framework" in VB WPF projects, it adds 
`<ApplicationDefinition Include="Application.xaml" />` to the project file, which is already implicitly declared and causes the build to fail. This PR removes this ApplicationDefinition when the property is re-enabled.
Note that this change leaves empty `<ItemGroup />` in the project file because the `ItemGroups` is a readonly collection available by MSBuild

Fix WPF application framework re-enable bug

---

build.cmd

Our PR builds have been hit with https://github.com/dotnet/sdk/issues/35768, where an issue in the template engine causes `dotnet new` to report an error and return an exit code. We use MSBuild to script `dotnet new` to create a solution to build on the fly, and that invocation of MSBuild takes `/warnaserror` as an argument. When MSBuild reports a warning for the exit code, that becomes an error that fails the whole build.
This issue is fixed in newer versions of the SDK, but present in the version still installed on the PR build machine images. By removing /warnaserror for the moment we hope to get past the issue in the SDK.
We will need to add /warnaserror back in later, once the build systems have a version of the SDK with the fix. Otherwise we risk other warnings being introduced …

Remove /warnaserror

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml

This adds the new property from https://github.com/NuGet/NuGet.Client/pull/5440 to nomination so that it can be read by NuGet restore.

Add CentralPackageFloatingVersionsEnabled property

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/StartupObjectValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/StartupObjectsEnumProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.VisualBasic.xaml.zh-Hant.xlf

Fixes #9262
- Don't show an entry for 'My.MyApplication' value. That is only set in the project file but should not be surfaced to the UI. Value should come from the myapp file.
- Show correct StartupObject property. ~~Seems like we had 2 properties, one in the base Application.xaml rule and another in the vb-specific Application.xaml rule. Ensured that they have different names and have a visibility condition that would show/hide the correct one, depending on the project language.~~ Interceptor had the wrong property name `InterceptedStartupObjectProperty`; it now uses the correct property name.
The only thing missing is to ensure the VB WinForms template contains the correct value in the StartupObject: right now it has 'Sub Main', but should be '[rootnamespace].My.MyApplication'.

Save startup object correctly; show correct dropdown entries.

---

eng/pipelines/templates/build-pull-request.yml

_This is a cherry-pick of 18d5bfbe4ff6732c8bc1a9d7292154b1d83f143b._
Update the PR build to install the version of the .NET runtime used in our unit test runs, specifically, 7.0.x. This wasn't previously needed, so I can only guess that the build system image we were using came with it preinstalled. It seems we can no longer count on that, so now we will explicitly install it.
Without this our unit tests fail to run due to a lack of a runtime.

Install .NET runtime

---

build.cmd
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/StartupObjectValueProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/StartupObjectsEnumProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml

Cherry-picks commits from #9300 to 17.8.x branch.
I went back to those commits to exclude changes to the localization files, which were changed due to the rename of the property from `StartupObject` -> `StartupObjectVB` -> `StartupObject`. Since there is no actual change, there's no need to bring those localization changes.
Also included the changes from #9296 to remove `/warnaserror` argument to avoid hitting https://github.com/dotnet/sdk/issues/35768 in our build PR.

[17.8] Save startup object correctly; show correct dropdown entries.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.VisualBasic.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.zh-Hant.xlf

Fixes [AzDO#1817057](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1817057/?view=edit)
Added a lock statement to the resources to prevent them from being translated.
String resources locked:
- OptionCompare.Binary|DisplayName
- OptionExplicit.Off|DisplayName
- OptionExplicit.On|DisplayName
- OptionInfer.Off|DisplayName
- OptionInfer.On|DisplayName
- OptionStrict.Off|DisplayName
- OptionStrict.On|DisplayName

Lock VB keywords from being translated.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf

Fixes [AB#1891981](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1891981)
SDK-style projects cannot set `BaseIntermediateOutputPath` within the main project file, as this is too late in the evaluation order. Attempting to do so produces:
> MSB3539 (BaseIntermediateOutputPath modified after use) is triggered incorrectly
It's not feasible for us to expose this via the property pages, so we remove it completely from the UI in this commit.

Remove BaseIntermediateOutputPath from property pages

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml

Add `NuGetAuditMode` to the properties that are sent to NuGet during nomination, for restore.
This actually should have been done in VS17.8, so this property isn't going to work in VS in 17.8, but will on the command line! 🤦‍♂️
At least this can be fixed in 17.9

Add NuGetAuditMode to NuGet nominations

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/ProjectSystemOptions.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IProjectSystemOptions.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/PackageRestoreCycleDetector.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PackageRestore/PackageRestoreCycleDetectorTests.cs

Fixes #9315
This feature is on by default and we have no reason to believe anyone would turn it off.
Remove the feature flag to reduce the number of flags.
This PR pairs with https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/510431, though we don't have to synchronise insertions.

Remove NuGet cycle detection feature flag

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/BuildUpToDateCheck.cs

Avoids the potential for treating file paths that differ only by case as different items. On Windows, they are the same path.

Use explicit string comparers

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/BuildUpToDateCheck.Log.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/UpToDate/BuildUpToDateCheckTests.cs

Fixes #9322
CPS supports projects having multiple `IBuildUpToDateCheckProvider` implementations being active. When multiple exist, any one of them can declare the project as out of date.
This can cause confusion when there are multiple checks, as the log output from this check will declare the project up to date, then another check determines the project is out of date but doesn't log anything. In such cases, the output resembles:
```
1>FastUpToDate: Project is up-to-date. (MauiLib1)
1>------ Build started: Project: MauiLib1, Configuration: Debug Any CPU ------
1>MauiLib1 -> C:\Users\emafern\source\repos\MauiApp9\MauiLib1\bin\Debug\net8.0-ios\MauiLib1.dll
```
This change detects when multiple checks are present, and includes the following output:
```
1>FastUpToDate: Note that other checks …
```

Log when multiple up-to-date checks exist

---

eng/imports/HostAgnostic.props

The Microsoft.Net.Compilers.Toolset package does not contain libraries to reference; rather, it allows us to pick up different versions of the C# compiler and associated MSBuild files than what we would normally get from the SDK. As a NuGet package, however, it is subject to the same transitive reference rules as every other package and that means that consumers of our Microsoft.VisualStudio.ProjectSystem.Managed NuGet package _also_ end up depending on Microsoft.Net.Compilers.Toolset whether or not they want to.
This means we're changing how consuming projects build in a way that has nothing to do with the functionality they need from Microsoft.VisualStudio.ProjectSystem.Managed which is not what was intended. We see this in other repos using Microsoft.Net.Compilers.Toolset; NuGet …

Specify PrivateAssets="all"

---

Directory.Build.props
docs/repo/property-pages/localization.md
docs/repo/property-pages/property-specification.md

The repo was merged into dotnet/arcade

Removed old links to dotnet/xliff-tasks repo

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/BuildUpToDateCheck.cs

Previously code would log the following message twice if FUTDC logging was enabled along with the BA feature flag.
> Build acceleration is enabled for this project via a feature flag. See "Tools | Options | Environment | Preview Features" to control this setting. See https://aka.ms/vs-build-acceleration.
This change ensures it's only logged once in the output per project.

Fix double logging of BA feature flag

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/LanguageServiceHost.cs

Fixes #9339 
Fixes [AB#1907473](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1907473)
Fixes [AB#1872265](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1872265)
Previous code would wait for prioritized project load (via `PrioritizedProjectLoadedInHost`), however this left a race where the primary workspace might still not have been initialized.
This change adds a wait for that initialization before returning the primary workspace, to ensure it's not null and our assertion doesn't fire.

Fix "Primary workspace unknown" bug in language service

---

docs/build-acceleration.md

This extends the information we have on reference assemblies in the Build Acceleration documentation.

Add more documentation about reference assemblies

---

eng/pipelines/official.yml

Update runSettingsURI vsdrop corp url to ZTN in DartLab template to improve test infrastructure authentication mechanism.

Update vsdrop corp url to ZTN in DartLab template

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/WorkspaceFactory.cs

During solution load we run evaluations but not DTB. CPS has a feature that detects when the main thread needs DTB results and allows the DTB to run before solution load completes, in order to avoid deadlocks.
While it's fine to create a dataflow subscription for build data during solution load, the joining of upstream data sources can cause CPS to accidentally think that DTB is blocking the UI thread. There's only one gate for the whole solution, so even a single project in this state will cause all projects to build.
In order to avoid this, we defer joining upstream sources until after the solution has loaded.

Defer joining ProjectBuildRuleSource until solution loaded

---

setup/Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles/CommonFiles.swr
src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/AdditionalFiles.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/AdditionalFiles.xaml
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rules/ItemRuleTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Setup/PackageContentTests.CommonFiles.verified.txt

To ensure the language service can get the same link metadata and handling as Compile items, I'm updating the VS Code project system to reuse the same logic. This requires having a new rule to grab the items during evaluation, so I'm copy/pasting the Compile item and updating as appropriate.

Add a rule for AdditionalFiles

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectFileClassifier.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs

We had a report of an error with this stack:
```
System.AggregateException: Project system data flow 'Import Tree Action: 30768406' closed because of an exception: 'path' cannot be an empty string ("") or start with the null character.
Parameter name: path.
---> (Inner Exception #0) System.ArgumentException: 'path' cannot be an empty string ("") or start with the null character.
Parameter name: path
at Microsoft.Requires.NotNullOrEmpty(String value, String parameterName)
at Microsoft.VisualStudio.ProjectSystem.PathHelper.EnsureTrailingSlash(String path)
at Microsoft.VisualStudio.ProjectSystem.Tree.ProjectImports.ImportTreeProvider.<set_ShowAllFiles>g__SyncTree|22_5(IProjectVersionedValue`1 e)
at Microsoft.VisualStudio.ProjectSystem.ActionBlockSlimSync`1.ProcessInputAsync(TInput input)
at …
```

Prevent fault in ImportTreeProvider

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/BuildUpToDateCheck.FileSystemOperationAggregator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/IFileSystem.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/IO/Win32FileSystem.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IFileSystemMock.cs

Fixes [AB#1934681](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1934681)
When a `CopyToOutputDirectory` source item is read only, MSBuild copies the file but clears the read only attribute.
Build Acceleration is a feature that mimics builds in MSBuild and therefore must also clear this flag.
Without doing so, errors can be seen in the output window during build:
```
Build started at 4:35 PM...
1>FastUpToDate: Exception copying file, scheduling MSBuild: System.UnauthorizedAccessException: Access to the path 'D:\repos\issues\Ticket1934681BuildAccelerationCopyReadOnlyFiles\Ticket1934681BuildAccelerationCopyReadOnlyFiles\bin\Debug\net8.0\ReadOnly.txt' is denied.
1>   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>   at …
```

Build acceleration clears read only flag of copied files

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/MSBuildDependencyCollection.cs

Fixes #9360
This fixes an issue where dependencies having different capitalisation between unresolved and resolved forms can cause multiple entries in the collection for the same dependency, where one of those may be out of date, causing a previous error to still be reported at the group level, despite only one dependency tree item being shown for the pair.

Use the correct string comparer in MSBuildDependencyCollection

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesTreeBuilder.cs

Two commits here, easily reviewed separately:
1. Improve chances of cancelation avoiding redundant work.
2. Avoid tree mutations/allocations in the common case that the node's icons are unchanged.

Improve perf of dependency tree updates

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/MSBuildDependencyFactoryBase.cs

Dependency nodes in the tree have various flags, which allow other code to inspect dependencies in order to interact with them (commands, attaching children, etc.).
Flags are computed via the virtual `UpdateTreeFlags` method, and certain MSBuild dependency factories override this method to include additional logic.
For package dependencies, the dependency's ID is added as a flag of form `$ID:MyPackage`.
An unresolved package dependency has item spec `MyPackage`, whereas the resolved form includes the version `MyPackage/1.2.3`. The code was incorrectly passing the resolved form, including the version. This change ensures we pass the ID, which is consistent regardless of whether the dependency is resolved or not.
This fix could, under certain timing conditions, fix issues where child nodes …

Use dependency ID in project tree flags correctly

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/MSBuildDependencyFactoryBase.cs

Fixes #9368
We have two ways of detecting whether a dependency is "implicit": via `IsImplicitlyDefined` and `DefiningProjectFullPath` metadata.
It turns out we need to consider both evaluation and build metadata when computing whether package dependencies are implicit. Packages incorrectly advertise `IsImplicitlyDefined` as `false` in build data, while its evaluation properties show the `DefiningProjectFullPath` as differing from the project's path. So this change prioritises `DefiningProjectFullPath` over `IsImplicitlyDefined`, to work around the incorrect value in build data, and includes both evaluation and build properties, to allow reading the `DefiningFullPath` value when processing a build update.

Fix calculation of implicit state for package dependencies

---

eng/pipelines/templates/build-official-release.yml

Related to [AB#1939807](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1939807).
To perform partial NGEN of our installed assemblies--where NGEN only pre-JITs the methods we need for a scenario, rather than every method--we need optimization data produced by OptProf runs. We run our own little test that produces this optimization data on every scheduled build of our `main` branch. This test is pretty straightforward--it loads a solution with a handful of projects in VS. We run the test out of our `main` branch so that it can incorporate our latest changes without the need for us to insert into VS. However, this means the test needs to install and run a build of VS that actually has those changes. We accomplish this with the …

Update "Build VS Bootstrapper"

---

src/Microsoft.VisualStudio.Editors/PropPages/PackagePropPage.vb

This code is trying to access the `UnconfiguredProject` for a given `IVsHierarchy`.
It first attempts to cast the hierarchy to `IVsBrowseObjectContext`. It looks like the intention was then to use that if present, otherwise use DTE.
The code incorrectly checks for null (`Nothing`) to see if the first conversion failed, and only then try DTE. As it was written, it would only check DTE if the first conversion succeeded, meaning that _both_ the first cast and the DTE approach have to work.
By fixing the null check, we avoid calling DTE in the common case.
There is only one caller of this private method and I've reviewed it for correctness.

Avoid DTE construction where possible

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/DependenciesAttachedCollectionSourceProviderBase.cs

The documentation was referencing a parameter that no longer exists.

Fix compiler warning

---

eng/imports/HostAgnostic.props
src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.csproj

Nuget raises the NU1701 warning when a referenced package does not contain an assembly that is compatible with the project's target framework. E.g., if the project targets .NET 7 but the package only contains assemblies targeting .NET Framework 4.7.2 then you'll get this warning. The restore will still complete but you may end up referencing an assembly that may fail to run correctly at runtime.
Early in our C# Dev Kit efforts we needed to turn off this warning because CPS didn't have .NET 7-compatible binaries yet and we _wanted_ to build against the available .NET Framework 4.7.2 binaries while we worked through our own multi-targeting plan. CPS has now had proper .NET 7/8 binaries for a while so we can turn the warning back on--but we also need to adjust our package references. …

Fix NU1701 warnings

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/PackageRestoreDataSource.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PackageRestore/PackageRestoreDataSourceMocked.cs

This PR is to add additional check to reduce the chance of restoring NuGet package with out of dated project state. it is essentially similar to the IsProjectConfigurationVersionOutOfDate check but extends the logic to additional data sources. On the other hand, because project version source is not registered as a normal data source, it does not cover the project version, so the original check is still necessary.

check other input data source version along with the project version

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsJsonEncoding.cs

To improve performance of script debugging VSCode supports a launch.json property called skipFiles . This property is a string array which allows customers to define a set of globbing patterns to skip looking for map files.  I am adding the equivalent property to launchsettings.json in Visual Studio, however the launchsettings.json serializer in the managed project system ignores string array types.  This is a small change to support properties which define string arrays.

Support string[] launchSettings.json properties

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Legacy/IDependencyModel.cs

The `IDependencyModel` interface is used by legacy dependency providers. Several of the members on that interface are no longer used, and we mark them as obsolete to advertise this fact to implementers.
This change adds `[Obsolete]` to a few more unused properties that were missed during earlier work.

Obsolete some IDependencyModel properties

---

eng/pipelines/templates/build-official-release.yml

Added a comment to Sign task with the YAML reference link. This is useful when configuring the task.

Add Sign task reference link to build-official-release.yml

---

docs/dependencies-tree.md
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/MSBuildDependencyCollection.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/MSBuildDependencyFactoryBase.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/MSBuildDependencyCollectionTests.cs

A common user complaint is the appearance of yellow triangles in the dependencies tree with no explanation as to what is wrong or how to resolve the issue.
When a design-time build fails, the dependencies tree often shows all dependencies with a yellow triangle. This happens because the evaluated value was observed, but the resolved item is not found in the build results (due to the failure).
With the semi-recent rewrite of the dependencies tree, we're taking a more cautious approach to displaying these warnings. For example, we don't show yellow triangles during project load, instead waiting until it seems that there's really a reason for concern (i.e. we received build results and the item actually was missing).
This change here takes into account whether the build failed. When it does, …

Don't show yellow triangles when DTB fails

---

.github/ISSUE_TEMPLATE/branch-checklist.md

This is follow-up to https://github.com/dotnet/project-system/pull/9387

Update repo documentation to reference Policy Service instead of FabricBot

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/LanguageServiceErrorListProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/IWorkspace.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/Workspace.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IWorkspaceMockFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IWorkspaceWriterFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Build/LanguageServiceErrorListProviderTests.cs

Historically, the `IWorkspace` type was in the host-agnostic layer, meaning that the error-reporing type was specific to the host. Since the introduction of C# DevKit, `IWorkspace` moved into the VS layer, and we no longer need this property to be of type `object`. Instead, it can be typed as `IVsLanguageServiceBuildErrorReporter2`, which simplifies consuming code.
NOTE there's a bunch more layer-change tidying that could be done here, but we'd want to validate it wouldn't impact C# DevKit first. cc @tmeschter to validate that this change is safe there.

Use strongly-typed error reporter

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/MSBuildDependencyFactoryBase.cs
tests/Common/ThrowingTraceListener.cs

Fixes the following warning in .NET 8 builds (currently only via the integration test project):
> tests\Common\ThrowingTraceListener.cs(50,101,50,122): warning SYSLIB0051: 'Exception.Exception(SerializationInfo, StreamingContext)' is obsolete: 'This API supports obsolete formatter-based serialization. It should not be called or extended by application code.' (https://aka.ms/dotnet-warnings/SYSLIB0051)
Also fixes a missing parameter doc entry.

Fix two compilation warnings in the solution

---

eng/pipelines/official.yml

We pick up certain pipeline templates providing OptProf functionality from the DartLab.OptProf repository. Currently we get these from the "main" branch of that repo, but as with other repos "main" is the bleeding edge of OptProf changes. This potentially exposes us to bugs and instability.
Instead we want to use the "Production" tag rather than the latest main. This should be better tested and more stable.
This is based on
https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/515949.

Use production OptProf tooling

---

docs/up-to-date-check-legacy.md
docs/up-to-date-check.md

- Link to the current version of the docs
- Introduce a separate doc for legacy FUTDC, and cross-reference
- Improve documentation on capturing binlogs

Fix link to vcxproj FUTDC docs

---

Directory.Packages.props
src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj

Parallel work is attempting to bump Roslyn packages, but hitting failures. Here we make a few upgrades in an attempt to isolate the cause of those issues.
---
Bump some package versions.
Also, the particular version of the `Microsoft.CodeAnalysis` package we reference includes both `net6.0` and `net7.0` versions. Here we bump the one we reference, so that we're using the latest version available.

Upgrade packages

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets

Fixes #9433
When a project specifies `GeneratePackageOnBuild`, additional items must become inputs to the FUTDC. Without this, it's possible to change a `Content` item, for example, that has `Pack="true"` metadata, and not have those changes included in the generated NuGet package during builds.
This change includes all the items that NuGet would include in the package as inputs to the FUTDC.
Note that ideally we would only include these items when `GeneratePackageOnBuild` was `true`, however we force the property to `false` during design-time builds in `GeneratePackageOnBuildDesignTimeBuildPropertyProvider`, so instead we add these items unconditionally. It's possible that this could trigger a few extra builds for some uncommon project configurations, but that seems unlikely and is …

FUTDC detects changes to Pack items

---

eng/pipelines/optprof-scheduled.yml

I was missing some context on my last PR and missed renaming the value to our team's resource pipeline name. Here I'm updating to the correct name.

Update resource pipeline name.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/ProjectFileOrAssemblyInfoPropertiesProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/AssemblyAttributeProperties/AbstractProjectFileOrAssemblyInfoPropertiesProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/IInterceptingPropertyValueProviderMetadata.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/IInterceptingPropertyValueProviderMetadata2.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/InterceptedProjectPropertiesProviderBase.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/InterceptedPropertiesProviderBase.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ProjectFileInterceptedProjectPropertiesProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ProjectFileInterceptedViaSnapshotProjectPropertiesProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/UserFileInterceptedProjectPropertiesProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/UserFileWithXamlDefaultsInterceptedProjectPropertiesProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI/net472/PublicAPI.Shipped.txt
src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI/net8.0/PublicAPI.Shipped.txt
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IInterceptingPropertyValueProviderFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IInterceptingPropertyValueProviderMetadataFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/AssemblyInfoPropertiesProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptingProjectProperties/AssemblyOriginatorKeyFileValueProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptingProjectProperties/InterceptedProjectPropertiesTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptingProjectProperties/TargetFrameworkValueProviderTests.cs

This PR is to address further issues showing in performance traces.
Due to the code is in the hot path to load solution, some further works:
1, first export was added twice in the list, which might be the reason of complex LINQ code later. This PR fixes the issue, but I keep the original LINQ code just to prevent changing behaviors.
2, Use MEF metadata instead of reflection APIs. MEF can cache strings efficiently, while reflection is slow, and also the code would load components then checking the capabilities, which is incorrect.
3, prevent using LINQ in this hot path, i updated it to a normal loop.

Further fixes in intercept provider supporting code

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets

Reverts dotnet/project-system#9437
This is causing issues:
1. Some projects are seeing errors about a missing `_GetPackageFiles` target.
2. It can lead to overbuild (see comments in the original issue which has since been re-openend).
I'll take another swing at this shortly.

Revert "FUTDC detects changes to Pack items"

---

setup/Directory.Build.props
setup/VisualStudioEditorsSetup/VisualStudioEditorsSetup.csproj

Fixes AB#1987317
We currently specify that Microsoft.VisualStudio.Editors.dll and Microsoft.VisualStudio.AppDesigner.dll should be NGEN'd for all architectures. This means that on an x64 system NGEN will run twice for each: once to create a 32-bit version, and once to create a 64-bit version. As we no longer ship a 32-bit version of VS the former is unnecessary, and we're just wasting time and resources on that NGEN and potentially delaying useful NGEN work.
This commit removes the `<NGenArchitecture>all</NGenArchitecture>` MSBuild property affecting these binaries. Without this property being set, NGEN will default to the current system architecture (e.g. AMD64 on an AMD64 system).

Don't NGEN for all architectures

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/TemporaryPropertyStorage.cs

This change passes the captured state on the stack, to avoid a heap-allocated closure object. The delegate will then be cached and reused.

Avoid per-call lambda allocation

---

tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/UpToDate/BuildUpToDateCheckTests.cs

Fixes #8642.
Re-enable a number of Fast Up-to-Date Check unit tests that have been disabled for a while. I am no longer able to reproduce the problematic behavior that originally led me to disable them; it looks like the underlying issue (non-deterministic output) has been resolved.

Re-enable unit tests

---

docs/build-acceleration.md
spelling.dic
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/BuildUpToDateCheck.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/CopyItemAggregator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/ICopyItemAggregator.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.Designer.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSResources.resx
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/xlf/VSResources.zh-Hant.xlf
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/UpToDate/BuildUpToDateCheckTests.cs

Fixes #9001
Build Acceleration gathers items to copy from referenced files, transitively. Each copy item includes a relative path, to which the file should be copied (relative to the output path of the project being built).
It's possible for multiple projects to specify copy items with the same relative target path. When this occurs, only one file will end up in the output directory at that location. The exact rules defining which file "wins" in this case are complex. The situation is relatively rare however.
This change makes Build Acceleration disable itself in cases where duplicate relative target paths exist. The project will fall back to calling MSBuild so that the correct behaviour is guaranteed.
---
Note to reviewers: There are some small cleanup commits that make the overall diff …

Build Acceleration handles duplicate copy items

---

.github/policies/resourceManagement.yml

- Move the current milestone to 17.11, to stop incorrectly setting merged PRs in 17.10
- Extend the number of labels we sync from issues to PRs when they merge
- Add some space between tasks to make them easier to read
- Update the list of milestones assigned to PRs when they merge to only those present in the repo, order them descending, and document how to keep this list up-to-date with a link to the current branches

Update resource management rules

---

Directory.Packages.props
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManager.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/BuildUpToDateCheck.Subscription.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/UnconfiguredProjectFactory.cs

Fixes https://github.com/dotnet/project-system/issues/9424
We bump the VSSDK to 17.11. As part of this, we receive warnings to replace `AsyncSemaphore` with `ReentrantSemaphore`. This PR includes that recommended change.

Bump VSSDK version

---

Directory.Packages.props
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckHost.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj

Fixes #9424
Replaces API usage:
- From `_vsShell.GetProperty((int)__VSSPROPID.VSSPROPID_IsInCommandLineMode, ...)`
- To `vsAppId.GetProperty((int)__VSAPROPID10.VSAPROPID_IsInCommandLineMode, ...)`
The latter is free-threaded, as described in: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/40079/Free-threaded-replacements
This requires bumping several VS packages to 17.11, in order to use `__VSAPROPID10.VSAPROPID_IsInCommandLineMode`.
Also, `IVsAppCommandLine` is free-threaded, so don't use `IVsUIService` for that, as given in: https://github.com/microsoft/VSSDK-Analyzers/blob/614165cfdca3245dd8c19530bd054e24cd80be32/src/Microsoft.VisualStudio.SDK.Analyzers.CodeFixes/build/AdditionalFiles/vs-threading.MembersRequiringMainThread.txt#L84
Together, these changes mean we don't …

Avoid main thread switch in UpToDateCheckHost

---

Directory.Packages.props
eng/imports/HostAgnostic.props
spelling.dic
src/Microsoft.VisualStudio.AppDesigner/Microsoft.VisualStudio.AppDesigner.vbproj
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/Handlers/AdditionalFilesItemHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/Handlers/CommandLineNotificationHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/Workspace.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectThreadingServiceFactory.ProjectThreadingService.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IProjectThreadingServiceFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/AssemblyInfoPropertiesProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Utilities/SynchronizationContextUtil.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/IWorkspaceProjectContextMock.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/WorkspaceTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/CSharp/RenamerTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/RenamerTestsBase.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rename/VisualBasic/RenamerTests.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1881089
Roslyn recently introduced async API for obtaining and releasing "batch" objects for applying updates in https://github.com/dotnet/roslyn/pull/72424.
This change increases the package versions, uses the newer API, fixes some obsolete usages, and gets things building by adding a few package references in order to break the tie on some assembly version conflicts during build.
---
This is another iteration of https://github.com/dotnet/project-system/pull/9455, which was reverted due to issues it created during signing. Unlike that prior PR, this does not remove `Microsoft.VisualStudio.Internal.MicroBuild.Swix`.

Avoid contention in Roslyn language service

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManager.cs

Fixes [AB#2065632](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2065632)
After updating the VSSDK in #9460, we converted a bunch of usages of `AsyncSemaphore` to `ReentrantSemaphore`.
This has caused an issue in hot reload.
The new semaphore class has several modes. We change from disallowing re-entrancy, so allowing freeform re-entrancy.

Allow re-entrancy in ProjectHotReloadSessionManager's semaphore

---

src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerView.vb

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2060273
The two combo boxes at the top of property pages - Configuration and Platform - do not respond to system-wide font changes. I am adding screenshots taken after increasing the text size via Accessibility -> Text size Windows setting.
**Before:**
**After:**
The fix implements the logic already in place for other controls.

Make PropPageDesignerView update font on WM_SETTINGCHANGE

---

eng/pipelines/templates/analyze-compliance.yml
eng/pipelines/templates/build-official-release.yml

Unit test, integration test, and setup dlls all fall under this banner, as well as the vs bootstrapper and a file produced under the SymStore directory path.
successful build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9655384&view=logs&j=3de96e8d-b8d1-5108-47b8-f6a54739db67&t=ae45fcc0-4c88-53b1-520c-1a3469c00c6b

Removes files that do not need code signing checked 

---

src/Microsoft.VisualStudio.Editors/VSPackage.resx
src/Microsoft.VisualStudio.Editors/xlf/VSPackage.cs.xlf
src/Microsoft.VisualStudio.Editors/xlf/VSPackage.de.xlf
src/Microsoft.VisualStudio.Editors/xlf/VSPackage.es.xlf
src/Microsoft.VisualStudio.Editors/xlf/VSPackage.fr.xlf
src/Microsoft.VisualStudio.Editors/xlf/VSPackage.it.xlf
src/Microsoft.VisualStudio.Editors/xlf/VSPackage.ja.xlf
src/Microsoft.VisualStudio.Editors/xlf/VSPackage.ko.xlf
src/Microsoft.VisualStudio.Editors/xlf/VSPackage.pl.xlf
src/Microsoft.VisualStudio.Editors/xlf/VSPackage.pt-BR.xlf
src/Microsoft.VisualStudio.Editors/xlf/VSPackage.ru.xlf
src/Microsoft.VisualStudio.Editors/xlf/VSPackage.tr.xlf
src/Microsoft.VisualStudio.Editors/xlf/VSPackage.zh-Hans.xlf
src/Microsoft.VisualStudio.Editors/xlf/VSPackage.zh-Hant.xlf

When a user right-clicks a `.resx` file in Solution Explorer and selects "Open With..." they are presented with a list of editor factories.
With the forthcoming introduction of the Resource Explorer, users are now presented with (among other options):
- "Resource Explorer"
- "Managed Resources Editor"
The second is the legacy experience. This change appends a "(Legacy)" to the name of the editor to help differentiate between the two, and to help users find the improved editor.
---
This is the UI that will be updated by this change:

Rename the legacy "Managed Resource Editor" editor factory

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ProjectContextCodeModelProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryEventName.cs

CodeModel is part of DTE and should not be being used in core VS scenarios. However extensions and some legacy components may still be hitting this code path.
We want to understand scenarios in which these code paths are used, and hope to use that information to improve startup performance when initializing language services.

Send telemetry when CodeModel is used

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets

Related to PR #9470.
After PR #9470, VS and C# Dev Kit will attempt to collect NuGet audit suppression items via the `CollectNuGetAuditSuppressions` target. However, this target new to the 8.0.400 version of the .NET SDK. If a project is using an older version of the SDK our design-time build will now fail with complaints that the target doesn't exist.
To work around this, here we update Microsoft.Managed.DesignTime.targets to include a no-op version of the target. This file ships with VS and the C# Dev Kit, not the SDK, and so we can guarantee that the target will always be present when we need it. The real definition in the SDK is in NuGet.targets; this file is imported _after_ Microsoft.Managed.DesignTime.targets and so the real definition, when it exists, will automatically replace …

Add CollectNuGetAuditSupressions target

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml

Add `SdkAnalysisLevel` and `UsingMicrosoftNETSdk` to the properties that are sent to NuGet during nomination, for restore.
Related PR : https://github.com/NuGet/NuGet.Client/pull/5833

Add `SdkAnalysisLevel` and `UsingMicrosoftNETSdk` to NuGet nominations

---

Directory.Packages.props
eng/imports/Versions.props
src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Legacy/LegacyDependencySubscriber.cs

Insertions from dotnet/project-system into dotnet-project-system-vscode automatically update the CPS version of that repo to match the version used in this repo. I need a newer version in dotnet-project-system-vscode for some feature work, so to avoid problems I'm updating it here as well.
This also allows us to remove a `PackageReference` that was needed just to resolve a Component Governance issue. The change also removes an unnecessary "using" that the build started to warn about.

Update CPS to version 11.17.207

---

eng/imports/Versions.props
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProjectTypeRegistration.cs

Fixes #1821
This change takes a new version of CPS, and populates a new property on the `ProjectTypeRegistrationAttribute` that specifies the preferred project type GUID for persistence.
This helps avoid an issue where occasionally VS would change the project type GUID in the solution file, as now the project can explicitly define when it wants to use a different project type GUID for persistence, as we do for managed C#/VB/F# projects.

Specify preferred persistence GUID for project types

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.FSharp.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.FSharp.xaml.zh-Hant.xlf

Fixes #9469
Fixes https://github.com/dotnet/fsharp/issues/13714
F# projects don't use the same warning levels as C#/VB projects.
Previously, the same set of levels were used on all project types. This change adds an explicit set for F#.

Specify warning levels for F# projects

---

.github/policies/resourceManagement.yml

`main` is now targeting 17.12. Update the config so that merged PRs are incorrectly assigned to the 17.11 milestone on GitHub.
This helps prevent confusion about what VS version a fix is in.

Bump milestone tracking for merged PRs to 17.12

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hant.xlf

C# 13 introduces a warning wave that is enabled by warning level 8. Add the option so it appears in the UI.

Add a warning level property entry for level 8

---

docs/repo/loading-components-with-projects.md

Fixes a simple typo, making it easier to find these docs when searching for the attribute.

Fix minor typo in documentation

---

docs/build-acceleration.md

Fixes #9426
In 17.8 we changed the defaults for Build Acceleration. We didn't update the docs to reflect that. This changes the guidance around configuring Build Acceleration, and steers the reader towards the validation steps.

Update Build Acceleration documentation around opt-in/out

---

docs/design-time-builds.md

This puts the VS2022 instructions at the top, increasing the chance that users following these instructions produce high-fidelity binlogs.

Reorder DTB documentation sections

---

docs/build-acceleration.md
src/Microsoft.VisualStudio.ProjectSystem.Managed/StringComparers.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/StringComparisonTests.cs

These two utility classes should have the same members, with equivalent values. This change adds missing properties to both classes, and adds a test to ensure that they're kept in sync in future.
(I made a similar test for Aspire so copied it here.)

Test that StringComparers and StringComparisons are kept in sync

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/LanguageServiceHost.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/VSShellServices.cs

During solution load, there is a per project switch to the main thread to determine if the language service needs to be initialized. The APIs for this were switched to be safe to call from a background thread and we only need to check once since this can't change once the process is started.

Avoid repeated switches to main thread to check if in command line mode

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hant.xlf

Fixes #9246
Adds definitions for three properties that control how NuGet Audit is presented to the user, allowing them to configure the feature to their liking.

Add Project Properties UI for NuGet Audit settings

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/MSBuildDependency.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/MSBuildDependencyCollection.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/MSBuildDependencyFactoryBase.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/MSBuildDependencyCollectionTests.cs

Fixes #9230
Generally, we require MSBuild-based dependencies to exist in evaluation before they're shown in the tree. Items that exist only in build data are not displayed.
Analyzers opt out of this default behaviour by setting `ResolvedItemRequiresEvaluatedItem` to false. Analyzer references can be added to the project within MSBuild targets and will appear as resolved in the tree.
When such an item is removed from build data, we only removed from the tree when no evaluation data was present.
There was a bug in this code. It was checking for an evaluated item in the previous data, where it should have been checking in the current data. It's a simple fix.
Added more test cases. Made a function change as part of that testing to restore caption and file path on a dependency that becomes …

Fix lingering analyzer node with warning

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/FSharp/FSharpCommandLineParserService.cs

Unlike exports of interfaces, it's harder to find the consumer of an exported function. This change adds a comment showing where to find this import.
Also, some minor formatting.
(Change made following a conversation with @0101.)

Document where exported function is imported

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/LanguageService.xaml

The property determines the full paths of source-generated files which needs to be tracked by Roslyn project to support EnC.

Make build property CompilerGeneratedFilesOutputPath accessible to Roslyn project

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Setup/SetupComponentReferenceData.cs

Extends our hard-coded mapping from `TargetFrameworkVersion` to Visual Studio setup component ID so that targeting .NET 9 will prompt to install the relevant runtime via IPA (in-product acquisition).
The component is defined in https://dev.azure.com/devdiv/DevDiv/_git/VS?path=%2Fsrc%2FSetupPackages%2FGroup%2FComponent%2FDotNetCoreRuntime.9.0%2Fcomponent.swr (MS internal)
#8186 is tracking the removal of this hard-coded data, which requires work from the SDK (tracked in https://github.com/dotnet/sdk/issues/25575).

Add setup component ID for .NET 9

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/PackageRestoreConfiguredInputDataSource.cs

The base class does exactly the same logic as this class. Doing this here adds a little size to the object (not a big deal) and is potentially confusing (a bigger deal).

Remove unused field

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Frameworks/SupportedTargetFrameworksEnumProvider.cs

Fixes: https://developercommunity.visualstudio.com/t/Project-Properties-GUI-doesnt-show-avai/10770236
This change fixes the case where we show an empty list of target frameworks in the Project Properties UI.
When there's no `<TargetFramework>` or `<TargetFrameworks>` properties, we now show the list of `.NETCoreApp` target frameworks.
This assumes the user is trying to manually migrate from legacy CSPROJ to SDK-style, and has not added the property to their project. This change allows them to do that.
The real change is in e73bb1923c04124f5dab4dbc5799d71ab2563934. Other changes modernize the code in this area and improve performance in a few cases. Probably best reviewed commit-by-commit, as each commit is small and clear.

Fix showing empty target framework options in the Project Properties UI

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Frameworks/SupportedTargetFrameworksEnumProvider.cs

Small tweak following #9564.
Previously the ordering was "natural" ascending. This created a block with ".NET 5+" items at the top, and ".NET Core" items below, however the newest .NET item (e.g. ".NET 9") would be in the middle of the list.
The change here adds sorting by group, then by version, and makes that version ordering descending. This means that the latest and greatest version is always at the top of the list.

Improve ordering in target framework dropdown

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Frameworks/SupportedTargetFrameworkAliasEnumProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/LanguageServiceHost.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/Workspace.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/WorkspaceFactory.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Setup/SetupComponentProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesTreeBuildRuleRequirements.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckImplicitConfiguredInputDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/PackageRestoreConfiguredInputDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/AnalyzerDependencyFactory.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/AssemblyDependencyFactory.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/ComDependencyFactory.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/FrameworkDependencyFactory.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/PackageDependencyFactory.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/ProjectDependencyFactory.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/MSBuildDependencies/SdkDependencyFactory.cs

Export initial rules subscriptions

---

Directory.Packages.props

The 9.0.0-rc.2.24473.5 version is causing issues in CI due to package downgrades being reported as errors. Building locally suggests that 8.0.0 is fine for our solution, so this drops the version.

Drop dataflow package version to 8.0.0

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/Snapshots/RestoreBuilder.cs

The nested ToReferenceItem method was creating an ImmutableArray, but not using it. Went ahead and removed that line, and then since that method was only a single line, just pushed it's remaining contents to the caller.
There was a surprising amount of allocations going on in this line, which I happened to find while looking at the solution load section of a speedometer trace. Overall, this was about 0.3% of allocations in this profile.
*** relevant allocations from the speedometer profile addressed ***

Remove an unnecessary allocation from RestoreBuilder.ToReferenceItems

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/LanguageService.xaml

Reverts dotnet/project-system#9544
This change was triggering a failure in Roslyn around use of `EmitCompilerGeneratedFiles`, leading to project faults resembling:
```
System.ArgumentException: Absolute path expected
Parameter name: path
at Microsoft.CodeAnalysis.CompilationOutputInfo.WithGeneratedFilesOutputDirectory(String path)
at Microsoft.CodeAnalysis.Workspaces.ProjectSystem.ProjectSystemProject.<>c__DisplayClass69_0.<set_GeneratedFilesOutputDirectory>b__0(Solution s)
...
```
At the start of October, Roslyn started requiring an absolute path here:
https://github.com/dotnet/roslyn/pull/75311/files#diff-8440787c9215f81fa8cabe9072d5ab0598251313a4480cfca075041ceed8a5bbR41-R44
But by default, the SDK provides a relative path (and indeed all online examples show relative paths here). Only …

Revert "Make build property CompilerGeneratedFilesOutputPath accessible to Roslyn project"

---

.editorconfig
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/AbstractReferenceHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/UpToDateCheckStatePersistence.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PackageRestore/PackageRestoreCycleDetectorTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Rules/MiscellaneousRuleTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/UpToDate/BuildUpToDateCheckTests.cs

Following a recent PR that improved performance by removing the initialization of a value assigned to an unused variable, I wanted to enable more analyzers to prevent this in future.
Unfortunately there's not an analyzer that'll catch all instances of this. Within VS we have `IDE0059` already, and this PR turns it into an error (rather than a hint) but it won't catch everything.
The things it did flag are fixed here.

Remove some unused locals

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/LanguageService.xaml

Following the fix in https://github.com/dotnet/roslyn/pull/75674, we can revisit this change.
This PR reverts dotnet/project-system#9579, reinstating #9544.

Revert "Revert "Make build property CompilerGeneratedFilesOutputPath accessible to Roslyn project""

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/LanguageServiceErrorListProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsCompiler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate/BuildUpToDateCheck.Log.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Telemetry/DesignTimeTelemetryLogger.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/PackageRestoreCycleDetector.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Telemetry/SdkVersionReporter.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/ITelemetryOperation.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/ITelemetryService.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/ManagedTelemetryService.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/ITelemetryServiceFactory.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Telemetry/ManagedTelemetryServiceTests.cs

(Pulled from other work, to keep the diff for that work smaller.)
We have some APIs that wrap telemetry operations, and they were imposing an artificial restriction on telemetry property values. A null value is perfectly valid.
Changing callers of this method to use collection literals cleaned those call sites up a little, avoiding the need for casts. Apparently there's better type inference in that form.
Also some other minor tweaks.

Telemetry values can be null

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ProjectAndExecutableLaunchHandlerHelpers.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/ProjectAndExecutableLaunchHandlerHelpersTests.cs

Replace backward/forward slash in ProjectAndExecutableLaunchHandlerHelpers.GetOutputDirectoryAsync with system default

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj

`Microsoft.VisualStudio.ProjectSystem.Managed` also have indirect dependency over MessagePack

Pin MessagePack version in Microsoft.VisualStudio.ProjectSystem.Managed

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/IPackageRestoreCycleDetector.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/PackageRestoreCycleDetector.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/PackageRestoreDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/PackageRestoreUnconfiguredInputDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/Snapshots/PackageRestoreUnconfiguredInput.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PackageRestore/PackageRestoreCycleDetectorTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PackageRestore/PackageRestoreDataSourceTests.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1951646
We have a feature that attempts to detect patterns in NuGet restore data, flagging these as a runaway restore cycle, stopping the cyclic behaviour, and alerting the user.
Test teams found a scenario where continuously changing active configuration (i.e. toggling between Debug and Release several times) would trigger the cycle detection logic incorrectly. This was causing failures in automated test runs.
This only happens when restore data differs between configurations. A new console app with some simple packages added does not trigger this. The .NET Project System repo would, however.
This commit fixes the issue by including the active project configuration in the dataflow data, such that the cycle detector resets its …

Changing active configuration should not trigger restore cycle detection

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/DesignTimeBuilds/DesignTimeBuildLoggerProvider.cs

During DTBs, a target may run more than once. A previous change used the target name as a key in a dictionary, however in some cases this would throw and exception due to having duplicate dictionary keys.
This changes the form of the data to an array of arrays. It's potentially harder to write Kusto queries against, but preserves all the information within the data and avoids the exception.

Fix exception due to duplicate keys

---

docs/design-time-builds.md

This PR updates `docs/design-time-builds.md` as it was missing some details, and had some outdated information. The content was rewritten in a few places to be clearer and provide more context.
Docs in the `/docs` folder are aimed at users of the project system. This PR moves the most relevant customer-facing content to the front of the doc, particularly now we are surfacing DTB errors more prominently in VS.
This change adds the verbatim info bar text to the doc, so that searches can find it more easily.
The instructions for capturing binlogs were refined to be more targeted and succinct. Instructions for earlier versions of VS were collapsed in a summary/details region.
Outdated instructions for performance analysis have been rewritten to reference features in the structured log viewer. …

Improve docs around design-time builds

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSession.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManager.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/FrameworkReferenceAssemblyAttachedCollectionSourceProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectLaunchTargetsProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/HotReload/ProjectHotReloadSessionManagerTests.cs

Addresses some build warnings and other IDE warnings seen while reading through code today.
- Remove duplicate package reference warning during builds
- Remove redundant using directive warnings during builds
- Remove an unused constructor parameter injected via MEF
- Fix invalid paths in test data, due to incorrect escaping

Small fixes

---

Directory.Packages.props
eng/imports/Versions.props
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectLaunchTargetsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/Handlers/DynamicItemHandler.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/Workspace.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ProjectAndExecutableLaunchHandlerHelpers.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/ApplicationPropertyPage/ApplicationIconValueProvider.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ProjectLaunchTargetsProviderTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/Handlers/CompileItemHandler_CommandLineTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/Handlers/MetadataReferenceItemHandlerTests.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/WorkspaceTests.cs

Avoids calling `Path.GetDirectoryName` in a bunch of places, which will allocate a new string for each call. The new extension method in CPS provides a singleton string for the project.
Needs https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/595076 or newer to insert before being merged.

Use new GetProjectDirectory method to reduce string allocations

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/Workspace.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/WorkspaceTests.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1833278
In #8321, we optimised how we handle Roslyn projects in the language service during configuration switches, such as from Debug to Release.
Before that PR, we maintained different pipelines for each configuration. That PR re-uses the same pipeline between configurations, instead applying a delta representing the switch. This makes configuration switches a lot faster.
Project data flows through with version numbers, and each configuration tracks versions to ensure that evaluation and build data is applied with correct sequencing.
The previous PR introduced the chance for an unexpected regression in configured project version, which would lead to an exception that'd trigger a NFE and gold bar in VS.
> Attempted to push a …

Fix NFE about version regression on configuration switch

---

docs/design-time-builds.md
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/Snapshots/VsTargetFrameworkInfo.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/PackageRestoreConfiguredInputDataSource.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/Snapshots/RestoreBuilder.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/Snapshots/RestoreLogger.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/PackageRestore/Snapshots/TargetFrameworkInfo.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/CollectedPrunePackageReference.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/CollectedPrunePackageReference.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/RuleExporter.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/PackageRestore/Snapshots/RestoreBuilderTests.cs

Design at https://github.com/NuGet/Home/blob/dev/accepted/2024/prune-package-reference.md. 
This adds support for `PrunePackageReference` with a `Version` attribute and the `RestoreEnablePackagePruning` property. 
I know in the past we've had to do certain things to get CDK working. cc @tmeschter

Add PrunePackageReference support in project-system

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets

Fix invalid XML in design-time targets

---

tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/DesignTimeTargets/DesignTimeTargetsTests.cs

We recently had an issue where a design-time target was merged containing invalid XML. These targets are crucial to almost everything the project system does, so a failure in them completely breaks the IDE.
In this change we add a unit test to validate that our C#/VB/F# design-time targets files can be correctly evaluated, and can build a simple target. This ensures both that they contain valid XML with valid MSBuild semantics.

Test that design-time targets evaluate and build

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UI/InfoBars/VsInfoBarService.cs

When signalling project close to an info bar entry, if there are no other remaining projects associated with that info bar, it will be removed from the collection. That triggers an exception.
The fix is to make a defensive copy before enumerating, so that the original can be safely modified while the copy is enumerated.

Fix "collection modified" exception

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/ContextAndRuleProviderState.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/IProjectState.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/QueryProjectPropertiesContext.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Unshipped.txt

The TS/JS team would like to add a version of the launch profiles UI for JSPS projects that reads/writes from` launch.json `rather than `launchsettings.json`. By making `ContextAndRuleProviderState`, `IProjectState`, and `QueryProjectPropertiesContext  `public, we can reuse several of the QueryDataProviders dotnet has already implemented to populate the launch profiles UI.
For example, the [UIPropertyFromRuleDataProducer](src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/UIPropertyFromRuleDataProducer.cs) class is expecting context of the type `ContextAndRuleProviderState`, and I would like this class to populate UI properties for the JSPS scenario as well.
I have already confirmed that these changes will allow the launch.json UI to work properly:

Expose ContextAndRuleProviderState, IProjectState, and QueryProjectPropertiesContext to Support JSPS Launch Profiles UI

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Menus.vsct

`SlnExplorerGuid` was unused and is removed in this change. `guidSolutionExplorerToolWindow` (which has the same value) is actually used.
(Seen while debugging something earlier in the day with Zewditu.)

Remove unused GuidSymbol from VSCT file

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/LanguageServiceHost.cs

`LanguageServiceHost` uses its own JTF collection and factory to track its work.
This class derives from `OnceInitializedOnceDisposedAsync`, which also has its own collection and factory.
@lifengl recently noticed this while investigating a hang and suggested that we reuse the base class's objects to reduce allocations and potentially even help avoid deadlocks.

Avoid extra JTF collection/factory

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build/LanguageServiceErrorListProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/AbstractProjectState.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/PublishItemsOutputGroupProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/DebugProfileEnumValuesGenerator.cs

This avoids the overhead associated with the type's re-entrancy prevention in cases where we the code cannot call itself.
See https://github.com/microsoft/vs-threading/pull/1265 for more information.
@lifengl proposed this improvement as part of #9623. One occurrence is addressed in that PR. Others are here in this PR.

Set AsyncLazy.SuppressRecursiveFactoryDetection to true

---

src/Microsoft.VisualStudio.Editors/MyApplication/MyApplicationDataSerializer.vb

Fixes [ADO#2300157](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2300157)
@drewnoakes fixed a typo in the name of the element used for HighDpiMode serialization, so the deserializer now picks up that value. However, there is a type mismatch. The value is serialized as a boolean, but the deserializer converts it to an Int32. The exception thrown by this failed conversion causes problems when editing VB WinForms project properties in Visual Studio.
The value is now serialized as Int32.

Fixed serialization of the HighDpiMode value

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/LaunchProfiles/LaunchProfileActionProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/ProjectActionProvider.cs

The project team is working on supporting multiple query providers for different project systems. The JavaScript project team aims to add launch profiles action providers. Currently, the issue is that the .NET provider takes precedence, preventing their provider from being invoked. The AppliesTo attribute will be used to select the appropriate provider based on capability. At present, we are not reading this attribute on the query side, so it will not have any impact.

Adding AppliesTo attribute to query providers

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/DesignTimeBuilds/DesignTimeBuildLoggerProvider.cs

We see these errors popping up during regular operations such as branch switches. I'd hoped that they would present themselves as cancellations, however we don't see ` BuildCanceledEventArgs` in our logger. These are advertised as real failures. There's nothing the user can do about these, so it's not helpful to tell the user about them.
I hope to revisit this in 17.14 to see if there's still a way to provide helpful warnings when actionable errors occur, without any noise from internal and unactionable errors.

Disable DTB error info bars for now

---

eng/pipelines/templates/generate-localization.yml
eng/tools/OneLocBuildSetup/OneLocBuildSetup.csproj

Fixes build failures during the localization stage on the insertion PR pipeline.

Use .NET 8 for OneLocBuildSetup

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/Build/BuildUtilities.cs

The comment for `RemovePropertyValue` incorrectly states that the value is renamed.
Further `property` is declared way before it is used.  Moved the declaration closer to its first usage.
Ran build.cmd.  Build passed with flying colors.

Fixing a comment and moving one line of code

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/LaunchProfileProjectActionProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Query/PropertyPages/ProjectActionProvider.cs

Adding an` [AppliesTo] `filter to `ProjectActionProvider ` in [this](https://github.com/dotnet/project-system/commit/3ea13d2998039c8673209497edde8df411a9a182) PR broke the functionality of updating project properties for JSPS. JavaScript projects are relying on dotnet's properties provider for this. Removing the `[AppliesTo] ` attribute fixes this problem.

Fix 'SetEvaluatedUIPropertyValue' is not supported Exception in JSPS

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.cs.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.de.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.es.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.fr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.it.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ja.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ko.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pl.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.pt-BR.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.ru.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.tr.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hant.xlf

This adds the ability to override the AssemblyTitleAttribute for the project's output assembly. Without this, the value is always hard-coded to that of the project's file name.
Requested in https://developercommunity.visualstudio.com/t/Cannot-set-assembly-title-AssemblyTitle/10445147

Add 'Assembly Title' to the project properties UI

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.VisualBasic.DesignTime.targets

Defining a new capability to turn off the default namespace calculation logic in VB projects.
This matches the behavior in classic VB projects.
The new capability can be turned off by specifying this property in the project file:
```xml
<DisableNoDefaultSingleFileGenNamespace>true</DisableNoDefaultSingleFileGenNamespace>
```

New capability to turn off default namespace logic for SFG in VB

---

eng/Build.proj
eng/pipelines/templates/build-official-release.yml
eng/pipelines/templates/build-pull-request.yml
global.json
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/LaunchProfilesDebugLaunchProvider.cs
tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/HotReload/ProjectHotReloadSessionTests.cs

This file was added in #9649 to pin a specific SDK version in order to work around issues in CI builds. This change removes that, in the hope that CI images no longer experience this issue. Having a `global.json` file requires keeping it updated for security reasons, and we'd rather avoid that overhead here, and let the CI machines do the right thing by default.

Remove global.json

---

Directory.Packages.props
eng/imports/Versions.props
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/Workspace.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UnconfiguredProjectTasksService.cs

Reverts dotnet/project-system#9672
This introduced a regression from Roslyn starting too early.

Revert "Register background task critical to load projects."

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/LanguageServiceHost.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/VsSafeProjectGuidService.cs

This PR is to adjust the logic so the language service pipeline can be established earlier in common cases.
Today, the code path waits project to be fully loaded to ensure the ProjectGuid would not be changed. The additional logic added here is to check whether project and solution has already agreed with each other on the ProjectGuid. In a few cases, we will still fall back to the original logic, including new projects, newly added projects, or potentially there is a conflicting between solution and project.

Allow language service to get ProjectGuid earlier in common cases.

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesTreeProvider.cs
src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs

Fixes #2707
Lifeng reported that calling `GetActiveConfiguredProjectExports` on the base class was taking 0.5 seconds of CPU while loading Roslyn.sln.
This change uses `IActiveConfiguredValue<>` to cache the instance, to improve performance while building dependencies trees across the solution during solution load.
The same optimisation is applied to `ImportTreeProvider` as well.

Improve perf of accessing configured values in tree, particularly during solution load

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets

This only opts Data Source Windows in for WPF/WinForms projects and nothing else - it doesn't nothing for other projects.
See https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/651666 for more details.
I tested this, and this works as expected, hides for any project except for WinForms/WPF.

Only opt into data source for WinForms/WPF

---

Directory.Packages.props
eng/imports/VisualStudio.props

Onboard to VSSDK analyzers, specifically to see warnings from [VSSDK008](https://github.com/microsoft/VSSDK-Analyzers/blob/main/doc/VSSDK008.md) which reveals UI thread affinity in MEF part construction

Onboard to VSSDK analyzers

---

src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/Workspace.cs

GetPropertyValue is optimized in the cache mode. 
It would read data directly without causing extra lazy structure (ProjectPropertyInstance) to be created.

use GetPropertyValue instead of GetProperty().EvaluatedValue

---

tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Build/SolutionBuildManagerTests.cs

This test would fail with:
> Second build should start after the first build
Based on the comparison:
```c#
buildStartTimes[1] > buildStartTimes[0]
```
These `buildStartTimes` values were `DateTime` instances, captured using `DateTime.UtcNow`. That can be problematic when comparing timestamps that are close together, as `DateTime.Now` and friends only update every 15ms or so.
One possible fix is to use a more fine-grained timer. `Stopwatch` has much better precision and should avoid having two successive timestamps being equal.

Fix flakey test

---

Directory.Packages.props
setup/Directory.Build.targets

These targets could cause issues during DTBs (The target "GetVsixSourceItems" does not exist in the project.) if the VSSDK wasn't restored.
Newer versions of the VSSDK implement the equivalent logic.
This change removes our explicit overrides. If we see any issues with the FUTDC after this we can work with the VSSDK team to address any gaps.

Remove VSSDK FUTDC overrides

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml

Related to https://github.com/NuGet/NuGet.Client/pull/6696. 
Used for inferring pruning defaults.

Add _RestorePackagePruningDefault to nomination

---

Directory.Packages.props

Reverts dotnet/project-system#9736
This change is causing issues with the insertion. Reverting for now.

Revert "Update Debugger.Contract"

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/HotReload/ProjectHotReloadSession.cs

We have updated WebProject to use the `StartSessionAsync` overload since it passes `DebugLaunchOptions` to CreateSession, but that value is not used yet.

Fixes default value for runningUnderDebugger

---

src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs

when it is initialized by another extension.
Basically, when external code accessess its dataflow block on UI thread and initialize the object, the lazy compuation would try to resume on UI thread, which leads performance/deadlock problems to appear.

Prevent launch settings provider to capture and depend on main thread

---

Directory.Packages.props
eng/imports/HostAgnostic.props
eng/imports/Workarounds.targets

Source Link is included in the SDK since NET 8.

Remove explicit SourceLink package refs

---

setup/ProjectSystemSetup/ProjectSystemSetup.csproj

Updated ngen priorities for our ongoing efforts to reduce the time it takes to ngen pri 1 assemblies. The following two assemblies are being changed to priority 2:
- common7\ide\extensions\microsoft\managedprojectsystem\microsoft.visualstudio.projectsystem.managed.vs.dll
- common7\ide\extensions\microsoft\managedprojectsystem\microsoft.visualstudio.projectsystem.managed.dll

Update Ngen priorities for VS
